// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstaibot.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the MyFirstAIBot module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_AttachedDocument_AddToChatContextBuilder(
		myfirstaibot.proxies.AttachedDocument _attachedDocument,
		conversationalui.proxies.ChatContext _chatContext
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstAIBot.ACT_AttachedDocument_AddToChatContext");
		builder = builder.withParam("AttachedDocument", _attachedDocument);
		builder = builder.withParam("ChatContext", _chatContext);
		return builder;
	}

	public static void aCT_AttachedDocument_AddToChatContext(
		IContext context,
		myfirstaibot.proxies.AttachedDocument _attachedDocument,
		conversationalui.proxies.ChatContext _chatContext
	)
	{
		aCT_AttachedDocument_AddToChatContextBuilder(
				_attachedDocument,
				_chatContext
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_AttachedDocument_DeleteBuilder(
		myfirstaibot.proxies.AttachedDocument _attachedDocument,
		conversationalui.proxies.ChatContext _chatContext
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstAIBot.ACT_AttachedDocument_Delete");
		builder = builder.withParam("AttachedDocument", _attachedDocument);
		builder = builder.withParam("ChatContext", _chatContext);
		return builder;
	}

	public static void aCT_AttachedDocument_Delete(
		IContext context,
		myfirstaibot.proxies.AttachedDocument _attachedDocument,
		conversationalui.proxies.ChatContext _chatContext
	)
	{
		aCT_AttachedDocument_DeleteBuilder(
				_attachedDocument,
				_chatContext
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_AttachedDocument_OpenUploadBuilder(
		conversationalui.proxies.ChatContext _chatContext
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstAIBot.ACT_AttachedDocument_OpenUpload");
		builder = builder.withParam("ChatContext", _chatContext);
		return builder;
	}

	public static void aCT_AttachedDocument_OpenUpload(
		IContext context,
		conversationalui.proxies.ChatContext _chatContext
	)
	{
		aCT_AttachedDocument_OpenUploadBuilder(
				_chatContext
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_BotConfig_CancelBuilder(
		myfirstaibot.proxies.BotConfig _botConfig
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstAIBot.ACT_BotConfig_Cancel");
		builder = builder.withParam("BotConfig", _botConfig);
		return builder;
	}

	public static void aCT_BotConfig_Cancel(
		IContext context,
		myfirstaibot.proxies.BotConfig _botConfig
	)
	{
		aCT_BotConfig_CancelBuilder(
				_botConfig
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_BotConfig_DeleteBuilder(
		myfirstaibot.proxies.BotConfig _botConfig
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstAIBot.ACT_BotConfig_Delete");
		builder = builder.withParam("BotConfig", _botConfig);
		return builder;
	}

	public static void aCT_BotConfig_Delete(
		IContext context,
		myfirstaibot.proxies.BotConfig _botConfig
	)
	{
		aCT_BotConfig_DeleteBuilder(
				_botConfig
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_BotConfig_MakeDefaultBuilder(
		myfirstaibot.proxies.BotConfig _botConfig
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstAIBot.ACT_BotConfig_MakeDefault");
		builder = builder.withParam("BotConfig", _botConfig);
		return builder;
	}

	public static void aCT_BotConfig_MakeDefault(
		IContext context,
		myfirstaibot.proxies.BotConfig _botConfig
	)
	{
		aCT_BotConfig_MakeDefaultBuilder(
				_botConfig
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_BotConfig_NewBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstAIBot.ACT_BotConfig_New");
		return builder;
	}

	public static void aCT_BotConfig_New(IContext context)
	{
		aCT_BotConfig_NewBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_BotConfig_SaveBuilder(
		myfirstaibot.proxies.BotConfig _botConfig
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstAIBot.ACT_BotConfig_Save");
		builder = builder.withParam("BotConfig", _botConfig);
		return builder;
	}

	public static void aCT_BotConfig_Save(
		IContext context,
		myfirstaibot.proxies.BotConfig _botConfig
	)
	{
		aCT_BotConfig_SaveBuilder(
				_botConfig
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_ChatContext_New_OpenChatBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstAIBot.ACT_ChatContext_New_OpenChat");
		return builder;
	}

	public static void aCT_ChatContext_New_OpenChat(IContext context)
	{
		aCT_ChatContext_New_OpenChatBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_ChatContext_OpenChatBuilder(
		conversationalui.proxies.ChatContext _chatContext
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstAIBot.ACT_ChatContext_OpenChat");
		builder = builder.withParam("ChatContext", _chatContext);
		return builder;
	}

	public static void aCT_ChatContext_OpenChat(
		IContext context,
		conversationalui.proxies.ChatContext _chatContext
	)
	{
		aCT_ChatContext_OpenChatBuilder(
				_chatContext
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_CustomKnowledgeBase_GetEmbeddingsAndStoreBuilder(
		myfirstaibot.proxies.BotConfig _botConfig,
		myfirstaibot.proxies.CustomKnowledgeBase _customKnowledgeBase
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstAIBot.ACT_CustomKnowledgeBase_GetEmbeddingsAndStore");
		builder = builder.withParam("BotConfig", _botConfig);
		builder = builder.withParam("CustomKnowledgeBase", _customKnowledgeBase);
		return builder;
	}

	public static void aCT_CustomKnowledgeBase_GetEmbeddingsAndStore(
		IContext context,
		myfirstaibot.proxies.BotConfig _botConfig,
		myfirstaibot.proxies.CustomKnowledgeBase _customKnowledgeBase
	)
	{
		aCT_CustomKnowledgeBase_GetEmbeddingsAndStoreBuilder(
				_botConfig,
				_customKnowledgeBase
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_DeployedKBRetrieval_AddBuilder(
		myfirstaibot.proxies.BotConfig _botConfig
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstAIBot.ACT_DeployedKBRetrieval_Add");
		builder = builder.withParam("BotConfig", _botConfig);
		return builder;
	}

	public static void aCT_DeployedKBRetrieval_Add(
		IContext context,
		myfirstaibot.proxies.BotConfig _botConfig
	)
	{
		aCT_DeployedKBRetrieval_AddBuilder(
				_botConfig
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_DeployedKBRetrieval_DeleteBuilder(
		myfirstaibot.proxies.DeployedKBRetrieval _deployedKBRetrieval
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstAIBot.ACT_DeployedKBRetrieval_Delete");
		builder = builder.withParam("DeployedKBRetrieval", _deployedKBRetrieval);
		return builder;
	}

	public static void aCT_DeployedKBRetrieval_Delete(
		IContext context,
		myfirstaibot.proxies.DeployedKBRetrieval _deployedKBRetrieval
	)
	{
		aCT_DeployedKBRetrieval_DeleteBuilder(
				_deployedKBRetrieval
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_DeployedKBRetrieval_SaveBuilder(
		myfirstaibot.proxies.DeployedKBRetrieval _deployedKBRetrieval
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstAIBot.ACT_DeployedKBRetrieval_Save");
		builder = builder.withParam("DeployedKBRetrieval", _deployedKBRetrieval);
		return builder;
	}

	public static void aCT_DeployedKBRetrieval_Save(
		IContext context,
		myfirstaibot.proxies.DeployedKBRetrieval _deployedKBRetrieval
	)
	{
		aCT_DeployedKBRetrieval_SaveBuilder(
				_deployedKBRetrieval
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_InitialUserPrompt_DeleteBuilder(
		myfirstaibot.proxies.InitialUserPrompt _initialUserPrompt
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstAIBot.ACT_InitialUserPrompt_Delete");
		builder = builder.withParam("InitialUserPrompt", _initialUserPrompt);
		return builder;
	}

	public static void aCT_InitialUserPrompt_Delete(
		IContext context,
		myfirstaibot.proxies.InitialUserPrompt _initialUserPrompt
	)
	{
		aCT_InitialUserPrompt_DeleteBuilder(
				_initialUserPrompt
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_InitialUserPrompt_NewBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstAIBot.ACT_InitialUserPrompt_New");
		return builder;
	}

	public static void aCT_InitialUserPrompt_New(IContext context)
	{
		aCT_InitialUserPrompt_NewBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_InitialUserPrompt_SaveBuilder(
		myfirstaibot.proxies.InitialUserPrompt _initialUserPrompt
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstAIBot.ACT_InitialUserPrompt_Save");
		builder = builder.withParam("InitialUserPrompt", _initialUserPrompt);
		return builder;
	}

	public static void aCT_InitialUserPrompt_Save(
		IContext context,
		myfirstaibot.proxies.InitialUserPrompt _initialUserPrompt
	)
	{
		aCT_InitialUserPrompt_SaveBuilder(
				_initialUserPrompt
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_InitialUserPrompt_SelectBuilder(
		conversationalui.proxies.ChatContext _chatContext,
		myfirstaibot.proxies.InitialUserPrompt _initialUserPrompt
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstAIBot.ACT_InitialUserPrompt_Select");
		builder = builder.withParam("ChatContext", _chatContext);
		builder = builder.withParam("InitialUserPrompt", _initialUserPrompt);
		return builder;
	}

	public static void aCT_InitialUserPrompt_Select(
		IContext context,
		conversationalui.proxies.ChatContext _chatContext,
		myfirstaibot.proxies.InitialUserPrompt _initialUserPrompt
	)
	{
		aCT_InitialUserPrompt_SelectBuilder(
				_chatContext,
				_initialUserPrompt
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Instruction_CancelBuilder(
		myfirstaibot.proxies.Instruction _instruction
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstAIBot.ACT_Instruction_Cancel");
		builder = builder.withParam("Instruction", _instruction);
		return builder;
	}

	public static void aCT_Instruction_Cancel(
		IContext context,
		myfirstaibot.proxies.Instruction _instruction
	)
	{
		aCT_Instruction_CancelBuilder(
				_instruction
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Instruction_DeleteBuilder(
		myfirstaibot.proxies.Instruction _instruction
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstAIBot.ACT_Instruction_Delete");
		builder = builder.withParam("Instruction", _instruction);
		return builder;
	}

	public static void aCT_Instruction_Delete(
		IContext context,
		myfirstaibot.proxies.Instruction _instruction
	)
	{
		aCT_Instruction_DeleteBuilder(
				_instruction
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Instruction_Delete_AdminBuilder(
		myfirstaibot.proxies.Instruction _instruction
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstAIBot.ACT_Instruction_Delete_Admin");
		builder = builder.withParam("Instruction", _instruction);
		return builder;
	}

	public static void aCT_Instruction_Delete_Admin(
		IContext context,
		myfirstaibot.proxies.Instruction _instruction
	)
	{
		aCT_Instruction_Delete_AdminBuilder(
				_instruction
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Instruction_NewBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstAIBot.ACT_Instruction_New");
		return builder;
	}

	public static void aCT_Instruction_New(IContext context)
	{
		aCT_Instruction_NewBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Instruction_NewCustomBuilder(
		myfirstaibot.proxies.ContextExtension _contextExtension
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstAIBot.ACT_Instruction_NewCustom");
		builder = builder.withParam("ContextExtension", _contextExtension);
		return builder;
	}

	public static void aCT_Instruction_NewCustom(
		IContext context,
		myfirstaibot.proxies.ContextExtension _contextExtension
	)
	{
		aCT_Instruction_NewCustomBuilder(
				_contextExtension
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Instruction_SaveBuilder(
		myfirstaibot.proxies.Instruction _instruction
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstAIBot.ACT_Instruction_Save");
		builder = builder.withParam("Instruction", _instruction);
		return builder;
	}

	public static void aCT_Instruction_Save(
		IContext context,
		myfirstaibot.proxies.Instruction _instruction
	)
	{
		aCT_Instruction_SaveBuilder(
				_instruction
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_New_KnowledgeBase_ItemBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstAIBot.ACT_New_KnowledgeBase_Item");
		return builder;
	}

	public static void aCT_New_KnowledgeBase_Item(IContext context)
	{
		aCT_New_KnowledgeBase_ItemBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder advancedSettings_GetAndUpdateBuilder(
		conversationalui.proxies.ChatContext _chatContext,
		java.math.BigDecimal _temperatureMin,
		java.math.BigDecimal _temperatureMax
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstAIBot.AdvancedSettings_GetAndUpdate");
		builder = builder.withParam("ChatContext", _chatContext);
		builder = builder.withParam("TemperatureMin", _temperatureMin);
		builder = builder.withParam("TemperatureMax", _temperatureMax);
		return builder;
	}

	public static conversationalui.proxies.AdvancedSettings advancedSettings_GetAndUpdate(
		IContext context,
		conversationalui.proxies.ChatContext _chatContext,
		java.math.BigDecimal _temperatureMin,
		java.math.BigDecimal _temperatureMax
	)
	{
		Object result = advancedSettings_GetAndUpdateBuilder(
				_chatContext,
				_temperatureMin,
				_temperatureMax
			)
			.execute(context);
		return result == null ? null : conversationalui.proxies.AdvancedSettings.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aSU_AfterStartupBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstAIBot.ASU_AfterStartup");
		return builder;
	}

	public static boolean aSU_AfterStartup(IContext context)
	{
		Object result = aSU_AfterStartupBuilder().execute(context);
		return (boolean) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aSU_Instruction_InitialUserPrompt_CreateListBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstAIBot.ASU_Instruction_InitialUserPrompt_CreateList");
		return builder;
	}

	public static void aSU_Instruction_InitialUserPrompt_CreateList(IContext context)
	{
		aSU_Instruction_InitialUserPrompt_CreateListBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aSU_Settings_SyncBedrockBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstAIBot.ASU_Settings_SyncBedrock");
		return builder;
	}

	public static void aSU_Settings_SyncBedrock(IContext context)
	{
		aSU_Settings_SyncBedrockBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder attachedDocument_AddToChatContextBuilder(
		conversationalui.proxies.ChatContext _chatContext,
		myfirstaibot.proxies.AttachedDocument _attachedDocument
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstAIBot.AttachedDocument_AddToChatContext");
		builder = builder.withParam("ChatContext", _chatContext);
		builder = builder.withParam("AttachedDocument", _attachedDocument);
		return builder;
	}

	public static void attachedDocument_AddToChatContext(
		IContext context,
		conversationalui.proxies.ChatContext _chatContext,
		myfirstaibot.proxies.AttachedDocument _attachedDocument
	)
	{
		attachedDocument_AddToChatContextBuilder(
				_chatContext,
				_attachedDocument
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder attachedDocument_AddToCurrentMessage_CommitBuilder(
		java.util.List<myfirstaibot.proxies.AttachedDocument> _attachedDocumentList,
		conversationalui.proxies.ChatContext _chatContext
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstAIBot.AttachedDocument_AddToCurrentMessage_Commit");
		builder = builder.withParam("AttachedDocumentList", _attachedDocumentList);
		builder = builder.withParam("ChatContext", _chatContext);
		return builder;
	}

	public static void attachedDocument_AddToCurrentMessage_Commit(
		IContext context,
		java.util.List<myfirstaibot.proxies.AttachedDocument> _attachedDocumentList,
		conversationalui.proxies.ChatContext _chatContext
	)
	{
		attachedDocument_AddToCurrentMessage_CommitBuilder(
				_attachedDocumentList,
				_chatContext
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder attachedDocument_CommitBuilder(
		myfirstaibot.proxies.AttachedDocument _attachedDocument
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstAIBot.AttachedDocument_Commit");
		builder = builder.withParam("AttachedDocument", _attachedDocument);
		return builder;
	}

	public static void attachedDocument_Commit(
		IContext context,
		myfirstaibot.proxies.AttachedDocument _attachedDocument
	)
	{
		attachedDocument_CommitBuilder(
				_attachedDocument
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder attachedDocument_CommitListBuilder(
		java.util.List<myfirstaibot.proxies.AttachedDocument> _attachedDocumentList
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstAIBot.AttachedDocument_CommitList");
		builder = builder.withParam("AttachedDocumentList", _attachedDocumentList);
		return builder;
	}

	public static void attachedDocument_CommitList(
		IContext context,
		java.util.List<myfirstaibot.proxies.AttachedDocument> _attachedDocumentList
	)
	{
		attachedDocument_CommitListBuilder(
				_attachedDocumentList
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder attachedDocument_CreateBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstAIBot.AttachedDocument_Create");
		return builder;
	}

	public static myfirstaibot.proxies.AttachedDocument attachedDocument_Create(IContext context)
	{
		Object result = attachedDocument_CreateBuilder().execute(context);
		return result == null ? null : myfirstaibot.proxies.AttachedDocument.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder attachedDocument_DeleteBuilder(
		myfirstaibot.proxies.AttachedDocument _attachedDocument
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstAIBot.AttachedDocument_Delete");
		builder = builder.withParam("AttachedDocument", _attachedDocument);
		return builder;
	}

	public static void attachedDocument_Delete(
		IContext context,
		myfirstaibot.proxies.AttachedDocument _attachedDocument
	)
	{
		attachedDocument_DeleteBuilder(
				_attachedDocument
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder attachedDocument_GetContentBuilder(
		myfirstaibot.proxies.AttachedDocument _attachedDocument
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstAIBot.AttachedDocument_GetContent");
		builder = builder.withParam("AttachedDocument", _attachedDocument);
		return builder;
	}

	public static pdfextraction.proxies.PDFContent attachedDocument_GetContent(
		IContext context,
		myfirstaibot.proxies.AttachedDocument _attachedDocument
	)
	{
		Object result = attachedDocument_GetContentBuilder(
				_attachedDocument
			)
			.execute(context);
		return result == null ? null : pdfextraction.proxies.PDFContent.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder attachedDocument_GetFirstBuilder(
		conversationalui.proxies.ChatContext _chatContext
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstAIBot.AttachedDocument_GetFirst");
		builder = builder.withParam("ChatContext", _chatContext);
		return builder;
	}

	public static myfirstaibot.proxies.AttachedDocument attachedDocument_GetFirst(
		IContext context,
		conversationalui.proxies.ChatContext _chatContext
	)
	{
		Object result = attachedDocument_GetFirstBuilder(
				_chatContext
			)
			.execute(context);
		return result == null ? null : myfirstaibot.proxies.AttachedDocument.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder attachedDocument_GetListBuilder(
		conversationalui.proxies.ChatContext _chatContext
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstAIBot.AttachedDocument_GetList");
		builder = builder.withParam("ChatContext", _chatContext);
		return builder;
	}

	public static java.util.List<myfirstaibot.proxies.AttachedDocument> attachedDocument_GetList(
		IContext context,
		conversationalui.proxies.ChatContext _chatContext
	)
	{
		Object result = attachedDocument_GetListBuilder(
				_chatContext
			)
			.execute(context);
		return result == null ? null : com.mendix.utils.ListUtils.map((java.util.List<IMendixObject>) result, obj -> myfirstaibot.proxies.AttachedDocument.initialize(context, obj));
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder attachedDocument_IsSinglePDFModelBuilder(
		genaicommons.proxies.DeployedModel _deployedModel
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstAIBot.AttachedDocument_IsSinglePDFModel");
		builder = builder.withParam("DeployedModel", _deployedModel);
		return builder;
	}

	public static boolean attachedDocument_IsSinglePDFModel(
		IContext context,
		genaicommons.proxies.DeployedModel _deployedModel
	)
	{
		Object result = attachedDocument_IsSinglePDFModelBuilder(
				_deployedModel
			)
			.execute(context);
		return (boolean) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder attachedDocument_RemoveOld_IfNeededBuilder(
		myfirstaibot.proxies.BotConfig _botConfig,
		conversationalui.proxies.ChatContext _chatContext,
		myfirstaibot.proxies.AttachedDocument _attachedDocument
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstAIBot.AttachedDocument_RemoveOld_IfNeeded");
		builder = builder.withParam("BotConfig", _botConfig);
		builder = builder.withParam("ChatContext", _chatContext);
		builder = builder.withParam("AttachedDocument", _attachedDocument);
		return builder;
	}

	public static void attachedDocument_RemoveOld_IfNeeded(
		IContext context,
		myfirstaibot.proxies.BotConfig _botConfig,
		conversationalui.proxies.ChatContext _chatContext,
		myfirstaibot.proxies.AttachedDocument _attachedDocument
	)
	{
		attachedDocument_RemoveOld_IfNeededBuilder(
				_botConfig,
				_chatContext,
				_attachedDocument
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder attachedDocument_ValidateBuilder(
		myfirstaibot.proxies.AttachedDocument _attachedDocument,
		myfirstaibot.proxies.BotConfig _botConfig,
		conversationalui.proxies.ChatContext _chatContext
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstAIBot.AttachedDocument_Validate");
		builder = builder.withParam("AttachedDocument", _attachedDocument);
		builder = builder.withParam("BotConfig", _botConfig);
		builder = builder.withParam("ChatContext", _chatContext);
		return builder;
	}

	public static boolean attachedDocument_Validate(
		IContext context,
		myfirstaibot.proxies.AttachedDocument _attachedDocument,
		myfirstaibot.proxies.BotConfig _botConfig,
		conversationalui.proxies.ChatContext _chatContext
	)
	{
		Object result = attachedDocument_ValidateBuilder(
				_attachedDocument,
				_botConfig,
				_chatContext
			)
			.execute(context);
		return (boolean) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder botConfig_CastBuilder(
		conversationalui.proxies.ProviderConfig _providerConfig
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstAIBot.BotConfig_Cast");
		builder = builder.withParam("ProviderConfig", _providerConfig);
		return builder;
	}

	public static myfirstaibot.proxies.BotConfig botConfig_Cast(
		IContext context,
		conversationalui.proxies.ProviderConfig _providerConfig
	)
	{
		Object result = botConfig_CastBuilder(
				_providerConfig
			)
			.execute(context);
		return result == null ? null : myfirstaibot.proxies.BotConfig.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder botConfig_CommitBuilder(
		myfirstaibot.proxies.BotConfig _botConfig
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstAIBot.BotConfig_Commit");
		builder = builder.withParam("BotConfig", _botConfig);
		return builder;
	}

	public static void botConfig_Commit(
		IContext context,
		myfirstaibot.proxies.BotConfig _botConfig
	)
	{
		botConfig_CommitBuilder(
				_botConfig
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder botConfig_CommitListBuilder(
		java.util.List<myfirstaibot.proxies.BotConfig> _botConfigList
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstAIBot.BotConfig_CommitList");
		builder = builder.withParam("BotConfigList", _botConfigList);
		return builder;
	}

	public static void botConfig_CommitList(
		IContext context,
		java.util.List<myfirstaibot.proxies.BotConfig> _botConfigList
	)
	{
		botConfig_CommitListBuilder(
				_botConfigList
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder botConfig_CreateBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstAIBot.BotConfig_Create");
		return builder;
	}

	public static myfirstaibot.proxies.BotConfig botConfig_Create(IContext context)
	{
		Object result = botConfig_CreateBuilder().execute(context);
		return result == null ? null : myfirstaibot.proxies.BotConfig.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder botConfig_DeleteBuilder(
		myfirstaibot.proxies.BotConfig _botConfig
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstAIBot.BotConfig_Delete");
		builder = builder.withParam("BotConfig", _botConfig);
		return builder;
	}

	public static void botConfig_Delete(
		IContext context,
		myfirstaibot.proxies.BotConfig _botConfig
	)
	{
		botConfig_DeleteBuilder(
				_botConfig
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder botConfig_GetDefaultBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstAIBot.BotConfig_GetDefault");
		return builder;
	}

	public static myfirstaibot.proxies.BotConfig botConfig_GetDefault(IContext context)
	{
		Object result = botConfig_GetDefaultBuilder().execute(context);
		return result == null ? null : myfirstaibot.proxies.BotConfig.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder botConfig_GetSelectableListBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstAIBot.BotConfig_GetSelectableList");
		return builder;
	}

	public static java.util.List<myfirstaibot.proxies.BotConfig> botConfig_GetSelectableList(IContext context)
	{
		Object result = botConfig_GetSelectableListBuilder().execute(context);
		return result == null ? null : com.mendix.utils.ListUtils.map((java.util.List<IMendixObject>) result, obj -> myfirstaibot.proxies.BotConfig.initialize(context, obj));
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder botConfig_MakeDefaultBuilder(
		myfirstaibot.proxies.BotConfig _botConfigNewDefault
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstAIBot.BotConfig_MakeDefault");
		builder = builder.withParam("BotConfigNewDefault", _botConfigNewDefault);
		return builder;
	}

	public static void botConfig_MakeDefault(
		IContext context,
		myfirstaibot.proxies.BotConfig _botConfigNewDefault
	)
	{
		botConfig_MakeDefaultBuilder(
				_botConfigNewDefault
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder botConfig_RollbackWithAssociationsBuilder(
		myfirstaibot.proxies.BotConfig _botConfig
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstAIBot.BotConfig_RollbackWithAssociations");
		builder = builder.withParam("BotConfig", _botConfig);
		return builder;
	}

	public static void botConfig_RollbackWithAssociations(
		IContext context,
		myfirstaibot.proxies.BotConfig _botConfig
	)
	{
		botConfig_RollbackWithAssociationsBuilder(
				_botConfig
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder botConfig_SetActionMicroflowBuilder(
		myfirstaibot.proxies.BotConfig _botConfig
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstAIBot.BotConfig_SetActionMicroflow");
		builder = builder.withParam("BotConfig", _botConfig);
		return builder;
	}

	public static void botConfig_SetActionMicroflow(
		IContext context,
		myfirstaibot.proxies.BotConfig _botConfig
	)
	{
		botConfig_SetActionMicroflowBuilder(
				_botConfig
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder botConfig_UpdateHasKnowledgeBaseBuilder(
		myfirstaibot.proxies.BotConfig _botConfig
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstAIBot.BotConfig_UpdateHasKnowledgeBase");
		builder = builder.withParam("BotConfig", _botConfig);
		return builder;
	}

	public static void botConfig_UpdateHasKnowledgeBase(
		IContext context,
		myfirstaibot.proxies.BotConfig _botConfig
	)
	{
		botConfig_UpdateHasKnowledgeBaseBuilder(
				_botConfig
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder botConfig_ValidateBuilder(
		myfirstaibot.proxies.BotConfig _botConfig
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstAIBot.BotConfig_Validate");
		builder = builder.withParam("BotConfig", _botConfig);
		return builder;
	}

	public static boolean botConfig_Validate(
		IContext context,
		myfirstaibot.proxies.BotConfig _botConfig
	)
	{
		Object result = botConfig_ValidateBuilder(
				_botConfig
			)
			.execute(context);
		return (boolean) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder botConfig_Validate_AWSCredentialsBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstAIBot.BotConfig_Validate_AWSCredentials");
		return builder;
	}

	public static boolean botConfig_Validate_AWSCredentials(IContext context)
	{
		Object result = botConfig_Validate_AWSCredentialsBuilder().execute(context);
		return (boolean) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder botConfig_Validate_Microflow_SpecificBuilder(
		myfirstaibot.proxies.BotConfig _botConfig
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstAIBot.BotConfig_Validate_Microflow_Specific");
		builder = builder.withParam("BotConfig", _botConfig);
		return builder;
	}

	public static boolean botConfig_Validate_Microflow_Specific(
		IContext context,
		myfirstaibot.proxies.BotConfig _botConfig
	)
	{
		Object result = botConfig_Validate_Microflow_SpecificBuilder(
				_botConfig
			)
			.execute(context);
		return (boolean) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder botConfig_Validate_ModelArchitectureBuilder(
		myfirstaibot.proxies.BotConfig _botConfig
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstAIBot.BotConfig_Validate_ModelArchitecture");
		builder = builder.withParam("BotConfig", _botConfig);
		return builder;
	}

	public static boolean botConfig_Validate_ModelArchitecture(
		IContext context,
		myfirstaibot.proxies.BotConfig _botConfig
	)
	{
		Object result = botConfig_Validate_ModelArchitectureBuilder(
				_botConfig
			)
			.execute(context);
		return (boolean) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder botConfig_Validate_ProviderSpecificBuilder(
		myfirstaibot.proxies.BotConfig _botConfig
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstAIBot.BotConfig_Validate_ProviderSpecific");
		builder = builder.withParam("BotConfig", _botConfig);
		return builder;
	}

	public static boolean botConfig_Validate_ProviderSpecific(
		IContext context,
		myfirstaibot.proxies.BotConfig _botConfig
	)
	{
		Object result = botConfig_Validate_ProviderSpecificBuilder(
				_botConfig
			)
			.execute(context);
		return (boolean) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder botConfig_ValidateActionMicroflowBuilder(
		myfirstaibot.proxies.BotConfig _botConfig
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstAIBot.BotConfig_ValidateActionMicroflow");
		builder = builder.withParam("BotConfig", _botConfig);
		return builder;
	}

	public static boolean botConfig_ValidateActionMicroflow(
		IContext context,
		myfirstaibot.proxies.BotConfig _botConfig
	)
	{
		Object result = botConfig_ValidateActionMicroflowBuilder(
				_botConfig
			)
			.execute(context);
		return (boolean) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder chatContext_BedrockRetrieveAndGenerate_ActionMicroflowBuilder(
		conversationalui.proxies.ChatContext _chatContext
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstAIBot.ChatContext_BedrockRetrieveAndGenerate_ActionMicroflow");
		builder = builder.withParam("ChatContext", _chatContext);
		return builder;
	}

	public static boolean chatContext_BedrockRetrieveAndGenerate_ActionMicroflow(
		IContext context,
		conversationalui.proxies.ChatContext _chatContext
	)
	{
		Object result = chatContext_BedrockRetrieveAndGenerate_ActionMicroflowBuilder(
				_chatContext
			)
			.execute(context);
		return (boolean) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder chatContext_ChatWithHistory_ActionMicroflowBuilder(
		conversationalui.proxies.ChatContext _chatContext
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstAIBot.ChatContext_ChatWithHistory_ActionMicroflow");
		builder = builder.withParam("ChatContext", _chatContext);
		return builder;
	}

	public static boolean chatContext_ChatWithHistory_ActionMicroflow(
		IContext context,
		conversationalui.proxies.ChatContext _chatContext
	)
	{
		Object result = chatContext_ChatWithHistory_ActionMicroflowBuilder(
				_chatContext
			)
			.execute(context);
		return (boolean) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder chatContext_CreateBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstAIBot.ChatContext_Create");
		return builder;
	}

	public static conversationalui.proxies.ChatContext chatContext_Create(IContext context)
	{
		Object result = chatContext_CreateBuilder().execute(context);
		return result == null ? null : conversationalui.proxies.ChatContext.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder chatContext_GetActiveBotConfigBuilder(
		conversationalui.proxies.ChatContext _chatContext
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstAIBot.ChatContext_GetActiveBotConfig");
		builder = builder.withParam("ChatContext", _chatContext);
		return builder;
	}

	public static myfirstaibot.proxies.BotConfig chatContext_GetActiveBotConfig(
		IContext context,
		conversationalui.proxies.ChatContext _chatContext
	)
	{
		Object result = chatContext_GetActiveBotConfigBuilder(
				_chatContext
			)
			.execute(context);
		return result == null ? null : myfirstaibot.proxies.BotConfig.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder chatContext_GetPDFContentBuilder(
		conversationalui.proxies.ChatContext _chatContext
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstAIBot.ChatContext_GetPDFContent");
		builder = builder.withParam("ChatContext", _chatContext);
		return builder;
	}

	public static pdfextraction.proxies.PDFContent chatContext_GetPDFContent(
		IContext context,
		conversationalui.proxies.ChatContext _chatContext
	)
	{
		Object result = chatContext_GetPDFContentBuilder(
				_chatContext
			)
			.execute(context);
		return result == null ? null : pdfextraction.proxies.PDFContent.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder chatContext_GetSystemPromptBuilder(
		conversationalui.proxies.ChatContext _chatContext
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstAIBot.ChatContext_GetSystemPrompt");
		builder = builder.withParam("ChatContext", _chatContext);
		return builder;
	}

	public static java.lang.String chatContext_GetSystemPrompt(
		IContext context,
		conversationalui.proxies.ChatContext _chatContext
	)
	{
		Object result = chatContext_GetSystemPromptBuilder(
				_chatContext
			)
			.execute(context);
		return (java.lang.String) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder chatContext_RemoveOldBotconfigsBuilder(
		conversationalui.proxies.ChatContext _chatContext
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstAIBot.ChatContext_RemoveOldBotconfigs");
		builder = builder.withParam("ChatContext", _chatContext);
		return builder;
	}

	public static void chatContext_RemoveOldBotconfigs(
		IContext context,
		conversationalui.proxies.ChatContext _chatContext
	)
	{
		chatContext_RemoveOldBotconfigsBuilder(
				_chatContext
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder chatContext_UpdateWithInitialUserPromptBuilder(
		conversationalui.proxies.ChatContext _chatContext,
		myfirstaibot.proxies.InitialUserPrompt _initialUserPrompt
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstAIBot.ChatContext_UpdateWithInitialUserPrompt");
		builder = builder.withParam("ChatContext", _chatContext);
		builder = builder.withParam("InitialUserPrompt", _initialUserPrompt);
		return builder;
	}

	public static void chatContext_UpdateWithInitialUserPrompt(
		IContext context,
		conversationalui.proxies.ChatContext _chatContext,
		myfirstaibot.proxies.InitialUserPrompt _initialUserPrompt
	)
	{
		chatContext_UpdateWithInitialUserPromptBuilder(
				_chatContext,
				_initialUserPrompt
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder chunkCollection_Embed_InsertBuilder(
		genaicommons.proxies.DeployedModel _deployedModel_Embeddings,
		genaicommons.proxies.ChunkCollection _chunkCollection,
		genaicommons.proxies.DeployedKnowledgeBase _deployedKnowledgeBase
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstAIBot.ChunkCollection_Embed_Insert");
		builder = builder.withParam("DeployedModel_Embeddings", _deployedModel_Embeddings);
		builder = builder.withParam("ChunkCollection", _chunkCollection);
		builder = builder.withParam("DeployedKnowledgeBase", _deployedKnowledgeBase);
		return builder;
	}

	public static boolean chunkCollection_Embed_Insert(
		IContext context,
		genaicommons.proxies.DeployedModel _deployedModel_Embeddings,
		genaicommons.proxies.ChunkCollection _chunkCollection,
		genaicommons.proxies.DeployedKnowledgeBase _deployedKnowledgeBase
	)
	{
		Object result = chunkCollection_Embed_InsertBuilder(
				_deployedModel_Embeddings,
				_chunkCollection,
				_deployedKnowledgeBase
			)
			.execute(context);
		return (boolean) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder chunkCollection_Embed_ReplaceBuilder(
		genaicommons.proxies.DeployedModel _deployedModel_Embeddings,
		genaicommons.proxies.ChunkCollection _chunkCollection,
		genaicommons.proxies.DeployedKnowledgeBase _deployedKnowledgeBase
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstAIBot.ChunkCollection_Embed_Replace");
		builder = builder.withParam("DeployedModel_Embeddings", _deployedModel_Embeddings);
		builder = builder.withParam("ChunkCollection", _chunkCollection);
		builder = builder.withParam("DeployedKnowledgeBase", _deployedKnowledgeBase);
		return builder;
	}

	public static boolean chunkCollection_Embed_Replace(
		IContext context,
		genaicommons.proxies.DeployedModel _deployedModel_Embeddings,
		genaicommons.proxies.ChunkCollection _chunkCollection,
		genaicommons.proxies.DeployedKnowledgeBase _deployedKnowledgeBase
	)
	{
		Object result = chunkCollection_Embed_ReplaceBuilder(
				_deployedModel_Embeddings,
				_chunkCollection,
				_deployedKnowledgeBase
			)
			.execute(context);
		return (boolean) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder chunkCollection_Embed_RepopulateKnowledgeBaseBuilder(
		genaicommons.proxies.ChunkCollection _chunkCollection,
		genaicommons.proxies.DeployedKnowledgeBase _deployedKnowledgeBase,
		genaicommons.proxies.DeployedModel _deployedModel_Embeddings
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstAIBot.ChunkCollection_Embed_RepopulateKnowledgeBase");
		builder = builder.withParam("ChunkCollection", _chunkCollection);
		builder = builder.withParam("DeployedKnowledgeBase", _deployedKnowledgeBase);
		builder = builder.withParam("DeployedModel_Embeddings", _deployedModel_Embeddings);
		return builder;
	}

	public static boolean chunkCollection_Embed_RepopulateKnowledgeBase(
		IContext context,
		genaicommons.proxies.ChunkCollection _chunkCollection,
		genaicommons.proxies.DeployedKnowledgeBase _deployedKnowledgeBase,
		genaicommons.proxies.DeployedModel _deployedModel_Embeddings
	)
	{
		Object result = chunkCollection_Embed_RepopulateKnowledgeBaseBuilder(
				_chunkCollection,
				_deployedKnowledgeBase,
				_deployedModel_Embeddings
			)
			.execute(context);
		return (boolean) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder configurationSelection_DeployedKnowledgeBase_KnowledgeBaseBuilder(
		myfirstaibot.proxies.BotConfig _botConfig
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstAIBot.ConfigurationSelection_DeployedKnowledgeBase_KnowledgeBase");
		builder = builder.withParam("BotConfig", _botConfig);
		return builder;
	}

	public static genaicommons.proxies.DeployedKnowledgeBase configurationSelection_DeployedKnowledgeBase_KnowledgeBase(
		IContext context,
		myfirstaibot.proxies.BotConfig _botConfig
	)
	{
		Object result = configurationSelection_DeployedKnowledgeBase_KnowledgeBaseBuilder(
				_botConfig
			)
			.execute(context);
		return result == null ? null : genaicommons.proxies.DeployedKnowledgeBase.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder contextExtension_CommitBuilder(
		myfirstaibot.proxies.ContextExtension _contextExtension
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstAIBot.ContextExtension_Commit");
		builder = builder.withParam("ContextExtension", _contextExtension);
		return builder;
	}

	public static void contextExtension_Commit(
		IContext context,
		myfirstaibot.proxies.ContextExtension _contextExtension
	)
	{
		contextExtension_CommitBuilder(
				_contextExtension
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder contextExtension_GetCreateBuilder(
		conversationalui.proxies.ChatContext _chatContext
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstAIBot.ContextExtension_GetCreate");
		builder = builder.withParam("ChatContext", _chatContext);
		return builder;
	}

	public static myfirstaibot.proxies.ContextExtension contextExtension_GetCreate(
		IContext context,
		conversationalui.proxies.ChatContext _chatContext
	)
	{
		Object result = contextExtension_GetCreateBuilder(
				_chatContext
			)
			.execute(context);
		return result == null ? null : myfirstaibot.proxies.ContextExtension.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder contextExtension_RemoveInstructionBuilder(
		myfirstaibot.proxies.Instruction _instruction
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstAIBot.ContextExtension_RemoveInstruction");
		builder = builder.withParam("Instruction", _instruction);
		return builder;
	}

	public static void contextExtension_RemoveInstruction(
		IContext context,
		myfirstaibot.proxies.Instruction _instruction
	)
	{
		contextExtension_RemoveInstructionBuilder(
				_instruction
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder contextExtension_SetInstructionBuilder(
		myfirstaibot.proxies.Instruction _instruction,
		myfirstaibot.proxies.ContextExtension _contextExtension
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstAIBot.ContextExtension_SetInstruction");
		builder = builder.withParam("Instruction", _instruction);
		builder = builder.withParam("ContextExtension", _contextExtension);
		return builder;
	}

	public static void contextExtension_SetInstruction(
		IContext context,
		myfirstaibot.proxies.Instruction _instruction,
		myfirstaibot.proxies.ContextExtension _contextExtension
	)
	{
		contextExtension_SetInstructionBuilder(
				_instruction,
				_contextExtension
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder contextExtension_SetTemperatureBuilder(
		myfirstaibot.proxies.ContextExtension _contextExtension
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstAIBot.ContextExtension_SetTemperature");
		builder = builder.withParam("ContextExtension", _contextExtension);
		return builder;
	}

	public static void contextExtension_SetTemperature(
		IContext context,
		myfirstaibot.proxies.ContextExtension _contextExtension
	)
	{
		contextExtension_SetTemperatureBuilder(
				_contextExtension
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder contextExtension_UpdateBuilder(
		conversationalui.proxies.ChatContext _chatContext
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstAIBot.ContextExtension_Update");
		builder = builder.withParam("ChatContext", _chatContext);
		return builder;
	}

	public static void contextExtension_Update(
		IContext context,
		conversationalui.proxies.ChatContext _chatContext
	)
	{
		contextExtension_UpdateBuilder(
				_chatContext
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder deployedKBRetrieval_CommitWithBotConfigBuilder(
		myfirstaibot.proxies.BotConfig _botConfig,
		myfirstaibot.proxies.DeployedKBRetrieval _deployedKBRetrieval
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstAIBot.DeployedKBRetrieval_CommitWithBotConfig");
		builder = builder.withParam("BotConfig", _botConfig);
		builder = builder.withParam("DeployedKBRetrieval", _deployedKBRetrieval);
		return builder;
	}

	public static void deployedKBRetrieval_CommitWithBotConfig(
		IContext context,
		myfirstaibot.proxies.BotConfig _botConfig,
		myfirstaibot.proxies.DeployedKBRetrieval _deployedKBRetrieval
	)
	{
		deployedKBRetrieval_CommitWithBotConfigBuilder(
				_botConfig,
				_deployedKBRetrieval
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder deployedKBRetrieval_CreateBuilder(
		myfirstaibot.proxies.BotConfig _botConfig
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstAIBot.DeployedKBRetrieval_Create");
		builder = builder.withParam("BotConfig", _botConfig);
		return builder;
	}

	public static myfirstaibot.proxies.DeployedKBRetrieval deployedKBRetrieval_Create(
		IContext context,
		myfirstaibot.proxies.BotConfig _botConfig
	)
	{
		Object result = deployedKBRetrieval_CreateBuilder(
				_botConfig
			)
			.execute(context);
		return result == null ? null : myfirstaibot.proxies.DeployedKBRetrieval.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder deployedKBRetrieval_DeleteBuilder(
		myfirstaibot.proxies.DeployedKBRetrieval _deployedKBRetrieval
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstAIBot.DeployedKBRetrieval_Delete");
		builder = builder.withParam("DeployedKBRetrieval", _deployedKBRetrieval);
		return builder;
	}

	public static void deployedKBRetrieval_Delete(
		IContext context,
		myfirstaibot.proxies.DeployedKBRetrieval _deployedKBRetrieval
	)
	{
		deployedKBRetrieval_DeleteBuilder(
				_deployedKBRetrieval
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder deployedKBRetrieval_ValidateBuilder(
		myfirstaibot.proxies.DeployedKBRetrieval _deployedKBRetrieval
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstAIBot.DeployedKBRetrieval_Validate");
		builder = builder.withParam("DeployedKBRetrieval", _deployedKBRetrieval);
		return builder;
	}

	public static boolean deployedKBRetrieval_Validate(
		IContext context,
		myfirstaibot.proxies.DeployedKBRetrieval _deployedKBRetrieval
	)
	{
		Object result = deployedKBRetrieval_ValidateBuilder(
				_deployedKBRetrieval
			)
			.execute(context);
		return (boolean) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder documentDisplay_GetAndUpdateBuilder(
		conversationalui.proxies.ChatContext _chatContext
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstAIBot.DocumentDisplay_GetAndUpdate");
		builder = builder.withParam("ChatContext", _chatContext);
		return builder;
	}

	public static void documentDisplay_GetAndUpdate(
		IContext context,
		conversationalui.proxies.ChatContext _chatContext
	)
	{
		documentDisplay_GetAndUpdateBuilder(
				_chatContext
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder documentDisplay_GetOrCreateBuilder(
		conversationalui.proxies.ChatContext _chatContext
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstAIBot.DocumentDisplay_GetOrCreate");
		builder = builder.withParam("ChatContext", _chatContext);
		return builder;
	}

	public static myfirstaibot.proxies.DocumentDisplay documentDisplay_GetOrCreate(
		IContext context,
		conversationalui.proxies.ChatContext _chatContext
	)
	{
		Object result = documentDisplay_GetOrCreateBuilder(
				_chatContext
			)
			.execute(context);
		return result == null ? null : myfirstaibot.proxies.DocumentDisplay.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder documentDisplay_UpdateBuilder(
		java.util.List<myfirstaibot.proxies.AttachedDocument> _attachedDocumentList,
		myfirstaibot.proxies.DocumentDisplay _documentDisplay,
		conversationalui.proxies.ChatContext _chatContext
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstAIBot.DocumentDisplay_Update");
		builder = builder.withParam("AttachedDocumentList", _attachedDocumentList);
		builder = builder.withParam("DocumentDisplay", _documentDisplay);
		builder = builder.withParam("ChatContext", _chatContext);
		return builder;
	}

	public static void documentDisplay_Update(
		IContext context,
		java.util.List<myfirstaibot.proxies.AttachedDocument> _attachedDocumentList,
		myfirstaibot.proxies.DocumentDisplay _documentDisplay,
		conversationalui.proxies.ChatContext _chatContext
	)
	{
		documentDisplay_UpdateBuilder(
				_attachedDocumentList,
				_documentDisplay,
				_chatContext
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_AmazonBedrockKnowledgeBaseBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstAIBot.DS_AmazonBedrockKnowledgeBase");
		return builder;
	}

	public static java.util.List<amazonbedrockconnector.proxies.AmazonBedrockKnowledgeBase> dS_AmazonBedrockKnowledgeBase(IContext context)
	{
		Object result = dS_AmazonBedrockKnowledgeBaseBuilder().execute(context);
		return result == null ? null : com.mendix.utils.ListUtils.map((java.util.List<IMendixObject>) result, obj -> amazonbedrockconnector.proxies.AmazonBedrockKnowledgeBase.initialize(context, obj));
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_ChatContext_GetDocumentDisplayBuilder(
		conversationalui.proxies.ChatContext _chatContext
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstAIBot.DS_ChatContext_GetDocumentDisplay");
		builder = builder.withParam("ChatContext", _chatContext);
		return builder;
	}

	public static myfirstaibot.proxies.DocumentDisplay dS_ChatContext_GetDocumentDisplay(
		IContext context,
		conversationalui.proxies.ChatContext _chatContext
	)
	{
		Object result = dS_ChatContext_GetDocumentDisplayBuilder(
				_chatContext
			)
			.execute(context);
		return result == null ? null : myfirstaibot.proxies.DocumentDisplay.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_ContextExtension_GetOrCreateBuilder(
		conversationalui.proxies.ChatContext _chatContext
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstAIBot.DS_ContextExtension_GetOrCreate");
		builder = builder.withParam("ChatContext", _chatContext);
		return builder;
	}

	public static myfirstaibot.proxies.ContextExtension dS_ContextExtension_GetOrCreate(
		IContext context,
		conversationalui.proxies.ChatContext _chatContext
	)
	{
		Object result = dS_ContextExtension_GetOrCreateBuilder(
				_chatContext
			)
			.execute(context);
		return result == null ? null : myfirstaibot.proxies.ContextExtension.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_DocumentDisplay_GetAttachedDocumentListBuilder(
		myfirstaibot.proxies.DocumentDisplay _documentDisplay
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstAIBot.DS_DocumentDisplay_GetAttachedDocumentList");
		builder = builder.withParam("DocumentDisplay", _documentDisplay);
		return builder;
	}

	public static java.util.List<myfirstaibot.proxies.AttachedDocument> dS_DocumentDisplay_GetAttachedDocumentList(
		IContext context,
		myfirstaibot.proxies.DocumentDisplay _documentDisplay
	)
	{
		Object result = dS_DocumentDisplay_GetAttachedDocumentListBuilder(
				_documentDisplay
			)
			.execute(context);
		return result == null ? null : com.mendix.utils.ListUtils.map((java.util.List<IMendixObject>) result, obj -> myfirstaibot.proxies.AttachedDocument.initialize(context, obj));
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder initialUserPrompt_CommitBuilder(
		myfirstaibot.proxies.InitialUserPrompt _initialUserPrompt
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstAIBot.InitialUserPrompt_Commit");
		builder = builder.withParam("InitialUserPrompt", _initialUserPrompt);
		return builder;
	}

	public static void initialUserPrompt_Commit(
		IContext context,
		myfirstaibot.proxies.InitialUserPrompt _initialUserPrompt
	)
	{
		initialUserPrompt_CommitBuilder(
				_initialUserPrompt
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder initialUserPrompt_CommitListBuilder(
		java.util.List<myfirstaibot.proxies.InitialUserPrompt> _initialUserPromptList
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstAIBot.InitialUserPrompt_CommitList");
		builder = builder.withParam("InitialUserPromptList", _initialUserPromptList);
		return builder;
	}

	public static void initialUserPrompt_CommitList(
		IContext context,
		java.util.List<myfirstaibot.proxies.InitialUserPrompt> _initialUserPromptList
	)
	{
		initialUserPrompt_CommitListBuilder(
				_initialUserPromptList
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder initialUserPrompt_CreateBuilder(
		myfirstaibot.proxies.Instruction _instruction,
		java.lang.String _header,
		myfirstaibot.proxies.ENUM_InitialUserPromptCategory _category,
		java.lang.String _userPrompt,
		java.lang.Long _order
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstAIBot.InitialUserPrompt_Create");
		builder = builder.withParam("Instruction", _instruction);
		builder = builder.withParam("Header", _header);
		builder = builder.withParam("Category", _category == null ? null : _category.name());
		builder = builder.withParam("UserPrompt", _userPrompt);
		builder = builder.withParam("Order", _order);
		return builder;
	}

	public static myfirstaibot.proxies.InitialUserPrompt initialUserPrompt_Create(
		IContext context,
		myfirstaibot.proxies.Instruction _instruction,
		java.lang.String _header,
		myfirstaibot.proxies.ENUM_InitialUserPromptCategory _category,
		java.lang.String _userPrompt,
		java.lang.Long _order
	)
	{
		Object result = initialUserPrompt_CreateBuilder(
				_instruction,
				_header,
				_category,
				_userPrompt,
				_order
			)
			.execute(context);
		return result == null ? null : myfirstaibot.proxies.InitialUserPrompt.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder initialUserPrompt_CreateAndAddToListBuilder(
		java.util.List<myfirstaibot.proxies.InitialUserPrompt> _initialUserPromptList,
		myfirstaibot.proxies.Instruction _instruction,
		java.lang.String _header,
		myfirstaibot.proxies.ENUM_InitialUserPromptCategory _category,
		java.lang.String _userPrompt,
		java.lang.Long _order
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstAIBot.InitialUserPrompt_CreateAndAddToList");
		builder = builder.withParam("InitialUserPromptList", _initialUserPromptList);
		builder = builder.withParam("Instruction", _instruction);
		builder = builder.withParam("Header", _header);
		builder = builder.withParam("Category", _category == null ? null : _category.name());
		builder = builder.withParam("UserPrompt", _userPrompt);
		builder = builder.withParam("Order", _order);
		return builder;
	}

	public static void initialUserPrompt_CreateAndAddToList(
		IContext context,
		java.util.List<myfirstaibot.proxies.InitialUserPrompt> _initialUserPromptList,
		myfirstaibot.proxies.Instruction _instruction,
		java.lang.String _header,
		myfirstaibot.proxies.ENUM_InitialUserPromptCategory _category,
		java.lang.String _userPrompt,
		java.lang.Long _order
	)
	{
		initialUserPrompt_CreateAndAddToListBuilder(
				_initialUserPromptList,
				_instruction,
				_header,
				_category,
				_userPrompt,
				_order
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder initialUserPrompt_DeleteBuilder(
		myfirstaibot.proxies.InitialUserPrompt _initialUserPrompt
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstAIBot.InitialUserPrompt_Delete");
		builder = builder.withParam("InitialUserPrompt", _initialUserPrompt);
		return builder;
	}

	public static void initialUserPrompt_Delete(
		IContext context,
		myfirstaibot.proxies.InitialUserPrompt _initialUserPrompt
	)
	{
		initialUserPrompt_DeleteBuilder(
				_initialUserPrompt
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder initialUserPrompt_ValidateBuilder(
		myfirstaibot.proxies.InitialUserPrompt _initialUserPrompt
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstAIBot.InitialUserPrompt_Validate");
		builder = builder.withParam("InitialUserPrompt", _initialUserPrompt);
		return builder;
	}

	public static boolean initialUserPrompt_Validate(
		IContext context,
		myfirstaibot.proxies.InitialUserPrompt _initialUserPrompt
	)
	{
		Object result = initialUserPrompt_ValidateBuilder(
				_initialUserPrompt
			)
			.execute(context);
		return (boolean) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder instruction_CommitBuilder(
		myfirstaibot.proxies.Instruction _instruction
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstAIBot.Instruction_Commit");
		builder = builder.withParam("Instruction", _instruction);
		return builder;
	}

	public static void instruction_Commit(
		IContext context,
		myfirstaibot.proxies.Instruction _instruction
	)
	{
		instruction_CommitBuilder(
				_instruction
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder instruction_Commit_IfCustomAndChangedBuilder(
		myfirstaibot.proxies.Instruction _instruction
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstAIBot.Instruction_Commit_IfCustomAndChanged");
		builder = builder.withParam("Instruction", _instruction);
		return builder;
	}

	public static void instruction_Commit_IfCustomAndChanged(
		IContext context,
		myfirstaibot.proxies.Instruction _instruction
	)
	{
		instruction_Commit_IfCustomAndChangedBuilder(
				_instruction
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder instruction_CommitListBuilder(
		java.util.List<myfirstaibot.proxies.Instruction> _instructionList
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstAIBot.Instruction_CommitList");
		builder = builder.withParam("InstructionList", _instructionList);
		return builder;
	}

	public static void instruction_CommitList(
		IContext context,
		java.util.List<myfirstaibot.proxies.Instruction> _instructionList
	)
	{
		instruction_CommitListBuilder(
				_instructionList
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder instruction_CreateBuilder(
		java.lang.String _instruction,
		java.lang.String _displayName,
		boolean _isCustom
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstAIBot.Instruction_Create");
		builder = builder.withParam("Instruction", _instruction);
		builder = builder.withParam("DisplayName", _displayName);
		builder = builder.withParam("IsCustom", _isCustom);
		return builder;
	}

	public static myfirstaibot.proxies.Instruction instruction_Create(
		IContext context,
		java.lang.String _instruction,
		java.lang.String _displayName,
		boolean _isCustom
	)
	{
		Object result = instruction_CreateBuilder(
				_instruction,
				_displayName,
				_isCustom
			)
			.execute(context);
		return result == null ? null : myfirstaibot.proxies.Instruction.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder instruction_CreateAndAddToListBuilder(
		java.util.List<myfirstaibot.proxies.Instruction> _instructionList,
		java.lang.String _displayName,
		java.lang.String _instruction
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstAIBot.Instruction_CreateAndAddToList");
		builder = builder.withParam("InstructionList", _instructionList);
		builder = builder.withParam("DisplayName", _displayName);
		builder = builder.withParam("Instruction", _instruction);
		return builder;
	}

	public static myfirstaibot.proxies.Instruction instruction_CreateAndAddToList(
		IContext context,
		java.util.List<myfirstaibot.proxies.Instruction> _instructionList,
		java.lang.String _displayName,
		java.lang.String _instruction
	)
	{
		Object result = instruction_CreateAndAddToListBuilder(
				_instructionList,
				_displayName,
				_instruction
			)
			.execute(context);
		return result == null ? null : myfirstaibot.proxies.Instruction.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder instruction_DeleteBuilder(
		myfirstaibot.proxies.Instruction _instruction
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstAIBot.Instruction_Delete");
		builder = builder.withParam("Instruction", _instruction);
		return builder;
	}

	public static void instruction_Delete(
		IContext context,
		myfirstaibot.proxies.Instruction _instruction
	)
	{
		instruction_DeleteBuilder(
				_instruction
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder instruction_ValidateBuilder(
		myfirstaibot.proxies.Instruction _instruction
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstAIBot.Instruction_Validate");
		builder = builder.withParam("Instruction", _instruction);
		return builder;
	}

	public static boolean instruction_Validate(
		IContext context,
		myfirstaibot.proxies.Instruction _instruction
	)
	{
		Object result = instruction_ValidateBuilder(
				_instruction
			)
			.execute(context);
		return (boolean) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder knowledgeBase_ChunkCollection_CreateKnowledgebaseChunksBuilder(
		myfirstaibot.proxies.CustomKnowledgeBase _knowledgeBaseItem,
		genaicommons.proxies.ChunkCollection _chunkCollection
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstAIBot.KnowledgeBase_ChunkCollection_CreateKnowledgebaseChunks");
		builder = builder.withParam("KnowledgeBaseItem", _knowledgeBaseItem);
		builder = builder.withParam("ChunkCollection", _chunkCollection);
		return builder;
	}

	public static void knowledgeBase_ChunkCollection_CreateKnowledgebaseChunks(
		IContext context,
		myfirstaibot.proxies.CustomKnowledgeBase _knowledgeBaseItem,
		genaicommons.proxies.ChunkCollection _chunkCollection
	)
	{
		knowledgeBase_ChunkCollection_CreateKnowledgebaseChunksBuilder(
				_knowledgeBaseItem,
				_chunkCollection
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder knowledgeBaseUpdate_GetCreateBuilder(
		myfirstaibot.proxies.BotConfig _botConfig
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstAIBot.KnowledgeBaseUpdate_GetCreate");
		builder = builder.withParam("BotConfig", _botConfig);
		return builder;
	}

	public static myfirstaibot.proxies.KnowledgeBaseUpdate knowledgeBaseUpdate_GetCreate(
		IContext context,
		myfirstaibot.proxies.BotConfig _botConfig
	)
	{
		Object result = knowledgeBaseUpdate_GetCreateBuilder(
				_botConfig
			)
			.execute(context);
		return result == null ? null : myfirstaibot.proxies.KnowledgeBaseUpdate.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder knowledgeBaseUpdate_UpdateBuilder(
		myfirstaibot.proxies.BotConfig _botConfig
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstAIBot.KnowledgeBaseUpdate_Update");
		builder = builder.withParam("BotConfig", _botConfig);
		return builder;
	}

	public static void knowledgeBaseUpdate_Update(
		IContext context,
		myfirstaibot.proxies.BotConfig _botConfig
	)
	{
		knowledgeBaseUpdate_UpdateBuilder(
				_botConfig
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder message_AddAttachedDocumentBuilder(
		genaicommons.proxies.Message _message,
		myfirstaibot.proxies.AttachedDocument _attachedDocument
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstAIBot.Message_AddAttachedDocument");
		builder = builder.withParam("Message", _message);
		builder = builder.withParam("AttachedDocument", _attachedDocument);
		return builder;
	}

	public static void message_AddAttachedDocument(
		IContext context,
		genaicommons.proxies.Message _message,
		myfirstaibot.proxies.AttachedDocument _attachedDocument
	)
	{
		message_AddAttachedDocumentBuilder(
				_message,
				_attachedDocument
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder nAV_TokenMonitorBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstAIBot.NAV_TokenMonitor");
		return builder;
	}

	public static void nAV_TokenMonitor(IContext context)
	{
		nAV_TokenMonitorBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder oCh_ChatContext_RefreshBuilder(
		conversationalui.proxies.ChatContext _chatContext
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstAIBot.OCh_ChatContext_Refresh");
		builder = builder.withParam("ChatContext", _chatContext);
		return builder;
	}

	public static void oCh_ChatContext_Refresh(
		IContext context,
		conversationalui.proxies.ChatContext _chatContext
	)
	{
		oCh_ChatContext_RefreshBuilder(
				_chatContext
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder oCh_Instruction_SaveBuilder(
		myfirstaibot.proxies.Instruction _instruction
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstAIBot.OCh_Instruction_Save");
		builder = builder.withParam("Instruction", _instruction);
		return builder;
	}

	public static void oCh_Instruction_Save(
		IContext context,
		myfirstaibot.proxies.Instruction _instruction
	)
	{
		oCh_Instruction_SaveBuilder(
				_instruction
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder request_AddDocumentsToMessageBuilder(
		conversationalui.proxies.ChatContext _chatContext,
		genaicommons.proxies.Request _request
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstAIBot.Request_AddDocumentsToMessage");
		builder = builder.withParam("ChatContext", _chatContext);
		builder = builder.withParam("Request", _request);
		return builder;
	}

	public static void request_AddDocumentsToMessage(
		IContext context,
		conversationalui.proxies.ChatContext _chatContext,
		genaicommons.proxies.Request _request
	)
	{
		request_AddDocumentsToMessageBuilder(
				_chatContext,
				_request
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder request_AddKnowledgeBaseToolsBuilder(
		genaicommons.proxies.Request _request,
		myfirstaibot.proxies.BotConfig _botConfig
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstAIBot.Request_AddKnowledgeBaseTools");
		builder = builder.withParam("Request", _request);
		builder = builder.withParam("BotConfig", _botConfig);
		return builder;
	}

	public static void request_AddKnowledgeBaseTools(
		IContext context,
		genaicommons.proxies.Request _request,
		myfirstaibot.proxies.BotConfig _botConfig
	)
	{
		request_AddKnowledgeBaseToolsBuilder(
				_request,
				_botConfig
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder request_ApplyInstructions_MapAttachedDocumentsBuilder(
		genaicommons.proxies.Request _request,
		conversationalui.proxies.ChatContext _chatContext
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstAIBot.Request_ApplyInstructions_MapAttachedDocuments");
		builder = builder.withParam("Request", _request);
		builder = builder.withParam("ChatContext", _chatContext);
		return builder;
	}

	public static void request_ApplyInstructions_MapAttachedDocuments(
		IContext context,
		genaicommons.proxies.Request _request,
		conversationalui.proxies.ChatContext _chatContext
	)
	{
		request_ApplyInstructions_MapAttachedDocumentsBuilder(
				_request,
				_chatContext
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sUB_Get_BotConfigurationBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstAIBot.SUB_Get_BotConfiguration");
		return builder;
	}

	public static void sUB_Get_BotConfiguration(IContext context)
	{
		sUB_Get_BotConfigurationBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sUB_Get_DeployedKnowledgeBase_Or_CreateBuilder(
		myfirstaibot.proxies.BotConfig _botConfig
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstAIBot.SUB_Get_DeployedKnowledgeBase_Or_Create");
		builder = builder.withParam("BotConfig", _botConfig);
		return builder;
	}

	public static void sUB_Get_DeployedKnowledgeBase_Or_Create(
		IContext context,
		myfirstaibot.proxies.BotConfig _botConfig
	)
	{
		sUB_Get_DeployedKnowledgeBase_Or_CreateBuilder(
				_botConfig
			)
			.execute(context);
	}
}
