// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package awsauthentication.proxies.constants;

import com.mendix.core.Core;

public final class Constants
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Constants() {}

	// These are the constants for the AWSAuthentication module

	public static java.lang.String getAccessKey()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("AWSAuthentication.AccessKey");
	}

	public static java.lang.String getClientCertificateID()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("AWSAuthentication.ClientCertificateID");
	}

	public static java.lang.Long getDuration()
	{
		return (java.lang.Long)Core.getConfiguration().getConstantValue("AWSAuthentication.Duration");
	}

	public static java.lang.String getProfileARN()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("AWSAuthentication.ProfileARN");
	}

	public static java.lang.String getRoleARN()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("AWSAuthentication.RoleARN");
	}

	public static java.lang.String getSecretAccessKey()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("AWSAuthentication.SecretAccessKey");
	}

	public static java.lang.String getSessionName()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("AWSAuthentication.SessionName");
	}

	public static java.lang.String getTrustAnchorARN()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("AWSAuthentication.TrustAnchorARN");
	}
}