// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package feedbackmodule.proxies;

public enum TranslationLanguages
{
	Dutch("e963a1ec-8e62-4270-8918-596a5e6228f2"),
	English("f7205fd4-9322-43a8-b2d2-f86eaf2f5b89"),
	French("a9bbb3d4-ee07-4633-b1ce-35de117c4ecf"),
	German("936a41b0-e810-4909-b4f1-eb305e8e52d4"),
	Hindi("013e7e58-4d06-4c88-89d8-d58b713f22c7"),
	Portuguese("93bb6e6e-3874-4055-a756-67c867fe099c"),
	Spanish("c9409c9c-ee16-4a9e-baba-091bd65123bc"),
	Turkish("ca037d28-59bc-4f05-827b-bc9359056fd4");

	private final java.lang.String i18nCaptionKey;
	
	private TranslationLanguages(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
