// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package openaiconnector.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the OpenAIConnector module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_AzureAISearchConfiguration_SaveBuilder(
		openaiconnector.proxies.AzureAISearchResource _azureAISearchResource
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpenAIConnector.ACT_AzureAISearchConfiguration_Save");
		builder = builder.withParam("AzureAISearchResource", _azureAISearchResource);
		return builder;
	}

	public static void aCT_AzureAISearchConfiguration_Save(
		IContext context,
		openaiconnector.proxies.AzureAISearchResource _azureAISearchResource
	)
	{
		aCT_AzureAISearchConfiguration_SaveBuilder(
				_azureAISearchResource
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_AzureAISearchResource_DeleteBuilder(
		openaiconnector.proxies.AzureAISearchResource _azureAISearchResource
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpenAIConnector.ACT_AzureAISearchResource_Delete");
		builder = builder.withParam("AzureAISearchResource", _azureAISearchResource);
		return builder;
	}

	public static void aCT_AzureAISearchResource_Delete(
		IContext context,
		openaiconnector.proxies.AzureAISearchResource _azureAISearchResource
	)
	{
		aCT_AzureAISearchResource_DeleteBuilder(
				_azureAISearchResource
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_AzureAISearchResource_EditBuilder(
		openaiconnector.proxies.AzureAISearchResource _azureAISearchResource
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpenAIConnector.ACT_AzureAISearchResource_Edit");
		builder = builder.withParam("AzureAISearchResource", _azureAISearchResource);
		return builder;
	}

	public static void aCT_AzureAISearchResource_Edit(
		IContext context,
		openaiconnector.proxies.AzureAISearchResource _azureAISearchResource
	)
	{
		aCT_AzureAISearchResource_EditBuilder(
				_azureAISearchResource
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_AzureAISearchResource_NewBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpenAIConnector.ACT_AzureAISearchResource_New");
		return builder;
	}

	public static void aCT_AzureAISearchResource_New(IContext context)
	{
		aCT_AzureAISearchResource_NewBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Configuration_AddDefaultOpenAIModelsBuilder(
		openaiconnector.proxies.Configuration _configuration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpenAIConnector.ACT_Configuration_AddDefaultOpenAIModels");
		builder = builder.withParam("Configuration", _configuration);
		return builder;
	}

	public static void aCT_Configuration_AddDefaultOpenAIModels(
		IContext context,
		openaiconnector.proxies.Configuration _configuration
	)
	{
		aCT_Configuration_AddDefaultOpenAIModelsBuilder(
				_configuration
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Configuration_DeleteBuilder(
		openaiconnector.proxies.Configuration _configuration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpenAIConnector.ACT_Configuration_Delete");
		builder = builder.withParam("Configuration", _configuration);
		return builder;
	}

	public static void aCT_Configuration_Delete(
		IContext context,
		openaiconnector.proxies.Configuration _configuration
	)
	{
		aCT_Configuration_DeleteBuilder(
				_configuration
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Configuration_DuplicateBuilder(
		openaiconnector.proxies.Configuration _configuration_Existing
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpenAIConnector.ACT_Configuration_Duplicate");
		builder = builder.withParam("Configuration_Existing", _configuration_Existing);
		return builder;
	}

	public static void aCT_Configuration_Duplicate(
		IContext context,
		openaiconnector.proxies.Configuration _configuration_Existing
	)
	{
		aCT_Configuration_DuplicateBuilder(
				_configuration_Existing
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Configuration_EditBuilder(
		openaiconnector.proxies.Configuration _configuration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpenAIConnector.ACT_Configuration_Edit");
		builder = builder.withParam("Configuration", _configuration);
		return builder;
	}

	public static void aCT_Configuration_Edit(
		IContext context,
		openaiconnector.proxies.Configuration _configuration
	)
	{
		aCT_Configuration_EditBuilder(
				_configuration
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Configuration_ExecuteTestBuilder(
		openaiconnector.proxies.ConfigurationTest _configurationTest
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpenAIConnector.ACT_Configuration_ExecuteTest");
		builder = builder.withParam("ConfigurationTest", _configurationTest);
		return builder;
	}

	public static void aCT_Configuration_ExecuteTest(
		IContext context,
		openaiconnector.proxies.ConfigurationTest _configurationTest
	)
	{
		aCT_Configuration_ExecuteTestBuilder(
				_configurationTest
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Configuration_ManageDeployedModelsBuilder(
		openaiconnector.proxies.Configuration _configuration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpenAIConnector.ACT_Configuration_ManageDeployedModels");
		builder = builder.withParam("Configuration", _configuration);
		return builder;
	}

	public static void aCT_Configuration_ManageDeployedModels(
		IContext context,
		openaiconnector.proxies.Configuration _configuration
	)
	{
		aCT_Configuration_ManageDeployedModelsBuilder(
				_configuration
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Configuration_NewBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpenAIConnector.ACT_Configuration_New");
		return builder;
	}

	public static void aCT_Configuration_New(IContext context)
	{
		aCT_Configuration_NewBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Configuration_SaveBuilder(
		openaiconnector.proxies.Configuration _configuration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpenAIConnector.ACT_Configuration_Save");
		builder = builder.withParam("Configuration", _configuration);
		return builder;
	}

	public static void aCT_Configuration_Save(
		IContext context,
		openaiconnector.proxies.Configuration _configuration
	)
	{
		aCT_Configuration_SaveBuilder(
				_configuration
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Configuration_ShowTestBuilder(
		openaiconnector.proxies.Configuration _configuration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpenAIConnector.ACT_Configuration_ShowTest");
		builder = builder.withParam("Configuration", _configuration);
		return builder;
	}

	public static void aCT_Configuration_ShowTest(
		IContext context,
		openaiconnector.proxies.Configuration _configuration
	)
	{
		aCT_Configuration_ShowTestBuilder(
				_configuration
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Index_DeleteBuilder(
		openaiconnector.proxies.Index _index
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpenAIConnector.ACT_Index_Delete");
		builder = builder.withParam("Index", _index);
		return builder;
	}

	public static void aCT_Index_Delete(
		IContext context,
		openaiconnector.proxies.Index _index
	)
	{
		aCT_Index_DeleteBuilder(
				_index
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Index_SaveBuilder(
		openaiconnector.proxies.Index _index
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpenAIConnector.ACT_Index_Save");
		builder = builder.withParam("Index", _index);
		return builder;
	}

	public static void aCT_Index_Save(
		IContext context,
		openaiconnector.proxies.Index _index
	)
	{
		aCT_Index_SaveBuilder(
				_index
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_OpenAIDeployedModel_DeleteBuilder(
		openaiconnector.proxies.OpenAIDeployedModel _openAIDeployedModel
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpenAIConnector.ACT_OpenAIDeployedModel_Delete");
		builder = builder.withParam("OpenAIDeployedModel", _openAIDeployedModel);
		return builder;
	}

	public static void aCT_OpenAIDeployedModel_Delete(
		IContext context,
		openaiconnector.proxies.OpenAIDeployedModel _openAIDeployedModel
	)
	{
		aCT_OpenAIDeployedModel_DeleteBuilder(
				_openAIDeployedModel
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_OpenAIDeployedModel_EditBuilder(
		openaiconnector.proxies.OpenAIDeployedModel _openAIDeployedModel
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpenAIConnector.ACT_OpenAIDeployedModel_Edit");
		builder = builder.withParam("OpenAIDeployedModel", _openAIDeployedModel);
		return builder;
	}

	public static void aCT_OpenAIDeployedModel_Edit(
		IContext context,
		openaiconnector.proxies.OpenAIDeployedModel _openAIDeployedModel
	)
	{
		aCT_OpenAIDeployedModel_EditBuilder(
				_openAIDeployedModel
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_OpenAIDeployedModel_NewBuilder(
		openaiconnector.proxies.Configuration _configuration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpenAIConnector.ACT_OpenAIDeployedModel_New");
		builder = builder.withParam("Configuration", _configuration);
		return builder;
	}

	public static void aCT_OpenAIDeployedModel_New(
		IContext context,
		openaiconnector.proxies.Configuration _configuration
	)
	{
		aCT_OpenAIDeployedModel_NewBuilder(
				_configuration
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_OpenAIDeployedModel_SaveBuilder(
		openaiconnector.proxies.OpenAIDeployedModel _openAIDeployedModel
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpenAIConnector.ACT_OpenAIDeployedModel_Save");
		builder = builder.withParam("OpenAIDeployedModel", _openAIDeployedModel);
		return builder;
	}

	public static void aCT_OpenAIDeployedModel_Save(
		IContext context,
		openaiconnector.proxies.OpenAIDeployedModel _openAIDeployedModel
	)
	{
		aCT_OpenAIDeployedModel_SaveBuilder(
				_openAIDeployedModel
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder apiKey_GetCreate_AzureAISearchResourceBuilder(
		openaiconnector.proxies.AzureAISearchResource _azureAISearchResource
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpenAIConnector.ApiKey_GetCreate_AzureAISearchResource");
		builder = builder.withParam("AzureAISearchResource", _azureAISearchResource);
		return builder;
	}

	public static openaiconnector.proxies.ApiKey apiKey_GetCreate_AzureAISearchResource(
		IContext context,
		openaiconnector.proxies.AzureAISearchResource _azureAISearchResource
	)
	{
		Object result = apiKey_GetCreate_AzureAISearchResourceBuilder(
				_azureAISearchResource
			)
			.execute(context);
		return result == null ? null : openaiconnector.proxies.ApiKey.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder apiKey_GetCreate_ConfigurationBuilder(
		openaiconnector.proxies.Configuration _configuration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpenAIConnector.ApiKey_GetCreate_Configuration");
		builder = builder.withParam("Configuration", _configuration);
		return builder;
	}

	public static openaiconnector.proxies.ApiKey apiKey_GetCreate_Configuration(
		IContext context,
		openaiconnector.proxies.Configuration _configuration
	)
	{
		Object result = apiKey_GetCreate_ConfigurationBuilder(
				_configuration
			)
			.execute(context);
		return result == null ? null : openaiconnector.proxies.ApiKey.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder azureAISearchResource_CommitBuilder(
		openaiconnector.proxies.AzureAISearchResource _azureAISearchResource
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpenAIConnector.AzureAISearchResource_Commit");
		builder = builder.withParam("AzureAISearchResource", _azureAISearchResource);
		return builder;
	}

	public static void azureAISearchResource_Commit(
		IContext context,
		openaiconnector.proxies.AzureAISearchResource _azureAISearchResource
	)
	{
		azureAISearchResource_CommitBuilder(
				_azureAISearchResource
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder azureAISearchResource_CreateBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpenAIConnector.AzureAISearchResource_Create");
		return builder;
	}

	public static openaiconnector.proxies.AzureAISearchResource azureAISearchResource_Create(IContext context)
	{
		Object result = azureAISearchResource_CreateBuilder().execute(context);
		return result == null ? null : openaiconnector.proxies.AzureAISearchResource.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder azureAISearchResource_DeleteBuilder(
		openaiconnector.proxies.AzureAISearchResource _azureAISearchResource
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpenAIConnector.AzureAISearchResource_Delete");
		builder = builder.withParam("AzureAISearchResource", _azureAISearchResource);
		return builder;
	}

	public static void azureAISearchResource_Delete(
		IContext context,
		openaiconnector.proxies.AzureAISearchResource _azureAISearchResource
	)
	{
		azureAISearchResource_DeleteBuilder(
				_azureAISearchResource
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder azureAISearchResource_SaveBuilder(
		openaiconnector.proxies.AzureAISearchResource _azureAISearchResource
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpenAIConnector.AzureAISearchResource_Save");
		builder = builder.withParam("AzureAISearchResource", _azureAISearchResource);
		return builder;
	}

	public static boolean azureAISearchResource_Save(
		IContext context,
		openaiconnector.proxies.AzureAISearchResource _azureAISearchResource
	)
	{
		Object result = azureAISearchResource_SaveBuilder(
				_azureAISearchResource
			)
			.execute(context);
		return (boolean) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder azureAISearchResource_SetApiKeyBuilder(
		openaiconnector.proxies.AzureAISearchResource _azureAISearchResource
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpenAIConnector.AzureAISearchResource_SetApiKey");
		builder = builder.withParam("AzureAISearchResource", _azureAISearchResource);
		return builder;
	}

	public static void azureAISearchResource_SetApiKey(
		IContext context,
		openaiconnector.proxies.AzureAISearchResource _azureAISearchResource
	)
	{
		azureAISearchResource_SetApiKeyBuilder(
				_azureAISearchResource
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder azureAISearchResource_ValidateBuilder(
		openaiconnector.proxies.AzureAISearchResource _azureAISearchResource
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpenAIConnector.AzureAISearchResource_Validate");
		builder = builder.withParam("AzureAISearchResource", _azureAISearchResource);
		return builder;
	}

	public static boolean azureAISearchResource_Validate(
		IContext context,
		openaiconnector.proxies.AzureAISearchResource _azureAISearchResource
	)
	{
		Object result = azureAISearchResource_ValidateBuilder(
				_azureAISearchResource
			)
			.execute(context);
		return (boolean) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder chatCompletions_WithHistory_ExecuteBuilder(
		genaicommons.proxies.Request _request,
		genaicommons.proxies.DeployedModel _deployedModel
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpenAIConnector.ChatCompletions_WithHistory_Execute");
		builder = builder.withParam("Request", _request);
		builder = builder.withParam("DeployedModel", _deployedModel);
		return builder;
	}

	public static genaicommons.proxies.Response chatCompletions_WithHistory_Execute(
		IContext context,
		genaicommons.proxies.Request _request,
		genaicommons.proxies.DeployedModel _deployedModel
	)
	{
		Object result = chatCompletions_WithHistory_ExecuteBuilder(
				_request,
				_deployedModel
			)
			.execute(context);
		return result == null ? null : genaicommons.proxies.Response.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder configuration_CommitBuilder(
		openaiconnector.proxies.Configuration _configuration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpenAIConnector.Configuration_Commit");
		builder = builder.withParam("Configuration", _configuration);
		return builder;
	}

	public static void configuration_Commit(
		IContext context,
		openaiconnector.proxies.Configuration _configuration
	)
	{
		configuration_CommitBuilder(
				_configuration
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder configuration_CreateBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpenAIConnector.Configuration_Create");
		return builder;
	}

	public static openaiconnector.proxies.Configuration configuration_Create(IContext context)
	{
		Object result = configuration_CreateBuilder().execute(context);
		return result == null ? null : openaiconnector.proxies.Configuration.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder configuration_CreateAndCopyValuesBuilder(
		openaiconnector.proxies.Configuration _configuration_Existing
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpenAIConnector.Configuration_CreateAndCopyValues");
		builder = builder.withParam("Configuration_Existing", _configuration_Existing);
		return builder;
	}

	public static openaiconnector.proxies.Configuration configuration_CreateAndCopyValues(
		IContext context,
		openaiconnector.proxies.Configuration _configuration_Existing
	)
	{
		Object result = configuration_CreateAndCopyValuesBuilder(
				_configuration_Existing
			)
			.execute(context);
		return result == null ? null : openaiconnector.proxies.Configuration.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder configuration_CreateDefaultDeployedModels_OpenAIBuilder(
		openaiconnector.proxies.Configuration _configuration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpenAIConnector.Configuration_CreateDefaultDeployedModels_OpenAI");
		builder = builder.withParam("Configuration", _configuration);
		return builder;
	}

	public static void configuration_CreateDefaultDeployedModels_OpenAI(
		IContext context,
		openaiconnector.proxies.Configuration _configuration
	)
	{
		configuration_CreateDefaultDeployedModels_OpenAIBuilder(
				_configuration
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder configuration_DeleteBuilder(
		openaiconnector.proxies.Configuration _configuration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpenAIConnector.Configuration_Delete");
		builder = builder.withParam("Configuration", _configuration);
		return builder;
	}

	public static void configuration_Delete(
		IContext context,
		openaiconnector.proxies.Configuration _configuration
	)
	{
		configuration_DeleteBuilder(
				_configuration
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder configuration_SaveBuilder(
		openaiconnector.proxies.Configuration _configuration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpenAIConnector.Configuration_Save");
		builder = builder.withParam("Configuration", _configuration);
		return builder;
	}

	public static boolean configuration_Save(
		IContext context,
		openaiconnector.proxies.Configuration _configuration
	)
	{
		Object result = configuration_SaveBuilder(
				_configuration
			)
			.execute(context);
		return (boolean) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder configuration_SetApiKeyBuilder(
		openaiconnector.proxies.Configuration _configuration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpenAIConnector.Configuration_SetApiKey");
		builder = builder.withParam("Configuration", _configuration);
		return builder;
	}

	public static void configuration_SetApiKey(
		IContext context,
		openaiconnector.proxies.Configuration _configuration
	)
	{
		configuration_SetApiKeyBuilder(
				_configuration
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder configuration_ValidateBuilder(
		openaiconnector.proxies.Configuration _configuration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpenAIConnector.Configuration_Validate");
		builder = builder.withParam("Configuration", _configuration);
		return builder;
	}

	public static boolean configuration_Validate(
		IContext context,
		openaiconnector.proxies.Configuration _configuration
	)
	{
		Object result = configuration_ValidateBuilder(
				_configuration
			)
			.execute(context);
		return (boolean) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder configuration_ValidateGenericBuilder(
		openaiconnector.proxies.Configuration _configuration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpenAIConnector.Configuration_ValidateGeneric");
		builder = builder.withParam("Configuration", _configuration);
		return builder;
	}

	public static boolean configuration_ValidateGeneric(
		IContext context,
		openaiconnector.proxies.Configuration _configuration
	)
	{
		Object result = configuration_ValidateGenericBuilder(
				_configuration
			)
			.execute(context);
		return (boolean) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder configurationTest_CreateBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpenAIConnector.ConfigurationTest_Create");
		return builder;
	}

	public static openaiconnector.proxies.ConfigurationTest configurationTest_Create(IContext context)
	{
		Object result = configurationTest_CreateBuilder().execute(context);
		return result == null ? null : openaiconnector.proxies.ConfigurationTest.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder configurationTest_ExecuteTestBuilder(
		openaiconnector.proxies.ConfigurationTest _configurationTest
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpenAIConnector.ConfigurationTest_ExecuteTest");
		builder = builder.withParam("ConfigurationTest", _configurationTest);
		return builder;
	}

	public static void configurationTest_ExecuteTest(
		IContext context,
		openaiconnector.proxies.ConfigurationTest _configurationTest
	)
	{
		configurationTest_ExecuteTestBuilder(
				_configurationTest
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder configurationTest_ValidateBuilder(
		openaiconnector.proxies.ConfigurationTest _configurationTest
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpenAIConnector.ConfigurationTest_Validate");
		builder = builder.withParam("ConfigurationTest", _configurationTest);
		return builder;
	}

	public static boolean configurationTest_Validate(
		IContext context,
		openaiconnector.proxies.ConfigurationTest _configurationTest
	)
	{
		Object result = configurationTest_ValidateBuilder(
				_configurationTest
			)
			.execute(context);
		return (boolean) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder deployedKnowledgeBase_CastBuilder(
		genaicommons.proxies.DeployedKnowledgeBase _deployedKnowledgeBase
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpenAIConnector.DeployedKnowledgeBase_Cast");
		builder = builder.withParam("DeployedKnowledgeBase", _deployedKnowledgeBase);
		return builder;
	}

	public static openaiconnector.proxies.Index deployedKnowledgeBase_Cast(
		IContext context,
		genaicommons.proxies.DeployedKnowledgeBase _deployedKnowledgeBase
	)
	{
		Object result = deployedKnowledgeBase_CastBuilder(
				_deployedKnowledgeBase
			)
			.execute(context);
		return result == null ? null : openaiconnector.proxies.Index.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder deployedModel_GetOpenAIDeployedModelBuilder(
		genaicommons.proxies.DeployedModel _deployedModel
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpenAIConnector.DeployedModel_GetOpenAIDeployedModel");
		builder = builder.withParam("DeployedModel", _deployedModel);
		return builder;
	}

	public static openaiconnector.proxies.OpenAIDeployedModel deployedModel_GetOpenAIDeployedModel(
		IContext context,
		genaicommons.proxies.DeployedModel _deployedModel
	)
	{
		Object result = deployedModel_GetOpenAIDeployedModelBuilder(
				_deployedModel
			)
			.execute(context);
		return result == null ? null : openaiconnector.proxies.OpenAIDeployedModel.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder doNothingBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpenAIConnector.DoNothing");
		return builder;
	}

	public static void doNothing(IContext context)
	{
		doNothingBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_AzureAISearchResource_ApiKeyBuilder(
		openaiconnector.proxies.AzureAISearchResource _azureAISearchResource
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpenAIConnector.DS_AzureAISearchResource_ApiKey");
		builder = builder.withParam("AzureAISearchResource", _azureAISearchResource);
		return builder;
	}

	public static openaiconnector.proxies.ApiKey dS_AzureAISearchResource_ApiKey(
		IContext context,
		openaiconnector.proxies.AzureAISearchResource _azureAISearchResource
	)
	{
		Object result = dS_AzureAISearchResource_ApiKeyBuilder(
				_azureAISearchResource
			)
			.execute(context);
		return result == null ? null : openaiconnector.proxies.ApiKey.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_Configuration_ApiKeyBuilder(
		openaiconnector.proxies.Configuration _configuration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpenAIConnector.DS_Configuration_ApiKey");
		builder = builder.withParam("Configuration", _configuration);
		return builder;
	}

	public static openaiconnector.proxies.ApiKey dS_Configuration_ApiKey(
		IContext context,
		openaiconnector.proxies.Configuration _configuration
	)
	{
		Object result = dS_Configuration_ApiKeyBuilder(
				_configuration
			)
			.execute(context);
		return result == null ? null : openaiconnector.proxies.ApiKey.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder embedding_ChunkCollection_ExecuteBuilder(
		genaicommons.proxies.DeployedModel _deployedModel,
		genaicommons.proxies.ChunkCollection _chunkCollection,
		genaicommons.proxies.EmbeddingsOptions _embeddingsOptions
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpenAIConnector.Embedding_ChunkCollection_Execute");
		builder = builder.withParam("DeployedModel", _deployedModel);
		builder = builder.withParam("ChunkCollection", _chunkCollection);
		builder = builder.withParam("EmbeddingsOptions", _embeddingsOptions);
		return builder;
	}

	public static genaicommons.proxies.EmbeddingsResponse embedding_ChunkCollection_Execute(
		IContext context,
		genaicommons.proxies.DeployedModel _deployedModel,
		genaicommons.proxies.ChunkCollection _chunkCollection,
		genaicommons.proxies.EmbeddingsOptions _embeddingsOptions
	)
	{
		Object result = embedding_ChunkCollection_ExecuteBuilder(
				_deployedModel,
				_chunkCollection,
				_embeddingsOptions
			)
			.execute(context);
		return result == null ? null : genaicommons.proxies.EmbeddingsResponse.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder embeddingsRequestMapping_CallAPIBuilder(
		openaiconnector.proxies.EmbeddingsRequestMapping _embeddingsRequestMapping,
		openaiconnector.proxies.Configuration _configuration,
		openaiconnector.proxies.OpenAIDeployedModel _openAIDeployedModel
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpenAIConnector.EmbeddingsRequestMapping_CallAPI");
		builder = builder.withParam("EmbeddingsRequestMapping", _embeddingsRequestMapping);
		builder = builder.withParam("Configuration", _configuration);
		builder = builder.withParam("OpenAIDeployedModel", _openAIDeployedModel);
		return builder;
	}

	public static genaicommons.proxies.EmbeddingsResponse embeddingsRequestMapping_CallAPI(
		IContext context,
		openaiconnector.proxies.EmbeddingsRequestMapping _embeddingsRequestMapping,
		openaiconnector.proxies.Configuration _configuration,
		openaiconnector.proxies.OpenAIDeployedModel _openAIDeployedModel
	)
	{
		Object result = embeddingsRequestMapping_CallAPIBuilder(
				_embeddingsRequestMapping,
				_configuration,
				_openAIDeployedModel
			)
			.execute(context);
		return result == null ? null : genaicommons.proxies.EmbeddingsResponse.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder embeddingsRequestMapping_CreateAndSetModelBuilder(
		openaiconnector.proxies.Configuration _configuration,
		java.lang.String _model,
		genaicommons.proxies.EmbeddingsOptions _embeddingsOptions,
		genaicommons.proxies.ChunkCollection _chunkCollection
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpenAIConnector.EmbeddingsRequestMapping_CreateAndSetModel");
		builder = builder.withParam("Configuration", _configuration);
		builder = builder.withParam("Model", _model);
		builder = builder.withParam("EmbeddingsOptions", _embeddingsOptions);
		builder = builder.withParam("ChunkCollection", _chunkCollection);
		return builder;
	}

	public static openaiconnector.proxies.EmbeddingsRequestMapping embeddingsRequestMapping_CreateAndSetModel(
		IContext context,
		openaiconnector.proxies.Configuration _configuration,
		java.lang.String _model,
		genaicommons.proxies.EmbeddingsOptions _embeddingsOptions,
		genaicommons.proxies.ChunkCollection _chunkCollection
	)
	{
		Object result = embeddingsRequestMapping_CreateAndSetModelBuilder(
				_configuration,
				_model,
				_embeddingsOptions,
				_chunkCollection
			)
			.execute(context);
		return result == null ? null : openaiconnector.proxies.EmbeddingsRequestMapping.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder embeddingsRequestMapping_POSTBuilder(
		java.lang.String _uRL,
		java.lang.String _decryptedApiKey,
		openaiconnector.proxies.EmbeddingsRequestMapping _embeddingsRequestMapping,
		openaiconnector.proxies.Configuration _configuration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpenAIConnector.EmbeddingsRequestMapping_POST");
		builder = builder.withParam("URL", _uRL);
		builder = builder.withParam("DecryptedApiKey", _decryptedApiKey);
		builder = builder.withParam("EmbeddingsRequestMapping", _embeddingsRequestMapping);
		builder = builder.withParam("Configuration", _configuration);
		return builder;
	}

	public static java.lang.String embeddingsRequestMapping_POST(
		IContext context,
		java.lang.String _uRL,
		java.lang.String _decryptedApiKey,
		openaiconnector.proxies.EmbeddingsRequestMapping _embeddingsRequestMapping,
		openaiconnector.proxies.Configuration _configuration
	)
	{
		Object result = embeddingsRequestMapping_POSTBuilder(
				_uRL,
				_decryptedApiKey,
				_embeddingsRequestMapping,
				_configuration
			)
			.execute(context);
		return (java.lang.String) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder embeddingsRequestMapping_ValidateBuilder(
		openaiconnector.proxies.EmbeddingsRequestMapping _embeddingsRequestMapping,
		openaiconnector.proxies.Configuration _configuration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpenAIConnector.EmbeddingsRequestMapping_Validate");
		builder = builder.withParam("EmbeddingsRequestMapping", _embeddingsRequestMapping);
		builder = builder.withParam("Configuration", _configuration);
		return builder;
	}

	public static boolean embeddingsRequestMapping_Validate(
		IContext context,
		openaiconnector.proxies.EmbeddingsRequestMapping _embeddingsRequestMapping,
		openaiconnector.proxies.Configuration _configuration
	)
	{
		Object result = embeddingsRequestMapping_ValidateBuilder(
				_embeddingsRequestMapping,
				_configuration
			)
			.execute(context);
		return (boolean) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder embeddingsResponse_ApplyImportMappingBuilder(
		java.lang.String _embeddingsResponseString,
		genaicommons.proxies.ChunkCollection _chunkCollection
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpenAIConnector.EmbeddingsResponse_ApplyImportMapping");
		builder = builder.withParam("EmbeddingsResponseString", _embeddingsResponseString);
		builder = builder.withParam("ChunkCollection", _chunkCollection);
		return builder;
	}

	public static genaicommons.proxies.EmbeddingsResponse embeddingsResponse_ApplyImportMapping(
		IContext context,
		java.lang.String _embeddingsResponseString,
		genaicommons.proxies.ChunkCollection _chunkCollection
	)
	{
		Object result = embeddingsResponse_ApplyImportMappingBuilder(
				_embeddingsResponseString,
				_chunkCollection
			)
			.execute(context);
		return result == null ? null : genaicommons.proxies.EmbeddingsResponse.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder embeddingsResponse_GetSelfBuilder(
		genaicommons.proxies.EmbeddingsResponse _embeddingsResponse
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpenAIConnector.EmbeddingsResponse_GetSelf");
		builder = builder.withParam("EmbeddingsResponse", _embeddingsResponse);
		return builder;
	}

	public static genaicommons.proxies.EmbeddingsResponse embeddingsResponse_GetSelf(
		IContext context,
		genaicommons.proxies.EmbeddingsResponse _embeddingsResponse
	)
	{
		Object result = embeddingsResponse_GetSelfBuilder(
				_embeddingsResponse
			)
			.execute(context);
		return result == null ? null : genaicommons.proxies.EmbeddingsResponse.initialize(context, (IMendixObject) result);
	}
	/**
	 * Microflow can be used to add a File to a FileCollection. The File Collection is an optional part of the input for the main operations.
	 * To add other files such as PDF documents, use the Add File to Collection action.
	 */
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder fileCollection_AddFile_OpenAIBuilder(
		genaicommons.proxies.FileCollection _fileCollection,
		java.lang.String _uRL,
		system.proxies.FileDocument _fileDocument,
		genaicommons.proxies.ENUM_FileType _eNUM_FileType,
		java.lang.String _textContent,
		openaiconnector.proxies.ENUM_ImageDetail _imageDetail
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpenAIConnector.FileCollection_AddFile_OpenAI");
		builder = builder.withParam("FileCollection", _fileCollection);
		builder = builder.withParam("URL", _uRL);
		builder = builder.withParam("FileDocument", _fileDocument);
		builder = builder.withParam("ENUM_FileType", _eNUM_FileType == null ? null : _eNUM_FileType.name());
		builder = builder.withParam("TextContent", _textContent);
		builder = builder.withParam("ImageDetail", _imageDetail == null ? null : _imageDetail.name());
		return builder;
	}

	/**
	 * Microflow can be used to add a File to a FileCollection. The File Collection is an optional part of the input for the main operations.
	 * To add other files such as PDF documents, use the Add File to Collection action.
	 */
	public static void fileCollection_AddFile_OpenAI(
		IContext context,
		genaicommons.proxies.FileCollection _fileCollection,
		java.lang.String _uRL,
		system.proxies.FileDocument _fileDocument,
		genaicommons.proxies.ENUM_FileType _eNUM_FileType,
		java.lang.String _textContent,
		openaiconnector.proxies.ENUM_ImageDetail _imageDetail
	)
	{
		fileCollection_AddFile_OpenAIBuilder(
				_fileCollection,
				_uRL,
				_fileDocument,
				_eNUM_FileType,
				_textContent,
				_imageDetail
			)
			.execute(context);
	}
	/**
	 * Microflow can be used to create a File Collection and add the first File to it immediately. The File Collection is an optional part of the input for the main operations.
	 * To add other files such as PDF documents, use the Initialize Colellection with File action.
	 */
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder fileCollection_CreateAndAddFile_OpenAIBuilder(
		java.lang.String _uRL,
		system.proxies.FileDocument _fileDocument,
		genaicommons.proxies.ENUM_FileType _eNUM_FileType,
		java.lang.String _textContent,
		openaiconnector.proxies.ENUM_ImageDetail _imageDetail
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpenAIConnector.FileCollection_CreateAndAddFile_OpenAI");
		builder = builder.withParam("URL", _uRL);
		builder = builder.withParam("FileDocument", _fileDocument);
		builder = builder.withParam("ENUM_FileType", _eNUM_FileType == null ? null : _eNUM_FileType.name());
		builder = builder.withParam("TextContent", _textContent);
		builder = builder.withParam("ImageDetail", _imageDetail == null ? null : _imageDetail.name());
		return builder;
	}

	/**
	 * Microflow can be used to create a File Collection and add the first File to it immediately. The File Collection is an optional part of the input for the main operations.
	 * To add other files such as PDF documents, use the Initialize Colellection with File action.
	 */
	public static genaicommons.proxies.FileCollection fileCollection_CreateAndAddFile_OpenAI(
		IContext context,
		java.lang.String _uRL,
		system.proxies.FileDocument _fileDocument,
		genaicommons.proxies.ENUM_FileType _eNUM_FileType,
		java.lang.String _textContent,
		openaiconnector.proxies.ENUM_ImageDetail _imageDetail
	)
	{
		Object result = fileCollection_CreateAndAddFile_OpenAIBuilder(
				_uRL,
				_fileDocument,
				_eNUM_FileType,
				_textContent,
				_imageDetail
			)
			.execute(context);
		return result == null ? null : genaicommons.proxies.FileCollection.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder fileCollection_GetFileContentListAndCastTo_OpenAIBuilder(
		genaicommons.proxies.FileCollection _fileCollection
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpenAIConnector.FileCollection_GetFileContentListAndCastTo_OpenAI");
		builder = builder.withParam("FileCollection", _fileCollection);
		return builder;
	}

	public static java.util.List<openaiconnector.proxies.OpenAIImageContent> fileCollection_GetFileContentListAndCastTo_OpenAI(
		IContext context,
		genaicommons.proxies.FileCollection _fileCollection
	)
	{
		Object result = fileCollection_GetFileContentListAndCastTo_OpenAIBuilder(
				_fileCollection
			)
			.execute(context);
		return result == null ? null : com.mendix.utils.ListUtils.map((java.util.List<IMendixObject>) result, obj -> openaiconnector.proxies.OpenAIImageContent.initialize(context, obj));
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder fileContent_CastTo_OpenAIFileContentBuilder(
		genaicommons.proxies.FileContent _fileContent
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpenAIConnector.FileContent_CastTo_OpenAIFileContent");
		builder = builder.withParam("FileContent", _fileContent);
		return builder;
	}

	public static openaiconnector.proxies.OpenAIImageContent fileContent_CastTo_OpenAIFileContent(
		IContext context,
		genaicommons.proxies.FileContent _fileContent
	)
	{
		Object result = fileContent_CastTo_OpenAIFileContentBuilder(
				_fileContent
			)
			.execute(context);
		return result == null ? null : openaiconnector.proxies.OpenAIImageContent.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder fileContent_CreateOpenAIFileContentBuilder(
		genaicommons.proxies.FileContent _fileContent
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpenAIConnector.FileContent_CreateOpenAIFileContent");
		builder = builder.withParam("FileContent", _fileContent);
		return builder;
	}

	public static openaiconnector.proxies.OpenAIImageContent fileContent_CreateOpenAIFileContent(
		IContext context,
		genaicommons.proxies.FileContent _fileContent
	)
	{
		Object result = fileContent_CreateOpenAIFileContentBuilder(
				_fileContent
			)
			.execute(context);
		return result == null ? null : openaiconnector.proxies.OpenAIImageContent.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder fileContent_ValidateBuilder(
		genaicommons.proxies.FileContent _fileContent
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpenAIConnector.FileContent_Validate");
		builder = builder.withParam("FileContent", _fileContent);
		return builder;
	}

	public static java.lang.String fileContent_Validate(
		IContext context,
		genaicommons.proxies.FileContent _fileContent
	)
	{
		Object result = fileContent_ValidateBuilder(
				_fileContent
			)
			.execute(context);
		return (java.lang.String) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder httpResponse_LogWithErrorBuilder(
		java.lang.String _microflowName,
		java.lang.String _operationName,
		system.proxies.HttpResponse _httpResponse,
		java.lang.String _additionalInformation_Optional,
		java.lang.String _logNode,
		system.proxies.Error _error
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpenAIConnector.HttpResponse_LogWithError");
		builder = builder.withParam("MicroflowName", _microflowName);
		builder = builder.withParam("OperationName", _operationName);
		builder = builder.withParam("HttpResponse", _httpResponse);
		builder = builder.withParam("AdditionalInformation_Optional", _additionalInformation_Optional);
		builder = builder.withParam("LogNode", _logNode);
		builder = builder.withParam("Error", _error);
		return builder;
	}

	public static void httpResponse_LogWithError(
		IContext context,
		java.lang.String _microflowName,
		java.lang.String _operationName,
		system.proxies.HttpResponse _httpResponse,
		java.lang.String _additionalInformation_Optional,
		java.lang.String _logNode,
		system.proxies.Error _error
	)
	{
		httpResponse_LogWithErrorBuilder(
				_microflowName,
				_operationName,
				_httpResponse,
				_additionalInformation_Optional,
				_logNode,
				_error
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder imageGenerations_ExecuteBuilder(
		java.lang.String _userPrompt,
		genaicommons.proxies.DeployedModel _deployedModel,
		genaicommons.proxies.ImageOptions _imageOptions
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpenAIConnector.ImageGenerations_Execute");
		builder = builder.withParam("UserPrompt", _userPrompt);
		builder = builder.withParam("DeployedModel", _deployedModel);
		builder = builder.withParam("ImageOptions", _imageOptions);
		return builder;
	}

	public static genaicommons.proxies.Response imageGenerations_Execute(
		IContext context,
		java.lang.String _userPrompt,
		genaicommons.proxies.DeployedModel _deployedModel,
		genaicommons.proxies.ImageOptions _imageOptions
	)
	{
		Object result = imageGenerations_ExecuteBuilder(
				_userPrompt,
				_deployedModel,
				_imageOptions
			)
			.execute(context);
		return result == null ? null : genaicommons.proxies.Response.initialize(context, (IMendixObject) result);
	}
	/**
	 * Microflow can be used to invoke OpenAI's image generations API with a custom request. The input and output of this microflow are intended to mirror the OpenAI JSON structures as much as possible. This operation should be used only in cases where the other exposed operations do not provide enough support. Use ImageGeneration_Create to create you request.
	 * Inputs:
	 * - ImageGenerationsRequest: The top-level input object for the API call.
	 * - Configuration: Configuration object that contains endpoint and API key
	 * Outputs:
	 * - ImageGenerationsResponse: The top-level output object of the reponse of the API call.
	 */
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder imageGenerationsRequestMapping_CallAPIBuilder(
		openaiconnector.proxies.Configuration _configuration,
		openaiconnector.proxies.ImageGenerationsRequestMapping _imageGenerationsRequestMapping,
		openaiconnector.proxies.OpenAIDeployedModel _openAIDeployedModel
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpenAIConnector.ImageGenerationsRequestMapping_CallAPI");
		builder = builder.withParam("Configuration", _configuration);
		builder = builder.withParam("ImageGenerationsRequestMapping", _imageGenerationsRequestMapping);
		builder = builder.withParam("OpenAIDeployedModel", _openAIDeployedModel);
		return builder;
	}

	/**
	 * Microflow can be used to invoke OpenAI's image generations API with a custom request. The input and output of this microflow are intended to mirror the OpenAI JSON structures as much as possible. This operation should be used only in cases where the other exposed operations do not provide enough support. Use ImageGeneration_Create to create you request.
	 * Inputs:
	 * - ImageGenerationsRequest: The top-level input object for the API call.
	 * - Configuration: Configuration object that contains endpoint and API key
	 * Outputs:
	 * - ImageGenerationsResponse: The top-level output object of the reponse of the API call.
	 */
	public static genaicommons.proxies.Response imageGenerationsRequestMapping_CallAPI(
		IContext context,
		openaiconnector.proxies.Configuration _configuration,
		openaiconnector.proxies.ImageGenerationsRequestMapping _imageGenerationsRequestMapping,
		openaiconnector.proxies.OpenAIDeployedModel _openAIDeployedModel
	)
	{
		Object result = imageGenerationsRequestMapping_CallAPIBuilder(
				_configuration,
				_imageGenerationsRequestMapping,
				_openAIDeployedModel
			)
			.execute(context);
		return result == null ? null : genaicommons.proxies.Response.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder imageGenerationsRequestMapping_CreateBuilder(
		genaicommons.proxies.ImageOptions _imageOptions,
		java.lang.String _prompt,
		java.lang.String _model,
		openaiconnector.proxies.Configuration _configuration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpenAIConnector.ImageGenerationsRequestMapping_Create");
		builder = builder.withParam("ImageOptions", _imageOptions);
		builder = builder.withParam("Prompt", _prompt);
		builder = builder.withParam("Model", _model);
		builder = builder.withParam("Configuration", _configuration);
		return builder;
	}

	public static openaiconnector.proxies.ImageGenerationsRequestMapping imageGenerationsRequestMapping_Create(
		IContext context,
		genaicommons.proxies.ImageOptions _imageOptions,
		java.lang.String _prompt,
		java.lang.String _model,
		openaiconnector.proxies.Configuration _configuration
	)
	{
		Object result = imageGenerationsRequestMapping_CreateBuilder(
				_imageOptions,
				_prompt,
				_model,
				_configuration
			)
			.execute(context);
		return result == null ? null : openaiconnector.proxies.ImageGenerationsRequestMapping.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder imageGenerationsRequestMapping_POSTBuilder(
		java.lang.String _uRL,
		java.lang.String _decryptedApiKey,
		openaiconnector.proxies.ImageGenerationsRequestMapping _imageGenerationsRequestMapping,
		openaiconnector.proxies.Configuration _configuration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpenAIConnector.ImageGenerationsRequestMapping_POST");
		builder = builder.withParam("URL", _uRL);
		builder = builder.withParam("DecryptedApiKey", _decryptedApiKey);
		builder = builder.withParam("ImageGenerationsRequestMapping", _imageGenerationsRequestMapping);
		builder = builder.withParam("Configuration", _configuration);
		return builder;
	}

	public static java.lang.String imageGenerationsRequestMapping_POST(
		IContext context,
		java.lang.String _uRL,
		java.lang.String _decryptedApiKey,
		openaiconnector.proxies.ImageGenerationsRequestMapping _imageGenerationsRequestMapping,
		openaiconnector.proxies.Configuration _configuration
	)
	{
		Object result = imageGenerationsRequestMapping_POSTBuilder(
				_uRL,
				_decryptedApiKey,
				_imageGenerationsRequestMapping,
				_configuration
			)
			.execute(context);
		return (java.lang.String) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder imageGenerationsRequestMapping_SetModelBuilder(
		openaiconnector.proxies.Configuration _configuration,
		java.lang.String _model,
		openaiconnector.proxies.ImageGenerationsRequestMapping _imageGenerationsRequestMapping
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpenAIConnector.ImageGenerationsRequestMapping_SetModel");
		builder = builder.withParam("Configuration", _configuration);
		builder = builder.withParam("Model", _model);
		builder = builder.withParam("ImageGenerationsRequestMapping", _imageGenerationsRequestMapping);
		return builder;
	}

	public static void imageGenerationsRequestMapping_SetModel(
		IContext context,
		openaiconnector.proxies.Configuration _configuration,
		java.lang.String _model,
		openaiconnector.proxies.ImageGenerationsRequestMapping _imageGenerationsRequestMapping
	)
	{
		imageGenerationsRequestMapping_SetModelBuilder(
				_configuration,
				_model,
				_imageGenerationsRequestMapping
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder imageGenerationsRequestMapping_ValidateBuilder(
		openaiconnector.proxies.ImageGenerationsRequestMapping _imageGenerationsRequestMapping
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpenAIConnector.ImageGenerationsRequestMapping_Validate");
		builder = builder.withParam("ImageGenerationsRequestMapping", _imageGenerationsRequestMapping);
		return builder;
	}

	public static boolean imageGenerationsRequestMapping_Validate(
		IContext context,
		openaiconnector.proxies.ImageGenerationsRequestMapping _imageGenerationsRequestMapping
	)
	{
		Object result = imageGenerationsRequestMapping_ValidateBuilder(
				_imageGenerationsRequestMapping
			)
			.execute(context);
		return (boolean) result;
	}
	/**
	 * Set OpenAI specific, optional image generations request parameters.
	 */
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder imageOptions_SetOpenAIExtensionBuilder(
		genaicommons.proxies.ImageOptions _imageOptions,
		openaiconnector.proxies.ENUM_ResponseFormat_Image _responseFormat,
		openaiconnector.proxies.ENUM_Style _style,
		openaiconnector.proxies.ENUM_Quality _quality,
		java.lang.String _userString
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpenAIConnector.ImageOptions_SetOpenAIExtension");
		builder = builder.withParam("ImageOptions", _imageOptions);
		builder = builder.withParam("ResponseFormat", _responseFormat == null ? null : _responseFormat.name());
		builder = builder.withParam("Style", _style == null ? null : _style.name());
		builder = builder.withParam("Quality", _quality == null ? null : _quality.name());
		builder = builder.withParam("UserString", _userString);
		return builder;
	}

	/**
	 * Set OpenAI specific, optional image generations request parameters.
	 */
	public static void imageOptions_SetOpenAIExtension(
		IContext context,
		genaicommons.proxies.ImageOptions _imageOptions,
		openaiconnector.proxies.ENUM_ResponseFormat_Image _responseFormat,
		openaiconnector.proxies.ENUM_Style _style,
		openaiconnector.proxies.ENUM_Quality _quality,
		java.lang.String _userString
	)
	{
		imageOptions_SetOpenAIExtensionBuilder(
				_imageOptions,
				_responseFormat,
				_style,
				_quality,
				_userString
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder index_GetCreateBuilder(
		java.lang.String _name,
		openaiconnector.proxies.AzureAISearchResource _azureAISearchResource
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpenAIConnector.Index_GetCreate");
		builder = builder.withParam("Name", _name);
		builder = builder.withParam("AzureAISearchResource", _azureAISearchResource);
		return builder;
	}

	public static openaiconnector.proxies.Index index_GetCreate(
		IContext context,
		java.lang.String _name,
		openaiconnector.proxies.AzureAISearchResource _azureAISearchResource
	)
	{
		Object result = index_GetCreateBuilder(
				_name,
				_azureAISearchResource
			)
			.execute(context);
		return result == null ? null : openaiconnector.proxies.Index.initialize(context, (IMendixObject) result);
	}
	/**
	 * Retrieves a list of Indexes for a given Azure AI Search Resource. The list is not committed inside of this action.
	 */
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder index_GetListBuilder(
		openaiconnector.proxies.AzureAISearchResource _azureAISearchResource
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpenAIConnector.Index_GetList");
		builder = builder.withParam("AzureAISearchResource", _azureAISearchResource);
		return builder;
	}

	/**
	 * Retrieves a list of Indexes for a given Azure AI Search Resource. The list is not committed inside of this action.
	 */
	public static java.util.List<openaiconnector.proxies.Index> index_GetList(
		IContext context,
		openaiconnector.proxies.AzureAISearchResource _azureAISearchResource
	)
	{
		Object result = index_GetListBuilder(
				_azureAISearchResource
			)
			.execute(context);
		return result == null ? null : com.mendix.utils.ListUtils.map((java.util.List<IMendixObject>) result, obj -> openaiconnector.proxies.Index.initialize(context, obj));
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder index_ReSyncBuilder(
		openaiconnector.proxies.AzureAISearchResource _azureAISearchResource
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpenAIConnector.Index_ReSync");
		builder = builder.withParam("AzureAISearchResource", _azureAISearchResource);
		return builder;
	}

	public static void index_ReSync(
		IContext context,
		openaiconnector.proxies.AzureAISearchResource _azureAISearchResource
	)
	{
		index_ReSyncBuilder(
				_azureAISearchResource
			)
			.execute(context);
	}
	/**
	 * Retrieve references for a given Index and Search Query via Azure AI Search.
	 */
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder index_RetrieveReferencesBuilder(
		genaicommons.proxies.DeployedKnowledgeBase _deployedKnowledgeBase,
		java.lang.String _searchQuery,
		java.lang.Long _maxNumberOfResults
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpenAIConnector.Index_RetrieveReferences");
		builder = builder.withParam("DeployedKnowledgeBase", _deployedKnowledgeBase);
		builder = builder.withParam("SearchQuery", _searchQuery);
		builder = builder.withParam("MaxNumberOfResults", _maxNumberOfResults);
		return builder;
	}

	/**
	 * Retrieve references for a given Index and Search Query via Azure AI Search.
	 */
	public static java.util.List<genaicommons.proxies.Reference> index_RetrieveReferences(
		IContext context,
		genaicommons.proxies.DeployedKnowledgeBase _deployedKnowledgeBase,
		java.lang.String _searchQuery,
		java.lang.Long _maxNumberOfResults
	)
	{
		Object result = index_RetrieveReferencesBuilder(
				_deployedKnowledgeBase,
				_searchQuery,
				_maxNumberOfResults
			)
			.execute(context);
		return result == null ? null : com.mendix.utils.ListUtils.map((java.util.List<IMendixObject>) result, obj -> genaicommons.proxies.Reference.initialize(context, obj));
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder index_ValidateBuilder(
		openaiconnector.proxies.Index _index
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpenAIConnector.Index_Validate");
		builder = builder.withParam("Index", _index);
		return builder;
	}

	public static boolean index_Validate(
		IContext context,
		openaiconnector.proxies.Index _index
	)
	{
		Object result = index_ValidateBuilder(
				_index
			)
			.execute(context);
		return (boolean) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder knowledgeBaseRetrieval_RetrieveBuilder(
		genaicommons.proxies.KnowledgeBaseRetrieval _knowledgeBaseRetrieval,
		genaicommons.proxies.Request _request,
		java.lang.String _searchQuery
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpenAIConnector.KnowledgeBaseRetrieval_Retrieve");
		builder = builder.withParam("KnowledgeBaseRetrieval", _knowledgeBaseRetrieval);
		builder = builder.withParam("Request", _request);
		builder = builder.withParam("SearchQuery", _searchQuery);
		return builder;
	}

	public static java.lang.String knowledgeBaseRetrieval_Retrieve(
		IContext context,
		genaicommons.proxies.KnowledgeBaseRetrieval _knowledgeBaseRetrieval,
		genaicommons.proxies.Request _request,
		java.lang.String _searchQuery
	)
	{
		Object result = knowledgeBaseRetrieval_RetrieveBuilder(
				_knowledgeBaseRetrieval,
				_request,
				_searchQuery
			)
			.execute(context);
		return (java.lang.String) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder message_ValidateBuilder(
		genaicommons.proxies.Message _message,
		java.lang.String _architecture
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpenAIConnector.Message_Validate");
		builder = builder.withParam("Message", _message);
		builder = builder.withParam("Architecture", _architecture);
		return builder;
	}

	public static java.lang.String message_Validate(
		IContext context,
		genaicommons.proxies.Message _message,
		java.lang.String _architecture
	)
	{
		Object result = message_ValidateBuilder(
				_message,
				_architecture
			)
			.execute(context);
		return (java.lang.String) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder message_Validate_AssistantBuilder(
		genaicommons.proxies.Message _message,
		java.lang.String _architecture
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpenAIConnector.Message_Validate_Assistant");
		builder = builder.withParam("Message", _message);
		builder = builder.withParam("Architecture", _architecture);
		return builder;
	}

	public static java.lang.String message_Validate_Assistant(
		IContext context,
		genaicommons.proxies.Message _message,
		java.lang.String _architecture
	)
	{
		Object result = message_Validate_AssistantBuilder(
				_message,
				_architecture
			)
			.execute(context);
		return (java.lang.String) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder message_Validate_ToolBuilder(
		genaicommons.proxies.Message _message
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpenAIConnector.Message_Validate_Tool");
		builder = builder.withParam("Message", _message);
		return builder;
	}

	public static java.lang.String message_Validate_Tool(
		IContext context,
		genaicommons.proxies.Message _message
	)
	{
		Object result = message_Validate_ToolBuilder(
				_message
			)
			.execute(context);
		return (java.lang.String) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder message_Validate_UserBuilder(
		genaicommons.proxies.Message _message
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpenAIConnector.Message_Validate_User");
		builder = builder.withParam("Message", _message);
		return builder;
	}

	public static java.lang.String message_Validate_User(
		IContext context,
		genaicommons.proxies.Message _message
	)
	{
		Object result = message_Validate_UserBuilder(
				_message
			)
			.execute(context);
		return (java.lang.String) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder openAIDeployedModel_CommitListBuilder(
		java.util.List<openaiconnector.proxies.OpenAIDeployedModel> _openAIDeployedModelList
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpenAIConnector.OpenAIDeployedModel_CommitList");
		builder = builder.withParam("OpenAIDeployedModelList", _openAIDeployedModelList);
		return builder;
	}

	public static void openAIDeployedModel_CommitList(
		IContext context,
		java.util.List<openaiconnector.proxies.OpenAIDeployedModel> _openAIDeployedModelList
	)
	{
		openAIDeployedModel_CommitListBuilder(
				_openAIDeployedModelList
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder openAIDeployedModel_CreateBuilder(
		openaiconnector.proxies.Configuration _configuration,
		java.lang.String _model,
		java.lang.String _architecture,
		genaicommons.proxies.ENUM_ModelModality _outputModality,
		java.lang.String _apiVersion,
		java.lang.String _displayName,
		genaicommons.proxies.ENUM_ModelSupport _supportsSystemPrompt,
		genaicommons.proxies.ENUM_ModelSupport _supportsFunctionCalling,
		genaicommons.proxies.ENUM_ModelSupport _supportsConversationHistory,
		java.util.List<genaicommons.proxies.InputModality> _inputModalityList
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpenAIConnector.OpenAIDeployedModel_Create");
		builder = builder.withParam("Configuration", _configuration);
		builder = builder.withParam("Model", _model);
		builder = builder.withParam("Architecture", _architecture);
		builder = builder.withParam("OutputModality", _outputModality == null ? null : _outputModality.name());
		builder = builder.withParam("ApiVersion", _apiVersion);
		builder = builder.withParam("DisplayName", _displayName);
		builder = builder.withParam("SupportsSystemPrompt", _supportsSystemPrompt == null ? null : _supportsSystemPrompt.name());
		builder = builder.withParam("SupportsFunctionCalling", _supportsFunctionCalling == null ? null : _supportsFunctionCalling.name());
		builder = builder.withParam("SupportsConversationHistory", _supportsConversationHistory == null ? null : _supportsConversationHistory.name());
		builder = builder.withParam("InputModalityList", _inputModalityList);
		return builder;
	}

	public static openaiconnector.proxies.OpenAIDeployedModel openAIDeployedModel_Create(
		IContext context,
		openaiconnector.proxies.Configuration _configuration,
		java.lang.String _model,
		java.lang.String _architecture,
		genaicommons.proxies.ENUM_ModelModality _outputModality,
		java.lang.String _apiVersion,
		java.lang.String _displayName,
		genaicommons.proxies.ENUM_ModelSupport _supportsSystemPrompt,
		genaicommons.proxies.ENUM_ModelSupport _supportsFunctionCalling,
		genaicommons.proxies.ENUM_ModelSupport _supportsConversationHistory,
		java.util.List<genaicommons.proxies.InputModality> _inputModalityList
	)
	{
		Object result = openAIDeployedModel_CreateBuilder(
				_configuration,
				_model,
				_architecture,
				_outputModality,
				_apiVersion,
				_displayName,
				_supportsSystemPrompt,
				_supportsFunctionCalling,
				_supportsConversationHistory,
				_inputModalityList
			)
			.execute(context);
		return result == null ? null : openaiconnector.proxies.OpenAIDeployedModel.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder openAIDeployedModel_GetCreateAndAddToListBuilder(
		openaiconnector.proxies.Configuration _configuration,
		java.lang.String _architecture,
		genaicommons.proxies.ENUM_ModelModality _outputModality,
		java.lang.String _apiVersion,
		java.lang.String _model,
		java.util.List<genaicommons.proxies.DeployedModel> _deployedModelList,
		genaicommons.proxies.ENUM_ModelSupport _supportsSystemPrompt,
		genaicommons.proxies.ENUM_ModelSupport _supportsFunctionCalling,
		genaicommons.proxies.ENUM_ModelSupport _supportsConversationHistory,
		java.util.List<genaicommons.proxies.InputModality> _inputModalityList
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpenAIConnector.OpenAIDeployedModel_GetCreateAndAddToList");
		builder = builder.withParam("Configuration", _configuration);
		builder = builder.withParam("Architecture", _architecture);
		builder = builder.withParam("OutputModality", _outputModality == null ? null : _outputModality.name());
		builder = builder.withParam("ApiVersion", _apiVersion);
		builder = builder.withParam("Model", _model);
		builder = builder.withParam("DeployedModelList", _deployedModelList);
		builder = builder.withParam("SupportsSystemPrompt", _supportsSystemPrompt == null ? null : _supportsSystemPrompt.name());
		builder = builder.withParam("SupportsFunctionCalling", _supportsFunctionCalling == null ? null : _supportsFunctionCalling.name());
		builder = builder.withParam("SupportsConversationHistory", _supportsConversationHistory == null ? null : _supportsConversationHistory.name());
		builder = builder.withParam("InputModalityList", _inputModalityList);
		return builder;
	}

	public static void openAIDeployedModel_GetCreateAndAddToList(
		IContext context,
		openaiconnector.proxies.Configuration _configuration,
		java.lang.String _architecture,
		genaicommons.proxies.ENUM_ModelModality _outputModality,
		java.lang.String _apiVersion,
		java.lang.String _model,
		java.util.List<genaicommons.proxies.DeployedModel> _deployedModelList,
		genaicommons.proxies.ENUM_ModelSupport _supportsSystemPrompt,
		genaicommons.proxies.ENUM_ModelSupport _supportsFunctionCalling,
		genaicommons.proxies.ENUM_ModelSupport _supportsConversationHistory,
		java.util.List<genaicommons.proxies.InputModality> _inputModalityList
	)
	{
		openAIDeployedModel_GetCreateAndAddToListBuilder(
				_configuration,
				_architecture,
				_outputModality,
				_apiVersion,
				_model,
				_deployedModelList,
				_supportsSystemPrompt,
				_supportsFunctionCalling,
				_supportsConversationHistory,
				_inputModalityList
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder openAIDeployedModel_GetURLBuilder(
		openaiconnector.proxies.OpenAIDeployedModel _openAIDeployedModel
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpenAIConnector.OpenAIDeployedModel_GetURL");
		builder = builder.withParam("OpenAIDeployedModel", _openAIDeployedModel);
		return builder;
	}

	public static java.lang.String openAIDeployedModel_GetURL(
		IContext context,
		openaiconnector.proxies.OpenAIDeployedModel _openAIDeployedModel
	)
	{
		Object result = openAIDeployedModel_GetURLBuilder(
				_openAIDeployedModel
			)
			.execute(context);
		return (java.lang.String) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder openAIDeployedModel_RetrieveListFromConfigurationBuilder(
		openaiconnector.proxies.Configuration _configuration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpenAIConnector.OpenAIDeployedModel_RetrieveListFromConfiguration");
		builder = builder.withParam("Configuration", _configuration);
		return builder;
	}

	public static java.util.List<openaiconnector.proxies.OpenAIDeployedModel> openAIDeployedModel_RetrieveListFromConfiguration(
		IContext context,
		openaiconnector.proxies.Configuration _configuration
	)
	{
		Object result = openAIDeployedModel_RetrieveListFromConfigurationBuilder(
				_configuration
			)
			.execute(context);
		return result == null ? null : com.mendix.utils.ListUtils.map((java.util.List<IMendixObject>) result, obj -> openaiconnector.proxies.OpenAIDeployedModel.initialize(context, obj));
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder openAIDeployedModel_SetMicroflowBuilder(
		openaiconnector.proxies.OpenAIDeployedModel _openAIDeployedModel
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpenAIConnector.OpenAIDeployedModel_SetMicroflow");
		builder = builder.withParam("OpenAIDeployedModel", _openAIDeployedModel);
		return builder;
	}

	public static void openAIDeployedModel_SetMicroflow(
		IContext context,
		openaiconnector.proxies.OpenAIDeployedModel _openAIDeployedModel
	)
	{
		openAIDeployedModel_SetMicroflowBuilder(
				_openAIDeployedModel
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder openAIDeployedModel_ValidateBuilder(
		openaiconnector.proxies.OpenAIDeployedModel _openAIDeployedModel
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpenAIConnector.OpenAIDeployedModel_Validate");
		builder = builder.withParam("OpenAIDeployedModel", _openAIDeployedModel);
		return builder;
	}

	public static boolean openAIDeployedModel_Validate(
		IContext context,
		openaiconnector.proxies.OpenAIDeployedModel _openAIDeployedModel
	)
	{
		Object result = openAIDeployedModel_ValidateBuilder(
				_openAIDeployedModel
			)
			.execute(context);
		return (boolean) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder openAIFileContent_SetFileContentBuilder(
		openaiconnector.proxies.OpenAIImageContent _openAIFileContent
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpenAIConnector.OpenAIFileContent_SetFileContent");
		builder = builder.withParam("OpenAIFileContent", _openAIFileContent);
		return builder;
	}

	public static void openAIFileContent_SetFileContent(
		IContext context,
		openaiconnector.proxies.OpenAIImageContent _openAIFileContent
	)
	{
		openAIFileContent_SetFileContentBuilder(
				_openAIFileContent
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder openAIImageOptions_Extension_GetCreateBuilder(
		genaicommons.proxies.ImageOptions _imageOptions
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpenAIConnector.OpenAIImageOptions_Extension_GetCreate");
		builder = builder.withParam("ImageOptions", _imageOptions);
		return builder;
	}

	public static openaiconnector.proxies.OpenAIImageOptions_Extension openAIImageOptions_Extension_GetCreate(
		IContext context,
		genaicommons.proxies.ImageOptions _imageOptions
	)
	{
		Object result = openAIImageOptions_Extension_GetCreateBuilder(
				_imageOptions
			)
			.execute(context);
		return result == null ? null : openaiconnector.proxies.OpenAIImageOptions_Extension.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder openAIRequest_Extension_GetOrCreateBuilder(
		genaicommons.proxies.Request _request
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpenAIConnector.OpenAIRequest_Extension_GetOrCreate");
		builder = builder.withParam("Request", _request);
		return builder;
	}

	public static openaiconnector.proxies.OpenAIRequest_Extension openAIRequest_Extension_GetOrCreate(
		IContext context,
		genaicommons.proxies.Request _request
	)
	{
		Object result = openAIRequest_Extension_GetOrCreateBuilder(
				_request
			)
			.execute(context);
		return result == null ? null : openaiconnector.proxies.OpenAIRequest_Extension.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder request_CallAPIBuilder(
		genaicommons.proxies.Request _request,
		genaicommons.proxies.DeployedModel _deployedModel
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpenAIConnector.Request_CallAPI");
		builder = builder.withParam("Request", _request);
		builder = builder.withParam("DeployedModel", _deployedModel);
		return builder;
	}

	public static genaicommons.proxies.Response request_CallAPI(
		IContext context,
		genaicommons.proxies.Request _request,
		genaicommons.proxies.DeployedModel _deployedModel
	)
	{
		Object result = request_CallAPIBuilder(
				_request,
				_deployedModel
			)
			.execute(context);
		return result == null ? null : genaicommons.proxies.Response.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder request_CreateCombinedLogMessageValidationBuilder(
		java.lang.String _logMessage_Request,
		java.lang.String _logMessage_Messages,
		java.lang.String _logMessage_FunctionCalling
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpenAIConnector.Request_CreateCombinedLogMessageValidation");
		builder = builder.withParam("LogMessage_Request", _logMessage_Request);
		builder = builder.withParam("LogMessage_Messages", _logMessage_Messages);
		builder = builder.withParam("LogMessage_FunctionCalling", _logMessage_FunctionCalling);
		return builder;
	}

	public static java.lang.String request_CreateCombinedLogMessageValidation(
		IContext context,
		java.lang.String _logMessage_Request,
		java.lang.String _logMessage_Messages,
		java.lang.String _logMessage_FunctionCalling
	)
	{
		Object result = request_CreateCombinedLogMessageValidationBuilder(
				_logMessage_Request,
				_logMessage_Messages,
				_logMessage_FunctionCalling
			)
			.execute(context);
		return (java.lang.String) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder request_ExportToJsonBuilder(
		genaicommons.proxies.Request _request,
		openaiconnector.proxies.OpenAIDeployedModel _openAIDeployedModel
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpenAIConnector.Request_ExportToJson");
		builder = builder.withParam("Request", _request);
		builder = builder.withParam("OpenAIDeployedModel", _openAIDeployedModel);
		return builder;
	}

	public static java.lang.String request_ExportToJson(
		IContext context,
		genaicommons.proxies.Request _request,
		openaiconnector.proxies.OpenAIDeployedModel _openAIDeployedModel
	)
	{
		Object result = request_ExportToJsonBuilder(
				_request,
				_openAIDeployedModel
			)
			.execute(context);
		return (java.lang.String) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder request_FunctionCalling_ValidateBuilder(
		genaicommons.proxies.Request _request
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpenAIConnector.Request_FunctionCalling_Validate");
		builder = builder.withParam("Request", _request);
		return builder;
	}

	public static java.lang.String request_FunctionCalling_Validate(
		IContext context,
		genaicommons.proxies.Request _request
	)
	{
		Object result = request_FunctionCalling_ValidateBuilder(
				_request
			)
			.execute(context);
		return (java.lang.String) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder request_Messages_ValidateBuilder(
		java.util.List<genaicommons.proxies.Message> _messageList,
		java.lang.String _architecture
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpenAIConnector.Request_Messages_Validate");
		builder = builder.withParam("MessageList", _messageList);
		builder = builder.withParam("Architecture", _architecture);
		return builder;
	}

	public static java.lang.String request_Messages_Validate(
		IContext context,
		java.util.List<genaicommons.proxies.Message> _messageList,
		java.lang.String _architecture
	)
	{
		Object result = request_Messages_ValidateBuilder(
				_messageList,
				_architecture
			)
			.execute(context);
		return (java.lang.String) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder request_POSTBuilder(
		java.lang.String _uRL,
		java.lang.String _decryptedApiKey,
		java.lang.String _request_Json,
		openaiconnector.proxies.Configuration _configuration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpenAIConnector.Request_POST");
		builder = builder.withParam("URL", _uRL);
		builder = builder.withParam("DecryptedApiKey", _decryptedApiKey);
		builder = builder.withParam("Request_Json", _request_Json);
		builder = builder.withParam("Configuration", _configuration);
		return builder;
	}

	public static java.lang.String request_POST(
		IContext context,
		java.lang.String _uRL,
		java.lang.String _decryptedApiKey,
		java.lang.String _request_Json,
		openaiconnector.proxies.Configuration _configuration
	)
	{
		Object result = request_POSTBuilder(
				_uRL,
				_decryptedApiKey,
				_request_Json,
				_configuration
			)
			.execute(context);
		return (java.lang.String) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder request_SetModelBuilder(
		openaiconnector.proxies.Configuration _configuration,
		java.lang.String _model,
		genaicommons.proxies.Request _request
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpenAIConnector.Request_SetModel");
		builder = builder.withParam("Configuration", _configuration);
		builder = builder.withParam("Model", _model);
		builder = builder.withParam("Request", _request);
		return builder;
	}

	public static void request_SetModel(
		IContext context,
		openaiconnector.proxies.Configuration _configuration,
		java.lang.String _model,
		genaicommons.proxies.Request _request
	)
	{
		request_SetModelBuilder(
				_configuration,
				_model,
				_request
			)
			.execute(context);
	}
	/**
	 * Microflow can be used to set the response format for OpenAI operations. This describes the format that the chat completions model must output.
	 */
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder request_SetResponseFormatBuilder(
		genaicommons.proxies.Request _request,
		openaiconnector.proxies.ENUM_ResponseFormat_Chat _eNUM_ResponseFormat_Chat
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpenAIConnector.Request_SetResponseFormat");
		builder = builder.withParam("Request", _request);
		builder = builder.withParam("ENUM_ResponseFormat_Chat", _eNUM_ResponseFormat_Chat == null ? null : _eNUM_ResponseFormat_Chat.name());
		return builder;
	}

	/**
	 * Microflow can be used to set the response format for OpenAI operations. This describes the format that the chat completions model must output.
	 */
	public static void request_SetResponseFormat(
		IContext context,
		genaicommons.proxies.Request _request,
		openaiconnector.proxies.ENUM_ResponseFormat_Chat _eNUM_ResponseFormat_Chat
	)
	{
		request_SetResponseFormatBuilder(
				_request,
				_eNUM_ResponseFormat_Chat
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder request_ValidateBuilder(
		genaicommons.proxies.Request _request,
		openaiconnector.proxies.Configuration _configuration,
		openaiconnector.proxies.OpenAIDeployedModel _openAIDeployedModel
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpenAIConnector.Request_Validate");
		builder = builder.withParam("Request", _request);
		builder = builder.withParam("Configuration", _configuration);
		builder = builder.withParam("OpenAIDeployedModel", _openAIDeployedModel);
		return builder;
	}

	public static boolean request_Validate(
		IContext context,
		genaicommons.proxies.Request _request,
		openaiconnector.proxies.Configuration _configuration,
		openaiconnector.proxies.OpenAIDeployedModel _openAIDeployedModel
	)
	{
		Object result = request_ValidateBuilder(
				_request,
				_configuration,
				_openAIDeployedModel
			)
			.execute(context);
		return (boolean) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder requestMapping_GetMessagesBuilder(
		openaiconnector.proxies.RequestMapping _requestMapping
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpenAIConnector.RequestMapping_GetMessages");
		builder = builder.withParam("RequestMapping", _requestMapping);
		return builder;
	}

	public static java.util.List<genaicommons.proxies.Message> requestMapping_GetMessages(
		IContext context,
		openaiconnector.proxies.RequestMapping _requestMapping
	)
	{
		Object result = requestMapping_GetMessagesBuilder(
				_requestMapping
			)
			.execute(context);
		return result == null ? null : com.mendix.utils.ListUtils.map((java.util.List<IMendixObject>) result, obj -> genaicommons.proxies.Message.initialize(context, obj));
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder requestMapping_GetSelf_ResponseFormatBuilder(
		openaiconnector.proxies.RequestMapping _requestMapping
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpenAIConnector.RequestMapping_GetSelf_ResponseFormat");
		builder = builder.withParam("RequestMapping", _requestMapping);
		return builder;
	}

	public static openaiconnector.proxies.RequestMapping requestMapping_GetSelf_ResponseFormat(
		IContext context,
		openaiconnector.proxies.RequestMapping _requestMapping
	)
	{
		Object result = requestMapping_GetSelf_ResponseFormatBuilder(
				_requestMapping
			)
			.execute(context);
		return result == null ? null : openaiconnector.proxies.RequestMapping.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder requestMapping_GetStopSequencesBuilder(
		openaiconnector.proxies.RequestMapping _requestMapping
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpenAIConnector.RequestMapping_GetStopSequences");
		builder = builder.withParam("RequestMapping", _requestMapping);
		return builder;
	}

	public static java.util.List<genaicommons.proxies.StopSequence> requestMapping_GetStopSequences(
		IContext context,
		openaiconnector.proxies.RequestMapping _requestMapping
	)
	{
		Object result = requestMapping_GetStopSequencesBuilder(
				_requestMapping
			)
			.execute(context);
		return result == null ? null : com.mendix.utils.ListUtils.map((java.util.List<IMendixObject>) result, obj -> genaicommons.proxies.StopSequence.initialize(context, obj));
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder requestMapping_GetToolCollectionBuilder(
		openaiconnector.proxies.RequestMapping _requestMapping
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpenAIConnector.RequestMapping_GetToolCollection");
		builder = builder.withParam("RequestMapping", _requestMapping);
		return builder;
	}

	public static genaicommons.proxies.ToolCollection requestMapping_GetToolCollection(
		IContext context,
		openaiconnector.proxies.RequestMapping _requestMapping
	)
	{
		Object result = requestMapping_GetToolCollectionBuilder(
				_requestMapping
			)
			.execute(context);
		return result == null ? null : genaicommons.proxies.ToolCollection.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder response_ApplyImportMapping_ImageGenerationsBuilder(
		java.lang.String _responseString
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpenAIConnector.Response_ApplyImportMapping_ImageGenerations");
		builder = builder.withParam("ResponseString", _responseString);
		return builder;
	}

	public static genaicommons.proxies.Response response_ApplyImportMapping_ImageGenerations(
		IContext context,
		java.lang.String _responseString
	)
	{
		Object result = response_ApplyImportMapping_ImageGenerationsBuilder(
				_responseString
			)
			.execute(context);
		return result == null ? null : genaicommons.proxies.Response.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder response_CreateFileContentBuilder(
		genaicommons.proxies.Response _response
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpenAIConnector.Response_CreateFileContent");
		builder = builder.withParam("Response", _response);
		return builder;
	}

	public static genaicommons.proxies.FileContent response_CreateFileContent(
		IContext context,
		genaicommons.proxies.Response _response
	)
	{
		Object result = response_CreateFileContentBuilder(
				_response
			)
			.execute(context);
		return result == null ? null : genaicommons.proxies.FileContent.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder response_MapResponse_CreateReferencesBuilder(
		genaicommons.proxies.Response _response,
		genaicommons.proxies.Request _request
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpenAIConnector.Response_MapResponse_CreateReferences");
		builder = builder.withParam("Response", _response);
		builder = builder.withParam("Request", _request);
		return builder;
	}

	public static void response_MapResponse_CreateReferences(
		IContext context,
		genaicommons.proxies.Response _response,
		genaicommons.proxies.Request _request
	)
	{
		response_MapResponse_CreateReferencesBuilder(
				_response,
				_request
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder tool_SetToolTypeToFunctionBuilder(
		java.lang.String _toolType
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpenAIConnector.Tool_SetToolTypeToFunction");
		builder = builder.withParam("ToolType", _toolType);
		return builder;
	}

	public static java.lang.String tool_SetToolTypeToFunction(
		IContext context,
		java.lang.String _toolType
	)
	{
		Object result = tool_SetToolTypeToFunctionBuilder(
				_toolType
			)
			.execute(context);
		return (java.lang.String) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder tool_ValidateBuilder(
		genaicommons.proxies.Tool _tool,
		java.util.List<genaicommons.proxies.Tool> _toolList
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpenAIConnector.Tool_Validate");
		builder = builder.withParam("Tool", _tool);
		builder = builder.withParam("ToolList", _toolList);
		return builder;
	}

	public static java.lang.String tool_Validate(
		IContext context,
		genaicommons.proxies.Tool _tool,
		java.util.List<genaicommons.proxies.Tool> _toolList
	)
	{
		Object result = tool_ValidateBuilder(
				_tool,
				_toolList
			)
			.execute(context);
		return (java.lang.String) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder toolCall_ValidateBuilder(
		genaicommons.proxies.ToolCall _toolCall,
		java.lang.String _architecture
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OpenAIConnector.ToolCall_Validate");
		builder = builder.withParam("ToolCall", _toolCall);
		builder = builder.withParam("Architecture", _architecture);
		return builder;
	}

	public static java.lang.String toolCall_Validate(
		IContext context,
		genaicommons.proxies.ToolCall _toolCall,
		java.lang.String _architecture
	)
	{
		Object result = toolCall_ValidateBuilder(
				_toolCall,
				_architecture
			)
			.execute(context);
		return (java.lang.String) result;
	}
}
