// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstaibot.proxies;

public class BotConfig extends conversationalui.proxies.ProviderConfig
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstAIBot.BotConfig";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ActionMicroflowSelection("ActionMicroflowSelection"),
		IsSelectable("IsSelectable"),
		IsDefault("IsDefault"),
		HasKnowledgeBase("HasKnowledgeBase"),
		Architecture("Architecture"),
		ActionMicroflow("ActionMicroflow"),
		DisplayName("DisplayName"),
		SystemPrompt("SystemPrompt"),
		BotConfig_AmazonBedrockKnowledgeBase("MyFirstAIBot.BotConfig_AmazonBedrockKnowledgeBase"),
		ProviderConfig_DeployedModel("ConversationalUI.ProviderConfig_DeployedModel");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public BotConfig(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected BotConfig(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject botConfigMendixObject)
	{
		super(context, botConfigMendixObject);
		if (!botConfigMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static myfirstaibot.proxies.BotConfig initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstaibot.proxies.BotConfig(context, mendixObject);
	}

	public static myfirstaibot.proxies.BotConfig load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstaibot.proxies.BotConfig.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstaibot.proxies.BotConfig> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> myfirstaibot.proxies.BotConfig.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Get value of ActionMicroflowSelection
	 * @param actionmicroflowselection
	 */
	public final myfirstaibot.proxies.ENUM_ActionMicroflowSelection getActionMicroflowSelection()
	{
		return getActionMicroflowSelection(getContext());
	}

	/**
	 * @param context
	 * @return value of ActionMicroflowSelection
	 */
	public final myfirstaibot.proxies.ENUM_ActionMicroflowSelection getActionMicroflowSelection(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.ActionMicroflowSelection.toString());
		if (obj == null) {
			return null;
		}
		return myfirstaibot.proxies.ENUM_ActionMicroflowSelection.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of ActionMicroflowSelection
	 * @param actionmicroflowselection
	 */
	public final void setActionMicroflowSelection(myfirstaibot.proxies.ENUM_ActionMicroflowSelection actionmicroflowselection)
	{
		setActionMicroflowSelection(getContext(), actionmicroflowselection);
	}

	/**
	 * Set value of ActionMicroflowSelection
	 * @param context
	 * @param actionmicroflowselection
	 */
	public final void setActionMicroflowSelection(com.mendix.systemwideinterfaces.core.IContext context, myfirstaibot.proxies.ENUM_ActionMicroflowSelection actionmicroflowselection)
	{
		if (actionmicroflowselection != null) {
			getMendixObject().setValue(context, MemberNames.ActionMicroflowSelection.toString(), actionmicroflowselection.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.ActionMicroflowSelection.toString(), null);
		}
	}

	/**
	 * @return value of IsSelectable
	 */
	public final java.lang.Boolean getIsSelectable()
	{
		return getIsSelectable(getContext());
	}

	/**
	 * @param context
	 * @return value of IsSelectable
	 */
	public final java.lang.Boolean getIsSelectable(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsSelectable.toString());
	}

	/**
	 * Set value of IsSelectable
	 * @param isselectable
	 */
	public final void setIsSelectable(java.lang.Boolean isselectable)
	{
		setIsSelectable(getContext(), isselectable);
	}

	/**
	 * Set value of IsSelectable
	 * @param context
	 * @param isselectable
	 */
	public final void setIsSelectable(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isselectable)
	{
		getMendixObject().setValue(context, MemberNames.IsSelectable.toString(), isselectable);
	}

	/**
	 * @return value of IsDefault
	 */
	public final java.lang.Boolean getIsDefault()
	{
		return getIsDefault(getContext());
	}

	/**
	 * @param context
	 * @return value of IsDefault
	 */
	public final java.lang.Boolean getIsDefault(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsDefault.toString());
	}

	/**
	 * Set value of IsDefault
	 * @param isdefault
	 */
	public final void setIsDefault(java.lang.Boolean isdefault)
	{
		setIsDefault(getContext(), isdefault);
	}

	/**
	 * Set value of IsDefault
	 * @param context
	 * @param isdefault
	 */
	public final void setIsDefault(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isdefault)
	{
		getMendixObject().setValue(context, MemberNames.IsDefault.toString(), isdefault);
	}

	/**
	 * @return value of HasKnowledgeBase
	 */
	public final java.lang.Boolean getHasKnowledgeBase()
	{
		return getHasKnowledgeBase(getContext());
	}

	/**
	 * @param context
	 * @return value of HasKnowledgeBase
	 */
	public final java.lang.Boolean getHasKnowledgeBase(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.HasKnowledgeBase.toString());
	}

	/**
	 * Set value of HasKnowledgeBase
	 * @param hasknowledgebase
	 */
	public final void setHasKnowledgeBase(java.lang.Boolean hasknowledgebase)
	{
		setHasKnowledgeBase(getContext(), hasknowledgebase);
	}

	/**
	 * Set value of HasKnowledgeBase
	 * @param context
	 * @param hasknowledgebase
	 */
	public final void setHasKnowledgeBase(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean hasknowledgebase)
	{
		getMendixObject().setValue(context, MemberNames.HasKnowledgeBase.toString(), hasknowledgebase);
	}

	/**
	 * @return value of Architecture
	 */
	public final java.lang.String getArchitecture()
	{
		return getArchitecture(getContext());
	}

	/**
	 * @param context
	 * @return value of Architecture
	 */
	public final java.lang.String getArchitecture(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Architecture.toString());
	}

	/**
	 * Set value of Architecture
	 * @param architecture
	 */
	public final void setArchitecture(java.lang.String architecture)
	{
		setArchitecture(getContext(), architecture);
	}

	/**
	 * Set value of Architecture
	 * @param context
	 * @param architecture
	 */
	public final void setArchitecture(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String architecture)
	{
		getMendixObject().setValue(context, MemberNames.Architecture.toString(), architecture);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of BotConfig_AmazonBedrockKnowledgeBase
	 */
	public final amazonbedrockconnector.proxies.AmazonBedrockKnowledgeBase getBotConfig_AmazonBedrockKnowledgeBase() throws com.mendix.core.CoreException
	{
		return getBotConfig_AmazonBedrockKnowledgeBase(getContext());
	}

	/**
	 * @param context
	 * @return value of BotConfig_AmazonBedrockKnowledgeBase
	 * @throws com.mendix.core.CoreException
	 */
	public final amazonbedrockconnector.proxies.AmazonBedrockKnowledgeBase getBotConfig_AmazonBedrockKnowledgeBase(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		amazonbedrockconnector.proxies.AmazonBedrockKnowledgeBase result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.BotConfig_AmazonBedrockKnowledgeBase.toString());
		if (identifier != null) {
			result = amazonbedrockconnector.proxies.AmazonBedrockKnowledgeBase.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of BotConfig_AmazonBedrockKnowledgeBase
	 * @param botconfig_amazonbedrockknowledgebase
	 */
	public final void setBotConfig_AmazonBedrockKnowledgeBase(amazonbedrockconnector.proxies.AmazonBedrockKnowledgeBase botconfig_amazonbedrockknowledgebase)
	{
		setBotConfig_AmazonBedrockKnowledgeBase(getContext(), botconfig_amazonbedrockknowledgebase);
	}

	/**
	 * Set value of BotConfig_AmazonBedrockKnowledgeBase
	 * @param context
	 * @param botconfig_amazonbedrockknowledgebase
	 */
	public final void setBotConfig_AmazonBedrockKnowledgeBase(com.mendix.systemwideinterfaces.core.IContext context, amazonbedrockconnector.proxies.AmazonBedrockKnowledgeBase botconfig_amazonbedrockknowledgebase)
	{
		if (botconfig_amazonbedrockknowledgebase == null) {
			getMendixObject().setValue(context, MemberNames.BotConfig_AmazonBedrockKnowledgeBase.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.BotConfig_AmazonBedrockKnowledgeBase.toString(), botconfig_amazonbedrockknowledgebase.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstaibot.proxies.BotConfig that = (myfirstaibot.proxies.BotConfig) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
