// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstaibot.proxies;

public class ContextExtension implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject contextExtensionMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstAIBot.ContextExtension";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Temperature("Temperature"),
		ContextExtension_Instruction("MyFirstAIBot.ContextExtension_Instruction"),
		ContextExtension_ChatContext("MyFirstAIBot.ContextExtension_ChatContext");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ContextExtension(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ContextExtension(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject contextExtensionMendixObject)
	{
		if (contextExtensionMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!contextExtensionMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.contextExtensionMendixObject = contextExtensionMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static myfirstaibot.proxies.ContextExtension initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstaibot.proxies.ContextExtension(context, mendixObject);
	}

	public static myfirstaibot.proxies.ContextExtension load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstaibot.proxies.ContextExtension.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstaibot.proxies.ContextExtension> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> myfirstaibot.proxies.ContextExtension.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of Temperature
	 */
	public final java.math.BigDecimal getTemperature()
	{
		return getTemperature(getContext());
	}

	/**
	 * @param context
	 * @return value of Temperature
	 */
	public final java.math.BigDecimal getTemperature(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Temperature.toString());
	}

	/**
	 * Set value of Temperature
	 * @param temperature
	 */
	public final void setTemperature(java.math.BigDecimal temperature)
	{
		setTemperature(getContext(), temperature);
	}

	/**
	 * Set value of Temperature
	 * @param context
	 * @param temperature
	 */
	public final void setTemperature(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal temperature)
	{
		getMendixObject().setValue(context, MemberNames.Temperature.toString(), temperature);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ContextExtension_Instruction
	 */
	public final myfirstaibot.proxies.Instruction getContextExtension_Instruction() throws com.mendix.core.CoreException
	{
		return getContextExtension_Instruction(getContext());
	}

	/**
	 * @param context
	 * @return value of ContextExtension_Instruction
	 * @throws com.mendix.core.CoreException
	 */
	public final myfirstaibot.proxies.Instruction getContextExtension_Instruction(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstaibot.proxies.Instruction result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ContextExtension_Instruction.toString());
		if (identifier != null) {
			result = myfirstaibot.proxies.Instruction.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ContextExtension_Instruction
	 * @param contextextension_instruction
	 */
	public final void setContextExtension_Instruction(myfirstaibot.proxies.Instruction contextextension_instruction)
	{
		setContextExtension_Instruction(getContext(), contextextension_instruction);
	}

	/**
	 * Set value of ContextExtension_Instruction
	 * @param context
	 * @param contextextension_instruction
	 */
	public final void setContextExtension_Instruction(com.mendix.systemwideinterfaces.core.IContext context, myfirstaibot.proxies.Instruction contextextension_instruction)
	{
		if (contextextension_instruction == null) {
			getMendixObject().setValue(context, MemberNames.ContextExtension_Instruction.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ContextExtension_Instruction.toString(), contextextension_instruction.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ContextExtension_ChatContext
	 */
	public final conversationalui.proxies.ChatContext getContextExtension_ChatContext() throws com.mendix.core.CoreException
	{
		return getContextExtension_ChatContext(getContext());
	}

	/**
	 * @param context
	 * @return value of ContextExtension_ChatContext
	 * @throws com.mendix.core.CoreException
	 */
	public final conversationalui.proxies.ChatContext getContextExtension_ChatContext(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		conversationalui.proxies.ChatContext result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ContextExtension_ChatContext.toString());
		if (identifier != null) {
			result = conversationalui.proxies.ChatContext.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ContextExtension_ChatContext
	 * @param contextextension_chatcontext
	 */
	public final void setContextExtension_ChatContext(conversationalui.proxies.ChatContext contextextension_chatcontext)
	{
		setContextExtension_ChatContext(getContext(), contextextension_chatcontext);
	}

	/**
	 * Set value of ContextExtension_ChatContext
	 * @param context
	 * @param contextextension_chatcontext
	 */
	public final void setContextExtension_ChatContext(com.mendix.systemwideinterfaces.core.IContext context, conversationalui.proxies.ChatContext contextextension_chatcontext)
	{
		if (contextextension_chatcontext == null) {
			getMendixObject().setValue(context, MemberNames.ContextExtension_ChatContext.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ContextExtension_ChatContext.toString(), contextextension_chatcontext.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return contextExtensionMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstaibot.proxies.ContextExtension that = (myfirstaibot.proxies.ContextExtension) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
