// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstaibot.proxies;

public class DeployedKBRetrieval implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject deployedKBRetrievalMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstAIBot.DeployedKBRetrieval";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		Description("Description"),
		DeployedKBRetrieval_BotConfig("MyFirstAIBot.DeployedKBRetrieval_BotConfig"),
		DeployedKBRetrieval_DeployedKnowledgeBase("MyFirstAIBot.DeployedKBRetrieval_DeployedKnowledgeBase");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public DeployedKBRetrieval(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected DeployedKBRetrieval(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject deployedKBRetrievalMendixObject)
	{
		if (deployedKBRetrievalMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!deployedKBRetrievalMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.deployedKBRetrievalMendixObject = deployedKBRetrievalMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static myfirstaibot.proxies.DeployedKBRetrieval initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstaibot.proxies.DeployedKBRetrieval(context, mendixObject);
	}

	public static myfirstaibot.proxies.DeployedKBRetrieval load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstaibot.proxies.DeployedKBRetrieval.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstaibot.proxies.DeployedKBRetrieval> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> myfirstaibot.proxies.DeployedKBRetrieval.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of Description
	 */
	public final java.lang.String getDescription()
	{
		return getDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of Description
	 */
	public final java.lang.String getDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Description.toString());
	}

	/**
	 * Set value of Description
	 * @param description
	 */
	public final void setDescription(java.lang.String description)
	{
		setDescription(getContext(), description);
	}

	/**
	 * Set value of Description
	 * @param context
	 * @param description
	 */
	public final void setDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String description)
	{
		getMendixObject().setValue(context, MemberNames.Description.toString(), description);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of DeployedKBRetrieval_BotConfig
	 */
	public final myfirstaibot.proxies.BotConfig getDeployedKBRetrieval_BotConfig() throws com.mendix.core.CoreException
	{
		return getDeployedKBRetrieval_BotConfig(getContext());
	}

	/**
	 * @param context
	 * @return value of DeployedKBRetrieval_BotConfig
	 * @throws com.mendix.core.CoreException
	 */
	public final myfirstaibot.proxies.BotConfig getDeployedKBRetrieval_BotConfig(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstaibot.proxies.BotConfig result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DeployedKBRetrieval_BotConfig.toString());
		if (identifier != null) {
			result = myfirstaibot.proxies.BotConfig.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of DeployedKBRetrieval_BotConfig
	 * @param deployedkbretrieval_botconfig
	 */
	public final void setDeployedKBRetrieval_BotConfig(myfirstaibot.proxies.BotConfig deployedkbretrieval_botconfig)
	{
		setDeployedKBRetrieval_BotConfig(getContext(), deployedkbretrieval_botconfig);
	}

	/**
	 * Set value of DeployedKBRetrieval_BotConfig
	 * @param context
	 * @param deployedkbretrieval_botconfig
	 */
	public final void setDeployedKBRetrieval_BotConfig(com.mendix.systemwideinterfaces.core.IContext context, myfirstaibot.proxies.BotConfig deployedkbretrieval_botconfig)
	{
		if (deployedkbretrieval_botconfig == null) {
			getMendixObject().setValue(context, MemberNames.DeployedKBRetrieval_BotConfig.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.DeployedKBRetrieval_BotConfig.toString(), deployedkbretrieval_botconfig.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of DeployedKBRetrieval_DeployedKnowledgeBase
	 */
	public final genaicommons.proxies.DeployedKnowledgeBase getDeployedKBRetrieval_DeployedKnowledgeBase() throws com.mendix.core.CoreException
	{
		return getDeployedKBRetrieval_DeployedKnowledgeBase(getContext());
	}

	/**
	 * @param context
	 * @return value of DeployedKBRetrieval_DeployedKnowledgeBase
	 * @throws com.mendix.core.CoreException
	 */
	public final genaicommons.proxies.DeployedKnowledgeBase getDeployedKBRetrieval_DeployedKnowledgeBase(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		genaicommons.proxies.DeployedKnowledgeBase result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DeployedKBRetrieval_DeployedKnowledgeBase.toString());
		if (identifier != null) {
			result = genaicommons.proxies.DeployedKnowledgeBase.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of DeployedKBRetrieval_DeployedKnowledgeBase
	 * @param deployedkbretrieval_deployedknowledgebase
	 */
	public final void setDeployedKBRetrieval_DeployedKnowledgeBase(genaicommons.proxies.DeployedKnowledgeBase deployedkbretrieval_deployedknowledgebase)
	{
		setDeployedKBRetrieval_DeployedKnowledgeBase(getContext(), deployedkbretrieval_deployedknowledgebase);
	}

	/**
	 * Set value of DeployedKBRetrieval_DeployedKnowledgeBase
	 * @param context
	 * @param deployedkbretrieval_deployedknowledgebase
	 */
	public final void setDeployedKBRetrieval_DeployedKnowledgeBase(com.mendix.systemwideinterfaces.core.IContext context, genaicommons.proxies.DeployedKnowledgeBase deployedkbretrieval_deployedknowledgebase)
	{
		if (deployedkbretrieval_deployedknowledgebase == null) {
			getMendixObject().setValue(context, MemberNames.DeployedKBRetrieval_DeployedKnowledgeBase.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.DeployedKBRetrieval_DeployedKnowledgeBase.toString(), deployedkbretrieval_deployedknowledgebase.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return deployedKBRetrievalMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstaibot.proxies.DeployedKBRetrieval that = (myfirstaibot.proxies.DeployedKBRetrieval) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
