// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstaibot.proxies;

public class DocumentDisplay implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject documentDisplayMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstAIBot.DocumentDisplay";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		NumberOfDocuments("NumberOfDocuments"),
		SupportsMultipleFiles("SupportsMultipleFiles"),
		ContentLength("ContentLength"),
		DocumentDisplay_ContextExtension("MyFirstAIBot.DocumentDisplay_ContextExtension");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public DocumentDisplay(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected DocumentDisplay(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject documentDisplayMendixObject)
	{
		if (documentDisplayMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!documentDisplayMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.documentDisplayMendixObject = documentDisplayMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static myfirstaibot.proxies.DocumentDisplay initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstaibot.proxies.DocumentDisplay(context, mendixObject);
	}

	public static myfirstaibot.proxies.DocumentDisplay load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstaibot.proxies.DocumentDisplay.initialize(context, mendixObject);
	}

	/**
	 * @return value of NumberOfDocuments
	 */
	public final java.lang.Integer getNumberOfDocuments()
	{
		return getNumberOfDocuments(getContext());
	}

	/**
	 * @param context
	 * @return value of NumberOfDocuments
	 */
	public final java.lang.Integer getNumberOfDocuments(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.NumberOfDocuments.toString());
	}

	/**
	 * Set value of NumberOfDocuments
	 * @param numberofdocuments
	 */
	public final void setNumberOfDocuments(java.lang.Integer numberofdocuments)
	{
		setNumberOfDocuments(getContext(), numberofdocuments);
	}

	/**
	 * Set value of NumberOfDocuments
	 * @param context
	 * @param numberofdocuments
	 */
	public final void setNumberOfDocuments(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer numberofdocuments)
	{
		getMendixObject().setValue(context, MemberNames.NumberOfDocuments.toString(), numberofdocuments);
	}

	/**
	 * @return value of SupportsMultipleFiles
	 */
	public final java.lang.Boolean getSupportsMultipleFiles()
	{
		return getSupportsMultipleFiles(getContext());
	}

	/**
	 * @param context
	 * @return value of SupportsMultipleFiles
	 */
	public final java.lang.Boolean getSupportsMultipleFiles(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.SupportsMultipleFiles.toString());
	}

	/**
	 * Set value of SupportsMultipleFiles
	 * @param supportsmultiplefiles
	 */
	public final void setSupportsMultipleFiles(java.lang.Boolean supportsmultiplefiles)
	{
		setSupportsMultipleFiles(getContext(), supportsmultiplefiles);
	}

	/**
	 * Set value of SupportsMultipleFiles
	 * @param context
	 * @param supportsmultiplefiles
	 */
	public final void setSupportsMultipleFiles(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean supportsmultiplefiles)
	{
		getMendixObject().setValue(context, MemberNames.SupportsMultipleFiles.toString(), supportsmultiplefiles);
	}

	/**
	 * @return value of ContentLength
	 */
	public final java.lang.Integer getContentLength()
	{
		return getContentLength(getContext());
	}

	/**
	 * @param context
	 * @return value of ContentLength
	 */
	public final java.lang.Integer getContentLength(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.ContentLength.toString());
	}

	/**
	 * Set value of ContentLength
	 * @param contentlength
	 */
	public final void setContentLength(java.lang.Integer contentlength)
	{
		setContentLength(getContext(), contentlength);
	}

	/**
	 * Set value of ContentLength
	 * @param context
	 * @param contentlength
	 */
	public final void setContentLength(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer contentlength)
	{
		getMendixObject().setValue(context, MemberNames.ContentLength.toString(), contentlength);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of DocumentDisplay_ContextExtension
	 */
	public final myfirstaibot.proxies.ContextExtension getDocumentDisplay_ContextExtension() throws com.mendix.core.CoreException
	{
		return getDocumentDisplay_ContextExtension(getContext());
	}

	/**
	 * @param context
	 * @return value of DocumentDisplay_ContextExtension
	 * @throws com.mendix.core.CoreException
	 */
	public final myfirstaibot.proxies.ContextExtension getDocumentDisplay_ContextExtension(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstaibot.proxies.ContextExtension result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DocumentDisplay_ContextExtension.toString());
		if (identifier != null) {
			result = myfirstaibot.proxies.ContextExtension.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of DocumentDisplay_ContextExtension
	 * @param documentdisplay_contextextension
	 */
	public final void setDocumentDisplay_ContextExtension(myfirstaibot.proxies.ContextExtension documentdisplay_contextextension)
	{
		setDocumentDisplay_ContextExtension(getContext(), documentdisplay_contextextension);
	}

	/**
	 * Set value of DocumentDisplay_ContextExtension
	 * @param context
	 * @param documentdisplay_contextextension
	 */
	public final void setDocumentDisplay_ContextExtension(com.mendix.systemwideinterfaces.core.IContext context, myfirstaibot.proxies.ContextExtension documentdisplay_contextextension)
	{
		if (documentdisplay_contextextension == null) {
			getMendixObject().setValue(context, MemberNames.DocumentDisplay_ContextExtension.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.DocumentDisplay_ContextExtension.toString(), documentdisplay_contextextension.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return documentDisplayMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstaibot.proxies.DocumentDisplay that = (myfirstaibot.proxies.DocumentDisplay) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
