// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstaibot.proxies;

public enum ENUM_ActionMicroflowSelection
{
	ChatContext_ChatWithHistory_ActionMicroflow("dd89f2c1-87f7-5892-9033-73b251d88dba"),
	ChatContext_BedrockRetrieveAndGenerate_ActionMicroflow("a6810b9f-ea20-5f45-b66d-d83b6086c890");

	private final java.lang.String i18nCaptionKey;
	
	private ENUM_ActionMicroflowSelection(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
