// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstaibot.proxies;

public enum ENUM_InitialUserPromptCategory
{
	PersonalAssistant("3b07825e-02c6-450a-a661-783abcf33737"),
	TextWriter("82fd01ad-5e4f-41f7-a91b-58350043f342"),
	BrainstormingAssistant("150514fb-0db1-4fea-8945-7a902f926728"),
	LinkedInWriter("ff606a89-59e9-4bcc-b074-cdac13810314");

	private final java.lang.String i18nCaptionKey;
	
	private ENUM_InitialUserPromptCategory(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
