// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstaibot.proxies;

public class InitialUserPrompt implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject initialUserPromptMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstAIBot.InitialUserPrompt";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Order("Order"),
		Header("Header"),
		Category("Category"),
		UserPrompt("UserPrompt"),
		InitialUserPrompt_Instruction("MyFirstAIBot.InitialUserPrompt_Instruction");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public InitialUserPrompt(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected InitialUserPrompt(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject initialUserPromptMendixObject)
	{
		if (initialUserPromptMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!initialUserPromptMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.initialUserPromptMendixObject = initialUserPromptMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static myfirstaibot.proxies.InitialUserPrompt initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstaibot.proxies.InitialUserPrompt(context, mendixObject);
	}

	public static myfirstaibot.proxies.InitialUserPrompt load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstaibot.proxies.InitialUserPrompt.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstaibot.proxies.InitialUserPrompt> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> myfirstaibot.proxies.InitialUserPrompt.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of Order
	 */
	public final java.lang.Integer getOrder()
	{
		return getOrder(getContext());
	}

	/**
	 * @param context
	 * @return value of Order
	 */
	public final java.lang.Integer getOrder(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Order.toString());
	}

	/**
	 * Set value of Order
	 * @param order
	 */
	public final void setOrder(java.lang.Integer order)
	{
		setOrder(getContext(), order);
	}

	/**
	 * Set value of Order
	 * @param context
	 * @param order
	 */
	public final void setOrder(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer order)
	{
		getMendixObject().setValue(context, MemberNames.Order.toString(), order);
	}

	/**
	 * @return value of Header
	 */
	public final java.lang.String getHeader()
	{
		return getHeader(getContext());
	}

	/**
	 * @param context
	 * @return value of Header
	 */
	public final java.lang.String getHeader(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Header.toString());
	}

	/**
	 * Set value of Header
	 * @param header
	 */
	public final void setHeader(java.lang.String header)
	{
		setHeader(getContext(), header);
	}

	/**
	 * Set value of Header
	 * @param context
	 * @param header
	 */
	public final void setHeader(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String header)
	{
		getMendixObject().setValue(context, MemberNames.Header.toString(), header);
	}

	/**
	 * Get value of Category
	 * @param category
	 */
	public final myfirstaibot.proxies.ENUM_InitialUserPromptCategory getCategory()
	{
		return getCategory(getContext());
	}

	/**
	 * @param context
	 * @return value of Category
	 */
	public final myfirstaibot.proxies.ENUM_InitialUserPromptCategory getCategory(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Category.toString());
		if (obj == null) {
			return null;
		}
		return myfirstaibot.proxies.ENUM_InitialUserPromptCategory.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Category
	 * @param category
	 */
	public final void setCategory(myfirstaibot.proxies.ENUM_InitialUserPromptCategory category)
	{
		setCategory(getContext(), category);
	}

	/**
	 * Set value of Category
	 * @param context
	 * @param category
	 */
	public final void setCategory(com.mendix.systemwideinterfaces.core.IContext context, myfirstaibot.proxies.ENUM_InitialUserPromptCategory category)
	{
		if (category != null) {
			getMendixObject().setValue(context, MemberNames.Category.toString(), category.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.Category.toString(), null);
		}
	}

	/**
	 * @return value of UserPrompt
	 */
	public final java.lang.String getUserPrompt()
	{
		return getUserPrompt(getContext());
	}

	/**
	 * @param context
	 * @return value of UserPrompt
	 */
	public final java.lang.String getUserPrompt(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.UserPrompt.toString());
	}

	/**
	 * Set value of UserPrompt
	 * @param userprompt
	 */
	public final void setUserPrompt(java.lang.String userprompt)
	{
		setUserPrompt(getContext(), userprompt);
	}

	/**
	 * Set value of UserPrompt
	 * @param context
	 * @param userprompt
	 */
	public final void setUserPrompt(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String userprompt)
	{
		getMendixObject().setValue(context, MemberNames.UserPrompt.toString(), userprompt);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of InitialUserPrompt_Instruction
	 */
	public final myfirstaibot.proxies.Instruction getInitialUserPrompt_Instruction() throws com.mendix.core.CoreException
	{
		return getInitialUserPrompt_Instruction(getContext());
	}

	/**
	 * @param context
	 * @return value of InitialUserPrompt_Instruction
	 * @throws com.mendix.core.CoreException
	 */
	public final myfirstaibot.proxies.Instruction getInitialUserPrompt_Instruction(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstaibot.proxies.Instruction result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.InitialUserPrompt_Instruction.toString());
		if (identifier != null) {
			result = myfirstaibot.proxies.Instruction.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of InitialUserPrompt_Instruction
	 * @param initialuserprompt_instruction
	 */
	public final void setInitialUserPrompt_Instruction(myfirstaibot.proxies.Instruction initialuserprompt_instruction)
	{
		setInitialUserPrompt_Instruction(getContext(), initialuserprompt_instruction);
	}

	/**
	 * Set value of InitialUserPrompt_Instruction
	 * @param context
	 * @param initialuserprompt_instruction
	 */
	public final void setInitialUserPrompt_Instruction(com.mendix.systemwideinterfaces.core.IContext context, myfirstaibot.proxies.Instruction initialuserprompt_instruction)
	{
		if (initialuserprompt_instruction == null) {
			getMendixObject().setValue(context, MemberNames.InitialUserPrompt_Instruction.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.InitialUserPrompt_Instruction.toString(), initialuserprompt_instruction.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return initialUserPromptMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstaibot.proxies.InitialUserPrompt that = (myfirstaibot.proxies.InitialUserPrompt) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
