// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstaibot.proxies;

public class Instruction implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject instructionMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstAIBot.Instruction";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Instruction("Instruction"),
		DisplayName("DisplayName"),
		IsCustom("IsCustom");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Instruction(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Instruction(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject instructionMendixObject)
	{
		if (instructionMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!instructionMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.instructionMendixObject = instructionMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static myfirstaibot.proxies.Instruction initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstaibot.proxies.Instruction(context, mendixObject);
	}

	public static myfirstaibot.proxies.Instruction load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstaibot.proxies.Instruction.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstaibot.proxies.Instruction> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> myfirstaibot.proxies.Instruction.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of Instruction
	 */
	public final java.lang.String getInstruction()
	{
		return getInstruction(getContext());
	}

	/**
	 * @param context
	 * @return value of Instruction
	 */
	public final java.lang.String getInstruction(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Instruction.toString());
	}

	/**
	 * Set value of Instruction
	 * @param instruction
	 */
	public final void setInstruction(java.lang.String instruction)
	{
		setInstruction(getContext(), instruction);
	}

	/**
	 * Set value of Instruction
	 * @param context
	 * @param instruction
	 */
	public final void setInstruction(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String instruction)
	{
		getMendixObject().setValue(context, MemberNames.Instruction.toString(), instruction);
	}

	/**
	 * @return value of DisplayName
	 */
	public final java.lang.String getDisplayName()
	{
		return getDisplayName(getContext());
	}

	/**
	 * @param context
	 * @return value of DisplayName
	 */
	public final java.lang.String getDisplayName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DisplayName.toString());
	}

	/**
	 * Set value of DisplayName
	 * @param displayname
	 */
	public final void setDisplayName(java.lang.String displayname)
	{
		setDisplayName(getContext(), displayname);
	}

	/**
	 * Set value of DisplayName
	 * @param context
	 * @param displayname
	 */
	public final void setDisplayName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String displayname)
	{
		getMendixObject().setValue(context, MemberNames.DisplayName.toString(), displayname);
	}

	/**
	 * @return value of IsCustom
	 */
	public final java.lang.Boolean getIsCustom()
	{
		return getIsCustom(getContext());
	}

	/**
	 * @param context
	 * @return value of IsCustom
	 */
	public final java.lang.Boolean getIsCustom(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsCustom.toString());
	}

	/**
	 * Set value of IsCustom
	 * @param iscustom
	 */
	public final void setIsCustom(java.lang.Boolean iscustom)
	{
		setIsCustom(getContext(), iscustom);
	}

	/**
	 * Set value of IsCustom
	 * @param context
	 * @param iscustom
	 */
	public final void setIsCustom(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean iscustom)
	{
		getMendixObject().setValue(context, MemberNames.IsCustom.toString(), iscustom);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return instructionMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstaibot.proxies.Instruction that = (myfirstaibot.proxies.Instruction) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
