// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nanoflowcommons.proxies;

public enum GeocodingProvider
{
	Google("6ffb1139-68ab-49b4-9118-e41fdc63d269"),
	Geocodio("8669f8f3-16a4-4240-ab5b-9ee25d7132a5"),
	LocationIQ("d62fcf8a-de52-4f0f-a32d-1af753a8185b"),
	MapQuest("8d84e67e-cbbb-497e-b5d0-4497988580eb");

	private final java.lang.String i18nCaptionKey;
	
	private GeocodingProvider(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
