// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mistralconnector.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the MistralConnector module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_MistralConfiguration_DuplicateBuilder(
		mistralconnector.proxies.MistralConfiguration _mistralConfiguration_Existing
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MistralConnector.ACT_MistralConfiguration_Duplicate");
		builder = builder.withParam("MistralConfiguration_Existing", _mistralConfiguration_Existing);
		return builder;
	}

	public static void aCT_MistralConfiguration_Duplicate(
		IContext context,
		mistralconnector.proxies.MistralConfiguration _mistralConfiguration_Existing
	)
	{
		aCT_MistralConfiguration_DuplicateBuilder(
				_mistralConfiguration_Existing
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_MistralConfiguration_EditBuilder(
		mistralconnector.proxies.MistralConfiguration _mistralConfiguration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MistralConnector.ACT_MistralConfiguration_Edit");
		builder = builder.withParam("MistralConfiguration", _mistralConfiguration);
		return builder;
	}

	public static void aCT_MistralConfiguration_Edit(
		IContext context,
		mistralconnector.proxies.MistralConfiguration _mistralConfiguration
	)
	{
		aCT_MistralConfiguration_EditBuilder(
				_mistralConfiguration
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_MistralConfiguration_ManageDeployedModelsBuilder(
		mistralconnector.proxies.MistralConfiguration _mistralConfiguration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MistralConnector.ACT_MistralConfiguration_ManageDeployedModels");
		builder = builder.withParam("MistralConfiguration", _mistralConfiguration);
		return builder;
	}

	public static void aCT_MistralConfiguration_ManageDeployedModels(
		IContext context,
		mistralconnector.proxies.MistralConfiguration _mistralConfiguration
	)
	{
		aCT_MistralConfiguration_ManageDeployedModelsBuilder(
				_mistralConfiguration
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_MistralConfiguration_NewBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MistralConnector.ACT_MistralConfiguration_New");
		return builder;
	}

	public static void aCT_MistralConfiguration_New(IContext context)
	{
		aCT_MistralConfiguration_NewBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_MistralConfiguration_SaveBuilder(
		mistralconnector.proxies.MistralConfiguration _mistralConfiguration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MistralConnector.ACT_MistralConfiguration_Save");
		builder = builder.withParam("MistralConfiguration", _mistralConfiguration);
		return builder;
	}

	public static void aCT_MistralConfiguration_Save(
		IContext context,
		mistralconnector.proxies.MistralConfiguration _mistralConfiguration
	)
	{
		aCT_MistralConfiguration_SaveBuilder(
				_mistralConfiguration
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_MistralConfiguration_ShowTestBuilder(
		mistralconnector.proxies.MistralConfiguration _mistralConfiguration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MistralConnector.ACT_MistralConfiguration_ShowTest");
		builder = builder.withParam("MistralConfiguration", _mistralConfiguration);
		return builder;
	}

	public static void aCT_MistralConfiguration_ShowTest(
		IContext context,
		mistralconnector.proxies.MistralConfiguration _mistralConfiguration
	)
	{
		aCT_MistralConfiguration_ShowTestBuilder(
				_mistralConfiguration
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_MistralConfiguration_SyncDeployedModelsBuilder(
		mistralconnector.proxies.MistralConfiguration _mistralConfiguration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MistralConnector.ACT_MistralConfiguration_SyncDeployedModels");
		builder = builder.withParam("MistralConfiguration", _mistralConfiguration);
		return builder;
	}

	public static void aCT_MistralConfiguration_SyncDeployedModels(
		IContext context,
		mistralconnector.proxies.MistralConfiguration _mistralConfiguration
	)
	{
		aCT_MistralConfiguration_SyncDeployedModelsBuilder(
				_mistralConfiguration
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_MistralDeployedModel_DeleteBuilder(
		mistralconnector.proxies.MistralDeployedModel _mistralDeployedModel
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MistralConnector.ACT_MistralDeployedModel_Delete");
		builder = builder.withParam("MistralDeployedModel", _mistralDeployedModel);
		return builder;
	}

	public static void aCT_MistralDeployedModel_Delete(
		IContext context,
		mistralconnector.proxies.MistralDeployedModel _mistralDeployedModel
	)
	{
		aCT_MistralDeployedModel_DeleteBuilder(
				_mistralDeployedModel
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_MistralDeployedModel_EditBuilder(
		mistralconnector.proxies.MistralDeployedModel _mistralDeployedModel
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MistralConnector.ACT_MistralDeployedModel_Edit");
		builder = builder.withParam("MistralDeployedModel", _mistralDeployedModel);
		return builder;
	}

	public static void aCT_MistralDeployedModel_Edit(
		IContext context,
		mistralconnector.proxies.MistralDeployedModel _mistralDeployedModel
	)
	{
		aCT_MistralDeployedModel_EditBuilder(
				_mistralDeployedModel
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_MistralDeployedModel_NewBuilder(
		mistralconnector.proxies.MistralConfiguration _mistralConfiguration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MistralConnector.ACT_MistralDeployedModel_New");
		builder = builder.withParam("MistralConfiguration", _mistralConfiguration);
		return builder;
	}

	public static void aCT_MistralDeployedModel_New(
		IContext context,
		mistralconnector.proxies.MistralConfiguration _mistralConfiguration
	)
	{
		aCT_MistralDeployedModel_NewBuilder(
				_mistralConfiguration
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_MistralDeployedModel_SaveBuilder(
		mistralconnector.proxies.MistralDeployedModel _mistralDeployedModel
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MistralConnector.ACT_MistralDeployedModel_Save");
		builder = builder.withParam("MistralDeployedModel", _mistralDeployedModel);
		return builder;
	}

	public static void aCT_MistralDeployedModel_Save(
		IContext context,
		mistralconnector.proxies.MistralDeployedModel _mistralDeployedModel
	)
	{
		aCT_MistralDeployedModel_SaveBuilder(
				_mistralDeployedModel
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder mistralConfiguration_CreateBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MistralConnector.MistralConfiguration_Create");
		return builder;
	}

	public static mistralconnector.proxies.MistralConfiguration mistralConfiguration_Create(IContext context)
	{
		Object result = mistralConfiguration_CreateBuilder().execute(context);
		return result == null ? null : mistralconnector.proxies.MistralConfiguration.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder mistralConfiguration_CreateAndCopyValuesBuilder(
		mistralconnector.proxies.MistralConfiguration _mistralConfiguration_Existing
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MistralConnector.MistralConfiguration_CreateAndCopyValues");
		builder = builder.withParam("MistralConfiguration_Existing", _mistralConfiguration_Existing);
		return builder;
	}

	public static mistralconnector.proxies.MistralConfiguration mistralConfiguration_CreateAndCopyValues(
		IContext context,
		mistralconnector.proxies.MistralConfiguration _mistralConfiguration_Existing
	)
	{
		Object result = mistralConfiguration_CreateAndCopyValuesBuilder(
				_mistralConfiguration_Existing
			)
			.execute(context);
		return result == null ? null : mistralconnector.proxies.MistralConfiguration.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder mistralConfiguration_CreateAvailableDeployedModelsBuilder(
		mistralconnector.proxies.MistralConfiguration _mistralConfiguration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MistralConnector.MistralConfiguration_CreateAvailableDeployedModels");
		builder = builder.withParam("MistralConfiguration", _mistralConfiguration);
		return builder;
	}

	public static void mistralConfiguration_CreateAvailableDeployedModels(
		IContext context,
		mistralconnector.proxies.MistralConfiguration _mistralConfiguration
	)
	{
		mistralConfiguration_CreateAvailableDeployedModelsBuilder(
				_mistralConfiguration
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder mistralConfiguration_RefreshBuilder(
		mistralconnector.proxies.MistralConfiguration _mistralConfiguration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MistralConnector.MistralConfiguration_Refresh");
		builder = builder.withParam("MistralConfiguration", _mistralConfiguration);
		return builder;
	}

	public static void mistralConfiguration_Refresh(
		IContext context,
		mistralconnector.proxies.MistralConfiguration _mistralConfiguration
	)
	{
		mistralConfiguration_RefreshBuilder(
				_mistralConfiguration
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder mistralConfiguration_SaveBuilder(
		mistralconnector.proxies.MistralConfiguration _mistralConfiguration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MistralConnector.MistralConfiguration_Save");
		builder = builder.withParam("MistralConfiguration", _mistralConfiguration);
		return builder;
	}

	public static boolean mistralConfiguration_Save(
		IContext context,
		mistralconnector.proxies.MistralConfiguration _mistralConfiguration
	)
	{
		Object result = mistralConfiguration_SaveBuilder(
				_mistralConfiguration
			)
			.execute(context);
		return (boolean) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder mistralConfiguration_ValidateBuilder(
		mistralconnector.proxies.MistralConfiguration _mistralConfiguration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MistralConnector.MistralConfiguration_Validate");
		builder = builder.withParam("MistralConfiguration", _mistralConfiguration);
		return builder;
	}

	public static boolean mistralConfiguration_Validate(
		IContext context,
		mistralconnector.proxies.MistralConfiguration _mistralConfiguration
	)
	{
		Object result = mistralConfiguration_ValidateBuilder(
				_mistralConfiguration
			)
			.execute(context);
		return (boolean) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder mistralDeployedModel_CreateBuilder(
		openaiconnector.proxies.Configuration _configuration,
		java.lang.String _model,
		java.lang.String _architecture,
		genaicommons.proxies.ENUM_ModelModality _outputModality,
		java.lang.String _apiVersion,
		java.lang.String _displayName,
		genaicommons.proxies.ENUM_ModelSupport _supportsSystemPrompt,
		genaicommons.proxies.ENUM_ModelSupport _supportsFunctionCalling,
		genaicommons.proxies.ENUM_ModelSupport _supportsConversationHistory,
		java.util.List<genaicommons.proxies.InputModality> _inputModalityList
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MistralConnector.MistralDeployedModel_Create");
		builder = builder.withParam("Configuration", _configuration);
		builder = builder.withParam("Model", _model);
		builder = builder.withParam("Architecture", _architecture);
		builder = builder.withParam("OutputModality", _outputModality == null ? null : _outputModality.name());
		builder = builder.withParam("ApiVersion", _apiVersion);
		builder = builder.withParam("DisplayName", _displayName);
		builder = builder.withParam("SupportsSystemPrompt", _supportsSystemPrompt == null ? null : _supportsSystemPrompt.name());
		builder = builder.withParam("SupportsFunctionCalling", _supportsFunctionCalling == null ? null : _supportsFunctionCalling.name());
		builder = builder.withParam("SupportsConversationHistory", _supportsConversationHistory == null ? null : _supportsConversationHistory.name());
		builder = builder.withParam("InputModalityList", _inputModalityList);
		return builder;
	}

	public static mistralconnector.proxies.MistralDeployedModel mistralDeployedModel_Create(
		IContext context,
		openaiconnector.proxies.Configuration _configuration,
		java.lang.String _model,
		java.lang.String _architecture,
		genaicommons.proxies.ENUM_ModelModality _outputModality,
		java.lang.String _apiVersion,
		java.lang.String _displayName,
		genaicommons.proxies.ENUM_ModelSupport _supportsSystemPrompt,
		genaicommons.proxies.ENUM_ModelSupport _supportsFunctionCalling,
		genaicommons.proxies.ENUM_ModelSupport _supportsConversationHistory,
		java.util.List<genaicommons.proxies.InputModality> _inputModalityList
	)
	{
		Object result = mistralDeployedModel_CreateBuilder(
				_configuration,
				_model,
				_architecture,
				_outputModality,
				_apiVersion,
				_displayName,
				_supportsSystemPrompt,
				_supportsFunctionCalling,
				_supportsConversationHistory,
				_inputModalityList
			)
			.execute(context);
		return result == null ? null : mistralconnector.proxies.MistralDeployedModel.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder mistralDeployedModel_DeleteAllFromConfigBuilder(
		mistralconnector.proxies.MistralConfiguration _mistralConfiguration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MistralConnector.MistralDeployedModel_DeleteAllFromConfig");
		builder = builder.withParam("MistralConfiguration", _mistralConfiguration);
		return builder;
	}

	public static void mistralDeployedModel_DeleteAllFromConfig(
		IContext context,
		mistralconnector.proxies.MistralConfiguration _mistralConfiguration
	)
	{
		mistralDeployedModel_DeleteAllFromConfigBuilder(
				_mistralConfiguration
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder mistralDeployedModel_ValidateBuilder(
		mistralconnector.proxies.MistralDeployedModel _mistralDeployedModel
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MistralConnector.MistralDeployedModel_Validate");
		builder = builder.withParam("MistralDeployedModel", _mistralDeployedModel);
		return builder;
	}

	public static boolean mistralDeployedModel_Validate(
		IContext context,
		mistralconnector.proxies.MistralDeployedModel _mistralDeployedModel
	)
	{
		Object result = mistralDeployedModel_ValidateBuilder(
				_mistralDeployedModel
			)
			.execute(context);
		return (boolean) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder mistralModel_CleanListByNameFilterBuilder(
		java.util.List<mistralconnector.proxies.MistralModel> _mistralModelList
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MistralConnector.MistralModel_CleanListByNameFilter");
		builder = builder.withParam("MistralModelList", _mistralModelList);
		return builder;
	}

	public static void mistralModel_CleanListByNameFilter(
		IContext context,
		java.util.List<mistralconnector.proxies.MistralModel> _mistralModelList
	)
	{
		mistralModel_CleanListByNameFilterBuilder(
				_mistralModelList
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder mistralModel_CreateDeployedModelListBuilder(
		java.util.List<mistralconnector.proxies.MistralModel> _mistralModelList,
		java.util.List<openaiconnector.proxies.OpenAIDeployedModel> _mistralDeployedModelList_ToCommit,
		mistralconnector.proxies.MistralConfiguration _mistralConfiguration,
		java.util.List<genaicommons.proxies.InputModality> _inputModalityList,
		genaicommons.proxies.ENUM_ModelModality _outputModality
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MistralConnector.MistralModel_CreateDeployedModelList");
		builder = builder.withParam("MistralModelList", _mistralModelList);
		builder = builder.withParam("MistralDeployedModelList_ToCommit", _mistralDeployedModelList_ToCommit);
		builder = builder.withParam("MistralConfiguration", _mistralConfiguration);
		builder = builder.withParam("InputModalityList", _inputModalityList);
		builder = builder.withParam("OutputModality", _outputModality == null ? null : _outputModality.name());
		return builder;
	}

	public static void mistralModel_CreateDeployedModelList(
		IContext context,
		java.util.List<mistralconnector.proxies.MistralModel> _mistralModelList,
		java.util.List<openaiconnector.proxies.OpenAIDeployedModel> _mistralDeployedModelList_ToCommit,
		mistralconnector.proxies.MistralConfiguration _mistralConfiguration,
		java.util.List<genaicommons.proxies.InputModality> _inputModalityList,
		genaicommons.proxies.ENUM_ModelModality _outputModality
	)
	{
		mistralModel_CreateDeployedModelListBuilder(
				_mistralModelList,
				_mistralDeployedModelList_ToCommit,
				_mistralConfiguration,
				_inputModalityList,
				_outputModality
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder mistralModel_FilterListBySearchStringBuilder(
		java.util.List<mistralconnector.proxies.MistralModel> _mistralModelList,
		java.lang.String _searchString
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MistralConnector.MistralModel_FilterListBySearchString");
		builder = builder.withParam("MistralModelList", _mistralModelList);
		builder = builder.withParam("SearchString", _searchString);
		return builder;
	}

	public static java.util.List<mistralconnector.proxies.MistralModel> mistralModel_FilterListBySearchString(
		IContext context,
		java.util.List<mistralconnector.proxies.MistralModel> _mistralModelList,
		java.lang.String _searchString
	)
	{
		Object result = mistralModel_FilterListBySearchStringBuilder(
				_mistralModelList,
				_searchString
			)
			.execute(context);
		return result == null ? null : com.mendix.utils.ListUtils.map((java.util.List<IMendixObject>) result, obj -> mistralconnector.proxies.MistralModel.initialize(context, obj));
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder mistralModel_GetListBuilder(
		mistralconnector.proxies.MistralConfiguration _mistralConfiguration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MistralConnector.MistralModel_GetList");
		builder = builder.withParam("MistralConfiguration", _mistralConfiguration);
		return builder;
	}

	public static java.util.List<mistralconnector.proxies.MistralModel> mistralModel_GetList(
		IContext context,
		mistralconnector.proxies.MistralConfiguration _mistralConfiguration
	)
	{
		Object result = mistralModel_GetListBuilder(
				_mistralConfiguration
			)
			.execute(context);
		return result == null ? null : com.mendix.utils.ListUtils.map((java.util.List<IMendixObject>) result, obj -> mistralconnector.proxies.MistralModel.initialize(context, obj));
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder mistralModel_RemoveModelFromListByNameBuilder(
		java.util.List<mistralconnector.proxies.MistralModel> _mistralModelList,
		java.lang.String _modelName
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MistralConnector.MistralModel_RemoveModelFromListByName");
		builder = builder.withParam("MistralModelList", _mistralModelList);
		builder = builder.withParam("ModelName", _modelName);
		return builder;
	}

	public static java.util.List<mistralconnector.proxies.MistralModel> mistralModel_RemoveModelFromListByName(
		IContext context,
		java.util.List<mistralconnector.proxies.MistralModel> _mistralModelList,
		java.lang.String _modelName
	)
	{
		Object result = mistralModel_RemoveModelFromListByNameBuilder(
				_mistralModelList,
				_modelName
			)
			.execute(context);
		return result == null ? null : com.mendix.utils.ListUtils.map((java.util.List<IMendixObject>) result, obj -> mistralconnector.proxies.MistralModel.initialize(context, obj));
	}
}
