// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mistralconnector.proxies;

/**
 * Model object as returned in a list from GET https://api.mistral.ai/v1/models.
 */
public class MistralModel implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject mistralModelMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MistralConnector.MistralModel";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Created("Created"),
		Name("Name"),
		Completion_Chat("Completion_Chat"),
		Function_Calling("Function_Calling"),
		Vision("Vision");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public MistralModel(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected MistralModel(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mistralModelMendixObject)
	{
		if (mistralModelMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!mistralModelMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.mistralModelMendixObject = mistralModelMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static mistralconnector.proxies.MistralModel initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new mistralconnector.proxies.MistralModel(context, mendixObject);
	}

	public static mistralconnector.proxies.MistralModel load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return mistralconnector.proxies.MistralModel.initialize(context, mendixObject);
	}

	/**
	 * @return value of Created
	 */
	public final java.lang.Integer getCreated()
	{
		return getCreated(getContext());
	}

	/**
	 * @param context
	 * @return value of Created
	 */
	public final java.lang.Integer getCreated(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Created.toString());
	}

	/**
	 * Set value of Created
	 * @param created
	 */
	public final void setCreated(java.lang.Integer created)
	{
		setCreated(getContext(), created);
	}

	/**
	 * Set value of Created
	 * @param context
	 * @param created
	 */
	public final void setCreated(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer created)
	{
		getMendixObject().setValue(context, MemberNames.Created.toString(), created);
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of Completion_Chat
	 */
	public final java.lang.Boolean getCompletion_Chat()
	{
		return getCompletion_Chat(getContext());
	}

	/**
	 * @param context
	 * @return value of Completion_Chat
	 */
	public final java.lang.Boolean getCompletion_Chat(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Completion_Chat.toString());
	}

	/**
	 * Set value of Completion_Chat
	 * @param completion_chat
	 */
	public final void setCompletion_Chat(java.lang.Boolean completion_chat)
	{
		setCompletion_Chat(getContext(), completion_chat);
	}

	/**
	 * Set value of Completion_Chat
	 * @param context
	 * @param completion_chat
	 */
	public final void setCompletion_Chat(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean completion_chat)
	{
		getMendixObject().setValue(context, MemberNames.Completion_Chat.toString(), completion_chat);
	}

	/**
	 * @return value of Function_Calling
	 */
	public final java.lang.Boolean getFunction_Calling()
	{
		return getFunction_Calling(getContext());
	}

	/**
	 * @param context
	 * @return value of Function_Calling
	 */
	public final java.lang.Boolean getFunction_Calling(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Function_Calling.toString());
	}

	/**
	 * Set value of Function_Calling
	 * @param function_calling
	 */
	public final void setFunction_Calling(java.lang.Boolean function_calling)
	{
		setFunction_Calling(getContext(), function_calling);
	}

	/**
	 * Set value of Function_Calling
	 * @param context
	 * @param function_calling
	 */
	public final void setFunction_Calling(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean function_calling)
	{
		getMendixObject().setValue(context, MemberNames.Function_Calling.toString(), function_calling);
	}

	/**
	 * @return value of Vision
	 */
	public final java.lang.Boolean getVision()
	{
		return getVision(getContext());
	}

	/**
	 * @param context
	 * @return value of Vision
	 */
	public final java.lang.Boolean getVision(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Vision.toString());
	}

	/**
	 * Set value of Vision
	 * @param vision
	 */
	public final void setVision(java.lang.Boolean vision)
	{
		setVision(getContext(), vision);
	}

	/**
	 * Set value of Vision
	 * @param context
	 * @param vision
	 */
	public final void setVision(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean vision)
	{
		getMendixObject().setValue(context, MemberNames.Vision.toString(), vision);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return mistralModelMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final mistralconnector.proxies.MistralModel that = (mistralconnector.proxies.MistralModel) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
