// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mistralconnector.proxies;

/**
 * OpenAIDeployedModel is a specialization of GenAICommons.DeployedModel, which is associated to the Configuration. To make the operations more compatible and interchangeable with operations from other GenAI connectors based on the GenAI commons module, the operations technically accept DeployedModel objects, but internally required to be of the specialization OpenAIDeployedModel.
 */
public class MistralDeployedModel extends openaiconnector.proxies.OpenAIDeployedModel
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MistralConnector.MistralDeployedModel";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		AzureApiVersion("AzureApiVersion"),
		DisplayName("DisplayName"),
		Architecture("Architecture"),
		Model("Model"),
		OutputModality("OutputModality"),
		Microflow("Microflow"),
		SupportsSystemPrompt("SupportsSystemPrompt"),
		SupportsConversationsWithHistory("SupportsConversationsWithHistory"),
		SupportsFunctionCalling("SupportsFunctionCalling"),
		IsActive("IsActive"),
		OpenAIDeployedModel_Configuration("OpenAIConnector.OpenAIDeployedModel_Configuration"),
		DeployedModel_InputModality("GenAICommons.DeployedModel_InputModality");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public MistralDeployedModel(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected MistralDeployedModel(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mistralDeployedModelMendixObject)
	{
		super(context, mistralDeployedModelMendixObject);
		if (!mistralDeployedModelMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static mistralconnector.proxies.MistralDeployedModel initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new mistralconnector.proxies.MistralDeployedModel(context, mendixObject);
	}

	public static mistralconnector.proxies.MistralDeployedModel load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return mistralconnector.proxies.MistralDeployedModel.initialize(context, mendixObject);
	}

	public static java.util.List<mistralconnector.proxies.MistralDeployedModel> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> mistralconnector.proxies.MistralDeployedModel.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final mistralconnector.proxies.MistralDeployedModel that = (mistralconnector.proxies.MistralDeployedModel) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
