// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package awsauthentication.proxies;

/**
 * This entity is an abstract entity that all requests should inherit from. It will allow for the usage of custom client settings. 
 */
public class AbstractRequest implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject abstractRequestMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AWSAuthentication.AbstractRequest";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		AbstractRequest_BasicClientConfig("AWSAuthentication.AbstractRequest_BasicClientConfig");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public AbstractRequest(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected AbstractRequest(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject abstractRequestMendixObject)
	{
		if (abstractRequestMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!abstractRequestMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.abstractRequestMendixObject = abstractRequestMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static awsauthentication.proxies.AbstractRequest initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		if (mendixObject.isInstanceOf("AmazonBedrockConnector.ChatCompletionsRequest_Extension")) {
			return amazonbedrockconnector.proxies.ChatCompletionsRequest_Extension.initialize(context, mendixObject);
		}
		if (mendixObject.isInstanceOf("AmazonBedrockConnector.CreateDataSourceRequest")) {
			return amazonbedrockconnector.proxies.CreateDataSourceRequest.initialize(context, mendixObject);
		}
		if (mendixObject.isInstanceOf("AmazonBedrockConnector.DeleteDataSourceRequest")) {
			return amazonbedrockconnector.proxies.DeleteDataSourceRequest.initialize(context, mendixObject);
		}
		if (mendixObject.isInstanceOf("AmazonBedrockConnector.GetAgentRequest")) {
			return amazonbedrockconnector.proxies.GetAgentRequest.initialize(context, mendixObject);
		}
		if (mendixObject.isInstanceOf("AmazonBedrockConnector.GetDataSourceRequest")) {
			return amazonbedrockconnector.proxies.GetDataSourceRequest.initialize(context, mendixObject);
		}
		if (mendixObject.isInstanceOf("AmazonBedrockConnector.GetIngestionJobRequest")) {
			return amazonbedrockconnector.proxies.GetIngestionJobRequest.initialize(context, mendixObject);
		}
		if (mendixObject.isInstanceOf("AmazonBedrockConnector.InvokeAgentRequest")) {
			return amazonbedrockconnector.proxies.InvokeAgentRequest.initialize(context, mendixObject);
		}
		if (mendixObject.isInstanceOf("AmazonBedrockConnector.InvokeModelRequest")) {
			return amazonbedrockconnector.proxies.InvokeModelRequest.initialize(context, mendixObject);
		}
		if (mendixObject.isInstanceOf("AmazonBedrockConnector.ListAgentsRequest")) {
			return amazonbedrockconnector.proxies.ListAgentsRequest.initialize(context, mendixObject);
		}
		if (mendixObject.isInstanceOf("AmazonBedrockConnector.ListDataSourcesRequest")) {
			return amazonbedrockconnector.proxies.ListDataSourcesRequest.initialize(context, mendixObject);
		}
		if (mendixObject.isInstanceOf("AmazonBedrockConnector.ListFoundationModelsRequest")) {
			return amazonbedrockconnector.proxies.ListFoundationModelsRequest.initialize(context, mendixObject);
		}
		if (mendixObject.isInstanceOf("AmazonBedrockConnector.ListIngestionJobsRequest")) {
			return amazonbedrockconnector.proxies.ListIngestionJobsRequest.initialize(context, mendixObject);
		}
		if (mendixObject.isInstanceOf("AmazonBedrockConnector.ListKnowledgeBasesRequest")) {
			return amazonbedrockconnector.proxies.ListKnowledgeBasesRequest.initialize(context, mendixObject);
		}
		if (mendixObject.isInstanceOf("AmazonBedrockConnector.RetrieveAndGenerateRequest_Extension")) {
			return amazonbedrockconnector.proxies.RetrieveAndGenerateRequest_Extension.initialize(context, mendixObject);
		}
		if (mendixObject.isInstanceOf("AmazonBedrockConnector.RetrieveRequest_Extension")) {
			return amazonbedrockconnector.proxies.RetrieveRequest_Extension.initialize(context, mendixObject);
		}
		if (mendixObject.isInstanceOf("AmazonBedrockConnector.StartIngestionJobRequest")) {
			return amazonbedrockconnector.proxies.StartIngestionJobRequest.initialize(context, mendixObject);
		}
		return new awsauthentication.proxies.AbstractRequest(context, mendixObject);
	}

	public static awsauthentication.proxies.AbstractRequest load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return awsauthentication.proxies.AbstractRequest.initialize(context, mendixObject);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of AbstractRequest_BasicClientConfig
	 */
	public final awsauthentication.proxies.BasicClientConfig getAbstractRequest_BasicClientConfig() throws com.mendix.core.CoreException
	{
		return getAbstractRequest_BasicClientConfig(getContext());
	}

	/**
	 * @param context
	 * @return value of AbstractRequest_BasicClientConfig
	 * @throws com.mendix.core.CoreException
	 */
	public final awsauthentication.proxies.BasicClientConfig getAbstractRequest_BasicClientConfig(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		awsauthentication.proxies.BasicClientConfig result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.AbstractRequest_BasicClientConfig.toString());
		if (identifier != null) {
			result = awsauthentication.proxies.BasicClientConfig.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of AbstractRequest_BasicClientConfig
	 * @param abstractrequest_basicclientconfig
	 */
	public final void setAbstractRequest_BasicClientConfig(awsauthentication.proxies.BasicClientConfig abstractrequest_basicclientconfig)
	{
		setAbstractRequest_BasicClientConfig(getContext(), abstractrequest_basicclientconfig);
	}

	/**
	 * Set value of AbstractRequest_BasicClientConfig
	 * @param context
	 * @param abstractrequest_basicclientconfig
	 */
	public final void setAbstractRequest_BasicClientConfig(com.mendix.systemwideinterfaces.core.IContext context, awsauthentication.proxies.BasicClientConfig abstractrequest_basicclientconfig)
	{
		if (abstractrequest_basicclientconfig == null) {
			getMendixObject().setValue(context, MemberNames.AbstractRequest_BasicClientConfig.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.AbstractRequest_BasicClientConfig.toString(), abstractrequest_basicclientconfig.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return abstractRequestMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final awsauthentication.proxies.AbstractRequest that = (awsauthentication.proxies.AbstractRequest) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
