// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package awsauthentication.proxies;

/**
 * This entity sets the values of the ApacheHttpClient. Only the values that are not empty are set on the ApacheHttpClient. All values that are left empty are set to the system default
 * https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/http/apache/ApacheHttpClient.Builder.html
 */
public class ApacheHttpConfig extends awsauthentication.proxies.AbstractHttpConfig
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AWSAuthentication.ApacheHttpConfig";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ConnectionAcquisitionTimeOutInMs("ConnectionAcquisitionTimeOutInMs"),
		ConnectionMaxIdleTimeInMs("ConnectionMaxIdleTimeInMs"),
		ConnectionTimeOutInMs("ConnectionTimeOutInMs"),
		ConnectionTimeToLiveInMs("ConnectionTimeToLiveInMs"),
		ExpectContinueEnabled("ExpectContinueEnabled"),
		LocalAddress("LocalAddress"),
		MaxConnections("MaxConnections"),
		SocketTimeOutInMs("SocketTimeOutInMs"),
		TcpKeepAlive("TcpKeepAlive"),
		UseIdleConnectionReaper("UseIdleConnectionReaper"),
		SdkClientConfig_AbstractHttpConfig("AWSAuthentication.SdkClientConfig_AbstractHttpConfig");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ApacheHttpConfig(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ApacheHttpConfig(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject apacheHttpConfigMendixObject)
	{
		super(context, apacheHttpConfigMendixObject);
		if (!apacheHttpConfigMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static awsauthentication.proxies.ApacheHttpConfig initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new awsauthentication.proxies.ApacheHttpConfig(context, mendixObject);
	}

	public static awsauthentication.proxies.ApacheHttpConfig load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return awsauthentication.proxies.ApacheHttpConfig.initialize(context, mendixObject);
	}

	/**
	 * @return value of ConnectionAcquisitionTimeOutInMs
	 */
	public final java.lang.Long getConnectionAcquisitionTimeOutInMs()
	{
		return getConnectionAcquisitionTimeOutInMs(getContext());
	}

	/**
	 * @param context
	 * @return value of ConnectionAcquisitionTimeOutInMs
	 */
	public final java.lang.Long getConnectionAcquisitionTimeOutInMs(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.ConnectionAcquisitionTimeOutInMs.toString());
	}

	/**
	 * Set value of ConnectionAcquisitionTimeOutInMs
	 * @param connectionacquisitiontimeoutinms
	 */
	public final void setConnectionAcquisitionTimeOutInMs(java.lang.Long connectionacquisitiontimeoutinms)
	{
		setConnectionAcquisitionTimeOutInMs(getContext(), connectionacquisitiontimeoutinms);
	}

	/**
	 * Set value of ConnectionAcquisitionTimeOutInMs
	 * @param context
	 * @param connectionacquisitiontimeoutinms
	 */
	public final void setConnectionAcquisitionTimeOutInMs(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long connectionacquisitiontimeoutinms)
	{
		getMendixObject().setValue(context, MemberNames.ConnectionAcquisitionTimeOutInMs.toString(), connectionacquisitiontimeoutinms);
	}

	/**
	 * @return value of ConnectionMaxIdleTimeInMs
	 */
	public final java.lang.Long getConnectionMaxIdleTimeInMs()
	{
		return getConnectionMaxIdleTimeInMs(getContext());
	}

	/**
	 * @param context
	 * @return value of ConnectionMaxIdleTimeInMs
	 */
	public final java.lang.Long getConnectionMaxIdleTimeInMs(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.ConnectionMaxIdleTimeInMs.toString());
	}

	/**
	 * Set value of ConnectionMaxIdleTimeInMs
	 * @param connectionmaxidletimeinms
	 */
	public final void setConnectionMaxIdleTimeInMs(java.lang.Long connectionmaxidletimeinms)
	{
		setConnectionMaxIdleTimeInMs(getContext(), connectionmaxidletimeinms);
	}

	/**
	 * Set value of ConnectionMaxIdleTimeInMs
	 * @param context
	 * @param connectionmaxidletimeinms
	 */
	public final void setConnectionMaxIdleTimeInMs(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long connectionmaxidletimeinms)
	{
		getMendixObject().setValue(context, MemberNames.ConnectionMaxIdleTimeInMs.toString(), connectionmaxidletimeinms);
	}

	/**
	 * @return value of ConnectionTimeOutInMs
	 */
	public final java.lang.Long getConnectionTimeOutInMs()
	{
		return getConnectionTimeOutInMs(getContext());
	}

	/**
	 * @param context
	 * @return value of ConnectionTimeOutInMs
	 */
	public final java.lang.Long getConnectionTimeOutInMs(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.ConnectionTimeOutInMs.toString());
	}

	/**
	 * Set value of ConnectionTimeOutInMs
	 * @param connectiontimeoutinms
	 */
	public final void setConnectionTimeOutInMs(java.lang.Long connectiontimeoutinms)
	{
		setConnectionTimeOutInMs(getContext(), connectiontimeoutinms);
	}

	/**
	 * Set value of ConnectionTimeOutInMs
	 * @param context
	 * @param connectiontimeoutinms
	 */
	public final void setConnectionTimeOutInMs(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long connectiontimeoutinms)
	{
		getMendixObject().setValue(context, MemberNames.ConnectionTimeOutInMs.toString(), connectiontimeoutinms);
	}

	/**
	 * @return value of ConnectionTimeToLiveInMs
	 */
	public final java.lang.Long getConnectionTimeToLiveInMs()
	{
		return getConnectionTimeToLiveInMs(getContext());
	}

	/**
	 * @param context
	 * @return value of ConnectionTimeToLiveInMs
	 */
	public final java.lang.Long getConnectionTimeToLiveInMs(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.ConnectionTimeToLiveInMs.toString());
	}

	/**
	 * Set value of ConnectionTimeToLiveInMs
	 * @param connectiontimetoliveinms
	 */
	public final void setConnectionTimeToLiveInMs(java.lang.Long connectiontimetoliveinms)
	{
		setConnectionTimeToLiveInMs(getContext(), connectiontimetoliveinms);
	}

	/**
	 * Set value of ConnectionTimeToLiveInMs
	 * @param context
	 * @param connectiontimetoliveinms
	 */
	public final void setConnectionTimeToLiveInMs(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long connectiontimetoliveinms)
	{
		getMendixObject().setValue(context, MemberNames.ConnectionTimeToLiveInMs.toString(), connectiontimetoliveinms);
	}

	/**
	 * Get value of ExpectContinueEnabled
	 * @param expectcontinueenabled
	 */
	public final awsauthentication.proxies.ENUM_Boolean getExpectContinueEnabled()
	{
		return getExpectContinueEnabled(getContext());
	}

	/**
	 * @param context
	 * @return value of ExpectContinueEnabled
	 */
	public final awsauthentication.proxies.ENUM_Boolean getExpectContinueEnabled(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.ExpectContinueEnabled.toString());
		if (obj == null) {
			return null;
		}
		return awsauthentication.proxies.ENUM_Boolean.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of ExpectContinueEnabled
	 * @param expectcontinueenabled
	 */
	public final void setExpectContinueEnabled(awsauthentication.proxies.ENUM_Boolean expectcontinueenabled)
	{
		setExpectContinueEnabled(getContext(), expectcontinueenabled);
	}

	/**
	 * Set value of ExpectContinueEnabled
	 * @param context
	 * @param expectcontinueenabled
	 */
	public final void setExpectContinueEnabled(com.mendix.systemwideinterfaces.core.IContext context, awsauthentication.proxies.ENUM_Boolean expectcontinueenabled)
	{
		if (expectcontinueenabled != null) {
			getMendixObject().setValue(context, MemberNames.ExpectContinueEnabled.toString(), expectcontinueenabled.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.ExpectContinueEnabled.toString(), null);
		}
	}

	/**
	 * @return value of LocalAddress
	 */
	public final java.lang.String getLocalAddress()
	{
		return getLocalAddress(getContext());
	}

	/**
	 * @param context
	 * @return value of LocalAddress
	 */
	public final java.lang.String getLocalAddress(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.LocalAddress.toString());
	}

	/**
	 * Set value of LocalAddress
	 * @param localaddress
	 */
	public final void setLocalAddress(java.lang.String localaddress)
	{
		setLocalAddress(getContext(), localaddress);
	}

	/**
	 * Set value of LocalAddress
	 * @param context
	 * @param localaddress
	 */
	public final void setLocalAddress(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String localaddress)
	{
		getMendixObject().setValue(context, MemberNames.LocalAddress.toString(), localaddress);
	}

	/**
	 * @return value of MaxConnections
	 */
	public final java.lang.Integer getMaxConnections()
	{
		return getMaxConnections(getContext());
	}

	/**
	 * @param context
	 * @return value of MaxConnections
	 */
	public final java.lang.Integer getMaxConnections(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.MaxConnections.toString());
	}

	/**
	 * Set value of MaxConnections
	 * @param maxconnections
	 */
	public final void setMaxConnections(java.lang.Integer maxconnections)
	{
		setMaxConnections(getContext(), maxconnections);
	}

	/**
	 * Set value of MaxConnections
	 * @param context
	 * @param maxconnections
	 */
	public final void setMaxConnections(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer maxconnections)
	{
		getMendixObject().setValue(context, MemberNames.MaxConnections.toString(), maxconnections);
	}

	/**
	 * @return value of SocketTimeOutInMs
	 */
	public final java.lang.Long getSocketTimeOutInMs()
	{
		return getSocketTimeOutInMs(getContext());
	}

	/**
	 * @param context
	 * @return value of SocketTimeOutInMs
	 */
	public final java.lang.Long getSocketTimeOutInMs(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.SocketTimeOutInMs.toString());
	}

	/**
	 * Set value of SocketTimeOutInMs
	 * @param sockettimeoutinms
	 */
	public final void setSocketTimeOutInMs(java.lang.Long sockettimeoutinms)
	{
		setSocketTimeOutInMs(getContext(), sockettimeoutinms);
	}

	/**
	 * Set value of SocketTimeOutInMs
	 * @param context
	 * @param sockettimeoutinms
	 */
	public final void setSocketTimeOutInMs(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long sockettimeoutinms)
	{
		getMendixObject().setValue(context, MemberNames.SocketTimeOutInMs.toString(), sockettimeoutinms);
	}

	/**
	 * Get value of TcpKeepAlive
	 * @param tcpkeepalive
	 */
	public final awsauthentication.proxies.ENUM_Boolean getTcpKeepAlive()
	{
		return getTcpKeepAlive(getContext());
	}

	/**
	 * @param context
	 * @return value of TcpKeepAlive
	 */
	public final awsauthentication.proxies.ENUM_Boolean getTcpKeepAlive(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.TcpKeepAlive.toString());
		if (obj == null) {
			return null;
		}
		return awsauthentication.proxies.ENUM_Boolean.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of TcpKeepAlive
	 * @param tcpkeepalive
	 */
	public final void setTcpKeepAlive(awsauthentication.proxies.ENUM_Boolean tcpkeepalive)
	{
		setTcpKeepAlive(getContext(), tcpkeepalive);
	}

	/**
	 * Set value of TcpKeepAlive
	 * @param context
	 * @param tcpkeepalive
	 */
	public final void setTcpKeepAlive(com.mendix.systemwideinterfaces.core.IContext context, awsauthentication.proxies.ENUM_Boolean tcpkeepalive)
	{
		if (tcpkeepalive != null) {
			getMendixObject().setValue(context, MemberNames.TcpKeepAlive.toString(), tcpkeepalive.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.TcpKeepAlive.toString(), null);
		}
	}

	/**
	 * Get value of UseIdleConnectionReaper
	 * @param useidleconnectionreaper
	 */
	public final awsauthentication.proxies.ENUM_Boolean getUseIdleConnectionReaper()
	{
		return getUseIdleConnectionReaper(getContext());
	}

	/**
	 * @param context
	 * @return value of UseIdleConnectionReaper
	 */
	public final awsauthentication.proxies.ENUM_Boolean getUseIdleConnectionReaper(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.UseIdleConnectionReaper.toString());
		if (obj == null) {
			return null;
		}
		return awsauthentication.proxies.ENUM_Boolean.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of UseIdleConnectionReaper
	 * @param useidleconnectionreaper
	 */
	public final void setUseIdleConnectionReaper(awsauthentication.proxies.ENUM_Boolean useidleconnectionreaper)
	{
		setUseIdleConnectionReaper(getContext(), useidleconnectionreaper);
	}

	/**
	 * Set value of UseIdleConnectionReaper
	 * @param context
	 * @param useidleconnectionreaper
	 */
	public final void setUseIdleConnectionReaper(com.mendix.systemwideinterfaces.core.IContext context, awsauthentication.proxies.ENUM_Boolean useidleconnectionreaper)
	{
		if (useidleconnectionreaper != null) {
			getMendixObject().setValue(context, MemberNames.UseIdleConnectionReaper.toString(), useidleconnectionreaper.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.UseIdleConnectionReaper.toString(), null);
		}
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final awsauthentication.proxies.ApacheHttpConfig that = (awsauthentication.proxies.ApacheHttpConfig) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
