// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package awsauthentication.proxies;

/**
 * The AssumedRoleUser entity holds information about the specific IAM role that was assumed, including its Amazon Resource Name (Arn) and a unique identifier (AssumedRoleId) for that assumed session.
 */
public class AssumedRoleUser implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject assumedRoleUserMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AWSAuthentication.AssumedRoleUser";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Arn("Arn"),
		AssumedRoleId("AssumedRoleId"),
		CredentialSetProperties_AssumedRoleUser("AWSAuthentication.CredentialSetProperties_AssumedRoleUser");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public AssumedRoleUser(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected AssumedRoleUser(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject assumedRoleUserMendixObject)
	{
		if (assumedRoleUserMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!assumedRoleUserMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.assumedRoleUserMendixObject = assumedRoleUserMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static awsauthentication.proxies.AssumedRoleUser initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new awsauthentication.proxies.AssumedRoleUser(context, mendixObject);
	}

	public static awsauthentication.proxies.AssumedRoleUser load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return awsauthentication.proxies.AssumedRoleUser.initialize(context, mendixObject);
	}

	/**
	 * @return value of Arn
	 */
	public final java.lang.String getArn()
	{
		return getArn(getContext());
	}

	/**
	 * @param context
	 * @return value of Arn
	 */
	public final java.lang.String getArn(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Arn.toString());
	}

	/**
	 * Set value of Arn
	 * @param arn
	 */
	public final void setArn(java.lang.String arn)
	{
		setArn(getContext(), arn);
	}

	/**
	 * Set value of Arn
	 * @param context
	 * @param arn
	 */
	public final void setArn(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String arn)
	{
		getMendixObject().setValue(context, MemberNames.Arn.toString(), arn);
	}

	/**
	 * @return value of AssumedRoleId
	 */
	public final java.lang.String getAssumedRoleId()
	{
		return getAssumedRoleId(getContext());
	}

	/**
	 * @param context
	 * @return value of AssumedRoleId
	 */
	public final java.lang.String getAssumedRoleId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.AssumedRoleId.toString());
	}

	/**
	 * Set value of AssumedRoleId
	 * @param assumedroleid
	 */
	public final void setAssumedRoleId(java.lang.String assumedroleid)
	{
		setAssumedRoleId(getContext(), assumedroleid);
	}

	/**
	 * Set value of AssumedRoleId
	 * @param context
	 * @param assumedroleid
	 */
	public final void setAssumedRoleId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String assumedroleid)
	{
		getMendixObject().setValue(context, MemberNames.AssumedRoleId.toString(), assumedroleid);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of CredentialSetProperties_AssumedRoleUser
	 */
	public final awsauthentication.proxies.CredentialSetProperties getCredentialSetProperties_AssumedRoleUser() throws com.mendix.core.CoreException
	{
		return getCredentialSetProperties_AssumedRoleUser(getContext());
	}

	/**
	 * @param context
	 * @return value of CredentialSetProperties_AssumedRoleUser
	 * @throws com.mendix.core.CoreException
	 */
	public final awsauthentication.proxies.CredentialSetProperties getCredentialSetProperties_AssumedRoleUser(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		awsauthentication.proxies.CredentialSetProperties result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.CredentialSetProperties_AssumedRoleUser.toString());
		if (identifier != null) {
			result = awsauthentication.proxies.CredentialSetProperties.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of CredentialSetProperties_AssumedRoleUser
	 * @param credentialsetproperties_assumedroleuser
	 */
	public final void setCredentialSetProperties_AssumedRoleUser(awsauthentication.proxies.CredentialSetProperties credentialsetproperties_assumedroleuser)
	{
		setCredentialSetProperties_AssumedRoleUser(getContext(), credentialsetproperties_assumedroleuser);
	}

	/**
	 * Set value of CredentialSetProperties_AssumedRoleUser
	 * @param context
	 * @param credentialsetproperties_assumedroleuser
	 */
	public final void setCredentialSetProperties_AssumedRoleUser(com.mendix.systemwideinterfaces.core.IContext context, awsauthentication.proxies.CredentialSetProperties credentialsetproperties_assumedroleuser)
	{
		if (credentialsetproperties_assumedroleuser == null) {
			getMendixObject().setValue(context, MemberNames.CredentialSetProperties_AssumedRoleUser.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.CredentialSetProperties_AssumedRoleUser.toString(), credentialsetproperties_assumedroleuser.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return assumedRoleUserMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final awsauthentication.proxies.AssumedRoleUser that = (awsauthentication.proxies.AssumedRoleUser) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
