// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package awsauthentication.proxies;

/**
 * The entity is the response for the AssumeRole API.
 */
public class AssumeRoleResponse implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject assumeRoleResponseMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AWSAuthentication.AssumeRoleResponse";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		SubjectArn("SubjectArn");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public AssumeRoleResponse(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected AssumeRoleResponse(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject assumeRoleResponseMendixObject)
	{
		if (assumeRoleResponseMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!assumeRoleResponseMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.assumeRoleResponseMendixObject = assumeRoleResponseMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static awsauthentication.proxies.AssumeRoleResponse initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new awsauthentication.proxies.AssumeRoleResponse(context, mendixObject);
	}

	public static awsauthentication.proxies.AssumeRoleResponse load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return awsauthentication.proxies.AssumeRoleResponse.initialize(context, mendixObject);
	}

	/**
	 * @return value of SubjectArn
	 */
	public final java.lang.String getSubjectArn()
	{
		return getSubjectArn(getContext());
	}

	/**
	 * @param context
	 * @return value of SubjectArn
	 */
	public final java.lang.String getSubjectArn(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SubjectArn.toString());
	}

	/**
	 * Set value of SubjectArn
	 * @param subjectarn
	 */
	public final void setSubjectArn(java.lang.String subjectarn)
	{
		setSubjectArn(getContext(), subjectarn);
	}

	/**
	 * Set value of SubjectArn
	 * @param context
	 * @param subjectarn
	 */
	public final void setSubjectArn(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String subjectarn)
	{
		getMendixObject().setValue(context, MemberNames.SubjectArn.toString(), subjectarn);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return assumeRoleResponseMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final awsauthentication.proxies.AssumeRoleResponse that = (awsauthentication.proxies.AssumeRoleResponse) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
