// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package awsauthentication.proxies;

/**
 * This entity has some basic settings that are available for both REST and SDK based connectors. 
 * SDK based connectors have more options available to them, but the BasicClientConfig can still be passed along if these attributes are all that need to be customized
 */
public class BasicClientConfig implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject basicClientConfigMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AWSAuthentication.BasicClientConfig";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ApiTimeOutInMs("ApiTimeOutInMs"),
		EndpointUrl("EndpointUrl"),
		AbstractRequest_BasicClientConfig("AWSAuthentication.AbstractRequest_BasicClientConfig");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public BasicClientConfig(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected BasicClientConfig(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject basicClientConfigMendixObject)
	{
		if (basicClientConfigMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!basicClientConfigMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.basicClientConfigMendixObject = basicClientConfigMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static awsauthentication.proxies.BasicClientConfig initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		if (mendixObject.isInstanceOf("AWSAuthentication.SdkClientConfig")) {
			return awsauthentication.proxies.SdkClientConfig.initialize(context, mendixObject);
		}
		return new awsauthentication.proxies.BasicClientConfig(context, mendixObject);
	}

	public static awsauthentication.proxies.BasicClientConfig load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return awsauthentication.proxies.BasicClientConfig.initialize(context, mendixObject);
	}

	/**
	 * @return value of ApiTimeOutInMs
	 */
	public final java.lang.Long getApiTimeOutInMs()
	{
		return getApiTimeOutInMs(getContext());
	}

	/**
	 * @param context
	 * @return value of ApiTimeOutInMs
	 */
	public final java.lang.Long getApiTimeOutInMs(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.ApiTimeOutInMs.toString());
	}

	/**
	 * Set value of ApiTimeOutInMs
	 * @param apitimeoutinms
	 */
	public final void setApiTimeOutInMs(java.lang.Long apitimeoutinms)
	{
		setApiTimeOutInMs(getContext(), apitimeoutinms);
	}

	/**
	 * Set value of ApiTimeOutInMs
	 * @param context
	 * @param apitimeoutinms
	 */
	public final void setApiTimeOutInMs(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long apitimeoutinms)
	{
		getMendixObject().setValue(context, MemberNames.ApiTimeOutInMs.toString(), apitimeoutinms);
	}

	/**
	 * @return value of EndpointUrl
	 */
	public final java.lang.String getEndpointUrl()
	{
		return getEndpointUrl(getContext());
	}

	/**
	 * @param context
	 * @return value of EndpointUrl
	 */
	public final java.lang.String getEndpointUrl(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EndpointUrl.toString());
	}

	/**
	 * Set value of EndpointUrl
	 * @param endpointurl
	 */
	public final void setEndpointUrl(java.lang.String endpointurl)
	{
		setEndpointUrl(getContext(), endpointurl);
	}

	/**
	 * Set value of EndpointUrl
	 * @param context
	 * @param endpointurl
	 */
	public final void setEndpointUrl(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String endpointurl)
	{
		getMendixObject().setValue(context, MemberNames.EndpointUrl.toString(), endpointurl);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of AbstractRequest_BasicClientConfig
	 */
	public final awsauthentication.proxies.AbstractRequest getAbstractRequest_BasicClientConfig() throws com.mendix.core.CoreException
	{
		return getAbstractRequest_BasicClientConfig(getContext());
	}

	/**
	 * @param context
	 * @return value of AbstractRequest_BasicClientConfig
	 * @throws com.mendix.core.CoreException
	 */
	public final awsauthentication.proxies.AbstractRequest getAbstractRequest_BasicClientConfig(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		awsauthentication.proxies.AbstractRequest result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.AbstractRequest_BasicClientConfig.toString());
		if (identifier != null) {
			result = awsauthentication.proxies.AbstractRequest.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of AbstractRequest_BasicClientConfig
	 * @param abstractrequest_basicclientconfig
	 */
	public final void setAbstractRequest_BasicClientConfig(awsauthentication.proxies.AbstractRequest abstractrequest_basicclientconfig)
	{
		setAbstractRequest_BasicClientConfig(getContext(), abstractrequest_basicclientconfig);
	}

	/**
	 * Set value of AbstractRequest_BasicClientConfig
	 * @param context
	 * @param abstractrequest_basicclientconfig
	 */
	public final void setAbstractRequest_BasicClientConfig(com.mendix.systemwideinterfaces.core.IContext context, awsauthentication.proxies.AbstractRequest abstractrequest_basicclientconfig)
	{
		if (abstractrequest_basicclientconfig == null) {
			getMendixObject().setValue(context, MemberNames.AbstractRequest_BasicClientConfig.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.AbstractRequest_BasicClientConfig.toString(), abstractrequest_basicclientconfig.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return basicClientConfigMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final awsauthentication.proxies.BasicClientConfig that = (awsauthentication.proxies.BasicClientConfig) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
