// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package awsauthentication.proxies;

/**
 * The CredentialDetails entity holds information about the temporary security credentials, including the AccessKeyId, SecretAccessKey, SessionToken, and Expiration, provided by the AssumeRole API for authenticating AWS service requests.
 */
public class CredentialDetails implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject credentialDetailsMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AWSAuthentication.CredentialDetails";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		AccessKeyId("AccessKeyId"),
		SecretAccessKey("SecretAccessKey"),
		SessionToken("SessionToken"),
		Expiration("Expiration"),
		CredentialSetProperties_CredentialDetails("AWSAuthentication.CredentialSetProperties_CredentialDetails");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public CredentialDetails(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected CredentialDetails(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject credentialDetailsMendixObject)
	{
		if (credentialDetailsMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!credentialDetailsMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.credentialDetailsMendixObject = credentialDetailsMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static awsauthentication.proxies.CredentialDetails initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new awsauthentication.proxies.CredentialDetails(context, mendixObject);
	}

	public static awsauthentication.proxies.CredentialDetails load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return awsauthentication.proxies.CredentialDetails.initialize(context, mendixObject);
	}

	/**
	 * @return value of AccessKeyId
	 */
	public final java.lang.String getAccessKeyId()
	{
		return getAccessKeyId(getContext());
	}

	/**
	 * @param context
	 * @return value of AccessKeyId
	 */
	public final java.lang.String getAccessKeyId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.AccessKeyId.toString());
	}

	/**
	 * Set value of AccessKeyId
	 * @param accesskeyid
	 */
	public final void setAccessKeyId(java.lang.String accesskeyid)
	{
		setAccessKeyId(getContext(), accesskeyid);
	}

	/**
	 * Set value of AccessKeyId
	 * @param context
	 * @param accesskeyid
	 */
	public final void setAccessKeyId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String accesskeyid)
	{
		getMendixObject().setValue(context, MemberNames.AccessKeyId.toString(), accesskeyid);
	}

	/**
	 * @return value of SecretAccessKey
	 */
	public final java.lang.String getSecretAccessKey()
	{
		return getSecretAccessKey(getContext());
	}

	/**
	 * @param context
	 * @return value of SecretAccessKey
	 */
	public final java.lang.String getSecretAccessKey(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SecretAccessKey.toString());
	}

	/**
	 * Set value of SecretAccessKey
	 * @param secretaccesskey
	 */
	public final void setSecretAccessKey(java.lang.String secretaccesskey)
	{
		setSecretAccessKey(getContext(), secretaccesskey);
	}

	/**
	 * Set value of SecretAccessKey
	 * @param context
	 * @param secretaccesskey
	 */
	public final void setSecretAccessKey(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String secretaccesskey)
	{
		getMendixObject().setValue(context, MemberNames.SecretAccessKey.toString(), secretaccesskey);
	}

	/**
	 * @return value of SessionToken
	 */
	public final java.lang.String getSessionToken()
	{
		return getSessionToken(getContext());
	}

	/**
	 * @param context
	 * @return value of SessionToken
	 */
	public final java.lang.String getSessionToken(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SessionToken.toString());
	}

	/**
	 * Set value of SessionToken
	 * @param sessiontoken
	 */
	public final void setSessionToken(java.lang.String sessiontoken)
	{
		setSessionToken(getContext(), sessiontoken);
	}

	/**
	 * Set value of SessionToken
	 * @param context
	 * @param sessiontoken
	 */
	public final void setSessionToken(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String sessiontoken)
	{
		getMendixObject().setValue(context, MemberNames.SessionToken.toString(), sessiontoken);
	}

	/**
	 * @return value of Expiration
	 */
	public final java.util.Date getExpiration()
	{
		return getExpiration(getContext());
	}

	/**
	 * @param context
	 * @return value of Expiration
	 */
	public final java.util.Date getExpiration(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Expiration.toString());
	}

	/**
	 * Set value of Expiration
	 * @param expiration
	 */
	public final void setExpiration(java.util.Date expiration)
	{
		setExpiration(getContext(), expiration);
	}

	/**
	 * Set value of Expiration
	 * @param context
	 * @param expiration
	 */
	public final void setExpiration(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date expiration)
	{
		getMendixObject().setValue(context, MemberNames.Expiration.toString(), expiration);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of CredentialSetProperties_CredentialDetails
	 */
	public final awsauthentication.proxies.CredentialSetProperties getCredentialSetProperties_CredentialDetails() throws com.mendix.core.CoreException
	{
		return getCredentialSetProperties_CredentialDetails(getContext());
	}

	/**
	 * @param context
	 * @return value of CredentialSetProperties_CredentialDetails
	 * @throws com.mendix.core.CoreException
	 */
	public final awsauthentication.proxies.CredentialSetProperties getCredentialSetProperties_CredentialDetails(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		awsauthentication.proxies.CredentialSetProperties result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.CredentialSetProperties_CredentialDetails.toString());
		if (identifier != null) {
			result = awsauthentication.proxies.CredentialSetProperties.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of CredentialSetProperties_CredentialDetails
	 * @param credentialsetproperties_credentialdetails
	 */
	public final void setCredentialSetProperties_CredentialDetails(awsauthentication.proxies.CredentialSetProperties credentialsetproperties_credentialdetails)
	{
		setCredentialSetProperties_CredentialDetails(getContext(), credentialsetproperties_credentialdetails);
	}

	/**
	 * Set value of CredentialSetProperties_CredentialDetails
	 * @param context
	 * @param credentialsetproperties_credentialdetails
	 */
	public final void setCredentialSetProperties_CredentialDetails(com.mendix.systemwideinterfaces.core.IContext context, awsauthentication.proxies.CredentialSetProperties credentialsetproperties_credentialdetails)
	{
		if (credentialsetproperties_credentialdetails == null) {
			getMendixObject().setValue(context, MemberNames.CredentialSetProperties_CredentialDetails.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.CredentialSetProperties_CredentialDetails.toString(), credentialsetproperties_credentialdetails.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return credentialDetailsMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final awsauthentication.proxies.CredentialDetails that = (awsauthentication.proxies.CredentialDetails) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
