// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package awsauthentication.proxies;

public enum ENUM_Region
{
	us_east_1("736d5dfc-dea9-4c56-910f-dd0d5682b99d"),
	us_east_2("8ce8df65-89f2-4386-917b-0f4c6efa4661"),
	us_west_1("3dbc0e75-7083-41fb-9c43-c1d0846841a1"),
	us_west_2("4c43ee5c-b5a3-4dfc-a1d5-f167b80dd7bf"),
	af_south_1("a5a8c00f-e200-4db5-813b-fed3220219a3"),
	ap_east_1("b8655657-cf45-42ea-aeb8-5c3c196e419d"),
	ap_northeast_1("7d17dbb4-fad1-4b70-935d-a7bbc7e9c2ca"),
	ap_northeast_2("28414797-9424-43fc-9149-29e5ca2ec433"),
	ap_northeast_3("b8d26f39-1c4b-49af-8664-8ee182c866c5"),
	ap_south_1("31eb93fb-f0fe-4fb7-898e-0a2dfcb21d2f"),
	ap_south_2("f3f51074-3eee-441f-b99d-a6d346ad233b"),
	ap_southeast_1("446e9eb7-7502-409b-a49d-b5b858db4491"),
	ap_southeast_2("162dd741-b73f-49ca-99cf-65d63fb00e47"),
	ap_southeast_3("da5ddf26-ef02-41f5-8b87-fad5072f1a01"),
	ap_southeast_4("1a42571b-b9b5-47bc-84c4-9423a88d3b9c"),
	ca_central_1("98ca11c0-30dd-474f-afe8-aeb9f7c52822"),
	ca_west_1("19604170-1356-4ea9-9e51-38118552ea98"),
	eu_central_1("d7697f52-cd1b-480d-b670-a278d7f5d08c"),
	eu_central_2("7be528c4-9cd2-4917-97a8-c2b6d375ccd7"),
	eu_north_1("96850bd1-fff1-4488-8172-a0009d319b68"),
	eu_south_1("d2a1da23-ee0e-4615-aa05-159d0f110410"),
	eu_south_2("cd53f86f-5511-4c33-909f-978dcef24f95"),
	eu_west_1("109a2437-b29e-40b3-a4f9-e104c5729a2e"),
	eu_west_2("717c762e-d583-4f5a-99bc-2acce7ba55db"),
	eu_west_3("faa62b5c-9db0-4e93-ba92-a5ac7e4aeb9e"),
	il_central_1("376eff8a-835b-4aa9-b248-90fa2c028585"),
	me_central_1("0e791341-6d79-47ce-ab14-0deb1b1c50b8"),
	me_south_1("428f1ca0-a0c6-48e0-a56c-ca31543d27dd"),
	mx_central_1("44c201d0-808f-4e9b-9104-f40d5bec67b9"),
	sa_east_1("5ac057e0-c174-44bd-9d97-55d89e06e235"),
	us_gov_east_1("5a4e35b5-2d9b-46cb-b9de-6b08603519dc"),
	us_gov_west_1("81443df8-3758-46b5-ac00-18d11a21f3b9");

	private final java.lang.String i18nCaptionKey;
	
	private ENUM_Region(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
