// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package awsauthentication.proxies;

public enum ENUM_HTTPMethod
{
	GET("97d84976-9067-4247-9393-2af7a8d98feb"),
	POST("5b480b28-95f8-41ca-a827-b31ce26d7000"),
	PUT("bf0cf8ba-a80d-4260-802a-07ac290313e2"),
	TRACE("107f2579-0975-42e0-ad02-21dc9b000af6"),
	HEAD("7114237d-a5e7-42e8-904f-5ff59b1c0449"),
	DELETE("03eee604-7ea6-4c37-8e30-c83fdfbfde08"),
	CONNECT("4d8b5748-d193-4a9b-a42d-69364a142111"),
	OPTIONS("ac114c98-3050-4631-ab43-a8e9af623742");

	private final java.lang.String i18nCaptionKey;
	
	private ENUM_HTTPMethod(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
