// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package awsauthentication.proxies;

/**
 * This enum allows for empty values to be passed into boolean fields. This in turn allows for the default configuration of those boolean values to be used
 */
public enum ENUM_Boolean
{
	_True("2915e2cb-d9a9-4cca-955b-18c1eac445f0"),
	_False("8be99cb6-f828-4b03-8b71-f1b982e3b011");

	private final java.lang.String i18nCaptionKey;
	
	private ENUM_Boolean(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
