// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package awsauthentication.proxies;

/**
 * Sets a maximum number of retries
 * https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/core/retry/RetryPolicy.html#numRetries()
 */
public class NumberRetryPolicy extends awsauthentication.proxies.AbstractRetryPolicy
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AWSAuthentication.NumberRetryPolicy";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		MaxNumberOfRetries("MaxNumberOfRetries"),
		SdkClientConfig_AbstractRetryPolicy("AWSAuthentication.SdkClientConfig_AbstractRetryPolicy");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public NumberRetryPolicy(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected NumberRetryPolicy(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject numberRetryPolicyMendixObject)
	{
		super(context, numberRetryPolicyMendixObject);
		if (!numberRetryPolicyMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static awsauthentication.proxies.NumberRetryPolicy initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new awsauthentication.proxies.NumberRetryPolicy(context, mendixObject);
	}

	public static awsauthentication.proxies.NumberRetryPolicy load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return awsauthentication.proxies.NumberRetryPolicy.initialize(context, mendixObject);
	}

	/**
	 * @return value of MaxNumberOfRetries
	 */
	public final java.lang.Integer getMaxNumberOfRetries()
	{
		return getMaxNumberOfRetries(getContext());
	}

	/**
	 * @param context
	 * @return value of MaxNumberOfRetries
	 */
	public final java.lang.Integer getMaxNumberOfRetries(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.MaxNumberOfRetries.toString());
	}

	/**
	 * Set value of MaxNumberOfRetries
	 * @param maxnumberofretries
	 */
	public final void setMaxNumberOfRetries(java.lang.Integer maxnumberofretries)
	{
		setMaxNumberOfRetries(getContext(), maxnumberofretries);
	}

	/**
	 * Set value of MaxNumberOfRetries
	 * @param context
	 * @param maxnumberofretries
	 */
	public final void setMaxNumberOfRetries(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer maxnumberofretries)
	{
		getMendixObject().setValue(context, MemberNames.MaxNumberOfRetries.toString(), maxnumberofretries);
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final awsauthentication.proxies.NumberRetryPolicy that = (awsauthentication.proxies.NumberRetryPolicy) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
