// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package awsauthentication.proxies;

/**
 * Specialization of the BasicClientConfig entity. This can be used for SDK based calls to AWS
 */
public class SdkClientConfig extends awsauthentication.proxies.BasicClientConfig
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AWSAuthentication.SdkClientConfig";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ApiAttemptTimeOutInMs("ApiAttemptTimeOutInMs"),
		ApiTimeOutInMs("ApiTimeOutInMs"),
		EndpointUrl("EndpointUrl"),
		SdkClientConfig_AbstractRetryPolicy("AWSAuthentication.SdkClientConfig_AbstractRetryPolicy"),
		SdkClientConfig_AbstractHttpConfig("AWSAuthentication.SdkClientConfig_AbstractHttpConfig"),
		AbstractRequest_BasicClientConfig("AWSAuthentication.AbstractRequest_BasicClientConfig");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public SdkClientConfig(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected SdkClientConfig(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject sdkClientConfigMendixObject)
	{
		super(context, sdkClientConfigMendixObject);
		if (!sdkClientConfigMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static awsauthentication.proxies.SdkClientConfig initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new awsauthentication.proxies.SdkClientConfig(context, mendixObject);
	}

	public static awsauthentication.proxies.SdkClientConfig load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return awsauthentication.proxies.SdkClientConfig.initialize(context, mendixObject);
	}

	/**
	 * @return value of ApiAttemptTimeOutInMs
	 */
	public final java.lang.Long getApiAttemptTimeOutInMs()
	{
		return getApiAttemptTimeOutInMs(getContext());
	}

	/**
	 * @param context
	 * @return value of ApiAttemptTimeOutInMs
	 */
	public final java.lang.Long getApiAttemptTimeOutInMs(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.ApiAttemptTimeOutInMs.toString());
	}

	/**
	 * Set value of ApiAttemptTimeOutInMs
	 * @param apiattempttimeoutinms
	 */
	public final void setApiAttemptTimeOutInMs(java.lang.Long apiattempttimeoutinms)
	{
		setApiAttemptTimeOutInMs(getContext(), apiattempttimeoutinms);
	}

	/**
	 * Set value of ApiAttemptTimeOutInMs
	 * @param context
	 * @param apiattempttimeoutinms
	 */
	public final void setApiAttemptTimeOutInMs(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long apiattempttimeoutinms)
	{
		getMendixObject().setValue(context, MemberNames.ApiAttemptTimeOutInMs.toString(), apiattempttimeoutinms);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of SdkClientConfig_AbstractRetryPolicy
	 */
	public final awsauthentication.proxies.AbstractRetryPolicy getSdkClientConfig_AbstractRetryPolicy() throws com.mendix.core.CoreException
	{
		return getSdkClientConfig_AbstractRetryPolicy(getContext());
	}

	/**
	 * @param context
	 * @return value of SdkClientConfig_AbstractRetryPolicy
	 * @throws com.mendix.core.CoreException
	 */
	public final awsauthentication.proxies.AbstractRetryPolicy getSdkClientConfig_AbstractRetryPolicy(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		awsauthentication.proxies.AbstractRetryPolicy result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.SdkClientConfig_AbstractRetryPolicy.toString());
		if (identifier != null) {
			result = awsauthentication.proxies.AbstractRetryPolicy.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of SdkClientConfig_AbstractRetryPolicy
	 * @param sdkclientconfig_abstractretrypolicy
	 */
	public final void setSdkClientConfig_AbstractRetryPolicy(awsauthentication.proxies.AbstractRetryPolicy sdkclientconfig_abstractretrypolicy)
	{
		setSdkClientConfig_AbstractRetryPolicy(getContext(), sdkclientconfig_abstractretrypolicy);
	}

	/**
	 * Set value of SdkClientConfig_AbstractRetryPolicy
	 * @param context
	 * @param sdkclientconfig_abstractretrypolicy
	 */
	public final void setSdkClientConfig_AbstractRetryPolicy(com.mendix.systemwideinterfaces.core.IContext context, awsauthentication.proxies.AbstractRetryPolicy sdkclientconfig_abstractretrypolicy)
	{
		if (sdkclientconfig_abstractretrypolicy == null) {
			getMendixObject().setValue(context, MemberNames.SdkClientConfig_AbstractRetryPolicy.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.SdkClientConfig_AbstractRetryPolicy.toString(), sdkclientconfig_abstractretrypolicy.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of SdkClientConfig_AbstractHttpConfig
	 */
	public final awsauthentication.proxies.AbstractHttpConfig getSdkClientConfig_AbstractHttpConfig() throws com.mendix.core.CoreException
	{
		return getSdkClientConfig_AbstractHttpConfig(getContext());
	}

	/**
	 * @param context
	 * @return value of SdkClientConfig_AbstractHttpConfig
	 * @throws com.mendix.core.CoreException
	 */
	public final awsauthentication.proxies.AbstractHttpConfig getSdkClientConfig_AbstractHttpConfig(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		awsauthentication.proxies.AbstractHttpConfig result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.SdkClientConfig_AbstractHttpConfig.toString());
		if (identifier != null) {
			result = awsauthentication.proxies.AbstractHttpConfig.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of SdkClientConfig_AbstractHttpConfig
	 * @param sdkclientconfig_abstracthttpconfig
	 */
	public final void setSdkClientConfig_AbstractHttpConfig(awsauthentication.proxies.AbstractHttpConfig sdkclientconfig_abstracthttpconfig)
	{
		setSdkClientConfig_AbstractHttpConfig(getContext(), sdkclientconfig_abstracthttpconfig);
	}

	/**
	 * Set value of SdkClientConfig_AbstractHttpConfig
	 * @param context
	 * @param sdkclientconfig_abstracthttpconfig
	 */
	public final void setSdkClientConfig_AbstractHttpConfig(com.mendix.systemwideinterfaces.core.IContext context, awsauthentication.proxies.AbstractHttpConfig sdkclientconfig_abstracthttpconfig)
	{
		if (sdkclientconfig_abstracthttpconfig == null) {
			getMendixObject().setValue(context, MemberNames.SdkClientConfig_AbstractHttpConfig.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.SdkClientConfig_AbstractHttpConfig.toString(), sdkclientconfig_abstracthttpconfig.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final awsauthentication.proxies.SdkClientConfig that = (awsauthentication.proxies.SdkClientConfig) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
