// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package awsauthentication.proxies;

/**
 * This is the entity that holds the (signed) headers to be assigned to a HTTP call.
 */
public class SigV4Headers implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject sigV4HeadersMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AWSAuthentication.SigV4Headers";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		EndpointUrl("EndpointUrl"),
		Header_Authorization("Header_Authorization"),
		Header_Host("Header_Host"),
		Header_X_Amz_Date("Header_X_Amz_Date"),
		Header_X_Amz_Content_Sha256("Header_X_Amz_Content_Sha256");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public SigV4Headers(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected SigV4Headers(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject sigV4HeadersMendixObject)
	{
		if (sigV4HeadersMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!sigV4HeadersMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.sigV4HeadersMendixObject = sigV4HeadersMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static awsauthentication.proxies.SigV4Headers initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new awsauthentication.proxies.SigV4Headers(context, mendixObject);
	}

	public static awsauthentication.proxies.SigV4Headers load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return awsauthentication.proxies.SigV4Headers.initialize(context, mendixObject);
	}

	/**
	 * @return value of EndpointUrl
	 */
	public final java.lang.String getEndpointUrl()
	{
		return getEndpointUrl(getContext());
	}

	/**
	 * @param context
	 * @return value of EndpointUrl
	 */
	public final java.lang.String getEndpointUrl(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EndpointUrl.toString());
	}

	/**
	 * Set value of EndpointUrl
	 * @param endpointurl
	 */
	public final void setEndpointUrl(java.lang.String endpointurl)
	{
		setEndpointUrl(getContext(), endpointurl);
	}

	/**
	 * Set value of EndpointUrl
	 * @param context
	 * @param endpointurl
	 */
	public final void setEndpointUrl(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String endpointurl)
	{
		getMendixObject().setValue(context, MemberNames.EndpointUrl.toString(), endpointurl);
	}

	/**
	 * @return value of Header_Authorization
	 */
	public final java.lang.String getHeader_Authorization()
	{
		return getHeader_Authorization(getContext());
	}

	/**
	 * @param context
	 * @return value of Header_Authorization
	 */
	public final java.lang.String getHeader_Authorization(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Header_Authorization.toString());
	}

	/**
	 * Set value of Header_Authorization
	 * @param header_authorization
	 */
	public final void setHeader_Authorization(java.lang.String header_authorization)
	{
		setHeader_Authorization(getContext(), header_authorization);
	}

	/**
	 * Set value of Header_Authorization
	 * @param context
	 * @param header_authorization
	 */
	public final void setHeader_Authorization(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String header_authorization)
	{
		getMendixObject().setValue(context, MemberNames.Header_Authorization.toString(), header_authorization);
	}

	/**
	 * @return value of Header_Host
	 */
	public final java.lang.String getHeader_Host()
	{
		return getHeader_Host(getContext());
	}

	/**
	 * @param context
	 * @return value of Header_Host
	 */
	public final java.lang.String getHeader_Host(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Header_Host.toString());
	}

	/**
	 * Set value of Header_Host
	 * @param header_host
	 */
	public final void setHeader_Host(java.lang.String header_host)
	{
		setHeader_Host(getContext(), header_host);
	}

	/**
	 * Set value of Header_Host
	 * @param context
	 * @param header_host
	 */
	public final void setHeader_Host(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String header_host)
	{
		getMendixObject().setValue(context, MemberNames.Header_Host.toString(), header_host);
	}

	/**
	 * @return value of Header_X_Amz_Date
	 */
	public final java.lang.String getHeader_X_Amz_Date()
	{
		return getHeader_X_Amz_Date(getContext());
	}

	/**
	 * @param context
	 * @return value of Header_X_Amz_Date
	 */
	public final java.lang.String getHeader_X_Amz_Date(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Header_X_Amz_Date.toString());
	}

	/**
	 * Set value of Header_X_Amz_Date
	 * @param header_x_amz_date
	 */
	public final void setHeader_X_Amz_Date(java.lang.String header_x_amz_date)
	{
		setHeader_X_Amz_Date(getContext(), header_x_amz_date);
	}

	/**
	 * Set value of Header_X_Amz_Date
	 * @param context
	 * @param header_x_amz_date
	 */
	public final void setHeader_X_Amz_Date(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String header_x_amz_date)
	{
		getMendixObject().setValue(context, MemberNames.Header_X_Amz_Date.toString(), header_x_amz_date);
	}

	/**
	 * @return value of Header_X_Amz_Content_Sha256
	 */
	public final java.lang.String getHeader_X_Amz_Content_Sha256()
	{
		return getHeader_X_Amz_Content_Sha256(getContext());
	}

	/**
	 * @param context
	 * @return value of Header_X_Amz_Content_Sha256
	 */
	public final java.lang.String getHeader_X_Amz_Content_Sha256(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Header_X_Amz_Content_Sha256.toString());
	}

	/**
	 * Set value of Header_X_Amz_Content_Sha256
	 * @param header_x_amz_content_sha256
	 */
	public final void setHeader_X_Amz_Content_Sha256(java.lang.String header_x_amz_content_sha256)
	{
		setHeader_X_Amz_Content_Sha256(getContext(), header_x_amz_content_sha256);
	}

	/**
	 * Set value of Header_X_Amz_Content_Sha256
	 * @param context
	 * @param header_x_amz_content_sha256
	 */
	public final void setHeader_X_Amz_Content_Sha256(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String header_x_amz_content_sha256)
	{
		getMendixObject().setValue(context, MemberNames.Header_X_Amz_Content_Sha256.toString(), header_x_amz_content_sha256);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return sigV4HeadersMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final awsauthentication.proxies.SigV4Headers that = (awsauthentication.proxies.SigV4Headers) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
