// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package awsauthentication.proxies;

/**
 * This is the entity that helps to sign the HTTP request using AWS' SignatureV4 method.
 */
public class SigV4Builder implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject sigV4BuilderMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AWSAuthentication.SigV4Builder";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ServiceName("ServiceName"),
		HTTPMethod("HTTPMethod"),
		URIPrefix("URIPrefix"),
		Region("Region"),
		Path("Path"),
		RequestBody("RequestBody"),
		EndpointURL("EndpointURL"),
		SubDomain("SubDomain");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public SigV4Builder(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected SigV4Builder(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject sigV4BuilderMendixObject)
	{
		if (sigV4BuilderMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!sigV4BuilderMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.sigV4BuilderMendixObject = sigV4BuilderMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static awsauthentication.proxies.SigV4Builder initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new awsauthentication.proxies.SigV4Builder(context, mendixObject);
	}

	public static awsauthentication.proxies.SigV4Builder load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return awsauthentication.proxies.SigV4Builder.initialize(context, mendixObject);
	}

	/**
	 * @return value of ServiceName
	 */
	public final java.lang.String getServiceName()
	{
		return getServiceName(getContext());
	}

	/**
	 * @param context
	 * @return value of ServiceName
	 */
	public final java.lang.String getServiceName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ServiceName.toString());
	}

	/**
	 * Set value of ServiceName
	 * @param servicename
	 */
	public final void setServiceName(java.lang.String servicename)
	{
		setServiceName(getContext(), servicename);
	}

	/**
	 * Set value of ServiceName
	 * @param context
	 * @param servicename
	 */
	public final void setServiceName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String servicename)
	{
		getMendixObject().setValue(context, MemberNames.ServiceName.toString(), servicename);
	}

	/**
	 * Get value of HTTPMethod
	 * @param httpmethod
	 */
	public final awsauthentication.proxies.ENUM_HTTPMethod getHTTPMethod()
	{
		return getHTTPMethod(getContext());
	}

	/**
	 * @param context
	 * @return value of HTTPMethod
	 */
	public final awsauthentication.proxies.ENUM_HTTPMethod getHTTPMethod(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.HTTPMethod.toString());
		if (obj == null) {
			return null;
		}
		return awsauthentication.proxies.ENUM_HTTPMethod.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of HTTPMethod
	 * @param httpmethod
	 */
	public final void setHTTPMethod(awsauthentication.proxies.ENUM_HTTPMethod httpmethod)
	{
		setHTTPMethod(getContext(), httpmethod);
	}

	/**
	 * Set value of HTTPMethod
	 * @param context
	 * @param httpmethod
	 */
	public final void setHTTPMethod(com.mendix.systemwideinterfaces.core.IContext context, awsauthentication.proxies.ENUM_HTTPMethod httpmethod)
	{
		if (httpmethod != null) {
			getMendixObject().setValue(context, MemberNames.HTTPMethod.toString(), httpmethod.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.HTTPMethod.toString(), null);
		}
	}

	/**
	 * @return value of URIPrefix
	 */
	public final java.lang.String getURIPrefix()
	{
		return getURIPrefix(getContext());
	}

	/**
	 * @param context
	 * @return value of URIPrefix
	 */
	public final java.lang.String getURIPrefix(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.URIPrefix.toString());
	}

	/**
	 * Set value of URIPrefix
	 * @param uriprefix
	 */
	public final void setURIPrefix(java.lang.String uriprefix)
	{
		setURIPrefix(getContext(), uriprefix);
	}

	/**
	 * Set value of URIPrefix
	 * @param context
	 * @param uriprefix
	 */
	public final void setURIPrefix(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String uriprefix)
	{
		getMendixObject().setValue(context, MemberNames.URIPrefix.toString(), uriprefix);
	}

	/**
	 * Get value of Region
	 * @param region
	 */
	public final awsauthentication.proxies.ENUM_Region getRegion()
	{
		return getRegion(getContext());
	}

	/**
	 * @param context
	 * @return value of Region
	 */
	public final awsauthentication.proxies.ENUM_Region getRegion(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Region.toString());
		if (obj == null) {
			return null;
		}
		return awsauthentication.proxies.ENUM_Region.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Region
	 * @param region
	 */
	public final void setRegion(awsauthentication.proxies.ENUM_Region region)
	{
		setRegion(getContext(), region);
	}

	/**
	 * Set value of Region
	 * @param context
	 * @param region
	 */
	public final void setRegion(com.mendix.systemwideinterfaces.core.IContext context, awsauthentication.proxies.ENUM_Region region)
	{
		if (region != null) {
			getMendixObject().setValue(context, MemberNames.Region.toString(), region.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.Region.toString(), null);
		}
	}

	/**
	 * @return value of Path
	 */
	public final java.lang.String getPath()
	{
		return getPath(getContext());
	}

	/**
	 * @param context
	 * @return value of Path
	 */
	public final java.lang.String getPath(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Path.toString());
	}

	/**
	 * Set value of Path
	 * @param path
	 */
	public final void setPath(java.lang.String path)
	{
		setPath(getContext(), path);
	}

	/**
	 * Set value of Path
	 * @param context
	 * @param path
	 */
	public final void setPath(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String path)
	{
		getMendixObject().setValue(context, MemberNames.Path.toString(), path);
	}

	/**
	 * @return value of RequestBody
	 */
	public final java.lang.String getRequestBody()
	{
		return getRequestBody(getContext());
	}

	/**
	 * @param context
	 * @return value of RequestBody
	 */
	public final java.lang.String getRequestBody(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.RequestBody.toString());
	}

	/**
	 * Set value of RequestBody
	 * @param requestbody
	 */
	public final void setRequestBody(java.lang.String requestbody)
	{
		setRequestBody(getContext(), requestbody);
	}

	/**
	 * Set value of RequestBody
	 * @param context
	 * @param requestbody
	 */
	public final void setRequestBody(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String requestbody)
	{
		getMendixObject().setValue(context, MemberNames.RequestBody.toString(), requestbody);
	}

	/**
	 * @return value of EndpointURL
	 */
	public final java.lang.String getEndpointURL()
	{
		return getEndpointURL(getContext());
	}

	/**
	 * @param context
	 * @return value of EndpointURL
	 */
	public final java.lang.String getEndpointURL(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EndpointURL.toString());
	}

	/**
	 * Set value of EndpointURL
	 * @param endpointurl
	 */
	public final void setEndpointURL(java.lang.String endpointurl)
	{
		setEndpointURL(getContext(), endpointurl);
	}

	/**
	 * Set value of EndpointURL
	 * @param context
	 * @param endpointurl
	 */
	public final void setEndpointURL(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String endpointurl)
	{
		getMendixObject().setValue(context, MemberNames.EndpointURL.toString(), endpointurl);
	}

	/**
	 * @return value of SubDomain
	 */
	public final java.lang.String getSubDomain()
	{
		return getSubDomain(getContext());
	}

	/**
	 * @param context
	 * @return value of SubDomain
	 */
	public final java.lang.String getSubDomain(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SubDomain.toString());
	}

	/**
	 * Set value of SubDomain
	 * @param subdomain
	 */
	public final void setSubDomain(java.lang.String subdomain)
	{
		setSubDomain(getContext(), subdomain);
	}

	/**
	 * Set value of SubDomain
	 * @param context
	 * @param subdomain
	 */
	public final void setSubDomain(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String subdomain)
	{
		getMendixObject().setValue(context, MemberNames.SubDomain.toString(), subdomain);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return sigV4BuilderMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final awsauthentication.proxies.SigV4Builder that = (awsauthentication.proxies.SigV4Builder) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
