// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package awsauthentication.proxies;

/**
 * This entity holds information for authenticating into the AWS ecosystem.
 */
public class TemporaryCredentials extends awsauthentication.proxies.Credentials
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AWSAuthentication.TemporaryCredentials";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Token("Token"),
		Expiration("Expiration"),
		AccessKey("AccessKey"),
		SecretAccessKey("SecretAccessKey");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public TemporaryCredentials(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected TemporaryCredentials(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject temporaryCredentialsMendixObject)
	{
		super(context, temporaryCredentialsMendixObject);
		if (!temporaryCredentialsMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static awsauthentication.proxies.TemporaryCredentials initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new awsauthentication.proxies.TemporaryCredentials(context, mendixObject);
	}

	public static awsauthentication.proxies.TemporaryCredentials load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return awsauthentication.proxies.TemporaryCredentials.initialize(context, mendixObject);
	}

	/**
	 * @return value of Token
	 */
	public final java.lang.String getToken()
	{
		return getToken(getContext());
	}

	/**
	 * @param context
	 * @return value of Token
	 */
	public final java.lang.String getToken(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Token.toString());
	}

	/**
	 * Set value of Token
	 * @param token
	 */
	public final void setToken(java.lang.String token)
	{
		setToken(getContext(), token);
	}

	/**
	 * Set value of Token
	 * @param context
	 * @param token
	 */
	public final void setToken(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String token)
	{
		getMendixObject().setValue(context, MemberNames.Token.toString(), token);
	}

	/**
	 * @return value of Expiration
	 */
	public final java.util.Date getExpiration()
	{
		return getExpiration(getContext());
	}

	/**
	 * @param context
	 * @return value of Expiration
	 */
	public final java.util.Date getExpiration(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Expiration.toString());
	}

	/**
	 * Set value of Expiration
	 * @param expiration
	 */
	public final void setExpiration(java.util.Date expiration)
	{
		setExpiration(getContext(), expiration);
	}

	/**
	 * Set value of Expiration
	 * @param context
	 * @param expiration
	 */
	public final void setExpiration(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date expiration)
	{
		getMendixObject().setValue(context, MemberNames.Expiration.toString(), expiration);
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final awsauthentication.proxies.TemporaryCredentials that = (awsauthentication.proxies.TemporaryCredentials) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
