// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package awsauthentication.proxies;

/**
 * This entity sets the values of the UrlHttpClient. Only the values that are not empty are set on the UrlHttpClient. All values that are left empty are set to the system default. 
 * https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/http/urlconnection/UrlConnectionHttpClient.Builder.html
 */
public class UrlHttpConfig extends awsauthentication.proxies.AbstractHttpConfig
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AWSAuthentication.UrlHttpConfig";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ConnectionTimeOutInMs("ConnectionTimeOutInMs"),
		SocketTimeOutInMs("SocketTimeOutInMs"),
		SdkClientConfig_AbstractHttpConfig("AWSAuthentication.SdkClientConfig_AbstractHttpConfig");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public UrlHttpConfig(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected UrlHttpConfig(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject urlHttpConfigMendixObject)
	{
		super(context, urlHttpConfigMendixObject);
		if (!urlHttpConfigMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static awsauthentication.proxies.UrlHttpConfig initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new awsauthentication.proxies.UrlHttpConfig(context, mendixObject);
	}

	public static awsauthentication.proxies.UrlHttpConfig load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return awsauthentication.proxies.UrlHttpConfig.initialize(context, mendixObject);
	}

	/**
	 * @return value of ConnectionTimeOutInMs
	 */
	public final java.lang.Long getConnectionTimeOutInMs()
	{
		return getConnectionTimeOutInMs(getContext());
	}

	/**
	 * @param context
	 * @return value of ConnectionTimeOutInMs
	 */
	public final java.lang.Long getConnectionTimeOutInMs(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.ConnectionTimeOutInMs.toString());
	}

	/**
	 * Set value of ConnectionTimeOutInMs
	 * @param connectiontimeoutinms
	 */
	public final void setConnectionTimeOutInMs(java.lang.Long connectiontimeoutinms)
	{
		setConnectionTimeOutInMs(getContext(), connectiontimeoutinms);
	}

	/**
	 * Set value of ConnectionTimeOutInMs
	 * @param context
	 * @param connectiontimeoutinms
	 */
	public final void setConnectionTimeOutInMs(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long connectiontimeoutinms)
	{
		getMendixObject().setValue(context, MemberNames.ConnectionTimeOutInMs.toString(), connectiontimeoutinms);
	}

	/**
	 * @return value of SocketTimeOutInMs
	 */
	public final java.lang.Long getSocketTimeOutInMs()
	{
		return getSocketTimeOutInMs(getContext());
	}

	/**
	 * @param context
	 * @return value of SocketTimeOutInMs
	 */
	public final java.lang.Long getSocketTimeOutInMs(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.SocketTimeOutInMs.toString());
	}

	/**
	 * Set value of SocketTimeOutInMs
	 * @param sockettimeoutinms
	 */
	public final void setSocketTimeOutInMs(java.lang.Long sockettimeoutinms)
	{
		setSocketTimeOutInMs(getContext(), sockettimeoutinms);
	}

	/**
	 * Set value of SocketTimeOutInMs
	 * @param context
	 * @param sockettimeoutinms
	 */
	public final void setSocketTimeOutInMs(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long sockettimeoutinms)
	{
		getMendixObject().setValue(context, MemberNames.SocketTimeOutInMs.toString(), sockettimeoutinms);
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final awsauthentication.proxies.UrlHttpConfig that = (awsauthentication.proxies.UrlHttpConfig) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
