// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mxgenaiconnector.proxies;

public class CohereEmbedRequestMapping implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject cohereEmbedRequestMappingMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MxGenAIConnector.CohereEmbedRequestMapping";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		InputType("InputType"),
		EmbeddingTypes("EmbeddingTypes"),
		Truncate("Truncate"),
		CohereEmbedRequestMapping_ChunkCollection("MxGenAIConnector.CohereEmbedRequestMapping_ChunkCollection");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public CohereEmbedRequestMapping(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected CohereEmbedRequestMapping(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject cohereEmbedRequestMappingMendixObject)
	{
		if (cohereEmbedRequestMappingMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!cohereEmbedRequestMappingMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.cohereEmbedRequestMappingMendixObject = cohereEmbedRequestMappingMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static mxgenaiconnector.proxies.CohereEmbedRequestMapping initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new mxgenaiconnector.proxies.CohereEmbedRequestMapping(context, mendixObject);
	}

	public static mxgenaiconnector.proxies.CohereEmbedRequestMapping load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return mxgenaiconnector.proxies.CohereEmbedRequestMapping.initialize(context, mendixObject);
	}

	/**
	 * Get value of InputType
	 * @param inputtype
	 */
	public final mxgenaiconnector.proxies.ENUM_CohereEmbed_InputType getInputType()
	{
		return getInputType(getContext());
	}

	/**
	 * @param context
	 * @return value of InputType
	 */
	public final mxgenaiconnector.proxies.ENUM_CohereEmbed_InputType getInputType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.InputType.toString());
		if (obj == null) {
			return null;
		}
		return mxgenaiconnector.proxies.ENUM_CohereEmbed_InputType.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of InputType
	 * @param inputtype
	 */
	public final void setInputType(mxgenaiconnector.proxies.ENUM_CohereEmbed_InputType inputtype)
	{
		setInputType(getContext(), inputtype);
	}

	/**
	 * Set value of InputType
	 * @param context
	 * @param inputtype
	 */
	public final void setInputType(com.mendix.systemwideinterfaces.core.IContext context, mxgenaiconnector.proxies.ENUM_CohereEmbed_InputType inputtype)
	{
		if (inputtype != null) {
			getMendixObject().setValue(context, MemberNames.InputType.toString(), inputtype.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.InputType.toString(), null);
		}
	}

	/**
	 * Get value of EmbeddingTypes
	 * @param embeddingtypes
	 */
	public final mxgenaiconnector.proxies.ENUM_CohereEmbed_EmbeddingTypes getEmbeddingTypes()
	{
		return getEmbeddingTypes(getContext());
	}

	/**
	 * @param context
	 * @return value of EmbeddingTypes
	 */
	public final mxgenaiconnector.proxies.ENUM_CohereEmbed_EmbeddingTypes getEmbeddingTypes(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.EmbeddingTypes.toString());
		if (obj == null) {
			return null;
		}
		return mxgenaiconnector.proxies.ENUM_CohereEmbed_EmbeddingTypes.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of EmbeddingTypes
	 * @param embeddingtypes
	 */
	public final void setEmbeddingTypes(mxgenaiconnector.proxies.ENUM_CohereEmbed_EmbeddingTypes embeddingtypes)
	{
		setEmbeddingTypes(getContext(), embeddingtypes);
	}

	/**
	 * Set value of EmbeddingTypes
	 * @param context
	 * @param embeddingtypes
	 */
	public final void setEmbeddingTypes(com.mendix.systemwideinterfaces.core.IContext context, mxgenaiconnector.proxies.ENUM_CohereEmbed_EmbeddingTypes embeddingtypes)
	{
		if (embeddingtypes != null) {
			getMendixObject().setValue(context, MemberNames.EmbeddingTypes.toString(), embeddingtypes.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.EmbeddingTypes.toString(), null);
		}
	}

	/**
	 * Get value of Truncate
	 * @param truncate
	 */
	public final mxgenaiconnector.proxies.ENUM_CohereEmbed_Truncate getTruncate()
	{
		return getTruncate(getContext());
	}

	/**
	 * @param context
	 * @return value of Truncate
	 */
	public final mxgenaiconnector.proxies.ENUM_CohereEmbed_Truncate getTruncate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Truncate.toString());
		if (obj == null) {
			return null;
		}
		return mxgenaiconnector.proxies.ENUM_CohereEmbed_Truncate.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Truncate
	 * @param truncate
	 */
	public final void setTruncate(mxgenaiconnector.proxies.ENUM_CohereEmbed_Truncate truncate)
	{
		setTruncate(getContext(), truncate);
	}

	/**
	 * Set value of Truncate
	 * @param context
	 * @param truncate
	 */
	public final void setTruncate(com.mendix.systemwideinterfaces.core.IContext context, mxgenaiconnector.proxies.ENUM_CohereEmbed_Truncate truncate)
	{
		if (truncate != null) {
			getMendixObject().setValue(context, MemberNames.Truncate.toString(), truncate.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.Truncate.toString(), null);
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of CohereEmbedRequestMapping_ChunkCollection
	 */
	public final genaicommons.proxies.ChunkCollection getCohereEmbedRequestMapping_ChunkCollection() throws com.mendix.core.CoreException
	{
		return getCohereEmbedRequestMapping_ChunkCollection(getContext());
	}

	/**
	 * @param context
	 * @return value of CohereEmbedRequestMapping_ChunkCollection
	 * @throws com.mendix.core.CoreException
	 */
	public final genaicommons.proxies.ChunkCollection getCohereEmbedRequestMapping_ChunkCollection(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		genaicommons.proxies.ChunkCollection result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.CohereEmbedRequestMapping_ChunkCollection.toString());
		if (identifier != null) {
			result = genaicommons.proxies.ChunkCollection.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of CohereEmbedRequestMapping_ChunkCollection
	 * @param cohereembedrequestmapping_chunkcollection
	 */
	public final void setCohereEmbedRequestMapping_ChunkCollection(genaicommons.proxies.ChunkCollection cohereembedrequestmapping_chunkcollection)
	{
		setCohereEmbedRequestMapping_ChunkCollection(getContext(), cohereembedrequestmapping_chunkcollection);
	}

	/**
	 * Set value of CohereEmbedRequestMapping_ChunkCollection
	 * @param context
	 * @param cohereembedrequestmapping_chunkcollection
	 */
	public final void setCohereEmbedRequestMapping_ChunkCollection(com.mendix.systemwideinterfaces.core.IContext context, genaicommons.proxies.ChunkCollection cohereembedrequestmapping_chunkcollection)
	{
		if (cohereembedrequestmapping_chunkcollection == null) {
			getMendixObject().setValue(context, MemberNames.CohereEmbedRequestMapping_ChunkCollection.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.CohereEmbedRequestMapping_ChunkCollection.toString(), cohereembedrequestmapping_chunkcollection.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return cohereEmbedRequestMappingMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final mxgenaiconnector.proxies.CohereEmbedRequestMapping that = (mxgenaiconnector.proxies.CohereEmbedRequestMapping) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
