// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mxgenaiconnector.proxies;

/**
 * This entity stores the connectivity information for a MxCloud deployed model or knowledge base resource.
 * It contains the location URL and the credentials, as well as metadata about the key. 
 */
public class Configuration implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject configurationMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MxGenAIConnector.Configuration";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ConfigurationID("ConfigurationID"),
		AccessToken("AccessToken"),
		ResourceBaseUrl("ResourceBaseUrl"),
		Architecture("Architecture"),
		DeepLinkURL("DeepLinkURL"),
		Environment("Environment"),
		KeyName("KeyName"),
		KeyId("KeyId");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Configuration(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Configuration(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject configurationMendixObject)
	{
		if (configurationMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!configurationMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.configurationMendixObject = configurationMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static mxgenaiconnector.proxies.Configuration initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new mxgenaiconnector.proxies.Configuration(context, mendixObject);
	}

	public static mxgenaiconnector.proxies.Configuration load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return mxgenaiconnector.proxies.Configuration.initialize(context, mendixObject);
	}

	public static java.util.List<mxgenaiconnector.proxies.Configuration> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> mxgenaiconnector.proxies.Configuration.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of ConfigurationID
	 */
	public final java.lang.String getConfigurationID()
	{
		return getConfigurationID(getContext());
	}

	/**
	 * @param context
	 * @return value of ConfigurationID
	 */
	public final java.lang.String getConfigurationID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ConfigurationID.toString());
	}

	/**
	 * Set value of ConfigurationID
	 * @param configurationid
	 */
	public final void setConfigurationID(java.lang.String configurationid)
	{
		setConfigurationID(getContext(), configurationid);
	}

	/**
	 * Set value of ConfigurationID
	 * @param context
	 * @param configurationid
	 */
	public final void setConfigurationID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String configurationid)
	{
		getMendixObject().setValue(context, MemberNames.ConfigurationID.toString(), configurationid);
	}

	/**
	 * @return value of AccessToken
	 */
	public final java.lang.String getAccessToken()
	{
		return getAccessToken(getContext());
	}

	/**
	 * @param context
	 * @return value of AccessToken
	 */
	public final java.lang.String getAccessToken(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.AccessToken.toString());
	}

	/**
	 * Set value of AccessToken
	 * @param accesstoken
	 */
	public final void setAccessToken(java.lang.String accesstoken)
	{
		setAccessToken(getContext(), accesstoken);
	}

	/**
	 * Set value of AccessToken
	 * @param context
	 * @param accesstoken
	 */
	public final void setAccessToken(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String accesstoken)
	{
		getMendixObject().setValue(context, MemberNames.AccessToken.toString(), accesstoken);
	}

	/**
	 * @return value of ResourceBaseUrl
	 */
	public final java.lang.String getResourceBaseUrl()
	{
		return getResourceBaseUrl(getContext());
	}

	/**
	 * @param context
	 * @return value of ResourceBaseUrl
	 */
	public final java.lang.String getResourceBaseUrl(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ResourceBaseUrl.toString());
	}

	/**
	 * Set value of ResourceBaseUrl
	 * @param resourcebaseurl
	 */
	public final void setResourceBaseUrl(java.lang.String resourcebaseurl)
	{
		setResourceBaseUrl(getContext(), resourcebaseurl);
	}

	/**
	 * Set value of ResourceBaseUrl
	 * @param context
	 * @param resourcebaseurl
	 */
	public final void setResourceBaseUrl(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String resourcebaseurl)
	{
		getMendixObject().setValue(context, MemberNames.ResourceBaseUrl.toString(), resourcebaseurl);
	}

	/**
	 * Get value of Architecture
	 * @param architecture
	 */
	public final mxgenaiconnector.proxies.ENUM_Architecture getArchitecture()
	{
		return getArchitecture(getContext());
	}

	/**
	 * @param context
	 * @return value of Architecture
	 */
	public final mxgenaiconnector.proxies.ENUM_Architecture getArchitecture(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Architecture.toString());
		if (obj == null) {
			return null;
		}
		return mxgenaiconnector.proxies.ENUM_Architecture.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Architecture
	 * @param architecture
	 */
	public final void setArchitecture(mxgenaiconnector.proxies.ENUM_Architecture architecture)
	{
		setArchitecture(getContext(), architecture);
	}

	/**
	 * Set value of Architecture
	 * @param context
	 * @param architecture
	 */
	public final void setArchitecture(com.mendix.systemwideinterfaces.core.IContext context, mxgenaiconnector.proxies.ENUM_Architecture architecture)
	{
		if (architecture != null) {
			getMendixObject().setValue(context, MemberNames.Architecture.toString(), architecture.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.Architecture.toString(), null);
		}
	}

	/**
	 * @return value of DeepLinkURL
	 */
	public final java.lang.String getDeepLinkURL()
	{
		return getDeepLinkURL(getContext());
	}

	/**
	 * @param context
	 * @return value of DeepLinkURL
	 */
	public final java.lang.String getDeepLinkURL(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DeepLinkURL.toString());
	}

	/**
	 * Set value of DeepLinkURL
	 * @param deeplinkurl
	 */
	public final void setDeepLinkURL(java.lang.String deeplinkurl)
	{
		setDeepLinkURL(getContext(), deeplinkurl);
	}

	/**
	 * Set value of DeepLinkURL
	 * @param context
	 * @param deeplinkurl
	 */
	public final void setDeepLinkURL(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String deeplinkurl)
	{
		getMendixObject().setValue(context, MemberNames.DeepLinkURL.toString(), deeplinkurl);
	}

	/**
	 * @return value of Environment
	 */
	public final java.lang.String getEnvironment()
	{
		return getEnvironment(getContext());
	}

	/**
	 * @param context
	 * @return value of Environment
	 */
	public final java.lang.String getEnvironment(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Environment.toString());
	}

	/**
	 * Set value of Environment
	 * @param environment
	 */
	public final void setEnvironment(java.lang.String environment)
	{
		setEnvironment(getContext(), environment);
	}

	/**
	 * Set value of Environment
	 * @param context
	 * @param environment
	 */
	public final void setEnvironment(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String environment)
	{
		getMendixObject().setValue(context, MemberNames.Environment.toString(), environment);
	}

	/**
	 * @return value of KeyName
	 */
	public final java.lang.String getKeyName()
	{
		return getKeyName(getContext());
	}

	/**
	 * @param context
	 * @return value of KeyName
	 */
	public final java.lang.String getKeyName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.KeyName.toString());
	}

	/**
	 * Set value of KeyName
	 * @param keyname
	 */
	public final void setKeyName(java.lang.String keyname)
	{
		setKeyName(getContext(), keyname);
	}

	/**
	 * Set value of KeyName
	 * @param context
	 * @param keyname
	 */
	public final void setKeyName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String keyname)
	{
		getMendixObject().setValue(context, MemberNames.KeyName.toString(), keyname);
	}

	/**
	 * @return value of KeyId
	 */
	public final java.lang.String getKeyId()
	{
		return getKeyId(getContext());
	}

	/**
	 * @param context
	 * @return value of KeyId
	 */
	public final java.lang.String getKeyId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.KeyId.toString());
	}

	/**
	 * Set value of KeyId
	 * @param keyid
	 */
	public final void setKeyId(java.lang.String keyid)
	{
		setKeyId(getContext(), keyid);
	}

	/**
	 * Set value of KeyId
	 * @param context
	 * @param keyid
	 */
	public final void setKeyId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String keyid)
	{
		getMendixObject().setValue(context, MemberNames.KeyId.toString(), keyid);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return configurationMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final mxgenaiconnector.proxies.Configuration that = (mxgenaiconnector.proxies.Configuration) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
