// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mxgenaiconnector.proxies;

public enum ENUM_CohereEmbed_Truncate
{
	NONE("aca9039b-94c7-468c-9e1f-e9b158864cbd"),
	START("5e35f9ce-55e7-47a1-bf7c-4ec071b8e281"),
	END("a85492ac-3085-459f-8ec4-0f499b8a15fa");

	private final java.lang.String i18nCaptionKey;
	
	private ENUM_CohereEmbed_Truncate(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
