// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mxgenaiconnector.proxies;

public enum ENUM_CohereEmbed_EmbeddingTypes
{
	_float("3475f584-da41-4171-b6c8-acd42f049f5a"),
	int8("a55c2787-a539-49f4-8c9c-0284b2e7023c"),
	uint8("e8ca84e9-c017-483f-ac30-42833dee3e99"),
	binary("d3bfa8d4-c7d4-4d2f-a077-413f24912297"),
	ubinary("b2b4c90c-3036-421b-8717-8478f1ca2593");

	private final java.lang.String i18nCaptionKey;
	
	private ENUM_CohereEmbed_EmbeddingTypes(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
