// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mxgenaiconnector.proxies;

public enum ENUM_CohereEmbed_InputType
{
	search_document("ec5cf125-ded6-4fc7-8358-4688a7b7881a"),
	search_query("9d1fabf3-24e5-44b2-a0fa-d2dae2c2e501"),
	classification("f922c035-17de-4531-91f7-7c19cdab6ffe"),
	clustering("3adce78f-414d-4acc-abd1-b91a68b26896");

	private final java.lang.String i18nCaptionKey;
	
	private ENUM_CohereEmbed_InputType(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
