// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mxgenaiconnector.proxies;

/**
 * Used in the Configuration to determine the resource type.
 */
public enum ENUM_ResourceType
{
	TEXT_GENERATION("63c8eeed-4d31-4daa-b9e0-19f1f5f3edee"),
	KNOWLEDGE_BASE("216462c6-7ead-4711-ab15-26103d83b970"),
	EMBEDDINGS_GENERATION("30f59a1a-5bb3-4c62-875f-81121c44d5bc");

	private final java.lang.String i18nCaptionKey;
	
	private ENUM_ResourceType(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
