// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mxgenaiconnector.proxies;

public class KnowledgeBaseMapping implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject knowledgeBaseMappingMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MxGenAIConnector.KnowledgeBaseMapping";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		MaxNumberOfResults("MaxNumberOfResults"),
		Vector("Vector"),
		KnowledgeBaseMapping_MetadataCollection("MxGenAIConnector.KnowledgeBaseMapping_MetadataCollection");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public KnowledgeBaseMapping(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected KnowledgeBaseMapping(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject knowledgeBaseMappingMendixObject)
	{
		if (knowledgeBaseMappingMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!knowledgeBaseMappingMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.knowledgeBaseMappingMendixObject = knowledgeBaseMappingMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static mxgenaiconnector.proxies.KnowledgeBaseMapping initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new mxgenaiconnector.proxies.KnowledgeBaseMapping(context, mendixObject);
	}

	public static mxgenaiconnector.proxies.KnowledgeBaseMapping load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return mxgenaiconnector.proxies.KnowledgeBaseMapping.initialize(context, mendixObject);
	}

	/**
	 * @return value of MaxNumberOfResults
	 */
	public final java.lang.Integer getMaxNumberOfResults()
	{
		return getMaxNumberOfResults(getContext());
	}

	/**
	 * @param context
	 * @return value of MaxNumberOfResults
	 */
	public final java.lang.Integer getMaxNumberOfResults(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.MaxNumberOfResults.toString());
	}

	/**
	 * Set value of MaxNumberOfResults
	 * @param maxnumberofresults
	 */
	public final void setMaxNumberOfResults(java.lang.Integer maxnumberofresults)
	{
		setMaxNumberOfResults(getContext(), maxnumberofresults);
	}

	/**
	 * Set value of MaxNumberOfResults
	 * @param context
	 * @param maxnumberofresults
	 */
	public final void setMaxNumberOfResults(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer maxnumberofresults)
	{
		getMendixObject().setValue(context, MemberNames.MaxNumberOfResults.toString(), maxnumberofresults);
	}

	/**
	 * @return value of Vector
	 */
	public final java.lang.String getVector()
	{
		return getVector(getContext());
	}

	/**
	 * @param context
	 * @return value of Vector
	 */
	public final java.lang.String getVector(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Vector.toString());
	}

	/**
	 * Set value of Vector
	 * @param vector
	 */
	public final void setVector(java.lang.String vector)
	{
		setVector(getContext(), vector);
	}

	/**
	 * Set value of Vector
	 * @param context
	 * @param vector
	 */
	public final void setVector(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String vector)
	{
		getMendixObject().setValue(context, MemberNames.Vector.toString(), vector);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of KnowledgeBaseMapping_MetadataCollection
	 */
	public final genaicommons.proxies.MetadataCollection getKnowledgeBaseMapping_MetadataCollection() throws com.mendix.core.CoreException
	{
		return getKnowledgeBaseMapping_MetadataCollection(getContext());
	}

	/**
	 * @param context
	 * @return value of KnowledgeBaseMapping_MetadataCollection
	 * @throws com.mendix.core.CoreException
	 */
	public final genaicommons.proxies.MetadataCollection getKnowledgeBaseMapping_MetadataCollection(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		genaicommons.proxies.MetadataCollection result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.KnowledgeBaseMapping_MetadataCollection.toString());
		if (identifier != null) {
			result = genaicommons.proxies.MetadataCollection.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of KnowledgeBaseMapping_MetadataCollection
	 * @param knowledgebasemapping_metadatacollection
	 */
	public final void setKnowledgeBaseMapping_MetadataCollection(genaicommons.proxies.MetadataCollection knowledgebasemapping_metadatacollection)
	{
		setKnowledgeBaseMapping_MetadataCollection(getContext(), knowledgebasemapping_metadatacollection);
	}

	/**
	 * Set value of KnowledgeBaseMapping_MetadataCollection
	 * @param context
	 * @param knowledgebasemapping_metadatacollection
	 */
	public final void setKnowledgeBaseMapping_MetadataCollection(com.mendix.systemwideinterfaces.core.IContext context, genaicommons.proxies.MetadataCollection knowledgebasemapping_metadatacollection)
	{
		if (knowledgebasemapping_metadatacollection == null) {
			getMendixObject().setValue(context, MemberNames.KnowledgeBaseMapping_MetadataCollection.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.KnowledgeBaseMapping_MetadataCollection.toString(), knowledgebasemapping_metadatacollection.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return knowledgeBaseMappingMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final mxgenaiconnector.proxies.KnowledgeBaseMapping that = (mxgenaiconnector.proxies.KnowledgeBaseMapping) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
