// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mxgenaiconnector.proxies;

public class RequestExtension implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject requestExtensionMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MxGenAIConnector.RequestExtension";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ToolUseContent("ToolUseContent"),
		RequestExtension_Request("MxGenAIConnector.RequestExtension_Request");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public RequestExtension(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected RequestExtension(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject requestExtensionMendixObject)
	{
		if (requestExtensionMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!requestExtensionMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.requestExtensionMendixObject = requestExtensionMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static mxgenaiconnector.proxies.RequestExtension initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new mxgenaiconnector.proxies.RequestExtension(context, mendixObject);
	}

	public static mxgenaiconnector.proxies.RequestExtension load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return mxgenaiconnector.proxies.RequestExtension.initialize(context, mendixObject);
	}

	/**
	 * @return value of ToolUseContent
	 */
	public final java.lang.String getToolUseContent()
	{
		return getToolUseContent(getContext());
	}

	/**
	 * @param context
	 * @return value of ToolUseContent
	 */
	public final java.lang.String getToolUseContent(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ToolUseContent.toString());
	}

	/**
	 * Set value of ToolUseContent
	 * @param toolusecontent
	 */
	public final void setToolUseContent(java.lang.String toolusecontent)
	{
		setToolUseContent(getContext(), toolusecontent);
	}

	/**
	 * Set value of ToolUseContent
	 * @param context
	 * @param toolusecontent
	 */
	public final void setToolUseContent(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String toolusecontent)
	{
		getMendixObject().setValue(context, MemberNames.ToolUseContent.toString(), toolusecontent);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of RequestExtension_Request
	 */
	public final genaicommons.proxies.Request getRequestExtension_Request() throws com.mendix.core.CoreException
	{
		return getRequestExtension_Request(getContext());
	}

	/**
	 * @param context
	 * @return value of RequestExtension_Request
	 * @throws com.mendix.core.CoreException
	 */
	public final genaicommons.proxies.Request getRequestExtension_Request(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		genaicommons.proxies.Request result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.RequestExtension_Request.toString());
		if (identifier != null) {
			result = genaicommons.proxies.Request.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of RequestExtension_Request
	 * @param requestextension_request
	 */
	public final void setRequestExtension_Request(genaicommons.proxies.Request requestextension_request)
	{
		setRequestExtension_Request(getContext(), requestextension_request);
	}

	/**
	 * Set value of RequestExtension_Request
	 * @param context
	 * @param requestextension_request
	 */
	public final void setRequestExtension_Request(com.mendix.systemwideinterfaces.core.IContext context, genaicommons.proxies.Request requestextension_request)
	{
		if (requestextension_request == null) {
			getMendixObject().setValue(context, MemberNames.RequestExtension_Request.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.RequestExtension_Request.toString(), requestextension_request.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return requestExtensionMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final mxgenaiconnector.proxies.RequestExtension that = (mxgenaiconnector.proxies.RequestExtension) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
