// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mxgenaiconnector.proxies;

public class RetrieveResponse implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject retrieveResponseMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MxGenAIConnector.RetrieveResponse";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Size("Size"),
		Number("Number"),
		NumberOfElements("NumberOfElements"),
		IsFirst("IsFirst"),
		IsLast("IsLast"),
		TotalPages("TotalPages"),
		TotalElements("TotalElements"),
		RetrieveResponse_KnowledgeBaseChunk("MxGenAIConnector.RetrieveResponse_KnowledgeBaseChunk");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public RetrieveResponse(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected RetrieveResponse(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject retrieveResponseMendixObject)
	{
		if (retrieveResponseMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!retrieveResponseMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.retrieveResponseMendixObject = retrieveResponseMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static mxgenaiconnector.proxies.RetrieveResponse initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new mxgenaiconnector.proxies.RetrieveResponse(context, mendixObject);
	}

	public static mxgenaiconnector.proxies.RetrieveResponse load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return mxgenaiconnector.proxies.RetrieveResponse.initialize(context, mendixObject);
	}

	/**
	 * @return value of Size
	 */
	public final java.lang.Integer getSize()
	{
		return getSize(getContext());
	}

	/**
	 * @param context
	 * @return value of Size
	 */
	public final java.lang.Integer getSize(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Size.toString());
	}

	/**
	 * Set value of Size
	 * @param size
	 */
	public final void setSize(java.lang.Integer size)
	{
		setSize(getContext(), size);
	}

	/**
	 * Set value of Size
	 * @param context
	 * @param size
	 */
	public final void setSize(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer size)
	{
		getMendixObject().setValue(context, MemberNames.Size.toString(), size);
	}

	/**
	 * @return value of Number
	 */
	public final java.lang.Integer getNumber()
	{
		return getNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of Number
	 */
	public final java.lang.Integer getNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Number.toString());
	}

	/**
	 * Set value of Number
	 * @param number
	 */
	public final void setNumber(java.lang.Integer number)
	{
		setNumber(getContext(), number);
	}

	/**
	 * Set value of Number
	 * @param context
	 * @param number
	 */
	public final void setNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer number)
	{
		getMendixObject().setValue(context, MemberNames.Number.toString(), number);
	}

	/**
	 * @return value of NumberOfElements
	 */
	public final java.lang.Integer getNumberOfElements()
	{
		return getNumberOfElements(getContext());
	}

	/**
	 * @param context
	 * @return value of NumberOfElements
	 */
	public final java.lang.Integer getNumberOfElements(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.NumberOfElements.toString());
	}

	/**
	 * Set value of NumberOfElements
	 * @param numberofelements
	 */
	public final void setNumberOfElements(java.lang.Integer numberofelements)
	{
		setNumberOfElements(getContext(), numberofelements);
	}

	/**
	 * Set value of NumberOfElements
	 * @param context
	 * @param numberofelements
	 */
	public final void setNumberOfElements(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer numberofelements)
	{
		getMendixObject().setValue(context, MemberNames.NumberOfElements.toString(), numberofelements);
	}

	/**
	 * @return value of IsFirst
	 */
	public final java.lang.Boolean getIsFirst()
	{
		return getIsFirst(getContext());
	}

	/**
	 * @param context
	 * @return value of IsFirst
	 */
	public final java.lang.Boolean getIsFirst(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsFirst.toString());
	}

	/**
	 * Set value of IsFirst
	 * @param isfirst
	 */
	public final void setIsFirst(java.lang.Boolean isfirst)
	{
		setIsFirst(getContext(), isfirst);
	}

	/**
	 * Set value of IsFirst
	 * @param context
	 * @param isfirst
	 */
	public final void setIsFirst(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isfirst)
	{
		getMendixObject().setValue(context, MemberNames.IsFirst.toString(), isfirst);
	}

	/**
	 * @return value of IsLast
	 */
	public final java.lang.Boolean getIsLast()
	{
		return getIsLast(getContext());
	}

	/**
	 * @param context
	 * @return value of IsLast
	 */
	public final java.lang.Boolean getIsLast(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsLast.toString());
	}

	/**
	 * Set value of IsLast
	 * @param islast
	 */
	public final void setIsLast(java.lang.Boolean islast)
	{
		setIsLast(getContext(), islast);
	}

	/**
	 * Set value of IsLast
	 * @param context
	 * @param islast
	 */
	public final void setIsLast(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean islast)
	{
		getMendixObject().setValue(context, MemberNames.IsLast.toString(), islast);
	}

	/**
	 * @return value of TotalPages
	 */
	public final java.lang.Integer getTotalPages()
	{
		return getTotalPages(getContext());
	}

	/**
	 * @param context
	 * @return value of TotalPages
	 */
	public final java.lang.Integer getTotalPages(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.TotalPages.toString());
	}

	/**
	 * Set value of TotalPages
	 * @param totalpages
	 */
	public final void setTotalPages(java.lang.Integer totalpages)
	{
		setTotalPages(getContext(), totalpages);
	}

	/**
	 * Set value of TotalPages
	 * @param context
	 * @param totalpages
	 */
	public final void setTotalPages(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer totalpages)
	{
		getMendixObject().setValue(context, MemberNames.TotalPages.toString(), totalpages);
	}

	/**
	 * @return value of TotalElements
	 */
	public final java.lang.Integer getTotalElements()
	{
		return getTotalElements(getContext());
	}

	/**
	 * @param context
	 * @return value of TotalElements
	 */
	public final java.lang.Integer getTotalElements(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.TotalElements.toString());
	}

	/**
	 * Set value of TotalElements
	 * @param totalelements
	 */
	public final void setTotalElements(java.lang.Integer totalelements)
	{
		setTotalElements(getContext(), totalelements);
	}

	/**
	 * Set value of TotalElements
	 * @param context
	 * @param totalelements
	 */
	public final void setTotalElements(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer totalelements)
	{
		getMendixObject().setValue(context, MemberNames.TotalElements.toString(), totalelements);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of RetrieveResponse_KnowledgeBaseChunk
	 */
	public final java.util.List<genaicommons.proxies.KnowledgeBaseChunk> getRetrieveResponse_KnowledgeBaseChunk() throws com.mendix.core.CoreException
	{
		return getRetrieveResponse_KnowledgeBaseChunk(getContext());
	}

	/**
	 * @param context
	 * @return value of RetrieveResponse_KnowledgeBaseChunk
	 * @throws com.mendix.core.CoreException
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<genaicommons.proxies.KnowledgeBaseChunk> getRetrieveResponse_KnowledgeBaseChunk(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<genaicommons.proxies.KnowledgeBaseChunk> result = new java.util.ArrayList<>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.RetrieveResponse_KnowledgeBaseChunk.toString());
		if (valueObject == null) {
			return result;
		}
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject)) {
			result.add(genaicommons.proxies.KnowledgeBaseChunk.initialize(context, mendixObject));
		}
		return result;
	}

	/**
	 * Set value of RetrieveResponse_KnowledgeBaseChunk
	 * @param retrieveresponse_knowledgebasechunk
	 */
	public final void setRetrieveResponse_KnowledgeBaseChunk(java.util.List<genaicommons.proxies.KnowledgeBaseChunk> retrieveresponse_knowledgebasechunk)
	{
		setRetrieveResponse_KnowledgeBaseChunk(getContext(), retrieveresponse_knowledgebasechunk);
	}

	/**
	 * Set value of RetrieveResponse_KnowledgeBaseChunk
	 * @param context
	 * @param retrieveresponse_knowledgebasechunk
	 */
	public final void setRetrieveResponse_KnowledgeBaseChunk(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<genaicommons.proxies.KnowledgeBaseChunk> retrieveresponse_knowledgebasechunk)
	{
		var identifiers = retrieveresponse_knowledgebasechunk
			.stream()
			.map(proxyObject -> proxyObject.getMendixObject().getId())
			.collect(java.util.stream.Collectors.toList());
		
		getMendixObject().setValue(context, MemberNames.RetrieveResponse_KnowledgeBaseChunk.toString(), identifiers);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return retrieveResponseMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final mxgenaiconnector.proxies.RetrieveResponse that = (mxgenaiconnector.proxies.RetrieveResponse) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
