// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package conversationalui.proxies.constants;

import com.mendix.core.Core;

public final class Constants
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Constants() {}

	// These are the constants for the ConversationalUI module

	/**
	* When set to true, assistant messages written in Markdown format are rendered as such. If set to false messages are rendered as plain text.
	*/
	public static boolean getEnableMarkdownViewer()
	{
		return (java.lang.Boolean)Core.getConfiguration().getConstantValue("ConversationalUI.EnableMarkdownViewer");
	}

	public static java.lang.String getLogNode()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("ConversationalUI.LogNode");
	}

	/**
	* The text that is displayed below the user input field in the chat. This can be used for keystroke instructions or general GenAI disclaimers.
	* If you leave it blank, nothing will be displayed.
	*/
	public static java.lang.String getUserInputInstructions()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("ConversationalUI.UserInputInstructions");
	}
}