// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package genaicommons.proxies;

/**
 * For the action Request_AddTool a list of ArgumentInput can be passed. Those are used to create the required input schema for the model (inside of the individual connectors). This is useful when the actual tool is not a microflow, but just passing the input from the model to an external service.
 */
public class ArgumentInput implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject argumentInputMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "GenAICommons.ArgumentInput";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		_Type("_Type"),
		Required("Required"),
		ArgumentInput_EnumValue("GenAICommons.ArgumentInput_EnumValue");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ArgumentInput(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ArgumentInput(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject argumentInputMendixObject)
	{
		if (argumentInputMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!argumentInputMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.argumentInputMendixObject = argumentInputMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static genaicommons.proxies.ArgumentInput initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new genaicommons.proxies.ArgumentInput(context, mendixObject);
	}

	public static genaicommons.proxies.ArgumentInput load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return genaicommons.proxies.ArgumentInput.initialize(context, mendixObject);
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of _Type
	 */
	public final java.lang.String get_Type()
	{
		return get_Type(getContext());
	}

	/**
	 * @param context
	 * @return value of _Type
	 */
	public final java.lang.String get_Type(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames._Type.toString());
	}

	/**
	 * Set value of _Type
	 * @param _type
	 */
	public final void set_Type(java.lang.String _type)
	{
		set_Type(getContext(), _type);
	}

	/**
	 * Set value of _Type
	 * @param context
	 * @param _type
	 */
	public final void set_Type(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String _type)
	{
		getMendixObject().setValue(context, MemberNames._Type.toString(), _type);
	}

	/**
	 * @return value of Required
	 */
	public final java.lang.Boolean getRequired()
	{
		return getRequired(getContext());
	}

	/**
	 * @param context
	 * @return value of Required
	 */
	public final java.lang.Boolean getRequired(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Required.toString());
	}

	/**
	 * Set value of Required
	 * @param required
	 */
	public final void setRequired(java.lang.Boolean required)
	{
		setRequired(getContext(), required);
	}

	/**
	 * Set value of Required
	 * @param context
	 * @param required
	 */
	public final void setRequired(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean required)
	{
		getMendixObject().setValue(context, MemberNames.Required.toString(), required);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ArgumentInput_EnumValue
	 */
	public final java.util.List<genaicommons.proxies.EnumValue> getArgumentInput_EnumValue() throws com.mendix.core.CoreException
	{
		return getArgumentInput_EnumValue(getContext());
	}

	/**
	 * @param context
	 * @return value of ArgumentInput_EnumValue
	 * @throws com.mendix.core.CoreException
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<genaicommons.proxies.EnumValue> getArgumentInput_EnumValue(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<genaicommons.proxies.EnumValue> result = new java.util.ArrayList<>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.ArgumentInput_EnumValue.toString());
		if (valueObject == null) {
			return result;
		}
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject)) {
			result.add(genaicommons.proxies.EnumValue.initialize(context, mendixObject));
		}
		return result;
	}

	/**
	 * Set value of ArgumentInput_EnumValue
	 * @param argumentinput_enumvalue
	 */
	public final void setArgumentInput_EnumValue(java.util.List<genaicommons.proxies.EnumValue> argumentinput_enumvalue)
	{
		setArgumentInput_EnumValue(getContext(), argumentinput_enumvalue);
	}

	/**
	 * Set value of ArgumentInput_EnumValue
	 * @param context
	 * @param argumentinput_enumvalue
	 */
	public final void setArgumentInput_EnumValue(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<genaicommons.proxies.EnumValue> argumentinput_enumvalue)
	{
		var identifiers = argumentinput_enumvalue
			.stream()
			.map(proxyObject -> proxyObject.getMendixObject().getId())
			.collect(java.util.stream.Collectors.toList());
		
		getMendixObject().setValue(context, MemberNames.ArgumentInput_EnumValue.toString(), identifiers);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return argumentInputMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final genaicommons.proxies.ArgumentInput that = (genaicommons.proxies.ArgumentInput) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
