// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package genaicommons.proxies;

public enum ENUM_ToolChoice
{
	auto("4401794f-2dff-4147-8da6-74ef25643616"),
	none("406b2b8d-a197-4cb2-b15b-5fc0ff1324f2"),
	any("c88b9d69-c467-4350-9809-7ebc4e653afe"),
	tool("75530637-472e-4c50-af2f-54e3b9647104");

	private final java.lang.String i18nCaptionKey;
	
	private ENUM_ToolChoice(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
