// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package genaicommons.proxies;

public enum ENUM_MessageRole
{
	user("231aeb61-fe45-4a1c-86de-df0d2aa5620f"),
	assistant("fadcfaec-c887-4f5a-a09a-126124f1d101"),
	system("9660e175-3582-49c0-9f20-40ea94b43371"),
	tool("2093f43a-5b63-4dd5-9a1f-3920aa98a447");

	private final java.lang.String i18nCaptionKey;
	
	private ENUM_MessageRole(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
