// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package genaicommons.proxies;

public enum ENUM_ModelSupport
{
	_True("3a6d40a0-ee4e-42d3-8c32-e0f8bed8a480"),
	_False("f9e83564-9e7c-4e76-8258-29fb665af9e4"),
	Unknown("3f5b7ad2-88d4-4bbf-9341-b3494f63e7da");

	private final java.lang.String i18nCaptionKey;
	
	private ENUM_ModelSupport(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
