// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package genaicommons.proxies;

/**
 * A knowledge base span is created for each knowledge base retrieval tool call that the LLM requested. The tool call is processed in GenAI Commons and the result is sent back to the model.
 */
public class KnowledgeBaseSpan extends genaicommons.proxies.ToolSpan
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "GenAICommons.KnowledgeBaseSpan";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Architecture("Architecture"),
		MinimumSimilarity("MinimumSimilarity"),
		MaxNumberOfResults("MaxNumberOfResults"),
		KBDisplayName("KBDisplayName"),
		ToolName("ToolName"),
		ToolDescription("ToolDescription"),
		_ToolCallId("_ToolCallId"),
		SpanId("SpanId"),
		Input("Input"),
		Output("Output"),
		StartTime("StartTime"),
		EndTime("EndTime"),
		DurationMilliseconds("DurationMilliseconds"),
		IsError("IsError"),
		Span_Trace("GenAICommons.Span_Trace"),
		Span_SubSpan("GenAICommons.Span_SubSpan");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public KnowledgeBaseSpan(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected KnowledgeBaseSpan(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject knowledgeBaseSpanMendixObject)
	{
		super(context, knowledgeBaseSpanMendixObject);
		if (!knowledgeBaseSpanMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static genaicommons.proxies.KnowledgeBaseSpan initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new genaicommons.proxies.KnowledgeBaseSpan(context, mendixObject);
	}

	public static genaicommons.proxies.KnowledgeBaseSpan load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return genaicommons.proxies.KnowledgeBaseSpan.initialize(context, mendixObject);
	}

	public static java.util.List<genaicommons.proxies.KnowledgeBaseSpan> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> genaicommons.proxies.KnowledgeBaseSpan.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of Architecture
	 */
	public final java.lang.String getArchitecture()
	{
		return getArchitecture(getContext());
	}

	/**
	 * @param context
	 * @return value of Architecture
	 */
	public final java.lang.String getArchitecture(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Architecture.toString());
	}

	/**
	 * Set value of Architecture
	 * @param architecture
	 */
	public final void setArchitecture(java.lang.String architecture)
	{
		setArchitecture(getContext(), architecture);
	}

	/**
	 * Set value of Architecture
	 * @param context
	 * @param architecture
	 */
	public final void setArchitecture(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String architecture)
	{
		getMendixObject().setValue(context, MemberNames.Architecture.toString(), architecture);
	}

	/**
	 * @return value of MinimumSimilarity
	 */
	public final java.math.BigDecimal getMinimumSimilarity()
	{
		return getMinimumSimilarity(getContext());
	}

	/**
	 * @param context
	 * @return value of MinimumSimilarity
	 */
	public final java.math.BigDecimal getMinimumSimilarity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.MinimumSimilarity.toString());
	}

	/**
	 * Set value of MinimumSimilarity
	 * @param minimumsimilarity
	 */
	public final void setMinimumSimilarity(java.math.BigDecimal minimumsimilarity)
	{
		setMinimumSimilarity(getContext(), minimumsimilarity);
	}

	/**
	 * Set value of MinimumSimilarity
	 * @param context
	 * @param minimumsimilarity
	 */
	public final void setMinimumSimilarity(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal minimumsimilarity)
	{
		getMendixObject().setValue(context, MemberNames.MinimumSimilarity.toString(), minimumsimilarity);
	}

	/**
	 * @return value of MaxNumberOfResults
	 */
	public final java.lang.Integer getMaxNumberOfResults()
	{
		return getMaxNumberOfResults(getContext());
	}

	/**
	 * @param context
	 * @return value of MaxNumberOfResults
	 */
	public final java.lang.Integer getMaxNumberOfResults(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.MaxNumberOfResults.toString());
	}

	/**
	 * Set value of MaxNumberOfResults
	 * @param maxnumberofresults
	 */
	public final void setMaxNumberOfResults(java.lang.Integer maxnumberofresults)
	{
		setMaxNumberOfResults(getContext(), maxnumberofresults);
	}

	/**
	 * Set value of MaxNumberOfResults
	 * @param context
	 * @param maxnumberofresults
	 */
	public final void setMaxNumberOfResults(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer maxnumberofresults)
	{
		getMendixObject().setValue(context, MemberNames.MaxNumberOfResults.toString(), maxnumberofresults);
	}

	/**
	 * @return value of KBDisplayName
	 */
	public final java.lang.String getKBDisplayName()
	{
		return getKBDisplayName(getContext());
	}

	/**
	 * @param context
	 * @return value of KBDisplayName
	 */
	public final java.lang.String getKBDisplayName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.KBDisplayName.toString());
	}

	/**
	 * Set value of KBDisplayName
	 * @param kbdisplayname
	 */
	public final void setKBDisplayName(java.lang.String kbdisplayname)
	{
		setKBDisplayName(getContext(), kbdisplayname);
	}

	/**
	 * Set value of KBDisplayName
	 * @param context
	 * @param kbdisplayname
	 */
	public final void setKBDisplayName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String kbdisplayname)
	{
		getMendixObject().setValue(context, MemberNames.KBDisplayName.toString(), kbdisplayname);
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final genaicommons.proxies.KnowledgeBaseSpan that = (genaicommons.proxies.KnowledgeBaseSpan) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
