// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package genaicommons.proxies;

/**
 * An MCP span is created for each tool invokation over the Model Context Protocol via the MCP Client module. The tool call is processed on the MCP server, usually outside of this application, and the result is sent back to the model.
 */
public class MCPSpan extends genaicommons.proxies.ToolSpan
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "GenAICommons.MCPSpan";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ServerName("ServerName"),
		ToolName("ToolName"),
		ToolDescription("ToolDescription"),
		_ToolCallId("_ToolCallId"),
		SpanId("SpanId"),
		Input("Input"),
		Output("Output"),
		StartTime("StartTime"),
		EndTime("EndTime"),
		DurationMilliseconds("DurationMilliseconds"),
		IsError("IsError"),
		Span_Trace("GenAICommons.Span_Trace"),
		Span_SubSpan("GenAICommons.Span_SubSpan");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public MCPSpan(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected MCPSpan(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mCPSpanMendixObject)
	{
		super(context, mCPSpanMendixObject);
		if (!mCPSpanMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static genaicommons.proxies.MCPSpan initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new genaicommons.proxies.MCPSpan(context, mendixObject);
	}

	public static genaicommons.proxies.MCPSpan load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return genaicommons.proxies.MCPSpan.initialize(context, mendixObject);
	}

	public static java.util.List<genaicommons.proxies.MCPSpan> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> genaicommons.proxies.MCPSpan.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of ServerName
	 */
	public final java.lang.String getServerName()
	{
		return getServerName(getContext());
	}

	/**
	 * @param context
	 * @return value of ServerName
	 */
	public final java.lang.String getServerName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ServerName.toString());
	}

	/**
	 * Set value of ServerName
	 * @param servername
	 */
	public final void setServerName(java.lang.String servername)
	{
		setServerName(getContext(), servername);
	}

	/**
	 * Set value of ServerName
	 * @param context
	 * @param servername
	 */
	public final void setServerName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String servername)
	{
		getMendixObject().setValue(context, MemberNames.ServerName.toString(), servername);
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final genaicommons.proxies.MCPSpan that = (genaicommons.proxies.MCPSpan) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
