// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package genaicommons.proxies;

/**
 * A span is created for each interaction between Mendix and the LLM (chat completions, tool calling, ...). If applicable, a sub span (e.g. for a tool or knowledge base operation happening during a model invocation) is associated to the surrounding span.
 */
public class Span implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject spanMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "GenAICommons.Span";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		SpanId("SpanId"),
		Input("Input"),
		Output("Output"),
		StartTime("StartTime"),
		EndTime("EndTime"),
		DurationMilliseconds("DurationMilliseconds"),
		IsError("IsError"),
		Span_Trace("GenAICommons.Span_Trace"),
		Span_SubSpan("GenAICommons.Span_SubSpan");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Span(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Span(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject spanMendixObject)
	{
		if (spanMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!spanMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.spanMendixObject = spanMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static genaicommons.proxies.Span initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		if (mendixObject.isInstanceOf("GenAICommons.ModelSpan")) {
			return genaicommons.proxies.ModelSpan.initialize(context, mendixObject);
		}
		if (mendixObject.isInstanceOf("GenAICommons.ToolSpan")) {
			return genaicommons.proxies.ToolSpan.initialize(context, mendixObject);
		}
		return new genaicommons.proxies.Span(context, mendixObject);
	}

	public static genaicommons.proxies.Span load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return genaicommons.proxies.Span.initialize(context, mendixObject);
	}

	public static java.util.List<? extends genaicommons.proxies.Span> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> genaicommons.proxies.Span.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of SpanId
	 */
	public final java.lang.String getSpanId()
	{
		return getSpanId(getContext());
	}

	/**
	 * @param context
	 * @return value of SpanId
	 */
	public final java.lang.String getSpanId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SpanId.toString());
	}

	/**
	 * Set value of SpanId
	 * @param spanid
	 */
	public final void setSpanId(java.lang.String spanid)
	{
		setSpanId(getContext(), spanid);
	}

	/**
	 * Set value of SpanId
	 * @param context
	 * @param spanid
	 */
	public final void setSpanId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String spanid)
	{
		getMendixObject().setValue(context, MemberNames.SpanId.toString(), spanid);
	}

	/**
	 * @return value of Input
	 */
	public final java.lang.String getInput()
	{
		return getInput(getContext());
	}

	/**
	 * @param context
	 * @return value of Input
	 */
	public final java.lang.String getInput(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Input.toString());
	}

	/**
	 * Set value of Input
	 * @param input
	 */
	public final void setInput(java.lang.String input)
	{
		setInput(getContext(), input);
	}

	/**
	 * Set value of Input
	 * @param context
	 * @param input
	 */
	public final void setInput(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String input)
	{
		getMendixObject().setValue(context, MemberNames.Input.toString(), input);
	}

	/**
	 * @return value of Output
	 */
	public final java.lang.String getOutput()
	{
		return getOutput(getContext());
	}

	/**
	 * @param context
	 * @return value of Output
	 */
	public final java.lang.String getOutput(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Output.toString());
	}

	/**
	 * Set value of Output
	 * @param output
	 */
	public final void setOutput(java.lang.String output)
	{
		setOutput(getContext(), output);
	}

	/**
	 * Set value of Output
	 * @param context
	 * @param output
	 */
	public final void setOutput(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String output)
	{
		getMendixObject().setValue(context, MemberNames.Output.toString(), output);
	}

	/**
	 * @return value of StartTime
	 */
	public final java.util.Date getStartTime()
	{
		return getStartTime(getContext());
	}

	/**
	 * @param context
	 * @return value of StartTime
	 */
	public final java.util.Date getStartTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.StartTime.toString());
	}

	/**
	 * Set value of StartTime
	 * @param starttime
	 */
	public final void setStartTime(java.util.Date starttime)
	{
		setStartTime(getContext(), starttime);
	}

	/**
	 * Set value of StartTime
	 * @param context
	 * @param starttime
	 */
	public final void setStartTime(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date starttime)
	{
		getMendixObject().setValue(context, MemberNames.StartTime.toString(), starttime);
	}

	/**
	 * @return value of EndTime
	 */
	public final java.util.Date getEndTime()
	{
		return getEndTime(getContext());
	}

	/**
	 * @param context
	 * @return value of EndTime
	 */
	public final java.util.Date getEndTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.EndTime.toString());
	}

	/**
	 * Set value of EndTime
	 * @param endtime
	 */
	public final void setEndTime(java.util.Date endtime)
	{
		setEndTime(getContext(), endtime);
	}

	/**
	 * Set value of EndTime
	 * @param context
	 * @param endtime
	 */
	public final void setEndTime(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date endtime)
	{
		getMendixObject().setValue(context, MemberNames.EndTime.toString(), endtime);
	}

	/**
	 * @return value of DurationMilliseconds
	 */
	public final java.lang.Integer getDurationMilliseconds()
	{
		return getDurationMilliseconds(getContext());
	}

	/**
	 * @param context
	 * @return value of DurationMilliseconds
	 */
	public final java.lang.Integer getDurationMilliseconds(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.DurationMilliseconds.toString());
	}

	/**
	 * Set value of DurationMilliseconds
	 * @param durationmilliseconds
	 */
	public final void setDurationMilliseconds(java.lang.Integer durationmilliseconds)
	{
		setDurationMilliseconds(getContext(), durationmilliseconds);
	}

	/**
	 * Set value of DurationMilliseconds
	 * @param context
	 * @param durationmilliseconds
	 */
	public final void setDurationMilliseconds(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer durationmilliseconds)
	{
		getMendixObject().setValue(context, MemberNames.DurationMilliseconds.toString(), durationmilliseconds);
	}

	/**
	 * @return value of IsError
	 */
	public final java.lang.Boolean getIsError()
	{
		return getIsError(getContext());
	}

	/**
	 * @param context
	 * @return value of IsError
	 */
	public final java.lang.Boolean getIsError(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsError.toString());
	}

	/**
	 * Set value of IsError
	 * @param iserror
	 */
	public final void setIsError(java.lang.Boolean iserror)
	{
		setIsError(getContext(), iserror);
	}

	/**
	 * Set value of IsError
	 * @param context
	 * @param iserror
	 */
	public final void setIsError(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean iserror)
	{
		getMendixObject().setValue(context, MemberNames.IsError.toString(), iserror);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Span_Trace
	 */
	public final genaicommons.proxies.Trace getSpan_Trace() throws com.mendix.core.CoreException
	{
		return getSpan_Trace(getContext());
	}

	/**
	 * @param context
	 * @return value of Span_Trace
	 * @throws com.mendix.core.CoreException
	 */
	public final genaicommons.proxies.Trace getSpan_Trace(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		genaicommons.proxies.Trace result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Span_Trace.toString());
		if (identifier != null) {
			result = genaicommons.proxies.Trace.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Span_Trace
	 * @param span_trace
	 */
	public final void setSpan_Trace(genaicommons.proxies.Trace span_trace)
	{
		setSpan_Trace(getContext(), span_trace);
	}

	/**
	 * Set value of Span_Trace
	 * @param context
	 * @param span_trace
	 */
	public final void setSpan_Trace(com.mendix.systemwideinterfaces.core.IContext context, genaicommons.proxies.Trace span_trace)
	{
		if (span_trace == null) {
			getMendixObject().setValue(context, MemberNames.Span_Trace.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Span_Trace.toString(), span_trace.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Span_SubSpan
	 */
	public final genaicommons.proxies.Span getSpan_SubSpan() throws com.mendix.core.CoreException
	{
		return getSpan_SubSpan(getContext());
	}

	/**
	 * @param context
	 * @return value of Span_SubSpan
	 * @throws com.mendix.core.CoreException
	 */
	public final genaicommons.proxies.Span getSpan_SubSpan(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		genaicommons.proxies.Span result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Span_SubSpan.toString());
		if (identifier != null) {
			result = genaicommons.proxies.Span.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Span_SubSpan
	 * @param span_subspan
	 */
	public final void setSpan_SubSpan(genaicommons.proxies.Span span_subspan)
	{
		setSpan_SubSpan(getContext(), span_subspan);
	}

	/**
	 * Set value of Span_SubSpan
	 * @param context
	 * @param span_subspan
	 */
	public final void setSpan_SubSpan(com.mendix.systemwideinterfaces.core.IContext context, genaicommons.proxies.Span span_subspan)
	{
		if (span_subspan == null) {
			getMendixObject().setValue(context, MemberNames.Span_SubSpan.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Span_SubSpan.toString(), span_subspan.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return spanMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final genaicommons.proxies.Span that = (genaicommons.proxies.Span) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
