// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package genaicommons.proxies;

/**
 * A tool call object may be generated by the model in certain scenarios, such as a function call pattern. This entity is only applicable for messages with role `assistant`.
 */
public class ToolCall implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject toolCallMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "GenAICommons.ToolCall";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		ToolType("ToolType"),
		ToolCallId("ToolCallId"),
		ToolCall_Argument("GenAICommons.ToolCall_Argument");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ToolCall(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ToolCall(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject toolCallMendixObject)
	{
		if (toolCallMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!toolCallMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.toolCallMendixObject = toolCallMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static genaicommons.proxies.ToolCall initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new genaicommons.proxies.ToolCall(context, mendixObject);
	}

	public static genaicommons.proxies.ToolCall load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return genaicommons.proxies.ToolCall.initialize(context, mendixObject);
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of ToolType
	 */
	public final java.lang.String getToolType()
	{
		return getToolType(getContext());
	}

	/**
	 * @param context
	 * @return value of ToolType
	 */
	public final java.lang.String getToolType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ToolType.toString());
	}

	/**
	 * Set value of ToolType
	 * @param tooltype
	 */
	public final void setToolType(java.lang.String tooltype)
	{
		setToolType(getContext(), tooltype);
	}

	/**
	 * Set value of ToolType
	 * @param context
	 * @param tooltype
	 */
	public final void setToolType(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String tooltype)
	{
		getMendixObject().setValue(context, MemberNames.ToolType.toString(), tooltype);
	}

	/**
	 * @return value of ToolCallId
	 */
	public final java.lang.String getToolCallId()
	{
		return getToolCallId(getContext());
	}

	/**
	 * @param context
	 * @return value of ToolCallId
	 */
	public final java.lang.String getToolCallId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ToolCallId.toString());
	}

	/**
	 * Set value of ToolCallId
	 * @param toolcallid
	 */
	public final void setToolCallId(java.lang.String toolcallid)
	{
		setToolCallId(getContext(), toolcallid);
	}

	/**
	 * Set value of ToolCallId
	 * @param context
	 * @param toolcallid
	 */
	public final void setToolCallId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String toolcallid)
	{
		getMendixObject().setValue(context, MemberNames.ToolCallId.toString(), toolcallid);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ToolCall_Argument
	 */
	public final java.util.List<genaicommons.proxies.Argument> getToolCall_Argument() throws com.mendix.core.CoreException
	{
		return getToolCall_Argument(getContext());
	}

	/**
	 * @param context
	 * @return value of ToolCall_Argument
	 * @throws com.mendix.core.CoreException
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<genaicommons.proxies.Argument> getToolCall_Argument(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<genaicommons.proxies.Argument> result = new java.util.ArrayList<>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.ToolCall_Argument.toString());
		if (valueObject == null) {
			return result;
		}
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject)) {
			result.add(genaicommons.proxies.Argument.initialize(context, mendixObject));
		}
		return result;
	}

	/**
	 * Set value of ToolCall_Argument
	 * @param toolcall_argument
	 */
	public final void setToolCall_Argument(java.util.List<genaicommons.proxies.Argument> toolcall_argument)
	{
		setToolCall_Argument(getContext(), toolcall_argument);
	}

	/**
	 * Set value of ToolCall_Argument
	 * @param context
	 * @param toolcall_argument
	 */
	public final void setToolCall_Argument(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<genaicommons.proxies.Argument> toolcall_argument)
	{
		var identifiers = toolcall_argument
			.stream()
			.map(proxyObject -> proxyObject.getMendixObject().getId())
			.collect(java.util.stream.Collectors.toList());
		
		getMendixObject().setValue(context, MemberNames.ToolCall_Argument.toString(), identifiers);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return toolCallMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final genaicommons.proxies.ToolCall that = (genaicommons.proxies.ToolCall) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
