// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package amazonbedrockconnector.proxies;

/**
 * Contains one part of the agent's reasoning process and results from calling API actions and querying knowledge bases. You can use the trace to understand how the agent arrived at the response it provided the customer.
 * 
 * See also:
 * 
 * API Reference:
 * https://docs.aws.amazon.com/bedrock/latest/APIReference/API_agent-runtime_Trace.html
 * 
 * Java SDK Documentation:
 * https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/bedrockagentruntime/model/Trace.html
 */
public class AbstractTrace implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject abstractTraceMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AmazonBedrockConnector.AbstractTrace";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		TraceId("TraceId"),
		TraceType("TraceType"),
		AbstractTrace_TracePart("AmazonBedrockConnector.AbstractTrace_TracePart");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public AbstractTrace(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected AbstractTrace(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject abstractTraceMendixObject)
	{
		if (abstractTraceMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!abstractTraceMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.abstractTraceMendixObject = abstractTraceMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static amazonbedrockconnector.proxies.AbstractTrace initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		if (mendixObject.isInstanceOf("AmazonBedrockConnector.FailureTrace")) {
			return amazonbedrockconnector.proxies.FailureTrace.initialize(context, mendixObject);
		}
		if (mendixObject.isInstanceOf("AmazonBedrockConnector.InvocationInput")) {
			return amazonbedrockconnector.proxies.InvocationInput.initialize(context, mendixObject);
		}
		if (mendixObject.isInstanceOf("AmazonBedrockConnector.ModelInvocationInput")) {
			return amazonbedrockconnector.proxies.ModelInvocationInput.initialize(context, mendixObject);
		}
		if (mendixObject.isInstanceOf("AmazonBedrockConnector.Observation")) {
			return amazonbedrockconnector.proxies.Observation.initialize(context, mendixObject);
		}
		if (mendixObject.isInstanceOf("AmazonBedrockConnector.PostProcessingModelInvocationOutput")) {
			return amazonbedrockconnector.proxies.PostProcessingModelInvocationOutput.initialize(context, mendixObject);
		}
		if (mendixObject.isInstanceOf("AmazonBedrockConnector.PreProcessingModelInvocationOutput")) {
			return amazonbedrockconnector.proxies.PreProcessingModelInvocationOutput.initialize(context, mendixObject);
		}
		if (mendixObject.isInstanceOf("AmazonBedrockConnector.Rationale")) {
			return amazonbedrockconnector.proxies.Rationale.initialize(context, mendixObject);
		}
		return new amazonbedrockconnector.proxies.AbstractTrace(context, mendixObject);
	}

	public static amazonbedrockconnector.proxies.AbstractTrace load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return amazonbedrockconnector.proxies.AbstractTrace.initialize(context, mendixObject);
	}

	/**
	 * @return value of TraceId
	 */
	public final java.lang.String getTraceId()
	{
		return getTraceId(getContext());
	}

	/**
	 * @param context
	 * @return value of TraceId
	 */
	public final java.lang.String getTraceId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.TraceId.toString());
	}

	/**
	 * Set value of TraceId
	 * @param traceid
	 */
	public final void setTraceId(java.lang.String traceid)
	{
		setTraceId(getContext(), traceid);
	}

	/**
	 * Set value of TraceId
	 * @param context
	 * @param traceid
	 */
	public final void setTraceId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String traceid)
	{
		getMendixObject().setValue(context, MemberNames.TraceId.toString(), traceid);
	}

	/**
	 * Get value of TraceType
	 * @param tracetype
	 */
	public final amazonbedrockconnector.proxies.ENUM_TraceType getTraceType()
	{
		return getTraceType(getContext());
	}

	/**
	 * @param context
	 * @return value of TraceType
	 */
	public final amazonbedrockconnector.proxies.ENUM_TraceType getTraceType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.TraceType.toString());
		if (obj == null) {
			return null;
		}
		return amazonbedrockconnector.proxies.ENUM_TraceType.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of TraceType
	 * @param tracetype
	 */
	public final void setTraceType(amazonbedrockconnector.proxies.ENUM_TraceType tracetype)
	{
		setTraceType(getContext(), tracetype);
	}

	/**
	 * Set value of TraceType
	 * @param context
	 * @param tracetype
	 */
	public final void setTraceType(com.mendix.systemwideinterfaces.core.IContext context, amazonbedrockconnector.proxies.ENUM_TraceType tracetype)
	{
		if (tracetype != null) {
			getMendixObject().setValue(context, MemberNames.TraceType.toString(), tracetype.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.TraceType.toString(), null);
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of AbstractTrace_TracePart
	 */
	public final amazonbedrockconnector.proxies.TracePart getAbstractTrace_TracePart() throws com.mendix.core.CoreException
	{
		return getAbstractTrace_TracePart(getContext());
	}

	/**
	 * @param context
	 * @return value of AbstractTrace_TracePart
	 * @throws com.mendix.core.CoreException
	 */
	public final amazonbedrockconnector.proxies.TracePart getAbstractTrace_TracePart(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		amazonbedrockconnector.proxies.TracePart result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.AbstractTrace_TracePart.toString());
		if (identifier != null) {
			result = amazonbedrockconnector.proxies.TracePart.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of AbstractTrace_TracePart
	 * @param abstracttrace_tracepart
	 */
	public final void setAbstractTrace_TracePart(amazonbedrockconnector.proxies.TracePart abstracttrace_tracepart)
	{
		setAbstractTrace_TracePart(getContext(), abstracttrace_tracepart);
	}

	/**
	 * Set value of AbstractTrace_TracePart
	 * @param context
	 * @param abstracttrace_tracepart
	 */
	public final void setAbstractTrace_TracePart(com.mendix.systemwideinterfaces.core.IContext context, amazonbedrockconnector.proxies.TracePart abstracttrace_tracepart)
	{
		if (abstracttrace_tracepart == null) {
			getMendixObject().setValue(context, MemberNames.AbstractTrace_TracePart.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.AbstractTrace_TracePart.toString(), abstracttrace_tracepart.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return abstractTraceMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final amazonbedrockconnector.proxies.AbstractTrace that = (amazonbedrockconnector.proxies.AbstractTrace) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
