// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package amazonbedrockconnector.proxies;

/**
 * Contains information pertaining to the action group or knowledge base that is being invoked.
 * 
 * See also:
 * 
 * API Reference:
 * https://docs.aws.amazon.com/bedrock/latest/APIReference/API_agent-runtime_ActionGroupInvocationInput.html
 * 
 * Java SDK Documentation:
 * https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/bedrockagentruntime/model/ActionGroupInvocationInput.html
 * 
 * 
 */
public class ActionGroupInvocationInput implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject actionGroupInvocationInputMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AmazonBedrockConnector.ActionGroupInvocationInput";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ActionGroupName("ActionGroupName"),
		ApiPath("ApiPath"),
		Verb("Verb"),
		ActionGroupInvocationInput_InvocationInput("AmazonBedrockConnector.ActionGroupInvocationInput_InvocationInput");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ActionGroupInvocationInput(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ActionGroupInvocationInput(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject actionGroupInvocationInputMendixObject)
	{
		if (actionGroupInvocationInputMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!actionGroupInvocationInputMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.actionGroupInvocationInputMendixObject = actionGroupInvocationInputMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static amazonbedrockconnector.proxies.ActionGroupInvocationInput initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new amazonbedrockconnector.proxies.ActionGroupInvocationInput(context, mendixObject);
	}

	public static amazonbedrockconnector.proxies.ActionGroupInvocationInput load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return amazonbedrockconnector.proxies.ActionGroupInvocationInput.initialize(context, mendixObject);
	}

	/**
	 * @return value of ActionGroupName
	 */
	public final java.lang.String getActionGroupName()
	{
		return getActionGroupName(getContext());
	}

	/**
	 * @param context
	 * @return value of ActionGroupName
	 */
	public final java.lang.String getActionGroupName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ActionGroupName.toString());
	}

	/**
	 * Set value of ActionGroupName
	 * @param actiongroupname
	 */
	public final void setActionGroupName(java.lang.String actiongroupname)
	{
		setActionGroupName(getContext(), actiongroupname);
	}

	/**
	 * Set value of ActionGroupName
	 * @param context
	 * @param actiongroupname
	 */
	public final void setActionGroupName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String actiongroupname)
	{
		getMendixObject().setValue(context, MemberNames.ActionGroupName.toString(), actiongroupname);
	}

	/**
	 * @return value of ApiPath
	 */
	public final java.lang.String getApiPath()
	{
		return getApiPath(getContext());
	}

	/**
	 * @param context
	 * @return value of ApiPath
	 */
	public final java.lang.String getApiPath(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ApiPath.toString());
	}

	/**
	 * Set value of ApiPath
	 * @param apipath
	 */
	public final void setApiPath(java.lang.String apipath)
	{
		setApiPath(getContext(), apipath);
	}

	/**
	 * Set value of ApiPath
	 * @param context
	 * @param apipath
	 */
	public final void setApiPath(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String apipath)
	{
		getMendixObject().setValue(context, MemberNames.ApiPath.toString(), apipath);
	}

	/**
	 * @return value of Verb
	 */
	public final java.lang.String getVerb()
	{
		return getVerb(getContext());
	}

	/**
	 * @param context
	 * @return value of Verb
	 */
	public final java.lang.String getVerb(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Verb.toString());
	}

	/**
	 * Set value of Verb
	 * @param verb
	 */
	public final void setVerb(java.lang.String verb)
	{
		setVerb(getContext(), verb);
	}

	/**
	 * Set value of Verb
	 * @param context
	 * @param verb
	 */
	public final void setVerb(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String verb)
	{
		getMendixObject().setValue(context, MemberNames.Verb.toString(), verb);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ActionGroupInvocationInput_InvocationInput
	 */
	public final amazonbedrockconnector.proxies.InvocationInput getActionGroupInvocationInput_InvocationInput() throws com.mendix.core.CoreException
	{
		return getActionGroupInvocationInput_InvocationInput(getContext());
	}

	/**
	 * @param context
	 * @return value of ActionGroupInvocationInput_InvocationInput
	 * @throws com.mendix.core.CoreException
	 */
	public final amazonbedrockconnector.proxies.InvocationInput getActionGroupInvocationInput_InvocationInput(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		amazonbedrockconnector.proxies.InvocationInput result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ActionGroupInvocationInput_InvocationInput.toString());
		if (identifier != null) {
			result = amazonbedrockconnector.proxies.InvocationInput.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ActionGroupInvocationInput_InvocationInput
	 * @param actiongroupinvocationinput_invocationinput
	 */
	public final void setActionGroupInvocationInput_InvocationInput(amazonbedrockconnector.proxies.InvocationInput actiongroupinvocationinput_invocationinput)
	{
		setActionGroupInvocationInput_InvocationInput(getContext(), actiongroupinvocationinput_invocationinput);
	}

	/**
	 * Set value of ActionGroupInvocationInput_InvocationInput
	 * @param context
	 * @param actiongroupinvocationinput_invocationinput
	 */
	public final void setActionGroupInvocationInput_InvocationInput(com.mendix.systemwideinterfaces.core.IContext context, amazonbedrockconnector.proxies.InvocationInput actiongroupinvocationinput_invocationinput)
	{
		if (actiongroupinvocationinput_invocationinput == null) {
			getMendixObject().setValue(context, MemberNames.ActionGroupInvocationInput_InvocationInput.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ActionGroupInvocationInput_InvocationInput.toString(), actiongroupinvocationinput_invocationinput.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return actionGroupInvocationInputMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final amazonbedrockconnector.proxies.ActionGroupInvocationInput that = (amazonbedrockconnector.proxies.ActionGroupInvocationInput) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
