// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package amazonbedrockconnector.proxies;

/**
 * This entity contains the reasons that the agent-related API that you invoked failed. A new object is created for each reason.
 */
public class AgentFailureReason implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject agentFailureReasonMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AmazonBedrockConnector.AgentFailureReason";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Text("Text"),
		AgentFailureReason_Agent("AmazonBedrockConnector.AgentFailureReason_Agent");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public AgentFailureReason(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected AgentFailureReason(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject agentFailureReasonMendixObject)
	{
		if (agentFailureReasonMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!agentFailureReasonMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.agentFailureReasonMendixObject = agentFailureReasonMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static amazonbedrockconnector.proxies.AgentFailureReason initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new amazonbedrockconnector.proxies.AgentFailureReason(context, mendixObject);
	}

	public static amazonbedrockconnector.proxies.AgentFailureReason load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return amazonbedrockconnector.proxies.AgentFailureReason.initialize(context, mendixObject);
	}

	/**
	 * @return value of Text
	 */
	public final java.lang.String getText()
	{
		return getText(getContext());
	}

	/**
	 * @param context
	 * @return value of Text
	 */
	public final java.lang.String getText(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Text.toString());
	}

	/**
	 * Set value of Text
	 * @param text
	 */
	public final void setText(java.lang.String text)
	{
		setText(getContext(), text);
	}

	/**
	 * Set value of Text
	 * @param context
	 * @param text
	 */
	public final void setText(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String text)
	{
		getMendixObject().setValue(context, MemberNames.Text.toString(), text);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of AgentFailureReason_Agent
	 */
	public final amazonbedrockconnector.proxies.Agent getAgentFailureReason_Agent() throws com.mendix.core.CoreException
	{
		return getAgentFailureReason_Agent(getContext());
	}

	/**
	 * @param context
	 * @return value of AgentFailureReason_Agent
	 * @throws com.mendix.core.CoreException
	 */
	public final amazonbedrockconnector.proxies.Agent getAgentFailureReason_Agent(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		amazonbedrockconnector.proxies.Agent result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.AgentFailureReason_Agent.toString());
		if (identifier != null) {
			result = amazonbedrockconnector.proxies.Agent.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of AgentFailureReason_Agent
	 * @param agentfailurereason_agent
	 */
	public final void setAgentFailureReason_Agent(amazonbedrockconnector.proxies.Agent agentfailurereason_agent)
	{
		setAgentFailureReason_Agent(getContext(), agentfailurereason_agent);
	}

	/**
	 * Set value of AgentFailureReason_Agent
	 * @param context
	 * @param agentfailurereason_agent
	 */
	public final void setAgentFailureReason_Agent(com.mendix.systemwideinterfaces.core.IContext context, amazonbedrockconnector.proxies.Agent agentfailurereason_agent)
	{
		if (agentfailurereason_agent == null) {
			getMendixObject().setValue(context, MemberNames.AgentFailureReason_Agent.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.AgentFailureReason_Agent.toString(), agentfailurereason_agent.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return agentFailureReasonMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final amazonbedrockconnector.proxies.AgentFailureReason that = (amazonbedrockconnector.proxies.AgentFailureReason) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
