// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package amazonbedrockconnector.proxies;

/**
 * This entity contains details about an agent.
 * 
 * API reference:
 * https://docs.aws.amazon.com/bedrock/latest/APIReference/API_agent_Agent.html
 * 
 * Java SDK documentation:
 * https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/bedrockagent/model/Agent.html
 */
public class Agent implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject agentMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AmazonBedrockConnector.Agent";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		AgentARN("AgentARN"),
		AgentID("AgentID"),
		AgentName("AgentName"),
		AgentResourceRoleARN("AgentResourceRoleARN"),
		AgentStatus("AgentStatus"),
		AgentVersion("AgentVersion"),
		CreatedAt("CreatedAt"),
		IdleSessionTTLInSeconds("IdleSessionTTLInSeconds"),
		UpdatedAt("UpdatedAt"),
		ClientToken("ClientToken"),
		CustomerEncryptionKeyArn("CustomerEncryptionKeyArn"),
		Description("Description"),
		FoundationModel("FoundationModel"),
		Instruction("Instruction"),
		PreparedAt("PreparedAt"),
		Agent_GetAgentResponse("AmazonBedrockConnector.Agent_GetAgentResponse");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Agent(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Agent(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject agentMendixObject)
	{
		if (agentMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!agentMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.agentMendixObject = agentMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static amazonbedrockconnector.proxies.Agent initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new amazonbedrockconnector.proxies.Agent(context, mendixObject);
	}

	public static amazonbedrockconnector.proxies.Agent load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return amazonbedrockconnector.proxies.Agent.initialize(context, mendixObject);
	}

	/**
	 * @return value of AgentARN
	 */
	public final java.lang.String getAgentARN()
	{
		return getAgentARN(getContext());
	}

	/**
	 * @param context
	 * @return value of AgentARN
	 */
	public final java.lang.String getAgentARN(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.AgentARN.toString());
	}

	/**
	 * Set value of AgentARN
	 * @param agentarn
	 */
	public final void setAgentARN(java.lang.String agentarn)
	{
		setAgentARN(getContext(), agentarn);
	}

	/**
	 * Set value of AgentARN
	 * @param context
	 * @param agentarn
	 */
	public final void setAgentARN(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String agentarn)
	{
		getMendixObject().setValue(context, MemberNames.AgentARN.toString(), agentarn);
	}

	/**
	 * @return value of AgentID
	 */
	public final java.lang.String getAgentID()
	{
		return getAgentID(getContext());
	}

	/**
	 * @param context
	 * @return value of AgentID
	 */
	public final java.lang.String getAgentID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.AgentID.toString());
	}

	/**
	 * Set value of AgentID
	 * @param agentid
	 */
	public final void setAgentID(java.lang.String agentid)
	{
		setAgentID(getContext(), agentid);
	}

	/**
	 * Set value of AgentID
	 * @param context
	 * @param agentid
	 */
	public final void setAgentID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String agentid)
	{
		getMendixObject().setValue(context, MemberNames.AgentID.toString(), agentid);
	}

	/**
	 * @return value of AgentName
	 */
	public final java.lang.String getAgentName()
	{
		return getAgentName(getContext());
	}

	/**
	 * @param context
	 * @return value of AgentName
	 */
	public final java.lang.String getAgentName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.AgentName.toString());
	}

	/**
	 * Set value of AgentName
	 * @param agentname
	 */
	public final void setAgentName(java.lang.String agentname)
	{
		setAgentName(getContext(), agentname);
	}

	/**
	 * Set value of AgentName
	 * @param context
	 * @param agentname
	 */
	public final void setAgentName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String agentname)
	{
		getMendixObject().setValue(context, MemberNames.AgentName.toString(), agentname);
	}

	/**
	 * @return value of AgentResourceRoleARN
	 */
	public final java.lang.String getAgentResourceRoleARN()
	{
		return getAgentResourceRoleARN(getContext());
	}

	/**
	 * @param context
	 * @return value of AgentResourceRoleARN
	 */
	public final java.lang.String getAgentResourceRoleARN(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.AgentResourceRoleARN.toString());
	}

	/**
	 * Set value of AgentResourceRoleARN
	 * @param agentresourcerolearn
	 */
	public final void setAgentResourceRoleARN(java.lang.String agentresourcerolearn)
	{
		setAgentResourceRoleARN(getContext(), agentresourcerolearn);
	}

	/**
	 * Set value of AgentResourceRoleARN
	 * @param context
	 * @param agentresourcerolearn
	 */
	public final void setAgentResourceRoleARN(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String agentresourcerolearn)
	{
		getMendixObject().setValue(context, MemberNames.AgentResourceRoleARN.toString(), agentresourcerolearn);
	}

	/**
	 * Get value of AgentStatus
	 * @param agentstatus
	 */
	public final amazonbedrockconnector.proxies.ENUM_AgentStatus getAgentStatus()
	{
		return getAgentStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of AgentStatus
	 */
	public final amazonbedrockconnector.proxies.ENUM_AgentStatus getAgentStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.AgentStatus.toString());
		if (obj == null) {
			return null;
		}
		return amazonbedrockconnector.proxies.ENUM_AgentStatus.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of AgentStatus
	 * @param agentstatus
	 */
	public final void setAgentStatus(amazonbedrockconnector.proxies.ENUM_AgentStatus agentstatus)
	{
		setAgentStatus(getContext(), agentstatus);
	}

	/**
	 * Set value of AgentStatus
	 * @param context
	 * @param agentstatus
	 */
	public final void setAgentStatus(com.mendix.systemwideinterfaces.core.IContext context, amazonbedrockconnector.proxies.ENUM_AgentStatus agentstatus)
	{
		if (agentstatus != null) {
			getMendixObject().setValue(context, MemberNames.AgentStatus.toString(), agentstatus.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.AgentStatus.toString(), null);
		}
	}

	/**
	 * @return value of AgentVersion
	 */
	public final java.lang.String getAgentVersion()
	{
		return getAgentVersion(getContext());
	}

	/**
	 * @param context
	 * @return value of AgentVersion
	 */
	public final java.lang.String getAgentVersion(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.AgentVersion.toString());
	}

	/**
	 * Set value of AgentVersion
	 * @param agentversion
	 */
	public final void setAgentVersion(java.lang.String agentversion)
	{
		setAgentVersion(getContext(), agentversion);
	}

	/**
	 * Set value of AgentVersion
	 * @param context
	 * @param agentversion
	 */
	public final void setAgentVersion(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String agentversion)
	{
		getMendixObject().setValue(context, MemberNames.AgentVersion.toString(), agentversion);
	}

	/**
	 * @return value of CreatedAt
	 */
	public final java.util.Date getCreatedAt()
	{
		return getCreatedAt(getContext());
	}

	/**
	 * @param context
	 * @return value of CreatedAt
	 */
	public final java.util.Date getCreatedAt(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.CreatedAt.toString());
	}

	/**
	 * Set value of CreatedAt
	 * @param createdat
	 */
	public final void setCreatedAt(java.util.Date createdat)
	{
		setCreatedAt(getContext(), createdat);
	}

	/**
	 * Set value of CreatedAt
	 * @param context
	 * @param createdat
	 */
	public final void setCreatedAt(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date createdat)
	{
		getMendixObject().setValue(context, MemberNames.CreatedAt.toString(), createdat);
	}

	/**
	 * @return value of IdleSessionTTLInSeconds
	 */
	public final java.lang.Integer getIdleSessionTTLInSeconds()
	{
		return getIdleSessionTTLInSeconds(getContext());
	}

	/**
	 * @param context
	 * @return value of IdleSessionTTLInSeconds
	 */
	public final java.lang.Integer getIdleSessionTTLInSeconds(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.IdleSessionTTLInSeconds.toString());
	}

	/**
	 * Set value of IdleSessionTTLInSeconds
	 * @param idlesessionttlinseconds
	 */
	public final void setIdleSessionTTLInSeconds(java.lang.Integer idlesessionttlinseconds)
	{
		setIdleSessionTTLInSeconds(getContext(), idlesessionttlinseconds);
	}

	/**
	 * Set value of IdleSessionTTLInSeconds
	 * @param context
	 * @param idlesessionttlinseconds
	 */
	public final void setIdleSessionTTLInSeconds(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer idlesessionttlinseconds)
	{
		getMendixObject().setValue(context, MemberNames.IdleSessionTTLInSeconds.toString(), idlesessionttlinseconds);
	}

	/**
	 * @return value of UpdatedAt
	 */
	public final java.util.Date getUpdatedAt()
	{
		return getUpdatedAt(getContext());
	}

	/**
	 * @param context
	 * @return value of UpdatedAt
	 */
	public final java.util.Date getUpdatedAt(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.UpdatedAt.toString());
	}

	/**
	 * Set value of UpdatedAt
	 * @param updatedat
	 */
	public final void setUpdatedAt(java.util.Date updatedat)
	{
		setUpdatedAt(getContext(), updatedat);
	}

	/**
	 * Set value of UpdatedAt
	 * @param context
	 * @param updatedat
	 */
	public final void setUpdatedAt(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date updatedat)
	{
		getMendixObject().setValue(context, MemberNames.UpdatedAt.toString(), updatedat);
	}

	/**
	 * @return value of ClientToken
	 */
	public final java.lang.String getClientToken()
	{
		return getClientToken(getContext());
	}

	/**
	 * @param context
	 * @return value of ClientToken
	 */
	public final java.lang.String getClientToken(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ClientToken.toString());
	}

	/**
	 * Set value of ClientToken
	 * @param clienttoken
	 */
	public final void setClientToken(java.lang.String clienttoken)
	{
		setClientToken(getContext(), clienttoken);
	}

	/**
	 * Set value of ClientToken
	 * @param context
	 * @param clienttoken
	 */
	public final void setClientToken(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String clienttoken)
	{
		getMendixObject().setValue(context, MemberNames.ClientToken.toString(), clienttoken);
	}

	/**
	 * @return value of CustomerEncryptionKeyArn
	 */
	public final java.lang.String getCustomerEncryptionKeyArn()
	{
		return getCustomerEncryptionKeyArn(getContext());
	}

	/**
	 * @param context
	 * @return value of CustomerEncryptionKeyArn
	 */
	public final java.lang.String getCustomerEncryptionKeyArn(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CustomerEncryptionKeyArn.toString());
	}

	/**
	 * Set value of CustomerEncryptionKeyArn
	 * @param customerencryptionkeyarn
	 */
	public final void setCustomerEncryptionKeyArn(java.lang.String customerencryptionkeyarn)
	{
		setCustomerEncryptionKeyArn(getContext(), customerencryptionkeyarn);
	}

	/**
	 * Set value of CustomerEncryptionKeyArn
	 * @param context
	 * @param customerencryptionkeyarn
	 */
	public final void setCustomerEncryptionKeyArn(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String customerencryptionkeyarn)
	{
		getMendixObject().setValue(context, MemberNames.CustomerEncryptionKeyArn.toString(), customerencryptionkeyarn);
	}

	/**
	 * @return value of Description
	 */
	public final java.lang.String getDescription()
	{
		return getDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of Description
	 */
	public final java.lang.String getDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Description.toString());
	}

	/**
	 * Set value of Description
	 * @param description
	 */
	public final void setDescription(java.lang.String description)
	{
		setDescription(getContext(), description);
	}

	/**
	 * Set value of Description
	 * @param context
	 * @param description
	 */
	public final void setDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String description)
	{
		getMendixObject().setValue(context, MemberNames.Description.toString(), description);
	}

	/**
	 * @return value of FoundationModel
	 */
	public final java.lang.String getFoundationModel()
	{
		return getFoundationModel(getContext());
	}

	/**
	 * @param context
	 * @return value of FoundationModel
	 */
	public final java.lang.String getFoundationModel(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.FoundationModel.toString());
	}

	/**
	 * Set value of FoundationModel
	 * @param foundationmodel
	 */
	public final void setFoundationModel(java.lang.String foundationmodel)
	{
		setFoundationModel(getContext(), foundationmodel);
	}

	/**
	 * Set value of FoundationModel
	 * @param context
	 * @param foundationmodel
	 */
	public final void setFoundationModel(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String foundationmodel)
	{
		getMendixObject().setValue(context, MemberNames.FoundationModel.toString(), foundationmodel);
	}

	/**
	 * @return value of Instruction
	 */
	public final java.lang.String getInstruction()
	{
		return getInstruction(getContext());
	}

	/**
	 * @param context
	 * @return value of Instruction
	 */
	public final java.lang.String getInstruction(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Instruction.toString());
	}

	/**
	 * Set value of Instruction
	 * @param instruction
	 */
	public final void setInstruction(java.lang.String instruction)
	{
		setInstruction(getContext(), instruction);
	}

	/**
	 * Set value of Instruction
	 * @param context
	 * @param instruction
	 */
	public final void setInstruction(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String instruction)
	{
		getMendixObject().setValue(context, MemberNames.Instruction.toString(), instruction);
	}

	/**
	 * @return value of PreparedAt
	 */
	public final java.util.Date getPreparedAt()
	{
		return getPreparedAt(getContext());
	}

	/**
	 * @param context
	 * @return value of PreparedAt
	 */
	public final java.util.Date getPreparedAt(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.PreparedAt.toString());
	}

	/**
	 * Set value of PreparedAt
	 * @param preparedat
	 */
	public final void setPreparedAt(java.util.Date preparedat)
	{
		setPreparedAt(getContext(), preparedat);
	}

	/**
	 * Set value of PreparedAt
	 * @param context
	 * @param preparedat
	 */
	public final void setPreparedAt(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date preparedat)
	{
		getMendixObject().setValue(context, MemberNames.PreparedAt.toString(), preparedat);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Agent_GetAgentResponse
	 */
	public final amazonbedrockconnector.proxies.GetAgentResponse getAgent_GetAgentResponse() throws com.mendix.core.CoreException
	{
		return getAgent_GetAgentResponse(getContext());
	}

	/**
	 * @param context
	 * @return value of Agent_GetAgentResponse
	 * @throws com.mendix.core.CoreException
	 */
	public final amazonbedrockconnector.proxies.GetAgentResponse getAgent_GetAgentResponse(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		amazonbedrockconnector.proxies.GetAgentResponse result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Agent_GetAgentResponse.toString());
		if (identifier != null) {
			result = amazonbedrockconnector.proxies.GetAgentResponse.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Agent_GetAgentResponse
	 * @param agent_getagentresponse
	 */
	public final void setAgent_GetAgentResponse(amazonbedrockconnector.proxies.GetAgentResponse agent_getagentresponse)
	{
		setAgent_GetAgentResponse(getContext(), agent_getagentresponse);
	}

	/**
	 * Set value of Agent_GetAgentResponse
	 * @param context
	 * @param agent_getagentresponse
	 */
	public final void setAgent_GetAgentResponse(com.mendix.systemwideinterfaces.core.IContext context, amazonbedrockconnector.proxies.GetAgentResponse agent_getagentresponse)
	{
		if (agent_getagentresponse == null) {
			getMendixObject().setValue(context, MemberNames.Agent_GetAgentResponse.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Agent_GetAgentResponse.toString(), agent_getagentresponse.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return agentMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final amazonbedrockconnector.proxies.Agent that = (amazonbedrockconnector.proxies.Agent) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
