// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package amazonbedrockconnector.proxies;

/**
 * This entity holds information about an Agent . 
 * 
 * This entity is used as part of the 'Sync Metadata' operations. 
 * A new AmazonBedrockAgent object will be created for each Agent found in your AWS Account when syncing data.
 * 
 * To sync Agents to the database, use the 'Sync Agents' operation in the toolbox.
 * 
 */
public class AmazonBedrockAgent implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject amazonBedrockAgentMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AmazonBedrockConnector.AmazonBedrockAgent";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		AgentID("AgentID"),
		AgentName("AgentName"),
		AgentStatus("AgentStatus"),
		Description("Description"),
		LatestAgentVersion("LatestAgentVersion"),
		UpdatedAt("UpdatedAt"),
		AmazonBedrockAgent_AmazonBedrockRegion("AmazonBedrockConnector.AmazonBedrockAgent_AmazonBedrockRegion");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public AmazonBedrockAgent(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected AmazonBedrockAgent(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject amazonBedrockAgentMendixObject)
	{
		if (amazonBedrockAgentMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!amazonBedrockAgentMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.amazonBedrockAgentMendixObject = amazonBedrockAgentMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static amazonbedrockconnector.proxies.AmazonBedrockAgent initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new amazonbedrockconnector.proxies.AmazonBedrockAgent(context, mendixObject);
	}

	public static amazonbedrockconnector.proxies.AmazonBedrockAgent load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return amazonbedrockconnector.proxies.AmazonBedrockAgent.initialize(context, mendixObject);
	}

	public static java.util.List<amazonbedrockconnector.proxies.AmazonBedrockAgent> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> amazonbedrockconnector.proxies.AmazonBedrockAgent.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of AgentID
	 */
	public final java.lang.String getAgentID()
	{
		return getAgentID(getContext());
	}

	/**
	 * @param context
	 * @return value of AgentID
	 */
	public final java.lang.String getAgentID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.AgentID.toString());
	}

	/**
	 * Set value of AgentID
	 * @param agentid
	 */
	public final void setAgentID(java.lang.String agentid)
	{
		setAgentID(getContext(), agentid);
	}

	/**
	 * Set value of AgentID
	 * @param context
	 * @param agentid
	 */
	public final void setAgentID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String agentid)
	{
		getMendixObject().setValue(context, MemberNames.AgentID.toString(), agentid);
	}

	/**
	 * @return value of AgentName
	 */
	public final java.lang.String getAgentName()
	{
		return getAgentName(getContext());
	}

	/**
	 * @param context
	 * @return value of AgentName
	 */
	public final java.lang.String getAgentName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.AgentName.toString());
	}

	/**
	 * Set value of AgentName
	 * @param agentname
	 */
	public final void setAgentName(java.lang.String agentname)
	{
		setAgentName(getContext(), agentname);
	}

	/**
	 * Set value of AgentName
	 * @param context
	 * @param agentname
	 */
	public final void setAgentName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String agentname)
	{
		getMendixObject().setValue(context, MemberNames.AgentName.toString(), agentname);
	}

	/**
	 * Get value of AgentStatus
	 * @param agentstatus
	 */
	public final amazonbedrockconnector.proxies.ENUM_AgentStatus getAgentStatus()
	{
		return getAgentStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of AgentStatus
	 */
	public final amazonbedrockconnector.proxies.ENUM_AgentStatus getAgentStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.AgentStatus.toString());
		if (obj == null) {
			return null;
		}
		return amazonbedrockconnector.proxies.ENUM_AgentStatus.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of AgentStatus
	 * @param agentstatus
	 */
	public final void setAgentStatus(amazonbedrockconnector.proxies.ENUM_AgentStatus agentstatus)
	{
		setAgentStatus(getContext(), agentstatus);
	}

	/**
	 * Set value of AgentStatus
	 * @param context
	 * @param agentstatus
	 */
	public final void setAgentStatus(com.mendix.systemwideinterfaces.core.IContext context, amazonbedrockconnector.proxies.ENUM_AgentStatus agentstatus)
	{
		if (agentstatus != null) {
			getMendixObject().setValue(context, MemberNames.AgentStatus.toString(), agentstatus.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.AgentStatus.toString(), null);
		}
	}

	/**
	 * @return value of Description
	 */
	public final java.lang.String getDescription()
	{
		return getDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of Description
	 */
	public final java.lang.String getDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Description.toString());
	}

	/**
	 * Set value of Description
	 * @param description
	 */
	public final void setDescription(java.lang.String description)
	{
		setDescription(getContext(), description);
	}

	/**
	 * Set value of Description
	 * @param context
	 * @param description
	 */
	public final void setDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String description)
	{
		getMendixObject().setValue(context, MemberNames.Description.toString(), description);
	}

	/**
	 * @return value of LatestAgentVersion
	 */
	public final java.lang.String getLatestAgentVersion()
	{
		return getLatestAgentVersion(getContext());
	}

	/**
	 * @param context
	 * @return value of LatestAgentVersion
	 */
	public final java.lang.String getLatestAgentVersion(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.LatestAgentVersion.toString());
	}

	/**
	 * Set value of LatestAgentVersion
	 * @param latestagentversion
	 */
	public final void setLatestAgentVersion(java.lang.String latestagentversion)
	{
		setLatestAgentVersion(getContext(), latestagentversion);
	}

	/**
	 * Set value of LatestAgentVersion
	 * @param context
	 * @param latestagentversion
	 */
	public final void setLatestAgentVersion(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String latestagentversion)
	{
		getMendixObject().setValue(context, MemberNames.LatestAgentVersion.toString(), latestagentversion);
	}

	/**
	 * @return value of UpdatedAt
	 */
	public final java.util.Date getUpdatedAt()
	{
		return getUpdatedAt(getContext());
	}

	/**
	 * @param context
	 * @return value of UpdatedAt
	 */
	public final java.util.Date getUpdatedAt(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.UpdatedAt.toString());
	}

	/**
	 * Set value of UpdatedAt
	 * @param updatedat
	 */
	public final void setUpdatedAt(java.util.Date updatedat)
	{
		setUpdatedAt(getContext(), updatedat);
	}

	/**
	 * Set value of UpdatedAt
	 * @param context
	 * @param updatedat
	 */
	public final void setUpdatedAt(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date updatedat)
	{
		getMendixObject().setValue(context, MemberNames.UpdatedAt.toString(), updatedat);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of AmazonBedrockAgent_AmazonBedrockRegion
	 */
	public final amazonbedrockconnector.proxies.AmazonBedrockRegion getAmazonBedrockAgent_AmazonBedrockRegion() throws com.mendix.core.CoreException
	{
		return getAmazonBedrockAgent_AmazonBedrockRegion(getContext());
	}

	/**
	 * @param context
	 * @return value of AmazonBedrockAgent_AmazonBedrockRegion
	 * @throws com.mendix.core.CoreException
	 */
	public final amazonbedrockconnector.proxies.AmazonBedrockRegion getAmazonBedrockAgent_AmazonBedrockRegion(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		amazonbedrockconnector.proxies.AmazonBedrockRegion result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.AmazonBedrockAgent_AmazonBedrockRegion.toString());
		if (identifier != null) {
			result = amazonbedrockconnector.proxies.AmazonBedrockRegion.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of AmazonBedrockAgent_AmazonBedrockRegion
	 * @param amazonbedrockagent_amazonbedrockregion
	 */
	public final void setAmazonBedrockAgent_AmazonBedrockRegion(amazonbedrockconnector.proxies.AmazonBedrockRegion amazonbedrockagent_amazonbedrockregion)
	{
		setAmazonBedrockAgent_AmazonBedrockRegion(getContext(), amazonbedrockagent_amazonbedrockregion);
	}

	/**
	 * Set value of AmazonBedrockAgent_AmazonBedrockRegion
	 * @param context
	 * @param amazonbedrockagent_amazonbedrockregion
	 */
	public final void setAmazonBedrockAgent_AmazonBedrockRegion(com.mendix.systemwideinterfaces.core.IContext context, amazonbedrockconnector.proxies.AmazonBedrockRegion amazonbedrockagent_amazonbedrockregion)
	{
		if (amazonbedrockagent_amazonbedrockregion == null) {
			getMendixObject().setValue(context, MemberNames.AmazonBedrockAgent_AmazonBedrockRegion.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.AmazonBedrockAgent_AmazonBedrockRegion.toString(), amazonbedrockagent_amazonbedrockregion.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return amazonBedrockAgentMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final amazonbedrockconnector.proxies.AmazonBedrockAgent that = (amazonbedrockconnector.proxies.AmazonBedrockAgent) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
