// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package amazonbedrockconnector.proxies;

public class ChatCompletionsResponse extends genaicommons.proxies.Response
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AmazonBedrockConnector.ChatCompletionsResponse";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		LatencyMs("LatencyMs"),
		_ID("_ID"),
		RequestTokens("RequestTokens"),
		ResponseTokens("ResponseTokens"),
		TotalTokens("TotalTokens"),
		DurationMilliseconds("DurationMilliseconds"),
		StopReason("StopReason"),
		ResponseText("ResponseText"),
		Response_Message("GenAICommons.Response_Message");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ChatCompletionsResponse(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ChatCompletionsResponse(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject chatCompletionsResponseMendixObject)
	{
		super(context, chatCompletionsResponseMendixObject);
		if (!chatCompletionsResponseMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static amazonbedrockconnector.proxies.ChatCompletionsResponse initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new amazonbedrockconnector.proxies.ChatCompletionsResponse(context, mendixObject);
	}

	public static amazonbedrockconnector.proxies.ChatCompletionsResponse load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return amazonbedrockconnector.proxies.ChatCompletionsResponse.initialize(context, mendixObject);
	}

	/**
	 * @return value of LatencyMs
	 */
	public final java.lang.Integer getLatencyMs()
	{
		return getLatencyMs(getContext());
	}

	/**
	 * @param context
	 * @return value of LatencyMs
	 */
	public final java.lang.Integer getLatencyMs(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.LatencyMs.toString());
	}

	/**
	 * Set value of LatencyMs
	 * @param latencyms
	 */
	public final void setLatencyMs(java.lang.Integer latencyms)
	{
		setLatencyMs(getContext(), latencyms);
	}

	/**
	 * Set value of LatencyMs
	 * @param context
	 * @param latencyms
	 */
	public final void setLatencyMs(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer latencyms)
	{
		getMendixObject().setValue(context, MemberNames.LatencyMs.toString(), latencyms);
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final amazonbedrockconnector.proxies.ChatCompletionsResponse that = (amazonbedrockconnector.proxies.ChatCompletionsResponse) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
