// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package amazonbedrockconnector.proxies;

/**
 * This entity extends the GenAICommons.Request entity and is used for the ChatCompletions operation.
 * This operation is based on the Converse API for Amazon Bedrock:
 * 
 * API reference:
 * https://docs.aws.amazon.com/bedrock/latest/APIReference/API_runtime_Converse.html
 * 
 * Java SDK documentation:
 * https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/bedrockruntime/BedrockRuntimeClient.html#converse(software.amazon.awssdk.services.bedrockruntime.model.ConverseRequest)
 */
public class ChatCompletionsRequest_Extension extends awsauthentication.proxies.AbstractRequest
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AmazonBedrockConnector.ChatCompletionsRequest_Extension";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ChatCompletionsRequest_Extension_AbstractRequestParameter("AmazonBedrockConnector.ChatCompletionsRequest_Extension_AbstractRequestParameter"),
		ChatCompletionsRequest_Extension_ResponseFieldRequest("AmazonBedrockConnector.ChatCompletionsRequest_Extension_ResponseFieldRequest"),
		ChatCompletionsRequest_Extension_Request("AmazonBedrockConnector.ChatCompletionsRequest_Extension_Request"),
		AbstractRequest_BasicClientConfig("AWSAuthentication.AbstractRequest_BasicClientConfig");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ChatCompletionsRequest_Extension(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ChatCompletionsRequest_Extension(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject chatCompletionsRequest_ExtensionMendixObject)
	{
		super(context, chatCompletionsRequest_ExtensionMendixObject);
		if (!chatCompletionsRequest_ExtensionMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static amazonbedrockconnector.proxies.ChatCompletionsRequest_Extension initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new amazonbedrockconnector.proxies.ChatCompletionsRequest_Extension(context, mendixObject);
	}

	public static amazonbedrockconnector.proxies.ChatCompletionsRequest_Extension load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return amazonbedrockconnector.proxies.ChatCompletionsRequest_Extension.initialize(context, mendixObject);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ChatCompletionsRequest_Extension_AbstractRequestParameter
	 */
	public final java.util.List<amazonbedrockconnector.proxies.AbstractRequestParameter> getChatCompletionsRequest_Extension_AbstractRequestParameter() throws com.mendix.core.CoreException
	{
		return getChatCompletionsRequest_Extension_AbstractRequestParameter(getContext());
	}

	/**
	 * @param context
	 * @return value of ChatCompletionsRequest_Extension_AbstractRequestParameter
	 * @throws com.mendix.core.CoreException
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<amazonbedrockconnector.proxies.AbstractRequestParameter> getChatCompletionsRequest_Extension_AbstractRequestParameter(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<amazonbedrockconnector.proxies.AbstractRequestParameter> result = new java.util.ArrayList<>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.ChatCompletionsRequest_Extension_AbstractRequestParameter.toString());
		if (valueObject == null) {
			return result;
		}
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject)) {
			result.add(amazonbedrockconnector.proxies.AbstractRequestParameter.initialize(context, mendixObject));
		}
		return result;
	}

	/**
	 * Set value of ChatCompletionsRequest_Extension_AbstractRequestParameter
	 * @param chatcompletionsrequest_extension_abstractrequestparameter
	 */
	public final void setChatCompletionsRequest_Extension_AbstractRequestParameter(java.util.List<amazonbedrockconnector.proxies.AbstractRequestParameter> chatcompletionsrequest_extension_abstractrequestparameter)
	{
		setChatCompletionsRequest_Extension_AbstractRequestParameter(getContext(), chatcompletionsrequest_extension_abstractrequestparameter);
	}

	/**
	 * Set value of ChatCompletionsRequest_Extension_AbstractRequestParameter
	 * @param context
	 * @param chatcompletionsrequest_extension_abstractrequestparameter
	 */
	public final void setChatCompletionsRequest_Extension_AbstractRequestParameter(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<amazonbedrockconnector.proxies.AbstractRequestParameter> chatcompletionsrequest_extension_abstractrequestparameter)
	{
		var identifiers = chatcompletionsrequest_extension_abstractrequestparameter
			.stream()
			.map(proxyObject -> proxyObject.getMendixObject().getId())
			.collect(java.util.stream.Collectors.toList());
		
		getMendixObject().setValue(context, MemberNames.ChatCompletionsRequest_Extension_AbstractRequestParameter.toString(), identifiers);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ChatCompletionsRequest_Extension_ResponseFieldRequest
	 */
	public final java.util.List<amazonbedrockconnector.proxies.ResponseFieldRequest> getChatCompletionsRequest_Extension_ResponseFieldRequest() throws com.mendix.core.CoreException
	{
		return getChatCompletionsRequest_Extension_ResponseFieldRequest(getContext());
	}

	/**
	 * @param context
	 * @return value of ChatCompletionsRequest_Extension_ResponseFieldRequest
	 * @throws com.mendix.core.CoreException
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<amazonbedrockconnector.proxies.ResponseFieldRequest> getChatCompletionsRequest_Extension_ResponseFieldRequest(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<amazonbedrockconnector.proxies.ResponseFieldRequest> result = new java.util.ArrayList<>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.ChatCompletionsRequest_Extension_ResponseFieldRequest.toString());
		if (valueObject == null) {
			return result;
		}
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject)) {
			result.add(amazonbedrockconnector.proxies.ResponseFieldRequest.initialize(context, mendixObject));
		}
		return result;
	}

	/**
	 * Set value of ChatCompletionsRequest_Extension_ResponseFieldRequest
	 * @param chatcompletionsrequest_extension_responsefieldrequest
	 */
	public final void setChatCompletionsRequest_Extension_ResponseFieldRequest(java.util.List<amazonbedrockconnector.proxies.ResponseFieldRequest> chatcompletionsrequest_extension_responsefieldrequest)
	{
		setChatCompletionsRequest_Extension_ResponseFieldRequest(getContext(), chatcompletionsrequest_extension_responsefieldrequest);
	}

	/**
	 * Set value of ChatCompletionsRequest_Extension_ResponseFieldRequest
	 * @param context
	 * @param chatcompletionsrequest_extension_responsefieldrequest
	 */
	public final void setChatCompletionsRequest_Extension_ResponseFieldRequest(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<amazonbedrockconnector.proxies.ResponseFieldRequest> chatcompletionsrequest_extension_responsefieldrequest)
	{
		var identifiers = chatcompletionsrequest_extension_responsefieldrequest
			.stream()
			.map(proxyObject -> proxyObject.getMendixObject().getId())
			.collect(java.util.stream.Collectors.toList());
		
		getMendixObject().setValue(context, MemberNames.ChatCompletionsRequest_Extension_ResponseFieldRequest.toString(), identifiers);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ChatCompletionsRequest_Extension_Request
	 */
	public final genaicommons.proxies.Request getChatCompletionsRequest_Extension_Request() throws com.mendix.core.CoreException
	{
		return getChatCompletionsRequest_Extension_Request(getContext());
	}

	/**
	 * @param context
	 * @return value of ChatCompletionsRequest_Extension_Request
	 * @throws com.mendix.core.CoreException
	 */
	public final genaicommons.proxies.Request getChatCompletionsRequest_Extension_Request(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		genaicommons.proxies.Request result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ChatCompletionsRequest_Extension_Request.toString());
		if (identifier != null) {
			result = genaicommons.proxies.Request.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ChatCompletionsRequest_Extension_Request
	 * @param chatcompletionsrequest_extension_request
	 */
	public final void setChatCompletionsRequest_Extension_Request(genaicommons.proxies.Request chatcompletionsrequest_extension_request)
	{
		setChatCompletionsRequest_Extension_Request(getContext(), chatcompletionsrequest_extension_request);
	}

	/**
	 * Set value of ChatCompletionsRequest_Extension_Request
	 * @param context
	 * @param chatcompletionsrequest_extension_request
	 */
	public final void setChatCompletionsRequest_Extension_Request(com.mendix.systemwideinterfaces.core.IContext context, genaicommons.proxies.Request chatcompletionsrequest_extension_request)
	{
		if (chatcompletionsrequest_extension_request == null) {
			getMendixObject().setValue(context, MemberNames.ChatCompletionsRequest_Extension_Request.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ChatCompletionsRequest_Extension_Request.toString(), chatcompletionsrequest_extension_request.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final amazonbedrockconnector.proxies.ChatCompletionsRequest_Extension that = (amazonbedrockconnector.proxies.ChatCompletionsRequest_Extension) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
