// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package amazonbedrockconnector.proxies;

/**
 * The CitationRetrievedResponse entity holds information about the citation, which contains a segment of the generated response that is based on a source in the knowledge base, alongside information about the source.
 * 
 * See also:
 * 
 * API Reference:
 * https://docs.aws.amazon.com/bedrock/latest/APIReference/API_agent-runtime_Citation.html
 * 
 * Java SDK Documentation:
 * https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/bedrockagentruntime/model/Citation.html
 */
public class CitationRetrievedReference extends amazonbedrockconnector.proxies.RetrievedReference
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AmazonBedrockConnector.CitationRetrievedReference";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Text("Text"),
		CitationRetrievedReference_Citation("AmazonBedrockConnector.CitationRetrievedReference_Citation"),
		ReferenceLocation_RetrievedReference("AmazonBedrockConnector.ReferenceLocation_RetrievedReference");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public CitationRetrievedReference(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected CitationRetrievedReference(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject citationRetrievedReferenceMendixObject)
	{
		super(context, citationRetrievedReferenceMendixObject);
		if (!citationRetrievedReferenceMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static amazonbedrockconnector.proxies.CitationRetrievedReference initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new amazonbedrockconnector.proxies.CitationRetrievedReference(context, mendixObject);
	}

	public static amazonbedrockconnector.proxies.CitationRetrievedReference load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return amazonbedrockconnector.proxies.CitationRetrievedReference.initialize(context, mendixObject);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of CitationRetrievedReference_Citation
	 */
	public final amazonbedrockconnector.proxies.Citation getCitationRetrievedReference_Citation() throws com.mendix.core.CoreException
	{
		return getCitationRetrievedReference_Citation(getContext());
	}

	/**
	 * @param context
	 * @return value of CitationRetrievedReference_Citation
	 * @throws com.mendix.core.CoreException
	 */
	public final amazonbedrockconnector.proxies.Citation getCitationRetrievedReference_Citation(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		amazonbedrockconnector.proxies.Citation result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.CitationRetrievedReference_Citation.toString());
		if (identifier != null) {
			result = amazonbedrockconnector.proxies.Citation.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of CitationRetrievedReference_Citation
	 * @param citationretrievedreference_citation
	 */
	public final void setCitationRetrievedReference_Citation(amazonbedrockconnector.proxies.Citation citationretrievedreference_citation)
	{
		setCitationRetrievedReference_Citation(getContext(), citationretrievedreference_citation);
	}

	/**
	 * Set value of CitationRetrievedReference_Citation
	 * @param context
	 * @param citationretrievedreference_citation
	 */
	public final void setCitationRetrievedReference_Citation(com.mendix.systemwideinterfaces.core.IContext context, amazonbedrockconnector.proxies.Citation citationretrievedreference_citation)
	{
		if (citationretrievedreference_citation == null) {
			getMendixObject().setValue(context, MemberNames.CitationRetrievedReference_Citation.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.CitationRetrievedReference_Citation.toString(), citationretrievedreference_citation.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final amazonbedrockconnector.proxies.CitationRetrievedReference that = (amazonbedrockconnector.proxies.CitationRetrievedReference) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
