// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package amazonbedrockconnector.proxies;

/**
 * The Citation entitiy contains a segment of the generated response that is based on a source in the knowledge base, alongside information about the source.
 * 
 * See also:
 * 
 * API Reference:
 * https://docs.aws.amazon.com/bedrock/latest/APIReference/API_agent-runtime_Citation.html
 * 
 * Java SDK Documentation:
 * https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/bedrockagentruntime/model/Citation.html
 */
public class Citation implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject citationMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AmazonBedrockConnector.Citation";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		GeneratedResponsePart_Citation("AmazonBedrockConnector.GeneratedResponsePart_Citation");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Citation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Citation(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject citationMendixObject)
	{
		if (citationMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!citationMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.citationMendixObject = citationMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static amazonbedrockconnector.proxies.Citation initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		if (mendixObject.isInstanceOf("AmazonBedrockConnector.InvokeAgentCitation")) {
			return amazonbedrockconnector.proxies.InvokeAgentCitation.initialize(context, mendixObject);
		}
		return new amazonbedrockconnector.proxies.Citation(context, mendixObject);
	}

	public static amazonbedrockconnector.proxies.Citation load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return amazonbedrockconnector.proxies.Citation.initialize(context, mendixObject);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of GeneratedResponsePart_Citation
	 */
	public final amazonbedrockconnector.proxies.GeneratedResponsePart getGeneratedResponsePart_Citation() throws com.mendix.core.CoreException
	{
		return getGeneratedResponsePart_Citation(getContext());
	}

	/**
	 * @param context
	 * @return value of GeneratedResponsePart_Citation
	 * @throws com.mendix.core.CoreException
	 */
	public final amazonbedrockconnector.proxies.GeneratedResponsePart getGeneratedResponsePart_Citation(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		amazonbedrockconnector.proxies.GeneratedResponsePart result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.GeneratedResponsePart_Citation.toString());
		if (identifier != null) {
			result = amazonbedrockconnector.proxies.GeneratedResponsePart.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of GeneratedResponsePart_Citation
	 * @param generatedresponsepart_citation
	 */
	public final void setGeneratedResponsePart_Citation(amazonbedrockconnector.proxies.GeneratedResponsePart generatedresponsepart_citation)
	{
		setGeneratedResponsePart_Citation(getContext(), generatedresponsepart_citation);
	}

	/**
	 * Set value of GeneratedResponsePart_Citation
	 * @param context
	 * @param generatedresponsepart_citation
	 */
	public final void setGeneratedResponsePart_Citation(com.mendix.systemwideinterfaces.core.IContext context, amazonbedrockconnector.proxies.GeneratedResponsePart generatedresponsepart_citation)
	{
		if (generatedresponsepart_citation == null) {
			getMendixObject().setValue(context, MemberNames.GeneratedResponsePart_Citation.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.GeneratedResponsePart_Citation.toString(), generatedresponsepart_citation.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return citationMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final amazonbedrockconnector.proxies.Citation that = (amazonbedrockconnector.proxies.Citation) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
