// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package amazonbedrockconnector.proxies;

public class CohereEmbedMappingHelper implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject cohereEmbedMappingHelperMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AmazonBedrockConnector.CohereEmbedMappingHelper";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		InputType("InputType"),
		Truncate("Truncate"),
		EmbeddingTypes("EmbeddingTypes"),
		CohereEmbedMappingHelper_CohereEmbedMappingHelper("AmazonBedrockConnector.CohereEmbedMappingHelper_CohereEmbedMappingHelper"),
		CohereEmbedMappingHelper_ChunkCollection("AmazonBedrockConnector.CohereEmbedMappingHelper_ChunkCollection");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public CohereEmbedMappingHelper(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected CohereEmbedMappingHelper(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject cohereEmbedMappingHelperMendixObject)
	{
		if (cohereEmbedMappingHelperMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!cohereEmbedMappingHelperMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.cohereEmbedMappingHelperMendixObject = cohereEmbedMappingHelperMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static amazonbedrockconnector.proxies.CohereEmbedMappingHelper initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new amazonbedrockconnector.proxies.CohereEmbedMappingHelper(context, mendixObject);
	}

	public static amazonbedrockconnector.proxies.CohereEmbedMappingHelper load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return amazonbedrockconnector.proxies.CohereEmbedMappingHelper.initialize(context, mendixObject);
	}

	/**
	 * Get value of InputType
	 * @param inputtype
	 */
	public final amazonbedrockconnector.proxies.ENUM_InputType_CohereEmbed getInputType()
	{
		return getInputType(getContext());
	}

	/**
	 * @param context
	 * @return value of InputType
	 */
	public final amazonbedrockconnector.proxies.ENUM_InputType_CohereEmbed getInputType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.InputType.toString());
		if (obj == null) {
			return null;
		}
		return amazonbedrockconnector.proxies.ENUM_InputType_CohereEmbed.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of InputType
	 * @param inputtype
	 */
	public final void setInputType(amazonbedrockconnector.proxies.ENUM_InputType_CohereEmbed inputtype)
	{
		setInputType(getContext(), inputtype);
	}

	/**
	 * Set value of InputType
	 * @param context
	 * @param inputtype
	 */
	public final void setInputType(com.mendix.systemwideinterfaces.core.IContext context, amazonbedrockconnector.proxies.ENUM_InputType_CohereEmbed inputtype)
	{
		if (inputtype != null) {
			getMendixObject().setValue(context, MemberNames.InputType.toString(), inputtype.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.InputType.toString(), null);
		}
	}

	/**
	 * Get value of Truncate
	 * @param truncate
	 */
	public final amazonbedrockconnector.proxies.ENUM_Truncate_CohereEmbed getTruncate()
	{
		return getTruncate(getContext());
	}

	/**
	 * @param context
	 * @return value of Truncate
	 */
	public final amazonbedrockconnector.proxies.ENUM_Truncate_CohereEmbed getTruncate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Truncate.toString());
		if (obj == null) {
			return null;
		}
		return amazonbedrockconnector.proxies.ENUM_Truncate_CohereEmbed.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Truncate
	 * @param truncate
	 */
	public final void setTruncate(amazonbedrockconnector.proxies.ENUM_Truncate_CohereEmbed truncate)
	{
		setTruncate(getContext(), truncate);
	}

	/**
	 * Set value of Truncate
	 * @param context
	 * @param truncate
	 */
	public final void setTruncate(com.mendix.systemwideinterfaces.core.IContext context, amazonbedrockconnector.proxies.ENUM_Truncate_CohereEmbed truncate)
	{
		if (truncate != null) {
			getMendixObject().setValue(context, MemberNames.Truncate.toString(), truncate.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.Truncate.toString(), null);
		}
	}

	/**
	 * Get value of EmbeddingTypes
	 * @param embeddingtypes
	 */
	public final amazonbedrockconnector.proxies.ENUM_EmbeddingTypes_CohereEmbed getEmbeddingTypes()
	{
		return getEmbeddingTypes(getContext());
	}

	/**
	 * @param context
	 * @return value of EmbeddingTypes
	 */
	public final amazonbedrockconnector.proxies.ENUM_EmbeddingTypes_CohereEmbed getEmbeddingTypes(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.EmbeddingTypes.toString());
		if (obj == null) {
			return null;
		}
		return amazonbedrockconnector.proxies.ENUM_EmbeddingTypes_CohereEmbed.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of EmbeddingTypes
	 * @param embeddingtypes
	 */
	public final void setEmbeddingTypes(amazonbedrockconnector.proxies.ENUM_EmbeddingTypes_CohereEmbed embeddingtypes)
	{
		setEmbeddingTypes(getContext(), embeddingtypes);
	}

	/**
	 * Set value of EmbeddingTypes
	 * @param context
	 * @param embeddingtypes
	 */
	public final void setEmbeddingTypes(com.mendix.systemwideinterfaces.core.IContext context, amazonbedrockconnector.proxies.ENUM_EmbeddingTypes_CohereEmbed embeddingtypes)
	{
		if (embeddingtypes != null) {
			getMendixObject().setValue(context, MemberNames.EmbeddingTypes.toString(), embeddingtypes.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.EmbeddingTypes.toString(), null);
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of CohereEmbedMappingHelper_CohereEmbedMappingHelper
	 */
	public final amazonbedrockconnector.proxies.CohereEmbedMappingHelper getCohereEmbedMappingHelper_CohereEmbedMappingHelper() throws com.mendix.core.CoreException
	{
		return getCohereEmbedMappingHelper_CohereEmbedMappingHelper(getContext());
	}

	/**
	 * @param context
	 * @return value of CohereEmbedMappingHelper_CohereEmbedMappingHelper
	 * @throws com.mendix.core.CoreException
	 */
	public final amazonbedrockconnector.proxies.CohereEmbedMappingHelper getCohereEmbedMappingHelper_CohereEmbedMappingHelper(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		amazonbedrockconnector.proxies.CohereEmbedMappingHelper result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.CohereEmbedMappingHelper_CohereEmbedMappingHelper.toString());
		if (identifier != null) {
			result = amazonbedrockconnector.proxies.CohereEmbedMappingHelper.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of CohereEmbedMappingHelper_CohereEmbedMappingHelper
	 * @param cohereembedmappinghelper_cohereembedmappinghelper
	 */
	public final void setCohereEmbedMappingHelper_CohereEmbedMappingHelper(amazonbedrockconnector.proxies.CohereEmbedMappingHelper cohereembedmappinghelper_cohereembedmappinghelper)
	{
		setCohereEmbedMappingHelper_CohereEmbedMappingHelper(getContext(), cohereembedmappinghelper_cohereembedmappinghelper);
	}

	/**
	 * Set value of CohereEmbedMappingHelper_CohereEmbedMappingHelper
	 * @param context
	 * @param cohereembedmappinghelper_cohereembedmappinghelper
	 */
	public final void setCohereEmbedMappingHelper_CohereEmbedMappingHelper(com.mendix.systemwideinterfaces.core.IContext context, amazonbedrockconnector.proxies.CohereEmbedMappingHelper cohereembedmappinghelper_cohereembedmappinghelper)
	{
		if (cohereembedmappinghelper_cohereembedmappinghelper == null) {
			getMendixObject().setValue(context, MemberNames.CohereEmbedMappingHelper_CohereEmbedMappingHelper.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.CohereEmbedMappingHelper_CohereEmbedMappingHelper.toString(), cohereembedmappinghelper_cohereembedmappinghelper.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of CohereEmbedMappingHelper_ChunkCollection
	 */
	public final genaicommons.proxies.ChunkCollection getCohereEmbedMappingHelper_ChunkCollection() throws com.mendix.core.CoreException
	{
		return getCohereEmbedMappingHelper_ChunkCollection(getContext());
	}

	/**
	 * @param context
	 * @return value of CohereEmbedMappingHelper_ChunkCollection
	 * @throws com.mendix.core.CoreException
	 */
	public final genaicommons.proxies.ChunkCollection getCohereEmbedMappingHelper_ChunkCollection(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		genaicommons.proxies.ChunkCollection result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.CohereEmbedMappingHelper_ChunkCollection.toString());
		if (identifier != null) {
			result = genaicommons.proxies.ChunkCollection.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of CohereEmbedMappingHelper_ChunkCollection
	 * @param cohereembedmappinghelper_chunkcollection
	 */
	public final void setCohereEmbedMappingHelper_ChunkCollection(genaicommons.proxies.ChunkCollection cohereembedmappinghelper_chunkcollection)
	{
		setCohereEmbedMappingHelper_ChunkCollection(getContext(), cohereembedmappinghelper_chunkcollection);
	}

	/**
	 * Set value of CohereEmbedMappingHelper_ChunkCollection
	 * @param context
	 * @param cohereembedmappinghelper_chunkcollection
	 */
	public final void setCohereEmbedMappingHelper_ChunkCollection(com.mendix.systemwideinterfaces.core.IContext context, genaicommons.proxies.ChunkCollection cohereembedmappinghelper_chunkcollection)
	{
		if (cohereembedmappinghelper_chunkcollection == null) {
			getMendixObject().setValue(context, MemberNames.CohereEmbedMappingHelper_ChunkCollection.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.CohereEmbedMappingHelper_ChunkCollection.toString(), cohereembedmappinghelper_chunkcollection.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return cohereEmbedMappingHelperMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final amazonbedrockconnector.proxies.CohereEmbedMappingHelper that = (amazonbedrockconnector.proxies.CohereEmbedMappingHelper) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
