// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package amazonbedrockconnector.proxies;

/**
 * Extends the EmbeddingsResponse object with attributes specific to Cohere Embed.
 */
public class CohereEmbedResponse extends genaicommons.proxies.EmbeddingsResponse
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AmazonBedrockConnector.CohereEmbedResponse";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ResponseType("ResponseType"),
		_id("_id"),
		PromptTokens("PromptTokens"),
		TotalTokens("TotalTokens"),
		DurationMilliseconds("DurationMilliseconds"),
		EmbeddingsResponse_ChunkCollection("GenAICommons.EmbeddingsResponse_ChunkCollection");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public CohereEmbedResponse(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected CohereEmbedResponse(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject cohereEmbedResponseMendixObject)
	{
		super(context, cohereEmbedResponseMendixObject);
		if (!cohereEmbedResponseMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static amazonbedrockconnector.proxies.CohereEmbedResponse initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new amazonbedrockconnector.proxies.CohereEmbedResponse(context, mendixObject);
	}

	public static amazonbedrockconnector.proxies.CohereEmbedResponse load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return amazonbedrockconnector.proxies.CohereEmbedResponse.initialize(context, mendixObject);
	}

	/**
	 * @return value of ResponseType
	 */
	public final java.lang.String getResponseType()
	{
		return getResponseType(getContext());
	}

	/**
	 * @param context
	 * @return value of ResponseType
	 */
	public final java.lang.String getResponseType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ResponseType.toString());
	}

	/**
	 * Set value of ResponseType
	 * @param responsetype
	 */
	public final void setResponseType(java.lang.String responsetype)
	{
		setResponseType(getContext(), responsetype);
	}

	/**
	 * Set value of ResponseType
	 * @param context
	 * @param responsetype
	 */
	public final void setResponseType(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String responsetype)
	{
		getMendixObject().setValue(context, MemberNames.ResponseType.toString(), responsetype);
	}

	/**
	 * @return value of _id
	 */
	public final java.lang.String get_id()
	{
		return get_id(getContext());
	}

	/**
	 * @param context
	 * @return value of _id
	 */
	public final java.lang.String get_id(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames._id.toString());
	}

	/**
	 * Set value of _id
	 * @param _id
	 */
	public final void set_id(java.lang.String _id)
	{
		set_id(getContext(), _id);
	}

	/**
	 * Set value of _id
	 * @param context
	 * @param _id
	 */
	public final void set_id(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String _id)
	{
		getMendixObject().setValue(context, MemberNames._id.toString(), _id);
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final amazonbedrockconnector.proxies.CohereEmbedResponse that = (amazonbedrockconnector.proxies.CohereEmbedResponse) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
