// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package amazonbedrockconnector.proxies;

public class ComputerUseTool extends amazonbedrockconnector.proxies.AbstractRequestParameter
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AmazonBedrockConnector.ComputerUseTool";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Key("Key"),
		ComputerUseTool_AbstractRequestParameter("AmazonBedrockConnector.ComputerUseTool_AbstractRequestParameter");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ComputerUseTool(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ComputerUseTool(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject computerUseToolMendixObject)
	{
		super(context, computerUseToolMendixObject);
		if (!computerUseToolMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static amazonbedrockconnector.proxies.ComputerUseTool initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new amazonbedrockconnector.proxies.ComputerUseTool(context, mendixObject);
	}

	public static amazonbedrockconnector.proxies.ComputerUseTool load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return amazonbedrockconnector.proxies.ComputerUseTool.initialize(context, mendixObject);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ComputerUseTool_AbstractRequestParameter
	 */
	public final java.util.List<amazonbedrockconnector.proxies.AbstractRequestParameter> getComputerUseTool_AbstractRequestParameter() throws com.mendix.core.CoreException
	{
		return getComputerUseTool_AbstractRequestParameter(getContext());
	}

	/**
	 * @param context
	 * @return value of ComputerUseTool_AbstractRequestParameter
	 * @throws com.mendix.core.CoreException
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<amazonbedrockconnector.proxies.AbstractRequestParameter> getComputerUseTool_AbstractRequestParameter(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<amazonbedrockconnector.proxies.AbstractRequestParameter> result = new java.util.ArrayList<>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.ComputerUseTool_AbstractRequestParameter.toString());
		if (valueObject == null) {
			return result;
		}
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject)) {
			result.add(amazonbedrockconnector.proxies.AbstractRequestParameter.initialize(context, mendixObject));
		}
		return result;
	}

	/**
	 * Set value of ComputerUseTool_AbstractRequestParameter
	 * @param computerusetool_abstractrequestparameter
	 */
	public final void setComputerUseTool_AbstractRequestParameter(java.util.List<amazonbedrockconnector.proxies.AbstractRequestParameter> computerusetool_abstractrequestparameter)
	{
		setComputerUseTool_AbstractRequestParameter(getContext(), computerusetool_abstractrequestparameter);
	}

	/**
	 * Set value of ComputerUseTool_AbstractRequestParameter
	 * @param context
	 * @param computerusetool_abstractrequestparameter
	 */
	public final void setComputerUseTool_AbstractRequestParameter(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<amazonbedrockconnector.proxies.AbstractRequestParameter> computerusetool_abstractrequestparameter)
	{
		var identifiers = computerusetool_abstractrequestparameter
			.stream()
			.map(proxyObject -> proxyObject.getMendixObject().getId())
			.collect(java.util.stream.Collectors.toList());
		
		getMendixObject().setValue(context, MemberNames.ComputerUseTool_AbstractRequestParameter.toString(), identifiers);
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final amazonbedrockconnector.proxies.ComputerUseTool that = (amazonbedrockconnector.proxies.ComputerUseTool) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
