// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package amazonbedrockconnector.proxies;

/**
 * The endpoint information to connect to your Confluence data source.
 * 
 * API reference:
 * https://docs.aws.amazon.com/bedrock/latest/APIReference/API_agent_ConfluenceSourceConfiguration.html
 * 
 * Java SDK documentation:
 * https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/bedrockagent/model/ConfluenceSourceConfiguration.html
 */
public class ConfluenceSourceConfiguration implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject confluenceSourceConfigurationMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AmazonBedrockConnector.ConfluenceSourceConfiguration";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		AuthType("AuthType"),
		CredentialsSecretARN("CredentialsSecretARN"),
		HostType("HostType"),
		HostURL("HostURL"),
		ConfluenceSourceConfiguration_ConfluenceDataSourceConfiguration("AmazonBedrockConnector.ConfluenceSourceConfiguration_ConfluenceDataSourceConfiguration");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ConfluenceSourceConfiguration(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ConfluenceSourceConfiguration(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject confluenceSourceConfigurationMendixObject)
	{
		if (confluenceSourceConfigurationMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!confluenceSourceConfigurationMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.confluenceSourceConfigurationMendixObject = confluenceSourceConfigurationMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static amazonbedrockconnector.proxies.ConfluenceSourceConfiguration initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new amazonbedrockconnector.proxies.ConfluenceSourceConfiguration(context, mendixObject);
	}

	public static amazonbedrockconnector.proxies.ConfluenceSourceConfiguration load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return amazonbedrockconnector.proxies.ConfluenceSourceConfiguration.initialize(context, mendixObject);
	}

	/**
	 * Get value of AuthType
	 * @param authtype
	 */
	public final amazonbedrockconnector.proxies.ENUM_ConfluenceAuthType getAuthType()
	{
		return getAuthType(getContext());
	}

	/**
	 * @param context
	 * @return value of AuthType
	 */
	public final amazonbedrockconnector.proxies.ENUM_ConfluenceAuthType getAuthType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.AuthType.toString());
		if (obj == null) {
			return null;
		}
		return amazonbedrockconnector.proxies.ENUM_ConfluenceAuthType.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of AuthType
	 * @param authtype
	 */
	public final void setAuthType(amazonbedrockconnector.proxies.ENUM_ConfluenceAuthType authtype)
	{
		setAuthType(getContext(), authtype);
	}

	/**
	 * Set value of AuthType
	 * @param context
	 * @param authtype
	 */
	public final void setAuthType(com.mendix.systemwideinterfaces.core.IContext context, amazonbedrockconnector.proxies.ENUM_ConfluenceAuthType authtype)
	{
		if (authtype != null) {
			getMendixObject().setValue(context, MemberNames.AuthType.toString(), authtype.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.AuthType.toString(), null);
		}
	}

	/**
	 * @return value of CredentialsSecretARN
	 */
	public final java.lang.String getCredentialsSecretARN()
	{
		return getCredentialsSecretARN(getContext());
	}

	/**
	 * @param context
	 * @return value of CredentialsSecretARN
	 */
	public final java.lang.String getCredentialsSecretARN(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CredentialsSecretARN.toString());
	}

	/**
	 * Set value of CredentialsSecretARN
	 * @param credentialssecretarn
	 */
	public final void setCredentialsSecretARN(java.lang.String credentialssecretarn)
	{
		setCredentialsSecretARN(getContext(), credentialssecretarn);
	}

	/**
	 * Set value of CredentialsSecretARN
	 * @param context
	 * @param credentialssecretarn
	 */
	public final void setCredentialsSecretARN(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String credentialssecretarn)
	{
		getMendixObject().setValue(context, MemberNames.CredentialsSecretARN.toString(), credentialssecretarn);
	}

	/**
	 * Get value of HostType
	 * @param hosttype
	 */
	public final amazonbedrockconnector.proxies.ENUM_ConfluenceHostType getHostType()
	{
		return getHostType(getContext());
	}

	/**
	 * @param context
	 * @return value of HostType
	 */
	public final amazonbedrockconnector.proxies.ENUM_ConfluenceHostType getHostType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.HostType.toString());
		if (obj == null) {
			return null;
		}
		return amazonbedrockconnector.proxies.ENUM_ConfluenceHostType.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of HostType
	 * @param hosttype
	 */
	public final void setHostType(amazonbedrockconnector.proxies.ENUM_ConfluenceHostType hosttype)
	{
		setHostType(getContext(), hosttype);
	}

	/**
	 * Set value of HostType
	 * @param context
	 * @param hosttype
	 */
	public final void setHostType(com.mendix.systemwideinterfaces.core.IContext context, amazonbedrockconnector.proxies.ENUM_ConfluenceHostType hosttype)
	{
		if (hosttype != null) {
			getMendixObject().setValue(context, MemberNames.HostType.toString(), hosttype.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.HostType.toString(), null);
		}
	}

	/**
	 * @return value of HostURL
	 */
	public final java.lang.String getHostURL()
	{
		return getHostURL(getContext());
	}

	/**
	 * @param context
	 * @return value of HostURL
	 */
	public final java.lang.String getHostURL(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.HostURL.toString());
	}

	/**
	 * Set value of HostURL
	 * @param hosturl
	 */
	public final void setHostURL(java.lang.String hosturl)
	{
		setHostURL(getContext(), hosturl);
	}

	/**
	 * Set value of HostURL
	 * @param context
	 * @param hosturl
	 */
	public final void setHostURL(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String hosturl)
	{
		getMendixObject().setValue(context, MemberNames.HostURL.toString(), hosturl);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ConfluenceSourceConfiguration_ConfluenceDataSourceConfiguration
	 */
	public final amazonbedrockconnector.proxies.ConfluenceDataSourceConfiguration getConfluenceSourceConfiguration_ConfluenceDataSourceConfiguration() throws com.mendix.core.CoreException
	{
		return getConfluenceSourceConfiguration_ConfluenceDataSourceConfiguration(getContext());
	}

	/**
	 * @param context
	 * @return value of ConfluenceSourceConfiguration_ConfluenceDataSourceConfiguration
	 * @throws com.mendix.core.CoreException
	 */
	public final amazonbedrockconnector.proxies.ConfluenceDataSourceConfiguration getConfluenceSourceConfiguration_ConfluenceDataSourceConfiguration(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		amazonbedrockconnector.proxies.ConfluenceDataSourceConfiguration result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ConfluenceSourceConfiguration_ConfluenceDataSourceConfiguration.toString());
		if (identifier != null) {
			result = amazonbedrockconnector.proxies.ConfluenceDataSourceConfiguration.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ConfluenceSourceConfiguration_ConfluenceDataSourceConfiguration
	 * @param confluencesourceconfiguration_confluencedatasourceconfiguration
	 */
	public final void setConfluenceSourceConfiguration_ConfluenceDataSourceConfiguration(amazonbedrockconnector.proxies.ConfluenceDataSourceConfiguration confluencesourceconfiguration_confluencedatasourceconfiguration)
	{
		setConfluenceSourceConfiguration_ConfluenceDataSourceConfiguration(getContext(), confluencesourceconfiguration_confluencedatasourceconfiguration);
	}

	/**
	 * Set value of ConfluenceSourceConfiguration_ConfluenceDataSourceConfiguration
	 * @param context
	 * @param confluencesourceconfiguration_confluencedatasourceconfiguration
	 */
	public final void setConfluenceSourceConfiguration_ConfluenceDataSourceConfiguration(com.mendix.systemwideinterfaces.core.IContext context, amazonbedrockconnector.proxies.ConfluenceDataSourceConfiguration confluencesourceconfiguration_confluencedatasourceconfiguration)
	{
		if (confluencesourceconfiguration_confluencedatasourceconfiguration == null) {
			getMendixObject().setValue(context, MemberNames.ConfluenceSourceConfiguration_ConfluenceDataSourceConfiguration.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ConfluenceSourceConfiguration_ConfluenceDataSourceConfiguration.toString(), confluencesourceconfiguration_confluencedatasourceconfiguration.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return confluenceSourceConfigurationMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final amazonbedrockconnector.proxies.ConfluenceSourceConfiguration that = (amazonbedrockconnector.proxies.ConfluenceSourceConfiguration) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
