// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package amazonbedrockconnector.proxies;

/**
 * The configuration information to connect to Confluence as your data source.
 * 
 * API reference:
 * https://docs.aws.amazon.com/bedrock/latest/APIReference/API_agent_ConfluenceDataSourceConfiguration.html
 * 
 * Java SDK documentation:
 * https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/bedrockagent/model/ConfluenceDataSourceConfiguration.html
 */
public class ConfluenceDataSourceConfiguration implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject confluenceDataSourceConfigurationMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AmazonBedrockConnector.ConfluenceDataSourceConfiguration";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ConfluenceDataSourceConfiguration_DataSourceConfiguration("AmazonBedrockConnector.ConfluenceDataSourceConfiguration_DataSourceConfiguration"),
		ConfluenceSourceConfiguration_ConfluenceDataSourceConfiguration("AmazonBedrockConnector.ConfluenceSourceConfiguration_ConfluenceDataSourceConfiguration");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ConfluenceDataSourceConfiguration(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ConfluenceDataSourceConfiguration(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject confluenceDataSourceConfigurationMendixObject)
	{
		if (confluenceDataSourceConfigurationMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!confluenceDataSourceConfigurationMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.confluenceDataSourceConfigurationMendixObject = confluenceDataSourceConfigurationMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static amazonbedrockconnector.proxies.ConfluenceDataSourceConfiguration initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new amazonbedrockconnector.proxies.ConfluenceDataSourceConfiguration(context, mendixObject);
	}

	public static amazonbedrockconnector.proxies.ConfluenceDataSourceConfiguration load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return amazonbedrockconnector.proxies.ConfluenceDataSourceConfiguration.initialize(context, mendixObject);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ConfluenceDataSourceConfiguration_DataSourceConfiguration
	 */
	public final amazonbedrockconnector.proxies.DataSourceConfiguration getConfluenceDataSourceConfiguration_DataSourceConfiguration() throws com.mendix.core.CoreException
	{
		return getConfluenceDataSourceConfiguration_DataSourceConfiguration(getContext());
	}

	/**
	 * @param context
	 * @return value of ConfluenceDataSourceConfiguration_DataSourceConfiguration
	 * @throws com.mendix.core.CoreException
	 */
	public final amazonbedrockconnector.proxies.DataSourceConfiguration getConfluenceDataSourceConfiguration_DataSourceConfiguration(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		amazonbedrockconnector.proxies.DataSourceConfiguration result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ConfluenceDataSourceConfiguration_DataSourceConfiguration.toString());
		if (identifier != null) {
			result = amazonbedrockconnector.proxies.DataSourceConfiguration.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ConfluenceDataSourceConfiguration_DataSourceConfiguration
	 * @param confluencedatasourceconfiguration_datasourceconfiguration
	 */
	public final void setConfluenceDataSourceConfiguration_DataSourceConfiguration(amazonbedrockconnector.proxies.DataSourceConfiguration confluencedatasourceconfiguration_datasourceconfiguration)
	{
		setConfluenceDataSourceConfiguration_DataSourceConfiguration(getContext(), confluencedatasourceconfiguration_datasourceconfiguration);
	}

	/**
	 * Set value of ConfluenceDataSourceConfiguration_DataSourceConfiguration
	 * @param context
	 * @param confluencedatasourceconfiguration_datasourceconfiguration
	 */
	public final void setConfluenceDataSourceConfiguration_DataSourceConfiguration(com.mendix.systemwideinterfaces.core.IContext context, amazonbedrockconnector.proxies.DataSourceConfiguration confluencedatasourceconfiguration_datasourceconfiguration)
	{
		if (confluencedatasourceconfiguration_datasourceconfiguration == null) {
			getMendixObject().setValue(context, MemberNames.ConfluenceDataSourceConfiguration_DataSourceConfiguration.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ConfluenceDataSourceConfiguration_DataSourceConfiguration.toString(), confluencedatasourceconfiguration_datasourceconfiguration.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ConfluenceSourceConfiguration_ConfluenceDataSourceConfiguration
	 */
	public final amazonbedrockconnector.proxies.ConfluenceSourceConfiguration getConfluenceSourceConfiguration_ConfluenceDataSourceConfiguration() throws com.mendix.core.CoreException
	{
		return getConfluenceSourceConfiguration_ConfluenceDataSourceConfiguration(getContext());
	}

	/**
	 * @param context
	 * @return value of ConfluenceSourceConfiguration_ConfluenceDataSourceConfiguration
	 * @throws com.mendix.core.CoreException
	 */
	public final amazonbedrockconnector.proxies.ConfluenceSourceConfiguration getConfluenceSourceConfiguration_ConfluenceDataSourceConfiguration(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		amazonbedrockconnector.proxies.ConfluenceSourceConfiguration result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ConfluenceSourceConfiguration_ConfluenceDataSourceConfiguration.toString());
		if (identifier != null) {
			result = amazonbedrockconnector.proxies.ConfluenceSourceConfiguration.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ConfluenceSourceConfiguration_ConfluenceDataSourceConfiguration
	 * @param confluencesourceconfiguration_confluencedatasourceconfiguration
	 */
	public final void setConfluenceSourceConfiguration_ConfluenceDataSourceConfiguration(amazonbedrockconnector.proxies.ConfluenceSourceConfiguration confluencesourceconfiguration_confluencedatasourceconfiguration)
	{
		setConfluenceSourceConfiguration_ConfluenceDataSourceConfiguration(getContext(), confluencesourceconfiguration_confluencedatasourceconfiguration);
	}

	/**
	 * Set value of ConfluenceSourceConfiguration_ConfluenceDataSourceConfiguration
	 * @param context
	 * @param confluencesourceconfiguration_confluencedatasourceconfiguration
	 */
	public final void setConfluenceSourceConfiguration_ConfluenceDataSourceConfiguration(com.mendix.systemwideinterfaces.core.IContext context, amazonbedrockconnector.proxies.ConfluenceSourceConfiguration confluencesourceconfiguration_confluencedatasourceconfiguration)
	{
		if (confluencesourceconfiguration_confluencedatasourceconfiguration == null) {
			getMendixObject().setValue(context, MemberNames.ConfluenceSourceConfiguration_ConfluenceDataSourceConfiguration.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ConfluenceSourceConfiguration_ConfluenceDataSourceConfiguration.toString(), confluencesourceconfiguration_confluencedatasourceconfiguration.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return confluenceDataSourceConfigurationMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final amazonbedrockconnector.proxies.ConfluenceDataSourceConfiguration that = (amazonbedrockconnector.proxies.ConfluenceDataSourceConfiguration) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
