// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package amazonbedrockconnector.proxies;

/**
 * This entity is the request for the Amazon Bedrock CreateDataSource action.
 * 
 * Currently it is supported for data source types S3 and Confluence.
 * 
 * API reference:
 * https://docs.aws.amazon.com/bedrock/latest/APIReference/API_agent_CreateDataSource.html
 * 
 * Java SDK documentation:
 * https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/bedrockagent/model/CreateDataSourceRequest.html
 */
public class CreateDataSourceRequest extends awsauthentication.proxies.AbstractRequest
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AmazonBedrockConnector.CreateDataSourceRequest";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		KnowledgeBaseId("KnowledgeBaseId"),
		Name("Name"),
		Description("Description"),
		CreateDataSourceConfiguration_CreateDataSourceRequest("AmazonBedrockConnector.CreateDataSourceConfiguration_CreateDataSourceRequest"),
		AbstractRequest_BasicClientConfig("AWSAuthentication.AbstractRequest_BasicClientConfig");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public CreateDataSourceRequest(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected CreateDataSourceRequest(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject createDataSourceRequestMendixObject)
	{
		super(context, createDataSourceRequestMendixObject);
		if (!createDataSourceRequestMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static amazonbedrockconnector.proxies.CreateDataSourceRequest initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new amazonbedrockconnector.proxies.CreateDataSourceRequest(context, mendixObject);
	}

	public static amazonbedrockconnector.proxies.CreateDataSourceRequest load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return amazonbedrockconnector.proxies.CreateDataSourceRequest.initialize(context, mendixObject);
	}

	/**
	 * @return value of KnowledgeBaseId
	 */
	public final java.lang.String getKnowledgeBaseId()
	{
		return getKnowledgeBaseId(getContext());
	}

	/**
	 * @param context
	 * @return value of KnowledgeBaseId
	 */
	public final java.lang.String getKnowledgeBaseId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.KnowledgeBaseId.toString());
	}

	/**
	 * Set value of KnowledgeBaseId
	 * @param knowledgebaseid
	 */
	public final void setKnowledgeBaseId(java.lang.String knowledgebaseid)
	{
		setKnowledgeBaseId(getContext(), knowledgebaseid);
	}

	/**
	 * Set value of KnowledgeBaseId
	 * @param context
	 * @param knowledgebaseid
	 */
	public final void setKnowledgeBaseId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String knowledgebaseid)
	{
		getMendixObject().setValue(context, MemberNames.KnowledgeBaseId.toString(), knowledgebaseid);
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of Description
	 */
	public final java.lang.String getDescription()
	{
		return getDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of Description
	 */
	public final java.lang.String getDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Description.toString());
	}

	/**
	 * Set value of Description
	 * @param description
	 */
	public final void setDescription(java.lang.String description)
	{
		setDescription(getContext(), description);
	}

	/**
	 * Set value of Description
	 * @param context
	 * @param description
	 */
	public final void setDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String description)
	{
		getMendixObject().setValue(context, MemberNames.Description.toString(), description);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of CreateDataSourceConfiguration_CreateDataSourceRequest
	 */
	public final amazonbedrockconnector.proxies.CreateDataSourceConfiguration getCreateDataSourceConfiguration_CreateDataSourceRequest() throws com.mendix.core.CoreException
	{
		return getCreateDataSourceConfiguration_CreateDataSourceRequest(getContext());
	}

	/**
	 * @param context
	 * @return value of CreateDataSourceConfiguration_CreateDataSourceRequest
	 * @throws com.mendix.core.CoreException
	 */
	public final amazonbedrockconnector.proxies.CreateDataSourceConfiguration getCreateDataSourceConfiguration_CreateDataSourceRequest(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		amazonbedrockconnector.proxies.CreateDataSourceConfiguration result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.CreateDataSourceConfiguration_CreateDataSourceRequest.toString());
		if (identifier != null) {
			result = amazonbedrockconnector.proxies.CreateDataSourceConfiguration.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of CreateDataSourceConfiguration_CreateDataSourceRequest
	 * @param createdatasourceconfiguration_createdatasourcerequest
	 */
	public final void setCreateDataSourceConfiguration_CreateDataSourceRequest(amazonbedrockconnector.proxies.CreateDataSourceConfiguration createdatasourceconfiguration_createdatasourcerequest)
	{
		setCreateDataSourceConfiguration_CreateDataSourceRequest(getContext(), createdatasourceconfiguration_createdatasourcerequest);
	}

	/**
	 * Set value of CreateDataSourceConfiguration_CreateDataSourceRequest
	 * @param context
	 * @param createdatasourceconfiguration_createdatasourcerequest
	 */
	public final void setCreateDataSourceConfiguration_CreateDataSourceRequest(com.mendix.systemwideinterfaces.core.IContext context, amazonbedrockconnector.proxies.CreateDataSourceConfiguration createdatasourceconfiguration_createdatasourcerequest)
	{
		if (createdatasourceconfiguration_createdatasourcerequest == null) {
			getMendixObject().setValue(context, MemberNames.CreateDataSourceConfiguration_CreateDataSourceRequest.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.CreateDataSourceConfiguration_CreateDataSourceRequest.toString(), createdatasourceconfiguration_createdatasourcerequest.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final amazonbedrockconnector.proxies.CreateDataSourceRequest that = (amazonbedrockconnector.proxies.CreateDataSourceRequest) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
