// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package amazonbedrockconnector.proxies;

public class CreateDataSourceConfiguration extends amazonbedrockconnector.proxies.DataSourceConfiguration
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AmazonBedrockConnector.CreateDataSourceConfiguration";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		DataSourceType("DataSourceType"),
		CreateDataSourceConfiguration_CreateDataSourceRequest("AmazonBedrockConnector.CreateDataSourceConfiguration_CreateDataSourceRequest"),
		ConfluenceDataSourceConfiguration_DataSourceConfiguration("AmazonBedrockConnector.ConfluenceDataSourceConfiguration_DataSourceConfiguration"),
		S3DataSourceConfiguration_DataSourceConfiguration("AmazonBedrockConnector.S3DataSourceConfiguration_DataSourceConfiguration"),
		SharePointDataSourceConfiguration_DataSourceConfiguration("AmazonBedrockConnector.SharePointDataSourceConfiguration_DataSourceConfiguration"),
		DataSourceConfiguration_DataSource("AmazonBedrockConnector.DataSourceConfiguration_DataSource");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public CreateDataSourceConfiguration(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected CreateDataSourceConfiguration(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject createDataSourceConfigurationMendixObject)
	{
		super(context, createDataSourceConfigurationMendixObject);
		if (!createDataSourceConfigurationMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static amazonbedrockconnector.proxies.CreateDataSourceConfiguration initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new amazonbedrockconnector.proxies.CreateDataSourceConfiguration(context, mendixObject);
	}

	public static amazonbedrockconnector.proxies.CreateDataSourceConfiguration load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return amazonbedrockconnector.proxies.CreateDataSourceConfiguration.initialize(context, mendixObject);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of CreateDataSourceConfiguration_CreateDataSourceRequest
	 */
	public final amazonbedrockconnector.proxies.CreateDataSourceRequest getCreateDataSourceConfiguration_CreateDataSourceRequest() throws com.mendix.core.CoreException
	{
		return getCreateDataSourceConfiguration_CreateDataSourceRequest(getContext());
	}

	/**
	 * @param context
	 * @return value of CreateDataSourceConfiguration_CreateDataSourceRequest
	 * @throws com.mendix.core.CoreException
	 */
	public final amazonbedrockconnector.proxies.CreateDataSourceRequest getCreateDataSourceConfiguration_CreateDataSourceRequest(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		amazonbedrockconnector.proxies.CreateDataSourceRequest result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.CreateDataSourceConfiguration_CreateDataSourceRequest.toString());
		if (identifier != null) {
			result = amazonbedrockconnector.proxies.CreateDataSourceRequest.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of CreateDataSourceConfiguration_CreateDataSourceRequest
	 * @param createdatasourceconfiguration_createdatasourcerequest
	 */
	public final void setCreateDataSourceConfiguration_CreateDataSourceRequest(amazonbedrockconnector.proxies.CreateDataSourceRequest createdatasourceconfiguration_createdatasourcerequest)
	{
		setCreateDataSourceConfiguration_CreateDataSourceRequest(getContext(), createdatasourceconfiguration_createdatasourcerequest);
	}

	/**
	 * Set value of CreateDataSourceConfiguration_CreateDataSourceRequest
	 * @param context
	 * @param createdatasourceconfiguration_createdatasourcerequest
	 */
	public final void setCreateDataSourceConfiguration_CreateDataSourceRequest(com.mendix.systemwideinterfaces.core.IContext context, amazonbedrockconnector.proxies.CreateDataSourceRequest createdatasourceconfiguration_createdatasourcerequest)
	{
		if (createdatasourceconfiguration_createdatasourcerequest == null) {
			getMendixObject().setValue(context, MemberNames.CreateDataSourceConfiguration_CreateDataSourceRequest.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.CreateDataSourceConfiguration_CreateDataSourceRequest.toString(), createdatasourceconfiguration_createdatasourcerequest.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final amazonbedrockconnector.proxies.CreateDataSourceConfiguration that = (amazonbedrockconnector.proxies.CreateDataSourceConfiguration) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
