// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package amazonbedrockconnector.proxies;

/**
 * The connection configuration for the data source.
 * 
 * API reference:
 * https://docs.aws.amazon.com/bedrock/latest/APIReference/API_agent_DataSourceConfiguration.html
 * 
 * Java SDK documentation:
 * https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/bedrockagent/model/DataSourceConfiguration.html
 */
public class DataSourceConfiguration implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject dataSourceConfigurationMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AmazonBedrockConnector.DataSourceConfiguration";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		DataSourceType("DataSourceType"),
		ConfluenceDataSourceConfiguration_DataSourceConfiguration("AmazonBedrockConnector.ConfluenceDataSourceConfiguration_DataSourceConfiguration"),
		S3DataSourceConfiguration_DataSourceConfiguration("AmazonBedrockConnector.S3DataSourceConfiguration_DataSourceConfiguration"),
		SharePointDataSourceConfiguration_DataSourceConfiguration("AmazonBedrockConnector.SharePointDataSourceConfiguration_DataSourceConfiguration"),
		DataSourceConfiguration_DataSource("AmazonBedrockConnector.DataSourceConfiguration_DataSource");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public DataSourceConfiguration(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected DataSourceConfiguration(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject dataSourceConfigurationMendixObject)
	{
		if (dataSourceConfigurationMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!dataSourceConfigurationMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.dataSourceConfigurationMendixObject = dataSourceConfigurationMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static amazonbedrockconnector.proxies.DataSourceConfiguration initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		if (mendixObject.isInstanceOf("AmazonBedrockConnector.CreateDataSourceConfiguration")) {
			return amazonbedrockconnector.proxies.CreateDataSourceConfiguration.initialize(context, mendixObject);
		}
		return new amazonbedrockconnector.proxies.DataSourceConfiguration(context, mendixObject);
	}

	public static amazonbedrockconnector.proxies.DataSourceConfiguration load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return amazonbedrockconnector.proxies.DataSourceConfiguration.initialize(context, mendixObject);
	}

	/**
	 * Get value of DataSourceType
	 * @param datasourcetype
	 */
	public final amazonbedrockconnector.proxies.ENUM_DataSourceType getDataSourceType()
	{
		return getDataSourceType(getContext());
	}

	/**
	 * @param context
	 * @return value of DataSourceType
	 */
	public final amazonbedrockconnector.proxies.ENUM_DataSourceType getDataSourceType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.DataSourceType.toString());
		if (obj == null) {
			return null;
		}
		return amazonbedrockconnector.proxies.ENUM_DataSourceType.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of DataSourceType
	 * @param datasourcetype
	 */
	public final void setDataSourceType(amazonbedrockconnector.proxies.ENUM_DataSourceType datasourcetype)
	{
		setDataSourceType(getContext(), datasourcetype);
	}

	/**
	 * Set value of DataSourceType
	 * @param context
	 * @param datasourcetype
	 */
	public final void setDataSourceType(com.mendix.systemwideinterfaces.core.IContext context, amazonbedrockconnector.proxies.ENUM_DataSourceType datasourcetype)
	{
		if (datasourcetype != null) {
			getMendixObject().setValue(context, MemberNames.DataSourceType.toString(), datasourcetype.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.DataSourceType.toString(), null);
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ConfluenceDataSourceConfiguration_DataSourceConfiguration
	 */
	public final amazonbedrockconnector.proxies.ConfluenceDataSourceConfiguration getConfluenceDataSourceConfiguration_DataSourceConfiguration() throws com.mendix.core.CoreException
	{
		return getConfluenceDataSourceConfiguration_DataSourceConfiguration(getContext());
	}

	/**
	 * @param context
	 * @return value of ConfluenceDataSourceConfiguration_DataSourceConfiguration
	 * @throws com.mendix.core.CoreException
	 */
	public final amazonbedrockconnector.proxies.ConfluenceDataSourceConfiguration getConfluenceDataSourceConfiguration_DataSourceConfiguration(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		amazonbedrockconnector.proxies.ConfluenceDataSourceConfiguration result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ConfluenceDataSourceConfiguration_DataSourceConfiguration.toString());
		if (identifier != null) {
			result = amazonbedrockconnector.proxies.ConfluenceDataSourceConfiguration.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ConfluenceDataSourceConfiguration_DataSourceConfiguration
	 * @param confluencedatasourceconfiguration_datasourceconfiguration
	 */
	public final void setConfluenceDataSourceConfiguration_DataSourceConfiguration(amazonbedrockconnector.proxies.ConfluenceDataSourceConfiguration confluencedatasourceconfiguration_datasourceconfiguration)
	{
		setConfluenceDataSourceConfiguration_DataSourceConfiguration(getContext(), confluencedatasourceconfiguration_datasourceconfiguration);
	}

	/**
	 * Set value of ConfluenceDataSourceConfiguration_DataSourceConfiguration
	 * @param context
	 * @param confluencedatasourceconfiguration_datasourceconfiguration
	 */
	public final void setConfluenceDataSourceConfiguration_DataSourceConfiguration(com.mendix.systemwideinterfaces.core.IContext context, amazonbedrockconnector.proxies.ConfluenceDataSourceConfiguration confluencedatasourceconfiguration_datasourceconfiguration)
	{
		if (confluencedatasourceconfiguration_datasourceconfiguration == null) {
			getMendixObject().setValue(context, MemberNames.ConfluenceDataSourceConfiguration_DataSourceConfiguration.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ConfluenceDataSourceConfiguration_DataSourceConfiguration.toString(), confluencedatasourceconfiguration_datasourceconfiguration.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of S3DataSourceConfiguration_DataSourceConfiguration
	 */
	public final amazonbedrockconnector.proxies.S3DataSourceConfiguration getS3DataSourceConfiguration_DataSourceConfiguration() throws com.mendix.core.CoreException
	{
		return getS3DataSourceConfiguration_DataSourceConfiguration(getContext());
	}

	/**
	 * @param context
	 * @return value of S3DataSourceConfiguration_DataSourceConfiguration
	 * @throws com.mendix.core.CoreException
	 */
	public final amazonbedrockconnector.proxies.S3DataSourceConfiguration getS3DataSourceConfiguration_DataSourceConfiguration(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		amazonbedrockconnector.proxies.S3DataSourceConfiguration result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.S3DataSourceConfiguration_DataSourceConfiguration.toString());
		if (identifier != null) {
			result = amazonbedrockconnector.proxies.S3DataSourceConfiguration.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of S3DataSourceConfiguration_DataSourceConfiguration
	 * @param s3datasourceconfiguration_datasourceconfiguration
	 */
	public final void setS3DataSourceConfiguration_DataSourceConfiguration(amazonbedrockconnector.proxies.S3DataSourceConfiguration s3datasourceconfiguration_datasourceconfiguration)
	{
		setS3DataSourceConfiguration_DataSourceConfiguration(getContext(), s3datasourceconfiguration_datasourceconfiguration);
	}

	/**
	 * Set value of S3DataSourceConfiguration_DataSourceConfiguration
	 * @param context
	 * @param s3datasourceconfiguration_datasourceconfiguration
	 */
	public final void setS3DataSourceConfiguration_DataSourceConfiguration(com.mendix.systemwideinterfaces.core.IContext context, amazonbedrockconnector.proxies.S3DataSourceConfiguration s3datasourceconfiguration_datasourceconfiguration)
	{
		if (s3datasourceconfiguration_datasourceconfiguration == null) {
			getMendixObject().setValue(context, MemberNames.S3DataSourceConfiguration_DataSourceConfiguration.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.S3DataSourceConfiguration_DataSourceConfiguration.toString(), s3datasourceconfiguration_datasourceconfiguration.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of SharePointDataSourceConfiguration_DataSourceConfiguration
	 */
	public final amazonbedrockconnector.proxies.SharePointDataSourceConfiguration getSharePointDataSourceConfiguration_DataSourceConfiguration() throws com.mendix.core.CoreException
	{
		return getSharePointDataSourceConfiguration_DataSourceConfiguration(getContext());
	}

	/**
	 * @param context
	 * @return value of SharePointDataSourceConfiguration_DataSourceConfiguration
	 * @throws com.mendix.core.CoreException
	 */
	public final amazonbedrockconnector.proxies.SharePointDataSourceConfiguration getSharePointDataSourceConfiguration_DataSourceConfiguration(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		amazonbedrockconnector.proxies.SharePointDataSourceConfiguration result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.SharePointDataSourceConfiguration_DataSourceConfiguration.toString());
		if (identifier != null) {
			result = amazonbedrockconnector.proxies.SharePointDataSourceConfiguration.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of SharePointDataSourceConfiguration_DataSourceConfiguration
	 * @param sharepointdatasourceconfiguration_datasourceconfiguration
	 */
	public final void setSharePointDataSourceConfiguration_DataSourceConfiguration(amazonbedrockconnector.proxies.SharePointDataSourceConfiguration sharepointdatasourceconfiguration_datasourceconfiguration)
	{
		setSharePointDataSourceConfiguration_DataSourceConfiguration(getContext(), sharepointdatasourceconfiguration_datasourceconfiguration);
	}

	/**
	 * Set value of SharePointDataSourceConfiguration_DataSourceConfiguration
	 * @param context
	 * @param sharepointdatasourceconfiguration_datasourceconfiguration
	 */
	public final void setSharePointDataSourceConfiguration_DataSourceConfiguration(com.mendix.systemwideinterfaces.core.IContext context, amazonbedrockconnector.proxies.SharePointDataSourceConfiguration sharepointdatasourceconfiguration_datasourceconfiguration)
	{
		if (sharepointdatasourceconfiguration_datasourceconfiguration == null) {
			getMendixObject().setValue(context, MemberNames.SharePointDataSourceConfiguration_DataSourceConfiguration.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.SharePointDataSourceConfiguration_DataSourceConfiguration.toString(), sharepointdatasourceconfiguration_datasourceconfiguration.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of DataSourceConfiguration_DataSource
	 */
	public final amazonbedrockconnector.proxies.DataSource getDataSourceConfiguration_DataSource() throws com.mendix.core.CoreException
	{
		return getDataSourceConfiguration_DataSource(getContext());
	}

	/**
	 * @param context
	 * @return value of DataSourceConfiguration_DataSource
	 * @throws com.mendix.core.CoreException
	 */
	public final amazonbedrockconnector.proxies.DataSource getDataSourceConfiguration_DataSource(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		amazonbedrockconnector.proxies.DataSource result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DataSourceConfiguration_DataSource.toString());
		if (identifier != null) {
			result = amazonbedrockconnector.proxies.DataSource.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of DataSourceConfiguration_DataSource
	 * @param datasourceconfiguration_datasource
	 */
	public final void setDataSourceConfiguration_DataSource(amazonbedrockconnector.proxies.DataSource datasourceconfiguration_datasource)
	{
		setDataSourceConfiguration_DataSource(getContext(), datasourceconfiguration_datasource);
	}

	/**
	 * Set value of DataSourceConfiguration_DataSource
	 * @param context
	 * @param datasourceconfiguration_datasource
	 */
	public final void setDataSourceConfiguration_DataSource(com.mendix.systemwideinterfaces.core.IContext context, amazonbedrockconnector.proxies.DataSource datasourceconfiguration_datasource)
	{
		if (datasourceconfiguration_datasource == null) {
			getMendixObject().setValue(context, MemberNames.DataSourceConfiguration_DataSource.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.DataSourceConfiguration_DataSource.toString(), datasourceconfiguration_datasource.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return dataSourceConfigurationMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final amazonbedrockconnector.proxies.DataSourceConfiguration that = (amazonbedrockconnector.proxies.DataSourceConfiguration) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
