// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package amazonbedrockconnector.proxies;

/**
 * Contains details about a data source.
 * 
 * API reference:
 * https://docs.aws.amazon.com/bedrock/latest/APIReference/API_agent_DataSourceSummary.html
 * 
 * Java SDK documentation:
 * https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/bedrockagent/model/DataSourceSummary.html
 */
public class DataSourceSummary implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject dataSourceSummaryMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AmazonBedrockConnector.DataSourceSummary";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		DataSourceId("DataSourceId"),
		KnowledgeBaseId("KnowledgeBaseId"),
		Name("Name"),
		Status("Status"),
		UpdatedAt("UpdatedAt"),
		Description("Description"),
		DataSourceSummary_ListDataSourcesResponse("AmazonBedrockConnector.DataSourceSummary_ListDataSourcesResponse");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public DataSourceSummary(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected DataSourceSummary(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject dataSourceSummaryMendixObject)
	{
		if (dataSourceSummaryMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!dataSourceSummaryMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.dataSourceSummaryMendixObject = dataSourceSummaryMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static amazonbedrockconnector.proxies.DataSourceSummary initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new amazonbedrockconnector.proxies.DataSourceSummary(context, mendixObject);
	}

	public static amazonbedrockconnector.proxies.DataSourceSummary load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return amazonbedrockconnector.proxies.DataSourceSummary.initialize(context, mendixObject);
	}

	/**
	 * @return value of DataSourceId
	 */
	public final java.lang.String getDataSourceId()
	{
		return getDataSourceId(getContext());
	}

	/**
	 * @param context
	 * @return value of DataSourceId
	 */
	public final java.lang.String getDataSourceId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DataSourceId.toString());
	}

	/**
	 * Set value of DataSourceId
	 * @param datasourceid
	 */
	public final void setDataSourceId(java.lang.String datasourceid)
	{
		setDataSourceId(getContext(), datasourceid);
	}

	/**
	 * Set value of DataSourceId
	 * @param context
	 * @param datasourceid
	 */
	public final void setDataSourceId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String datasourceid)
	{
		getMendixObject().setValue(context, MemberNames.DataSourceId.toString(), datasourceid);
	}

	/**
	 * @return value of KnowledgeBaseId
	 */
	public final java.lang.String getKnowledgeBaseId()
	{
		return getKnowledgeBaseId(getContext());
	}

	/**
	 * @param context
	 * @return value of KnowledgeBaseId
	 */
	public final java.lang.String getKnowledgeBaseId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.KnowledgeBaseId.toString());
	}

	/**
	 * Set value of KnowledgeBaseId
	 * @param knowledgebaseid
	 */
	public final void setKnowledgeBaseId(java.lang.String knowledgebaseid)
	{
		setKnowledgeBaseId(getContext(), knowledgebaseid);
	}

	/**
	 * Set value of KnowledgeBaseId
	 * @param context
	 * @param knowledgebaseid
	 */
	public final void setKnowledgeBaseId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String knowledgebaseid)
	{
		getMendixObject().setValue(context, MemberNames.KnowledgeBaseId.toString(), knowledgebaseid);
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * Get value of Status
	 * @param status
	 */
	public final amazonbedrockconnector.proxies.ENUM_DataSourceStatus getStatus()
	{
		return getStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of Status
	 */
	public final amazonbedrockconnector.proxies.ENUM_DataSourceStatus getStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Status.toString());
		if (obj == null) {
			return null;
		}
		return amazonbedrockconnector.proxies.ENUM_DataSourceStatus.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Status
	 * @param status
	 */
	public final void setStatus(amazonbedrockconnector.proxies.ENUM_DataSourceStatus status)
	{
		setStatus(getContext(), status);
	}

	/**
	 * Set value of Status
	 * @param context
	 * @param status
	 */
	public final void setStatus(com.mendix.systemwideinterfaces.core.IContext context, amazonbedrockconnector.proxies.ENUM_DataSourceStatus status)
	{
		if (status != null) {
			getMendixObject().setValue(context, MemberNames.Status.toString(), status.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.Status.toString(), null);
		}
	}

	/**
	 * @return value of UpdatedAt
	 */
	public final java.util.Date getUpdatedAt()
	{
		return getUpdatedAt(getContext());
	}

	/**
	 * @param context
	 * @return value of UpdatedAt
	 */
	public final java.util.Date getUpdatedAt(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.UpdatedAt.toString());
	}

	/**
	 * Set value of UpdatedAt
	 * @param updatedat
	 */
	public final void setUpdatedAt(java.util.Date updatedat)
	{
		setUpdatedAt(getContext(), updatedat);
	}

	/**
	 * Set value of UpdatedAt
	 * @param context
	 * @param updatedat
	 */
	public final void setUpdatedAt(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date updatedat)
	{
		getMendixObject().setValue(context, MemberNames.UpdatedAt.toString(), updatedat);
	}

	/**
	 * @return value of Description
	 */
	public final java.lang.String getDescription()
	{
		return getDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of Description
	 */
	public final java.lang.String getDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Description.toString());
	}

	/**
	 * Set value of Description
	 * @param description
	 */
	public final void setDescription(java.lang.String description)
	{
		setDescription(getContext(), description);
	}

	/**
	 * Set value of Description
	 * @param context
	 * @param description
	 */
	public final void setDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String description)
	{
		getMendixObject().setValue(context, MemberNames.Description.toString(), description);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of DataSourceSummary_ListDataSourcesResponse
	 */
	public final amazonbedrockconnector.proxies.ListDataSourcesResponse getDataSourceSummary_ListDataSourcesResponse() throws com.mendix.core.CoreException
	{
		return getDataSourceSummary_ListDataSourcesResponse(getContext());
	}

	/**
	 * @param context
	 * @return value of DataSourceSummary_ListDataSourcesResponse
	 * @throws com.mendix.core.CoreException
	 */
	public final amazonbedrockconnector.proxies.ListDataSourcesResponse getDataSourceSummary_ListDataSourcesResponse(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		amazonbedrockconnector.proxies.ListDataSourcesResponse result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DataSourceSummary_ListDataSourcesResponse.toString());
		if (identifier != null) {
			result = amazonbedrockconnector.proxies.ListDataSourcesResponse.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of DataSourceSummary_ListDataSourcesResponse
	 * @param datasourcesummary_listdatasourcesresponse
	 */
	public final void setDataSourceSummary_ListDataSourcesResponse(amazonbedrockconnector.proxies.ListDataSourcesResponse datasourcesummary_listdatasourcesresponse)
	{
		setDataSourceSummary_ListDataSourcesResponse(getContext(), datasourcesummary_listdatasourcesresponse);
	}

	/**
	 * Set value of DataSourceSummary_ListDataSourcesResponse
	 * @param context
	 * @param datasourcesummary_listdatasourcesresponse
	 */
	public final void setDataSourceSummary_ListDataSourcesResponse(com.mendix.systemwideinterfaces.core.IContext context, amazonbedrockconnector.proxies.ListDataSourcesResponse datasourcesummary_listdatasourcesresponse)
	{
		if (datasourcesummary_listdatasourcesresponse == null) {
			getMendixObject().setValue(context, MemberNames.DataSourceSummary_ListDataSourcesResponse.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.DataSourceSummary_ListDataSourcesResponse.toString(), datasourcesummary_listdatasourcesresponse.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return dataSourceSummaryMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final amazonbedrockconnector.proxies.DataSourceSummary that = (amazonbedrockconnector.proxies.DataSourceSummary) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
