// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package amazonbedrockconnector.proxies;

/**
 * This entity is the response for the Amazon Bedrock DeleteDataSource action.
 * 
 * API reference:
 * https://docs.aws.amazon.com/bedrock/latest/APIReference/API_agent_DeleteDataSource.html
 * 
 * Java SDK documentation:
 * https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/bedrockagent/model/DeleteDataSourceResponse.html
 */
public class DeleteDataSourceResponse implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject deleteDataSourceResponseMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AmazonBedrockConnector.DeleteDataSourceResponse";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		DataSourceId("DataSourceId"),
		KnowledgeBaseId("KnowledgeBaseId"),
		Status("Status");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public DeleteDataSourceResponse(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected DeleteDataSourceResponse(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject deleteDataSourceResponseMendixObject)
	{
		if (deleteDataSourceResponseMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!deleteDataSourceResponseMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.deleteDataSourceResponseMendixObject = deleteDataSourceResponseMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static amazonbedrockconnector.proxies.DeleteDataSourceResponse initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new amazonbedrockconnector.proxies.DeleteDataSourceResponse(context, mendixObject);
	}

	public static amazonbedrockconnector.proxies.DeleteDataSourceResponse load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return amazonbedrockconnector.proxies.DeleteDataSourceResponse.initialize(context, mendixObject);
	}

	/**
	 * @return value of DataSourceId
	 */
	public final java.lang.String getDataSourceId()
	{
		return getDataSourceId(getContext());
	}

	/**
	 * @param context
	 * @return value of DataSourceId
	 */
	public final java.lang.String getDataSourceId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DataSourceId.toString());
	}

	/**
	 * Set value of DataSourceId
	 * @param datasourceid
	 */
	public final void setDataSourceId(java.lang.String datasourceid)
	{
		setDataSourceId(getContext(), datasourceid);
	}

	/**
	 * Set value of DataSourceId
	 * @param context
	 * @param datasourceid
	 */
	public final void setDataSourceId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String datasourceid)
	{
		getMendixObject().setValue(context, MemberNames.DataSourceId.toString(), datasourceid);
	}

	/**
	 * @return value of KnowledgeBaseId
	 */
	public final java.lang.String getKnowledgeBaseId()
	{
		return getKnowledgeBaseId(getContext());
	}

	/**
	 * @param context
	 * @return value of KnowledgeBaseId
	 */
	public final java.lang.String getKnowledgeBaseId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.KnowledgeBaseId.toString());
	}

	/**
	 * Set value of KnowledgeBaseId
	 * @param knowledgebaseid
	 */
	public final void setKnowledgeBaseId(java.lang.String knowledgebaseid)
	{
		setKnowledgeBaseId(getContext(), knowledgebaseid);
	}

	/**
	 * Set value of KnowledgeBaseId
	 * @param context
	 * @param knowledgebaseid
	 */
	public final void setKnowledgeBaseId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String knowledgebaseid)
	{
		getMendixObject().setValue(context, MemberNames.KnowledgeBaseId.toString(), knowledgebaseid);
	}

	/**
	 * Get value of Status
	 * @param status
	 */
	public final amazonbedrockconnector.proxies.ENUM_DataSourceStatus getStatus()
	{
		return getStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of Status
	 */
	public final amazonbedrockconnector.proxies.ENUM_DataSourceStatus getStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Status.toString());
		if (obj == null) {
			return null;
		}
		return amazonbedrockconnector.proxies.ENUM_DataSourceStatus.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Status
	 * @param status
	 */
	public final void setStatus(amazonbedrockconnector.proxies.ENUM_DataSourceStatus status)
	{
		setStatus(getContext(), status);
	}

	/**
	 * Set value of Status
	 * @param context
	 * @param status
	 */
	public final void setStatus(com.mendix.systemwideinterfaces.core.IContext context, amazonbedrockconnector.proxies.ENUM_DataSourceStatus status)
	{
		if (status != null) {
			getMendixObject().setValue(context, MemberNames.Status.toString(), status.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.Status.toString(), null);
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return deleteDataSourceResponseMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final amazonbedrockconnector.proxies.DeleteDataSourceResponse that = (amazonbedrockconnector.proxies.DeleteDataSourceResponse) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
