// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package amazonbedrockconnector.proxies;

public enum ENUM_ModelFamily
{
	AnthropicClaude("cbbdb645-a384-487a-8fd7-544ead2be1e4"),
	Titan("92ef6699-a10c-4190-9688-313b5269793d"),
	TitanEmbeddings("aa5476fa-68c5-49c8-bf32-c3010585843c"),
	CohereEmbed("b80ac85c-dc87-483e-aa9d-59e541462989");

	private final java.lang.String i18nCaptionKey;
	
	private ENUM_ModelFamily(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
