// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package amazonbedrockconnector.proxies;

public enum ENUM_InferenceType
{
	ON_DEMAND("3171bd59-06a3-4619-869e-2abc342cc619"),
	PROVISIONED("9c7a08c7-d891-4ac4-a6af-3609b9469c6b"),
	UNKNOWN_TO_SDK_VERSION("b361e80a-3244-4928-bdca-02aec769988e");

	private final java.lang.String i18nCaptionKey;
	
	private ENUM_InferenceType(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
