// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package amazonbedrockconnector.proxies;

/**
 * Width x Height (in pixels)
 */
public enum ENUM_ImageSize_TitanImage
{
	_1024x1024("d4327892-e22a-4f44-ad69-5d53b6a339aa"),
	_768x768("1bd6f3ec-e9e9-47e5-bed3-11b61b871a8e"),
	_512x512("7f894266-876b-445f-a89a-001ad7e7b2c9"),
	_768x1152("a9493235-2b91-4d91-bd88-a2e397c3c681"),
	_384x576("d4910529-55ce-4dcb-81a2-0c325c39f727"),
	_1152x768("842f4d80-08ae-44e9-92f5-3d58fe63fcfd"),
	_576x384("72d4c856-093f-4a0d-97e9-5a63fd5bc395"),
	_768x1280("aac61e68-7289-4bad-af60-15e830e2ab30"),
	_384x640("9fce49e2-1729-42c1-ab5c-2c1597352909"),
	_1280x768("c1faa4fd-8cea-40fe-9001-8ef0142b3854"),
	_640x384("38125383-25b6-4b73-91f5-074805f54d98"),
	_896x1152("c1bb56f8-288b-419d-ada5-6e740fdb3425"),
	_448x576("85695eaa-15a1-4ac0-bb03-546b90bcbb8c"),
	_1152x896("570cd0fd-16d5-484b-9312-5856c7edd118"),
	_576x448("11a65734-7ba6-46be-80d0-32659e4cf0a0"),
	_768x1408("f3ee627d-c82d-4f47-b351-a5a388417012"),
	_384x704("f93b3c43-4fdd-43da-83e5-c7eed89410a4"),
	_1408x768("b4785942-2956-4648-82ef-c66c1add4222"),
	_704x384("c35dc705-d782-4b8e-912f-71a9fbed3ae3"),
	_640x1408("cc1a6396-e046-4243-bc3f-720f09160cf8"),
	_320x704("dcfd95c0-7aaf-46f7-99e1-957857bc9143"),
	_1408x640("2b6220f3-af93-4f74-8699-d2cf8ee40b26"),
	_704x320("b07934c8-95e0-45d5-8188-2f1dd39fff12"),
	_1152x640("10033e6e-b0ee-49bb-b93b-2dd51c1d137d"),
	_1173x640("7ac4d7f5-ef56-4ae2-a1f8-81186ac8df45");

	private final java.lang.String i18nCaptionKey;
	
	private ENUM_ImageSize_TitanImage(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
