// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package amazonbedrockconnector.proxies;

public enum ENUM_InputType_CohereEmbed
{
	search_document("cdbf5341-f936-484f-ba98-70af3511fb24"),
	search_query("96d96779-4fc7-4a8b-aafa-a41fa9abebee"),
	classification("fd7e825c-49c7-4f36-80fd-d9678078ae1d"),
	clustering("0f25c002-0d71-487a-a919-098411c84aaa");

	private final java.lang.String i18nCaptionKey;
	
	private ENUM_InputType_CohereEmbed(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
