// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package amazonbedrockconnector.proxies;

public enum ENUM_Truncate_CohereEmbed
{
	NONE("22a54e2f-ff0a-47a6-8788-ef91ed6972fd"),
	START("72ec8256-c6c1-4bce-92d1-215478434a9e"),
	END("c9d04fbe-b81b-46de-9b7c-ee626c553e81");

	private final java.lang.String i18nCaptionKey;
	
	private ENUM_Truncate_CohereEmbed(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
