// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package amazonbedrockconnector.proxies;

public enum ENUM_InputOutputModality
{
	TEXT("d51874e5-9841-4dbe-b145-6e646a560435"),
	IMAGE("9364fe07-bdc3-40b0-832a-fb8938719028"),
	EMBEDDING("fd7af62a-11fc-421f-9d00-1f76daec51fe"),
	UNKNOWN_TO_SDK_VERSION("3e955082-b437-4063-a95a-12f798df6ea8");

	private final java.lang.String i18nCaptionKey;
	
	private ENUM_InputOutputModality(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
