// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package amazonbedrockconnector.proxies;

public enum ENUM_PromptType
{
	PRE_PROCESSING("0fdc7f11-e862-4b54-a016-f62fd2ddb679"),
	ORCHESTRATION("7102d765-f7d9-4cc0-8734-2c4323932db8"),
	KNOWLEDGE_BASE_RESPONSE_GENERATION("2b447806-fdfa-4540-aa9c-c06f39bbb768"),
	POST_PROCESSING("33f0d1cb-f154-4730-a61f-deffe526d5a9"),
	UNKNOWN_TO_SDK_VERSION("1d5a1e3d-5204-4696-8236-89e703751100");

	private final java.lang.String i18nCaptionKey;
	
	private ENUM_PromptType(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
