// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package amazonbedrockconnector.proxies;

public enum ENUM_TraceType
{
	FAILURE_TRACE("0d0ff637-ee3a-410c-984d-072ec6ce4a3b"),
	PRE_PROCESSING_TRACE("8e34e606-a58e-4bac-8e9e-a6c9cefab08a"),
	ORCHESTRATION_TRACE("9b05e9ce-e939-4960-8dde-9b55241409b6"),
	POST_PROCESSING_TRACE("e76818ed-32a6-4dd8-ae43-cfb944ed1ffd"),
	UNKNOWN_TO_SDK_VERSION("5bce17a8-85f2-4f76-9dd1-d121abeaa283");

	private final java.lang.String i18nCaptionKey;
	
	private ENUM_TraceType(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
