// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package amazonbedrockconnector.proxies;

public enum ENUM_EmbeddingTypes_CohereEmbed
{
	_float("c3d6932f-95db-4d95-968a-181b895d1092"),
	int8("64af8fd5-adf9-4c38-9229-aa66686b8852"),
	uint8("2485c002-ec7a-465b-904e-7d698c22009f"),
	binary("ac7443ca-edef-4a3c-b888-f5548a5b9f37"),
	ubinary("3641e10d-cefa-4a65-9c2f-25127663df4d");

	private final java.lang.String i18nCaptionKey;
	
	private ENUM_EmbeddingTypes_CohereEmbed(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
