// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package amazonbedrockconnector.proxies;

public enum ENUM_SharePointAuthType
{
	OAUTH2_CLIENT_CREDENTIALS("55aa3115-3822-4a45-9635-cdd964f1e65e"),
	UNKNOWN_TO_SDK_VERSION("65de1199-8bf7-4736-98a6-31117a4577cf");

	private final java.lang.String i18nCaptionKey;
	
	private ENUM_SharePointAuthType(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
