// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package amazonbedrockconnector.proxies;

public enum ENUM_CreationMode
{
	_DEFAULT("8dc18112-1a8a-4f95-a1ed-a8d929b540fa"),
	OVERRIDDEN("25e562d2-6c26-4f57-9eca-f882a733a7f2"),
	UNKNOWN_TO_SDK_VERSION("99910ca6-d37d-46cd-b625-0a6b5e216d6f");

	private final java.lang.String i18nCaptionKey;
	
	private ENUM_CreationMode(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
