// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package amazonbedrockconnector.proxies;

public enum ENUM_ObservationType
{
	ACTION_GROUP("f6a89269-c344-4723-80dd-79a2a24911c3"),
	KNOWLEDGE_BASE("3036cfce-0a7d-4149-acf6-911f7c7a9f54"),
	FINISH("b4520168-4965-49db-af0c-e76f02f281f3"),
	ASK_USER("f813d321-44b4-4d26-8707-0e1bf79122e7"),
	REPROMPT("fb51efca-4a3a-4b43-a490-e16b0d0b30ca"),
	UNKNOWN_TO_SDK_VERSION("856d152e-092d-422a-b781-006753b9fc4f");

	private final java.lang.String i18nCaptionKey;
	
	private ENUM_ObservationType(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
