// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package amazonbedrockconnector.proxies;

public enum ENUM_AgentStatus
{
	CREATING("3e926989-1b79-413f-938e-b02bea38a754"),
	PREPARING("d2b328e7-d103-494c-9ac7-99c41f9aff4d"),
	PREPARED("a71db4c1-60a3-4229-99c1-b3cda294c7d5"),
	NOT_PREPARED("3995ed9b-cdd5-4830-8243-f00d37731b0d"),
	DELETING("c2463157-d70e-49c1-803e-42c0a4880f04"),
	FAILED("b47052bc-9630-414b-b004-b44fc8c4d432"),
	VERSIONING("63e3be8a-4d16-479c-a02e-f9a7ae97537a"),
	UPDATING("442e6f9c-5d65-491f-9b5e-88e3c953fc83"),
	UNKNOWN_TO_SDK_VERSION("7e902395-3d30-4ec5-b57e-7585e70a108a");

	private final java.lang.String i18nCaptionKey;
	
	private ENUM_AgentStatus(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
