// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package amazonbedrockconnector.proxies;

public enum ENUM_DataSourceType
{
	S3("520b534e-c167-4f01-953e-22cf0d23fc37"),
	WEB("9e10f374-364c-4755-85e4-d2a8526ddf66"),
	CONFLUENCE("8e512545-4418-4753-9f61-cecd2a21e5d1"),
	SALESFORCE("e79fefd1-ea9c-454e-a98e-ad56b2a93a51"),
	SHAREPOINT("9c17214a-f44b-453a-b84c-1d41b9e10edd"),
	CUSTOM("bdf5441b-b3bb-443e-876f-6a49b1c84ba2"),
	REDSHIFT_METADATA("a7dcb9d3-d63b-4c30-b9b9-e294260b1712"),
	UNKNOWN_TO_SDK_VERSION("4e119b98-b546-43b2-bbbf-5c7fbc8d126a");

	private final java.lang.String i18nCaptionKey;
	
	private ENUM_DataSourceType(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
