// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package amazonbedrockconnector.proxies;

public enum ENUM_DataSourceStatus
{
	AVAILABLE("b7586cc1-1d8f-406d-b1ee-be926e6d7bd5"),
	DELETING("066aa604-136b-49b7-99b2-d394cef9e8cd"),
	DELETE_UNSUCCESSFUL("050d1c37-9768-41b8-9c07-674ba0a0a312"),
	UNKNOWN_TO_SDK_VERSION("79b2fb84-3c37-4e20-8be0-70000ce67bd8");

	private final java.lang.String i18nCaptionKey;
	
	private ENUM_DataSourceStatus(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
