// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package amazonbedrockconnector.proxies;

public enum ENUM_IngestionJobStatus
{
	STARTING("28a6b848-66ff-4c58-b089-77f1fdcbf3a5"),
	IN_PROGRESS("901b9460-5472-4634-973c-a9f1b3ada3ab"),
	COMPLETE("394287aa-b31a-47b0-a55f-51cc5be95825"),
	FAILED("59cf1487-8525-4bcf-8011-fe78feb884f4"),
	UNKNOWN_TO_SDK_VERSION("f309ed2e-a6fc-4b5a-afdd-7b32f38790e7");

	private final java.lang.String i18nCaptionKey;
	
	private ENUM_IngestionJobStatus(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
