// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package amazonbedrockconnector.proxies;

public enum ENUM_KnowledgeBaseStatus
{
	CREATING("972977a2-9797-4fee-968d-263937e5a1bc"),
	ACTIVE("84264f1b-21d9-429e-b6a6-3fa692e492a0"),
	DELETING("90bf55ad-dae9-41ea-95d2-bafcf50ca3be"),
	UPDATING("5ff9dd52-ab52-4bb2-89e8-227d41ff311e"),
	FAILED("73b3bfb3-4573-4549-931f-69da7407fd52"),
	DELETE_UNSUCCESSFUL("d2219725-d02c-4453-969a-dad6b7b881cc"),
	UNKNOWN_TO_SDK_VERSION("094f6d42-1596-4559-9eff-f383ef425a7a");

	private final java.lang.String i18nCaptionKey;
	
	private ENUM_KnowledgeBaseStatus(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
