// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package amazonbedrockconnector.proxies;

public enum ENUM_RepromptSource
{
	ACTION_GROUP("f20deb4e-2b5c-4368-80f6-5163754aeb05"),
	KNOWLEDGE_BASE("9ad7d2d3-da4a-4e57-af7e-5f412efb5ec1"),
	PARSER("c88e0a53-ec18-4fbc-90a5-739eef76aa5b"),
	UNKNOWN_TO_SDK_VERSION("725f0f54-36da-44b5-a972-491e5d522cd6");

	private final java.lang.String i18nCaptionKey;
	
	private ENUM_RepromptSource(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
