// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package amazonbedrockconnector.proxies;

/**
 * Contains information about the failure of the interaction.
 */
public class FailureReason implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject failureReasonMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AmazonBedrockConnector.FailureReason";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Text("Text"),
		FailureReason_IngestionJob("AmazonBedrockConnector.FailureReason_IngestionJob");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public FailureReason(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected FailureReason(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject failureReasonMendixObject)
	{
		if (failureReasonMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!failureReasonMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.failureReasonMendixObject = failureReasonMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static amazonbedrockconnector.proxies.FailureReason initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new amazonbedrockconnector.proxies.FailureReason(context, mendixObject);
	}

	public static amazonbedrockconnector.proxies.FailureReason load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return amazonbedrockconnector.proxies.FailureReason.initialize(context, mendixObject);
	}

	/**
	 * @return value of Text
	 */
	public final java.lang.String getText()
	{
		return getText(getContext());
	}

	/**
	 * @param context
	 * @return value of Text
	 */
	public final java.lang.String getText(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Text.toString());
	}

	/**
	 * Set value of Text
	 * @param text
	 */
	public final void setText(java.lang.String text)
	{
		setText(getContext(), text);
	}

	/**
	 * Set value of Text
	 * @param context
	 * @param text
	 */
	public final void setText(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String text)
	{
		getMendixObject().setValue(context, MemberNames.Text.toString(), text);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of FailureReason_IngestionJob
	 */
	public final amazonbedrockconnector.proxies.IngestionJob getFailureReason_IngestionJob() throws com.mendix.core.CoreException
	{
		return getFailureReason_IngestionJob(getContext());
	}

	/**
	 * @param context
	 * @return value of FailureReason_IngestionJob
	 * @throws com.mendix.core.CoreException
	 */
	public final amazonbedrockconnector.proxies.IngestionJob getFailureReason_IngestionJob(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		amazonbedrockconnector.proxies.IngestionJob result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.FailureReason_IngestionJob.toString());
		if (identifier != null) {
			result = amazonbedrockconnector.proxies.IngestionJob.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of FailureReason_IngestionJob
	 * @param failurereason_ingestionjob
	 */
	public final void setFailureReason_IngestionJob(amazonbedrockconnector.proxies.IngestionJob failurereason_ingestionjob)
	{
		setFailureReason_IngestionJob(getContext(), failurereason_ingestionjob);
	}

	/**
	 * Set value of FailureReason_IngestionJob
	 * @param context
	 * @param failurereason_ingestionjob
	 */
	public final void setFailureReason_IngestionJob(com.mendix.systemwideinterfaces.core.IContext context, amazonbedrockconnector.proxies.IngestionJob failurereason_ingestionjob)
	{
		if (failurereason_ingestionjob == null) {
			getMendixObject().setValue(context, MemberNames.FailureReason_IngestionJob.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.FailureReason_IngestionJob.toString(), failurereason_ingestionjob.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return failureReasonMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final amazonbedrockconnector.proxies.FailureReason that = (amazonbedrockconnector.proxies.FailureReason) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
