// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package amazonbedrockconnector.proxies;

/**
 * This entity contains details (ModelArn & ModelId) of the requested foundational models.
 */
public class FoundationModelSummary implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject foundationModelSummaryMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AmazonBedrockConnector.FoundationModelSummary";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ModelARN("ModelARN"),
		ModelID("ModelID"),
		ModelName("ModelName"),
		ProviderName("ProviderName"),
		ResponseStreamingSupported("ResponseStreamingSupported"),
		FoundationModelSummary_ListFoundationModelsResponse("AmazonBedrockConnector.FoundationModelSummary_ListFoundationModelsResponse"),
		FoundationModelLifecycle_FoundationModelSummary("AmazonBedrockConnector.FoundationModelLifecycle_FoundationModelSummary");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public FoundationModelSummary(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected FoundationModelSummary(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject foundationModelSummaryMendixObject)
	{
		if (foundationModelSummaryMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!foundationModelSummaryMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.foundationModelSummaryMendixObject = foundationModelSummaryMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static amazonbedrockconnector.proxies.FoundationModelSummary initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new amazonbedrockconnector.proxies.FoundationModelSummary(context, mendixObject);
	}

	public static amazonbedrockconnector.proxies.FoundationModelSummary load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return amazonbedrockconnector.proxies.FoundationModelSummary.initialize(context, mendixObject);
	}

	/**
	 * @return value of ModelARN
	 */
	public final java.lang.String getModelARN()
	{
		return getModelARN(getContext());
	}

	/**
	 * @param context
	 * @return value of ModelARN
	 */
	public final java.lang.String getModelARN(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ModelARN.toString());
	}

	/**
	 * Set value of ModelARN
	 * @param modelarn
	 */
	public final void setModelARN(java.lang.String modelarn)
	{
		setModelARN(getContext(), modelarn);
	}

	/**
	 * Set value of ModelARN
	 * @param context
	 * @param modelarn
	 */
	public final void setModelARN(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String modelarn)
	{
		getMendixObject().setValue(context, MemberNames.ModelARN.toString(), modelarn);
	}

	/**
	 * @return value of ModelID
	 */
	public final java.lang.String getModelID()
	{
		return getModelID(getContext());
	}

	/**
	 * @param context
	 * @return value of ModelID
	 */
	public final java.lang.String getModelID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ModelID.toString());
	}

	/**
	 * Set value of ModelID
	 * @param modelid
	 */
	public final void setModelID(java.lang.String modelid)
	{
		setModelID(getContext(), modelid);
	}

	/**
	 * Set value of ModelID
	 * @param context
	 * @param modelid
	 */
	public final void setModelID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String modelid)
	{
		getMendixObject().setValue(context, MemberNames.ModelID.toString(), modelid);
	}

	/**
	 * @return value of ModelName
	 */
	public final java.lang.String getModelName()
	{
		return getModelName(getContext());
	}

	/**
	 * @param context
	 * @return value of ModelName
	 */
	public final java.lang.String getModelName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ModelName.toString());
	}

	/**
	 * Set value of ModelName
	 * @param modelname
	 */
	public final void setModelName(java.lang.String modelname)
	{
		setModelName(getContext(), modelname);
	}

	/**
	 * Set value of ModelName
	 * @param context
	 * @param modelname
	 */
	public final void setModelName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String modelname)
	{
		getMendixObject().setValue(context, MemberNames.ModelName.toString(), modelname);
	}

	/**
	 * @return value of ProviderName
	 */
	public final java.lang.String getProviderName()
	{
		return getProviderName(getContext());
	}

	/**
	 * @param context
	 * @return value of ProviderName
	 */
	public final java.lang.String getProviderName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ProviderName.toString());
	}

	/**
	 * Set value of ProviderName
	 * @param providername
	 */
	public final void setProviderName(java.lang.String providername)
	{
		setProviderName(getContext(), providername);
	}

	/**
	 * Set value of ProviderName
	 * @param context
	 * @param providername
	 */
	public final void setProviderName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String providername)
	{
		getMendixObject().setValue(context, MemberNames.ProviderName.toString(), providername);
	}

	/**
	 * @return value of ResponseStreamingSupported
	 */
	public final java.lang.Boolean getResponseStreamingSupported()
	{
		return getResponseStreamingSupported(getContext());
	}

	/**
	 * @param context
	 * @return value of ResponseStreamingSupported
	 */
	public final java.lang.Boolean getResponseStreamingSupported(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ResponseStreamingSupported.toString());
	}

	/**
	 * Set value of ResponseStreamingSupported
	 * @param responsestreamingsupported
	 */
	public final void setResponseStreamingSupported(java.lang.Boolean responsestreamingsupported)
	{
		setResponseStreamingSupported(getContext(), responsestreamingsupported);
	}

	/**
	 * Set value of ResponseStreamingSupported
	 * @param context
	 * @param responsestreamingsupported
	 */
	public final void setResponseStreamingSupported(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean responsestreamingsupported)
	{
		getMendixObject().setValue(context, MemberNames.ResponseStreamingSupported.toString(), responsestreamingsupported);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of FoundationModelSummary_ListFoundationModelsResponse
	 */
	public final amazonbedrockconnector.proxies.ListFoundationModelsResponse getFoundationModelSummary_ListFoundationModelsResponse() throws com.mendix.core.CoreException
	{
		return getFoundationModelSummary_ListFoundationModelsResponse(getContext());
	}

	/**
	 * @param context
	 * @return value of FoundationModelSummary_ListFoundationModelsResponse
	 * @throws com.mendix.core.CoreException
	 */
	public final amazonbedrockconnector.proxies.ListFoundationModelsResponse getFoundationModelSummary_ListFoundationModelsResponse(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		amazonbedrockconnector.proxies.ListFoundationModelsResponse result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.FoundationModelSummary_ListFoundationModelsResponse.toString());
		if (identifier != null) {
			result = amazonbedrockconnector.proxies.ListFoundationModelsResponse.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of FoundationModelSummary_ListFoundationModelsResponse
	 * @param foundationmodelsummary_listfoundationmodelsresponse
	 */
	public final void setFoundationModelSummary_ListFoundationModelsResponse(amazonbedrockconnector.proxies.ListFoundationModelsResponse foundationmodelsummary_listfoundationmodelsresponse)
	{
		setFoundationModelSummary_ListFoundationModelsResponse(getContext(), foundationmodelsummary_listfoundationmodelsresponse);
	}

	/**
	 * Set value of FoundationModelSummary_ListFoundationModelsResponse
	 * @param context
	 * @param foundationmodelsummary_listfoundationmodelsresponse
	 */
	public final void setFoundationModelSummary_ListFoundationModelsResponse(com.mendix.systemwideinterfaces.core.IContext context, amazonbedrockconnector.proxies.ListFoundationModelsResponse foundationmodelsummary_listfoundationmodelsresponse)
	{
		if (foundationmodelsummary_listfoundationmodelsresponse == null) {
			getMendixObject().setValue(context, MemberNames.FoundationModelSummary_ListFoundationModelsResponse.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.FoundationModelSummary_ListFoundationModelsResponse.toString(), foundationmodelsummary_listfoundationmodelsresponse.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of FoundationModelLifecycle_FoundationModelSummary
	 */
	public final amazonbedrockconnector.proxies.FoundationModelLifecycle getFoundationModelLifecycle_FoundationModelSummary() throws com.mendix.core.CoreException
	{
		return getFoundationModelLifecycle_FoundationModelSummary(getContext());
	}

	/**
	 * @param context
	 * @return value of FoundationModelLifecycle_FoundationModelSummary
	 * @throws com.mendix.core.CoreException
	 */
	public final amazonbedrockconnector.proxies.FoundationModelLifecycle getFoundationModelLifecycle_FoundationModelSummary(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		amazonbedrockconnector.proxies.FoundationModelLifecycle result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.FoundationModelLifecycle_FoundationModelSummary.toString());
		if (identifier != null) {
			result = amazonbedrockconnector.proxies.FoundationModelLifecycle.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of FoundationModelLifecycle_FoundationModelSummary
	 * @param foundationmodellifecycle_foundationmodelsummary
	 */
	public final void setFoundationModelLifecycle_FoundationModelSummary(amazonbedrockconnector.proxies.FoundationModelLifecycle foundationmodellifecycle_foundationmodelsummary)
	{
		setFoundationModelLifecycle_FoundationModelSummary(getContext(), foundationmodellifecycle_foundationmodelsummary);
	}

	/**
	 * Set value of FoundationModelLifecycle_FoundationModelSummary
	 * @param context
	 * @param foundationmodellifecycle_foundationmodelsummary
	 */
	public final void setFoundationModelLifecycle_FoundationModelSummary(com.mendix.systemwideinterfaces.core.IContext context, amazonbedrockconnector.proxies.FoundationModelLifecycle foundationmodellifecycle_foundationmodelsummary)
	{
		if (foundationmodellifecycle_foundationmodelsummary == null) {
			getMendixObject().setValue(context, MemberNames.FoundationModelLifecycle_FoundationModelSummary.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.FoundationModelLifecycle_FoundationModelSummary.toString(), foundationmodellifecycle_foundationmodelsummary.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return foundationModelSummaryMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final amazonbedrockconnector.proxies.FoundationModelSummary that = (amazonbedrockconnector.proxies.FoundationModelSummary) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
