// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package amazonbedrockconnector.proxies;

/**
 * This entity contains details about whether a model version is available or deprecated.
 */
public class FoundationModelLifecycle implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject foundationModelLifecycleMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AmazonBedrockConnector.FoundationModelLifecycle";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Status("Status"),
		FoundationModelLifecycle_FoundationModelSummary("AmazonBedrockConnector.FoundationModelLifecycle_FoundationModelSummary");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public FoundationModelLifecycle(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected FoundationModelLifecycle(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject foundationModelLifecycleMendixObject)
	{
		if (foundationModelLifecycleMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!foundationModelLifecycleMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.foundationModelLifecycleMendixObject = foundationModelLifecycleMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static amazonbedrockconnector.proxies.FoundationModelLifecycle initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new amazonbedrockconnector.proxies.FoundationModelLifecycle(context, mendixObject);
	}

	public static amazonbedrockconnector.proxies.FoundationModelLifecycle load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return amazonbedrockconnector.proxies.FoundationModelLifecycle.initialize(context, mendixObject);
	}

	/**
	 * Get value of Status
	 * @param status
	 */
	public final amazonbedrockconnector.proxies.ENUM_ModelLifecycleStatus getStatus()
	{
		return getStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of Status
	 */
	public final amazonbedrockconnector.proxies.ENUM_ModelLifecycleStatus getStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Status.toString());
		if (obj == null) {
			return null;
		}
		return amazonbedrockconnector.proxies.ENUM_ModelLifecycleStatus.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Status
	 * @param status
	 */
	public final void setStatus(amazonbedrockconnector.proxies.ENUM_ModelLifecycleStatus status)
	{
		setStatus(getContext(), status);
	}

	/**
	 * Set value of Status
	 * @param context
	 * @param status
	 */
	public final void setStatus(com.mendix.systemwideinterfaces.core.IContext context, amazonbedrockconnector.proxies.ENUM_ModelLifecycleStatus status)
	{
		if (status != null) {
			getMendixObject().setValue(context, MemberNames.Status.toString(), status.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.Status.toString(), null);
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of FoundationModelLifecycle_FoundationModelSummary
	 */
	public final amazonbedrockconnector.proxies.FoundationModelSummary getFoundationModelLifecycle_FoundationModelSummary() throws com.mendix.core.CoreException
	{
		return getFoundationModelLifecycle_FoundationModelSummary(getContext());
	}

	/**
	 * @param context
	 * @return value of FoundationModelLifecycle_FoundationModelSummary
	 * @throws com.mendix.core.CoreException
	 */
	public final amazonbedrockconnector.proxies.FoundationModelSummary getFoundationModelLifecycle_FoundationModelSummary(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		amazonbedrockconnector.proxies.FoundationModelSummary result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.FoundationModelLifecycle_FoundationModelSummary.toString());
		if (identifier != null) {
			result = amazonbedrockconnector.proxies.FoundationModelSummary.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of FoundationModelLifecycle_FoundationModelSummary
	 * @param foundationmodellifecycle_foundationmodelsummary
	 */
	public final void setFoundationModelLifecycle_FoundationModelSummary(amazonbedrockconnector.proxies.FoundationModelSummary foundationmodellifecycle_foundationmodelsummary)
	{
		setFoundationModelLifecycle_FoundationModelSummary(getContext(), foundationmodellifecycle_foundationmodelsummary);
	}

	/**
	 * Set value of FoundationModelLifecycle_FoundationModelSummary
	 * @param context
	 * @param foundationmodellifecycle_foundationmodelsummary
	 */
	public final void setFoundationModelLifecycle_FoundationModelSummary(com.mendix.systemwideinterfaces.core.IContext context, amazonbedrockconnector.proxies.FoundationModelSummary foundationmodellifecycle_foundationmodelsummary)
	{
		if (foundationmodellifecycle_foundationmodelsummary == null) {
			getMendixObject().setValue(context, MemberNames.FoundationModelLifecycle_FoundationModelSummary.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.FoundationModelLifecycle_FoundationModelSummary.toString(), foundationmodellifecycle_foundationmodelsummary.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return foundationModelLifecycleMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final amazonbedrockconnector.proxies.FoundationModelLifecycle that = (amazonbedrockconnector.proxies.FoundationModelLifecycle) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
