// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package amazonbedrockconnector.proxies;

/**
 * This entity is the request for the Amazon Bedrock GetDataSource action.
 * 
 * API reference:
 * https://docs.aws.amazon.com/bedrock/latest/APIReference/API_agent_GetDataSource.html
 * 
 * Java SDK documentation:
 * https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/bedrockagent/model/GetDataSourceRequest.html
 */
public class GetDataSourceRequest extends awsauthentication.proxies.AbstractRequest
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AmazonBedrockConnector.GetDataSourceRequest";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		DataSourceId("DataSourceId"),
		KnowledgeBaseId("KnowledgeBaseId"),
		AbstractRequest_BasicClientConfig("AWSAuthentication.AbstractRequest_BasicClientConfig");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public GetDataSourceRequest(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected GetDataSourceRequest(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject getDataSourceRequestMendixObject)
	{
		super(context, getDataSourceRequestMendixObject);
		if (!getDataSourceRequestMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static amazonbedrockconnector.proxies.GetDataSourceRequest initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new amazonbedrockconnector.proxies.GetDataSourceRequest(context, mendixObject);
	}

	public static amazonbedrockconnector.proxies.GetDataSourceRequest load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return amazonbedrockconnector.proxies.GetDataSourceRequest.initialize(context, mendixObject);
	}

	/**
	 * @return value of DataSourceId
	 */
	public final java.lang.String getDataSourceId()
	{
		return getDataSourceId(getContext());
	}

	/**
	 * @param context
	 * @return value of DataSourceId
	 */
	public final java.lang.String getDataSourceId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DataSourceId.toString());
	}

	/**
	 * Set value of DataSourceId
	 * @param datasourceid
	 */
	public final void setDataSourceId(java.lang.String datasourceid)
	{
		setDataSourceId(getContext(), datasourceid);
	}

	/**
	 * Set value of DataSourceId
	 * @param context
	 * @param datasourceid
	 */
	public final void setDataSourceId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String datasourceid)
	{
		getMendixObject().setValue(context, MemberNames.DataSourceId.toString(), datasourceid);
	}

	/**
	 * @return value of KnowledgeBaseId
	 */
	public final java.lang.String getKnowledgeBaseId()
	{
		return getKnowledgeBaseId(getContext());
	}

	/**
	 * @param context
	 * @return value of KnowledgeBaseId
	 */
	public final java.lang.String getKnowledgeBaseId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.KnowledgeBaseId.toString());
	}

	/**
	 * Set value of KnowledgeBaseId
	 * @param knowledgebaseid
	 */
	public final void setKnowledgeBaseId(java.lang.String knowledgebaseid)
	{
		setKnowledgeBaseId(getContext(), knowledgebaseid);
	}

	/**
	 * Set value of KnowledgeBaseId
	 * @param context
	 * @param knowledgebaseid
	 */
	public final void setKnowledgeBaseId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String knowledgebaseid)
	{
		getMendixObject().setValue(context, MemberNames.KnowledgeBaseId.toString(), knowledgebaseid);
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final amazonbedrockconnector.proxies.GetDataSourceRequest that = (amazonbedrockconnector.proxies.GetDataSourceRequest) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
