// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package amazonbedrockconnector.proxies;

public class GetIngestionJob extends amazonbedrockconnector.proxies.IngestionJob
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AmazonBedrockConnector.GetIngestionJob";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Description("Description"),
		DataSourceId("DataSourceId"),
		IngestionJobId("IngestionJobId"),
		KnowledgeBaseId("KnowledgeBaseId"),
		Status("Status"),
		StartedAt("StartedAt"),
		UpdatedAt("UpdatedAt"),
		GetIngestionJob_GetIngestionJobResponse("AmazonBedrockConnector.GetIngestionJob_GetIngestionJobResponse"),
		IngestionJobStats_IngestionJob("AmazonBedrockConnector.IngestionJobStats_IngestionJob");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public GetIngestionJob(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected GetIngestionJob(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject getIngestionJobMendixObject)
	{
		super(context, getIngestionJobMendixObject);
		if (!getIngestionJobMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static amazonbedrockconnector.proxies.GetIngestionJob initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new amazonbedrockconnector.proxies.GetIngestionJob(context, mendixObject);
	}

	public static amazonbedrockconnector.proxies.GetIngestionJob load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return amazonbedrockconnector.proxies.GetIngestionJob.initialize(context, mendixObject);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of GetIngestionJob_GetIngestionJobResponse
	 */
	public final amazonbedrockconnector.proxies.GetIngestionJobResponse getGetIngestionJob_GetIngestionJobResponse() throws com.mendix.core.CoreException
	{
		return getGetIngestionJob_GetIngestionJobResponse(getContext());
	}

	/**
	 * @param context
	 * @return value of GetIngestionJob_GetIngestionJobResponse
	 * @throws com.mendix.core.CoreException
	 */
	public final amazonbedrockconnector.proxies.GetIngestionJobResponse getGetIngestionJob_GetIngestionJobResponse(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		amazonbedrockconnector.proxies.GetIngestionJobResponse result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.GetIngestionJob_GetIngestionJobResponse.toString());
		if (identifier != null) {
			result = amazonbedrockconnector.proxies.GetIngestionJobResponse.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of GetIngestionJob_GetIngestionJobResponse
	 * @param getingestionjob_getingestionjobresponse
	 */
	public final void setGetIngestionJob_GetIngestionJobResponse(amazonbedrockconnector.proxies.GetIngestionJobResponse getingestionjob_getingestionjobresponse)
	{
		setGetIngestionJob_GetIngestionJobResponse(getContext(), getingestionjob_getingestionjobresponse);
	}

	/**
	 * Set value of GetIngestionJob_GetIngestionJobResponse
	 * @param context
	 * @param getingestionjob_getingestionjobresponse
	 */
	public final void setGetIngestionJob_GetIngestionJobResponse(com.mendix.systemwideinterfaces.core.IContext context, amazonbedrockconnector.proxies.GetIngestionJobResponse getingestionjob_getingestionjobresponse)
	{
		if (getingestionjob_getingestionjobresponse == null) {
			getMendixObject().setValue(context, MemberNames.GetIngestionJob_GetIngestionJobResponse.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.GetIngestionJob_GetIngestionJobResponse.toString(), getingestionjob_getingestionjobresponse.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final amazonbedrockconnector.proxies.GetIngestionJob that = (amazonbedrockconnector.proxies.GetIngestionJob) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
