// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package amazonbedrockconnector.proxies;

/**
 * This entity is the response for the Amazon Bedrock GetIngestionJob action.
 * 
 * API reference:
 * https://docs.aws.amazon.com/bedrock/latest/APIReference/API_InvokeModel.html
 * 
 * Java SDK documentation:
 * https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/bedrockruntime/model/InvokeModelResponse.html
 */
public class GetIngestionJobResponse implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject getIngestionJobResponseMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AmazonBedrockConnector.GetIngestionJobResponse";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		GetIngestionJob_GetIngestionJobResponse("AmazonBedrockConnector.GetIngestionJob_GetIngestionJobResponse");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public GetIngestionJobResponse(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected GetIngestionJobResponse(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject getIngestionJobResponseMendixObject)
	{
		if (getIngestionJobResponseMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!getIngestionJobResponseMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.getIngestionJobResponseMendixObject = getIngestionJobResponseMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static amazonbedrockconnector.proxies.GetIngestionJobResponse initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new amazonbedrockconnector.proxies.GetIngestionJobResponse(context, mendixObject);
	}

	public static amazonbedrockconnector.proxies.GetIngestionJobResponse load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return amazonbedrockconnector.proxies.GetIngestionJobResponse.initialize(context, mendixObject);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of GetIngestionJob_GetIngestionJobResponse
	 */
	public final amazonbedrockconnector.proxies.GetIngestionJob getGetIngestionJob_GetIngestionJobResponse() throws com.mendix.core.CoreException
	{
		return getGetIngestionJob_GetIngestionJobResponse(getContext());
	}

	/**
	 * @param context
	 * @return value of GetIngestionJob_GetIngestionJobResponse
	 * @throws com.mendix.core.CoreException
	 */
	public final amazonbedrockconnector.proxies.GetIngestionJob getGetIngestionJob_GetIngestionJobResponse(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		amazonbedrockconnector.proxies.GetIngestionJob result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.GetIngestionJob_GetIngestionJobResponse.toString());
		if (identifier != null) {
			result = amazonbedrockconnector.proxies.GetIngestionJob.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of GetIngestionJob_GetIngestionJobResponse
	 * @param getingestionjob_getingestionjobresponse
	 */
	public final void setGetIngestionJob_GetIngestionJobResponse(amazonbedrockconnector.proxies.GetIngestionJob getingestionjob_getingestionjobresponse)
	{
		setGetIngestionJob_GetIngestionJobResponse(getContext(), getingestionjob_getingestionjobresponse);
	}

	/**
	 * Set value of GetIngestionJob_GetIngestionJobResponse
	 * @param context
	 * @param getingestionjob_getingestionjobresponse
	 */
	public final void setGetIngestionJob_GetIngestionJobResponse(com.mendix.systemwideinterfaces.core.IContext context, amazonbedrockconnector.proxies.GetIngestionJob getingestionjob_getingestionjobresponse)
	{
		if (getingestionjob_getingestionjobresponse == null) {
			getMendixObject().setValue(context, MemberNames.GetIngestionJob_GetIngestionJobResponse.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.GetIngestionJob_GetIngestionJobResponse.toString(), getingestionjob_getingestionjobresponse.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return getIngestionJobResponseMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final amazonbedrockconnector.proxies.GetIngestionJobResponse that = (amazonbedrockconnector.proxies.GetIngestionJobResponse) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
