// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package amazonbedrockconnector.proxies;

/**
 * This entity holds information about an IngestionJob.
 * 
 * API reference:
 * https://docs.aws.amazon.com/bedrock/latest/APIReference/API_agent-runtime_IngestionJob.html
 * 
 * Java SDK documentation:
 * https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/bedrockagentruntime/model/IngestionJob.html
 */
public class IngestionJob implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject ingestionJobMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AmazonBedrockConnector.IngestionJob";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Description("Description"),
		DataSourceId("DataSourceId"),
		IngestionJobId("IngestionJobId"),
		KnowledgeBaseId("KnowledgeBaseId"),
		Status("Status"),
		StartedAt("StartedAt"),
		UpdatedAt("UpdatedAt"),
		IngestionJobStats_IngestionJob("AmazonBedrockConnector.IngestionJobStats_IngestionJob");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public IngestionJob(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected IngestionJob(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject ingestionJobMendixObject)
	{
		if (ingestionJobMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!ingestionJobMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.ingestionJobMendixObject = ingestionJobMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static amazonbedrockconnector.proxies.IngestionJob initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		if (mendixObject.isInstanceOf("AmazonBedrockConnector.GetIngestionJob")) {
			return amazonbedrockconnector.proxies.GetIngestionJob.initialize(context, mendixObject);
		}
		if (mendixObject.isInstanceOf("AmazonBedrockConnector.IngestionJobSummary")) {
			return amazonbedrockconnector.proxies.IngestionJobSummary.initialize(context, mendixObject);
		}
		if (mendixObject.isInstanceOf("AmazonBedrockConnector.StartIngestionJob")) {
			return amazonbedrockconnector.proxies.StartIngestionJob.initialize(context, mendixObject);
		}
		return new amazonbedrockconnector.proxies.IngestionJob(context, mendixObject);
	}

	public static amazonbedrockconnector.proxies.IngestionJob load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return amazonbedrockconnector.proxies.IngestionJob.initialize(context, mendixObject);
	}

	/**
	 * @return value of Description
	 */
	public final java.lang.String getDescription()
	{
		return getDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of Description
	 */
	public final java.lang.String getDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Description.toString());
	}

	/**
	 * Set value of Description
	 * @param description
	 */
	public final void setDescription(java.lang.String description)
	{
		setDescription(getContext(), description);
	}

	/**
	 * Set value of Description
	 * @param context
	 * @param description
	 */
	public final void setDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String description)
	{
		getMendixObject().setValue(context, MemberNames.Description.toString(), description);
	}

	/**
	 * @return value of DataSourceId
	 */
	public final java.lang.String getDataSourceId()
	{
		return getDataSourceId(getContext());
	}

	/**
	 * @param context
	 * @return value of DataSourceId
	 */
	public final java.lang.String getDataSourceId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DataSourceId.toString());
	}

	/**
	 * Set value of DataSourceId
	 * @param datasourceid
	 */
	public final void setDataSourceId(java.lang.String datasourceid)
	{
		setDataSourceId(getContext(), datasourceid);
	}

	/**
	 * Set value of DataSourceId
	 * @param context
	 * @param datasourceid
	 */
	public final void setDataSourceId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String datasourceid)
	{
		getMendixObject().setValue(context, MemberNames.DataSourceId.toString(), datasourceid);
	}

	/**
	 * @return value of IngestionJobId
	 */
	public final java.lang.String getIngestionJobId()
	{
		return getIngestionJobId(getContext());
	}

	/**
	 * @param context
	 * @return value of IngestionJobId
	 */
	public final java.lang.String getIngestionJobId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.IngestionJobId.toString());
	}

	/**
	 * Set value of IngestionJobId
	 * @param ingestionjobid
	 */
	public final void setIngestionJobId(java.lang.String ingestionjobid)
	{
		setIngestionJobId(getContext(), ingestionjobid);
	}

	/**
	 * Set value of IngestionJobId
	 * @param context
	 * @param ingestionjobid
	 */
	public final void setIngestionJobId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String ingestionjobid)
	{
		getMendixObject().setValue(context, MemberNames.IngestionJobId.toString(), ingestionjobid);
	}

	/**
	 * @return value of KnowledgeBaseId
	 */
	public final java.lang.String getKnowledgeBaseId()
	{
		return getKnowledgeBaseId(getContext());
	}

	/**
	 * @param context
	 * @return value of KnowledgeBaseId
	 */
	public final java.lang.String getKnowledgeBaseId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.KnowledgeBaseId.toString());
	}

	/**
	 * Set value of KnowledgeBaseId
	 * @param knowledgebaseid
	 */
	public final void setKnowledgeBaseId(java.lang.String knowledgebaseid)
	{
		setKnowledgeBaseId(getContext(), knowledgebaseid);
	}

	/**
	 * Set value of KnowledgeBaseId
	 * @param context
	 * @param knowledgebaseid
	 */
	public final void setKnowledgeBaseId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String knowledgebaseid)
	{
		getMendixObject().setValue(context, MemberNames.KnowledgeBaseId.toString(), knowledgebaseid);
	}

	/**
	 * Get value of Status
	 * @param status
	 */
	public final amazonbedrockconnector.proxies.ENUM_IngestionJobStatus getStatus()
	{
		return getStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of Status
	 */
	public final amazonbedrockconnector.proxies.ENUM_IngestionJobStatus getStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Status.toString());
		if (obj == null) {
			return null;
		}
		return amazonbedrockconnector.proxies.ENUM_IngestionJobStatus.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Status
	 * @param status
	 */
	public final void setStatus(amazonbedrockconnector.proxies.ENUM_IngestionJobStatus status)
	{
		setStatus(getContext(), status);
	}

	/**
	 * Set value of Status
	 * @param context
	 * @param status
	 */
	public final void setStatus(com.mendix.systemwideinterfaces.core.IContext context, amazonbedrockconnector.proxies.ENUM_IngestionJobStatus status)
	{
		if (status != null) {
			getMendixObject().setValue(context, MemberNames.Status.toString(), status.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.Status.toString(), null);
		}
	}

	/**
	 * @return value of StartedAt
	 */
	public final java.util.Date getStartedAt()
	{
		return getStartedAt(getContext());
	}

	/**
	 * @param context
	 * @return value of StartedAt
	 */
	public final java.util.Date getStartedAt(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.StartedAt.toString());
	}

	/**
	 * Set value of StartedAt
	 * @param startedat
	 */
	public final void setStartedAt(java.util.Date startedat)
	{
		setStartedAt(getContext(), startedat);
	}

	/**
	 * Set value of StartedAt
	 * @param context
	 * @param startedat
	 */
	public final void setStartedAt(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date startedat)
	{
		getMendixObject().setValue(context, MemberNames.StartedAt.toString(), startedat);
	}

	/**
	 * @return value of UpdatedAt
	 */
	public final java.util.Date getUpdatedAt()
	{
		return getUpdatedAt(getContext());
	}

	/**
	 * @param context
	 * @return value of UpdatedAt
	 */
	public final java.util.Date getUpdatedAt(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.UpdatedAt.toString());
	}

	/**
	 * Set value of UpdatedAt
	 * @param updatedat
	 */
	public final void setUpdatedAt(java.util.Date updatedat)
	{
		setUpdatedAt(getContext(), updatedat);
	}

	/**
	 * Set value of UpdatedAt
	 * @param context
	 * @param updatedat
	 */
	public final void setUpdatedAt(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date updatedat)
	{
		getMendixObject().setValue(context, MemberNames.UpdatedAt.toString(), updatedat);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of IngestionJobStats_IngestionJob
	 */
	public final amazonbedrockconnector.proxies.IngestionJobStats getIngestionJobStats_IngestionJob() throws com.mendix.core.CoreException
	{
		return getIngestionJobStats_IngestionJob(getContext());
	}

	/**
	 * @param context
	 * @return value of IngestionJobStats_IngestionJob
	 * @throws com.mendix.core.CoreException
	 */
	public final amazonbedrockconnector.proxies.IngestionJobStats getIngestionJobStats_IngestionJob(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		amazonbedrockconnector.proxies.IngestionJobStats result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.IngestionJobStats_IngestionJob.toString());
		if (identifier != null) {
			result = amazonbedrockconnector.proxies.IngestionJobStats.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of IngestionJobStats_IngestionJob
	 * @param ingestionjobstats_ingestionjob
	 */
	public final void setIngestionJobStats_IngestionJob(amazonbedrockconnector.proxies.IngestionJobStats ingestionjobstats_ingestionjob)
	{
		setIngestionJobStats_IngestionJob(getContext(), ingestionjobstats_ingestionjob);
	}

	/**
	 * Set value of IngestionJobStats_IngestionJob
	 * @param context
	 * @param ingestionjobstats_ingestionjob
	 */
	public final void setIngestionJobStats_IngestionJob(com.mendix.systemwideinterfaces.core.IContext context, amazonbedrockconnector.proxies.IngestionJobStats ingestionjobstats_ingestionjob)
	{
		if (ingestionjobstats_ingestionjob == null) {
			getMendixObject().setValue(context, MemberNames.IngestionJobStats_IngestionJob.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.IngestionJobStats_IngestionJob.toString(), ingestionjobstats_ingestionjob.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return ingestionJobMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final amazonbedrockconnector.proxies.IngestionJob that = (amazonbedrockconnector.proxies.IngestionJob) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
