// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package amazonbedrockconnector.proxies;

public class IngestionJobSummary extends amazonbedrockconnector.proxies.IngestionJob
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AmazonBedrockConnector.IngestionJobSummary";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Description("Description"),
		DataSourceId("DataSourceId"),
		IngestionJobId("IngestionJobId"),
		KnowledgeBaseId("KnowledgeBaseId"),
		Status("Status"),
		StartedAt("StartedAt"),
		UpdatedAt("UpdatedAt"),
		IngestionJobSummary_ListIngestionJobsResponse("AmazonBedrockConnector.IngestionJobSummary_ListIngestionJobsResponse"),
		IngestionJobStats_IngestionJob("AmazonBedrockConnector.IngestionJobStats_IngestionJob");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public IngestionJobSummary(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected IngestionJobSummary(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject ingestionJobSummaryMendixObject)
	{
		super(context, ingestionJobSummaryMendixObject);
		if (!ingestionJobSummaryMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static amazonbedrockconnector.proxies.IngestionJobSummary initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new amazonbedrockconnector.proxies.IngestionJobSummary(context, mendixObject);
	}

	public static amazonbedrockconnector.proxies.IngestionJobSummary load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return amazonbedrockconnector.proxies.IngestionJobSummary.initialize(context, mendixObject);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of IngestionJobSummary_ListIngestionJobsResponse
	 */
	public final amazonbedrockconnector.proxies.ListIngestionJobsResponse getIngestionJobSummary_ListIngestionJobsResponse() throws com.mendix.core.CoreException
	{
		return getIngestionJobSummary_ListIngestionJobsResponse(getContext());
	}

	/**
	 * @param context
	 * @return value of IngestionJobSummary_ListIngestionJobsResponse
	 * @throws com.mendix.core.CoreException
	 */
	public final amazonbedrockconnector.proxies.ListIngestionJobsResponse getIngestionJobSummary_ListIngestionJobsResponse(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		amazonbedrockconnector.proxies.ListIngestionJobsResponse result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.IngestionJobSummary_ListIngestionJobsResponse.toString());
		if (identifier != null) {
			result = amazonbedrockconnector.proxies.ListIngestionJobsResponse.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of IngestionJobSummary_ListIngestionJobsResponse
	 * @param ingestionjobsummary_listingestionjobsresponse
	 */
	public final void setIngestionJobSummary_ListIngestionJobsResponse(amazonbedrockconnector.proxies.ListIngestionJobsResponse ingestionjobsummary_listingestionjobsresponse)
	{
		setIngestionJobSummary_ListIngestionJobsResponse(getContext(), ingestionjobsummary_listingestionjobsresponse);
	}

	/**
	 * Set value of IngestionJobSummary_ListIngestionJobsResponse
	 * @param context
	 * @param ingestionjobsummary_listingestionjobsresponse
	 */
	public final void setIngestionJobSummary_ListIngestionJobsResponse(com.mendix.systemwideinterfaces.core.IContext context, amazonbedrockconnector.proxies.ListIngestionJobsResponse ingestionjobsummary_listingestionjobsresponse)
	{
		if (ingestionjobsummary_listingestionjobsresponse == null) {
			getMendixObject().setValue(context, MemberNames.IngestionJobSummary_ListIngestionJobsResponse.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.IngestionJobSummary_ListIngestionJobsResponse.toString(), ingestionjobsummary_listingestionjobsresponse.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final amazonbedrockconnector.proxies.IngestionJobSummary that = (amazonbedrockconnector.proxies.IngestionJobSummary) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
