// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package amazonbedrockconnector.proxies;

/**
 * Contains information about the failure of the interaction.
 */
public class IngestionJobStats implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject ingestionJobStatsMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AmazonBedrockConnector.IngestionJobStats";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		numberOfDocumentsDeleted("numberOfDocumentsDeleted"),
		numberOfDocumentsFailed("numberOfDocumentsFailed"),
		numberOfDocumentsScanned("numberOfDocumentsScanned"),
		numberOfModifiedDocumentsIndexed("numberOfModifiedDocumentsIndexed"),
		numberOfNewDocumentsIndexed("numberOfNewDocumentsIndexed"),
		IngestionJobStats_IngestionJob("AmazonBedrockConnector.IngestionJobStats_IngestionJob");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public IngestionJobStats(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected IngestionJobStats(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject ingestionJobStatsMendixObject)
	{
		if (ingestionJobStatsMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!ingestionJobStatsMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.ingestionJobStatsMendixObject = ingestionJobStatsMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static amazonbedrockconnector.proxies.IngestionJobStats initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new amazonbedrockconnector.proxies.IngestionJobStats(context, mendixObject);
	}

	public static amazonbedrockconnector.proxies.IngestionJobStats load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return amazonbedrockconnector.proxies.IngestionJobStats.initialize(context, mendixObject);
	}

	/**
	 * @return value of numberOfDocumentsDeleted
	 */
	public final java.lang.Long getnumberOfDocumentsDeleted()
	{
		return getnumberOfDocumentsDeleted(getContext());
	}

	/**
	 * @param context
	 * @return value of numberOfDocumentsDeleted
	 */
	public final java.lang.Long getnumberOfDocumentsDeleted(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.numberOfDocumentsDeleted.toString());
	}

	/**
	 * Set value of numberOfDocumentsDeleted
	 * @param numberofdocumentsdeleted
	 */
	public final void setnumberOfDocumentsDeleted(java.lang.Long numberofdocumentsdeleted)
	{
		setnumberOfDocumentsDeleted(getContext(), numberofdocumentsdeleted);
	}

	/**
	 * Set value of numberOfDocumentsDeleted
	 * @param context
	 * @param numberofdocumentsdeleted
	 */
	public final void setnumberOfDocumentsDeleted(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long numberofdocumentsdeleted)
	{
		getMendixObject().setValue(context, MemberNames.numberOfDocumentsDeleted.toString(), numberofdocumentsdeleted);
	}

	/**
	 * @return value of numberOfDocumentsFailed
	 */
	public final java.lang.Long getnumberOfDocumentsFailed()
	{
		return getnumberOfDocumentsFailed(getContext());
	}

	/**
	 * @param context
	 * @return value of numberOfDocumentsFailed
	 */
	public final java.lang.Long getnumberOfDocumentsFailed(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.numberOfDocumentsFailed.toString());
	}

	/**
	 * Set value of numberOfDocumentsFailed
	 * @param numberofdocumentsfailed
	 */
	public final void setnumberOfDocumentsFailed(java.lang.Long numberofdocumentsfailed)
	{
		setnumberOfDocumentsFailed(getContext(), numberofdocumentsfailed);
	}

	/**
	 * Set value of numberOfDocumentsFailed
	 * @param context
	 * @param numberofdocumentsfailed
	 */
	public final void setnumberOfDocumentsFailed(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long numberofdocumentsfailed)
	{
		getMendixObject().setValue(context, MemberNames.numberOfDocumentsFailed.toString(), numberofdocumentsfailed);
	}

	/**
	 * @return value of numberOfDocumentsScanned
	 */
	public final java.lang.Long getnumberOfDocumentsScanned()
	{
		return getnumberOfDocumentsScanned(getContext());
	}

	/**
	 * @param context
	 * @return value of numberOfDocumentsScanned
	 */
	public final java.lang.Long getnumberOfDocumentsScanned(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.numberOfDocumentsScanned.toString());
	}

	/**
	 * Set value of numberOfDocumentsScanned
	 * @param numberofdocumentsscanned
	 */
	public final void setnumberOfDocumentsScanned(java.lang.Long numberofdocumentsscanned)
	{
		setnumberOfDocumentsScanned(getContext(), numberofdocumentsscanned);
	}

	/**
	 * Set value of numberOfDocumentsScanned
	 * @param context
	 * @param numberofdocumentsscanned
	 */
	public final void setnumberOfDocumentsScanned(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long numberofdocumentsscanned)
	{
		getMendixObject().setValue(context, MemberNames.numberOfDocumentsScanned.toString(), numberofdocumentsscanned);
	}

	/**
	 * @return value of numberOfModifiedDocumentsIndexed
	 */
	public final java.lang.Long getnumberOfModifiedDocumentsIndexed()
	{
		return getnumberOfModifiedDocumentsIndexed(getContext());
	}

	/**
	 * @param context
	 * @return value of numberOfModifiedDocumentsIndexed
	 */
	public final java.lang.Long getnumberOfModifiedDocumentsIndexed(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.numberOfModifiedDocumentsIndexed.toString());
	}

	/**
	 * Set value of numberOfModifiedDocumentsIndexed
	 * @param numberofmodifieddocumentsindexed
	 */
	public final void setnumberOfModifiedDocumentsIndexed(java.lang.Long numberofmodifieddocumentsindexed)
	{
		setnumberOfModifiedDocumentsIndexed(getContext(), numberofmodifieddocumentsindexed);
	}

	/**
	 * Set value of numberOfModifiedDocumentsIndexed
	 * @param context
	 * @param numberofmodifieddocumentsindexed
	 */
	public final void setnumberOfModifiedDocumentsIndexed(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long numberofmodifieddocumentsindexed)
	{
		getMendixObject().setValue(context, MemberNames.numberOfModifiedDocumentsIndexed.toString(), numberofmodifieddocumentsindexed);
	}

	/**
	 * @return value of numberOfNewDocumentsIndexed
	 */
	public final java.lang.Long getnumberOfNewDocumentsIndexed()
	{
		return getnumberOfNewDocumentsIndexed(getContext());
	}

	/**
	 * @param context
	 * @return value of numberOfNewDocumentsIndexed
	 */
	public final java.lang.Long getnumberOfNewDocumentsIndexed(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.numberOfNewDocumentsIndexed.toString());
	}

	/**
	 * Set value of numberOfNewDocumentsIndexed
	 * @param numberofnewdocumentsindexed
	 */
	public final void setnumberOfNewDocumentsIndexed(java.lang.Long numberofnewdocumentsindexed)
	{
		setnumberOfNewDocumentsIndexed(getContext(), numberofnewdocumentsindexed);
	}

	/**
	 * Set value of numberOfNewDocumentsIndexed
	 * @param context
	 * @param numberofnewdocumentsindexed
	 */
	public final void setnumberOfNewDocumentsIndexed(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long numberofnewdocumentsindexed)
	{
		getMendixObject().setValue(context, MemberNames.numberOfNewDocumentsIndexed.toString(), numberofnewdocumentsindexed);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of IngestionJobStats_IngestionJob
	 */
	public final amazonbedrockconnector.proxies.IngestionJob getIngestionJobStats_IngestionJob() throws com.mendix.core.CoreException
	{
		return getIngestionJobStats_IngestionJob(getContext());
	}

	/**
	 * @param context
	 * @return value of IngestionJobStats_IngestionJob
	 * @throws com.mendix.core.CoreException
	 */
	public final amazonbedrockconnector.proxies.IngestionJob getIngestionJobStats_IngestionJob(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		amazonbedrockconnector.proxies.IngestionJob result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.IngestionJobStats_IngestionJob.toString());
		if (identifier != null) {
			result = amazonbedrockconnector.proxies.IngestionJob.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of IngestionJobStats_IngestionJob
	 * @param ingestionjobstats_ingestionjob
	 */
	public final void setIngestionJobStats_IngestionJob(amazonbedrockconnector.proxies.IngestionJob ingestionjobstats_ingestionjob)
	{
		setIngestionJobStats_IngestionJob(getContext(), ingestionjobstats_ingestionjob);
	}

	/**
	 * Set value of IngestionJobStats_IngestionJob
	 * @param context
	 * @param ingestionjobstats_ingestionjob
	 */
	public final void setIngestionJobStats_IngestionJob(com.mendix.systemwideinterfaces.core.IContext context, amazonbedrockconnector.proxies.IngestionJob ingestionjobstats_ingestionjob)
	{
		if (ingestionjobstats_ingestionjob == null) {
			getMendixObject().setValue(context, MemberNames.IngestionJobStats_IngestionJob.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.IngestionJobStats_IngestionJob.toString(), ingestionjobstats_ingestionjob.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return ingestionJobStatsMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final amazonbedrockconnector.proxies.IngestionJobStats that = (amazonbedrockconnector.proxies.IngestionJobStats) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
