// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package amazonbedrockconnector.proxies;

/**
 * The Citation entitiy contains a segment of the generated response that is based on a source in the knowledge base, alongside information about the source.
 * 
 * See also:
 * 
 * API Reference:
 * https://docs.aws.amazon.com/bedrock/latest/APIReference/API_agent-runtime_Citation.html
 * 
 * Java SDK Documentation:
 * https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/bedrockagentruntime/model/Citation.html
 */
public class InvokeAgentCitation extends amazonbedrockconnector.proxies.Citation
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AmazonBedrockConnector.InvokeAgentCitation";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		InvokeAgentCitation_InvokeAgentResponse("AmazonBedrockConnector.InvokeAgentCitation_InvokeAgentResponse"),
		GeneratedResponsePart_Citation("AmazonBedrockConnector.GeneratedResponsePart_Citation");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public InvokeAgentCitation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected InvokeAgentCitation(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject invokeAgentCitationMendixObject)
	{
		super(context, invokeAgentCitationMendixObject);
		if (!invokeAgentCitationMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static amazonbedrockconnector.proxies.InvokeAgentCitation initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new amazonbedrockconnector.proxies.InvokeAgentCitation(context, mendixObject);
	}

	public static amazonbedrockconnector.proxies.InvokeAgentCitation load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return amazonbedrockconnector.proxies.InvokeAgentCitation.initialize(context, mendixObject);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of InvokeAgentCitation_InvokeAgentResponse
	 */
	public final amazonbedrockconnector.proxies.InvokeAgentResponse getInvokeAgentCitation_InvokeAgentResponse() throws com.mendix.core.CoreException
	{
		return getInvokeAgentCitation_InvokeAgentResponse(getContext());
	}

	/**
	 * @param context
	 * @return value of InvokeAgentCitation_InvokeAgentResponse
	 * @throws com.mendix.core.CoreException
	 */
	public final amazonbedrockconnector.proxies.InvokeAgentResponse getInvokeAgentCitation_InvokeAgentResponse(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		amazonbedrockconnector.proxies.InvokeAgentResponse result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.InvokeAgentCitation_InvokeAgentResponse.toString());
		if (identifier != null) {
			result = amazonbedrockconnector.proxies.InvokeAgentResponse.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of InvokeAgentCitation_InvokeAgentResponse
	 * @param invokeagentcitation_invokeagentresponse
	 */
	public final void setInvokeAgentCitation_InvokeAgentResponse(amazonbedrockconnector.proxies.InvokeAgentResponse invokeagentcitation_invokeagentresponse)
	{
		setInvokeAgentCitation_InvokeAgentResponse(getContext(), invokeagentcitation_invokeagentresponse);
	}

	/**
	 * Set value of InvokeAgentCitation_InvokeAgentResponse
	 * @param context
	 * @param invokeagentcitation_invokeagentresponse
	 */
	public final void setInvokeAgentCitation_InvokeAgentResponse(com.mendix.systemwideinterfaces.core.IContext context, amazonbedrockconnector.proxies.InvokeAgentResponse invokeagentcitation_invokeagentresponse)
	{
		if (invokeagentcitation_invokeagentresponse == null) {
			getMendixObject().setValue(context, MemberNames.InvokeAgentCitation_InvokeAgentResponse.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.InvokeAgentCitation_InvokeAgentResponse.toString(), invokeagentcitation_invokeagentresponse.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final amazonbedrockconnector.proxies.InvokeAgentCitation that = (amazonbedrockconnector.proxies.InvokeAgentCitation) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
