// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package amazonbedrockconnector.proxies;

/**
 * Contains information pertaining to the action group or knowledge base that is being invoked.
 * 
 * See also:
 * 
 * API Reference:
 * https://docs.aws.amazon.com/bedrock/latest/APIReference/API_agent-runtime_InvocationInput.html
 * 
 * Java SDK Documentation:
 * https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/bedrockagentruntime/model/InvocationInput.html
 */
public class InvocationInput extends amazonbedrockconnector.proxies.AbstractTrace
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AmazonBedrockConnector.InvocationInput";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		InvocationType("InvocationType"),
		TraceId("TraceId"),
		TraceType("TraceType"),
		ActionGroupInvocationInput_InvocationInput("AmazonBedrockConnector.ActionGroupInvocationInput_InvocationInput"),
		KnowledgeBaseLookupInput_InvocationInput("AmazonBedrockConnector.KnowledgeBaseLookupInput_InvocationInput"),
		AbstractTrace_TracePart("AmazonBedrockConnector.AbstractTrace_TracePart");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public InvocationInput(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected InvocationInput(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject invocationInputMendixObject)
	{
		super(context, invocationInputMendixObject);
		if (!invocationInputMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static amazonbedrockconnector.proxies.InvocationInput initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new amazonbedrockconnector.proxies.InvocationInput(context, mendixObject);
	}

	public static amazonbedrockconnector.proxies.InvocationInput load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return amazonbedrockconnector.proxies.InvocationInput.initialize(context, mendixObject);
	}

	/**
	 * Get value of InvocationType
	 * @param invocationtype
	 */
	public final amazonbedrockconnector.proxies.ENUM_InvocationType getInvocationType()
	{
		return getInvocationType(getContext());
	}

	/**
	 * @param context
	 * @return value of InvocationType
	 */
	public final amazonbedrockconnector.proxies.ENUM_InvocationType getInvocationType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.InvocationType.toString());
		if (obj == null) {
			return null;
		}
		return amazonbedrockconnector.proxies.ENUM_InvocationType.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of InvocationType
	 * @param invocationtype
	 */
	public final void setInvocationType(amazonbedrockconnector.proxies.ENUM_InvocationType invocationtype)
	{
		setInvocationType(getContext(), invocationtype);
	}

	/**
	 * Set value of InvocationType
	 * @param context
	 * @param invocationtype
	 */
	public final void setInvocationType(com.mendix.systemwideinterfaces.core.IContext context, amazonbedrockconnector.proxies.ENUM_InvocationType invocationtype)
	{
		if (invocationtype != null) {
			getMendixObject().setValue(context, MemberNames.InvocationType.toString(), invocationtype.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.InvocationType.toString(), null);
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ActionGroupInvocationInput_InvocationInput
	 */
	public final amazonbedrockconnector.proxies.ActionGroupInvocationInput getActionGroupInvocationInput_InvocationInput() throws com.mendix.core.CoreException
	{
		return getActionGroupInvocationInput_InvocationInput(getContext());
	}

	/**
	 * @param context
	 * @return value of ActionGroupInvocationInput_InvocationInput
	 * @throws com.mendix.core.CoreException
	 */
	public final amazonbedrockconnector.proxies.ActionGroupInvocationInput getActionGroupInvocationInput_InvocationInput(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		amazonbedrockconnector.proxies.ActionGroupInvocationInput result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ActionGroupInvocationInput_InvocationInput.toString());
		if (identifier != null) {
			result = amazonbedrockconnector.proxies.ActionGroupInvocationInput.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ActionGroupInvocationInput_InvocationInput
	 * @param actiongroupinvocationinput_invocationinput
	 */
	public final void setActionGroupInvocationInput_InvocationInput(amazonbedrockconnector.proxies.ActionGroupInvocationInput actiongroupinvocationinput_invocationinput)
	{
		setActionGroupInvocationInput_InvocationInput(getContext(), actiongroupinvocationinput_invocationinput);
	}

	/**
	 * Set value of ActionGroupInvocationInput_InvocationInput
	 * @param context
	 * @param actiongroupinvocationinput_invocationinput
	 */
	public final void setActionGroupInvocationInput_InvocationInput(com.mendix.systemwideinterfaces.core.IContext context, amazonbedrockconnector.proxies.ActionGroupInvocationInput actiongroupinvocationinput_invocationinput)
	{
		if (actiongroupinvocationinput_invocationinput == null) {
			getMendixObject().setValue(context, MemberNames.ActionGroupInvocationInput_InvocationInput.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ActionGroupInvocationInput_InvocationInput.toString(), actiongroupinvocationinput_invocationinput.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of KnowledgeBaseLookupInput_InvocationInput
	 */
	public final amazonbedrockconnector.proxies.KnowledgeBaseLookupInput getKnowledgeBaseLookupInput_InvocationInput() throws com.mendix.core.CoreException
	{
		return getKnowledgeBaseLookupInput_InvocationInput(getContext());
	}

	/**
	 * @param context
	 * @return value of KnowledgeBaseLookupInput_InvocationInput
	 * @throws com.mendix.core.CoreException
	 */
	public final amazonbedrockconnector.proxies.KnowledgeBaseLookupInput getKnowledgeBaseLookupInput_InvocationInput(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		amazonbedrockconnector.proxies.KnowledgeBaseLookupInput result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.KnowledgeBaseLookupInput_InvocationInput.toString());
		if (identifier != null) {
			result = amazonbedrockconnector.proxies.KnowledgeBaseLookupInput.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of KnowledgeBaseLookupInput_InvocationInput
	 * @param knowledgebaselookupinput_invocationinput
	 */
	public final void setKnowledgeBaseLookupInput_InvocationInput(amazonbedrockconnector.proxies.KnowledgeBaseLookupInput knowledgebaselookupinput_invocationinput)
	{
		setKnowledgeBaseLookupInput_InvocationInput(getContext(), knowledgebaselookupinput_invocationinput);
	}

	/**
	 * Set value of KnowledgeBaseLookupInput_InvocationInput
	 * @param context
	 * @param knowledgebaselookupinput_invocationinput
	 */
	public final void setKnowledgeBaseLookupInput_InvocationInput(com.mendix.systemwideinterfaces.core.IContext context, amazonbedrockconnector.proxies.KnowledgeBaseLookupInput knowledgebaselookupinput_invocationinput)
	{
		if (knowledgebaselookupinput_invocationinput == null) {
			getMendixObject().setValue(context, MemberNames.KnowledgeBaseLookupInput_InvocationInput.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.KnowledgeBaseLookupInput_InvocationInput.toString(), knowledgebaselookupinput_invocationinput.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final amazonbedrockconnector.proxies.InvocationInput that = (amazonbedrockconnector.proxies.InvocationInput) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
