// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package amazonbedrockconnector.proxies;

/**
 * The request body to invoke the agent.
 * 
 * See also:
 * 
 * API Reference:
 * https://docs.aws.amazon.com/bedrock/latest/APIReference/API_agent-runtime_InvokeAgent.html#API_agent-runtime_InvokeAgent_RequestSyntax
 * 
 * Java SDK Documentation:
 * https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/bedrockagentruntime/model/InvokeAgentRequest.html
 */
public class InvokeAgentRequest extends awsauthentication.proxies.AbstractRequest
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AmazonBedrockConnector.InvokeAgentRequest";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		InputText("InputText"),
		AgentId("AgentId"),
		AgentAliasId("AgentAliasId"),
		SessionId("SessionId"),
		EnableTrace("EnableTrace"),
		EndSession("EndSession"),
		SessionState_InvokeAgentRequest("AmazonBedrockConnector.SessionState_InvokeAgentRequest"),
		AbstractRequest_BasicClientConfig("AWSAuthentication.AbstractRequest_BasicClientConfig");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public InvokeAgentRequest(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected InvokeAgentRequest(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject invokeAgentRequestMendixObject)
	{
		super(context, invokeAgentRequestMendixObject);
		if (!invokeAgentRequestMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static amazonbedrockconnector.proxies.InvokeAgentRequest initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new amazonbedrockconnector.proxies.InvokeAgentRequest(context, mendixObject);
	}

	public static amazonbedrockconnector.proxies.InvokeAgentRequest load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return amazonbedrockconnector.proxies.InvokeAgentRequest.initialize(context, mendixObject);
	}

	/**
	 * @return value of InputText
	 */
	public final java.lang.String getInputText()
	{
		return getInputText(getContext());
	}

	/**
	 * @param context
	 * @return value of InputText
	 */
	public final java.lang.String getInputText(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.InputText.toString());
	}

	/**
	 * Set value of InputText
	 * @param inputtext
	 */
	public final void setInputText(java.lang.String inputtext)
	{
		setInputText(getContext(), inputtext);
	}

	/**
	 * Set value of InputText
	 * @param context
	 * @param inputtext
	 */
	public final void setInputText(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String inputtext)
	{
		getMendixObject().setValue(context, MemberNames.InputText.toString(), inputtext);
	}

	/**
	 * @return value of AgentId
	 */
	public final java.lang.String getAgentId()
	{
		return getAgentId(getContext());
	}

	/**
	 * @param context
	 * @return value of AgentId
	 */
	public final java.lang.String getAgentId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.AgentId.toString());
	}

	/**
	 * Set value of AgentId
	 * @param agentid
	 */
	public final void setAgentId(java.lang.String agentid)
	{
		setAgentId(getContext(), agentid);
	}

	/**
	 * Set value of AgentId
	 * @param context
	 * @param agentid
	 */
	public final void setAgentId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String agentid)
	{
		getMendixObject().setValue(context, MemberNames.AgentId.toString(), agentid);
	}

	/**
	 * @return value of AgentAliasId
	 */
	public final java.lang.String getAgentAliasId()
	{
		return getAgentAliasId(getContext());
	}

	/**
	 * @param context
	 * @return value of AgentAliasId
	 */
	public final java.lang.String getAgentAliasId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.AgentAliasId.toString());
	}

	/**
	 * Set value of AgentAliasId
	 * @param agentaliasid
	 */
	public final void setAgentAliasId(java.lang.String agentaliasid)
	{
		setAgentAliasId(getContext(), agentaliasid);
	}

	/**
	 * Set value of AgentAliasId
	 * @param context
	 * @param agentaliasid
	 */
	public final void setAgentAliasId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String agentaliasid)
	{
		getMendixObject().setValue(context, MemberNames.AgentAliasId.toString(), agentaliasid);
	}

	/**
	 * @return value of SessionId
	 */
	public final java.lang.String getSessionId()
	{
		return getSessionId(getContext());
	}

	/**
	 * @param context
	 * @return value of SessionId
	 */
	public final java.lang.String getSessionId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SessionId.toString());
	}

	/**
	 * Set value of SessionId
	 * @param sessionid
	 */
	public final void setSessionId(java.lang.String sessionid)
	{
		setSessionId(getContext(), sessionid);
	}

	/**
	 * Set value of SessionId
	 * @param context
	 * @param sessionid
	 */
	public final void setSessionId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String sessionid)
	{
		getMendixObject().setValue(context, MemberNames.SessionId.toString(), sessionid);
	}

	/**
	 * @return value of EnableTrace
	 */
	public final java.lang.Boolean getEnableTrace()
	{
		return getEnableTrace(getContext());
	}

	/**
	 * @param context
	 * @return value of EnableTrace
	 */
	public final java.lang.Boolean getEnableTrace(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.EnableTrace.toString());
	}

	/**
	 * Set value of EnableTrace
	 * @param enabletrace
	 */
	public final void setEnableTrace(java.lang.Boolean enabletrace)
	{
		setEnableTrace(getContext(), enabletrace);
	}

	/**
	 * Set value of EnableTrace
	 * @param context
	 * @param enabletrace
	 */
	public final void setEnableTrace(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean enabletrace)
	{
		getMendixObject().setValue(context, MemberNames.EnableTrace.toString(), enabletrace);
	}

	/**
	 * @return value of EndSession
	 */
	public final java.lang.Boolean getEndSession()
	{
		return getEndSession(getContext());
	}

	/**
	 * @param context
	 * @return value of EndSession
	 */
	public final java.lang.Boolean getEndSession(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.EndSession.toString());
	}

	/**
	 * Set value of EndSession
	 * @param endsession
	 */
	public final void setEndSession(java.lang.Boolean endsession)
	{
		setEndSession(getContext(), endsession);
	}

	/**
	 * Set value of EndSession
	 * @param context
	 * @param endsession
	 */
	public final void setEndSession(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean endsession)
	{
		getMendixObject().setValue(context, MemberNames.EndSession.toString(), endsession);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of SessionState_InvokeAgentRequest
	 */
	public final amazonbedrockconnector.proxies.SessionState getSessionState_InvokeAgentRequest() throws com.mendix.core.CoreException
	{
		return getSessionState_InvokeAgentRequest(getContext());
	}

	/**
	 * @param context
	 * @return value of SessionState_InvokeAgentRequest
	 * @throws com.mendix.core.CoreException
	 */
	public final amazonbedrockconnector.proxies.SessionState getSessionState_InvokeAgentRequest(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		amazonbedrockconnector.proxies.SessionState result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.SessionState_InvokeAgentRequest.toString());
		if (identifier != null) {
			result = amazonbedrockconnector.proxies.SessionState.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of SessionState_InvokeAgentRequest
	 * @param sessionstate_invokeagentrequest
	 */
	public final void setSessionState_InvokeAgentRequest(amazonbedrockconnector.proxies.SessionState sessionstate_invokeagentrequest)
	{
		setSessionState_InvokeAgentRequest(getContext(), sessionstate_invokeagentrequest);
	}

	/**
	 * Set value of SessionState_InvokeAgentRequest
	 * @param context
	 * @param sessionstate_invokeagentrequest
	 */
	public final void setSessionState_InvokeAgentRequest(com.mendix.systemwideinterfaces.core.IContext context, amazonbedrockconnector.proxies.SessionState sessionstate_invokeagentrequest)
	{
		if (sessionstate_invokeagentrequest == null) {
			getMendixObject().setValue(context, MemberNames.SessionState_InvokeAgentRequest.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.SessionState_InvokeAgentRequest.toString(), sessionstate_invokeagentrequest.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final amazonbedrockconnector.proxies.InvokeAgentRequest that = (amazonbedrockconnector.proxies.InvokeAgentRequest) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
