// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package amazonbedrockconnector.proxies;

/**
 * Contains details about the knowledge base to look up and the query to be made.
 * 
 * See also:
 * 
 * API Reference:
 * https://docs.aws.amazon.com/bedrock/latest/APIReference/API_agent-runtime_KnowledgeBaseLookupInput.html
 * 
 * Java SDK Documentation:
 * https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/bedrockagentruntime/model/KnowledgeBaseLookupInput.html
 */
public class KnowledgeBaseLookupInput implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject knowledgeBaseLookupInputMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AmazonBedrockConnector.KnowledgeBaseLookupInput";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		KnowledgeBaseId("KnowledgeBaseId"),
		Text("Text"),
		KnowledgeBaseLookupInput_InvocationInput("AmazonBedrockConnector.KnowledgeBaseLookupInput_InvocationInput");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public KnowledgeBaseLookupInput(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected KnowledgeBaseLookupInput(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject knowledgeBaseLookupInputMendixObject)
	{
		if (knowledgeBaseLookupInputMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!knowledgeBaseLookupInputMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.knowledgeBaseLookupInputMendixObject = knowledgeBaseLookupInputMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static amazonbedrockconnector.proxies.KnowledgeBaseLookupInput initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new amazonbedrockconnector.proxies.KnowledgeBaseLookupInput(context, mendixObject);
	}

	public static amazonbedrockconnector.proxies.KnowledgeBaseLookupInput load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return amazonbedrockconnector.proxies.KnowledgeBaseLookupInput.initialize(context, mendixObject);
	}

	/**
	 * @return value of KnowledgeBaseId
	 */
	public final java.lang.String getKnowledgeBaseId()
	{
		return getKnowledgeBaseId(getContext());
	}

	/**
	 * @param context
	 * @return value of KnowledgeBaseId
	 */
	public final java.lang.String getKnowledgeBaseId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.KnowledgeBaseId.toString());
	}

	/**
	 * Set value of KnowledgeBaseId
	 * @param knowledgebaseid
	 */
	public final void setKnowledgeBaseId(java.lang.String knowledgebaseid)
	{
		setKnowledgeBaseId(getContext(), knowledgebaseid);
	}

	/**
	 * Set value of KnowledgeBaseId
	 * @param context
	 * @param knowledgebaseid
	 */
	public final void setKnowledgeBaseId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String knowledgebaseid)
	{
		getMendixObject().setValue(context, MemberNames.KnowledgeBaseId.toString(), knowledgebaseid);
	}

	/**
	 * @return value of Text
	 */
	public final java.lang.String getText()
	{
		return getText(getContext());
	}

	/**
	 * @param context
	 * @return value of Text
	 */
	public final java.lang.String getText(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Text.toString());
	}

	/**
	 * Set value of Text
	 * @param text
	 */
	public final void setText(java.lang.String text)
	{
		setText(getContext(), text);
	}

	/**
	 * Set value of Text
	 * @param context
	 * @param text
	 */
	public final void setText(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String text)
	{
		getMendixObject().setValue(context, MemberNames.Text.toString(), text);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of KnowledgeBaseLookupInput_InvocationInput
	 */
	public final amazonbedrockconnector.proxies.InvocationInput getKnowledgeBaseLookupInput_InvocationInput() throws com.mendix.core.CoreException
	{
		return getKnowledgeBaseLookupInput_InvocationInput(getContext());
	}

	/**
	 * @param context
	 * @return value of KnowledgeBaseLookupInput_InvocationInput
	 * @throws com.mendix.core.CoreException
	 */
	public final amazonbedrockconnector.proxies.InvocationInput getKnowledgeBaseLookupInput_InvocationInput(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		amazonbedrockconnector.proxies.InvocationInput result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.KnowledgeBaseLookupInput_InvocationInput.toString());
		if (identifier != null) {
			result = amazonbedrockconnector.proxies.InvocationInput.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of KnowledgeBaseLookupInput_InvocationInput
	 * @param knowledgebaselookupinput_invocationinput
	 */
	public final void setKnowledgeBaseLookupInput_InvocationInput(amazonbedrockconnector.proxies.InvocationInput knowledgebaselookupinput_invocationinput)
	{
		setKnowledgeBaseLookupInput_InvocationInput(getContext(), knowledgebaselookupinput_invocationinput);
	}

	/**
	 * Set value of KnowledgeBaseLookupInput_InvocationInput
	 * @param context
	 * @param knowledgebaselookupinput_invocationinput
	 */
	public final void setKnowledgeBaseLookupInput_InvocationInput(com.mendix.systemwideinterfaces.core.IContext context, amazonbedrockconnector.proxies.InvocationInput knowledgebaselookupinput_invocationinput)
	{
		if (knowledgebaselookupinput_invocationinput == null) {
			getMendixObject().setValue(context, MemberNames.KnowledgeBaseLookupInput_InvocationInput.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.KnowledgeBaseLookupInput_InvocationInput.toString(), knowledgebaselookupinput_invocationinput.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return knowledgeBaseLookupInputMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final amazonbedrockconnector.proxies.KnowledgeBaseLookupInput that = (amazonbedrockconnector.proxies.KnowledgeBaseLookupInput) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
