// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package amazonbedrockconnector.proxies;

/**
 * This entity is the request for the Amazon Bedrock ListKnowledgeBases action.
 * 
 * API reference:
 * https://docs.aws.amazon.com/bedrock/latest/APIReference/API_agent_ListKnowledgeBases.html
 * 
 * Java SDK documentation:
 * https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/bedrockagent/model/ListKnowledgeBasesRequest.html
 */
public class ListKnowledgeBasesRequest extends awsauthentication.proxies.AbstractRequest
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AmazonBedrockConnector.ListKnowledgeBasesRequest";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		MaxResults("MaxResults"),
		NextToken("NextToken"),
		AbstractRequest_BasicClientConfig("AWSAuthentication.AbstractRequest_BasicClientConfig");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ListKnowledgeBasesRequest(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ListKnowledgeBasesRequest(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject listKnowledgeBasesRequestMendixObject)
	{
		super(context, listKnowledgeBasesRequestMendixObject);
		if (!listKnowledgeBasesRequestMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static amazonbedrockconnector.proxies.ListKnowledgeBasesRequest initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new amazonbedrockconnector.proxies.ListKnowledgeBasesRequest(context, mendixObject);
	}

	public static amazonbedrockconnector.proxies.ListKnowledgeBasesRequest load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return amazonbedrockconnector.proxies.ListKnowledgeBasesRequest.initialize(context, mendixObject);
	}

	/**
	 * @return value of MaxResults
	 */
	public final java.lang.Integer getMaxResults()
	{
		return getMaxResults(getContext());
	}

	/**
	 * @param context
	 * @return value of MaxResults
	 */
	public final java.lang.Integer getMaxResults(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.MaxResults.toString());
	}

	/**
	 * Set value of MaxResults
	 * @param maxresults
	 */
	public final void setMaxResults(java.lang.Integer maxresults)
	{
		setMaxResults(getContext(), maxresults);
	}

	/**
	 * Set value of MaxResults
	 * @param context
	 * @param maxresults
	 */
	public final void setMaxResults(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer maxresults)
	{
		getMendixObject().setValue(context, MemberNames.MaxResults.toString(), maxresults);
	}

	/**
	 * @return value of NextToken
	 */
	public final java.lang.String getNextToken()
	{
		return getNextToken(getContext());
	}

	/**
	 * @param context
	 * @return value of NextToken
	 */
	public final java.lang.String getNextToken(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.NextToken.toString());
	}

	/**
	 * Set value of NextToken
	 * @param nexttoken
	 */
	public final void setNextToken(java.lang.String nexttoken)
	{
		setNextToken(getContext(), nexttoken);
	}

	/**
	 * Set value of NextToken
	 * @param context
	 * @param nexttoken
	 */
	public final void setNextToken(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String nexttoken)
	{
		getMendixObject().setValue(context, MemberNames.NextToken.toString(), nexttoken);
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final amazonbedrockconnector.proxies.ListKnowledgeBasesRequest that = (amazonbedrockconnector.proxies.ListKnowledgeBasesRequest) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
