// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package amazonbedrockconnector.proxies;

/**
 * This entity holds information about the location of the data source.
 * 
 * API reference:
 * https://docs.aws.amazon.com/bedrock/latest/APIReference/API_agent-runtime_RetrievalResultLocation.html
 * 
 * Java SDK documentation:
 * https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/bedrockagentruntime/model/RetrievalResultLocation.html
 */
public class Location implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject locationMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AmazonBedrockConnector.Location";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		DataSourceType("DataSourceType"),
		Location_S3Location("AmazonBedrockConnector.Location_S3Location"),
		WebLocation_Location("AmazonBedrockConnector.WebLocation_Location");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Location(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Location(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject locationMendixObject)
	{
		if (locationMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!locationMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.locationMendixObject = locationMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static amazonbedrockconnector.proxies.Location initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		if (mendixObject.isInstanceOf("AmazonBedrockConnector.ReferenceLocation")) {
			return amazonbedrockconnector.proxies.ReferenceLocation.initialize(context, mendixObject);
		}
		return new amazonbedrockconnector.proxies.Location(context, mendixObject);
	}

	public static amazonbedrockconnector.proxies.Location load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return amazonbedrockconnector.proxies.Location.initialize(context, mendixObject);
	}

	/**
	 * Get value of DataSourceType
	 * @param datasourcetype
	 */
	public final amazonbedrockconnector.proxies.ENUM_DataSourceType getDataSourceType()
	{
		return getDataSourceType(getContext());
	}

	/**
	 * @param context
	 * @return value of DataSourceType
	 */
	public final amazonbedrockconnector.proxies.ENUM_DataSourceType getDataSourceType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.DataSourceType.toString());
		if (obj == null) {
			return null;
		}
		return amazonbedrockconnector.proxies.ENUM_DataSourceType.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of DataSourceType
	 * @param datasourcetype
	 */
	public final void setDataSourceType(amazonbedrockconnector.proxies.ENUM_DataSourceType datasourcetype)
	{
		setDataSourceType(getContext(), datasourcetype);
	}

	/**
	 * Set value of DataSourceType
	 * @param context
	 * @param datasourcetype
	 */
	public final void setDataSourceType(com.mendix.systemwideinterfaces.core.IContext context, amazonbedrockconnector.proxies.ENUM_DataSourceType datasourcetype)
	{
		if (datasourcetype != null) {
			getMendixObject().setValue(context, MemberNames.DataSourceType.toString(), datasourcetype.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.DataSourceType.toString(), null);
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Location_S3Location
	 */
	public final amazonbedrockconnector.proxies.S3Location getLocation_S3Location() throws com.mendix.core.CoreException
	{
		return getLocation_S3Location(getContext());
	}

	/**
	 * @param context
	 * @return value of Location_S3Location
	 * @throws com.mendix.core.CoreException
	 */
	public final amazonbedrockconnector.proxies.S3Location getLocation_S3Location(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		amazonbedrockconnector.proxies.S3Location result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Location_S3Location.toString());
		if (identifier != null) {
			result = amazonbedrockconnector.proxies.S3Location.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Location_S3Location
	 * @param location_s3location
	 */
	public final void setLocation_S3Location(amazonbedrockconnector.proxies.S3Location location_s3location)
	{
		setLocation_S3Location(getContext(), location_s3location);
	}

	/**
	 * Set value of Location_S3Location
	 * @param context
	 * @param location_s3location
	 */
	public final void setLocation_S3Location(com.mendix.systemwideinterfaces.core.IContext context, amazonbedrockconnector.proxies.S3Location location_s3location)
	{
		if (location_s3location == null) {
			getMendixObject().setValue(context, MemberNames.Location_S3Location.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Location_S3Location.toString(), location_s3location.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of WebLocation_Location
	 */
	public final amazonbedrockconnector.proxies.WebLocation getWebLocation_Location() throws com.mendix.core.CoreException
	{
		return getWebLocation_Location(getContext());
	}

	/**
	 * @param context
	 * @return value of WebLocation_Location
	 * @throws com.mendix.core.CoreException
	 */
	public final amazonbedrockconnector.proxies.WebLocation getWebLocation_Location(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		amazonbedrockconnector.proxies.WebLocation result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.WebLocation_Location.toString());
		if (identifier != null) {
			result = amazonbedrockconnector.proxies.WebLocation.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of WebLocation_Location
	 * @param weblocation_location
	 */
	public final void setWebLocation_Location(amazonbedrockconnector.proxies.WebLocation weblocation_location)
	{
		setWebLocation_Location(getContext(), weblocation_location);
	}

	/**
	 * Set value of WebLocation_Location
	 * @param context
	 * @param weblocation_location
	 */
	public final void setWebLocation_Location(com.mendix.systemwideinterfaces.core.IContext context, amazonbedrockconnector.proxies.WebLocation weblocation_location)
	{
		if (weblocation_location == null) {
			getMendixObject().setValue(context, MemberNames.WebLocation_Location.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.WebLocation_Location.toString(), weblocation_location.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return locationMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final amazonbedrockconnector.proxies.Location that = (amazonbedrockconnector.proxies.Location) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
