// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package amazonbedrockconnector.proxies;

/**
 * This entity holds information about an InferenceType. 
 * 
 * This entity is used as part of the 'Sync Metadata' operations. 
 * InferenceType objects will be created when syncing models using the 'Sync Models' operation.
 */
public class ModelInferenceType implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject modelInferenceTypeMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AmazonBedrockConnector.ModelInferenceType";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		InferenceType("InferenceType");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ModelInferenceType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ModelInferenceType(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject modelInferenceTypeMendixObject)
	{
		if (modelInferenceTypeMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!modelInferenceTypeMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.modelInferenceTypeMendixObject = modelInferenceTypeMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static amazonbedrockconnector.proxies.ModelInferenceType initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new amazonbedrockconnector.proxies.ModelInferenceType(context, mendixObject);
	}

	public static amazonbedrockconnector.proxies.ModelInferenceType load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return amazonbedrockconnector.proxies.ModelInferenceType.initialize(context, mendixObject);
	}

	public static java.util.List<amazonbedrockconnector.proxies.ModelInferenceType> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> amazonbedrockconnector.proxies.ModelInferenceType.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Get value of InferenceType
	 * @param inferencetype
	 */
	public final amazonbedrockconnector.proxies.ENUM_InferenceType getInferenceType()
	{
		return getInferenceType(getContext());
	}

	/**
	 * @param context
	 * @return value of InferenceType
	 */
	public final amazonbedrockconnector.proxies.ENUM_InferenceType getInferenceType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.InferenceType.toString());
		if (obj == null) {
			return null;
		}
		return amazonbedrockconnector.proxies.ENUM_InferenceType.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of InferenceType
	 * @param inferencetype
	 */
	public final void setInferenceType(amazonbedrockconnector.proxies.ENUM_InferenceType inferencetype)
	{
		setInferenceType(getContext(), inferencetype);
	}

	/**
	 * Set value of InferenceType
	 * @param context
	 * @param inferencetype
	 */
	public final void setInferenceType(com.mendix.systemwideinterfaces.core.IContext context, amazonbedrockconnector.proxies.ENUM_InferenceType inferencetype)
	{
		if (inferencetype != null) {
			getMendixObject().setValue(context, MemberNames.InferenceType.toString(), inferencetype.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.InferenceType.toString(), null);
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return modelInferenceTypeMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final amazonbedrockconnector.proxies.ModelInferenceType that = (amazonbedrockconnector.proxies.ModelInferenceType) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
