// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package amazonbedrockconnector.proxies;

/**
 * Contains the result or output of an action group or knowledge base, or the response to the user.
 * 
 * See also:
 * 
 * API Reference:
 * https://docs.aws.amazon.com/bedrock/latest/APIReference/API_agent-runtime_Observation.html
 * 
 * Java SDK Documentation:
 * https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/bedrockagentruntime/model/Observation.html
 */
public class Observation extends amazonbedrockconnector.proxies.AbstractTrace
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AmazonBedrockConnector.Observation";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ActionGroupInvocationOutput("ActionGroupInvocationOutput"),
		FinalResponse("FinalResponse"),
		ObservationType("ObservationType"),
		TraceId("TraceId"),
		TraceType("TraceType"),
		RepromptResponse_Observation("AmazonBedrockConnector.RepromptResponse_Observation"),
		AbstractTrace_TracePart("AmazonBedrockConnector.AbstractTrace_TracePart");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Observation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Observation(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject observationMendixObject)
	{
		super(context, observationMendixObject);
		if (!observationMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static amazonbedrockconnector.proxies.Observation initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new amazonbedrockconnector.proxies.Observation(context, mendixObject);
	}

	public static amazonbedrockconnector.proxies.Observation load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return amazonbedrockconnector.proxies.Observation.initialize(context, mendixObject);
	}

	/**
	 * @return value of ActionGroupInvocationOutput
	 */
	public final java.lang.String getActionGroupInvocationOutput()
	{
		return getActionGroupInvocationOutput(getContext());
	}

	/**
	 * @param context
	 * @return value of ActionGroupInvocationOutput
	 */
	public final java.lang.String getActionGroupInvocationOutput(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ActionGroupInvocationOutput.toString());
	}

	/**
	 * Set value of ActionGroupInvocationOutput
	 * @param actiongroupinvocationoutput
	 */
	public final void setActionGroupInvocationOutput(java.lang.String actiongroupinvocationoutput)
	{
		setActionGroupInvocationOutput(getContext(), actiongroupinvocationoutput);
	}

	/**
	 * Set value of ActionGroupInvocationOutput
	 * @param context
	 * @param actiongroupinvocationoutput
	 */
	public final void setActionGroupInvocationOutput(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String actiongroupinvocationoutput)
	{
		getMendixObject().setValue(context, MemberNames.ActionGroupInvocationOutput.toString(), actiongroupinvocationoutput);
	}

	/**
	 * @return value of FinalResponse
	 */
	public final java.lang.String getFinalResponse()
	{
		return getFinalResponse(getContext());
	}

	/**
	 * @param context
	 * @return value of FinalResponse
	 */
	public final java.lang.String getFinalResponse(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.FinalResponse.toString());
	}

	/**
	 * Set value of FinalResponse
	 * @param finalresponse
	 */
	public final void setFinalResponse(java.lang.String finalresponse)
	{
		setFinalResponse(getContext(), finalresponse);
	}

	/**
	 * Set value of FinalResponse
	 * @param context
	 * @param finalresponse
	 */
	public final void setFinalResponse(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String finalresponse)
	{
		getMendixObject().setValue(context, MemberNames.FinalResponse.toString(), finalresponse);
	}

	/**
	 * Get value of ObservationType
	 * @param observationtype
	 */
	public final amazonbedrockconnector.proxies.ENUM_ObservationType getObservationType()
	{
		return getObservationType(getContext());
	}

	/**
	 * @param context
	 * @return value of ObservationType
	 */
	public final amazonbedrockconnector.proxies.ENUM_ObservationType getObservationType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.ObservationType.toString());
		if (obj == null) {
			return null;
		}
		return amazonbedrockconnector.proxies.ENUM_ObservationType.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of ObservationType
	 * @param observationtype
	 */
	public final void setObservationType(amazonbedrockconnector.proxies.ENUM_ObservationType observationtype)
	{
		setObservationType(getContext(), observationtype);
	}

	/**
	 * Set value of ObservationType
	 * @param context
	 * @param observationtype
	 */
	public final void setObservationType(com.mendix.systemwideinterfaces.core.IContext context, amazonbedrockconnector.proxies.ENUM_ObservationType observationtype)
	{
		if (observationtype != null) {
			getMendixObject().setValue(context, MemberNames.ObservationType.toString(), observationtype.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.ObservationType.toString(), null);
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of RepromptResponse_Observation
	 */
	public final amazonbedrockconnector.proxies.RepromptResponse getRepromptResponse_Observation() throws com.mendix.core.CoreException
	{
		return getRepromptResponse_Observation(getContext());
	}

	/**
	 * @param context
	 * @return value of RepromptResponse_Observation
	 * @throws com.mendix.core.CoreException
	 */
	public final amazonbedrockconnector.proxies.RepromptResponse getRepromptResponse_Observation(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		amazonbedrockconnector.proxies.RepromptResponse result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.RepromptResponse_Observation.toString());
		if (identifier != null) {
			result = amazonbedrockconnector.proxies.RepromptResponse.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of RepromptResponse_Observation
	 * @param repromptresponse_observation
	 */
	public final void setRepromptResponse_Observation(amazonbedrockconnector.proxies.RepromptResponse repromptresponse_observation)
	{
		setRepromptResponse_Observation(getContext(), repromptresponse_observation);
	}

	/**
	 * Set value of RepromptResponse_Observation
	 * @param context
	 * @param repromptresponse_observation
	 */
	public final void setRepromptResponse_Observation(com.mendix.systemwideinterfaces.core.IContext context, amazonbedrockconnector.proxies.RepromptResponse repromptresponse_observation)
	{
		if (repromptresponse_observation == null) {
			getMendixObject().setValue(context, MemberNames.RepromptResponse_Observation.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.RepromptResponse_Observation.toString(), repromptresponse_observation.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final amazonbedrockconnector.proxies.Observation that = (amazonbedrockconnector.proxies.Observation) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
