// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package amazonbedrockconnector.proxies;

/**
 * The foundation model output from the pre-processing step.
 * 
 * See also:
 * 
 * API Reference:
 * https://docs.aws.amazon.com/bedrock/latest/APIReference/API_agent-runtime_PreProcessingModelInvocationOutput.html
 * 
 * Java SDK Documentation:
 * https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/bedrockagentruntime/model/PreProcessingModelInvocationOutput.html
 */
public class PreProcessingModelInvocationOutput extends amazonbedrockconnector.proxies.AbstractTrace
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AmazonBedrockConnector.PreProcessingModelInvocationOutput";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		IsValid("IsValid"),
		Rationale("Rationale"),
		TraceId("TraceId"),
		TraceType("TraceType"),
		AbstractTrace_TracePart("AmazonBedrockConnector.AbstractTrace_TracePart");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public PreProcessingModelInvocationOutput(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected PreProcessingModelInvocationOutput(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject preProcessingModelInvocationOutputMendixObject)
	{
		super(context, preProcessingModelInvocationOutputMendixObject);
		if (!preProcessingModelInvocationOutputMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static amazonbedrockconnector.proxies.PreProcessingModelInvocationOutput initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new amazonbedrockconnector.proxies.PreProcessingModelInvocationOutput(context, mendixObject);
	}

	public static amazonbedrockconnector.proxies.PreProcessingModelInvocationOutput load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return amazonbedrockconnector.proxies.PreProcessingModelInvocationOutput.initialize(context, mendixObject);
	}

	/**
	 * @return value of IsValid
	 */
	public final java.lang.Boolean getIsValid()
	{
		return getIsValid(getContext());
	}

	/**
	 * @param context
	 * @return value of IsValid
	 */
	public final java.lang.Boolean getIsValid(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsValid.toString());
	}

	/**
	 * Set value of IsValid
	 * @param isvalid
	 */
	public final void setIsValid(java.lang.Boolean isvalid)
	{
		setIsValid(getContext(), isvalid);
	}

	/**
	 * Set value of IsValid
	 * @param context
	 * @param isvalid
	 */
	public final void setIsValid(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isvalid)
	{
		getMendixObject().setValue(context, MemberNames.IsValid.toString(), isvalid);
	}

	/**
	 * @return value of Rationale
	 */
	public final java.lang.String getRationale()
	{
		return getRationale(getContext());
	}

	/**
	 * @param context
	 * @return value of Rationale
	 */
	public final java.lang.String getRationale(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Rationale.toString());
	}

	/**
	 * Set value of Rationale
	 * @param rationale
	 */
	public final void setRationale(java.lang.String rationale)
	{
		setRationale(getContext(), rationale);
	}

	/**
	 * Set value of Rationale
	 * @param context
	 * @param rationale
	 */
	public final void setRationale(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String rationale)
	{
		getMendixObject().setValue(context, MemberNames.Rationale.toString(), rationale);
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final amazonbedrockconnector.proxies.PreProcessingModelInvocationOutput that = (amazonbedrockconnector.proxies.PreProcessingModelInvocationOutput) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
