// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package amazonbedrockconnector.proxies;

/**
 * Contains attributes related to the prompt and their values.
 * 
 * See also:
 * 
 * API Reference:
 * https://docs.aws.amazon.com/bedrock/latest/APIReference/API_agent-runtime_SessionState.html
 * 
 * Java SDK Documentation:
 * https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/bedrockagentruntime/model/SessionState.html
 */
public class PromptSessionAttribute extends amazonbedrockconnector.proxies.InvokeAgentAttribute
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AmazonBedrockConnector.PromptSessionAttribute";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Key("Key"),
		Value("Value"),
		PromptSessionAttribute_SessionState("AmazonBedrockConnector.PromptSessionAttribute_SessionState");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public PromptSessionAttribute(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected PromptSessionAttribute(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject promptSessionAttributeMendixObject)
	{
		super(context, promptSessionAttributeMendixObject);
		if (!promptSessionAttributeMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static amazonbedrockconnector.proxies.PromptSessionAttribute initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new amazonbedrockconnector.proxies.PromptSessionAttribute(context, mendixObject);
	}

	public static amazonbedrockconnector.proxies.PromptSessionAttribute load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return amazonbedrockconnector.proxies.PromptSessionAttribute.initialize(context, mendixObject);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of PromptSessionAttribute_SessionState
	 */
	public final amazonbedrockconnector.proxies.SessionState getPromptSessionAttribute_SessionState() throws com.mendix.core.CoreException
	{
		return getPromptSessionAttribute_SessionState(getContext());
	}

	/**
	 * @param context
	 * @return value of PromptSessionAttribute_SessionState
	 * @throws com.mendix.core.CoreException
	 */
	public final amazonbedrockconnector.proxies.SessionState getPromptSessionAttribute_SessionState(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		amazonbedrockconnector.proxies.SessionState result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.PromptSessionAttribute_SessionState.toString());
		if (identifier != null) {
			result = amazonbedrockconnector.proxies.SessionState.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of PromptSessionAttribute_SessionState
	 * @param promptsessionattribute_sessionstate
	 */
	public final void setPromptSessionAttribute_SessionState(amazonbedrockconnector.proxies.SessionState promptsessionattribute_sessionstate)
	{
		setPromptSessionAttribute_SessionState(getContext(), promptsessionattribute_sessionstate);
	}

	/**
	 * Set value of PromptSessionAttribute_SessionState
	 * @param context
	 * @param promptsessionattribute_sessionstate
	 */
	public final void setPromptSessionAttribute_SessionState(com.mendix.systemwideinterfaces.core.IContext context, amazonbedrockconnector.proxies.SessionState promptsessionattribute_sessionstate)
	{
		if (promptsessionattribute_sessionstate == null) {
			getMendixObject().setValue(context, MemberNames.PromptSessionAttribute_SessionState.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.PromptSessionAttribute_SessionState.toString(), promptsessionattribute_sessionstate.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final amazonbedrockconnector.proxies.PromptSessionAttribute that = (amazonbedrockconnector.proxies.PromptSessionAttribute) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
