// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package amazonbedrockconnector.proxies;

/**
 * This entity holds information about additional model-specific response fields. If valid additional response fields were requested during the request a list of this entity will be returned as part of the response.
 */
public class RequestedResponseField implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject requestedResponseFieldMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AmazonBedrockConnector.RequestedResponseField";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Key("Key"),
		Value("Value"),
		RequestedResponseField_ChatCompletionsResponse("AmazonBedrockConnector.RequestedResponseField_ChatCompletionsResponse");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public RequestedResponseField(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected RequestedResponseField(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject requestedResponseFieldMendixObject)
	{
		if (requestedResponseFieldMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!requestedResponseFieldMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.requestedResponseFieldMendixObject = requestedResponseFieldMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static amazonbedrockconnector.proxies.RequestedResponseField initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new amazonbedrockconnector.proxies.RequestedResponseField(context, mendixObject);
	}

	public static amazonbedrockconnector.proxies.RequestedResponseField load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return amazonbedrockconnector.proxies.RequestedResponseField.initialize(context, mendixObject);
	}

	/**
	 * @return value of Key
	 */
	public final java.lang.String getKey()
	{
		return getKey(getContext());
	}

	/**
	 * @param context
	 * @return value of Key
	 */
	public final java.lang.String getKey(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Key.toString());
	}

	/**
	 * Set value of Key
	 * @param key
	 */
	public final void setKey(java.lang.String key)
	{
		setKey(getContext(), key);
	}

	/**
	 * Set value of Key
	 * @param context
	 * @param key
	 */
	public final void setKey(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String key)
	{
		getMendixObject().setValue(context, MemberNames.Key.toString(), key);
	}

	/**
	 * @return value of Value
	 */
	public final java.lang.String getValue()
	{
		return getValue(getContext());
	}

	/**
	 * @param context
	 * @return value of Value
	 */
	public final java.lang.String getValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Value.toString());
	}

	/**
	 * Set value of Value
	 * @param value
	 */
	public final void setValue(java.lang.String value)
	{
		setValue(getContext(), value);
	}

	/**
	 * Set value of Value
	 * @param context
	 * @param value
	 */
	public final void setValue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String value)
	{
		getMendixObject().setValue(context, MemberNames.Value.toString(), value);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of RequestedResponseField_ChatCompletionsResponse
	 */
	public final amazonbedrockconnector.proxies.ChatCompletionsResponse getRequestedResponseField_ChatCompletionsResponse() throws com.mendix.core.CoreException
	{
		return getRequestedResponseField_ChatCompletionsResponse(getContext());
	}

	/**
	 * @param context
	 * @return value of RequestedResponseField_ChatCompletionsResponse
	 * @throws com.mendix.core.CoreException
	 */
	public final amazonbedrockconnector.proxies.ChatCompletionsResponse getRequestedResponseField_ChatCompletionsResponse(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		amazonbedrockconnector.proxies.ChatCompletionsResponse result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.RequestedResponseField_ChatCompletionsResponse.toString());
		if (identifier != null) {
			result = amazonbedrockconnector.proxies.ChatCompletionsResponse.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of RequestedResponseField_ChatCompletionsResponse
	 * @param requestedresponsefield_chatcompletionsresponse
	 */
	public final void setRequestedResponseField_ChatCompletionsResponse(amazonbedrockconnector.proxies.ChatCompletionsResponse requestedresponsefield_chatcompletionsresponse)
	{
		setRequestedResponseField_ChatCompletionsResponse(getContext(), requestedresponsefield_chatcompletionsresponse);
	}

	/**
	 * Set value of RequestedResponseField_ChatCompletionsResponse
	 * @param context
	 * @param requestedresponsefield_chatcompletionsresponse
	 */
	public final void setRequestedResponseField_ChatCompletionsResponse(com.mendix.systemwideinterfaces.core.IContext context, amazonbedrockconnector.proxies.ChatCompletionsResponse requestedresponsefield_chatcompletionsresponse)
	{
		if (requestedresponsefield_chatcompletionsresponse == null) {
			getMendixObject().setValue(context, MemberNames.RequestedResponseField_ChatCompletionsResponse.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.RequestedResponseField_ChatCompletionsResponse.toString(), requestedresponsefield_chatcompletionsresponse.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return requestedResponseFieldMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final amazonbedrockconnector.proxies.RequestedResponseField that = (amazonbedrockconnector.proxies.RequestedResponseField) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
