// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package amazonbedrockconnector.proxies;

/**
 * A parameter in the Lambda input event (for the request body).
 * 
 * See also:
 * 
 * API Reference:
 * https://docs.aws.amazon.com/bedrock/latest/APIReference/API_agent-runtime_Parameter.html
 * 
 * Java SDK Documentation:
 * https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/bedrockagentruntime/model/Parameter.html
 * 
 * 
 */
public class RequestBodyContentParameter extends amazonbedrockconnector.proxies.Parameter
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AmazonBedrockConnector.RequestBodyContentParameter";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		_Type("_Type"),
		Value("Value"),
		RequestBodyContentParameter_RequestBodyContent("AmazonBedrockConnector.RequestBodyContentParameter_RequestBodyContent");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public RequestBodyContentParameter(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected RequestBodyContentParameter(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject requestBodyContentParameterMendixObject)
	{
		super(context, requestBodyContentParameterMendixObject);
		if (!requestBodyContentParameterMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static amazonbedrockconnector.proxies.RequestBodyContentParameter initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new amazonbedrockconnector.proxies.RequestBodyContentParameter(context, mendixObject);
	}

	public static amazonbedrockconnector.proxies.RequestBodyContentParameter load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return amazonbedrockconnector.proxies.RequestBodyContentParameter.initialize(context, mendixObject);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of RequestBodyContentParameter_RequestBodyContent
	 */
	public final amazonbedrockconnector.proxies.RequestBodyContent getRequestBodyContentParameter_RequestBodyContent() throws com.mendix.core.CoreException
	{
		return getRequestBodyContentParameter_RequestBodyContent(getContext());
	}

	/**
	 * @param context
	 * @return value of RequestBodyContentParameter_RequestBodyContent
	 * @throws com.mendix.core.CoreException
	 */
	public final amazonbedrockconnector.proxies.RequestBodyContent getRequestBodyContentParameter_RequestBodyContent(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		amazonbedrockconnector.proxies.RequestBodyContent result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.RequestBodyContentParameter_RequestBodyContent.toString());
		if (identifier != null) {
			result = amazonbedrockconnector.proxies.RequestBodyContent.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of RequestBodyContentParameter_RequestBodyContent
	 * @param requestbodycontentparameter_requestbodycontent
	 */
	public final void setRequestBodyContentParameter_RequestBodyContent(amazonbedrockconnector.proxies.RequestBodyContent requestbodycontentparameter_requestbodycontent)
	{
		setRequestBodyContentParameter_RequestBodyContent(getContext(), requestbodycontentparameter_requestbodycontent);
	}

	/**
	 * Set value of RequestBodyContentParameter_RequestBodyContent
	 * @param context
	 * @param requestbodycontentparameter_requestbodycontent
	 */
	public final void setRequestBodyContentParameter_RequestBodyContent(com.mendix.systemwideinterfaces.core.IContext context, amazonbedrockconnector.proxies.RequestBodyContent requestbodycontentparameter_requestbodycontent)
	{
		if (requestbodycontentparameter_requestbodycontent == null) {
			getMendixObject().setValue(context, MemberNames.RequestBodyContentParameter_RequestBodyContent.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.RequestBodyContentParameter_RequestBodyContent.toString(), requestbodycontentparameter_requestbodycontent.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final amazonbedrockconnector.proxies.RequestBodyContentParameter that = (amazonbedrockconnector.proxies.RequestBodyContentParameter) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
