// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package amazonbedrockconnector.proxies;

/**
 * The parameters in the request body for the Lambda input event.
 * 
 * See also:
 * 
 * API Reference:
 * https://docs.aws.amazon.com/bedrock/latest/APIReference/API_agent-runtime_RequestBody.html
 * 
 * Java SDK Documentation:
 * https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/bedrockagentruntime/model/RequestBody.html
 * 
 * 
 */
public class RequestBodyContent implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject requestBodyContentMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AmazonBedrockConnector.RequestBodyContent";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ContentKey("ContentKey"),
		RequestBodyContent_ActionGroupInvocationInput("AmazonBedrockConnector.RequestBodyContent_ActionGroupInvocationInput");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public RequestBodyContent(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected RequestBodyContent(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject requestBodyContentMendixObject)
	{
		if (requestBodyContentMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!requestBodyContentMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.requestBodyContentMendixObject = requestBodyContentMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static amazonbedrockconnector.proxies.RequestBodyContent initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new amazonbedrockconnector.proxies.RequestBodyContent(context, mendixObject);
	}

	public static amazonbedrockconnector.proxies.RequestBodyContent load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return amazonbedrockconnector.proxies.RequestBodyContent.initialize(context, mendixObject);
	}

	/**
	 * @return value of ContentKey
	 */
	public final java.lang.String getContentKey()
	{
		return getContentKey(getContext());
	}

	/**
	 * @param context
	 * @return value of ContentKey
	 */
	public final java.lang.String getContentKey(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ContentKey.toString());
	}

	/**
	 * Set value of ContentKey
	 * @param contentkey
	 */
	public final void setContentKey(java.lang.String contentkey)
	{
		setContentKey(getContext(), contentkey);
	}

	/**
	 * Set value of ContentKey
	 * @param context
	 * @param contentkey
	 */
	public final void setContentKey(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String contentkey)
	{
		getMendixObject().setValue(context, MemberNames.ContentKey.toString(), contentkey);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of RequestBodyContent_ActionGroupInvocationInput
	 */
	public final amazonbedrockconnector.proxies.ActionGroupInvocationInput getRequestBodyContent_ActionGroupInvocationInput() throws com.mendix.core.CoreException
	{
		return getRequestBodyContent_ActionGroupInvocationInput(getContext());
	}

	/**
	 * @param context
	 * @return value of RequestBodyContent_ActionGroupInvocationInput
	 * @throws com.mendix.core.CoreException
	 */
	public final amazonbedrockconnector.proxies.ActionGroupInvocationInput getRequestBodyContent_ActionGroupInvocationInput(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		amazonbedrockconnector.proxies.ActionGroupInvocationInput result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.RequestBodyContent_ActionGroupInvocationInput.toString());
		if (identifier != null) {
			result = amazonbedrockconnector.proxies.ActionGroupInvocationInput.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of RequestBodyContent_ActionGroupInvocationInput
	 * @param requestbodycontent_actiongroupinvocationinput
	 */
	public final void setRequestBodyContent_ActionGroupInvocationInput(amazonbedrockconnector.proxies.ActionGroupInvocationInput requestbodycontent_actiongroupinvocationinput)
	{
		setRequestBodyContent_ActionGroupInvocationInput(getContext(), requestbodycontent_actiongroupinvocationinput);
	}

	/**
	 * Set value of RequestBodyContent_ActionGroupInvocationInput
	 * @param context
	 * @param requestbodycontent_actiongroupinvocationinput
	 */
	public final void setRequestBodyContent_ActionGroupInvocationInput(com.mendix.systemwideinterfaces.core.IContext context, amazonbedrockconnector.proxies.ActionGroupInvocationInput requestbodycontent_actiongroupinvocationinput)
	{
		if (requestbodycontent_actiongroupinvocationinput == null) {
			getMendixObject().setValue(context, MemberNames.RequestBodyContent_ActionGroupInvocationInput.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.RequestBodyContent_ActionGroupInvocationInput.toString(), requestbodycontent_actiongroupinvocationinput.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return requestBodyContentMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final amazonbedrockconnector.proxies.RequestBodyContent that = (amazonbedrockconnector.proxies.RequestBodyContent) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
