// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package amazonbedrockconnector.proxies;

/**
 * The ResponseFieldRequest entity can be used to request a model-specific response field to be returned in addition to the information on the GenAICommons.Response entity.
 */
public class ResponseFieldRequest implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject responseFieldRequestMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AmazonBedrockConnector.ResponseFieldRequest";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		FieldName("FieldName");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ResponseFieldRequest(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ResponseFieldRequest(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject responseFieldRequestMendixObject)
	{
		if (responseFieldRequestMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!responseFieldRequestMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.responseFieldRequestMendixObject = responseFieldRequestMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static amazonbedrockconnector.proxies.ResponseFieldRequest initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new amazonbedrockconnector.proxies.ResponseFieldRequest(context, mendixObject);
	}

	public static amazonbedrockconnector.proxies.ResponseFieldRequest load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return amazonbedrockconnector.proxies.ResponseFieldRequest.initialize(context, mendixObject);
	}

	/**
	 * @return value of FieldName
	 */
	public final java.lang.String getFieldName()
	{
		return getFieldName(getContext());
	}

	/**
	 * @param context
	 * @return value of FieldName
	 */
	public final java.lang.String getFieldName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.FieldName.toString());
	}

	/**
	 * Set value of FieldName
	 * @param fieldname
	 */
	public final void setFieldName(java.lang.String fieldname)
	{
		setFieldName(getContext(), fieldname);
	}

	/**
	 * Set value of FieldName
	 * @param context
	 * @param fieldname
	 */
	public final void setFieldName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String fieldname)
	{
		getMendixObject().setValue(context, MemberNames.FieldName.toString(), fieldname);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return responseFieldRequestMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final amazonbedrockconnector.proxies.ResponseFieldRequest that = (amazonbedrockconnector.proxies.ResponseFieldRequest) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
