// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package amazonbedrockconnector.proxies;

/**
 * This entity holds information about how the results should be returned.
 * 
 * API reference:
 * https://docs.aws.amazon.com/bedrock/latest/APIReference/API_agent-runtime_KnowledgeBaseRetrievalConfiguration.html
 * 
 * Java SDK documentation:
 * https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/bedrockagentruntime/model/KnowledgeBaseRetrievalConfiguration.html
 */
public class RetrievalConfiguration implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject retrievalConfigurationMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AmazonBedrockConnector.RetrievalConfiguration";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		NumberOfResults("NumberOfResults"),
		RetrieveRequest_Extension_RetrievalConfiguration("AmazonBedrockConnector.RetrieveRequest_Extension_RetrievalConfiguration");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public RetrievalConfiguration(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected RetrievalConfiguration(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject retrievalConfigurationMendixObject)
	{
		if (retrievalConfigurationMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!retrievalConfigurationMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.retrievalConfigurationMendixObject = retrievalConfigurationMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static amazonbedrockconnector.proxies.RetrievalConfiguration initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new amazonbedrockconnector.proxies.RetrievalConfiguration(context, mendixObject);
	}

	public static amazonbedrockconnector.proxies.RetrievalConfiguration load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return amazonbedrockconnector.proxies.RetrievalConfiguration.initialize(context, mendixObject);
	}

	/**
	 * @return value of NumberOfResults
	 */
	public final java.lang.Integer getNumberOfResults()
	{
		return getNumberOfResults(getContext());
	}

	/**
	 * @param context
	 * @return value of NumberOfResults
	 */
	public final java.lang.Integer getNumberOfResults(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.NumberOfResults.toString());
	}

	/**
	 * Set value of NumberOfResults
	 * @param numberofresults
	 */
	public final void setNumberOfResults(java.lang.Integer numberofresults)
	{
		setNumberOfResults(getContext(), numberofresults);
	}

	/**
	 * Set value of NumberOfResults
	 * @param context
	 * @param numberofresults
	 */
	public final void setNumberOfResults(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer numberofresults)
	{
		getMendixObject().setValue(context, MemberNames.NumberOfResults.toString(), numberofresults);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of RetrieveRequest_Extension_RetrievalConfiguration
	 */
	public final amazonbedrockconnector.proxies.RetrieveRequest_Extension getRetrieveRequest_Extension_RetrievalConfiguration() throws com.mendix.core.CoreException
	{
		return getRetrieveRequest_Extension_RetrievalConfiguration(getContext());
	}

	/**
	 * @param context
	 * @return value of RetrieveRequest_Extension_RetrievalConfiguration
	 * @throws com.mendix.core.CoreException
	 */
	public final amazonbedrockconnector.proxies.RetrieveRequest_Extension getRetrieveRequest_Extension_RetrievalConfiguration(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		amazonbedrockconnector.proxies.RetrieveRequest_Extension result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.RetrieveRequest_Extension_RetrievalConfiguration.toString());
		if (identifier != null) {
			result = amazonbedrockconnector.proxies.RetrieveRequest_Extension.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of RetrieveRequest_Extension_RetrievalConfiguration
	 * @param retrieverequest_extension_retrievalconfiguration
	 */
	public final void setRetrieveRequest_Extension_RetrievalConfiguration(amazonbedrockconnector.proxies.RetrieveRequest_Extension retrieverequest_extension_retrievalconfiguration)
	{
		setRetrieveRequest_Extension_RetrievalConfiguration(getContext(), retrieverequest_extension_retrievalconfiguration);
	}

	/**
	 * Set value of RetrieveRequest_Extension_RetrievalConfiguration
	 * @param context
	 * @param retrieverequest_extension_retrievalconfiguration
	 */
	public final void setRetrieveRequest_Extension_RetrievalConfiguration(com.mendix.systemwideinterfaces.core.IContext context, amazonbedrockconnector.proxies.RetrieveRequest_Extension retrieverequest_extension_retrievalconfiguration)
	{
		if (retrieverequest_extension_retrievalconfiguration == null) {
			getMendixObject().setValue(context, MemberNames.RetrieveRequest_Extension_RetrievalConfiguration.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.RetrieveRequest_Extension_RetrievalConfiguration.toString(), retrieverequest_extension_retrievalconfiguration.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return retrievalConfigurationMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final amazonbedrockconnector.proxies.RetrievalConfiguration that = (amazonbedrockconnector.proxies.RetrievalConfiguration) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
