// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package amazonbedrockconnector.proxies;

/**
 * This entity is the response for the Amazon Bedrock Retrieve action.
 * 
 * API reference:
 * https://docs.aws.amazon.com/bedrock/latest/APIReference/API_agent-runtime_Retrieve.html
 * 
 * Java SDK documentation:
 * https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/bedrockagentruntime/model/RetrieveResponse.html
 */
public class RetrieveResponse extends genaicommons.proxies.Response
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AmazonBedrockConnector.RetrieveResponse";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		NextToken("NextToken"),
		_ID("_ID"),
		RequestTokens("RequestTokens"),
		ResponseTokens("ResponseTokens"),
		TotalTokens("TotalTokens"),
		DurationMilliseconds("DurationMilliseconds"),
		StopReason("StopReason"),
		ResponseText("ResponseText"),
		Response_Message("GenAICommons.Response_Message");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public RetrieveResponse(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected RetrieveResponse(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject retrieveResponseMendixObject)
	{
		super(context, retrieveResponseMendixObject);
		if (!retrieveResponseMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static amazonbedrockconnector.proxies.RetrieveResponse initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new amazonbedrockconnector.proxies.RetrieveResponse(context, mendixObject);
	}

	public static amazonbedrockconnector.proxies.RetrieveResponse load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return amazonbedrockconnector.proxies.RetrieveResponse.initialize(context, mendixObject);
	}

	/**
	 * @return value of NextToken
	 */
	public final java.lang.String getNextToken()
	{
		return getNextToken(getContext());
	}

	/**
	 * @param context
	 * @return value of NextToken
	 */
	public final java.lang.String getNextToken(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.NextToken.toString());
	}

	/**
	 * Set value of NextToken
	 * @param nexttoken
	 */
	public final void setNextToken(java.lang.String nexttoken)
	{
		setNextToken(getContext(), nexttoken);
	}

	/**
	 * Set value of NextToken
	 * @param context
	 * @param nexttoken
	 */
	public final void setNextToken(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String nexttoken)
	{
		getMendixObject().setValue(context, MemberNames.NextToken.toString(), nexttoken);
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final amazonbedrockconnector.proxies.RetrieveResponse that = (amazonbedrockconnector.proxies.RetrieveResponse) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
