// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package amazonbedrockconnector.proxies;

/**
 * This entity is the request for the Amazon Bedrock Retrieve action.
 * 
 * API reference:
 * https://docs.aws.amazon.com/bedrock/latest/APIReference/API_agent-runtime_Retrieve.html
 * 
 * Java SDK documentation:
 * https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/bedrockagentruntime/model/RetrieveRequest.html
 */
public class RetrieveRequest_Extension extends awsauthentication.proxies.AbstractRequest
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AmazonBedrockConnector.RetrieveRequest_Extension";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		KnowledgeBaseId("KnowledgeBaseId"),
		NextToken("NextToken"),
		RetrieveRequest_Extension_RetrievalConfiguration("AmazonBedrockConnector.RetrieveRequest_Extension_RetrievalConfiguration"),
		RetrieveRequest_Extension_Request("AmazonBedrockConnector.RetrieveRequest_Extension_Request"),
		AbstractRequest_BasicClientConfig("AWSAuthentication.AbstractRequest_BasicClientConfig");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public RetrieveRequest_Extension(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected RetrieveRequest_Extension(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject retrieveRequest_ExtensionMendixObject)
	{
		super(context, retrieveRequest_ExtensionMendixObject);
		if (!retrieveRequest_ExtensionMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static amazonbedrockconnector.proxies.RetrieveRequest_Extension initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new amazonbedrockconnector.proxies.RetrieveRequest_Extension(context, mendixObject);
	}

	public static amazonbedrockconnector.proxies.RetrieveRequest_Extension load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return amazonbedrockconnector.proxies.RetrieveRequest_Extension.initialize(context, mendixObject);
	}

	/**
	 * @return value of KnowledgeBaseId
	 */
	public final java.lang.String getKnowledgeBaseId()
	{
		return getKnowledgeBaseId(getContext());
	}

	/**
	 * @param context
	 * @return value of KnowledgeBaseId
	 */
	public final java.lang.String getKnowledgeBaseId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.KnowledgeBaseId.toString());
	}

	/**
	 * Set value of KnowledgeBaseId
	 * @param knowledgebaseid
	 */
	public final void setKnowledgeBaseId(java.lang.String knowledgebaseid)
	{
		setKnowledgeBaseId(getContext(), knowledgebaseid);
	}

	/**
	 * Set value of KnowledgeBaseId
	 * @param context
	 * @param knowledgebaseid
	 */
	public final void setKnowledgeBaseId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String knowledgebaseid)
	{
		getMendixObject().setValue(context, MemberNames.KnowledgeBaseId.toString(), knowledgebaseid);
	}

	/**
	 * @return value of NextToken
	 */
	public final java.lang.String getNextToken()
	{
		return getNextToken(getContext());
	}

	/**
	 * @param context
	 * @return value of NextToken
	 */
	public final java.lang.String getNextToken(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.NextToken.toString());
	}

	/**
	 * Set value of NextToken
	 * @param nexttoken
	 */
	public final void setNextToken(java.lang.String nexttoken)
	{
		setNextToken(getContext(), nexttoken);
	}

	/**
	 * Set value of NextToken
	 * @param context
	 * @param nexttoken
	 */
	public final void setNextToken(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String nexttoken)
	{
		getMendixObject().setValue(context, MemberNames.NextToken.toString(), nexttoken);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of RetrieveRequest_Extension_RetrievalConfiguration
	 */
	public final amazonbedrockconnector.proxies.RetrievalConfiguration getRetrieveRequest_Extension_RetrievalConfiguration() throws com.mendix.core.CoreException
	{
		return getRetrieveRequest_Extension_RetrievalConfiguration(getContext());
	}

	/**
	 * @param context
	 * @return value of RetrieveRequest_Extension_RetrievalConfiguration
	 * @throws com.mendix.core.CoreException
	 */
	public final amazonbedrockconnector.proxies.RetrievalConfiguration getRetrieveRequest_Extension_RetrievalConfiguration(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		amazonbedrockconnector.proxies.RetrievalConfiguration result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.RetrieveRequest_Extension_RetrievalConfiguration.toString());
		if (identifier != null) {
			result = amazonbedrockconnector.proxies.RetrievalConfiguration.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of RetrieveRequest_Extension_RetrievalConfiguration
	 * @param retrieverequest_extension_retrievalconfiguration
	 */
	public final void setRetrieveRequest_Extension_RetrievalConfiguration(amazonbedrockconnector.proxies.RetrievalConfiguration retrieverequest_extension_retrievalconfiguration)
	{
		setRetrieveRequest_Extension_RetrievalConfiguration(getContext(), retrieverequest_extension_retrievalconfiguration);
	}

	/**
	 * Set value of RetrieveRequest_Extension_RetrievalConfiguration
	 * @param context
	 * @param retrieverequest_extension_retrievalconfiguration
	 */
	public final void setRetrieveRequest_Extension_RetrievalConfiguration(com.mendix.systemwideinterfaces.core.IContext context, amazonbedrockconnector.proxies.RetrievalConfiguration retrieverequest_extension_retrievalconfiguration)
	{
		if (retrieverequest_extension_retrievalconfiguration == null) {
			getMendixObject().setValue(context, MemberNames.RetrieveRequest_Extension_RetrievalConfiguration.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.RetrieveRequest_Extension_RetrievalConfiguration.toString(), retrieverequest_extension_retrievalconfiguration.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of RetrieveRequest_Extension_Request
	 */
	public final genaicommons.proxies.Request getRetrieveRequest_Extension_Request() throws com.mendix.core.CoreException
	{
		return getRetrieveRequest_Extension_Request(getContext());
	}

	/**
	 * @param context
	 * @return value of RetrieveRequest_Extension_Request
	 * @throws com.mendix.core.CoreException
	 */
	public final genaicommons.proxies.Request getRetrieveRequest_Extension_Request(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		genaicommons.proxies.Request result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.RetrieveRequest_Extension_Request.toString());
		if (identifier != null) {
			result = genaicommons.proxies.Request.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of RetrieveRequest_Extension_Request
	 * @param retrieverequest_extension_request
	 */
	public final void setRetrieveRequest_Extension_Request(genaicommons.proxies.Request retrieverequest_extension_request)
	{
		setRetrieveRequest_Extension_Request(getContext(), retrieverequest_extension_request);
	}

	/**
	 * Set value of RetrieveRequest_Extension_Request
	 * @param context
	 * @param retrieverequest_extension_request
	 */
	public final void setRetrieveRequest_Extension_Request(com.mendix.systemwideinterfaces.core.IContext context, genaicommons.proxies.Request retrieverequest_extension_request)
	{
		if (retrieverequest_extension_request == null) {
			getMendixObject().setValue(context, MemberNames.RetrieveRequest_Extension_Request.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.RetrieveRequest_Extension_Request.toString(), retrieverequest_extension_request.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final amazonbedrockconnector.proxies.RetrieveRequest_Extension that = (amazonbedrockconnector.proxies.RetrieveRequest_Extension) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
