// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package amazonbedrockconnector.proxies;

/**
 * This entity is the request for the Amazon Bedrock RetrieveAndGenerate action.
 * 
 * API reference:
 * https://docs.aws.amazon.com/bedrock/latest/APIReference/API_agent-runtime_RetrieveAndGenerate.html
 * 
 * Java SDK documentation:
 * https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/bedrockagentruntime/model/RetrieveAndGenerateRequest.html
 * 
 * 
 */
public class RetrieveAndGenerateRequest_Extension extends awsauthentication.proxies.AbstractRequest
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AmazonBedrockConnector.RetrieveAndGenerateRequest_Extension";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		KmsKeyARN("KmsKeyARN"),
		RetrieveAndGenerateType("RetrieveAndGenerateType"),
		PromptTemplate("PromptTemplate"),
		RetrieveAndGenerateRequest_Extension_Request("AmazonBedrockConnector.RetrieveAndGenerateRequest_Extension_Request"),
		AbstractRequest_BasicClientConfig("AWSAuthentication.AbstractRequest_BasicClientConfig");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public RetrieveAndGenerateRequest_Extension(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected RetrieveAndGenerateRequest_Extension(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject retrieveAndGenerateRequest_ExtensionMendixObject)
	{
		super(context, retrieveAndGenerateRequest_ExtensionMendixObject);
		if (!retrieveAndGenerateRequest_ExtensionMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static amazonbedrockconnector.proxies.RetrieveAndGenerateRequest_Extension initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new amazonbedrockconnector.proxies.RetrieveAndGenerateRequest_Extension(context, mendixObject);
	}

	public static amazonbedrockconnector.proxies.RetrieveAndGenerateRequest_Extension load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return amazonbedrockconnector.proxies.RetrieveAndGenerateRequest_Extension.initialize(context, mendixObject);
	}

	/**
	 * @return value of KmsKeyARN
	 */
	public final java.lang.String getKmsKeyARN()
	{
		return getKmsKeyARN(getContext());
	}

	/**
	 * @param context
	 * @return value of KmsKeyARN
	 */
	public final java.lang.String getKmsKeyARN(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.KmsKeyARN.toString());
	}

	/**
	 * Set value of KmsKeyARN
	 * @param kmskeyarn
	 */
	public final void setKmsKeyARN(java.lang.String kmskeyarn)
	{
		setKmsKeyARN(getContext(), kmskeyarn);
	}

	/**
	 * Set value of KmsKeyARN
	 * @param context
	 * @param kmskeyarn
	 */
	public final void setKmsKeyARN(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String kmskeyarn)
	{
		getMendixObject().setValue(context, MemberNames.KmsKeyARN.toString(), kmskeyarn);
	}

	/**
	 * Get value of RetrieveAndGenerateType
	 * @param retrieveandgeneratetype
	 */
	public final amazonbedrockconnector.proxies.ENUM_RetrieveAndGenerateType getRetrieveAndGenerateType()
	{
		return getRetrieveAndGenerateType(getContext());
	}

	/**
	 * @param context
	 * @return value of RetrieveAndGenerateType
	 */
	public final amazonbedrockconnector.proxies.ENUM_RetrieveAndGenerateType getRetrieveAndGenerateType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.RetrieveAndGenerateType.toString());
		if (obj == null) {
			return null;
		}
		return amazonbedrockconnector.proxies.ENUM_RetrieveAndGenerateType.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of RetrieveAndGenerateType
	 * @param retrieveandgeneratetype
	 */
	public final void setRetrieveAndGenerateType(amazonbedrockconnector.proxies.ENUM_RetrieveAndGenerateType retrieveandgeneratetype)
	{
		setRetrieveAndGenerateType(getContext(), retrieveandgeneratetype);
	}

	/**
	 * Set value of RetrieveAndGenerateType
	 * @param context
	 * @param retrieveandgeneratetype
	 */
	public final void setRetrieveAndGenerateType(com.mendix.systemwideinterfaces.core.IContext context, amazonbedrockconnector.proxies.ENUM_RetrieveAndGenerateType retrieveandgeneratetype)
	{
		if (retrieveandgeneratetype != null) {
			getMendixObject().setValue(context, MemberNames.RetrieveAndGenerateType.toString(), retrieveandgeneratetype.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.RetrieveAndGenerateType.toString(), null);
		}
	}

	/**
	 * @return value of PromptTemplate
	 */
	public final java.lang.String getPromptTemplate()
	{
		return getPromptTemplate(getContext());
	}

	/**
	 * @param context
	 * @return value of PromptTemplate
	 */
	public final java.lang.String getPromptTemplate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.PromptTemplate.toString());
	}

	/**
	 * Set value of PromptTemplate
	 * @param prompttemplate
	 */
	public final void setPromptTemplate(java.lang.String prompttemplate)
	{
		setPromptTemplate(getContext(), prompttemplate);
	}

	/**
	 * Set value of PromptTemplate
	 * @param context
	 * @param prompttemplate
	 */
	public final void setPromptTemplate(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String prompttemplate)
	{
		getMendixObject().setValue(context, MemberNames.PromptTemplate.toString(), prompttemplate);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of RetrieveAndGenerateRequest_Extension_Request
	 */
	public final genaicommons.proxies.Request getRetrieveAndGenerateRequest_Extension_Request() throws com.mendix.core.CoreException
	{
		return getRetrieveAndGenerateRequest_Extension_Request(getContext());
	}

	/**
	 * @param context
	 * @return value of RetrieveAndGenerateRequest_Extension_Request
	 * @throws com.mendix.core.CoreException
	 */
	public final genaicommons.proxies.Request getRetrieveAndGenerateRequest_Extension_Request(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		genaicommons.proxies.Request result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.RetrieveAndGenerateRequest_Extension_Request.toString());
		if (identifier != null) {
			result = genaicommons.proxies.Request.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of RetrieveAndGenerateRequest_Extension_Request
	 * @param retrieveandgeneraterequest_extension_request
	 */
	public final void setRetrieveAndGenerateRequest_Extension_Request(genaicommons.proxies.Request retrieveandgeneraterequest_extension_request)
	{
		setRetrieveAndGenerateRequest_Extension_Request(getContext(), retrieveandgeneraterequest_extension_request);
	}

	/**
	 * Set value of RetrieveAndGenerateRequest_Extension_Request
	 * @param context
	 * @param retrieveandgeneraterequest_extension_request
	 */
	public final void setRetrieveAndGenerateRequest_Extension_Request(com.mendix.systemwideinterfaces.core.IContext context, genaicommons.proxies.Request retrieveandgeneraterequest_extension_request)
	{
		if (retrieveandgeneraterequest_extension_request == null) {
			getMendixObject().setValue(context, MemberNames.RetrieveAndGenerateRequest_Extension_Request.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.RetrieveAndGenerateRequest_Extension_Request.toString(), retrieveandgeneraterequest_extension_request.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final amazonbedrockconnector.proxies.RetrieveAndGenerateRequest_Extension that = (amazonbedrockconnector.proxies.RetrieveAndGenerateRequest_Extension) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
