// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package amazonbedrockconnector.proxies;

/**
 * The configuration information to connect to Amazon S3 as your data source.
 * 
 * API reference:
 * https://docs.aws.amazon.com/bedrock/latest/APIReference/API_agent_S3DataSourceConfiguration.html
 * 
 * Java SDK documentation:
 * https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/bedrockagent/model/S3DataSourceConfiguration.html
 */
public class S3DataSourceConfiguration implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject s3DataSourceConfigurationMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AmazonBedrockConnector.S3DataSourceConfiguration";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		BucketARN("BucketARN"),
		BucketOwnerAccountId("BucketOwnerAccountId"),
		S3DataSourceConfiguration_DataSourceConfiguration("AmazonBedrockConnector.S3DataSourceConfiguration_DataSourceConfiguration");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public S3DataSourceConfiguration(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected S3DataSourceConfiguration(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject s3DataSourceConfigurationMendixObject)
	{
		if (s3DataSourceConfigurationMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!s3DataSourceConfigurationMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.s3DataSourceConfigurationMendixObject = s3DataSourceConfigurationMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static amazonbedrockconnector.proxies.S3DataSourceConfiguration initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new amazonbedrockconnector.proxies.S3DataSourceConfiguration(context, mendixObject);
	}

	public static amazonbedrockconnector.proxies.S3DataSourceConfiguration load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return amazonbedrockconnector.proxies.S3DataSourceConfiguration.initialize(context, mendixObject);
	}

	/**
	 * @return value of BucketARN
	 */
	public final java.lang.String getBucketARN()
	{
		return getBucketARN(getContext());
	}

	/**
	 * @param context
	 * @return value of BucketARN
	 */
	public final java.lang.String getBucketARN(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.BucketARN.toString());
	}

	/**
	 * Set value of BucketARN
	 * @param bucketarn
	 */
	public final void setBucketARN(java.lang.String bucketarn)
	{
		setBucketARN(getContext(), bucketarn);
	}

	/**
	 * Set value of BucketARN
	 * @param context
	 * @param bucketarn
	 */
	public final void setBucketARN(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String bucketarn)
	{
		getMendixObject().setValue(context, MemberNames.BucketARN.toString(), bucketarn);
	}

	/**
	 * @return value of BucketOwnerAccountId
	 */
	public final java.lang.String getBucketOwnerAccountId()
	{
		return getBucketOwnerAccountId(getContext());
	}

	/**
	 * @param context
	 * @return value of BucketOwnerAccountId
	 */
	public final java.lang.String getBucketOwnerAccountId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.BucketOwnerAccountId.toString());
	}

	/**
	 * Set value of BucketOwnerAccountId
	 * @param bucketowneraccountid
	 */
	public final void setBucketOwnerAccountId(java.lang.String bucketowneraccountid)
	{
		setBucketOwnerAccountId(getContext(), bucketowneraccountid);
	}

	/**
	 * Set value of BucketOwnerAccountId
	 * @param context
	 * @param bucketowneraccountid
	 */
	public final void setBucketOwnerAccountId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String bucketowneraccountid)
	{
		getMendixObject().setValue(context, MemberNames.BucketOwnerAccountId.toString(), bucketowneraccountid);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of S3DataSourceConfiguration_DataSourceConfiguration
	 */
	public final amazonbedrockconnector.proxies.DataSourceConfiguration getS3DataSourceConfiguration_DataSourceConfiguration() throws com.mendix.core.CoreException
	{
		return getS3DataSourceConfiguration_DataSourceConfiguration(getContext());
	}

	/**
	 * @param context
	 * @return value of S3DataSourceConfiguration_DataSourceConfiguration
	 * @throws com.mendix.core.CoreException
	 */
	public final amazonbedrockconnector.proxies.DataSourceConfiguration getS3DataSourceConfiguration_DataSourceConfiguration(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		amazonbedrockconnector.proxies.DataSourceConfiguration result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.S3DataSourceConfiguration_DataSourceConfiguration.toString());
		if (identifier != null) {
			result = amazonbedrockconnector.proxies.DataSourceConfiguration.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of S3DataSourceConfiguration_DataSourceConfiguration
	 * @param s3datasourceconfiguration_datasourceconfiguration
	 */
	public final void setS3DataSourceConfiguration_DataSourceConfiguration(amazonbedrockconnector.proxies.DataSourceConfiguration s3datasourceconfiguration_datasourceconfiguration)
	{
		setS3DataSourceConfiguration_DataSourceConfiguration(getContext(), s3datasourceconfiguration_datasourceconfiguration);
	}

	/**
	 * Set value of S3DataSourceConfiguration_DataSourceConfiguration
	 * @param context
	 * @param s3datasourceconfiguration_datasourceconfiguration
	 */
	public final void setS3DataSourceConfiguration_DataSourceConfiguration(com.mendix.systemwideinterfaces.core.IContext context, amazonbedrockconnector.proxies.DataSourceConfiguration s3datasourceconfiguration_datasourceconfiguration)
	{
		if (s3datasourceconfiguration_datasourceconfiguration == null) {
			getMendixObject().setValue(context, MemberNames.S3DataSourceConfiguration_DataSourceConfiguration.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.S3DataSourceConfiguration_DataSourceConfiguration.toString(), s3datasourceconfiguration_datasourceconfiguration.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return s3DataSourceConfigurationMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final amazonbedrockconnector.proxies.S3DataSourceConfiguration that = (amazonbedrockconnector.proxies.S3DataSourceConfiguration) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
