// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package amazonbedrockconnector.proxies;

/**
 * Contains parameters that specify various attributes of the session.
 * 
 * See also:
 * 
 * API Reference:
 * https://docs.aws.amazon.com/bedrock/latest/APIReference/API_agent-runtime_SessionState.html
 * 
 * Java SDK Documentation:
 * https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/bedrockagentruntime/model/SessionState.html
 */
public class SessionState implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject sessionStateMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AmazonBedrockConnector.SessionState";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		SessionState_InvokeAgentRequest("AmazonBedrockConnector.SessionState_InvokeAgentRequest");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public SessionState(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected SessionState(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject sessionStateMendixObject)
	{
		if (sessionStateMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!sessionStateMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.sessionStateMendixObject = sessionStateMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static amazonbedrockconnector.proxies.SessionState initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new amazonbedrockconnector.proxies.SessionState(context, mendixObject);
	}

	public static amazonbedrockconnector.proxies.SessionState load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return amazonbedrockconnector.proxies.SessionState.initialize(context, mendixObject);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of SessionState_InvokeAgentRequest
	 */
	public final amazonbedrockconnector.proxies.InvokeAgentRequest getSessionState_InvokeAgentRequest() throws com.mendix.core.CoreException
	{
		return getSessionState_InvokeAgentRequest(getContext());
	}

	/**
	 * @param context
	 * @return value of SessionState_InvokeAgentRequest
	 * @throws com.mendix.core.CoreException
	 */
	public final amazonbedrockconnector.proxies.InvokeAgentRequest getSessionState_InvokeAgentRequest(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		amazonbedrockconnector.proxies.InvokeAgentRequest result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.SessionState_InvokeAgentRequest.toString());
		if (identifier != null) {
			result = amazonbedrockconnector.proxies.InvokeAgentRequest.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of SessionState_InvokeAgentRequest
	 * @param sessionstate_invokeagentrequest
	 */
	public final void setSessionState_InvokeAgentRequest(amazonbedrockconnector.proxies.InvokeAgentRequest sessionstate_invokeagentrequest)
	{
		setSessionState_InvokeAgentRequest(getContext(), sessionstate_invokeagentrequest);
	}

	/**
	 * Set value of SessionState_InvokeAgentRequest
	 * @param context
	 * @param sessionstate_invokeagentrequest
	 */
	public final void setSessionState_InvokeAgentRequest(com.mendix.systemwideinterfaces.core.IContext context, amazonbedrockconnector.proxies.InvokeAgentRequest sessionstate_invokeagentrequest)
	{
		if (sessionstate_invokeagentrequest == null) {
			getMendixObject().setValue(context, MemberNames.SessionState_InvokeAgentRequest.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.SessionState_InvokeAgentRequest.toString(), sessionstate_invokeagentrequest.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return sessionStateMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final amazonbedrockconnector.proxies.SessionState that = (amazonbedrockconnector.proxies.SessionState) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
