// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package amazonbedrockconnector.proxies;

/**
 * The endpoint information to connect to your SharePoint data source.
 * 
 * API reference:
 * https://docs.aws.amazon.com/bedrock/latest/APIReference/API_agent_SharePointSourceConfiguration.html
 * 
 * Java SDK documentation:
 * https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/bedrockagent/model/SharePointSourceConfiguration.html
 */
public class SharePointSourceConfiguration implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject sharePointSourceConfigurationMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AmazonBedrockConnector.SharePointSourceConfiguration";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		AuthType("AuthType"),
		CredentialsSecretArn("CredentialsSecretArn"),
		Domain("Domain"),
		HostType("HostType"),
		TenantId("TenantId"),
		SharePointSourceConfiguration_SharePointDataSourceConfiguration("AmazonBedrockConnector.SharePointSourceConfiguration_SharePointDataSourceConfiguration");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public SharePointSourceConfiguration(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected SharePointSourceConfiguration(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject sharePointSourceConfigurationMendixObject)
	{
		if (sharePointSourceConfigurationMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!sharePointSourceConfigurationMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.sharePointSourceConfigurationMendixObject = sharePointSourceConfigurationMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static amazonbedrockconnector.proxies.SharePointSourceConfiguration initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new amazonbedrockconnector.proxies.SharePointSourceConfiguration(context, mendixObject);
	}

	public static amazonbedrockconnector.proxies.SharePointSourceConfiguration load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return amazonbedrockconnector.proxies.SharePointSourceConfiguration.initialize(context, mendixObject);
	}

	/**
	 * Get value of AuthType
	 * @param authtype
	 */
	public final amazonbedrockconnector.proxies.ENUM_SharePointAuthType getAuthType()
	{
		return getAuthType(getContext());
	}

	/**
	 * @param context
	 * @return value of AuthType
	 */
	public final amazonbedrockconnector.proxies.ENUM_SharePointAuthType getAuthType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.AuthType.toString());
		if (obj == null) {
			return null;
		}
		return amazonbedrockconnector.proxies.ENUM_SharePointAuthType.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of AuthType
	 * @param authtype
	 */
	public final void setAuthType(amazonbedrockconnector.proxies.ENUM_SharePointAuthType authtype)
	{
		setAuthType(getContext(), authtype);
	}

	/**
	 * Set value of AuthType
	 * @param context
	 * @param authtype
	 */
	public final void setAuthType(com.mendix.systemwideinterfaces.core.IContext context, amazonbedrockconnector.proxies.ENUM_SharePointAuthType authtype)
	{
		if (authtype != null) {
			getMendixObject().setValue(context, MemberNames.AuthType.toString(), authtype.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.AuthType.toString(), null);
		}
	}

	/**
	 * @return value of CredentialsSecretArn
	 */
	public final java.lang.String getCredentialsSecretArn()
	{
		return getCredentialsSecretArn(getContext());
	}

	/**
	 * @param context
	 * @return value of CredentialsSecretArn
	 */
	public final java.lang.String getCredentialsSecretArn(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CredentialsSecretArn.toString());
	}

	/**
	 * Set value of CredentialsSecretArn
	 * @param credentialssecretarn
	 */
	public final void setCredentialsSecretArn(java.lang.String credentialssecretarn)
	{
		setCredentialsSecretArn(getContext(), credentialssecretarn);
	}

	/**
	 * Set value of CredentialsSecretArn
	 * @param context
	 * @param credentialssecretarn
	 */
	public final void setCredentialsSecretArn(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String credentialssecretarn)
	{
		getMendixObject().setValue(context, MemberNames.CredentialsSecretArn.toString(), credentialssecretarn);
	}

	/**
	 * @return value of Domain
	 */
	public final java.lang.String getDomain()
	{
		return getDomain(getContext());
	}

	/**
	 * @param context
	 * @return value of Domain
	 */
	public final java.lang.String getDomain(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Domain.toString());
	}

	/**
	 * Set value of Domain
	 * @param domain
	 */
	public final void setDomain(java.lang.String domain)
	{
		setDomain(getContext(), domain);
	}

	/**
	 * Set value of Domain
	 * @param context
	 * @param domain
	 */
	public final void setDomain(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String domain)
	{
		getMendixObject().setValue(context, MemberNames.Domain.toString(), domain);
	}

	/**
	 * Get value of HostType
	 * @param hosttype
	 */
	public final amazonbedrockconnector.proxies.ENUM_SharePointHostType getHostType()
	{
		return getHostType(getContext());
	}

	/**
	 * @param context
	 * @return value of HostType
	 */
	public final amazonbedrockconnector.proxies.ENUM_SharePointHostType getHostType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.HostType.toString());
		if (obj == null) {
			return null;
		}
		return amazonbedrockconnector.proxies.ENUM_SharePointHostType.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of HostType
	 * @param hosttype
	 */
	public final void setHostType(amazonbedrockconnector.proxies.ENUM_SharePointHostType hosttype)
	{
		setHostType(getContext(), hosttype);
	}

	/**
	 * Set value of HostType
	 * @param context
	 * @param hosttype
	 */
	public final void setHostType(com.mendix.systemwideinterfaces.core.IContext context, amazonbedrockconnector.proxies.ENUM_SharePointHostType hosttype)
	{
		if (hosttype != null) {
			getMendixObject().setValue(context, MemberNames.HostType.toString(), hosttype.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.HostType.toString(), null);
		}
	}

	/**
	 * @return value of TenantId
	 */
	public final java.lang.String getTenantId()
	{
		return getTenantId(getContext());
	}

	/**
	 * @param context
	 * @return value of TenantId
	 */
	public final java.lang.String getTenantId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.TenantId.toString());
	}

	/**
	 * Set value of TenantId
	 * @param tenantid
	 */
	public final void setTenantId(java.lang.String tenantid)
	{
		setTenantId(getContext(), tenantid);
	}

	/**
	 * Set value of TenantId
	 * @param context
	 * @param tenantid
	 */
	public final void setTenantId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String tenantid)
	{
		getMendixObject().setValue(context, MemberNames.TenantId.toString(), tenantid);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of SharePointSourceConfiguration_SharePointDataSourceConfiguration
	 */
	public final amazonbedrockconnector.proxies.SharePointDataSourceConfiguration getSharePointSourceConfiguration_SharePointDataSourceConfiguration() throws com.mendix.core.CoreException
	{
		return getSharePointSourceConfiguration_SharePointDataSourceConfiguration(getContext());
	}

	/**
	 * @param context
	 * @return value of SharePointSourceConfiguration_SharePointDataSourceConfiguration
	 * @throws com.mendix.core.CoreException
	 */
	public final amazonbedrockconnector.proxies.SharePointDataSourceConfiguration getSharePointSourceConfiguration_SharePointDataSourceConfiguration(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		amazonbedrockconnector.proxies.SharePointDataSourceConfiguration result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.SharePointSourceConfiguration_SharePointDataSourceConfiguration.toString());
		if (identifier != null) {
			result = amazonbedrockconnector.proxies.SharePointDataSourceConfiguration.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of SharePointSourceConfiguration_SharePointDataSourceConfiguration
	 * @param sharepointsourceconfiguration_sharepointdatasourceconfiguration
	 */
	public final void setSharePointSourceConfiguration_SharePointDataSourceConfiguration(amazonbedrockconnector.proxies.SharePointDataSourceConfiguration sharepointsourceconfiguration_sharepointdatasourceconfiguration)
	{
		setSharePointSourceConfiguration_SharePointDataSourceConfiguration(getContext(), sharepointsourceconfiguration_sharepointdatasourceconfiguration);
	}

	/**
	 * Set value of SharePointSourceConfiguration_SharePointDataSourceConfiguration
	 * @param context
	 * @param sharepointsourceconfiguration_sharepointdatasourceconfiguration
	 */
	public final void setSharePointSourceConfiguration_SharePointDataSourceConfiguration(com.mendix.systemwideinterfaces.core.IContext context, amazonbedrockconnector.proxies.SharePointDataSourceConfiguration sharepointsourceconfiguration_sharepointdatasourceconfiguration)
	{
		if (sharepointsourceconfiguration_sharepointdatasourceconfiguration == null) {
			getMendixObject().setValue(context, MemberNames.SharePointSourceConfiguration_SharePointDataSourceConfiguration.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.SharePointSourceConfiguration_SharePointDataSourceConfiguration.toString(), sharepointsourceconfiguration_sharepointdatasourceconfiguration.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return sharePointSourceConfigurationMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final amazonbedrockconnector.proxies.SharePointSourceConfiguration that = (amazonbedrockconnector.proxies.SharePointSourceConfiguration) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
