// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package amazonbedrockconnector.proxies;

public class StartIngestionJob extends amazonbedrockconnector.proxies.IngestionJob
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AmazonBedrockConnector.StartIngestionJob";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Description("Description"),
		DataSourceId("DataSourceId"),
		IngestionJobId("IngestionJobId"),
		KnowledgeBaseId("KnowledgeBaseId"),
		Status("Status"),
		StartedAt("StartedAt"),
		UpdatedAt("UpdatedAt"),
		StartIngestionJob_StartIngestionJobResponse("AmazonBedrockConnector.StartIngestionJob_StartIngestionJobResponse"),
		IngestionJobStats_IngestionJob("AmazonBedrockConnector.IngestionJobStats_IngestionJob");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public StartIngestionJob(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected StartIngestionJob(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject startIngestionJobMendixObject)
	{
		super(context, startIngestionJobMendixObject);
		if (!startIngestionJobMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static amazonbedrockconnector.proxies.StartIngestionJob initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new amazonbedrockconnector.proxies.StartIngestionJob(context, mendixObject);
	}

	public static amazonbedrockconnector.proxies.StartIngestionJob load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return amazonbedrockconnector.proxies.StartIngestionJob.initialize(context, mendixObject);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of StartIngestionJob_StartIngestionJobResponse
	 */
	public final amazonbedrockconnector.proxies.StartIngestionJobResponse getStartIngestionJob_StartIngestionJobResponse() throws com.mendix.core.CoreException
	{
		return getStartIngestionJob_StartIngestionJobResponse(getContext());
	}

	/**
	 * @param context
	 * @return value of StartIngestionJob_StartIngestionJobResponse
	 * @throws com.mendix.core.CoreException
	 */
	public final amazonbedrockconnector.proxies.StartIngestionJobResponse getStartIngestionJob_StartIngestionJobResponse(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		amazonbedrockconnector.proxies.StartIngestionJobResponse result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.StartIngestionJob_StartIngestionJobResponse.toString());
		if (identifier != null) {
			result = amazonbedrockconnector.proxies.StartIngestionJobResponse.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of StartIngestionJob_StartIngestionJobResponse
	 * @param startingestionjob_startingestionjobresponse
	 */
	public final void setStartIngestionJob_StartIngestionJobResponse(amazonbedrockconnector.proxies.StartIngestionJobResponse startingestionjob_startingestionjobresponse)
	{
		setStartIngestionJob_StartIngestionJobResponse(getContext(), startingestionjob_startingestionjobresponse);
	}

	/**
	 * Set value of StartIngestionJob_StartIngestionJobResponse
	 * @param context
	 * @param startingestionjob_startingestionjobresponse
	 */
	public final void setStartIngestionJob_StartIngestionJobResponse(com.mendix.systemwideinterfaces.core.IContext context, amazonbedrockconnector.proxies.StartIngestionJobResponse startingestionjob_startingestionjobresponse)
	{
		if (startingestionjob_startingestionjobresponse == null) {
			getMendixObject().setValue(context, MemberNames.StartIngestionJob_StartIngestionJobResponse.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.StartIngestionJob_StartIngestionJobResponse.toString(), startingestionjob_startingestionjobresponse.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final amazonbedrockconnector.proxies.StartIngestionJob that = (amazonbedrockconnector.proxies.StartIngestionJob) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
