// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package amazonbedrockconnector.proxies;

/**
 * This entity contains the customization type that the model supports.
 */
public class SupportedCustomization implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject supportedCustomizationMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AmazonBedrockConnector.SupportedCustomization";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		CustomizationType("CustomizationType"),
		SupportedCustomization_FoundationModelSummary("AmazonBedrockConnector.SupportedCustomization_FoundationModelSummary");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public SupportedCustomization(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected SupportedCustomization(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject supportedCustomizationMendixObject)
	{
		if (supportedCustomizationMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!supportedCustomizationMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.supportedCustomizationMendixObject = supportedCustomizationMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static amazonbedrockconnector.proxies.SupportedCustomization initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new amazonbedrockconnector.proxies.SupportedCustomization(context, mendixObject);
	}

	public static amazonbedrockconnector.proxies.SupportedCustomization load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return amazonbedrockconnector.proxies.SupportedCustomization.initialize(context, mendixObject);
	}

	/**
	 * Get value of CustomizationType
	 * @param customizationtype
	 */
	public final amazonbedrockconnector.proxies.ENUM_CustomizationType getCustomizationType()
	{
		return getCustomizationType(getContext());
	}

	/**
	 * @param context
	 * @return value of CustomizationType
	 */
	public final amazonbedrockconnector.proxies.ENUM_CustomizationType getCustomizationType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.CustomizationType.toString());
		if (obj == null) {
			return null;
		}
		return amazonbedrockconnector.proxies.ENUM_CustomizationType.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of CustomizationType
	 * @param customizationtype
	 */
	public final void setCustomizationType(amazonbedrockconnector.proxies.ENUM_CustomizationType customizationtype)
	{
		setCustomizationType(getContext(), customizationtype);
	}

	/**
	 * Set value of CustomizationType
	 * @param context
	 * @param customizationtype
	 */
	public final void setCustomizationType(com.mendix.systemwideinterfaces.core.IContext context, amazonbedrockconnector.proxies.ENUM_CustomizationType customizationtype)
	{
		if (customizationtype != null) {
			getMendixObject().setValue(context, MemberNames.CustomizationType.toString(), customizationtype.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.CustomizationType.toString(), null);
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of SupportedCustomization_FoundationModelSummary
	 */
	public final amazonbedrockconnector.proxies.FoundationModelSummary getSupportedCustomization_FoundationModelSummary() throws com.mendix.core.CoreException
	{
		return getSupportedCustomization_FoundationModelSummary(getContext());
	}

	/**
	 * @param context
	 * @return value of SupportedCustomization_FoundationModelSummary
	 * @throws com.mendix.core.CoreException
	 */
	public final amazonbedrockconnector.proxies.FoundationModelSummary getSupportedCustomization_FoundationModelSummary(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		amazonbedrockconnector.proxies.FoundationModelSummary result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.SupportedCustomization_FoundationModelSummary.toString());
		if (identifier != null) {
			result = amazonbedrockconnector.proxies.FoundationModelSummary.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of SupportedCustomization_FoundationModelSummary
	 * @param supportedcustomization_foundationmodelsummary
	 */
	public final void setSupportedCustomization_FoundationModelSummary(amazonbedrockconnector.proxies.FoundationModelSummary supportedcustomization_foundationmodelsummary)
	{
		setSupportedCustomization_FoundationModelSummary(getContext(), supportedcustomization_foundationmodelsummary);
	}

	/**
	 * Set value of SupportedCustomization_FoundationModelSummary
	 * @param context
	 * @param supportedcustomization_foundationmodelsummary
	 */
	public final void setSupportedCustomization_FoundationModelSummary(com.mendix.systemwideinterfaces.core.IContext context, amazonbedrockconnector.proxies.FoundationModelSummary supportedcustomization_foundationmodelsummary)
	{
		if (supportedcustomization_foundationmodelsummary == null) {
			getMendixObject().setValue(context, MemberNames.SupportedCustomization_FoundationModelSummary.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.SupportedCustomization_FoundationModelSummary.toString(), supportedcustomization_foundationmodelsummary.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return supportedCustomizationMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final amazonbedrockconnector.proxies.SupportedCustomization that = (amazonbedrockconnector.proxies.SupportedCustomization) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
