// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package amazonbedrockconnector.proxies;

/**
 * This entity contains the inference type that the model supports.
 */
public class SupportedInferenceType implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject supportedInferenceTypeMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AmazonBedrockConnector.SupportedInferenceType";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		InferenceType("InferenceType"),
		SupportedInferenceType_FoundationModelSummary("AmazonBedrockConnector.SupportedInferenceType_FoundationModelSummary");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public SupportedInferenceType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected SupportedInferenceType(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject supportedInferenceTypeMendixObject)
	{
		if (supportedInferenceTypeMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!supportedInferenceTypeMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.supportedInferenceTypeMendixObject = supportedInferenceTypeMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static amazonbedrockconnector.proxies.SupportedInferenceType initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new amazonbedrockconnector.proxies.SupportedInferenceType(context, mendixObject);
	}

	public static amazonbedrockconnector.proxies.SupportedInferenceType load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return amazonbedrockconnector.proxies.SupportedInferenceType.initialize(context, mendixObject);
	}

	/**
	 * Get value of InferenceType
	 * @param inferencetype
	 */
	public final amazonbedrockconnector.proxies.ENUM_InferenceType getInferenceType()
	{
		return getInferenceType(getContext());
	}

	/**
	 * @param context
	 * @return value of InferenceType
	 */
	public final amazonbedrockconnector.proxies.ENUM_InferenceType getInferenceType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.InferenceType.toString());
		if (obj == null) {
			return null;
		}
		return amazonbedrockconnector.proxies.ENUM_InferenceType.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of InferenceType
	 * @param inferencetype
	 */
	public final void setInferenceType(amazonbedrockconnector.proxies.ENUM_InferenceType inferencetype)
	{
		setInferenceType(getContext(), inferencetype);
	}

	/**
	 * Set value of InferenceType
	 * @param context
	 * @param inferencetype
	 */
	public final void setInferenceType(com.mendix.systemwideinterfaces.core.IContext context, amazonbedrockconnector.proxies.ENUM_InferenceType inferencetype)
	{
		if (inferencetype != null) {
			getMendixObject().setValue(context, MemberNames.InferenceType.toString(), inferencetype.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.InferenceType.toString(), null);
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of SupportedInferenceType_FoundationModelSummary
	 */
	public final amazonbedrockconnector.proxies.FoundationModelSummary getSupportedInferenceType_FoundationModelSummary() throws com.mendix.core.CoreException
	{
		return getSupportedInferenceType_FoundationModelSummary(getContext());
	}

	/**
	 * @param context
	 * @return value of SupportedInferenceType_FoundationModelSummary
	 * @throws com.mendix.core.CoreException
	 */
	public final amazonbedrockconnector.proxies.FoundationModelSummary getSupportedInferenceType_FoundationModelSummary(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		amazonbedrockconnector.proxies.FoundationModelSummary result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.SupportedInferenceType_FoundationModelSummary.toString());
		if (identifier != null) {
			result = amazonbedrockconnector.proxies.FoundationModelSummary.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of SupportedInferenceType_FoundationModelSummary
	 * @param supportedinferencetype_foundationmodelsummary
	 */
	public final void setSupportedInferenceType_FoundationModelSummary(amazonbedrockconnector.proxies.FoundationModelSummary supportedinferencetype_foundationmodelsummary)
	{
		setSupportedInferenceType_FoundationModelSummary(getContext(), supportedinferencetype_foundationmodelsummary);
	}

	/**
	 * Set value of SupportedInferenceType_FoundationModelSummary
	 * @param context
	 * @param supportedinferencetype_foundationmodelsummary
	 */
	public final void setSupportedInferenceType_FoundationModelSummary(com.mendix.systemwideinterfaces.core.IContext context, amazonbedrockconnector.proxies.FoundationModelSummary supportedinferencetype_foundationmodelsummary)
	{
		if (supportedinferencetype_foundationmodelsummary == null) {
			getMendixObject().setValue(context, MemberNames.SupportedInferenceType_FoundationModelSummary.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.SupportedInferenceType_FoundationModelSummary.toString(), supportedinferencetype_foundationmodelsummary.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return supportedInferenceTypeMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final amazonbedrockconnector.proxies.SupportedInferenceType that = (amazonbedrockconnector.proxies.SupportedInferenceType) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
