// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package amazonbedrockconnector.proxies;

/**
 * This entity extends the GenAICommons.EmbeddingsOptions with attributes specific for Titan Embeddings.
 */
public class TitanEmbeddingsOptions_Extension implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject titanEmbeddingsOptions_ExtensionMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AmazonBedrockConnector.TitanEmbeddingsOptions_Extension";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Normalize("Normalize"),
		TitanEmbeddingsOptions_Extension_EmbeddingsOptions("AmazonBedrockConnector.TitanEmbeddingsOptions_Extension_EmbeddingsOptions");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public TitanEmbeddingsOptions_Extension(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected TitanEmbeddingsOptions_Extension(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject titanEmbeddingsOptions_ExtensionMendixObject)
	{
		if (titanEmbeddingsOptions_ExtensionMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!titanEmbeddingsOptions_ExtensionMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.titanEmbeddingsOptions_ExtensionMendixObject = titanEmbeddingsOptions_ExtensionMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static amazonbedrockconnector.proxies.TitanEmbeddingsOptions_Extension initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new amazonbedrockconnector.proxies.TitanEmbeddingsOptions_Extension(context, mendixObject);
	}

	public static amazonbedrockconnector.proxies.TitanEmbeddingsOptions_Extension load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return amazonbedrockconnector.proxies.TitanEmbeddingsOptions_Extension.initialize(context, mendixObject);
	}

	/**
	 * @return value of Normalize
	 */
	public final java.lang.Boolean getNormalize()
	{
		return getNormalize(getContext());
	}

	/**
	 * @param context
	 * @return value of Normalize
	 */
	public final java.lang.Boolean getNormalize(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Normalize.toString());
	}

	/**
	 * Set value of Normalize
	 * @param normalize
	 */
	public final void setNormalize(java.lang.Boolean normalize)
	{
		setNormalize(getContext(), normalize);
	}

	/**
	 * Set value of Normalize
	 * @param context
	 * @param normalize
	 */
	public final void setNormalize(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean normalize)
	{
		getMendixObject().setValue(context, MemberNames.Normalize.toString(), normalize);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of TitanEmbeddingsOptions_Extension_EmbeddingsOptions
	 */
	public final genaicommons.proxies.EmbeddingsOptions getTitanEmbeddingsOptions_Extension_EmbeddingsOptions() throws com.mendix.core.CoreException
	{
		return getTitanEmbeddingsOptions_Extension_EmbeddingsOptions(getContext());
	}

	/**
	 * @param context
	 * @return value of TitanEmbeddingsOptions_Extension_EmbeddingsOptions
	 * @throws com.mendix.core.CoreException
	 */
	public final genaicommons.proxies.EmbeddingsOptions getTitanEmbeddingsOptions_Extension_EmbeddingsOptions(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		genaicommons.proxies.EmbeddingsOptions result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.TitanEmbeddingsOptions_Extension_EmbeddingsOptions.toString());
		if (identifier != null) {
			result = genaicommons.proxies.EmbeddingsOptions.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of TitanEmbeddingsOptions_Extension_EmbeddingsOptions
	 * @param titanembeddingsoptions_extension_embeddingsoptions
	 */
	public final void setTitanEmbeddingsOptions_Extension_EmbeddingsOptions(genaicommons.proxies.EmbeddingsOptions titanembeddingsoptions_extension_embeddingsoptions)
	{
		setTitanEmbeddingsOptions_Extension_EmbeddingsOptions(getContext(), titanembeddingsoptions_extension_embeddingsoptions);
	}

	/**
	 * Set value of TitanEmbeddingsOptions_Extension_EmbeddingsOptions
	 * @param context
	 * @param titanembeddingsoptions_extension_embeddingsoptions
	 */
	public final void setTitanEmbeddingsOptions_Extension_EmbeddingsOptions(com.mendix.systemwideinterfaces.core.IContext context, genaicommons.proxies.EmbeddingsOptions titanembeddingsoptions_extension_embeddingsoptions)
	{
		if (titanembeddingsoptions_extension_embeddingsoptions == null) {
			getMendixObject().setValue(context, MemberNames.TitanEmbeddingsOptions_Extension_EmbeddingsOptions.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.TitanEmbeddingsOptions_Extension_EmbeddingsOptions.toString(), titanembeddingsoptions_extension_embeddingsoptions.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return titanEmbeddingsOptions_ExtensionMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final amazonbedrockconnector.proxies.TitanEmbeddingsOptions_Extension that = (amazonbedrockconnector.proxies.TitanEmbeddingsOptions_Extension) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
