// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package amazonbedrockconnector.proxies;

/**
 * This is a helper entity that solely serves the purpose to simplify the export mapping.
 */
public class TitanEmbeddingsMappingHelper implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject titanEmbeddingsMappingHelperMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AmazonBedrockConnector.TitanEmbeddingsMappingHelper";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Dimension("Dimension"),
		Normalize("Normalize"),
		InputText("InputText");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public TitanEmbeddingsMappingHelper(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected TitanEmbeddingsMappingHelper(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject titanEmbeddingsMappingHelperMendixObject)
	{
		if (titanEmbeddingsMappingHelperMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!titanEmbeddingsMappingHelperMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.titanEmbeddingsMappingHelperMendixObject = titanEmbeddingsMappingHelperMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static amazonbedrockconnector.proxies.TitanEmbeddingsMappingHelper initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new amazonbedrockconnector.proxies.TitanEmbeddingsMappingHelper(context, mendixObject);
	}

	public static amazonbedrockconnector.proxies.TitanEmbeddingsMappingHelper load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return amazonbedrockconnector.proxies.TitanEmbeddingsMappingHelper.initialize(context, mendixObject);
	}

	/**
	 * @return value of Dimension
	 */
	public final java.lang.Integer getDimension()
	{
		return getDimension(getContext());
	}

	/**
	 * @param context
	 * @return value of Dimension
	 */
	public final java.lang.Integer getDimension(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Dimension.toString());
	}

	/**
	 * Set value of Dimension
	 * @param dimension
	 */
	public final void setDimension(java.lang.Integer dimension)
	{
		setDimension(getContext(), dimension);
	}

	/**
	 * Set value of Dimension
	 * @param context
	 * @param dimension
	 */
	public final void setDimension(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer dimension)
	{
		getMendixObject().setValue(context, MemberNames.Dimension.toString(), dimension);
	}

	/**
	 * @return value of Normalize
	 */
	public final java.lang.Boolean getNormalize()
	{
		return getNormalize(getContext());
	}

	/**
	 * @param context
	 * @return value of Normalize
	 */
	public final java.lang.Boolean getNormalize(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Normalize.toString());
	}

	/**
	 * Set value of Normalize
	 * @param normalize
	 */
	public final void setNormalize(java.lang.Boolean normalize)
	{
		setNormalize(getContext(), normalize);
	}

	/**
	 * Set value of Normalize
	 * @param context
	 * @param normalize
	 */
	public final void setNormalize(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean normalize)
	{
		getMendixObject().setValue(context, MemberNames.Normalize.toString(), normalize);
	}

	/**
	 * @return value of InputText
	 */
	public final java.lang.String getInputText()
	{
		return getInputText(getContext());
	}

	/**
	 * @param context
	 * @return value of InputText
	 */
	public final java.lang.String getInputText(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.InputText.toString());
	}

	/**
	 * Set value of InputText
	 * @param inputtext
	 */
	public final void setInputText(java.lang.String inputtext)
	{
		setInputText(getContext(), inputtext);
	}

	/**
	 * Set value of InputText
	 * @param context
	 * @param inputtext
	 */
	public final void setInputText(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String inputtext)
	{
		getMendixObject().setValue(context, MemberNames.InputText.toString(), inputtext);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return titanEmbeddingsMappingHelperMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final amazonbedrockconnector.proxies.TitanEmbeddingsMappingHelper that = (amazonbedrockconnector.proxies.TitanEmbeddingsMappingHelper) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
