// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package amazonbedrockconnector.proxies;

/**
 * This entity is needed for the JSON export. 
 * Do not use.
 */
public class TitanImageMappingHelper implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject titanImageMappingHelperMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AmazonBedrockConnector.TitanImageMappingHelper";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Text("Text"),
		NegativeText("NegativeText"),
		TitanImageMappingHelper_TitanImageOptions_Extension("AmazonBedrockConnector.TitanImageMappingHelper_TitanImageOptions_Extension");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public TitanImageMappingHelper(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected TitanImageMappingHelper(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject titanImageMappingHelperMendixObject)
	{
		if (titanImageMappingHelperMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!titanImageMappingHelperMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.titanImageMappingHelperMendixObject = titanImageMappingHelperMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static amazonbedrockconnector.proxies.TitanImageMappingHelper initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new amazonbedrockconnector.proxies.TitanImageMappingHelper(context, mendixObject);
	}

	public static amazonbedrockconnector.proxies.TitanImageMappingHelper load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return amazonbedrockconnector.proxies.TitanImageMappingHelper.initialize(context, mendixObject);
	}

	/**
	 * @return value of Text
	 */
	public final java.lang.String getText()
	{
		return getText(getContext());
	}

	/**
	 * @param context
	 * @return value of Text
	 */
	public final java.lang.String getText(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Text.toString());
	}

	/**
	 * Set value of Text
	 * @param text
	 */
	public final void setText(java.lang.String text)
	{
		setText(getContext(), text);
	}

	/**
	 * Set value of Text
	 * @param context
	 * @param text
	 */
	public final void setText(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String text)
	{
		getMendixObject().setValue(context, MemberNames.Text.toString(), text);
	}

	/**
	 * @return value of NegativeText
	 */
	public final java.lang.String getNegativeText()
	{
		return getNegativeText(getContext());
	}

	/**
	 * @param context
	 * @return value of NegativeText
	 */
	public final java.lang.String getNegativeText(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.NegativeText.toString());
	}

	/**
	 * Set value of NegativeText
	 * @param negativetext
	 */
	public final void setNegativeText(java.lang.String negativetext)
	{
		setNegativeText(getContext(), negativetext);
	}

	/**
	 * Set value of NegativeText
	 * @param context
	 * @param negativetext
	 */
	public final void setNegativeText(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String negativetext)
	{
		getMendixObject().setValue(context, MemberNames.NegativeText.toString(), negativetext);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of TitanImageMappingHelper_TitanImageOptions_Extension
	 */
	public final amazonbedrockconnector.proxies.TitanImageOptions_Extension getTitanImageMappingHelper_TitanImageOptions_Extension() throws com.mendix.core.CoreException
	{
		return getTitanImageMappingHelper_TitanImageOptions_Extension(getContext());
	}

	/**
	 * @param context
	 * @return value of TitanImageMappingHelper_TitanImageOptions_Extension
	 * @throws com.mendix.core.CoreException
	 */
	public final amazonbedrockconnector.proxies.TitanImageOptions_Extension getTitanImageMappingHelper_TitanImageOptions_Extension(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		amazonbedrockconnector.proxies.TitanImageOptions_Extension result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.TitanImageMappingHelper_TitanImageOptions_Extension.toString());
		if (identifier != null) {
			result = amazonbedrockconnector.proxies.TitanImageOptions_Extension.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of TitanImageMappingHelper_TitanImageOptions_Extension
	 * @param titanimagemappinghelper_titanimageoptions_extension
	 */
	public final void setTitanImageMappingHelper_TitanImageOptions_Extension(amazonbedrockconnector.proxies.TitanImageOptions_Extension titanimagemappinghelper_titanimageoptions_extension)
	{
		setTitanImageMappingHelper_TitanImageOptions_Extension(getContext(), titanimagemappinghelper_titanimageoptions_extension);
	}

	/**
	 * Set value of TitanImageMappingHelper_TitanImageOptions_Extension
	 * @param context
	 * @param titanimagemappinghelper_titanimageoptions_extension
	 */
	public final void setTitanImageMappingHelper_TitanImageOptions_Extension(com.mendix.systemwideinterfaces.core.IContext context, amazonbedrockconnector.proxies.TitanImageOptions_Extension titanimagemappinghelper_titanimageoptions_extension)
	{
		if (titanimagemappinghelper_titanimageoptions_extension == null) {
			getMendixObject().setValue(context, MemberNames.TitanImageMappingHelper_TitanImageOptions_Extension.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.TitanImageMappingHelper_TitanImageOptions_Extension.toString(), titanimagemappinghelper_titanimageoptions_extension.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return titanImageMappingHelperMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final amazonbedrockconnector.proxies.TitanImageMappingHelper that = (amazonbedrockconnector.proxies.TitanImageMappingHelper) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
