// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package amazonbedrockconnector.proxies;

/**
 * This entity extends the GenAICommons.Request entity with attributes that are specific to the Titan Image model family.
 */
public class TitanImageOptions_Extension implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject titanImageOptions_ExtensionMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AmazonBedrockConnector.TitanImageOptions_Extension";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		NegativeText("NegativeText"),
		TitanImageOptions_Extension_ImageOptions("AmazonBedrockConnector.TitanImageOptions_Extension_ImageOptions");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public TitanImageOptions_Extension(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected TitanImageOptions_Extension(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject titanImageOptions_ExtensionMendixObject)
	{
		if (titanImageOptions_ExtensionMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!titanImageOptions_ExtensionMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.titanImageOptions_ExtensionMendixObject = titanImageOptions_ExtensionMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static amazonbedrockconnector.proxies.TitanImageOptions_Extension initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new amazonbedrockconnector.proxies.TitanImageOptions_Extension(context, mendixObject);
	}

	public static amazonbedrockconnector.proxies.TitanImageOptions_Extension load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return amazonbedrockconnector.proxies.TitanImageOptions_Extension.initialize(context, mendixObject);
	}

	/**
	 * @return value of NegativeText
	 */
	public final java.lang.String getNegativeText()
	{
		return getNegativeText(getContext());
	}

	/**
	 * @param context
	 * @return value of NegativeText
	 */
	public final java.lang.String getNegativeText(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.NegativeText.toString());
	}

	/**
	 * Set value of NegativeText
	 * @param negativetext
	 */
	public final void setNegativeText(java.lang.String negativetext)
	{
		setNegativeText(getContext(), negativetext);
	}

	/**
	 * Set value of NegativeText
	 * @param context
	 * @param negativetext
	 */
	public final void setNegativeText(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String negativetext)
	{
		getMendixObject().setValue(context, MemberNames.NegativeText.toString(), negativetext);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of TitanImageOptions_Extension_ImageOptions
	 */
	public final genaicommons.proxies.ImageOptions getTitanImageOptions_Extension_ImageOptions() throws com.mendix.core.CoreException
	{
		return getTitanImageOptions_Extension_ImageOptions(getContext());
	}

	/**
	 * @param context
	 * @return value of TitanImageOptions_Extension_ImageOptions
	 * @throws com.mendix.core.CoreException
	 */
	public final genaicommons.proxies.ImageOptions getTitanImageOptions_Extension_ImageOptions(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		genaicommons.proxies.ImageOptions result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.TitanImageOptions_Extension_ImageOptions.toString());
		if (identifier != null) {
			result = genaicommons.proxies.ImageOptions.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of TitanImageOptions_Extension_ImageOptions
	 * @param titanimageoptions_extension_imageoptions
	 */
	public final void setTitanImageOptions_Extension_ImageOptions(genaicommons.proxies.ImageOptions titanimageoptions_extension_imageoptions)
	{
		setTitanImageOptions_Extension_ImageOptions(getContext(), titanimageoptions_extension_imageoptions);
	}

	/**
	 * Set value of TitanImageOptions_Extension_ImageOptions
	 * @param context
	 * @param titanimageoptions_extension_imageoptions
	 */
	public final void setTitanImageOptions_Extension_ImageOptions(com.mendix.systemwideinterfaces.core.IContext context, genaicommons.proxies.ImageOptions titanimageoptions_extension_imageoptions)
	{
		if (titanimageoptions_extension_imageoptions == null) {
			getMendixObject().setValue(context, MemberNames.TitanImageOptions_Extension_ImageOptions.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.TitanImageOptions_Extension_ImageOptions.toString(), titanimageoptions_extension_imageoptions.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return titanImageOptions_ExtensionMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final amazonbedrockconnector.proxies.TitanImageOptions_Extension that = (amazonbedrockconnector.proxies.TitanImageOptions_Extension) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
