// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package openaiconnector.proxies;

/**
 * This is a helper entity edit the api key to be stored in the Configuration entity.
 */
public class ApiKey implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject apiKeyMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "OpenAIConnector.ApiKey";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ApiKey("ApiKey"),
		ApiKey_Configuration("OpenAIConnector.ApiKey_Configuration"),
		ApiKey_AzureAISearchResource("OpenAIConnector.ApiKey_AzureAISearchResource");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ApiKey(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ApiKey(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject apiKeyMendixObject)
	{
		if (apiKeyMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!apiKeyMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.apiKeyMendixObject = apiKeyMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static openaiconnector.proxies.ApiKey initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new openaiconnector.proxies.ApiKey(context, mendixObject);
	}

	public static openaiconnector.proxies.ApiKey load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return openaiconnector.proxies.ApiKey.initialize(context, mendixObject);
	}

	/**
	 * @return value of ApiKey
	 */
	public final java.lang.String getApiKey()
	{
		return getApiKey(getContext());
	}

	/**
	 * @param context
	 * @return value of ApiKey
	 */
	public final java.lang.String getApiKey(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ApiKey.toString());
	}

	/**
	 * Set value of ApiKey
	 * @param apikey
	 */
	public final void setApiKey(java.lang.String apikey)
	{
		setApiKey(getContext(), apikey);
	}

	/**
	 * Set value of ApiKey
	 * @param context
	 * @param apikey
	 */
	public final void setApiKey(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String apikey)
	{
		getMendixObject().setValue(context, MemberNames.ApiKey.toString(), apikey);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ApiKey_Configuration
	 */
	public final openaiconnector.proxies.Configuration getApiKey_Configuration() throws com.mendix.core.CoreException
	{
		return getApiKey_Configuration(getContext());
	}

	/**
	 * @param context
	 * @return value of ApiKey_Configuration
	 * @throws com.mendix.core.CoreException
	 */
	public final openaiconnector.proxies.Configuration getApiKey_Configuration(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		openaiconnector.proxies.Configuration result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ApiKey_Configuration.toString());
		if (identifier != null) {
			result = openaiconnector.proxies.Configuration.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ApiKey_Configuration
	 * @param apikey_configuration
	 */
	public final void setApiKey_Configuration(openaiconnector.proxies.Configuration apikey_configuration)
	{
		setApiKey_Configuration(getContext(), apikey_configuration);
	}

	/**
	 * Set value of ApiKey_Configuration
	 * @param context
	 * @param apikey_configuration
	 */
	public final void setApiKey_Configuration(com.mendix.systemwideinterfaces.core.IContext context, openaiconnector.proxies.Configuration apikey_configuration)
	{
		if (apikey_configuration == null) {
			getMendixObject().setValue(context, MemberNames.ApiKey_Configuration.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ApiKey_Configuration.toString(), apikey_configuration.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ApiKey_AzureAISearchResource
	 */
	public final openaiconnector.proxies.AzureAISearchResource getApiKey_AzureAISearchResource() throws com.mendix.core.CoreException
	{
		return getApiKey_AzureAISearchResource(getContext());
	}

	/**
	 * @param context
	 * @return value of ApiKey_AzureAISearchResource
	 * @throws com.mendix.core.CoreException
	 */
	public final openaiconnector.proxies.AzureAISearchResource getApiKey_AzureAISearchResource(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		openaiconnector.proxies.AzureAISearchResource result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ApiKey_AzureAISearchResource.toString());
		if (identifier != null) {
			result = openaiconnector.proxies.AzureAISearchResource.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ApiKey_AzureAISearchResource
	 * @param apikey_azureaisearchresource
	 */
	public final void setApiKey_AzureAISearchResource(openaiconnector.proxies.AzureAISearchResource apikey_azureaisearchresource)
	{
		setApiKey_AzureAISearchResource(getContext(), apikey_azureaisearchresource);
	}

	/**
	 * Set value of ApiKey_AzureAISearchResource
	 * @param context
	 * @param apikey_azureaisearchresource
	 */
	public final void setApiKey_AzureAISearchResource(com.mendix.systemwideinterfaces.core.IContext context, openaiconnector.proxies.AzureAISearchResource apikey_azureaisearchresource)
	{
		if (apikey_azureaisearchresource == null) {
			getMendixObject().setValue(context, MemberNames.ApiKey_AzureAISearchResource.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ApiKey_AzureAISearchResource.toString(), apikey_azureaisearchresource.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return apiKeyMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final openaiconnector.proxies.ApiKey that = (openaiconnector.proxies.ApiKey) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
