// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package openaiconnector.proxies;

/**
 * This entity is used to test an existing configuration by executing a simple chat completions API call.
 */
public class ConfigurationTest implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject configurationTestMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "OpenAIConnector.ConfigurationTest";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		TestSuccess("TestSuccess"),
		ConfigurationTest_OpenAIDeployedModel("OpenAIConnector.ConfigurationTest_OpenAIDeployedModel");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ConfigurationTest(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ConfigurationTest(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject configurationTestMendixObject)
	{
		if (configurationTestMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!configurationTestMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.configurationTestMendixObject = configurationTestMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static openaiconnector.proxies.ConfigurationTest initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new openaiconnector.proxies.ConfigurationTest(context, mendixObject);
	}

	public static openaiconnector.proxies.ConfigurationTest load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return openaiconnector.proxies.ConfigurationTest.initialize(context, mendixObject);
	}

	/**
	 * Get value of TestSuccess
	 * @param testsuccess
	 */
	public final openaiconnector.proxies.ENUM_TestSuccess getTestSuccess()
	{
		return getTestSuccess(getContext());
	}

	/**
	 * @param context
	 * @return value of TestSuccess
	 */
	public final openaiconnector.proxies.ENUM_TestSuccess getTestSuccess(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.TestSuccess.toString());
		if (obj == null) {
			return null;
		}
		return openaiconnector.proxies.ENUM_TestSuccess.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of TestSuccess
	 * @param testsuccess
	 */
	public final void setTestSuccess(openaiconnector.proxies.ENUM_TestSuccess testsuccess)
	{
		setTestSuccess(getContext(), testsuccess);
	}

	/**
	 * Set value of TestSuccess
	 * @param context
	 * @param testsuccess
	 */
	public final void setTestSuccess(com.mendix.systemwideinterfaces.core.IContext context, openaiconnector.proxies.ENUM_TestSuccess testsuccess)
	{
		if (testsuccess != null) {
			getMendixObject().setValue(context, MemberNames.TestSuccess.toString(), testsuccess.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.TestSuccess.toString(), null);
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ConfigurationTest_OpenAIDeployedModel
	 */
	public final openaiconnector.proxies.OpenAIDeployedModel getConfigurationTest_OpenAIDeployedModel() throws com.mendix.core.CoreException
	{
		return getConfigurationTest_OpenAIDeployedModel(getContext());
	}

	/**
	 * @param context
	 * @return value of ConfigurationTest_OpenAIDeployedModel
	 * @throws com.mendix.core.CoreException
	 */
	public final openaiconnector.proxies.OpenAIDeployedModel getConfigurationTest_OpenAIDeployedModel(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		openaiconnector.proxies.OpenAIDeployedModel result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ConfigurationTest_OpenAIDeployedModel.toString());
		if (identifier != null) {
			result = openaiconnector.proxies.OpenAIDeployedModel.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ConfigurationTest_OpenAIDeployedModel
	 * @param configurationtest_openaideployedmodel
	 */
	public final void setConfigurationTest_OpenAIDeployedModel(openaiconnector.proxies.OpenAIDeployedModel configurationtest_openaideployedmodel)
	{
		setConfigurationTest_OpenAIDeployedModel(getContext(), configurationtest_openaideployedmodel);
	}

	/**
	 * Set value of ConfigurationTest_OpenAIDeployedModel
	 * @param context
	 * @param configurationtest_openaideployedmodel
	 */
	public final void setConfigurationTest_OpenAIDeployedModel(com.mendix.systemwideinterfaces.core.IContext context, openaiconnector.proxies.OpenAIDeployedModel configurationtest_openaideployedmodel)
	{
		if (configurationtest_openaideployedmodel == null) {
			getMendixObject().setValue(context, MemberNames.ConfigurationTest_OpenAIDeployedModel.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ConfigurationTest_OpenAIDeployedModel.toString(), configurationtest_openaideployedmodel.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return configurationTestMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final openaiconnector.proxies.ConfigurationTest that = (openaiconnector.proxies.ConfigurationTest) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
