// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package openaiconnector.proxies;

/**
 * This entity is used to store the API credentials and endpoints in the configuration for OpenAI or Azure OpenAI.
 */
public class Configuration implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject configurationMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "OpenAIConnector.Configuration";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		DisplayName("DisplayName"),
		ApiType("ApiType"),
		Endpoint("Endpoint"),
		ApiKey("ApiKey"),
		KeyType("KeyType"),
		IsNativeOpenAI("IsNativeOpenAI");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Configuration(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Configuration(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject configurationMendixObject)
	{
		if (configurationMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!configurationMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.configurationMendixObject = configurationMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static openaiconnector.proxies.Configuration initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		if (mendixObject.isInstanceOf("MistralConnector.MistralConfiguration")) {
			return mistralconnector.proxies.MistralConfiguration.initialize(context, mendixObject);
		}
		return new openaiconnector.proxies.Configuration(context, mendixObject);
	}

	public static openaiconnector.proxies.Configuration load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return openaiconnector.proxies.Configuration.initialize(context, mendixObject);
	}

	public static java.util.List<? extends openaiconnector.proxies.Configuration> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> openaiconnector.proxies.Configuration.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of DisplayName
	 */
	public final java.lang.String getDisplayName()
	{
		return getDisplayName(getContext());
	}

	/**
	 * @param context
	 * @return value of DisplayName
	 */
	public final java.lang.String getDisplayName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DisplayName.toString());
	}

	/**
	 * Set value of DisplayName
	 * @param displayname
	 */
	public final void setDisplayName(java.lang.String displayname)
	{
		setDisplayName(getContext(), displayname);
	}

	/**
	 * Set value of DisplayName
	 * @param context
	 * @param displayname
	 */
	public final void setDisplayName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String displayname)
	{
		getMendixObject().setValue(context, MemberNames.DisplayName.toString(), displayname);
	}

	/**
	 * Get value of ApiType
	 * @param apitype
	 */
	public final openaiconnector.proxies.ENUM_ApiType getApiType()
	{
		return getApiType(getContext());
	}

	/**
	 * @param context
	 * @return value of ApiType
	 */
	public final openaiconnector.proxies.ENUM_ApiType getApiType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.ApiType.toString());
		if (obj == null) {
			return null;
		}
		return openaiconnector.proxies.ENUM_ApiType.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of ApiType
	 * @param apitype
	 */
	public final void setApiType(openaiconnector.proxies.ENUM_ApiType apitype)
	{
		setApiType(getContext(), apitype);
	}

	/**
	 * Set value of ApiType
	 * @param context
	 * @param apitype
	 */
	public final void setApiType(com.mendix.systemwideinterfaces.core.IContext context, openaiconnector.proxies.ENUM_ApiType apitype)
	{
		if (apitype != null) {
			getMendixObject().setValue(context, MemberNames.ApiType.toString(), apitype.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.ApiType.toString(), null);
		}
	}

	/**
	 * @return value of Endpoint
	 */
	public final java.lang.String getEndpoint()
	{
		return getEndpoint(getContext());
	}

	/**
	 * @param context
	 * @return value of Endpoint
	 */
	public final java.lang.String getEndpoint(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Endpoint.toString());
	}

	/**
	 * Set value of Endpoint
	 * @param endpoint
	 */
	public final void setEndpoint(java.lang.String endpoint)
	{
		setEndpoint(getContext(), endpoint);
	}

	/**
	 * Set value of Endpoint
	 * @param context
	 * @param endpoint
	 */
	public final void setEndpoint(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String endpoint)
	{
		getMendixObject().setValue(context, MemberNames.Endpoint.toString(), endpoint);
	}

	/**
	 * @return value of ApiKey
	 */
	public final java.lang.String getApiKey()
	{
		return getApiKey(getContext());
	}

	/**
	 * @param context
	 * @return value of ApiKey
	 */
	public final java.lang.String getApiKey(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ApiKey.toString());
	}

	/**
	 * Set value of ApiKey
	 * @param apikey
	 */
	public final void setApiKey(java.lang.String apikey)
	{
		setApiKey(getContext(), apikey);
	}

	/**
	 * Set value of ApiKey
	 * @param context
	 * @param apikey
	 */
	public final void setApiKey(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String apikey)
	{
		getMendixObject().setValue(context, MemberNames.ApiKey.toString(), apikey);
	}

	/**
	 * Get value of KeyType
	 * @param keytype
	 */
	public final openaiconnector.proxies.ENUM_KeyType getKeyType()
	{
		return getKeyType(getContext());
	}

	/**
	 * @param context
	 * @return value of KeyType
	 */
	public final openaiconnector.proxies.ENUM_KeyType getKeyType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.KeyType.toString());
		if (obj == null) {
			return null;
		}
		return openaiconnector.proxies.ENUM_KeyType.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of KeyType
	 * @param keytype
	 */
	public final void setKeyType(openaiconnector.proxies.ENUM_KeyType keytype)
	{
		setKeyType(getContext(), keytype);
	}

	/**
	 * Set value of KeyType
	 * @param context
	 * @param keytype
	 */
	public final void setKeyType(com.mendix.systemwideinterfaces.core.IContext context, openaiconnector.proxies.ENUM_KeyType keytype)
	{
		if (keytype != null) {
			getMendixObject().setValue(context, MemberNames.KeyType.toString(), keytype.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.KeyType.toString(), null);
		}
	}

	/**
	 * @return value of IsNativeOpenAI
	 */
	public final java.lang.Boolean getIsNativeOpenAI()
	{
		return getIsNativeOpenAI(getContext());
	}

	/**
	 * @param context
	 * @return value of IsNativeOpenAI
	 */
	public final java.lang.Boolean getIsNativeOpenAI(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsNativeOpenAI.toString());
	}

	/**
	 * Set value of IsNativeOpenAI
	 * @param isnativeopenai
	 */
	public final void setIsNativeOpenAI(java.lang.Boolean isnativeopenai)
	{
		setIsNativeOpenAI(getContext(), isnativeopenai);
	}

	/**
	 * Set value of IsNativeOpenAI
	 * @param context
	 * @param isnativeopenai
	 */
	public final void setIsNativeOpenAI(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isnativeopenai)
	{
		getMendixObject().setValue(context, MemberNames.IsNativeOpenAI.toString(), isnativeopenai);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return configurationMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final openaiconnector.proxies.Configuration that = (openaiconnector.proxies.Configuration) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
