// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package openaiconnector.proxies;

/**
 * Internal helper entity - for mapping purposes only.
 * DO NOT USE outside of connector.
 */
public class EmbeddingsRequestMapping implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject embeddingsRequestMappingMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "OpenAIConnector.EmbeddingsRequestMapping";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Model("Model"),
		Dimensions("Dimensions"),
		EmbeddingsRequestMapping_ChunkCollection("OpenAIConnector.EmbeddingsRequestMapping_ChunkCollection");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public EmbeddingsRequestMapping(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected EmbeddingsRequestMapping(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject embeddingsRequestMappingMendixObject)
	{
		if (embeddingsRequestMappingMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!embeddingsRequestMappingMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.embeddingsRequestMappingMendixObject = embeddingsRequestMappingMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static openaiconnector.proxies.EmbeddingsRequestMapping initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new openaiconnector.proxies.EmbeddingsRequestMapping(context, mendixObject);
	}

	public static openaiconnector.proxies.EmbeddingsRequestMapping load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return openaiconnector.proxies.EmbeddingsRequestMapping.initialize(context, mendixObject);
	}

	/**
	 * @return value of Model
	 */
	public final java.lang.String getModel()
	{
		return getModel(getContext());
	}

	/**
	 * @param context
	 * @return value of Model
	 */
	public final java.lang.String getModel(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Model.toString());
	}

	/**
	 * Set value of Model
	 * @param model
	 */
	public final void setModel(java.lang.String model)
	{
		setModel(getContext(), model);
	}

	/**
	 * Set value of Model
	 * @param context
	 * @param model
	 */
	public final void setModel(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String model)
	{
		getMendixObject().setValue(context, MemberNames.Model.toString(), model);
	}

	/**
	 * @return value of Dimensions
	 */
	public final java.lang.Integer getDimensions()
	{
		return getDimensions(getContext());
	}

	/**
	 * @param context
	 * @return value of Dimensions
	 */
	public final java.lang.Integer getDimensions(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Dimensions.toString());
	}

	/**
	 * Set value of Dimensions
	 * @param dimensions
	 */
	public final void setDimensions(java.lang.Integer dimensions)
	{
		setDimensions(getContext(), dimensions);
	}

	/**
	 * Set value of Dimensions
	 * @param context
	 * @param dimensions
	 */
	public final void setDimensions(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer dimensions)
	{
		getMendixObject().setValue(context, MemberNames.Dimensions.toString(), dimensions);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of EmbeddingsRequestMapping_ChunkCollection
	 */
	public final genaicommons.proxies.ChunkCollection getEmbeddingsRequestMapping_ChunkCollection() throws com.mendix.core.CoreException
	{
		return getEmbeddingsRequestMapping_ChunkCollection(getContext());
	}

	/**
	 * @param context
	 * @return value of EmbeddingsRequestMapping_ChunkCollection
	 * @throws com.mendix.core.CoreException
	 */
	public final genaicommons.proxies.ChunkCollection getEmbeddingsRequestMapping_ChunkCollection(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		genaicommons.proxies.ChunkCollection result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.EmbeddingsRequestMapping_ChunkCollection.toString());
		if (identifier != null) {
			result = genaicommons.proxies.ChunkCollection.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of EmbeddingsRequestMapping_ChunkCollection
	 * @param embeddingsrequestmapping_chunkcollection
	 */
	public final void setEmbeddingsRequestMapping_ChunkCollection(genaicommons.proxies.ChunkCollection embeddingsrequestmapping_chunkcollection)
	{
		setEmbeddingsRequestMapping_ChunkCollection(getContext(), embeddingsrequestmapping_chunkcollection);
	}

	/**
	 * Set value of EmbeddingsRequestMapping_ChunkCollection
	 * @param context
	 * @param embeddingsrequestmapping_chunkcollection
	 */
	public final void setEmbeddingsRequestMapping_ChunkCollection(com.mendix.systemwideinterfaces.core.IContext context, genaicommons.proxies.ChunkCollection embeddingsrequestmapping_chunkcollection)
	{
		if (embeddingsrequestmapping_chunkcollection == null) {
			getMendixObject().setValue(context, MemberNames.EmbeddingsRequestMapping_ChunkCollection.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.EmbeddingsRequestMapping_ChunkCollection.toString(), embeddingsrequestmapping_chunkcollection.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return embeddingsRequestMappingMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final openaiconnector.proxies.EmbeddingsRequestMapping that = (openaiconnector.proxies.EmbeddingsRequestMapping) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
