// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package openaiconnector.proxies;

/**
 * This is a list of supported visual styles for the generated images. It depends on the model whether this field is supported.
 */
public enum ENUM_Style
{
	vivid("28b95230-9536-4951-b9da-2a373cf1622b"),
	natural("044381c5-19f2-4e7b-abb6-b47b833a77f3");

	private final java.lang.String i18nCaptionKey;
	
	private ENUM_Style(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
