// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package openaiconnector.proxies;

/**
 * This represents the detail level of the image. 
 */
public enum ENUM_ImageDetail
{
	low("4a4a8059-38f8-4307-8b8e-a6347d62c51c"),
	high("bf83d2c0-4944-4499-be03-ddbe40c8979e"),
	auto("4d7cf59c-63b0-4b9d-a563-812ecec76a6e");

	private final java.lang.String i18nCaptionKey;
	
	private ENUM_ImageDetail(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
