// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package openaiconnector.proxies;

public enum ENUM_TestSuccess
{
	Success("bc4eb6d1-5e4e-46a6-b872-0fe1226adb39"),
	Failure("60c8cc20-0103-4dcf-8da1-019c11aa9d16");

	private final java.lang.String i18nCaptionKey;
	
	private ENUM_TestSuccess(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
