// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package openaiconnector.proxies;

/**
 * This is a list of key types that can be used during the connection to the APIs of Azure OpenAI.
 */
public enum ENUM_KeyType
{
	Bearer_Token("6851660a-e0e3-4ebf-a445-464536e039af"),
	API_key("03afd486-73a4-406d-8fdc-6c6160c4b2c9");

	private final java.lang.String i18nCaptionKey;
	
	private ENUM_KeyType(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
