// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package openaiconnector.proxies;

/**
 * This is a list of supported response types for generated images. Currently, images can be returned as a URL to a PNG file, or as a base64-encoded string representation of the image.
 */
public enum ENUM_ResponseFormat_Image
{
	url("29ac0f82-477c-4156-a16b-7ac74c04b001"),
	b64_json("ef114b33-792e-432a-8522-5f70f667d60d");

	private final java.lang.String i18nCaptionKey;
	
	private ENUM_ResponseFormat_Image(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
