// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package openaiconnector.proxies;

/**
 * This is a list of supported response types for chat completions. Currently, chat completions can be returned in normal text format (supported for all chat completions models available in the connector), as well as in JSON mode for specific models.
 */
public enum ENUM_ResponseFormat_Chat
{
	json_object("f70fbbdd-c129-4917-b2e5-ce8da1ab33f0"),
	text("8c201b71-50a1-4d32-9863-a30f8be20008");

	private final java.lang.String i18nCaptionKey;
	
	private ENUM_ResponseFormat_Chat(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
