// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package openaiconnector.proxies;

/**
 * Required
 * 
 * An image generations request that creates an image (GeneratedImage) for a given prompt.
 * 
 * See: https://platform.openai.com/docs/api-reference/images/create
 */
public class ImageGenerationsRequestMapping implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject imageGenerationsRequestMappingMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "OpenAIConnector.ImageGenerationsRequestMapping";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Prompt("Prompt"),
		Model("Model"),
		N("N"),
		Quality("Quality"),
		ResponseFormat("ResponseFormat"),
		Size("Size"),
		Style("Style"),
		User("User");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ImageGenerationsRequestMapping(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ImageGenerationsRequestMapping(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject imageGenerationsRequestMappingMendixObject)
	{
		if (imageGenerationsRequestMappingMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!imageGenerationsRequestMappingMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.imageGenerationsRequestMappingMendixObject = imageGenerationsRequestMappingMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static openaiconnector.proxies.ImageGenerationsRequestMapping initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new openaiconnector.proxies.ImageGenerationsRequestMapping(context, mendixObject);
	}

	public static openaiconnector.proxies.ImageGenerationsRequestMapping load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return openaiconnector.proxies.ImageGenerationsRequestMapping.initialize(context, mendixObject);
	}

	/**
	 * @return value of Prompt
	 */
	public final java.lang.String getPrompt()
	{
		return getPrompt(getContext());
	}

	/**
	 * @param context
	 * @return value of Prompt
	 */
	public final java.lang.String getPrompt(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Prompt.toString());
	}

	/**
	 * Set value of Prompt
	 * @param prompt
	 */
	public final void setPrompt(java.lang.String prompt)
	{
		setPrompt(getContext(), prompt);
	}

	/**
	 * Set value of Prompt
	 * @param context
	 * @param prompt
	 */
	public final void setPrompt(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String prompt)
	{
		getMendixObject().setValue(context, MemberNames.Prompt.toString(), prompt);
	}

	/**
	 * @return value of Model
	 */
	public final java.lang.String getModel()
	{
		return getModel(getContext());
	}

	/**
	 * @param context
	 * @return value of Model
	 */
	public final java.lang.String getModel(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Model.toString());
	}

	/**
	 * Set value of Model
	 * @param model
	 */
	public final void setModel(java.lang.String model)
	{
		setModel(getContext(), model);
	}

	/**
	 * Set value of Model
	 * @param context
	 * @param model
	 */
	public final void setModel(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String model)
	{
		getMendixObject().setValue(context, MemberNames.Model.toString(), model);
	}

	/**
	 * @return value of N
	 */
	public final java.lang.Integer getN()
	{
		return getN(getContext());
	}

	/**
	 * @param context
	 * @return value of N
	 */
	public final java.lang.Integer getN(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.N.toString());
	}

	/**
	 * Set value of N
	 * @param n
	 */
	public final void setN(java.lang.Integer n)
	{
		setN(getContext(), n);
	}

	/**
	 * Set value of N
	 * @param context
	 * @param n
	 */
	public final void setN(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer n)
	{
		getMendixObject().setValue(context, MemberNames.N.toString(), n);
	}

	/**
	 * @return value of Quality
	 */
	public final java.lang.String getQuality()
	{
		return getQuality(getContext());
	}

	/**
	 * @param context
	 * @return value of Quality
	 */
	public final java.lang.String getQuality(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Quality.toString());
	}

	/**
	 * Set value of Quality
	 * @param quality
	 */
	public final void setQuality(java.lang.String quality)
	{
		setQuality(getContext(), quality);
	}

	/**
	 * Set value of Quality
	 * @param context
	 * @param quality
	 */
	public final void setQuality(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String quality)
	{
		getMendixObject().setValue(context, MemberNames.Quality.toString(), quality);
	}

	/**
	 * @return value of ResponseFormat
	 */
	public final java.lang.String getResponseFormat()
	{
		return getResponseFormat(getContext());
	}

	/**
	 * @param context
	 * @return value of ResponseFormat
	 */
	public final java.lang.String getResponseFormat(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ResponseFormat.toString());
	}

	/**
	 * Set value of ResponseFormat
	 * @param responseformat
	 */
	public final void setResponseFormat(java.lang.String responseformat)
	{
		setResponseFormat(getContext(), responseformat);
	}

	/**
	 * Set value of ResponseFormat
	 * @param context
	 * @param responseformat
	 */
	public final void setResponseFormat(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String responseformat)
	{
		getMendixObject().setValue(context, MemberNames.ResponseFormat.toString(), responseformat);
	}

	/**
	 * @return value of Size
	 */
	public final java.lang.String getSize()
	{
		return getSize(getContext());
	}

	/**
	 * @param context
	 * @return value of Size
	 */
	public final java.lang.String getSize(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Size.toString());
	}

	/**
	 * Set value of Size
	 * @param size
	 */
	public final void setSize(java.lang.String size)
	{
		setSize(getContext(), size);
	}

	/**
	 * Set value of Size
	 * @param context
	 * @param size
	 */
	public final void setSize(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String size)
	{
		getMendixObject().setValue(context, MemberNames.Size.toString(), size);
	}

	/**
	 * @return value of Style
	 */
	public final java.lang.String getStyle()
	{
		return getStyle(getContext());
	}

	/**
	 * @param context
	 * @return value of Style
	 */
	public final java.lang.String getStyle(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Style.toString());
	}

	/**
	 * Set value of Style
	 * @param style
	 */
	public final void setStyle(java.lang.String style)
	{
		setStyle(getContext(), style);
	}

	/**
	 * Set value of Style
	 * @param context
	 * @param style
	 */
	public final void setStyle(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String style)
	{
		getMendixObject().setValue(context, MemberNames.Style.toString(), style);
	}

	/**
	 * @return value of User
	 */
	public final java.lang.String getUser()
	{
		return getUser(getContext());
	}

	/**
	 * @param context
	 * @return value of User
	 */
	public final java.lang.String getUser(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.User.toString());
	}

	/**
	 * Set value of User
	 * @param user
	 */
	public final void setUser(java.lang.String user)
	{
		setUser(getContext(), user);
	}

	/**
	 * Set value of User
	 * @param context
	 * @param user
	 */
	public final void setUser(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String user)
	{
		getMendixObject().setValue(context, MemberNames.User.toString(), user);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return imageGenerationsRequestMappingMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final openaiconnector.proxies.ImageGenerationsRequestMapping that = (openaiconnector.proxies.ImageGenerationsRequestMapping) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
