// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package openaiconnector.proxies;

/**
 * This entity contains details about an index resource containing search documents available in an Azure AI Search service. 
 * It includes a name which is used in every interaction with an Azure AI Search resource, to specify the index that is relevant for the data interactions.
 */
public class Index extends genaicommons.proxies.DeployedKnowledgeBase
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "OpenAIConnector.Index";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		DisplayName("DisplayName"),
		Name("Name"),
		IsActive("IsActive"),
		Microflow("Microflow"),
		Architecture("Architecture"),
		Index_AzureAISearchResource("OpenAIConnector.Index_AzureAISearchResource");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Index(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Index(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject indexMendixObject)
	{
		super(context, indexMendixObject);
		if (!indexMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static openaiconnector.proxies.Index initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new openaiconnector.proxies.Index(context, mendixObject);
	}

	public static openaiconnector.proxies.Index load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return openaiconnector.proxies.Index.initialize(context, mendixObject);
	}

	public static java.util.List<openaiconnector.proxies.Index> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> openaiconnector.proxies.Index.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Index_AzureAISearchResource
	 */
	public final openaiconnector.proxies.AzureAISearchResource getIndex_AzureAISearchResource() throws com.mendix.core.CoreException
	{
		return getIndex_AzureAISearchResource(getContext());
	}

	/**
	 * @param context
	 * @return value of Index_AzureAISearchResource
	 * @throws com.mendix.core.CoreException
	 */
	public final openaiconnector.proxies.AzureAISearchResource getIndex_AzureAISearchResource(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		openaiconnector.proxies.AzureAISearchResource result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Index_AzureAISearchResource.toString());
		if (identifier != null) {
			result = openaiconnector.proxies.AzureAISearchResource.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Index_AzureAISearchResource
	 * @param index_azureaisearchresource
	 */
	public final void setIndex_AzureAISearchResource(openaiconnector.proxies.AzureAISearchResource index_azureaisearchresource)
	{
		setIndex_AzureAISearchResource(getContext(), index_azureaisearchresource);
	}

	/**
	 * Set value of Index_AzureAISearchResource
	 * @param context
	 * @param index_azureaisearchresource
	 */
	public final void setIndex_AzureAISearchResource(com.mendix.systemwideinterfaces.core.IContext context, openaiconnector.proxies.AzureAISearchResource index_azureaisearchresource)
	{
		if (index_azureaisearchresource == null) {
			getMendixObject().setValue(context, MemberNames.Index_AzureAISearchResource.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Index_AzureAISearchResource.toString(), index_azureaisearchresource.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final openaiconnector.proxies.Index that = (openaiconnector.proxies.Index) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
