// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package openaiconnector.proxies;

/**
 * OpenAIDeployedModel is a specialization of GenAICommons.DeployedModel, which is associated to the Configuration. To make the operations more compatible and interchangeable with operations from other GenAI connectors based on the GenAI commons module, the operations technically accept DeployedModel objects, but internally required to be of the specialization OpenAIDeployedModel.
 */
public class OpenAIDeployedModel extends genaicommons.proxies.DeployedModel
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "OpenAIConnector.OpenAIDeployedModel";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		AzureApiVersion("AzureApiVersion"),
		DisplayName("DisplayName"),
		Architecture("Architecture"),
		Model("Model"),
		OutputModality("OutputModality"),
		Microflow("Microflow"),
		SupportsSystemPrompt("SupportsSystemPrompt"),
		SupportsConversationsWithHistory("SupportsConversationsWithHistory"),
		SupportsFunctionCalling("SupportsFunctionCalling"),
		IsActive("IsActive"),
		OpenAIDeployedModel_Configuration("OpenAIConnector.OpenAIDeployedModel_Configuration"),
		DeployedModel_InputModality("GenAICommons.DeployedModel_InputModality");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public OpenAIDeployedModel(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected OpenAIDeployedModel(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject openAIDeployedModelMendixObject)
	{
		super(context, openAIDeployedModelMendixObject);
		if (!openAIDeployedModelMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static openaiconnector.proxies.OpenAIDeployedModel initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		if (mendixObject.isInstanceOf("MistralConnector.MistralDeployedModel")) {
			return mistralconnector.proxies.MistralDeployedModel.initialize(context, mendixObject);
		}
		return new openaiconnector.proxies.OpenAIDeployedModel(context, mendixObject);
	}

	public static openaiconnector.proxies.OpenAIDeployedModel load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return openaiconnector.proxies.OpenAIDeployedModel.initialize(context, mendixObject);
	}

	public static java.util.List<? extends openaiconnector.proxies.OpenAIDeployedModel> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> openaiconnector.proxies.OpenAIDeployedModel.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of AzureApiVersion
	 */
	public final java.lang.String getAzureApiVersion()
	{
		return getAzureApiVersion(getContext());
	}

	/**
	 * @param context
	 * @return value of AzureApiVersion
	 */
	public final java.lang.String getAzureApiVersion(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.AzureApiVersion.toString());
	}

	/**
	 * Set value of AzureApiVersion
	 * @param azureapiversion
	 */
	public final void setAzureApiVersion(java.lang.String azureapiversion)
	{
		setAzureApiVersion(getContext(), azureapiversion);
	}

	/**
	 * Set value of AzureApiVersion
	 * @param context
	 * @param azureapiversion
	 */
	public final void setAzureApiVersion(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String azureapiversion)
	{
		getMendixObject().setValue(context, MemberNames.AzureApiVersion.toString(), azureapiversion);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of OpenAIDeployedModel_Configuration
	 */
	public final openaiconnector.proxies.Configuration getOpenAIDeployedModel_Configuration() throws com.mendix.core.CoreException
	{
		return getOpenAIDeployedModel_Configuration(getContext());
	}

	/**
	 * @param context
	 * @return value of OpenAIDeployedModel_Configuration
	 * @throws com.mendix.core.CoreException
	 */
	public final openaiconnector.proxies.Configuration getOpenAIDeployedModel_Configuration(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		openaiconnector.proxies.Configuration result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.OpenAIDeployedModel_Configuration.toString());
		if (identifier != null) {
			result = openaiconnector.proxies.Configuration.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of OpenAIDeployedModel_Configuration
	 * @param openaideployedmodel_configuration
	 */
	public final void setOpenAIDeployedModel_Configuration(openaiconnector.proxies.Configuration openaideployedmodel_configuration)
	{
		setOpenAIDeployedModel_Configuration(getContext(), openaideployedmodel_configuration);
	}

	/**
	 * Set value of OpenAIDeployedModel_Configuration
	 * @param context
	 * @param openaideployedmodel_configuration
	 */
	public final void setOpenAIDeployedModel_Configuration(com.mendix.systemwideinterfaces.core.IContext context, openaiconnector.proxies.Configuration openaideployedmodel_configuration)
	{
		if (openaideployedmodel_configuration == null) {
			getMendixObject().setValue(context, MemberNames.OpenAIDeployedModel_Configuration.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.OpenAIDeployedModel_Configuration.toString(), openaideployedmodel_configuration.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final openaiconnector.proxies.OpenAIDeployedModel that = (openaiconnector.proxies.OpenAIDeployedModel) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
