// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package openaiconnector.proxies;

/**
 * OpenAIFileContent is an entity that can be passed along the request, for example when using vision. Besides the attributes from its GenAI Commons generalization FileContent, Detail can be used to describe the detail level of an image. The chat completions operations can be used interchangeably with OpenAIFileContent as well as with GenAI Commons FileContent objects.
 */
public class OpenAIImageContent extends genaicommons.proxies.FileContent
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "OpenAIConnector.OpenAIImageContent";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Detail("Detail"),
		FileContent("FileContent"),
		ContentType("ContentType"),
		FileType("FileType"),
		TextContent("TextContent"),
		FileExtension("FileExtension"),
		FileName("FileName");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public OpenAIImageContent(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected OpenAIImageContent(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject openAIImageContentMendixObject)
	{
		super(context, openAIImageContentMendixObject);
		if (!openAIImageContentMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static openaiconnector.proxies.OpenAIImageContent initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new openaiconnector.proxies.OpenAIImageContent(context, mendixObject);
	}

	public static openaiconnector.proxies.OpenAIImageContent load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return openaiconnector.proxies.OpenAIImageContent.initialize(context, mendixObject);
	}

	/**
	 * Get value of Detail
	 * @param detail
	 */
	public final openaiconnector.proxies.ENUM_ImageDetail getDetail()
	{
		return getDetail(getContext());
	}

	/**
	 * @param context
	 * @return value of Detail
	 */
	public final openaiconnector.proxies.ENUM_ImageDetail getDetail(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Detail.toString());
		if (obj == null) {
			return null;
		}
		return openaiconnector.proxies.ENUM_ImageDetail.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Detail
	 * @param detail
	 */
	public final void setDetail(openaiconnector.proxies.ENUM_ImageDetail detail)
	{
		setDetail(getContext(), detail);
	}

	/**
	 * Set value of Detail
	 * @param context
	 * @param detail
	 */
	public final void setDetail(com.mendix.systemwideinterfaces.core.IContext context, openaiconnector.proxies.ENUM_ImageDetail detail)
	{
		if (detail != null) {
			getMendixObject().setValue(context, MemberNames.Detail.toString(), detail.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.Detail.toString(), null);
		}
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final openaiconnector.proxies.OpenAIImageContent that = (openaiconnector.proxies.OpenAIImageContent) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
