// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package openaiconnector.proxies;

/**
 * The OpenAIImageOptions_Extension object can be used to add OpenAI-specific configurations to a image generations request. It is optional and can be added via ImageOptions_SetOpenAIExtension to the GenAICommons.ImageOptions object that can be passed to the operation.
 */
public class OpenAIImageOptions_Extension implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject openAIImageOptions_ExtensionMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "OpenAIConnector.OpenAIImageOptions_Extension";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Quality("Quality"),
		ResponseFormat("ResponseFormat"),
		Style("Style"),
		User("User"),
		OpenAIImageOptions_Extension_ImageOptions("OpenAIConnector.OpenAIImageOptions_Extension_ImageOptions");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public OpenAIImageOptions_Extension(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected OpenAIImageOptions_Extension(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject openAIImageOptions_ExtensionMendixObject)
	{
		if (openAIImageOptions_ExtensionMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!openAIImageOptions_ExtensionMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.openAIImageOptions_ExtensionMendixObject = openAIImageOptions_ExtensionMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static openaiconnector.proxies.OpenAIImageOptions_Extension initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new openaiconnector.proxies.OpenAIImageOptions_Extension(context, mendixObject);
	}

	public static openaiconnector.proxies.OpenAIImageOptions_Extension load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return openaiconnector.proxies.OpenAIImageOptions_Extension.initialize(context, mendixObject);
	}

	/**
	 * @return value of Quality
	 */
	public final java.lang.String getQuality()
	{
		return getQuality(getContext());
	}

	/**
	 * @param context
	 * @return value of Quality
	 */
	public final java.lang.String getQuality(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Quality.toString());
	}

	/**
	 * Set value of Quality
	 * @param quality
	 */
	public final void setQuality(java.lang.String quality)
	{
		setQuality(getContext(), quality);
	}

	/**
	 * Set value of Quality
	 * @param context
	 * @param quality
	 */
	public final void setQuality(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String quality)
	{
		getMendixObject().setValue(context, MemberNames.Quality.toString(), quality);
	}

	/**
	 * @return value of ResponseFormat
	 */
	public final java.lang.String getResponseFormat()
	{
		return getResponseFormat(getContext());
	}

	/**
	 * @param context
	 * @return value of ResponseFormat
	 */
	public final java.lang.String getResponseFormat(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ResponseFormat.toString());
	}

	/**
	 * Set value of ResponseFormat
	 * @param responseformat
	 */
	public final void setResponseFormat(java.lang.String responseformat)
	{
		setResponseFormat(getContext(), responseformat);
	}

	/**
	 * Set value of ResponseFormat
	 * @param context
	 * @param responseformat
	 */
	public final void setResponseFormat(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String responseformat)
	{
		getMendixObject().setValue(context, MemberNames.ResponseFormat.toString(), responseformat);
	}

	/**
	 * @return value of Style
	 */
	public final java.lang.String getStyle()
	{
		return getStyle(getContext());
	}

	/**
	 * @param context
	 * @return value of Style
	 */
	public final java.lang.String getStyle(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Style.toString());
	}

	/**
	 * Set value of Style
	 * @param style
	 */
	public final void setStyle(java.lang.String style)
	{
		setStyle(getContext(), style);
	}

	/**
	 * Set value of Style
	 * @param context
	 * @param style
	 */
	public final void setStyle(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String style)
	{
		getMendixObject().setValue(context, MemberNames.Style.toString(), style);
	}

	/**
	 * @return value of User
	 */
	public final java.lang.String getUser()
	{
		return getUser(getContext());
	}

	/**
	 * @param context
	 * @return value of User
	 */
	public final java.lang.String getUser(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.User.toString());
	}

	/**
	 * Set value of User
	 * @param user
	 */
	public final void setUser(java.lang.String user)
	{
		setUser(getContext(), user);
	}

	/**
	 * Set value of User
	 * @param context
	 * @param user
	 */
	public final void setUser(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String user)
	{
		getMendixObject().setValue(context, MemberNames.User.toString(), user);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of OpenAIImageOptions_Extension_ImageOptions
	 */
	public final genaicommons.proxies.ImageOptions getOpenAIImageOptions_Extension_ImageOptions() throws com.mendix.core.CoreException
	{
		return getOpenAIImageOptions_Extension_ImageOptions(getContext());
	}

	/**
	 * @param context
	 * @return value of OpenAIImageOptions_Extension_ImageOptions
	 * @throws com.mendix.core.CoreException
	 */
	public final genaicommons.proxies.ImageOptions getOpenAIImageOptions_Extension_ImageOptions(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		genaicommons.proxies.ImageOptions result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.OpenAIImageOptions_Extension_ImageOptions.toString());
		if (identifier != null) {
			result = genaicommons.proxies.ImageOptions.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of OpenAIImageOptions_Extension_ImageOptions
	 * @param openaiimageoptions_extension_imageoptions
	 */
	public final void setOpenAIImageOptions_Extension_ImageOptions(genaicommons.proxies.ImageOptions openaiimageoptions_extension_imageoptions)
	{
		setOpenAIImageOptions_Extension_ImageOptions(getContext(), openaiimageoptions_extension_imageoptions);
	}

	/**
	 * Set value of OpenAIImageOptions_Extension_ImageOptions
	 * @param context
	 * @param openaiimageoptions_extension_imageoptions
	 */
	public final void setOpenAIImageOptions_Extension_ImageOptions(com.mendix.systemwideinterfaces.core.IContext context, genaicommons.proxies.ImageOptions openaiimageoptions_extension_imageoptions)
	{
		if (openaiimageoptions_extension_imageoptions == null) {
			getMendixObject().setValue(context, MemberNames.OpenAIImageOptions_Extension_ImageOptions.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.OpenAIImageOptions_Extension_ImageOptions.toString(), openaiimageoptions_extension_imageoptions.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return openAIImageOptions_ExtensionMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final openaiconnector.proxies.OpenAIImageOptions_Extension that = (openaiconnector.proxies.OpenAIImageOptions_Extension) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
