// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package openaiconnector.proxies;

/**
 * Internal helper entity - for mapping purposes only.
 * DO NOT USE outside of connector.
 */
public class RequestMapping implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject requestMappingMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "OpenAIConnector.RequestMapping";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ResponseFormat("ResponseFormat"),
		FrequencyPenalty("FrequencyPenalty"),
		_Model("_Model"),
		MaxTokens("MaxTokens"),
		ToolChoice("ToolChoice"),
		TopP("TopP"),
		Temperature("Temperature"),
		RequestMapping_OpenAIRequest_Extension("OpenAIConnector.RequestMapping_OpenAIRequest_Extension");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public RequestMapping(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected RequestMapping(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject requestMappingMendixObject)
	{
		if (requestMappingMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!requestMappingMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.requestMappingMendixObject = requestMappingMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static openaiconnector.proxies.RequestMapping initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new openaiconnector.proxies.RequestMapping(context, mendixObject);
	}

	public static openaiconnector.proxies.RequestMapping load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return openaiconnector.proxies.RequestMapping.initialize(context, mendixObject);
	}

	/**
	 * Get value of ResponseFormat
	 * @param responseformat
	 */
	public final openaiconnector.proxies.ENUM_ResponseFormat_Chat getResponseFormat()
	{
		return getResponseFormat(getContext());
	}

	/**
	 * @param context
	 * @return value of ResponseFormat
	 */
	public final openaiconnector.proxies.ENUM_ResponseFormat_Chat getResponseFormat(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.ResponseFormat.toString());
		if (obj == null) {
			return null;
		}
		return openaiconnector.proxies.ENUM_ResponseFormat_Chat.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of ResponseFormat
	 * @param responseformat
	 */
	public final void setResponseFormat(openaiconnector.proxies.ENUM_ResponseFormat_Chat responseformat)
	{
		setResponseFormat(getContext(), responseformat);
	}

	/**
	 * Set value of ResponseFormat
	 * @param context
	 * @param responseformat
	 */
	public final void setResponseFormat(com.mendix.systemwideinterfaces.core.IContext context, openaiconnector.proxies.ENUM_ResponseFormat_Chat responseformat)
	{
		if (responseformat != null) {
			getMendixObject().setValue(context, MemberNames.ResponseFormat.toString(), responseformat.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.ResponseFormat.toString(), null);
		}
	}

	/**
	 * @return value of FrequencyPenalty
	 */
	public final java.math.BigDecimal getFrequencyPenalty()
	{
		return getFrequencyPenalty(getContext());
	}

	/**
	 * @param context
	 * @return value of FrequencyPenalty
	 */
	public final java.math.BigDecimal getFrequencyPenalty(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.FrequencyPenalty.toString());
	}

	/**
	 * Set value of FrequencyPenalty
	 * @param frequencypenalty
	 */
	public final void setFrequencyPenalty(java.math.BigDecimal frequencypenalty)
	{
		setFrequencyPenalty(getContext(), frequencypenalty);
	}

	/**
	 * Set value of FrequencyPenalty
	 * @param context
	 * @param frequencypenalty
	 */
	public final void setFrequencyPenalty(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal frequencypenalty)
	{
		getMendixObject().setValue(context, MemberNames.FrequencyPenalty.toString(), frequencypenalty);
	}

	/**
	 * @return value of _Model
	 */
	public final java.lang.String get_Model()
	{
		return get_Model(getContext());
	}

	/**
	 * @param context
	 * @return value of _Model
	 */
	public final java.lang.String get_Model(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames._Model.toString());
	}

	/**
	 * Set value of _Model
	 * @param _model
	 */
	public final void set_Model(java.lang.String _model)
	{
		set_Model(getContext(), _model);
	}

	/**
	 * Set value of _Model
	 * @param context
	 * @param _model
	 */
	public final void set_Model(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String _model)
	{
		getMendixObject().setValue(context, MemberNames._Model.toString(), _model);
	}

	/**
	 * @return value of MaxTokens
	 */
	public final java.lang.Integer getMaxTokens()
	{
		return getMaxTokens(getContext());
	}

	/**
	 * @param context
	 * @return value of MaxTokens
	 */
	public final java.lang.Integer getMaxTokens(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.MaxTokens.toString());
	}

	/**
	 * Set value of MaxTokens
	 * @param maxtokens
	 */
	public final void setMaxTokens(java.lang.Integer maxtokens)
	{
		setMaxTokens(getContext(), maxtokens);
	}

	/**
	 * Set value of MaxTokens
	 * @param context
	 * @param maxtokens
	 */
	public final void setMaxTokens(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer maxtokens)
	{
		getMendixObject().setValue(context, MemberNames.MaxTokens.toString(), maxtokens);
	}

	/**
	 * Get value of ToolChoice
	 * @param toolchoice
	 */
	public final genaicommons.proxies.ENUM_ToolChoice getToolChoice()
	{
		return getToolChoice(getContext());
	}

	/**
	 * @param context
	 * @return value of ToolChoice
	 */
	public final genaicommons.proxies.ENUM_ToolChoice getToolChoice(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.ToolChoice.toString());
		if (obj == null) {
			return null;
		}
		return genaicommons.proxies.ENUM_ToolChoice.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of ToolChoice
	 * @param toolchoice
	 */
	public final void setToolChoice(genaicommons.proxies.ENUM_ToolChoice toolchoice)
	{
		setToolChoice(getContext(), toolchoice);
	}

	/**
	 * Set value of ToolChoice
	 * @param context
	 * @param toolchoice
	 */
	public final void setToolChoice(com.mendix.systemwideinterfaces.core.IContext context, genaicommons.proxies.ENUM_ToolChoice toolchoice)
	{
		if (toolchoice != null) {
			getMendixObject().setValue(context, MemberNames.ToolChoice.toString(), toolchoice.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.ToolChoice.toString(), null);
		}
	}

	/**
	 * @return value of TopP
	 */
	public final java.math.BigDecimal getTopP()
	{
		return getTopP(getContext());
	}

	/**
	 * @param context
	 * @return value of TopP
	 */
	public final java.math.BigDecimal getTopP(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.TopP.toString());
	}

	/**
	 * Set value of TopP
	 * @param topp
	 */
	public final void setTopP(java.math.BigDecimal topp)
	{
		setTopP(getContext(), topp);
	}

	/**
	 * Set value of TopP
	 * @param context
	 * @param topp
	 */
	public final void setTopP(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal topp)
	{
		getMendixObject().setValue(context, MemberNames.TopP.toString(), topp);
	}

	/**
	 * @return value of Temperature
	 */
	public final java.math.BigDecimal getTemperature()
	{
		return getTemperature(getContext());
	}

	/**
	 * @param context
	 * @return value of Temperature
	 */
	public final java.math.BigDecimal getTemperature(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Temperature.toString());
	}

	/**
	 * Set value of Temperature
	 * @param temperature
	 */
	public final void setTemperature(java.math.BigDecimal temperature)
	{
		setTemperature(getContext(), temperature);
	}

	/**
	 * Set value of Temperature
	 * @param context
	 * @param temperature
	 */
	public final void setTemperature(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal temperature)
	{
		getMendixObject().setValue(context, MemberNames.Temperature.toString(), temperature);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of RequestMapping_OpenAIRequest_Extension
	 */
	public final openaiconnector.proxies.OpenAIRequest_Extension getRequestMapping_OpenAIRequest_Extension() throws com.mendix.core.CoreException
	{
		return getRequestMapping_OpenAIRequest_Extension(getContext());
	}

	/**
	 * @param context
	 * @return value of RequestMapping_OpenAIRequest_Extension
	 * @throws com.mendix.core.CoreException
	 */
	public final openaiconnector.proxies.OpenAIRequest_Extension getRequestMapping_OpenAIRequest_Extension(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		openaiconnector.proxies.OpenAIRequest_Extension result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.RequestMapping_OpenAIRequest_Extension.toString());
		if (identifier != null) {
			result = openaiconnector.proxies.OpenAIRequest_Extension.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of RequestMapping_OpenAIRequest_Extension
	 * @param requestmapping_openairequest_extension
	 */
	public final void setRequestMapping_OpenAIRequest_Extension(openaiconnector.proxies.OpenAIRequest_Extension requestmapping_openairequest_extension)
	{
		setRequestMapping_OpenAIRequest_Extension(getContext(), requestmapping_openairequest_extension);
	}

	/**
	 * Set value of RequestMapping_OpenAIRequest_Extension
	 * @param context
	 * @param requestmapping_openairequest_extension
	 */
	public final void setRequestMapping_OpenAIRequest_Extension(com.mendix.systemwideinterfaces.core.IContext context, openaiconnector.proxies.OpenAIRequest_Extension requestmapping_openairequest_extension)
	{
		if (requestmapping_openairequest_extension == null) {
			getMendixObject().setValue(context, MemberNames.RequestMapping_OpenAIRequest_Extension.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.RequestMapping_OpenAIRequest_Extension.toString(), requestmapping_openairequest_extension.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return requestMappingMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final openaiconnector.proxies.RequestMapping that = (openaiconnector.proxies.RequestMapping) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
