// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package conversationalui.proxies;

public class AdvancedSettings implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject advancedSettingsMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "ConversationalUI.AdvancedSettings";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Temperature("Temperature"),
		TemperatureMax("TemperatureMax"),
		TemperatureMin("TemperatureMin"),
		AdvancedSettings_ChatContext("ConversationalUI.AdvancedSettings_ChatContext");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public AdvancedSettings(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected AdvancedSettings(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject advancedSettingsMendixObject)
	{
		if (advancedSettingsMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!advancedSettingsMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.advancedSettingsMendixObject = advancedSettingsMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static conversationalui.proxies.AdvancedSettings initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new conversationalui.proxies.AdvancedSettings(context, mendixObject);
	}

	public static conversationalui.proxies.AdvancedSettings load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return conversationalui.proxies.AdvancedSettings.initialize(context, mendixObject);
	}

	/**
	 * @return value of Temperature
	 */
	public final java.math.BigDecimal getTemperature()
	{
		return getTemperature(getContext());
	}

	/**
	 * @param context
	 * @return value of Temperature
	 */
	public final java.math.BigDecimal getTemperature(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Temperature.toString());
	}

	/**
	 * Set value of Temperature
	 * @param temperature
	 */
	public final void setTemperature(java.math.BigDecimal temperature)
	{
		setTemperature(getContext(), temperature);
	}

	/**
	 * Set value of Temperature
	 * @param context
	 * @param temperature
	 */
	public final void setTemperature(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal temperature)
	{
		getMendixObject().setValue(context, MemberNames.Temperature.toString(), temperature);
	}

	/**
	 * @return value of TemperatureMax
	 */
	public final java.math.BigDecimal getTemperatureMax()
	{
		return getTemperatureMax(getContext());
	}

	/**
	 * @param context
	 * @return value of TemperatureMax
	 */
	public final java.math.BigDecimal getTemperatureMax(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.TemperatureMax.toString());
	}

	/**
	 * Set value of TemperatureMax
	 * @param temperaturemax
	 */
	public final void setTemperatureMax(java.math.BigDecimal temperaturemax)
	{
		setTemperatureMax(getContext(), temperaturemax);
	}

	/**
	 * Set value of TemperatureMax
	 * @param context
	 * @param temperaturemax
	 */
	public final void setTemperatureMax(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal temperaturemax)
	{
		getMendixObject().setValue(context, MemberNames.TemperatureMax.toString(), temperaturemax);
	}

	/**
	 * @return value of TemperatureMin
	 */
	public final java.math.BigDecimal getTemperatureMin()
	{
		return getTemperatureMin(getContext());
	}

	/**
	 * @param context
	 * @return value of TemperatureMin
	 */
	public final java.math.BigDecimal getTemperatureMin(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.TemperatureMin.toString());
	}

	/**
	 * Set value of TemperatureMin
	 * @param temperaturemin
	 */
	public final void setTemperatureMin(java.math.BigDecimal temperaturemin)
	{
		setTemperatureMin(getContext(), temperaturemin);
	}

	/**
	 * Set value of TemperatureMin
	 * @param context
	 * @param temperaturemin
	 */
	public final void setTemperatureMin(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal temperaturemin)
	{
		getMendixObject().setValue(context, MemberNames.TemperatureMin.toString(), temperaturemin);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of AdvancedSettings_ChatContext
	 */
	public final conversationalui.proxies.ChatContext getAdvancedSettings_ChatContext() throws com.mendix.core.CoreException
	{
		return getAdvancedSettings_ChatContext(getContext());
	}

	/**
	 * @param context
	 * @return value of AdvancedSettings_ChatContext
	 * @throws com.mendix.core.CoreException
	 */
	public final conversationalui.proxies.ChatContext getAdvancedSettings_ChatContext(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		conversationalui.proxies.ChatContext result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.AdvancedSettings_ChatContext.toString());
		if (identifier != null) {
			result = conversationalui.proxies.ChatContext.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of AdvancedSettings_ChatContext
	 * @param advancedsettings_chatcontext
	 */
	public final void setAdvancedSettings_ChatContext(conversationalui.proxies.ChatContext advancedsettings_chatcontext)
	{
		setAdvancedSettings_ChatContext(getContext(), advancedsettings_chatcontext);
	}

	/**
	 * Set value of AdvancedSettings_ChatContext
	 * @param context
	 * @param advancedsettings_chatcontext
	 */
	public final void setAdvancedSettings_ChatContext(com.mendix.systemwideinterfaces.core.IContext context, conversationalui.proxies.ChatContext advancedsettings_chatcontext)
	{
		if (advancedsettings_chatcontext == null) {
			getMendixObject().setValue(context, MemberNames.AdvancedSettings_ChatContext.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.AdvancedSettings_ChatContext.toString(), advancedsettings_chatcontext.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return advancedSettingsMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final conversationalui.proxies.AdvancedSettings that = (conversationalui.proxies.AdvancedSettings) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
