// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package conversationalui.proxies;

/**
 * The `ChatContext` is the central entity in the UI and microflows. It can only be viewed by the owner and users with the _addOn_ReadAll module role. The object needs to be created for every new chat interaction and comprises the `messages` that are sent to and received from the model. A `ProviderConfig` should be associated via `ChatContext_ProviderConfig_Active` in order to execute the correct ActionMicroflow.
 * If you need additional attributes or associations on the `ChatContext`, we advise to use an extension entity that refers to the object which can then be retrieved and altered when needed (for example in the action microflow). This pattern was implemented in the AI Bot Starter App.
 */
public class ChatContext implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject chatContextMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "ConversationalUI.ChatContext";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Topic("Topic"),
		CurrentUserPrompt("CurrentUserPrompt"),
		Status("Status"),
		ConversationID("ConversationID"),
		ChatContext_ProviderConfig_Active("ConversationalUI.ChatContext_ProviderConfig_Active"),
		ChatContext_ProviderConfig("ConversationalUI.ChatContext_ProviderConfig");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ChatContext(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ChatContext(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject chatContextMendixObject)
	{
		if (chatContextMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!chatContextMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.chatContextMendixObject = chatContextMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static conversationalui.proxies.ChatContext initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new conversationalui.proxies.ChatContext(context, mendixObject);
	}

	public static conversationalui.proxies.ChatContext load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return conversationalui.proxies.ChatContext.initialize(context, mendixObject);
	}

	public static java.util.List<conversationalui.proxies.ChatContext> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> conversationalui.proxies.ChatContext.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of Topic
	 */
	public final java.lang.String getTopic()
	{
		return getTopic(getContext());
	}

	/**
	 * @param context
	 * @return value of Topic
	 */
	public final java.lang.String getTopic(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Topic.toString());
	}

	/**
	 * Set value of Topic
	 * @param topic
	 */
	public final void setTopic(java.lang.String topic)
	{
		setTopic(getContext(), topic);
	}

	/**
	 * Set value of Topic
	 * @param context
	 * @param topic
	 */
	public final void setTopic(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String topic)
	{
		getMendixObject().setValue(context, MemberNames.Topic.toString(), topic);
	}

	/**
	 * @return value of CurrentUserPrompt
	 */
	public final java.lang.String getCurrentUserPrompt()
	{
		return getCurrentUserPrompt(getContext());
	}

	/**
	 * @param context
	 * @return value of CurrentUserPrompt
	 */
	public final java.lang.String getCurrentUserPrompt(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CurrentUserPrompt.toString());
	}

	/**
	 * Set value of CurrentUserPrompt
	 * @param currentuserprompt
	 */
	public final void setCurrentUserPrompt(java.lang.String currentuserprompt)
	{
		setCurrentUserPrompt(getContext(), currentuserprompt);
	}

	/**
	 * Set value of CurrentUserPrompt
	 * @param context
	 * @param currentuserprompt
	 */
	public final void setCurrentUserPrompt(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String currentuserprompt)
	{
		getMendixObject().setValue(context, MemberNames.CurrentUserPrompt.toString(), currentuserprompt);
	}

	/**
	 * Get value of Status
	 * @param status
	 */
	public final conversationalui.proxies.ENUM_ChatContextStatus getStatus()
	{
		return getStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of Status
	 */
	public final conversationalui.proxies.ENUM_ChatContextStatus getStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Status.toString());
		if (obj == null) {
			return null;
		}
		return conversationalui.proxies.ENUM_ChatContextStatus.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Status
	 * @param status
	 */
	public final void setStatus(conversationalui.proxies.ENUM_ChatContextStatus status)
	{
		setStatus(getContext(), status);
	}

	/**
	 * Set value of Status
	 * @param context
	 * @param status
	 */
	public final void setStatus(com.mendix.systemwideinterfaces.core.IContext context, conversationalui.proxies.ENUM_ChatContextStatus status)
	{
		if (status != null) {
			getMendixObject().setValue(context, MemberNames.Status.toString(), status.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.Status.toString(), null);
		}
	}

	/**
	 * @return value of ConversationID
	 */
	public final java.lang.String getConversationID()
	{
		return getConversationID(getContext());
	}

	/**
	 * @param context
	 * @return value of ConversationID
	 */
	public final java.lang.String getConversationID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ConversationID.toString());
	}

	/**
	 * Set value of ConversationID
	 * @param conversationid
	 */
	public final void setConversationID(java.lang.String conversationid)
	{
		setConversationID(getContext(), conversationid);
	}

	/**
	 * Set value of ConversationID
	 * @param context
	 * @param conversationid
	 */
	public final void setConversationID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String conversationid)
	{
		getMendixObject().setValue(context, MemberNames.ConversationID.toString(), conversationid);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ChatContext_ProviderConfig_Active
	 */
	public final conversationalui.proxies.ProviderConfig getChatContext_ProviderConfig_Active() throws com.mendix.core.CoreException
	{
		return getChatContext_ProviderConfig_Active(getContext());
	}

	/**
	 * @param context
	 * @return value of ChatContext_ProviderConfig_Active
	 * @throws com.mendix.core.CoreException
	 */
	public final conversationalui.proxies.ProviderConfig getChatContext_ProviderConfig_Active(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		conversationalui.proxies.ProviderConfig result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ChatContext_ProviderConfig_Active.toString());
		if (identifier != null) {
			result = conversationalui.proxies.ProviderConfig.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ChatContext_ProviderConfig_Active
	 * @param chatcontext_providerconfig_active
	 */
	public final void setChatContext_ProviderConfig_Active(conversationalui.proxies.ProviderConfig chatcontext_providerconfig_active)
	{
		setChatContext_ProviderConfig_Active(getContext(), chatcontext_providerconfig_active);
	}

	/**
	 * Set value of ChatContext_ProviderConfig_Active
	 * @param context
	 * @param chatcontext_providerconfig_active
	 */
	public final void setChatContext_ProviderConfig_Active(com.mendix.systemwideinterfaces.core.IContext context, conversationalui.proxies.ProviderConfig chatcontext_providerconfig_active)
	{
		if (chatcontext_providerconfig_active == null) {
			getMendixObject().setValue(context, MemberNames.ChatContext_ProviderConfig_Active.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ChatContext_ProviderConfig_Active.toString(), chatcontext_providerconfig_active.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ChatContext_ProviderConfig
	 */
	public final java.util.List<conversationalui.proxies.ProviderConfig> getChatContext_ProviderConfig() throws com.mendix.core.CoreException
	{
		return getChatContext_ProviderConfig(getContext());
	}

	/**
	 * @param context
	 * @return value of ChatContext_ProviderConfig
	 * @throws com.mendix.core.CoreException
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<conversationalui.proxies.ProviderConfig> getChatContext_ProviderConfig(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<conversationalui.proxies.ProviderConfig> result = new java.util.ArrayList<>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.ChatContext_ProviderConfig.toString());
		if (valueObject == null) {
			return result;
		}
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject)) {
			result.add(conversationalui.proxies.ProviderConfig.initialize(context, mendixObject));
		}
		return result;
	}

	/**
	 * Set value of ChatContext_ProviderConfig
	 * @param chatcontext_providerconfig
	 */
	public final void setChatContext_ProviderConfig(java.util.List<conversationalui.proxies.ProviderConfig> chatcontext_providerconfig)
	{
		setChatContext_ProviderConfig(getContext(), chatcontext_providerconfig);
	}

	/**
	 * Set value of ChatContext_ProviderConfig
	 * @param context
	 * @param chatcontext_providerconfig
	 */
	public final void setChatContext_ProviderConfig(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<conversationalui.proxies.ProviderConfig> chatcontext_providerconfig)
	{
		var identifiers = chatcontext_providerconfig
			.stream()
			.map(proxyObject -> proxyObject.getMendixObject().getId())
			.collect(java.util.stream.Collectors.toList());
		
		getMendixObject().setValue(context, MemberNames.ChatContext_ProviderConfig.toString(), identifiers);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return chatContextMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final conversationalui.proxies.ChatContext that = (conversationalui.proxies.ChatContext) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
