// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package conversationalui.proxies;

public class DeploymentSelection implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject deploymentSelectionMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "ConversationalUI.DeploymentSelection";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		DeploymentIdentifier("DeploymentIdentifier");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public DeploymentSelection(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected DeploymentSelection(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject deploymentSelectionMendixObject)
	{
		if (deploymentSelectionMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!deploymentSelectionMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.deploymentSelectionMendixObject = deploymentSelectionMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static conversationalui.proxies.DeploymentSelection initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new conversationalui.proxies.DeploymentSelection(context, mendixObject);
	}

	public static conversationalui.proxies.DeploymentSelection load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return conversationalui.proxies.DeploymentSelection.initialize(context, mendixObject);
	}

	/**
	 * @return value of DeploymentIdentifier
	 */
	public final java.lang.String getDeploymentIdentifier()
	{
		return getDeploymentIdentifier(getContext());
	}

	/**
	 * @param context
	 * @return value of DeploymentIdentifier
	 */
	public final java.lang.String getDeploymentIdentifier(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DeploymentIdentifier.toString());
	}

	/**
	 * Set value of DeploymentIdentifier
	 * @param deploymentidentifier
	 */
	public final void setDeploymentIdentifier(java.lang.String deploymentidentifier)
	{
		setDeploymentIdentifier(getContext(), deploymentidentifier);
	}

	/**
	 * Set value of DeploymentIdentifier
	 * @param context
	 * @param deploymentidentifier
	 */
	public final void setDeploymentIdentifier(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String deploymentidentifier)
	{
		getMendixObject().setValue(context, MemberNames.DeploymentIdentifier.toString(), deploymentidentifier);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return deploymentSelectionMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final conversationalui.proxies.DeploymentSelection that = (conversationalui.proxies.DeploymentSelection) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
