// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package conversationalui.proxies;

public enum ENUM_FilterType
{
	Agent("cdbed45f-c9c7-46c9-a7d4-db8638905893"),
	Version("d77228d6-aa63-458c-9428-e4301fccdaaf"),
	Conversation_ID("997979c4-77de-4200-b6f3-88d00b4b0844"),
	Trace_ID("342c2b52-cb0e-4730-aed3-dec2ebbd93f1");

	private final java.lang.String i18nCaptionKey;
	
	private ENUM_FilterType(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
