// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package conversationalui.proxies;

public enum ENUM_MessageStatus
{
	Loading("10189beb-884b-42de-9c26-2f222f7603d0"),
	Error("8395138a-dac0-4014-aeae-0914c0363908"),
	Success("4917ac4b-471f-4877-ad45-92eba64869a3");

	private final java.lang.String i18nCaptionKey;
	
	private ENUM_MessageStatus(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
