// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package conversationalui.proxies;

public enum ENUM_SpanType
{
	Agent("161809de-17b4-491d-8faf-018add5b769f"),
	ModelCall("f312e329-48e1-45a9-90c3-13492feef812"),
	ToolCall("c9e4d0b1-59bb-45c6-b4c8-7a2bbf96bb71"),
	KnowledgeBaseCall("4ca0831e-5b6b-4243-8bc9-997482121cf1"),
	MCPCall("c89aa82d-b602-4e6c-b752-d8624644fe13");

	private final java.lang.String i18nCaptionKey;
	
	private ENUM_SpanType(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
