// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package conversationalui.proxies;

public enum ENUM_ChatContextStatus
{
	Loading("6d739117-2071-462f-9db8-cd80f182b7d3"),
	Ready("afc6174e-056e-4dfd-a958-7fd980f26b6e");

	private final java.lang.String i18nCaptionKey;
	
	private ENUM_ChatContextStatus(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
