// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package conversationalui.proxies;

public enum ENUM_TimeRange
{
	Day("4b976bab-c7e4-4de9-b131-c2fbb4eec3a5"),
	Week("79b5fb05-7710-4bfb-81e2-8a9a3cfbefcd"),
	Month("3e807d3d-b46d-4dd5-b8e6-b72fcc0e776a"),
	MonthToDate("2630ed44-96cb-40ad-bd94-3e8c9698601a"),
	_3Month("6f200cf1-af48-4357-9444-f7ed3a9d17bd"),
	_6Month("2c307c98-e8d8-49a7-8e7f-2359b715808a"),
	Custom("f66266ea-a4a6-40cf-9d2f-5fe0c210efd4"),
	All("3a593907-d7a9-48d1-b110-e6c4b4f84314");

	private final java.lang.String i18nCaptionKey;
	
	private ENUM_TimeRange(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
