// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package conversationalui.proxies;

public enum ENUM_Granularity
{
	_30Mins("6fff375f-d8e1-44e7-8958-682f147c7b18"),
	Hour("d94b1da3-6325-4259-b842-d809b2faa1b6"),
	_4Hours("e01d50f2-6947-4ca9-abaa-07a5907bffae"),
	_12Hours("721c6fe4-b3d1-4db3-a47c-dc27b8fc8026"),
	Day("09a3aaf3-ceb5-472f-bce9-7b478c820989"),
	_2Days("a9ed83ed-40a9-4570-9af2-b8ec682b1561"),
	Week("d4435202-2dff-4be0-991e-dead775a383b"),
	Month("596e289b-ab1f-46fd-9418-6fe58a9fad9f");

	private final java.lang.String i18nCaptionKey;
	
	private ENUM_Granularity(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
