// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package conversationalui.proxies;

/**
 * A `Message` contains the content of both user and assistant messages, distinguishable by the `Role` attribute (e.g. User and Assistant).
 */
public class Message implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject messageMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "ConversationalUI.Message";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Content("Content"),
		Role("Role"),
		Status("Status"),
		HasSources("HasSources"),
		Message_ChatContext("ConversationalUI.Message_ChatContext");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Message(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Message(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject messageMendixObject)
	{
		if (messageMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!messageMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.messageMendixObject = messageMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static conversationalui.proxies.Message initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new conversationalui.proxies.Message(context, mendixObject);
	}

	public static conversationalui.proxies.Message load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return conversationalui.proxies.Message.initialize(context, mendixObject);
	}

	public static java.util.List<conversationalui.proxies.Message> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> conversationalui.proxies.Message.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of Content
	 */
	public final java.lang.String getContent()
	{
		return getContent(getContext());
	}

	/**
	 * @param context
	 * @return value of Content
	 */
	public final java.lang.String getContent(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Content.toString());
	}

	/**
	 * Set value of Content
	 * @param content
	 */
	public final void setContent(java.lang.String content)
	{
		setContent(getContext(), content);
	}

	/**
	 * Set value of Content
	 * @param context
	 * @param content
	 */
	public final void setContent(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String content)
	{
		getMendixObject().setValue(context, MemberNames.Content.toString(), content);
	}

	/**
	 * Get value of Role
	 * @param role
	 */
	public final genaicommons.proxies.ENUM_MessageRole getRole()
	{
		return getRole(getContext());
	}

	/**
	 * @param context
	 * @return value of Role
	 */
	public final genaicommons.proxies.ENUM_MessageRole getRole(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Role.toString());
		if (obj == null) {
			return null;
		}
		return genaicommons.proxies.ENUM_MessageRole.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Role
	 * @param role
	 */
	public final void setRole(genaicommons.proxies.ENUM_MessageRole role)
	{
		setRole(getContext(), role);
	}

	/**
	 * Set value of Role
	 * @param context
	 * @param role
	 */
	public final void setRole(com.mendix.systemwideinterfaces.core.IContext context, genaicommons.proxies.ENUM_MessageRole role)
	{
		if (role != null) {
			getMendixObject().setValue(context, MemberNames.Role.toString(), role.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.Role.toString(), null);
		}
	}

	/**
	 * Get value of Status
	 * @param status
	 */
	public final conversationalui.proxies.ENUM_MessageStatus getStatus()
	{
		return getStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of Status
	 */
	public final conversationalui.proxies.ENUM_MessageStatus getStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Status.toString());
		if (obj == null) {
			return null;
		}
		return conversationalui.proxies.ENUM_MessageStatus.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Status
	 * @param status
	 */
	public final void setStatus(conversationalui.proxies.ENUM_MessageStatus status)
	{
		setStatus(getContext(), status);
	}

	/**
	 * Set value of Status
	 * @param context
	 * @param status
	 */
	public final void setStatus(com.mendix.systemwideinterfaces.core.IContext context, conversationalui.proxies.ENUM_MessageStatus status)
	{
		if (status != null) {
			getMendixObject().setValue(context, MemberNames.Status.toString(), status.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.Status.toString(), null);
		}
	}

	/**
	 * @return value of HasSources
	 */
	public final java.lang.Boolean getHasSources()
	{
		return getHasSources(getContext());
	}

	/**
	 * @param context
	 * @return value of HasSources
	 */
	public final java.lang.Boolean getHasSources(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.HasSources.toString());
	}

	/**
	 * Set value of HasSources
	 * @param hassources
	 */
	public final void setHasSources(java.lang.Boolean hassources)
	{
		setHasSources(getContext(), hassources);
	}

	/**
	 * Set value of HasSources
	 * @param context
	 * @param hassources
	 */
	public final void setHasSources(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean hassources)
	{
		getMendixObject().setValue(context, MemberNames.HasSources.toString(), hassources);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Message_ChatContext
	 */
	public final conversationalui.proxies.ChatContext getMessage_ChatContext() throws com.mendix.core.CoreException
	{
		return getMessage_ChatContext(getContext());
	}

	/**
	 * @param context
	 * @return value of Message_ChatContext
	 * @throws com.mendix.core.CoreException
	 */
	public final conversationalui.proxies.ChatContext getMessage_ChatContext(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		conversationalui.proxies.ChatContext result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Message_ChatContext.toString());
		if (identifier != null) {
			result = conversationalui.proxies.ChatContext.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Message_ChatContext
	 * @param message_chatcontext
	 */
	public final void setMessage_ChatContext(conversationalui.proxies.ChatContext message_chatcontext)
	{
		setMessage_ChatContext(getContext(), message_chatcontext);
	}

	/**
	 * Set value of Message_ChatContext
	 * @param context
	 * @param message_chatcontext
	 */
	public final void setMessage_ChatContext(com.mendix.systemwideinterfaces.core.IContext context, conversationalui.proxies.ChatContext message_chatcontext)
	{
		if (message_chatcontext == null) {
			getMendixObject().setValue(context, MemberNames.Message_ChatContext.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Message_ChatContext.toString(), message_chatcontext.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return messageMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final conversationalui.proxies.Message that = (conversationalui.proxies.Message) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
