// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package conversationalui.proxies;

/**
 * The `ProviderConfig` contains the selection of the model provider for the AI Bot to chat with. This contains an ActionMicroflow that will be executed when the send button is clicked. You could store additional information, such as connection details, on the `ProviderConfig` by using a specialization and adding the necessarry fields. This pattern was implemented in the AI Bot Starter App.
 */
public class ProviderConfig implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject providerConfigMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "ConversationalUI.ProviderConfig";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ActionMicroflow("ActionMicroflow"),
		DisplayName("DisplayName"),
		SystemPrompt("SystemPrompt"),
		ProviderConfig_DeployedModel("ConversationalUI.ProviderConfig_DeployedModel");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ProviderConfig(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ProviderConfig(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject providerConfigMendixObject)
	{
		if (providerConfigMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!providerConfigMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.providerConfigMendixObject = providerConfigMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static conversationalui.proxies.ProviderConfig initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		if (mendixObject.isInstanceOf("MyFirstAIBot.BotConfig")) {
			return myfirstaibot.proxies.BotConfig.initialize(context, mendixObject);
		}
		return new conversationalui.proxies.ProviderConfig(context, mendixObject);
	}

	public static conversationalui.proxies.ProviderConfig load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return conversationalui.proxies.ProviderConfig.initialize(context, mendixObject);
	}

	public static java.util.List<? extends conversationalui.proxies.ProviderConfig> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> conversationalui.proxies.ProviderConfig.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of ActionMicroflow
	 */
	public final java.lang.String getActionMicroflow()
	{
		return getActionMicroflow(getContext());
	}

	/**
	 * @param context
	 * @return value of ActionMicroflow
	 */
	public final java.lang.String getActionMicroflow(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ActionMicroflow.toString());
	}

	/**
	 * Set value of ActionMicroflow
	 * @param actionmicroflow
	 */
	public final void setActionMicroflow(java.lang.String actionmicroflow)
	{
		setActionMicroflow(getContext(), actionmicroflow);
	}

	/**
	 * Set value of ActionMicroflow
	 * @param context
	 * @param actionmicroflow
	 */
	public final void setActionMicroflow(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String actionmicroflow)
	{
		getMendixObject().setValue(context, MemberNames.ActionMicroflow.toString(), actionmicroflow);
	}

	/**
	 * @return value of DisplayName
	 */
	public final java.lang.String getDisplayName()
	{
		return getDisplayName(getContext());
	}

	/**
	 * @param context
	 * @return value of DisplayName
	 */
	public final java.lang.String getDisplayName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DisplayName.toString());
	}

	/**
	 * Set value of DisplayName
	 * @param displayname
	 */
	public final void setDisplayName(java.lang.String displayname)
	{
		setDisplayName(getContext(), displayname);
	}

	/**
	 * Set value of DisplayName
	 * @param context
	 * @param displayname
	 */
	public final void setDisplayName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String displayname)
	{
		getMendixObject().setValue(context, MemberNames.DisplayName.toString(), displayname);
	}

	/**
	 * @return value of SystemPrompt
	 */
	public final java.lang.String getSystemPrompt()
	{
		return getSystemPrompt(getContext());
	}

	/**
	 * @param context
	 * @return value of SystemPrompt
	 */
	public final java.lang.String getSystemPrompt(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SystemPrompt.toString());
	}

	/**
	 * Set value of SystemPrompt
	 * @param systemprompt
	 */
	public final void setSystemPrompt(java.lang.String systemprompt)
	{
		setSystemPrompt(getContext(), systemprompt);
	}

	/**
	 * Set value of SystemPrompt
	 * @param context
	 * @param systemprompt
	 */
	public final void setSystemPrompt(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String systemprompt)
	{
		getMendixObject().setValue(context, MemberNames.SystemPrompt.toString(), systemprompt);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ProviderConfig_DeployedModel
	 */
	public final genaicommons.proxies.DeployedModel getProviderConfig_DeployedModel() throws com.mendix.core.CoreException
	{
		return getProviderConfig_DeployedModel(getContext());
	}

	/**
	 * @param context
	 * @return value of ProviderConfig_DeployedModel
	 * @throws com.mendix.core.CoreException
	 */
	public final genaicommons.proxies.DeployedModel getProviderConfig_DeployedModel(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		genaicommons.proxies.DeployedModel result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ProviderConfig_DeployedModel.toString());
		if (identifier != null) {
			result = genaicommons.proxies.DeployedModel.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ProviderConfig_DeployedModel
	 * @param providerconfig_deployedmodel
	 */
	public final void setProviderConfig_DeployedModel(genaicommons.proxies.DeployedModel providerconfig_deployedmodel)
	{
		setProviderConfig_DeployedModel(getContext(), providerconfig_deployedmodel);
	}

	/**
	 * Set value of ProviderConfig_DeployedModel
	 * @param context
	 * @param providerconfig_deployedmodel
	 */
	public final void setProviderConfig_DeployedModel(com.mendix.systemwideinterfaces.core.IContext context, genaicommons.proxies.DeployedModel providerconfig_deployedmodel)
	{
		if (providerconfig_deployedmodel == null) {
			getMendixObject().setValue(context, MemberNames.ProviderConfig_DeployedModel.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ProviderConfig_DeployedModel.toString(), providerconfig_deployedmodel.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return providerConfigMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final conversationalui.proxies.ProviderConfig that = (conversationalui.proxies.ProviderConfig) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
