// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package conversationalui.proxies;

public class SpanTreeView implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject spanTreeViewMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "ConversationalUI.SpanTreeView";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Title("Title"),
		SpanType("SpanType"),
		TraceID("TraceID"),
		IsCopiedFirstAttribute("IsCopiedFirstAttribute"),
		IsCopiedSecondAttribute("IsCopiedSecondAttribute"),
		IsCopiedThirdAttribute("IsCopiedThirdAttribute"),
		HasToolResultInput("HasToolResultInput"),
		TotalTokens("TotalTokens"),
		SpanTreeView_SubSpanTreeView("ConversationalUI.SpanTreeView_SubSpanTreeView"),
		SpanTreeView_Span("ConversationalUI.SpanTreeView_Span");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public SpanTreeView(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected SpanTreeView(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject spanTreeViewMendixObject)
	{
		if (spanTreeViewMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!spanTreeViewMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.spanTreeViewMendixObject = spanTreeViewMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static conversationalui.proxies.SpanTreeView initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new conversationalui.proxies.SpanTreeView(context, mendixObject);
	}

	public static conversationalui.proxies.SpanTreeView load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return conversationalui.proxies.SpanTreeView.initialize(context, mendixObject);
	}

	/**
	 * @return value of Title
	 */
	public final java.lang.String getTitle()
	{
		return getTitle(getContext());
	}

	/**
	 * @param context
	 * @return value of Title
	 */
	public final java.lang.String getTitle(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Title.toString());
	}

	/**
	 * Set value of Title
	 * @param title
	 */
	public final void setTitle(java.lang.String title)
	{
		setTitle(getContext(), title);
	}

	/**
	 * Set value of Title
	 * @param context
	 * @param title
	 */
	public final void setTitle(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String title)
	{
		getMendixObject().setValue(context, MemberNames.Title.toString(), title);
	}

	/**
	 * Get value of SpanType
	 * @param spantype
	 */
	public final conversationalui.proxies.ENUM_SpanType getSpanType()
	{
		return getSpanType(getContext());
	}

	/**
	 * @param context
	 * @return value of SpanType
	 */
	public final conversationalui.proxies.ENUM_SpanType getSpanType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.SpanType.toString());
		if (obj == null) {
			return null;
		}
		return conversationalui.proxies.ENUM_SpanType.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of SpanType
	 * @param spantype
	 */
	public final void setSpanType(conversationalui.proxies.ENUM_SpanType spantype)
	{
		setSpanType(getContext(), spantype);
	}

	/**
	 * Set value of SpanType
	 * @param context
	 * @param spantype
	 */
	public final void setSpanType(com.mendix.systemwideinterfaces.core.IContext context, conversationalui.proxies.ENUM_SpanType spantype)
	{
		if (spantype != null) {
			getMendixObject().setValue(context, MemberNames.SpanType.toString(), spantype.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.SpanType.toString(), null);
		}
	}

	/**
	 * @return value of TraceID
	 */
	public final java.lang.String getTraceID()
	{
		return getTraceID(getContext());
	}

	/**
	 * @param context
	 * @return value of TraceID
	 */
	public final java.lang.String getTraceID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.TraceID.toString());
	}

	/**
	 * Set value of TraceID
	 * @param traceid
	 */
	public final void setTraceID(java.lang.String traceid)
	{
		setTraceID(getContext(), traceid);
	}

	/**
	 * Set value of TraceID
	 * @param context
	 * @param traceid
	 */
	public final void setTraceID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String traceid)
	{
		getMendixObject().setValue(context, MemberNames.TraceID.toString(), traceid);
	}

	/**
	 * @return value of IsCopiedFirstAttribute
	 */
	public final java.lang.Boolean getIsCopiedFirstAttribute()
	{
		return getIsCopiedFirstAttribute(getContext());
	}

	/**
	 * @param context
	 * @return value of IsCopiedFirstAttribute
	 */
	public final java.lang.Boolean getIsCopiedFirstAttribute(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsCopiedFirstAttribute.toString());
	}

	/**
	 * Set value of IsCopiedFirstAttribute
	 * @param iscopiedfirstattribute
	 */
	public final void setIsCopiedFirstAttribute(java.lang.Boolean iscopiedfirstattribute)
	{
		setIsCopiedFirstAttribute(getContext(), iscopiedfirstattribute);
	}

	/**
	 * Set value of IsCopiedFirstAttribute
	 * @param context
	 * @param iscopiedfirstattribute
	 */
	public final void setIsCopiedFirstAttribute(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean iscopiedfirstattribute)
	{
		getMendixObject().setValue(context, MemberNames.IsCopiedFirstAttribute.toString(), iscopiedfirstattribute);
	}

	/**
	 * @return value of IsCopiedSecondAttribute
	 */
	public final java.lang.Boolean getIsCopiedSecondAttribute()
	{
		return getIsCopiedSecondAttribute(getContext());
	}

	/**
	 * @param context
	 * @return value of IsCopiedSecondAttribute
	 */
	public final java.lang.Boolean getIsCopiedSecondAttribute(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsCopiedSecondAttribute.toString());
	}

	/**
	 * Set value of IsCopiedSecondAttribute
	 * @param iscopiedsecondattribute
	 */
	public final void setIsCopiedSecondAttribute(java.lang.Boolean iscopiedsecondattribute)
	{
		setIsCopiedSecondAttribute(getContext(), iscopiedsecondattribute);
	}

	/**
	 * Set value of IsCopiedSecondAttribute
	 * @param context
	 * @param iscopiedsecondattribute
	 */
	public final void setIsCopiedSecondAttribute(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean iscopiedsecondattribute)
	{
		getMendixObject().setValue(context, MemberNames.IsCopiedSecondAttribute.toString(), iscopiedsecondattribute);
	}

	/**
	 * @return value of IsCopiedThirdAttribute
	 */
	public final java.lang.Boolean getIsCopiedThirdAttribute()
	{
		return getIsCopiedThirdAttribute(getContext());
	}

	/**
	 * @param context
	 * @return value of IsCopiedThirdAttribute
	 */
	public final java.lang.Boolean getIsCopiedThirdAttribute(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsCopiedThirdAttribute.toString());
	}

	/**
	 * Set value of IsCopiedThirdAttribute
	 * @param iscopiedthirdattribute
	 */
	public final void setIsCopiedThirdAttribute(java.lang.Boolean iscopiedthirdattribute)
	{
		setIsCopiedThirdAttribute(getContext(), iscopiedthirdattribute);
	}

	/**
	 * Set value of IsCopiedThirdAttribute
	 * @param context
	 * @param iscopiedthirdattribute
	 */
	public final void setIsCopiedThirdAttribute(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean iscopiedthirdattribute)
	{
		getMendixObject().setValue(context, MemberNames.IsCopiedThirdAttribute.toString(), iscopiedthirdattribute);
	}

	/**
	 * @return value of HasToolResultInput
	 */
	public final java.lang.Boolean getHasToolResultInput()
	{
		return getHasToolResultInput(getContext());
	}

	/**
	 * @param context
	 * @return value of HasToolResultInput
	 */
	public final java.lang.Boolean getHasToolResultInput(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.HasToolResultInput.toString());
	}

	/**
	 * Set value of HasToolResultInput
	 * @param hastoolresultinput
	 */
	public final void setHasToolResultInput(java.lang.Boolean hastoolresultinput)
	{
		setHasToolResultInput(getContext(), hastoolresultinput);
	}

	/**
	 * Set value of HasToolResultInput
	 * @param context
	 * @param hastoolresultinput
	 */
	public final void setHasToolResultInput(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean hastoolresultinput)
	{
		getMendixObject().setValue(context, MemberNames.HasToolResultInput.toString(), hastoolresultinput);
	}

	/**
	 * @return value of TotalTokens
	 */
	public final java.lang.Integer getTotalTokens()
	{
		return getTotalTokens(getContext());
	}

	/**
	 * @param context
	 * @return value of TotalTokens
	 */
	public final java.lang.Integer getTotalTokens(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.TotalTokens.toString());
	}

	/**
	 * Set value of TotalTokens
	 * @param totaltokens
	 */
	public final void setTotalTokens(java.lang.Integer totaltokens)
	{
		setTotalTokens(getContext(), totaltokens);
	}

	/**
	 * Set value of TotalTokens
	 * @param context
	 * @param totaltokens
	 */
	public final void setTotalTokens(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer totaltokens)
	{
		getMendixObject().setValue(context, MemberNames.TotalTokens.toString(), totaltokens);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of SpanTreeView_SubSpanTreeView
	 */
	public final conversationalui.proxies.SpanTreeView getSpanTreeView_SubSpanTreeView() throws com.mendix.core.CoreException
	{
		return getSpanTreeView_SubSpanTreeView(getContext());
	}

	/**
	 * @param context
	 * @return value of SpanTreeView_SubSpanTreeView
	 * @throws com.mendix.core.CoreException
	 */
	public final conversationalui.proxies.SpanTreeView getSpanTreeView_SubSpanTreeView(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		conversationalui.proxies.SpanTreeView result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.SpanTreeView_SubSpanTreeView.toString());
		if (identifier != null) {
			result = conversationalui.proxies.SpanTreeView.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of SpanTreeView_SubSpanTreeView
	 * @param spantreeview_subspantreeview
	 */
	public final void setSpanTreeView_SubSpanTreeView(conversationalui.proxies.SpanTreeView spantreeview_subspantreeview)
	{
		setSpanTreeView_SubSpanTreeView(getContext(), spantreeview_subspantreeview);
	}

	/**
	 * Set value of SpanTreeView_SubSpanTreeView
	 * @param context
	 * @param spantreeview_subspantreeview
	 */
	public final void setSpanTreeView_SubSpanTreeView(com.mendix.systemwideinterfaces.core.IContext context, conversationalui.proxies.SpanTreeView spantreeview_subspantreeview)
	{
		if (spantreeview_subspantreeview == null) {
			getMendixObject().setValue(context, MemberNames.SpanTreeView_SubSpanTreeView.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.SpanTreeView_SubSpanTreeView.toString(), spantreeview_subspantreeview.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of SpanTreeView_Span
	 */
	public final genaicommons.proxies.Span getSpanTreeView_Span() throws com.mendix.core.CoreException
	{
		return getSpanTreeView_Span(getContext());
	}

	/**
	 * @param context
	 * @return value of SpanTreeView_Span
	 * @throws com.mendix.core.CoreException
	 */
	public final genaicommons.proxies.Span getSpanTreeView_Span(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		genaicommons.proxies.Span result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.SpanTreeView_Span.toString());
		if (identifier != null) {
			result = genaicommons.proxies.Span.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of SpanTreeView_Span
	 * @param spantreeview_span
	 */
	public final void setSpanTreeView_Span(genaicommons.proxies.Span spantreeview_span)
	{
		setSpanTreeView_Span(getContext(), spantreeview_span);
	}

	/**
	 * Set value of SpanTreeView_Span
	 * @param context
	 * @param spantreeview_span
	 */
	public final void setSpanTreeView_Span(com.mendix.systemwideinterfaces.core.IContext context, genaicommons.proxies.Span spantreeview_span)
	{
		if (spantreeview_span == null) {
			getMendixObject().setValue(context, MemberNames.SpanTreeView_Span.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.SpanTreeView_Span.toString(), spantreeview_span.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return spanTreeViewMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final conversationalui.proxies.SpanTreeView that = (conversationalui.proxies.SpanTreeView) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
