// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package conversationalui.proxies;

/**
 * A SuggestedUserPrompt that can start a predefined chat in the interface when clicked.
 */
public class SuggestedUserPrompt implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject suggestedUserPromptMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "ConversationalUI.SuggestedUserPrompt";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Content("Content"),
		SuggestedUserPrompt_ChatContext("ConversationalUI.SuggestedUserPrompt_ChatContext");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public SuggestedUserPrompt(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected SuggestedUserPrompt(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject suggestedUserPromptMendixObject)
	{
		if (suggestedUserPromptMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!suggestedUserPromptMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.suggestedUserPromptMendixObject = suggestedUserPromptMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static conversationalui.proxies.SuggestedUserPrompt initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new conversationalui.proxies.SuggestedUserPrompt(context, mendixObject);
	}

	public static conversationalui.proxies.SuggestedUserPrompt load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return conversationalui.proxies.SuggestedUserPrompt.initialize(context, mendixObject);
	}

	/**
	 * @return value of Content
	 */
	public final java.lang.String getContent()
	{
		return getContent(getContext());
	}

	/**
	 * @param context
	 * @return value of Content
	 */
	public final java.lang.String getContent(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Content.toString());
	}

	/**
	 * Set value of Content
	 * @param content
	 */
	public final void setContent(java.lang.String content)
	{
		setContent(getContext(), content);
	}

	/**
	 * Set value of Content
	 * @param context
	 * @param content
	 */
	public final void setContent(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String content)
	{
		getMendixObject().setValue(context, MemberNames.Content.toString(), content);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of SuggestedUserPrompt_ChatContext
	 */
	public final conversationalui.proxies.ChatContext getSuggestedUserPrompt_ChatContext() throws com.mendix.core.CoreException
	{
		return getSuggestedUserPrompt_ChatContext(getContext());
	}

	/**
	 * @param context
	 * @return value of SuggestedUserPrompt_ChatContext
	 * @throws com.mendix.core.CoreException
	 */
	public final conversationalui.proxies.ChatContext getSuggestedUserPrompt_ChatContext(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		conversationalui.proxies.ChatContext result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.SuggestedUserPrompt_ChatContext.toString());
		if (identifier != null) {
			result = conversationalui.proxies.ChatContext.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of SuggestedUserPrompt_ChatContext
	 * @param suggesteduserprompt_chatcontext
	 */
	public final void setSuggestedUserPrompt_ChatContext(conversationalui.proxies.ChatContext suggesteduserprompt_chatcontext)
	{
		setSuggestedUserPrompt_ChatContext(getContext(), suggesteduserprompt_chatcontext);
	}

	/**
	 * Set value of SuggestedUserPrompt_ChatContext
	 * @param context
	 * @param suggesteduserprompt_chatcontext
	 */
	public final void setSuggestedUserPrompt_ChatContext(com.mendix.systemwideinterfaces.core.IContext context, conversationalui.proxies.ChatContext suggesteduserprompt_chatcontext)
	{
		if (suggesteduserprompt_chatcontext == null) {
			getMendixObject().setValue(context, MemberNames.SuggestedUserPrompt_ChatContext.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.SuggestedUserPrompt_ChatContext.toString(), suggesteduserprompt_chatcontext.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return suggestedUserPromptMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final conversationalui.proxies.SuggestedUserPrompt that = (conversationalui.proxies.SuggestedUserPrompt) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
