// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package conversationalui.proxies;

public class TokenMonitorSettings implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject tokenMonitorSettingsMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "ConversationalUI.TokenMonitorSettings";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		DateFrom("DateFrom"),
		DateTo("DateTo"),
		InputTokensCurrentMonth("InputTokensCurrentMonth"),
		InputTokensCurrentMonthString("InputTokensCurrentMonthString"),
		OutputTokensCurrentMonth("OutputTokensCurrentMonth"),
		OutputTokensCurrentMonthString("OutputTokensCurrentMonthString"),
		TimeRange("TimeRange"),
		Granularity("Granularity"),
		ShowOutput("ShowOutput"),
		TokenMonitorSettings_DeploymentSelection_Selected("ConversationalUI.TokenMonitorSettings_DeploymentSelection_Selected"),
		TokenMonitorSettings_DeploymentSelection("ConversationalUI.TokenMonitorSettings_DeploymentSelection");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public TokenMonitorSettings(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected TokenMonitorSettings(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject tokenMonitorSettingsMendixObject)
	{
		if (tokenMonitorSettingsMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!tokenMonitorSettingsMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.tokenMonitorSettingsMendixObject = tokenMonitorSettingsMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static conversationalui.proxies.TokenMonitorSettings initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new conversationalui.proxies.TokenMonitorSettings(context, mendixObject);
	}

	public static conversationalui.proxies.TokenMonitorSettings load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return conversationalui.proxies.TokenMonitorSettings.initialize(context, mendixObject);
	}

	/**
	 * @return value of DateFrom
	 */
	public final java.util.Date getDateFrom()
	{
		return getDateFrom(getContext());
	}

	/**
	 * @param context
	 * @return value of DateFrom
	 */
	public final java.util.Date getDateFrom(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.DateFrom.toString());
	}

	/**
	 * Set value of DateFrom
	 * @param datefrom
	 */
	public final void setDateFrom(java.util.Date datefrom)
	{
		setDateFrom(getContext(), datefrom);
	}

	/**
	 * Set value of DateFrom
	 * @param context
	 * @param datefrom
	 */
	public final void setDateFrom(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date datefrom)
	{
		getMendixObject().setValue(context, MemberNames.DateFrom.toString(), datefrom);
	}

	/**
	 * @return value of DateTo
	 */
	public final java.util.Date getDateTo()
	{
		return getDateTo(getContext());
	}

	/**
	 * @param context
	 * @return value of DateTo
	 */
	public final java.util.Date getDateTo(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.DateTo.toString());
	}

	/**
	 * Set value of DateTo
	 * @param dateto
	 */
	public final void setDateTo(java.util.Date dateto)
	{
		setDateTo(getContext(), dateto);
	}

	/**
	 * Set value of DateTo
	 * @param context
	 * @param dateto
	 */
	public final void setDateTo(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date dateto)
	{
		getMendixObject().setValue(context, MemberNames.DateTo.toString(), dateto);
	}

	/**
	 * @return value of InputTokensCurrentMonth
	 */
	public final java.lang.Integer getInputTokensCurrentMonth()
	{
		return getInputTokensCurrentMonth(getContext());
	}

	/**
	 * @param context
	 * @return value of InputTokensCurrentMonth
	 */
	public final java.lang.Integer getInputTokensCurrentMonth(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.InputTokensCurrentMonth.toString());
	}

	/**
	 * Set value of InputTokensCurrentMonth
	 * @param inputtokenscurrentmonth
	 */
	public final void setInputTokensCurrentMonth(java.lang.Integer inputtokenscurrentmonth)
	{
		setInputTokensCurrentMonth(getContext(), inputtokenscurrentmonth);
	}

	/**
	 * Set value of InputTokensCurrentMonth
	 * @param context
	 * @param inputtokenscurrentmonth
	 */
	public final void setInputTokensCurrentMonth(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer inputtokenscurrentmonth)
	{
		getMendixObject().setValue(context, MemberNames.InputTokensCurrentMonth.toString(), inputtokenscurrentmonth);
	}

	/**
	 * @return value of InputTokensCurrentMonthString
	 */
	public final java.lang.String getInputTokensCurrentMonthString()
	{
		return getInputTokensCurrentMonthString(getContext());
	}

	/**
	 * @param context
	 * @return value of InputTokensCurrentMonthString
	 */
	public final java.lang.String getInputTokensCurrentMonthString(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.InputTokensCurrentMonthString.toString());
	}

	/**
	 * Set value of InputTokensCurrentMonthString
	 * @param inputtokenscurrentmonthstring
	 */
	public final void setInputTokensCurrentMonthString(java.lang.String inputtokenscurrentmonthstring)
	{
		setInputTokensCurrentMonthString(getContext(), inputtokenscurrentmonthstring);
	}

	/**
	 * Set value of InputTokensCurrentMonthString
	 * @param context
	 * @param inputtokenscurrentmonthstring
	 */
	public final void setInputTokensCurrentMonthString(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String inputtokenscurrentmonthstring)
	{
		getMendixObject().setValue(context, MemberNames.InputTokensCurrentMonthString.toString(), inputtokenscurrentmonthstring);
	}

	/**
	 * @return value of OutputTokensCurrentMonth
	 */
	public final java.lang.Integer getOutputTokensCurrentMonth()
	{
		return getOutputTokensCurrentMonth(getContext());
	}

	/**
	 * @param context
	 * @return value of OutputTokensCurrentMonth
	 */
	public final java.lang.Integer getOutputTokensCurrentMonth(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.OutputTokensCurrentMonth.toString());
	}

	/**
	 * Set value of OutputTokensCurrentMonth
	 * @param outputtokenscurrentmonth
	 */
	public final void setOutputTokensCurrentMonth(java.lang.Integer outputtokenscurrentmonth)
	{
		setOutputTokensCurrentMonth(getContext(), outputtokenscurrentmonth);
	}

	/**
	 * Set value of OutputTokensCurrentMonth
	 * @param context
	 * @param outputtokenscurrentmonth
	 */
	public final void setOutputTokensCurrentMonth(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer outputtokenscurrentmonth)
	{
		getMendixObject().setValue(context, MemberNames.OutputTokensCurrentMonth.toString(), outputtokenscurrentmonth);
	}

	/**
	 * @return value of OutputTokensCurrentMonthString
	 */
	public final java.lang.String getOutputTokensCurrentMonthString()
	{
		return getOutputTokensCurrentMonthString(getContext());
	}

	/**
	 * @param context
	 * @return value of OutputTokensCurrentMonthString
	 */
	public final java.lang.String getOutputTokensCurrentMonthString(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.OutputTokensCurrentMonthString.toString());
	}

	/**
	 * Set value of OutputTokensCurrentMonthString
	 * @param outputtokenscurrentmonthstring
	 */
	public final void setOutputTokensCurrentMonthString(java.lang.String outputtokenscurrentmonthstring)
	{
		setOutputTokensCurrentMonthString(getContext(), outputtokenscurrentmonthstring);
	}

	/**
	 * Set value of OutputTokensCurrentMonthString
	 * @param context
	 * @param outputtokenscurrentmonthstring
	 */
	public final void setOutputTokensCurrentMonthString(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String outputtokenscurrentmonthstring)
	{
		getMendixObject().setValue(context, MemberNames.OutputTokensCurrentMonthString.toString(), outputtokenscurrentmonthstring);
	}

	/**
	 * Get value of TimeRange
	 * @param timerange
	 */
	public final conversationalui.proxies.ENUM_TimeRange getTimeRange()
	{
		return getTimeRange(getContext());
	}

	/**
	 * @param context
	 * @return value of TimeRange
	 */
	public final conversationalui.proxies.ENUM_TimeRange getTimeRange(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.TimeRange.toString());
		if (obj == null) {
			return null;
		}
		return conversationalui.proxies.ENUM_TimeRange.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of TimeRange
	 * @param timerange
	 */
	public final void setTimeRange(conversationalui.proxies.ENUM_TimeRange timerange)
	{
		setTimeRange(getContext(), timerange);
	}

	/**
	 * Set value of TimeRange
	 * @param context
	 * @param timerange
	 */
	public final void setTimeRange(com.mendix.systemwideinterfaces.core.IContext context, conversationalui.proxies.ENUM_TimeRange timerange)
	{
		if (timerange != null) {
			getMendixObject().setValue(context, MemberNames.TimeRange.toString(), timerange.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.TimeRange.toString(), null);
		}
	}

	/**
	 * Get value of Granularity
	 * @param granularity
	 */
	public final conversationalui.proxies.ENUM_Granularity getGranularity()
	{
		return getGranularity(getContext());
	}

	/**
	 * @param context
	 * @return value of Granularity
	 */
	public final conversationalui.proxies.ENUM_Granularity getGranularity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Granularity.toString());
		if (obj == null) {
			return null;
		}
		return conversationalui.proxies.ENUM_Granularity.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Granularity
	 * @param granularity
	 */
	public final void setGranularity(conversationalui.proxies.ENUM_Granularity granularity)
	{
		setGranularity(getContext(), granularity);
	}

	/**
	 * Set value of Granularity
	 * @param context
	 * @param granularity
	 */
	public final void setGranularity(com.mendix.systemwideinterfaces.core.IContext context, conversationalui.proxies.ENUM_Granularity granularity)
	{
		if (granularity != null) {
			getMendixObject().setValue(context, MemberNames.Granularity.toString(), granularity.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.Granularity.toString(), null);
		}
	}

	/**
	 * @return value of ShowOutput
	 */
	public final java.lang.Boolean getShowOutput()
	{
		return getShowOutput(getContext());
	}

	/**
	 * @param context
	 * @return value of ShowOutput
	 */
	public final java.lang.Boolean getShowOutput(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ShowOutput.toString());
	}

	/**
	 * Set value of ShowOutput
	 * @param showoutput
	 */
	public final void setShowOutput(java.lang.Boolean showoutput)
	{
		setShowOutput(getContext(), showoutput);
	}

	/**
	 * Set value of ShowOutput
	 * @param context
	 * @param showoutput
	 */
	public final void setShowOutput(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean showoutput)
	{
		getMendixObject().setValue(context, MemberNames.ShowOutput.toString(), showoutput);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of TokenMonitorSettings_DeploymentSelection_Selected
	 */
	public final conversationalui.proxies.DeploymentSelection getTokenMonitorSettings_DeploymentSelection_Selected() throws com.mendix.core.CoreException
	{
		return getTokenMonitorSettings_DeploymentSelection_Selected(getContext());
	}

	/**
	 * @param context
	 * @return value of TokenMonitorSettings_DeploymentSelection_Selected
	 * @throws com.mendix.core.CoreException
	 */
	public final conversationalui.proxies.DeploymentSelection getTokenMonitorSettings_DeploymentSelection_Selected(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		conversationalui.proxies.DeploymentSelection result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.TokenMonitorSettings_DeploymentSelection_Selected.toString());
		if (identifier != null) {
			result = conversationalui.proxies.DeploymentSelection.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of TokenMonitorSettings_DeploymentSelection_Selected
	 * @param tokenmonitorsettings_deploymentselection_selected
	 */
	public final void setTokenMonitorSettings_DeploymentSelection_Selected(conversationalui.proxies.DeploymentSelection tokenmonitorsettings_deploymentselection_selected)
	{
		setTokenMonitorSettings_DeploymentSelection_Selected(getContext(), tokenmonitorsettings_deploymentselection_selected);
	}

	/**
	 * Set value of TokenMonitorSettings_DeploymentSelection_Selected
	 * @param context
	 * @param tokenmonitorsettings_deploymentselection_selected
	 */
	public final void setTokenMonitorSettings_DeploymentSelection_Selected(com.mendix.systemwideinterfaces.core.IContext context, conversationalui.proxies.DeploymentSelection tokenmonitorsettings_deploymentselection_selected)
	{
		if (tokenmonitorsettings_deploymentselection_selected == null) {
			getMendixObject().setValue(context, MemberNames.TokenMonitorSettings_DeploymentSelection_Selected.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.TokenMonitorSettings_DeploymentSelection_Selected.toString(), tokenmonitorsettings_deploymentselection_selected.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of TokenMonitorSettings_DeploymentSelection
	 */
	public final java.util.List<conversationalui.proxies.DeploymentSelection> getTokenMonitorSettings_DeploymentSelection() throws com.mendix.core.CoreException
	{
		return getTokenMonitorSettings_DeploymentSelection(getContext());
	}

	/**
	 * @param context
	 * @return value of TokenMonitorSettings_DeploymentSelection
	 * @throws com.mendix.core.CoreException
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<conversationalui.proxies.DeploymentSelection> getTokenMonitorSettings_DeploymentSelection(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<conversationalui.proxies.DeploymentSelection> result = new java.util.ArrayList<>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.TokenMonitorSettings_DeploymentSelection.toString());
		if (valueObject == null) {
			return result;
		}
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject)) {
			result.add(conversationalui.proxies.DeploymentSelection.initialize(context, mendixObject));
		}
		return result;
	}

	/**
	 * Set value of TokenMonitorSettings_DeploymentSelection
	 * @param tokenmonitorsettings_deploymentselection
	 */
	public final void setTokenMonitorSettings_DeploymentSelection(java.util.List<conversationalui.proxies.DeploymentSelection> tokenmonitorsettings_deploymentselection)
	{
		setTokenMonitorSettings_DeploymentSelection(getContext(), tokenmonitorsettings_deploymentselection);
	}

	/**
	 * Set value of TokenMonitorSettings_DeploymentSelection
	 * @param context
	 * @param tokenmonitorsettings_deploymentselection
	 */
	public final void setTokenMonitorSettings_DeploymentSelection(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<conversationalui.proxies.DeploymentSelection> tokenmonitorsettings_deploymentselection)
	{
		var identifiers = tokenmonitorsettings_deploymentselection
			.stream()
			.map(proxyObject -> proxyObject.getMendixObject().getId())
			.collect(java.util.stream.Collectors.toList());
		
		getMendixObject().setValue(context, MemberNames.TokenMonitorSettings_DeploymentSelection.toString(), identifiers);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return tokenMonitorSettingsMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final conversationalui.proxies.TokenMonitorSettings that = (conversationalui.proxies.TokenMonitorSettings) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
