// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package conversationalui.proxies;

public class TraceChartView implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject traceChartViewMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "ConversationalUI.TraceChartView";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		InputTokens("InputTokens"),
		OutputTokens("OutputTokens"),
		TimeFrameBeginning("TimeFrameBeginning"),
		TimeFrameEnd("TimeFrameEnd"),
		TotalInvocations("TotalInvocations"),
		TotalConversations("TotalConversations"),
		TraceChartView_TraceFiltering("ConversationalUI.TraceChartView_TraceFiltering");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public TraceChartView(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected TraceChartView(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject traceChartViewMendixObject)
	{
		if (traceChartViewMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!traceChartViewMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.traceChartViewMendixObject = traceChartViewMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static conversationalui.proxies.TraceChartView initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new conversationalui.proxies.TraceChartView(context, mendixObject);
	}

	public static conversationalui.proxies.TraceChartView load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return conversationalui.proxies.TraceChartView.initialize(context, mendixObject);
	}

	/**
	 * @return value of InputTokens
	 */
	public final java.lang.Integer getInputTokens()
	{
		return getInputTokens(getContext());
	}

	/**
	 * @param context
	 * @return value of InputTokens
	 */
	public final java.lang.Integer getInputTokens(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.InputTokens.toString());
	}

	/**
	 * Set value of InputTokens
	 * @param inputtokens
	 */
	public final void setInputTokens(java.lang.Integer inputtokens)
	{
		setInputTokens(getContext(), inputtokens);
	}

	/**
	 * Set value of InputTokens
	 * @param context
	 * @param inputtokens
	 */
	public final void setInputTokens(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer inputtokens)
	{
		getMendixObject().setValue(context, MemberNames.InputTokens.toString(), inputtokens);
	}

	/**
	 * @return value of OutputTokens
	 */
	public final java.lang.Integer getOutputTokens()
	{
		return getOutputTokens(getContext());
	}

	/**
	 * @param context
	 * @return value of OutputTokens
	 */
	public final java.lang.Integer getOutputTokens(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.OutputTokens.toString());
	}

	/**
	 * Set value of OutputTokens
	 * @param outputtokens
	 */
	public final void setOutputTokens(java.lang.Integer outputtokens)
	{
		setOutputTokens(getContext(), outputtokens);
	}

	/**
	 * Set value of OutputTokens
	 * @param context
	 * @param outputtokens
	 */
	public final void setOutputTokens(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer outputtokens)
	{
		getMendixObject().setValue(context, MemberNames.OutputTokens.toString(), outputtokens);
	}

	/**
	 * @return value of TimeFrameBeginning
	 */
	public final java.util.Date getTimeFrameBeginning()
	{
		return getTimeFrameBeginning(getContext());
	}

	/**
	 * @param context
	 * @return value of TimeFrameBeginning
	 */
	public final java.util.Date getTimeFrameBeginning(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.TimeFrameBeginning.toString());
	}

	/**
	 * Set value of TimeFrameBeginning
	 * @param timeframebeginning
	 */
	public final void setTimeFrameBeginning(java.util.Date timeframebeginning)
	{
		setTimeFrameBeginning(getContext(), timeframebeginning);
	}

	/**
	 * Set value of TimeFrameBeginning
	 * @param context
	 * @param timeframebeginning
	 */
	public final void setTimeFrameBeginning(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date timeframebeginning)
	{
		getMendixObject().setValue(context, MemberNames.TimeFrameBeginning.toString(), timeframebeginning);
	}

	/**
	 * @return value of TimeFrameEnd
	 */
	public final java.util.Date getTimeFrameEnd()
	{
		return getTimeFrameEnd(getContext());
	}

	/**
	 * @param context
	 * @return value of TimeFrameEnd
	 */
	public final java.util.Date getTimeFrameEnd(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.TimeFrameEnd.toString());
	}

	/**
	 * Set value of TimeFrameEnd
	 * @param timeframeend
	 */
	public final void setTimeFrameEnd(java.util.Date timeframeend)
	{
		setTimeFrameEnd(getContext(), timeframeend);
	}

	/**
	 * Set value of TimeFrameEnd
	 * @param context
	 * @param timeframeend
	 */
	public final void setTimeFrameEnd(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date timeframeend)
	{
		getMendixObject().setValue(context, MemberNames.TimeFrameEnd.toString(), timeframeend);
	}

	/**
	 * @return value of TotalInvocations
	 */
	public final java.lang.Integer getTotalInvocations()
	{
		return getTotalInvocations(getContext());
	}

	/**
	 * @param context
	 * @return value of TotalInvocations
	 */
	public final java.lang.Integer getTotalInvocations(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.TotalInvocations.toString());
	}

	/**
	 * Set value of TotalInvocations
	 * @param totalinvocations
	 */
	public final void setTotalInvocations(java.lang.Integer totalinvocations)
	{
		setTotalInvocations(getContext(), totalinvocations);
	}

	/**
	 * Set value of TotalInvocations
	 * @param context
	 * @param totalinvocations
	 */
	public final void setTotalInvocations(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer totalinvocations)
	{
		getMendixObject().setValue(context, MemberNames.TotalInvocations.toString(), totalinvocations);
	}

	/**
	 * @return value of TotalConversations
	 */
	public final java.lang.Integer getTotalConversations()
	{
		return getTotalConversations(getContext());
	}

	/**
	 * @param context
	 * @return value of TotalConversations
	 */
	public final java.lang.Integer getTotalConversations(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.TotalConversations.toString());
	}

	/**
	 * Set value of TotalConversations
	 * @param totalconversations
	 */
	public final void setTotalConversations(java.lang.Integer totalconversations)
	{
		setTotalConversations(getContext(), totalconversations);
	}

	/**
	 * Set value of TotalConversations
	 * @param context
	 * @param totalconversations
	 */
	public final void setTotalConversations(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer totalconversations)
	{
		getMendixObject().setValue(context, MemberNames.TotalConversations.toString(), totalconversations);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of TraceChartView_TraceFiltering
	 */
	public final conversationalui.proxies.TraceFiltering getTraceChartView_TraceFiltering() throws com.mendix.core.CoreException
	{
		return getTraceChartView_TraceFiltering(getContext());
	}

	/**
	 * @param context
	 * @return value of TraceChartView_TraceFiltering
	 * @throws com.mendix.core.CoreException
	 */
	public final conversationalui.proxies.TraceFiltering getTraceChartView_TraceFiltering(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		conversationalui.proxies.TraceFiltering result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.TraceChartView_TraceFiltering.toString());
		if (identifier != null) {
			result = conversationalui.proxies.TraceFiltering.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of TraceChartView_TraceFiltering
	 * @param tracechartview_tracefiltering
	 */
	public final void setTraceChartView_TraceFiltering(conversationalui.proxies.TraceFiltering tracechartview_tracefiltering)
	{
		setTraceChartView_TraceFiltering(getContext(), tracechartview_tracefiltering);
	}

	/**
	 * Set value of TraceChartView_TraceFiltering
	 * @param context
	 * @param tracechartview_tracefiltering
	 */
	public final void setTraceChartView_TraceFiltering(com.mendix.systemwideinterfaces.core.IContext context, conversationalui.proxies.TraceFiltering tracechartview_tracefiltering)
	{
		if (tracechartview_tracefiltering == null) {
			getMendixObject().setValue(context, MemberNames.TraceChartView_TraceFiltering.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.TraceChartView_TraceFiltering.toString(), tracechartview_tracefiltering.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return traceChartViewMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final conversationalui.proxies.TraceChartView that = (conversationalui.proxies.TraceChartView) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
