// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package conversationalui.proxies;

public class TraceFiltering implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject traceFilteringMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "ConversationalUI.TraceFiltering";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		DateFrom("DateFrom"),
		DateTo("DateTo"),
		TimeRange("TimeRange"),
		Granularity("Granularity"),
		MinDuration("MinDuration"),
		MaxDuration("MaxDuration"),
		MinTotalTokens("MinTotalTokens"),
		MaxTotalTokens("MaxTotalTokens"),
		MinInputTokens("MinInputTokens"),
		MaxInputTokens("MaxInputTokens"),
		MinOutputTokens("MinOutputTokens"),
		MaxOutputTokens("MaxOutputTokens"),
		ShowOnlyError("ShowOnlyError"),
		ConversationID("ConversationID"),
		TraceID("TraceID"),
		TotalInvocations("TotalInvocations"),
		TotalConversations("TotalConversations"),
		DurationP50("DurationP50"),
		DurationP95("DurationP95"),
		TotalToken("TotalToken"),
		TotalInputTokens("TotalInputTokens"),
		TotalOutputTokens("TotalOutputTokens"),
		ShowFilterActive("ShowFilterActive"),
		ChartType("ChartType"),
		ErrorCount("ErrorCount"),
		ErrorRate("ErrorRate"),
		TraceFiltering_Version("ConversationalUI.TraceFiltering_Version"),
		TraceFiltering_Agent("ConversationalUI.TraceFiltering_Agent");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public TraceFiltering(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected TraceFiltering(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject traceFilteringMendixObject)
	{
		if (traceFilteringMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!traceFilteringMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.traceFilteringMendixObject = traceFilteringMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static conversationalui.proxies.TraceFiltering initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new conversationalui.proxies.TraceFiltering(context, mendixObject);
	}

	public static conversationalui.proxies.TraceFiltering load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return conversationalui.proxies.TraceFiltering.initialize(context, mendixObject);
	}

	public static java.util.List<conversationalui.proxies.TraceFiltering> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> conversationalui.proxies.TraceFiltering.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of DateFrom
	 */
	public final java.util.Date getDateFrom()
	{
		return getDateFrom(getContext());
	}

	/**
	 * @param context
	 * @return value of DateFrom
	 */
	public final java.util.Date getDateFrom(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.DateFrom.toString());
	}

	/**
	 * Set value of DateFrom
	 * @param datefrom
	 */
	public final void setDateFrom(java.util.Date datefrom)
	{
		setDateFrom(getContext(), datefrom);
	}

	/**
	 * Set value of DateFrom
	 * @param context
	 * @param datefrom
	 */
	public final void setDateFrom(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date datefrom)
	{
		getMendixObject().setValue(context, MemberNames.DateFrom.toString(), datefrom);
	}

	/**
	 * @return value of DateTo
	 */
	public final java.util.Date getDateTo()
	{
		return getDateTo(getContext());
	}

	/**
	 * @param context
	 * @return value of DateTo
	 */
	public final java.util.Date getDateTo(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.DateTo.toString());
	}

	/**
	 * Set value of DateTo
	 * @param dateto
	 */
	public final void setDateTo(java.util.Date dateto)
	{
		setDateTo(getContext(), dateto);
	}

	/**
	 * Set value of DateTo
	 * @param context
	 * @param dateto
	 */
	public final void setDateTo(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date dateto)
	{
		getMendixObject().setValue(context, MemberNames.DateTo.toString(), dateto);
	}

	/**
	 * Get value of TimeRange
	 * @param timerange
	 */
	public final conversationalui.proxies.ENUM_TimeRange getTimeRange()
	{
		return getTimeRange(getContext());
	}

	/**
	 * @param context
	 * @return value of TimeRange
	 */
	public final conversationalui.proxies.ENUM_TimeRange getTimeRange(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.TimeRange.toString());
		if (obj == null) {
			return null;
		}
		return conversationalui.proxies.ENUM_TimeRange.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of TimeRange
	 * @param timerange
	 */
	public final void setTimeRange(conversationalui.proxies.ENUM_TimeRange timerange)
	{
		setTimeRange(getContext(), timerange);
	}

	/**
	 * Set value of TimeRange
	 * @param context
	 * @param timerange
	 */
	public final void setTimeRange(com.mendix.systemwideinterfaces.core.IContext context, conversationalui.proxies.ENUM_TimeRange timerange)
	{
		if (timerange != null) {
			getMendixObject().setValue(context, MemberNames.TimeRange.toString(), timerange.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.TimeRange.toString(), null);
		}
	}

	/**
	 * Get value of Granularity
	 * @param granularity
	 */
	public final conversationalui.proxies.ENUM_Granularity getGranularity()
	{
		return getGranularity(getContext());
	}

	/**
	 * @param context
	 * @return value of Granularity
	 */
	public final conversationalui.proxies.ENUM_Granularity getGranularity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Granularity.toString());
		if (obj == null) {
			return null;
		}
		return conversationalui.proxies.ENUM_Granularity.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Granularity
	 * @param granularity
	 */
	public final void setGranularity(conversationalui.proxies.ENUM_Granularity granularity)
	{
		setGranularity(getContext(), granularity);
	}

	/**
	 * Set value of Granularity
	 * @param context
	 * @param granularity
	 */
	public final void setGranularity(com.mendix.systemwideinterfaces.core.IContext context, conversationalui.proxies.ENUM_Granularity granularity)
	{
		if (granularity != null) {
			getMendixObject().setValue(context, MemberNames.Granularity.toString(), granularity.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.Granularity.toString(), null);
		}
	}

	/**
	 * @return value of MinDuration
	 */
	public final java.math.BigDecimal getMinDuration()
	{
		return getMinDuration(getContext());
	}

	/**
	 * @param context
	 * @return value of MinDuration
	 */
	public final java.math.BigDecimal getMinDuration(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.MinDuration.toString());
	}

	/**
	 * Set value of MinDuration
	 * @param minduration
	 */
	public final void setMinDuration(java.math.BigDecimal minduration)
	{
		setMinDuration(getContext(), minduration);
	}

	/**
	 * Set value of MinDuration
	 * @param context
	 * @param minduration
	 */
	public final void setMinDuration(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal minduration)
	{
		getMendixObject().setValue(context, MemberNames.MinDuration.toString(), minduration);
	}

	/**
	 * @return value of MaxDuration
	 */
	public final java.math.BigDecimal getMaxDuration()
	{
		return getMaxDuration(getContext());
	}

	/**
	 * @param context
	 * @return value of MaxDuration
	 */
	public final java.math.BigDecimal getMaxDuration(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.MaxDuration.toString());
	}

	/**
	 * Set value of MaxDuration
	 * @param maxduration
	 */
	public final void setMaxDuration(java.math.BigDecimal maxduration)
	{
		setMaxDuration(getContext(), maxduration);
	}

	/**
	 * Set value of MaxDuration
	 * @param context
	 * @param maxduration
	 */
	public final void setMaxDuration(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal maxduration)
	{
		getMendixObject().setValue(context, MemberNames.MaxDuration.toString(), maxduration);
	}

	/**
	 * @return value of MinTotalTokens
	 */
	public final java.lang.Integer getMinTotalTokens()
	{
		return getMinTotalTokens(getContext());
	}

	/**
	 * @param context
	 * @return value of MinTotalTokens
	 */
	public final java.lang.Integer getMinTotalTokens(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.MinTotalTokens.toString());
	}

	/**
	 * Set value of MinTotalTokens
	 * @param mintotaltokens
	 */
	public final void setMinTotalTokens(java.lang.Integer mintotaltokens)
	{
		setMinTotalTokens(getContext(), mintotaltokens);
	}

	/**
	 * Set value of MinTotalTokens
	 * @param context
	 * @param mintotaltokens
	 */
	public final void setMinTotalTokens(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer mintotaltokens)
	{
		getMendixObject().setValue(context, MemberNames.MinTotalTokens.toString(), mintotaltokens);
	}

	/**
	 * @return value of MaxTotalTokens
	 */
	public final java.lang.Integer getMaxTotalTokens()
	{
		return getMaxTotalTokens(getContext());
	}

	/**
	 * @param context
	 * @return value of MaxTotalTokens
	 */
	public final java.lang.Integer getMaxTotalTokens(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.MaxTotalTokens.toString());
	}

	/**
	 * Set value of MaxTotalTokens
	 * @param maxtotaltokens
	 */
	public final void setMaxTotalTokens(java.lang.Integer maxtotaltokens)
	{
		setMaxTotalTokens(getContext(), maxtotaltokens);
	}

	/**
	 * Set value of MaxTotalTokens
	 * @param context
	 * @param maxtotaltokens
	 */
	public final void setMaxTotalTokens(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer maxtotaltokens)
	{
		getMendixObject().setValue(context, MemberNames.MaxTotalTokens.toString(), maxtotaltokens);
	}

	/**
	 * @return value of MinInputTokens
	 */
	public final java.lang.Integer getMinInputTokens()
	{
		return getMinInputTokens(getContext());
	}

	/**
	 * @param context
	 * @return value of MinInputTokens
	 */
	public final java.lang.Integer getMinInputTokens(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.MinInputTokens.toString());
	}

	/**
	 * Set value of MinInputTokens
	 * @param mininputtokens
	 */
	public final void setMinInputTokens(java.lang.Integer mininputtokens)
	{
		setMinInputTokens(getContext(), mininputtokens);
	}

	/**
	 * Set value of MinInputTokens
	 * @param context
	 * @param mininputtokens
	 */
	public final void setMinInputTokens(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer mininputtokens)
	{
		getMendixObject().setValue(context, MemberNames.MinInputTokens.toString(), mininputtokens);
	}

	/**
	 * @return value of MaxInputTokens
	 */
	public final java.lang.Integer getMaxInputTokens()
	{
		return getMaxInputTokens(getContext());
	}

	/**
	 * @param context
	 * @return value of MaxInputTokens
	 */
	public final java.lang.Integer getMaxInputTokens(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.MaxInputTokens.toString());
	}

	/**
	 * Set value of MaxInputTokens
	 * @param maxinputtokens
	 */
	public final void setMaxInputTokens(java.lang.Integer maxinputtokens)
	{
		setMaxInputTokens(getContext(), maxinputtokens);
	}

	/**
	 * Set value of MaxInputTokens
	 * @param context
	 * @param maxinputtokens
	 */
	public final void setMaxInputTokens(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer maxinputtokens)
	{
		getMendixObject().setValue(context, MemberNames.MaxInputTokens.toString(), maxinputtokens);
	}

	/**
	 * @return value of MinOutputTokens
	 */
	public final java.lang.Integer getMinOutputTokens()
	{
		return getMinOutputTokens(getContext());
	}

	/**
	 * @param context
	 * @return value of MinOutputTokens
	 */
	public final java.lang.Integer getMinOutputTokens(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.MinOutputTokens.toString());
	}

	/**
	 * Set value of MinOutputTokens
	 * @param minoutputtokens
	 */
	public final void setMinOutputTokens(java.lang.Integer minoutputtokens)
	{
		setMinOutputTokens(getContext(), minoutputtokens);
	}

	/**
	 * Set value of MinOutputTokens
	 * @param context
	 * @param minoutputtokens
	 */
	public final void setMinOutputTokens(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer minoutputtokens)
	{
		getMendixObject().setValue(context, MemberNames.MinOutputTokens.toString(), minoutputtokens);
	}

	/**
	 * @return value of MaxOutputTokens
	 */
	public final java.lang.Integer getMaxOutputTokens()
	{
		return getMaxOutputTokens(getContext());
	}

	/**
	 * @param context
	 * @return value of MaxOutputTokens
	 */
	public final java.lang.Integer getMaxOutputTokens(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.MaxOutputTokens.toString());
	}

	/**
	 * Set value of MaxOutputTokens
	 * @param maxoutputtokens
	 */
	public final void setMaxOutputTokens(java.lang.Integer maxoutputtokens)
	{
		setMaxOutputTokens(getContext(), maxoutputtokens);
	}

	/**
	 * Set value of MaxOutputTokens
	 * @param context
	 * @param maxoutputtokens
	 */
	public final void setMaxOutputTokens(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer maxoutputtokens)
	{
		getMendixObject().setValue(context, MemberNames.MaxOutputTokens.toString(), maxoutputtokens);
	}

	/**
	 * @return value of ShowOnlyError
	 */
	public final java.lang.Boolean getShowOnlyError()
	{
		return getShowOnlyError(getContext());
	}

	/**
	 * @param context
	 * @return value of ShowOnlyError
	 */
	public final java.lang.Boolean getShowOnlyError(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ShowOnlyError.toString());
	}

	/**
	 * Set value of ShowOnlyError
	 * @param showonlyerror
	 */
	public final void setShowOnlyError(java.lang.Boolean showonlyerror)
	{
		setShowOnlyError(getContext(), showonlyerror);
	}

	/**
	 * Set value of ShowOnlyError
	 * @param context
	 * @param showonlyerror
	 */
	public final void setShowOnlyError(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean showonlyerror)
	{
		getMendixObject().setValue(context, MemberNames.ShowOnlyError.toString(), showonlyerror);
	}

	/**
	 * @return value of ConversationID
	 */
	public final java.lang.String getConversationID()
	{
		return getConversationID(getContext());
	}

	/**
	 * @param context
	 * @return value of ConversationID
	 */
	public final java.lang.String getConversationID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ConversationID.toString());
	}

	/**
	 * Set value of ConversationID
	 * @param conversationid
	 */
	public final void setConversationID(java.lang.String conversationid)
	{
		setConversationID(getContext(), conversationid);
	}

	/**
	 * Set value of ConversationID
	 * @param context
	 * @param conversationid
	 */
	public final void setConversationID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String conversationid)
	{
		getMendixObject().setValue(context, MemberNames.ConversationID.toString(), conversationid);
	}

	/**
	 * @return value of TraceID
	 */
	public final java.lang.String getTraceID()
	{
		return getTraceID(getContext());
	}

	/**
	 * @param context
	 * @return value of TraceID
	 */
	public final java.lang.String getTraceID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.TraceID.toString());
	}

	/**
	 * Set value of TraceID
	 * @param traceid
	 */
	public final void setTraceID(java.lang.String traceid)
	{
		setTraceID(getContext(), traceid);
	}

	/**
	 * Set value of TraceID
	 * @param context
	 * @param traceid
	 */
	public final void setTraceID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String traceid)
	{
		getMendixObject().setValue(context, MemberNames.TraceID.toString(), traceid);
	}

	/**
	 * @return value of TotalInvocations
	 */
	public final java.lang.Integer getTotalInvocations()
	{
		return getTotalInvocations(getContext());
	}

	/**
	 * @param context
	 * @return value of TotalInvocations
	 */
	public final java.lang.Integer getTotalInvocations(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.TotalInvocations.toString());
	}

	/**
	 * Set value of TotalInvocations
	 * @param totalinvocations
	 */
	public final void setTotalInvocations(java.lang.Integer totalinvocations)
	{
		setTotalInvocations(getContext(), totalinvocations);
	}

	/**
	 * Set value of TotalInvocations
	 * @param context
	 * @param totalinvocations
	 */
	public final void setTotalInvocations(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer totalinvocations)
	{
		getMendixObject().setValue(context, MemberNames.TotalInvocations.toString(), totalinvocations);
	}

	/**
	 * @return value of TotalConversations
	 */
	public final java.lang.Integer getTotalConversations()
	{
		return getTotalConversations(getContext());
	}

	/**
	 * @param context
	 * @return value of TotalConversations
	 */
	public final java.lang.Integer getTotalConversations(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.TotalConversations.toString());
	}

	/**
	 * Set value of TotalConversations
	 * @param totalconversations
	 */
	public final void setTotalConversations(java.lang.Integer totalconversations)
	{
		setTotalConversations(getContext(), totalconversations);
	}

	/**
	 * Set value of TotalConversations
	 * @param context
	 * @param totalconversations
	 */
	public final void setTotalConversations(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer totalconversations)
	{
		getMendixObject().setValue(context, MemberNames.TotalConversations.toString(), totalconversations);
	}

	/**
	 * @return value of DurationP50
	 */
	public final java.math.BigDecimal getDurationP50()
	{
		return getDurationP50(getContext());
	}

	/**
	 * @param context
	 * @return value of DurationP50
	 */
	public final java.math.BigDecimal getDurationP50(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.DurationP50.toString());
	}

	/**
	 * Set value of DurationP50
	 * @param durationp50
	 */
	public final void setDurationP50(java.math.BigDecimal durationp50)
	{
		setDurationP50(getContext(), durationp50);
	}

	/**
	 * Set value of DurationP50
	 * @param context
	 * @param durationp50
	 */
	public final void setDurationP50(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal durationp50)
	{
		getMendixObject().setValue(context, MemberNames.DurationP50.toString(), durationp50);
	}

	/**
	 * @return value of DurationP95
	 */
	public final java.math.BigDecimal getDurationP95()
	{
		return getDurationP95(getContext());
	}

	/**
	 * @param context
	 * @return value of DurationP95
	 */
	public final java.math.BigDecimal getDurationP95(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.DurationP95.toString());
	}

	/**
	 * Set value of DurationP95
	 * @param durationp95
	 */
	public final void setDurationP95(java.math.BigDecimal durationp95)
	{
		setDurationP95(getContext(), durationp95);
	}

	/**
	 * Set value of DurationP95
	 * @param context
	 * @param durationp95
	 */
	public final void setDurationP95(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal durationp95)
	{
		getMendixObject().setValue(context, MemberNames.DurationP95.toString(), durationp95);
	}

	/**
	 * @return value of TotalToken
	 */
	public final java.lang.Integer getTotalToken()
	{
		return getTotalToken(getContext());
	}

	/**
	 * @param context
	 * @return value of TotalToken
	 */
	public final java.lang.Integer getTotalToken(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.TotalToken.toString());
	}

	/**
	 * Set value of TotalToken
	 * @param totaltoken
	 */
	public final void setTotalToken(java.lang.Integer totaltoken)
	{
		setTotalToken(getContext(), totaltoken);
	}

	/**
	 * Set value of TotalToken
	 * @param context
	 * @param totaltoken
	 */
	public final void setTotalToken(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer totaltoken)
	{
		getMendixObject().setValue(context, MemberNames.TotalToken.toString(), totaltoken);
	}

	/**
	 * @return value of TotalInputTokens
	 */
	public final java.lang.Integer getTotalInputTokens()
	{
		return getTotalInputTokens(getContext());
	}

	/**
	 * @param context
	 * @return value of TotalInputTokens
	 */
	public final java.lang.Integer getTotalInputTokens(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.TotalInputTokens.toString());
	}

	/**
	 * Set value of TotalInputTokens
	 * @param totalinputtokens
	 */
	public final void setTotalInputTokens(java.lang.Integer totalinputtokens)
	{
		setTotalInputTokens(getContext(), totalinputtokens);
	}

	/**
	 * Set value of TotalInputTokens
	 * @param context
	 * @param totalinputtokens
	 */
	public final void setTotalInputTokens(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer totalinputtokens)
	{
		getMendixObject().setValue(context, MemberNames.TotalInputTokens.toString(), totalinputtokens);
	}

	/**
	 * @return value of TotalOutputTokens
	 */
	public final java.lang.Integer getTotalOutputTokens()
	{
		return getTotalOutputTokens(getContext());
	}

	/**
	 * @param context
	 * @return value of TotalOutputTokens
	 */
	public final java.lang.Integer getTotalOutputTokens(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.TotalOutputTokens.toString());
	}

	/**
	 * Set value of TotalOutputTokens
	 * @param totaloutputtokens
	 */
	public final void setTotalOutputTokens(java.lang.Integer totaloutputtokens)
	{
		setTotalOutputTokens(getContext(), totaloutputtokens);
	}

	/**
	 * Set value of TotalOutputTokens
	 * @param context
	 * @param totaloutputtokens
	 */
	public final void setTotalOutputTokens(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer totaloutputtokens)
	{
		getMendixObject().setValue(context, MemberNames.TotalOutputTokens.toString(), totaloutputtokens);
	}

	/**
	 * @return value of ShowFilterActive
	 */
	public final java.lang.Boolean getShowFilterActive()
	{
		return getShowFilterActive(getContext());
	}

	/**
	 * @param context
	 * @return value of ShowFilterActive
	 */
	public final java.lang.Boolean getShowFilterActive(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ShowFilterActive.toString());
	}

	/**
	 * Set value of ShowFilterActive
	 * @param showfilteractive
	 */
	public final void setShowFilterActive(java.lang.Boolean showfilteractive)
	{
		setShowFilterActive(getContext(), showfilteractive);
	}

	/**
	 * Set value of ShowFilterActive
	 * @param context
	 * @param showfilteractive
	 */
	public final void setShowFilterActive(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean showfilteractive)
	{
		getMendixObject().setValue(context, MemberNames.ShowFilterActive.toString(), showfilteractive);
	}

	/**
	 * Get value of ChartType
	 * @param charttype
	 */
	public final conversationalui.proxies.ENUM_ChartType getChartType()
	{
		return getChartType(getContext());
	}

	/**
	 * @param context
	 * @return value of ChartType
	 */
	public final conversationalui.proxies.ENUM_ChartType getChartType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.ChartType.toString());
		if (obj == null) {
			return null;
		}
		return conversationalui.proxies.ENUM_ChartType.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of ChartType
	 * @param charttype
	 */
	public final void setChartType(conversationalui.proxies.ENUM_ChartType charttype)
	{
		setChartType(getContext(), charttype);
	}

	/**
	 * Set value of ChartType
	 * @param context
	 * @param charttype
	 */
	public final void setChartType(com.mendix.systemwideinterfaces.core.IContext context, conversationalui.proxies.ENUM_ChartType charttype)
	{
		if (charttype != null) {
			getMendixObject().setValue(context, MemberNames.ChartType.toString(), charttype.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.ChartType.toString(), null);
		}
	}

	/**
	 * @return value of ErrorCount
	 */
	public final java.lang.Integer getErrorCount()
	{
		return getErrorCount(getContext());
	}

	/**
	 * @param context
	 * @return value of ErrorCount
	 */
	public final java.lang.Integer getErrorCount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.ErrorCount.toString());
	}

	/**
	 * Set value of ErrorCount
	 * @param errorcount
	 */
	public final void setErrorCount(java.lang.Integer errorcount)
	{
		setErrorCount(getContext(), errorcount);
	}

	/**
	 * Set value of ErrorCount
	 * @param context
	 * @param errorcount
	 */
	public final void setErrorCount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer errorcount)
	{
		getMendixObject().setValue(context, MemberNames.ErrorCount.toString(), errorcount);
	}

	/**
	 * @return value of ErrorRate
	 */
	public final java.math.BigDecimal getErrorRate()
	{
		return getErrorRate(getContext());
	}

	/**
	 * @param context
	 * @return value of ErrorRate
	 */
	public final java.math.BigDecimal getErrorRate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.ErrorRate.toString());
	}

	/**
	 * Set value of ErrorRate
	 * @param errorrate
	 */
	public final void setErrorRate(java.math.BigDecimal errorrate)
	{
		setErrorRate(getContext(), errorrate);
	}

	/**
	 * Set value of ErrorRate
	 * @param context
	 * @param errorrate
	 */
	public final void setErrorRate(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal errorrate)
	{
		getMendixObject().setValue(context, MemberNames.ErrorRate.toString(), errorrate);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of TraceFiltering_Version
	 */
	public final java.util.List<agentcommons.proxies.Version> getTraceFiltering_Version() throws com.mendix.core.CoreException
	{
		return getTraceFiltering_Version(getContext());
	}

	/**
	 * @param context
	 * @return value of TraceFiltering_Version
	 * @throws com.mendix.core.CoreException
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<agentcommons.proxies.Version> getTraceFiltering_Version(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<agentcommons.proxies.Version> result = new java.util.ArrayList<>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.TraceFiltering_Version.toString());
		if (valueObject == null) {
			return result;
		}
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject)) {
			result.add(agentcommons.proxies.Version.initialize(context, mendixObject));
		}
		return result;
	}

	/**
	 * Set value of TraceFiltering_Version
	 * @param tracefiltering_version
	 */
	public final void setTraceFiltering_Version(java.util.List<agentcommons.proxies.Version> tracefiltering_version)
	{
		setTraceFiltering_Version(getContext(), tracefiltering_version);
	}

	/**
	 * Set value of TraceFiltering_Version
	 * @param context
	 * @param tracefiltering_version
	 */
	public final void setTraceFiltering_Version(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<agentcommons.proxies.Version> tracefiltering_version)
	{
		var identifiers = tracefiltering_version
			.stream()
			.map(proxyObject -> proxyObject.getMendixObject().getId())
			.collect(java.util.stream.Collectors.toList());
		
		getMendixObject().setValue(context, MemberNames.TraceFiltering_Version.toString(), identifiers);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of TraceFiltering_Agent
	 */
	public final java.util.List<agentcommons.proxies.Agent> getTraceFiltering_Agent() throws com.mendix.core.CoreException
	{
		return getTraceFiltering_Agent(getContext());
	}

	/**
	 * @param context
	 * @return value of TraceFiltering_Agent
	 * @throws com.mendix.core.CoreException
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<agentcommons.proxies.Agent> getTraceFiltering_Agent(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<agentcommons.proxies.Agent> result = new java.util.ArrayList<>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.TraceFiltering_Agent.toString());
		if (valueObject == null) {
			return result;
		}
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject)) {
			result.add(agentcommons.proxies.Agent.initialize(context, mendixObject));
		}
		return result;
	}

	/**
	 * Set value of TraceFiltering_Agent
	 * @param tracefiltering_agent
	 */
	public final void setTraceFiltering_Agent(java.util.List<agentcommons.proxies.Agent> tracefiltering_agent)
	{
		setTraceFiltering_Agent(getContext(), tracefiltering_agent);
	}

	/**
	 * Set value of TraceFiltering_Agent
	 * @param context
	 * @param tracefiltering_agent
	 */
	public final void setTraceFiltering_Agent(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<agentcommons.proxies.Agent> tracefiltering_agent)
	{
		var identifiers = tracefiltering_agent
			.stream()
			.map(proxyObject -> proxyObject.getMendixObject().getId())
			.collect(java.util.stream.Collectors.toList());
		
		getMendixObject().setValue(context, MemberNames.TraceFiltering_Agent.toString(), identifiers);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return traceFilteringMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final conversationalui.proxies.TraceFiltering that = (conversationalui.proxies.TraceFiltering) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
