// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package conversationalui.proxies;

public class TraceView implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject traceViewMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "ConversationalUI.TraceView";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		NrOfToolCalls("NrOfToolCalls"),
		NrOfMCPCalls("NrOfMCPCalls"),
		NrOfKBCalls("NrOfKBCalls"),
		PageCounter("PageCounter"),
		ShowCopyChecked("ShowCopyChecked");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public TraceView(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected TraceView(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject traceViewMendixObject)
	{
		if (traceViewMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!traceViewMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.traceViewMendixObject = traceViewMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static conversationalui.proxies.TraceView initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new conversationalui.proxies.TraceView(context, mendixObject);
	}

	public static conversationalui.proxies.TraceView load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return conversationalui.proxies.TraceView.initialize(context, mendixObject);
	}

	/**
	 * @return value of NrOfToolCalls
	 */
	public final java.lang.Integer getNrOfToolCalls()
	{
		return getNrOfToolCalls(getContext());
	}

	/**
	 * @param context
	 * @return value of NrOfToolCalls
	 */
	public final java.lang.Integer getNrOfToolCalls(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.NrOfToolCalls.toString());
	}

	/**
	 * Set value of NrOfToolCalls
	 * @param nroftoolcalls
	 */
	public final void setNrOfToolCalls(java.lang.Integer nroftoolcalls)
	{
		setNrOfToolCalls(getContext(), nroftoolcalls);
	}

	/**
	 * Set value of NrOfToolCalls
	 * @param context
	 * @param nroftoolcalls
	 */
	public final void setNrOfToolCalls(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer nroftoolcalls)
	{
		getMendixObject().setValue(context, MemberNames.NrOfToolCalls.toString(), nroftoolcalls);
	}

	/**
	 * @return value of NrOfMCPCalls
	 */
	public final java.lang.Integer getNrOfMCPCalls()
	{
		return getNrOfMCPCalls(getContext());
	}

	/**
	 * @param context
	 * @return value of NrOfMCPCalls
	 */
	public final java.lang.Integer getNrOfMCPCalls(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.NrOfMCPCalls.toString());
	}

	/**
	 * Set value of NrOfMCPCalls
	 * @param nrofmcpcalls
	 */
	public final void setNrOfMCPCalls(java.lang.Integer nrofmcpcalls)
	{
		setNrOfMCPCalls(getContext(), nrofmcpcalls);
	}

	/**
	 * Set value of NrOfMCPCalls
	 * @param context
	 * @param nrofmcpcalls
	 */
	public final void setNrOfMCPCalls(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer nrofmcpcalls)
	{
		getMendixObject().setValue(context, MemberNames.NrOfMCPCalls.toString(), nrofmcpcalls);
	}

	/**
	 * @return value of NrOfKBCalls
	 */
	public final java.lang.Integer getNrOfKBCalls()
	{
		return getNrOfKBCalls(getContext());
	}

	/**
	 * @param context
	 * @return value of NrOfKBCalls
	 */
	public final java.lang.Integer getNrOfKBCalls(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.NrOfKBCalls.toString());
	}

	/**
	 * Set value of NrOfKBCalls
	 * @param nrofkbcalls
	 */
	public final void setNrOfKBCalls(java.lang.Integer nrofkbcalls)
	{
		setNrOfKBCalls(getContext(), nrofkbcalls);
	}

	/**
	 * Set value of NrOfKBCalls
	 * @param context
	 * @param nrofkbcalls
	 */
	public final void setNrOfKBCalls(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer nrofkbcalls)
	{
		getMendixObject().setValue(context, MemberNames.NrOfKBCalls.toString(), nrofkbcalls);
	}

	/**
	 * @return value of PageCounter
	 */
	public final java.lang.Integer getPageCounter()
	{
		return getPageCounter(getContext());
	}

	/**
	 * @param context
	 * @return value of PageCounter
	 */
	public final java.lang.Integer getPageCounter(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.PageCounter.toString());
	}

	/**
	 * Set value of PageCounter
	 * @param pagecounter
	 */
	public final void setPageCounter(java.lang.Integer pagecounter)
	{
		setPageCounter(getContext(), pagecounter);
	}

	/**
	 * Set value of PageCounter
	 * @param context
	 * @param pagecounter
	 */
	public final void setPageCounter(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer pagecounter)
	{
		getMendixObject().setValue(context, MemberNames.PageCounter.toString(), pagecounter);
	}

	/**
	 * @return value of ShowCopyChecked
	 */
	public final java.lang.Boolean getShowCopyChecked()
	{
		return getShowCopyChecked(getContext());
	}

	/**
	 * @param context
	 * @return value of ShowCopyChecked
	 */
	public final java.lang.Boolean getShowCopyChecked(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ShowCopyChecked.toString());
	}

	/**
	 * Set value of ShowCopyChecked
	 * @param showcopychecked
	 */
	public final void setShowCopyChecked(java.lang.Boolean showcopychecked)
	{
		setShowCopyChecked(getContext(), showcopychecked);
	}

	/**
	 * Set value of ShowCopyChecked
	 * @param context
	 * @param showcopychecked
	 */
	public final void setShowCopyChecked(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean showcopychecked)
	{
		getMendixObject().setValue(context, MemberNames.ShowCopyChecked.toString(), showcopychecked);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return traceViewMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final conversationalui.proxies.TraceView that = (conversationalui.proxies.TraceView) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
