// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package datawidgets.proxies;

public enum Filter_Operators
{
	contains("39c760a6-b2fc-4a46-b797-0c6c4a98a4e4"),
	startsWith("61fab2ab-5730-4fd4-9f8d-0962839cdcb3"),
	endsWith("c4ef21dc-33c1-4963-9ba0-39aff81bdf8f"),
	between("0554f6df-2700-4e88-9c29-47c65ec51d36"),
	greater("eafcb5a5-047d-4b7d-9697-2a70b3234219"),
	greaterEqual("1b7d0205-755b-4760-addc-c7cc7f3ef9c8"),
	equal("039c3a7a-df78-440c-b9e7-1c4504ed7bb3"),
	notEqual("0f6f5618-1a05-4749-8622-5a14a0514ac7"),
	smaller("fabcd217-7be9-47c6-a0a5-c97fb56309da"),
	smallerEqual("5cc9db28-de25-4b7b-9885-25c71847dfb9"),
	empty("5edac37e-63f9-4ed5-8f5e-0e73579bc902"),
	notEmpty("a26c87a3-357a-4579-b131-8eb528fd1abb");

	private final java.lang.String i18nCaptionKey;
	
	private Filter_Operators(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
