// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mcpclient.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the MCPClient module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_DoNothingBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MCPClient.ACT_DoNothing");
		return builder;
	}

	public static void aCT_DoNothing(IContext context)
	{
		aCT_DoNothingBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_MCPServerConfiguration_DeleteBuilder(
		mcpclient.proxies.MCPServerConfiguration _mCPServerConfiguration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MCPClient.ACT_MCPServerConfiguration_Delete");
		builder = builder.withParam("MCPServerConfiguration", _mCPServerConfiguration);
		return builder;
	}

	public static void aCT_MCPServerConfiguration_Delete(
		IContext context,
		mcpclient.proxies.MCPServerConfiguration _mCPServerConfiguration
	)
	{
		aCT_MCPServerConfiguration_DeleteBuilder(
				_mCPServerConfiguration
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_MCPServerConfiguration_NewBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MCPClient.ACT_MCPServerConfiguration_New");
		return builder;
	}

	public static void aCT_MCPServerConfiguration_New(IContext context)
	{
		aCT_MCPServerConfiguration_NewBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_MCPServerConfiguration_SaveBuilder(
		mcpclient.proxies.MCPServerConfiguration _mCPServerConfiguration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MCPClient.ACT_MCPServerConfiguration_Save");
		builder = builder.withParam("MCPServerConfiguration", _mCPServerConfiguration);
		return builder;
	}

	public static void aCT_MCPServerConfiguration_Save(
		IContext context,
		mcpclient.proxies.MCPServerConfiguration _mCPServerConfiguration
	)
	{
		aCT_MCPServerConfiguration_SaveBuilder(
				_mCPServerConfiguration
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_MCPServerConfiguration_SyncToolsBuilder(
		mcpclient.proxies.MCPServerConfiguration _mCPServerConfiguration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MCPClient.ACT_MCPServerConfiguration_SyncTools");
		builder = builder.withParam("MCPServerConfiguration", _mCPServerConfiguration);
		return builder;
	}

	public static void aCT_MCPServerConfiguration_SyncTools(
		IContext context,
		mcpclient.proxies.MCPServerConfiguration _mCPServerConfiguration
	)
	{
		aCT_MCPServerConfiguration_SyncToolsBuilder(
				_mCPServerConfiguration
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_MCPServerConfiguration_SyncToolsForAllServersBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MCPClient.ACT_MCPServerConfiguration_SyncToolsForAllServers");
		return builder;
	}

	public static void aCT_MCPServerConfiguration_SyncToolsForAllServers(IContext context)
	{
		aCT_MCPServerConfiguration_SyncToolsForAllServersBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_MCPServerConfiguration_ViewToolsAndPromptsBuilder(
		mcpclient.proxies.MCPServerConfiguration _mCPServerConfiguration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MCPClient.ACT_MCPServerConfiguration_ViewToolsAndPrompts");
		builder = builder.withParam("MCPServerConfiguration", _mCPServerConfiguration);
		return builder;
	}

	public static void aCT_MCPServerConfiguration_ViewToolsAndPrompts(
		IContext context,
		mcpclient.proxies.MCPServerConfiguration _mCPServerConfiguration
	)
	{
		aCT_MCPServerConfiguration_ViewToolsAndPromptsBuilder(
				_mCPServerConfiguration
			)
			.execute(context);
	}
	/**
	 * Use this action to create an empty ArgumentCollection which can be used as input for the "Argument Collection: Add New Input" action. An ArgumentCollection may be used for the "Get Prompt" and "Call Tool" action if applicable.
	 */
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder argumentCollection_CreateBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MCPClient.ArgumentCollection_Create");
		return builder;
	}

	/**
	 * Use this action to create an empty ArgumentCollection which can be used as input for the "Argument Collection: Add New Input" action. An ArgumentCollection may be used for the "Get Prompt" and "Call Tool" action if applicable.
	 */
	public static mcpclient.proxies.ArgumentCollection argumentCollection_Create(IContext context)
	{
		Object result = argumentCollection_CreateBuilder().execute(context);
		return result == null ? null : mcpclient.proxies.ArgumentCollection.initialize(context, (IMendixObject) result);
	}
	/**
	 * Use this action to create a new ArgumentInput which is added to the ArgumentCollection (can be created via the "Initialize Argument Collection" action). An ArgumentInput represents each argument of the tool or prompt when using the "Get Prompt" and "Call Tool" action.
	 * Ensure that for each required argument an ArgumentInput is created.
	 */
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder argumentInput_CreateAndAddBuilder(
		mcpclient.proxies.ArgumentCollection _argumentCollection,
		java.lang.String _name,
		java.lang.String _value
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MCPClient.ArgumentInput_CreateAndAdd");
		builder = builder.withParam("ArgumentCollection", _argumentCollection);
		builder = builder.withParam("Name", _name);
		builder = builder.withParam("Value", _value);
		return builder;
	}

	/**
	 * Use this action to create a new ArgumentInput which is added to the ArgumentCollection (can be created via the "Initialize Argument Collection" action). An ArgumentInput represents each argument of the tool or prompt when using the "Get Prompt" and "Call Tool" action.
	 * Ensure that for each required argument an ArgumentInput is created.
	 */
	public static mcpclient.proxies.ArgumentInput argumentInput_CreateAndAdd(
		IContext context,
		mcpclient.proxies.ArgumentCollection _argumentCollection,
		java.lang.String _name,
		java.lang.String _value
	)
	{
		Object result = argumentInput_CreateAndAddBuilder(
				_argumentCollection,
				_name,
				_value
			)
			.execute(context);
		return result == null ? null : mcpclient.proxies.ArgumentInput.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_MCPServerConfiguration_MicroflowSelectionBuilder(
		mcpclient.proxies.MCPServerConfiguration _mCPServerConfiguration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MCPClient.DS_MCPServerConfiguration_MicroflowSelection");
		builder = builder.withParam("MCPServerConfiguration", _mCPServerConfiguration);
		return builder;
	}

	public static mcpclient.proxies.MicroflowSelection dS_MCPServerConfiguration_MicroflowSelection(
		IContext context,
		mcpclient.proxies.MCPServerConfiguration _mCPServerConfiguration
	)
	{
		Object result = dS_MCPServerConfiguration_MicroflowSelectionBuilder(
				_mCPServerConfiguration
			)
			.execute(context);
		return result == null ? null : mcpclient.proxies.MicroflowSelection.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder getCredentials_EXAMPLEBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MCPClient.GetCredentials_EXAMPLE");
		return builder;
	}

	public static java.util.List<system.proxies.HttpHeader> getCredentials_EXAMPLE(IContext context)
	{
		Object result = getCredentials_EXAMPLEBuilder().execute(context);
		return result == null ? null : com.mendix.utils.ListUtils.map((java.util.List<IMendixObject>) result, obj -> system.proxies.HttpHeader.initialize(context, obj));
	}
	/**
	 * Use this action to add Http Headers containing credentials to authenticate to the MCP server to your GetCredentials microflow that can be selected as part of the MCP server configuration.
	 */
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder httpHeader_CreateAndAddToListBuilder(
		java.util.List<system.proxies.HttpHeader> _httpHeaderList,
		java.lang.String _key,
		java.lang.String _value
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MCPClient.HttpHeader_CreateAndAddToList");
		builder = builder.withParam("HttpHeaderList", _httpHeaderList);
		builder = builder.withParam("Key", _key);
		builder = builder.withParam("Value", _value);
		return builder;
	}

	/**
	 * Use this action to add Http Headers containing credentials to authenticate to the MCP server to your GetCredentials microflow that can be selected as part of the MCP server configuration.
	 */
	public static void httpHeader_CreateAndAddToList(
		IContext context,
		java.util.List<system.proxies.HttpHeader> _httpHeaderList,
		java.lang.String _key,
		java.lang.String _value
	)
	{
		httpHeader_CreateAndAddToListBuilder(
				_httpHeaderList,
				_key,
				_value
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder mCPClient_ConnectToServerBuilder(
		mcpclient.proxies.MCPServerConfiguration _mCPServerConfiguration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MCPClient.MCPClient_ConnectToServer");
		builder = builder.withParam("MCPServerConfiguration", _mCPServerConfiguration);
		return builder;
	}

	public static mcpclient.proxies.MCPClient mCPClient_ConnectToServer(
		IContext context,
		mcpclient.proxies.MCPServerConfiguration _mCPServerConfiguration
	)
	{
		Object result = mCPClient_ConnectToServerBuilder(
				_mCPServerConfiguration
			)
			.execute(context);
		return result == null ? null : mcpclient.proxies.MCPClient.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder mCPClient_GetPromptsBuilder(
		mcpclient.proxies.MCPServerConfiguration _mCPServerConfiguration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MCPClient.MCPClient_GetPrompts");
		builder = builder.withParam("MCPServerConfiguration", _mCPServerConfiguration);
		return builder;
	}

	public static java.util.List<mcpclient.proxies.Prompt> mCPClient_GetPrompts(
		IContext context,
		mcpclient.proxies.MCPServerConfiguration _mCPServerConfiguration
	)
	{
		Object result = mCPClient_GetPromptsBuilder(
				_mCPServerConfiguration
			)
			.execute(context);
		return result == null ? null : com.mendix.utils.ListUtils.map((java.util.List<IMendixObject>) result, obj -> mcpclient.proxies.Prompt.initialize(context, obj));
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder mCPClient_GetToolsBuilder(
		mcpclient.proxies.MCPServerConfiguration _mCPServerConfiguration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MCPClient.MCPClient_GetTools");
		builder = builder.withParam("MCPServerConfiguration", _mCPServerConfiguration);
		return builder;
	}

	public static java.util.List<mcpclient.proxies.Tool> mCPClient_GetTools(
		IContext context,
		mcpclient.proxies.MCPServerConfiguration _mCPServerConfiguration
	)
	{
		Object result = mCPClient_GetToolsBuilder(
				_mCPServerConfiguration
			)
			.execute(context);
		return result == null ? null : com.mendix.utils.ListUtils.map((java.util.List<IMendixObject>) result, obj -> mcpclient.proxies.Tool.initialize(context, obj));
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder mCPClient_ToolMicroflowBuilder(
		genaicommons.proxies.Tool _tool,
		genaicommons.proxies.Request _request
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MCPClient.MCPClient_ToolMicroflow");
		builder = builder.withParam("Tool", _tool);
		builder = builder.withParam("Request", _request);
		return builder;
	}

	public static java.lang.String mCPClient_ToolMicroflow(
		IContext context,
		genaicommons.proxies.Tool _tool,
		genaicommons.proxies.Request _request
	)
	{
		Object result = mCPClient_ToolMicroflowBuilder(
				_tool,
				_request
			)
			.execute(context);
		return (java.lang.String) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder mCPServerConfiguration_CommitBuilder(
		mcpclient.proxies.MCPServerConfiguration _mCPServerConfiguration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MCPClient.MCPServerConfiguration_Commit");
		builder = builder.withParam("MCPServerConfiguration", _mCPServerConfiguration);
		return builder;
	}

	public static void mCPServerConfiguration_Commit(
		IContext context,
		mcpclient.proxies.MCPServerConfiguration _mCPServerConfiguration
	)
	{
		mCPServerConfiguration_CommitBuilder(
				_mCPServerConfiguration
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder mCPServerConfiguration_CommitListBuilder(
		java.util.List<mcpclient.proxies.MCPServerConfiguration> _mCPServerConfigurationList
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MCPClient.MCPServerConfiguration_CommitList");
		builder = builder.withParam("MCPServerConfigurationList", _mCPServerConfigurationList);
		return builder;
	}

	public static void mCPServerConfiguration_CommitList(
		IContext context,
		java.util.List<mcpclient.proxies.MCPServerConfiguration> _mCPServerConfigurationList
	)
	{
		mCPServerConfiguration_CommitListBuilder(
				_mCPServerConfigurationList
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder mCPServerConfiguration_CreateBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MCPClient.MCPServerConfiguration_Create");
		return builder;
	}

	public static mcpclient.proxies.MCPServerConfiguration mCPServerConfiguration_Create(IContext context)
	{
		Object result = mCPServerConfiguration_CreateBuilder().execute(context);
		return result == null ? null : mcpclient.proxies.MCPServerConfiguration.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder mCPServerConfiguration_DeleteBuilder(
		mcpclient.proxies.MCPServerConfiguration _mCPServerConfiguration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MCPClient.MCPServerConfiguration_Delete");
		builder = builder.withParam("MCPServerConfiguration", _mCPServerConfiguration);
		return builder;
	}

	public static void mCPServerConfiguration_Delete(
		IContext context,
		mcpclient.proxies.MCPServerConfiguration _mCPServerConfiguration
	)
	{
		mCPServerConfiguration_DeleteBuilder(
				_mCPServerConfiguration
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder mCPServerConfiguration_NotSyncedBuilder(
		mcpclient.proxies.MCPServerConfiguration _mCPServerConfiguration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MCPClient.MCPServerConfiguration_NotSynced");
		builder = builder.withParam("MCPServerConfiguration", _mCPServerConfiguration);
		return builder;
	}

	public static void mCPServerConfiguration_NotSynced(
		IContext context,
		mcpclient.proxies.MCPServerConfiguration _mCPServerConfiguration
	)
	{
		mCPServerConfiguration_NotSyncedBuilder(
				_mCPServerConfiguration
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder mCPServerConfiguration_NotSyncedAllToolsBuilder(
		java.util.List<mcpclient.proxies.MCPTool> _mCPToolList
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MCPClient.MCPServerConfiguration_NotSyncedAllTools");
		builder = builder.withParam("MCPToolList", _mCPToolList);
		return builder;
	}

	public static void mCPServerConfiguration_NotSyncedAllTools(
		IContext context,
		java.util.List<mcpclient.proxies.MCPTool> _mCPToolList
	)
	{
		mCPServerConfiguration_NotSyncedAllToolsBuilder(
				_mCPToolList
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder mCPServerConfiguration_RefreshBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MCPClient.MCPServerConfiguration_Refresh");
		return builder;
	}

	public static void mCPServerConfiguration_Refresh(IContext context)
	{
		mCPServerConfiguration_RefreshBuilder().execute(context);
	}
	/**
	 * Syncs with the MCP Server and updates the tools saved in the database.
	 */
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder mCPServerConfiguration_SyncToolsBuilder(
		mcpclient.proxies.MCPServerConfiguration _mCPServerConfiguration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MCPClient.MCPServerConfiguration_SyncTools");
		builder = builder.withParam("MCPServerConfiguration", _mCPServerConfiguration);
		return builder;
	}

	/**
	 * Syncs with the MCP Server and updates the tools saved in the database.
	 */
	public static void mCPServerConfiguration_SyncTools(
		IContext context,
		mcpclient.proxies.MCPServerConfiguration _mCPServerConfiguration
	)
	{
		mCPServerConfiguration_SyncToolsBuilder(
				_mCPServerConfiguration
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder mCPServerConfiguration_SyncToolsForAllServersBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MCPClient.MCPServerConfiguration_SyncToolsForAllServers");
		return builder;
	}

	public static void mCPServerConfiguration_SyncToolsForAllServers(IContext context)
	{
		mCPServerConfiguration_SyncToolsForAllServersBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder mCPServerConfiguration_ValidateBuilder(
		mcpclient.proxies.MCPServerConfiguration _mCPServerConfiguration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MCPClient.MCPServerConfiguration_Validate");
		builder = builder.withParam("MCPServerConfiguration", _mCPServerConfiguration);
		return builder;
	}

	public static boolean mCPServerConfiguration_Validate(
		IContext context,
		mcpclient.proxies.MCPServerConfiguration _mCPServerConfiguration
	)
	{
		Object result = mCPServerConfiguration_ValidateBuilder(
				_mCPServerConfiguration
			)
			.execute(context);
		return (boolean) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder mCPTool_CreateAllFromListToolsResultBuilder(
		mcpclient.proxies.ListToolsResult _listToolsResult,
		mcpclient.proxies.MCPServerConfiguration _mCPServerConfiguration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MCPClient.MCPTool_CreateAllFromListToolsResult");
		builder = builder.withParam("ListToolsResult", _listToolsResult);
		builder = builder.withParam("MCPServerConfiguration", _mCPServerConfiguration);
		return builder;
	}

	public static void mCPTool_CreateAllFromListToolsResult(
		IContext context,
		mcpclient.proxies.ListToolsResult _listToolsResult,
		mcpclient.proxies.MCPServerConfiguration _mCPServerConfiguration
	)
	{
		mCPTool_CreateAllFromListToolsResultBuilder(
				_listToolsResult,
				_mCPServerConfiguration
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder mCPTool_GetCreateBuilder(
		mcpclient.proxies.Tool _tool,
		mcpclient.proxies.MCPServerConfiguration _mCPServerConfiguration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MCPClient.MCPTool_GetCreate");
		builder = builder.withParam("Tool", _tool);
		builder = builder.withParam("MCPServerConfiguration", _mCPServerConfiguration);
		return builder;
	}

	public static mcpclient.proxies.MCPTool mCPTool_GetCreate(
		IContext context,
		mcpclient.proxies.Tool _tool,
		mcpclient.proxies.MCPServerConfiguration _mCPServerConfiguration
	)
	{
		Object result = mCPTool_GetCreateBuilder(
				_tool,
				_mCPServerConfiguration
			)
			.execute(context);
		return result == null ? null : mcpclient.proxies.MCPTool.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder mCPToolList_CommitBuilder(
		java.util.List<mcpclient.proxies.MCPTool> _mCPToolList
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MCPClient.MCPToolList_Commit");
		builder = builder.withParam("MCPToolList", _mCPToolList);
		return builder;
	}

	public static void mCPToolList_Commit(
		IContext context,
		java.util.List<mcpclient.proxies.MCPTool> _mCPToolList
	)
	{
		mCPToolList_CommitBuilder(
				_mCPToolList
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder microflowSelection_GetBuilder(
		mcpclient.proxies.MCPServerConfiguration _mCPServerConfiguration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MCPClient.MicroflowSelection_Get");
		builder = builder.withParam("MCPServerConfiguration", _mCPServerConfiguration);
		return builder;
	}

	public static mcpclient.proxies.MicroflowSelection microflowSelection_Get(
		IContext context,
		mcpclient.proxies.MCPServerConfiguration _mCPServerConfiguration
	)
	{
		Object result = microflowSelection_GetBuilder(
				_mCPServerConfiguration
			)
			.execute(context);
		return result == null ? null : mcpclient.proxies.MicroflowSelection.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder microflowSelection_UpdateBuilder(
		mcpclient.proxies.MCPServerConfiguration _mCPServerConfiguration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MCPClient.MicroflowSelection_Update");
		builder = builder.withParam("MCPServerConfiguration", _mCPServerConfiguration);
		return builder;
	}

	public static mcpclient.proxies.MicroflowSelection microflowSelection_Update(
		IContext context,
		mcpclient.proxies.MCPServerConfiguration _mCPServerConfiguration
	)
	{
		Object result = microflowSelection_UpdateBuilder(
				_mCPServerConfiguration
			)
			.execute(context);
		return result == null ? null : mcpclient.proxies.MicroflowSelection.initialize(context, (IMendixObject) result);
	}
	/**
	 * Gets all tools from an MCP server and adds them to a request so that they become available to an LLM.
	 */
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder request_AddAllMCPToolsFromServerBuilder(
		genaicommons.proxies.Request _request,
		mcpclient.proxies.MCPServerConfiguration _mCPServerConfiguration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MCPClient.Request_AddAllMCPToolsFromServer");
		builder = builder.withParam("Request", _request);
		builder = builder.withParam("MCPServerConfiguration", _mCPServerConfiguration);
		return builder;
	}

	/**
	 * Gets all tools from an MCP server and adds them to a request so that they become available to an LLM.
	 */
	public static void request_AddAllMCPToolsFromServer(
		IContext context,
		genaicommons.proxies.Request _request,
		mcpclient.proxies.MCPServerConfiguration _mCPServerConfiguration
	)
	{
		request_AddAllMCPToolsFromServerBuilder(
				_request,
				_mCPServerConfiguration
			)
			.execute(context);
	}
	/**
	 * This action adds one specifc tool from an MCP server to the provided request. The tool will be identified by the MCPToolName attribute, but you can overwrite this name with the OverwritingToolName if you want to send a different name to the model.
	 */
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder request_AddSpecificMCPToolFromServerBuilder(
		genaicommons.proxies.Request _request,
		mcpclient.proxies.MCPServerConfiguration _mCPServerConfiguration,
		java.lang.String _overwritingToolName,
		java.lang.String _overwritingToolDescription,
		java.lang.String _mCPToolName
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MCPClient.Request_AddSpecificMCPToolFromServer");
		builder = builder.withParam("Request", _request);
		builder = builder.withParam("MCPServerConfiguration", _mCPServerConfiguration);
		builder = builder.withParam("OverwritingToolName", _overwritingToolName);
		builder = builder.withParam("OverwritingToolDescription", _overwritingToolDescription);
		builder = builder.withParam("MCPToolName", _mCPToolName);
		return builder;
	}

	/**
	 * This action adds one specifc tool from an MCP server to the provided request. The tool will be identified by the MCPToolName attribute, but you can overwrite this name with the OverwritingToolName if you want to send a different name to the model.
	 */
	public static void request_AddSpecificMCPToolFromServer(
		IContext context,
		genaicommons.proxies.Request _request,
		mcpclient.proxies.MCPServerConfiguration _mCPServerConfiguration,
		java.lang.String _overwritingToolName,
		java.lang.String _overwritingToolDescription,
		java.lang.String _mCPToolName
	)
	{
		request_AddSpecificMCPToolFromServerBuilder(
				_request,
				_mCPServerConfiguration,
				_overwritingToolName,
				_overwritingToolDescription,
				_mCPToolName
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder scE_MCPServerConfiguration_SyncToolsForAllServersBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MCPClient.ScE_MCPServerConfiguration_SyncToolsForAllServers");
		return builder;
	}

	public static void scE_MCPServerConfiguration_SyncToolsForAllServers(IContext context)
	{
		scE_MCPServerConfiguration_SyncToolsForAllServersBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder tool_CreateArgumentInputListBuilder(
		mcpclient.proxies.Tool _tool
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MCPClient.Tool_CreateArgumentInputList");
		builder = builder.withParam("Tool", _tool);
		return builder;
	}

	public static java.util.List<genaicommons.proxies.ArgumentInput> tool_CreateArgumentInputList(
		IContext context,
		mcpclient.proxies.Tool _tool
	)
	{
		Object result = tool_CreateArgumentInputListBuilder(
				_tool
			)
			.execute(context);
		return result == null ? null : com.mendix.utils.ListUtils.map((java.util.List<IMendixObject>) result, obj -> genaicommons.proxies.ArgumentInput.initialize(context, obj));
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder toolCall_GetToolArgumentCollectionBuilder(
		genaicommons.proxies.ToolCall _toolCall
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MCPClient.ToolCall_GetToolArgumentCollection");
		builder = builder.withParam("ToolCall", _toolCall);
		return builder;
	}

	public static mcpclient.proxies.ArgumentCollection toolCall_GetToolArgumentCollection(
		IContext context,
		genaicommons.proxies.ToolCall _toolCall
	)
	{
		Object result = toolCall_GetToolArgumentCollectionBuilder(
				_toolCall
			)
			.execute(context);
		return result == null ? null : mcpclient.proxies.ArgumentCollection.initialize(context, (IMendixObject) result);
	}
}
