// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mxgenaiconnector.proxies.constants;

import com.mendix.core.Core;

public final class Constants
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Constants() {}

	// These are the constants for the MxGenAIConnector module

	public static java.lang.String getDeployedModelArchitecture()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("MxGenAIConnector.DeployedModelArchitecture");
	}

	public static java.lang.Long getMaxChunkBatchSize()
	{
		return (java.lang.Long)Core.getConfiguration().getConstantValue("MxGenAIConnector.MaxChunkBatchSize");
	}
}