// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package agentcommons.proxies;

public class AgentImport implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject agentImportMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AgentCommons.AgentImport";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Title("Title"),
		Description("Description"),
		UUID("UUID"),
		AgentOwner("AgentOwner"),
		UsageType("UsageType"),
		Entity("Entity"),
		DeployedModel_Model("DeployedModel_Model"),
		DeployedModel_Architecture("DeployedModel_Architecture"),
		AgentImport_VersionImport_InUse("AgentCommons.AgentImport_VersionImport_InUse");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public AgentImport(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected AgentImport(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject agentImportMendixObject)
	{
		if (agentImportMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!agentImportMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.agentImportMendixObject = agentImportMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static agentcommons.proxies.AgentImport initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new agentcommons.proxies.AgentImport(context, mendixObject);
	}

	public static agentcommons.proxies.AgentImport load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return agentcommons.proxies.AgentImport.initialize(context, mendixObject);
	}

	/**
	 * @return value of Title
	 */
	public final java.lang.String getTitle()
	{
		return getTitle(getContext());
	}

	/**
	 * @param context
	 * @return value of Title
	 */
	public final java.lang.String getTitle(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Title.toString());
	}

	/**
	 * Set value of Title
	 * @param title
	 */
	public final void setTitle(java.lang.String title)
	{
		setTitle(getContext(), title);
	}

	/**
	 * Set value of Title
	 * @param context
	 * @param title
	 */
	public final void setTitle(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String title)
	{
		getMendixObject().setValue(context, MemberNames.Title.toString(), title);
	}

	/**
	 * @return value of Description
	 */
	public final java.lang.String getDescription()
	{
		return getDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of Description
	 */
	public final java.lang.String getDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Description.toString());
	}

	/**
	 * Set value of Description
	 * @param description
	 */
	public final void setDescription(java.lang.String description)
	{
		setDescription(getContext(), description);
	}

	/**
	 * Set value of Description
	 * @param context
	 * @param description
	 */
	public final void setDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String description)
	{
		getMendixObject().setValue(context, MemberNames.Description.toString(), description);
	}

	/**
	 * @return value of UUID
	 */
	public final java.lang.String getUUID()
	{
		return getUUID(getContext());
	}

	/**
	 * @param context
	 * @return value of UUID
	 */
	public final java.lang.String getUUID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.UUID.toString());
	}

	/**
	 * Set value of UUID
	 * @param uuid
	 */
	public final void setUUID(java.lang.String uuid)
	{
		setUUID(getContext(), uuid);
	}

	/**
	 * Set value of UUID
	 * @param context
	 * @param uuid
	 */
	public final void setUUID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String uuid)
	{
		getMendixObject().setValue(context, MemberNames.UUID.toString(), uuid);
	}

	/**
	 * @return value of AgentOwner
	 */
	public final java.lang.String getAgentOwner()
	{
		return getAgentOwner(getContext());
	}

	/**
	 * @param context
	 * @return value of AgentOwner
	 */
	public final java.lang.String getAgentOwner(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.AgentOwner.toString());
	}

	/**
	 * Set value of AgentOwner
	 * @param agentowner
	 */
	public final void setAgentOwner(java.lang.String agentowner)
	{
		setAgentOwner(getContext(), agentowner);
	}

	/**
	 * Set value of AgentOwner
	 * @param context
	 * @param agentowner
	 */
	public final void setAgentOwner(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String agentowner)
	{
		getMendixObject().setValue(context, MemberNames.AgentOwner.toString(), agentowner);
	}

	/**
	 * Get value of UsageType
	 * @param usagetype
	 */
	public final agentcommons.proxies.ENUM_Agent_UsageType getUsageType()
	{
		return getUsageType(getContext());
	}

	/**
	 * @param context
	 * @return value of UsageType
	 */
	public final agentcommons.proxies.ENUM_Agent_UsageType getUsageType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.UsageType.toString());
		if (obj == null) {
			return null;
		}
		return agentcommons.proxies.ENUM_Agent_UsageType.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of UsageType
	 * @param usagetype
	 */
	public final void setUsageType(agentcommons.proxies.ENUM_Agent_UsageType usagetype)
	{
		setUsageType(getContext(), usagetype);
	}

	/**
	 * Set value of UsageType
	 * @param context
	 * @param usagetype
	 */
	public final void setUsageType(com.mendix.systemwideinterfaces.core.IContext context, agentcommons.proxies.ENUM_Agent_UsageType usagetype)
	{
		if (usagetype != null) {
			getMendixObject().setValue(context, MemberNames.UsageType.toString(), usagetype.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.UsageType.toString(), null);
		}
	}

	/**
	 * @return value of Entity
	 */
	public final java.lang.String getEntity()
	{
		return getEntity(getContext());
	}

	/**
	 * @param context
	 * @return value of Entity
	 */
	public final java.lang.String getEntity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Entity.toString());
	}

	/**
	 * Set value of Entity
	 * @param entity
	 */
	public final void setEntity(java.lang.String entity)
	{
		setEntity(getContext(), entity);
	}

	/**
	 * Set value of Entity
	 * @param context
	 * @param entity
	 */
	public final void setEntity(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String entity)
	{
		getMendixObject().setValue(context, MemberNames.Entity.toString(), entity);
	}

	/**
	 * @return value of DeployedModel_Model
	 */
	public final java.lang.String getDeployedModel_Model()
	{
		return getDeployedModel_Model(getContext());
	}

	/**
	 * @param context
	 * @return value of DeployedModel_Model
	 */
	public final java.lang.String getDeployedModel_Model(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DeployedModel_Model.toString());
	}

	/**
	 * Set value of DeployedModel_Model
	 * @param deployedmodel_model
	 */
	public final void setDeployedModel_Model(java.lang.String deployedmodel_model)
	{
		setDeployedModel_Model(getContext(), deployedmodel_model);
	}

	/**
	 * Set value of DeployedModel_Model
	 * @param context
	 * @param deployedmodel_model
	 */
	public final void setDeployedModel_Model(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String deployedmodel_model)
	{
		getMendixObject().setValue(context, MemberNames.DeployedModel_Model.toString(), deployedmodel_model);
	}

	/**
	 * @return value of DeployedModel_Architecture
	 */
	public final java.lang.String getDeployedModel_Architecture()
	{
		return getDeployedModel_Architecture(getContext());
	}

	/**
	 * @param context
	 * @return value of DeployedModel_Architecture
	 */
	public final java.lang.String getDeployedModel_Architecture(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DeployedModel_Architecture.toString());
	}

	/**
	 * Set value of DeployedModel_Architecture
	 * @param deployedmodel_architecture
	 */
	public final void setDeployedModel_Architecture(java.lang.String deployedmodel_architecture)
	{
		setDeployedModel_Architecture(getContext(), deployedmodel_architecture);
	}

	/**
	 * Set value of DeployedModel_Architecture
	 * @param context
	 * @param deployedmodel_architecture
	 */
	public final void setDeployedModel_Architecture(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String deployedmodel_architecture)
	{
		getMendixObject().setValue(context, MemberNames.DeployedModel_Architecture.toString(), deployedmodel_architecture);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of AgentImport_VersionImport_InUse
	 */
	public final agentcommons.proxies.VersionImport getAgentImport_VersionImport_InUse() throws com.mendix.core.CoreException
	{
		return getAgentImport_VersionImport_InUse(getContext());
	}

	/**
	 * @param context
	 * @return value of AgentImport_VersionImport_InUse
	 * @throws com.mendix.core.CoreException
	 */
	public final agentcommons.proxies.VersionImport getAgentImport_VersionImport_InUse(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		agentcommons.proxies.VersionImport result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.AgentImport_VersionImport_InUse.toString());
		if (identifier != null) {
			result = agentcommons.proxies.VersionImport.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of AgentImport_VersionImport_InUse
	 * @param agentimport_versionimport_inuse
	 */
	public final void setAgentImport_VersionImport_InUse(agentcommons.proxies.VersionImport agentimport_versionimport_inuse)
	{
		setAgentImport_VersionImport_InUse(getContext(), agentimport_versionimport_inuse);
	}

	/**
	 * Set value of AgentImport_VersionImport_InUse
	 * @param context
	 * @param agentimport_versionimport_inuse
	 */
	public final void setAgentImport_VersionImport_InUse(com.mendix.systemwideinterfaces.core.IContext context, agentcommons.proxies.VersionImport agentimport_versionimport_inuse)
	{
		if (agentimport_versionimport_inuse == null) {
			getMendixObject().setValue(context, MemberNames.AgentImport_VersionImport_InUse.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.AgentImport_VersionImport_InUse.toString(), agentimport_versionimport_inuse.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return agentImportMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final agentcommons.proxies.AgentImport that = (agentcommons.proxies.AgentImport) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
