// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package agentcommons.proxies;

/**
 * An Agent can be created by Agent Admins in the UI. They can be used in microflow logic for GenAI interactions. Retrieve an existing agent and to use "Get Prompt For Context Object" action to exctract the "In Use" version and replace variable placeholders with the attribute values of an (optional) Context Object. Any linked functions (tools) and knowledge bases will be executed when the Request is passed to the GenAI Commons operations for LLM interactions, or this module's Call Agent activity.
 */
public class Agent implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject agentMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AgentCommons.Agent";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Title("Title"),
		Description("Description"),
		UUID("UUID"),
		AgentOwner("AgentOwner"),
		UsageType("UsageType"),
		Entity("Entity"),
		Agent_Version_InUse("AgentCommons.Agent_Version_InUse");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Agent(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Agent(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject agentMendixObject)
	{
		if (agentMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!agentMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.agentMendixObject = agentMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static agentcommons.proxies.Agent initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new agentcommons.proxies.Agent(context, mendixObject);
	}

	public static agentcommons.proxies.Agent load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return agentcommons.proxies.Agent.initialize(context, mendixObject);
	}

	public static java.util.List<agentcommons.proxies.Agent> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> agentcommons.proxies.Agent.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of Title
	 */
	public final java.lang.String getTitle()
	{
		return getTitle(getContext());
	}

	/**
	 * @param context
	 * @return value of Title
	 */
	public final java.lang.String getTitle(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Title.toString());
	}

	/**
	 * Set value of Title
	 * @param title
	 */
	public final void setTitle(java.lang.String title)
	{
		setTitle(getContext(), title);
	}

	/**
	 * Set value of Title
	 * @param context
	 * @param title
	 */
	public final void setTitle(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String title)
	{
		getMendixObject().setValue(context, MemberNames.Title.toString(), title);
	}

	/**
	 * @return value of Description
	 */
	public final java.lang.String getDescription()
	{
		return getDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of Description
	 */
	public final java.lang.String getDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Description.toString());
	}

	/**
	 * Set value of Description
	 * @param description
	 */
	public final void setDescription(java.lang.String description)
	{
		setDescription(getContext(), description);
	}

	/**
	 * Set value of Description
	 * @param context
	 * @param description
	 */
	public final void setDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String description)
	{
		getMendixObject().setValue(context, MemberNames.Description.toString(), description);
	}

	/**
	 * @return value of UUID
	 */
	public final java.lang.String getUUID()
	{
		return getUUID(getContext());
	}

	/**
	 * @param context
	 * @return value of UUID
	 */
	public final java.lang.String getUUID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.UUID.toString());
	}

	/**
	 * Set value of UUID
	 * @param uuid
	 */
	public final void setUUID(java.lang.String uuid)
	{
		setUUID(getContext(), uuid);
	}

	/**
	 * Set value of UUID
	 * @param context
	 * @param uuid
	 */
	public final void setUUID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String uuid)
	{
		getMendixObject().setValue(context, MemberNames.UUID.toString(), uuid);
	}

	/**
	 * @return value of AgentOwner
	 */
	public final java.lang.String getAgentOwner()
	{
		return getAgentOwner(getContext());
	}

	/**
	 * @param context
	 * @return value of AgentOwner
	 */
	public final java.lang.String getAgentOwner(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.AgentOwner.toString());
	}

	/**
	 * Set value of AgentOwner
	 * @param agentowner
	 */
	public final void setAgentOwner(java.lang.String agentowner)
	{
		setAgentOwner(getContext(), agentowner);
	}

	/**
	 * Set value of AgentOwner
	 * @param context
	 * @param agentowner
	 */
	public final void setAgentOwner(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String agentowner)
	{
		getMendixObject().setValue(context, MemberNames.AgentOwner.toString(), agentowner);
	}

	/**
	 * Get value of UsageType
	 * @param usagetype
	 */
	public final agentcommons.proxies.ENUM_Agent_UsageType getUsageType()
	{
		return getUsageType(getContext());
	}

	/**
	 * @param context
	 * @return value of UsageType
	 */
	public final agentcommons.proxies.ENUM_Agent_UsageType getUsageType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.UsageType.toString());
		if (obj == null) {
			return null;
		}
		return agentcommons.proxies.ENUM_Agent_UsageType.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of UsageType
	 * @param usagetype
	 */
	public final void setUsageType(agentcommons.proxies.ENUM_Agent_UsageType usagetype)
	{
		setUsageType(getContext(), usagetype);
	}

	/**
	 * Set value of UsageType
	 * @param context
	 * @param usagetype
	 */
	public final void setUsageType(com.mendix.systemwideinterfaces.core.IContext context, agentcommons.proxies.ENUM_Agent_UsageType usagetype)
	{
		if (usagetype != null) {
			getMendixObject().setValue(context, MemberNames.UsageType.toString(), usagetype.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.UsageType.toString(), null);
		}
	}

	/**
	 * @return value of Entity
	 */
	public final java.lang.String getEntity()
	{
		return getEntity(getContext());
	}

	/**
	 * @param context
	 * @return value of Entity
	 */
	public final java.lang.String getEntity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Entity.toString());
	}

	/**
	 * Set value of Entity
	 * @param entity
	 */
	public final void setEntity(java.lang.String entity)
	{
		setEntity(getContext(), entity);
	}

	/**
	 * Set value of Entity
	 * @param context
	 * @param entity
	 */
	public final void setEntity(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String entity)
	{
		getMendixObject().setValue(context, MemberNames.Entity.toString(), entity);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Agent_Version_InUse
	 */
	public final agentcommons.proxies.Version getAgent_Version_InUse() throws com.mendix.core.CoreException
	{
		return getAgent_Version_InUse(getContext());
	}

	/**
	 * @param context
	 * @return value of Agent_Version_InUse
	 * @throws com.mendix.core.CoreException
	 */
	public final agentcommons.proxies.Version getAgent_Version_InUse(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		agentcommons.proxies.Version result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Agent_Version_InUse.toString());
		if (identifier != null) {
			result = agentcommons.proxies.Version.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Agent_Version_InUse
	 * @param agent_version_inuse
	 */
	public final void setAgent_Version_InUse(agentcommons.proxies.Version agent_version_inuse)
	{
		setAgent_Version_InUse(getContext(), agent_version_inuse);
	}

	/**
	 * Set value of Agent_Version_InUse
	 * @param context
	 * @param agent_version_inuse
	 */
	public final void setAgent_Version_InUse(com.mendix.systemwideinterfaces.core.IContext context, agentcommons.proxies.Version agent_version_inuse)
	{
		if (agent_version_inuse == null) {
			getMendixObject().setValue(context, MemberNames.Agent_Version_InUse.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Agent_Version_InUse.toString(), agent_version_inuse.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return agentMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final agentcommons.proxies.Agent that = (agentcommons.proxies.Agent) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
