// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package agentcommons.proxies;

/**
 * Attributes of the selected Entity that are used to show in info boxes.
 */
public class EntityAttribute implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject entityAttributeMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AgentCommons.EntityAttribute";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		AttributeName("AttributeName"),
		AttributeType("AttributeType"),
		IsAvailableInPrompt("IsAvailableInPrompt"),
		EntityAttribute_PageHelper("AgentCommons.EntityAttribute_PageHelper");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public EntityAttribute(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected EntityAttribute(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject entityAttributeMendixObject)
	{
		if (entityAttributeMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!entityAttributeMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.entityAttributeMendixObject = entityAttributeMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static agentcommons.proxies.EntityAttribute initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new agentcommons.proxies.EntityAttribute(context, mendixObject);
	}

	public static agentcommons.proxies.EntityAttribute load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return agentcommons.proxies.EntityAttribute.initialize(context, mendixObject);
	}

	/**
	 * @return value of AttributeName
	 */
	public final java.lang.String getAttributeName()
	{
		return getAttributeName(getContext());
	}

	/**
	 * @param context
	 * @return value of AttributeName
	 */
	public final java.lang.String getAttributeName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.AttributeName.toString());
	}

	/**
	 * Set value of AttributeName
	 * @param attributename
	 */
	public final void setAttributeName(java.lang.String attributename)
	{
		setAttributeName(getContext(), attributename);
	}

	/**
	 * Set value of AttributeName
	 * @param context
	 * @param attributename
	 */
	public final void setAttributeName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String attributename)
	{
		getMendixObject().setValue(context, MemberNames.AttributeName.toString(), attributename);
	}

	/**
	 * @return value of AttributeType
	 */
	public final java.lang.String getAttributeType()
	{
		return getAttributeType(getContext());
	}

	/**
	 * @param context
	 * @return value of AttributeType
	 */
	public final java.lang.String getAttributeType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.AttributeType.toString());
	}

	/**
	 * Set value of AttributeType
	 * @param attributetype
	 */
	public final void setAttributeType(java.lang.String attributetype)
	{
		setAttributeType(getContext(), attributetype);
	}

	/**
	 * Set value of AttributeType
	 * @param context
	 * @param attributetype
	 */
	public final void setAttributeType(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String attributetype)
	{
		getMendixObject().setValue(context, MemberNames.AttributeType.toString(), attributetype);
	}

	/**
	 * @return value of IsAvailableInPrompt
	 */
	public final java.lang.Boolean getIsAvailableInPrompt()
	{
		return getIsAvailableInPrompt(getContext());
	}

	/**
	 * @param context
	 * @return value of IsAvailableInPrompt
	 */
	public final java.lang.Boolean getIsAvailableInPrompt(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsAvailableInPrompt.toString());
	}

	/**
	 * Set value of IsAvailableInPrompt
	 * @param isavailableinprompt
	 */
	public final void setIsAvailableInPrompt(java.lang.Boolean isavailableinprompt)
	{
		setIsAvailableInPrompt(getContext(), isavailableinprompt);
	}

	/**
	 * Set value of IsAvailableInPrompt
	 * @param context
	 * @param isavailableinprompt
	 */
	public final void setIsAvailableInPrompt(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isavailableinprompt)
	{
		getMendixObject().setValue(context, MemberNames.IsAvailableInPrompt.toString(), isavailableinprompt);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of EntityAttribute_PageHelper
	 */
	public final agentcommons.proxies.PageHelper getEntityAttribute_PageHelper() throws com.mendix.core.CoreException
	{
		return getEntityAttribute_PageHelper(getContext());
	}

	/**
	 * @param context
	 * @return value of EntityAttribute_PageHelper
	 * @throws com.mendix.core.CoreException
	 */
	public final agentcommons.proxies.PageHelper getEntityAttribute_PageHelper(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		agentcommons.proxies.PageHelper result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.EntityAttribute_PageHelper.toString());
		if (identifier != null) {
			result = agentcommons.proxies.PageHelper.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of EntityAttribute_PageHelper
	 * @param entityattribute_pagehelper
	 */
	public final void setEntityAttribute_PageHelper(agentcommons.proxies.PageHelper entityattribute_pagehelper)
	{
		setEntityAttribute_PageHelper(getContext(), entityattribute_pagehelper);
	}

	/**
	 * Set value of EntityAttribute_PageHelper
	 * @param context
	 * @param entityattribute_pagehelper
	 */
	public final void setEntityAttribute_PageHelper(com.mendix.systemwideinterfaces.core.IContext context, agentcommons.proxies.PageHelper entityattribute_pagehelper)
	{
		if (entityattribute_pagehelper == null) {
			getMendixObject().setValue(context, MemberNames.EntityAttribute_PageHelper.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.EntityAttribute_PageHelper.toString(), entityattribute_pagehelper.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return entityAttributeMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final agentcommons.proxies.EntityAttribute that = (agentcommons.proxies.EntityAttribute) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
