// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package agentcommons.proxies;

public enum ENUM_Agent_UsageType
{
	Single_Call("906c08cc-cef0-4418-8fa3-a41507c57ab3"),
	Conversational("2dd05ef6-dcda-4b0c-b8e4-041ae627c989");

	private final java.lang.String i18nCaptionKey;
	
	private ENUM_Agent_UsageType(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
