// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package agentcommons.proxies;

public enum ENUM_PageHelper_EntitySelectionStatus
{
	Entity_Not_Found("5fe49d8f-3e46-4972-a1e2-6d40d5d2d9df"),
	Entity_Not_Set("43652a30-6663-48cd-a031-8d1524bcebb9"),
	Variables_Not_Available("ac127377-6b6a-4206-ae6c-1eb7433b581a"),
	Entity_Matches_Variables("4360288f-ef20-4a87-8474-f498526ae354");

	private final java.lang.String i18nCaptionKey;
	
	private ENUM_PageHelper_EntitySelectionStatus(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
