// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package agentcommons.proxies;

public class KnowledgeBaseImport implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject knowledgeBaseImportMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AgentCommons.KnowledgeBaseImport";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		Description("Description"),
		MaxNumberOfResults("MaxNumberOfResults"),
		MinimumSimilarity("MinimumSimilarity"),
		DeployedKnowledgeBase_Architecture("DeployedKnowledgeBase_Architecture"),
		DeployedKnowledgeBase_DisplayName("DeployedKnowledgeBase_DisplayName"),
		UUID("UUID"),
		KnowledgeBaseImport_VersionImport("AgentCommons.KnowledgeBaseImport_VersionImport");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public KnowledgeBaseImport(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected KnowledgeBaseImport(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject knowledgeBaseImportMendixObject)
	{
		if (knowledgeBaseImportMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!knowledgeBaseImportMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.knowledgeBaseImportMendixObject = knowledgeBaseImportMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static agentcommons.proxies.KnowledgeBaseImport initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new agentcommons.proxies.KnowledgeBaseImport(context, mendixObject);
	}

	public static agentcommons.proxies.KnowledgeBaseImport load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return agentcommons.proxies.KnowledgeBaseImport.initialize(context, mendixObject);
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of Description
	 */
	public final java.lang.String getDescription()
	{
		return getDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of Description
	 */
	public final java.lang.String getDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Description.toString());
	}

	/**
	 * Set value of Description
	 * @param description
	 */
	public final void setDescription(java.lang.String description)
	{
		setDescription(getContext(), description);
	}

	/**
	 * Set value of Description
	 * @param context
	 * @param description
	 */
	public final void setDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String description)
	{
		getMendixObject().setValue(context, MemberNames.Description.toString(), description);
	}

	/**
	 * @return value of MaxNumberOfResults
	 */
	public final java.lang.Integer getMaxNumberOfResults()
	{
		return getMaxNumberOfResults(getContext());
	}

	/**
	 * @param context
	 * @return value of MaxNumberOfResults
	 */
	public final java.lang.Integer getMaxNumberOfResults(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.MaxNumberOfResults.toString());
	}

	/**
	 * Set value of MaxNumberOfResults
	 * @param maxnumberofresults
	 */
	public final void setMaxNumberOfResults(java.lang.Integer maxnumberofresults)
	{
		setMaxNumberOfResults(getContext(), maxnumberofresults);
	}

	/**
	 * Set value of MaxNumberOfResults
	 * @param context
	 * @param maxnumberofresults
	 */
	public final void setMaxNumberOfResults(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer maxnumberofresults)
	{
		getMendixObject().setValue(context, MemberNames.MaxNumberOfResults.toString(), maxnumberofresults);
	}

	/**
	 * @return value of MinimumSimilarity
	 */
	public final java.math.BigDecimal getMinimumSimilarity()
	{
		return getMinimumSimilarity(getContext());
	}

	/**
	 * @param context
	 * @return value of MinimumSimilarity
	 */
	public final java.math.BigDecimal getMinimumSimilarity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.MinimumSimilarity.toString());
	}

	/**
	 * Set value of MinimumSimilarity
	 * @param minimumsimilarity
	 */
	public final void setMinimumSimilarity(java.math.BigDecimal minimumsimilarity)
	{
		setMinimumSimilarity(getContext(), minimumsimilarity);
	}

	/**
	 * Set value of MinimumSimilarity
	 * @param context
	 * @param minimumsimilarity
	 */
	public final void setMinimumSimilarity(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal minimumsimilarity)
	{
		getMendixObject().setValue(context, MemberNames.MinimumSimilarity.toString(), minimumsimilarity);
	}

	/**
	 * @return value of DeployedKnowledgeBase_Architecture
	 */
	public final java.lang.String getDeployedKnowledgeBase_Architecture()
	{
		return getDeployedKnowledgeBase_Architecture(getContext());
	}

	/**
	 * @param context
	 * @return value of DeployedKnowledgeBase_Architecture
	 */
	public final java.lang.String getDeployedKnowledgeBase_Architecture(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DeployedKnowledgeBase_Architecture.toString());
	}

	/**
	 * Set value of DeployedKnowledgeBase_Architecture
	 * @param deployedknowledgebase_architecture
	 */
	public final void setDeployedKnowledgeBase_Architecture(java.lang.String deployedknowledgebase_architecture)
	{
		setDeployedKnowledgeBase_Architecture(getContext(), deployedknowledgebase_architecture);
	}

	/**
	 * Set value of DeployedKnowledgeBase_Architecture
	 * @param context
	 * @param deployedknowledgebase_architecture
	 */
	public final void setDeployedKnowledgeBase_Architecture(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String deployedknowledgebase_architecture)
	{
		getMendixObject().setValue(context, MemberNames.DeployedKnowledgeBase_Architecture.toString(), deployedknowledgebase_architecture);
	}

	/**
	 * @return value of DeployedKnowledgeBase_DisplayName
	 */
	public final java.lang.String getDeployedKnowledgeBase_DisplayName()
	{
		return getDeployedKnowledgeBase_DisplayName(getContext());
	}

	/**
	 * @param context
	 * @return value of DeployedKnowledgeBase_DisplayName
	 */
	public final java.lang.String getDeployedKnowledgeBase_DisplayName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DeployedKnowledgeBase_DisplayName.toString());
	}

	/**
	 * Set value of DeployedKnowledgeBase_DisplayName
	 * @param deployedknowledgebase_displayname
	 */
	public final void setDeployedKnowledgeBase_DisplayName(java.lang.String deployedknowledgebase_displayname)
	{
		setDeployedKnowledgeBase_DisplayName(getContext(), deployedknowledgebase_displayname);
	}

	/**
	 * Set value of DeployedKnowledgeBase_DisplayName
	 * @param context
	 * @param deployedknowledgebase_displayname
	 */
	public final void setDeployedKnowledgeBase_DisplayName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String deployedknowledgebase_displayname)
	{
		getMendixObject().setValue(context, MemberNames.DeployedKnowledgeBase_DisplayName.toString(), deployedknowledgebase_displayname);
	}

	/**
	 * @return value of UUID
	 */
	public final java.lang.String getUUID()
	{
		return getUUID(getContext());
	}

	/**
	 * @param context
	 * @return value of UUID
	 */
	public final java.lang.String getUUID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.UUID.toString());
	}

	/**
	 * Set value of UUID
	 * @param uuid
	 */
	public final void setUUID(java.lang.String uuid)
	{
		setUUID(getContext(), uuid);
	}

	/**
	 * Set value of UUID
	 * @param context
	 * @param uuid
	 */
	public final void setUUID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String uuid)
	{
		getMendixObject().setValue(context, MemberNames.UUID.toString(), uuid);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of KnowledgeBaseImport_VersionImport
	 */
	public final agentcommons.proxies.VersionImport getKnowledgeBaseImport_VersionImport() throws com.mendix.core.CoreException
	{
		return getKnowledgeBaseImport_VersionImport(getContext());
	}

	/**
	 * @param context
	 * @return value of KnowledgeBaseImport_VersionImport
	 * @throws com.mendix.core.CoreException
	 */
	public final agentcommons.proxies.VersionImport getKnowledgeBaseImport_VersionImport(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		agentcommons.proxies.VersionImport result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.KnowledgeBaseImport_VersionImport.toString());
		if (identifier != null) {
			result = agentcommons.proxies.VersionImport.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of KnowledgeBaseImport_VersionImport
	 * @param knowledgebaseimport_versionimport
	 */
	public final void setKnowledgeBaseImport_VersionImport(agentcommons.proxies.VersionImport knowledgebaseimport_versionimport)
	{
		setKnowledgeBaseImport_VersionImport(getContext(), knowledgebaseimport_versionimport);
	}

	/**
	 * Set value of KnowledgeBaseImport_VersionImport
	 * @param context
	 * @param knowledgebaseimport_versionimport
	 */
	public final void setKnowledgeBaseImport_VersionImport(com.mendix.systemwideinterfaces.core.IContext context, agentcommons.proxies.VersionImport knowledgebaseimport_versionimport)
	{
		if (knowledgebaseimport_versionimport == null) {
			getMendixObject().setValue(context, MemberNames.KnowledgeBaseImport_VersionImport.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.KnowledgeBaseImport_VersionImport.toString(), knowledgebaseimport_versionimport.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return knowledgeBaseImportMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final agentcommons.proxies.KnowledgeBaseImport that = (agentcommons.proxies.KnowledgeBaseImport) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
