// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package agentcommons.proxies;

/**
 * This is a knowledge base the Agent can retrieve information from in order to perform its tasks. Currently only MxCloud GenAI Knowledge bases are supported.
 */
public class KnowledgeBase implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject knowledgeBaseMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AgentCommons.KnowledgeBase";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		Description("Description"),
		MaxNumberOfResults("MaxNumberOfResults"),
		MinimumSimilarity("MinimumSimilarity"),
		IsEnabled("IsEnabled"),
		UUID("UUID"),
		KnowledgeBase_Version("AgentCommons.KnowledgeBase_Version"),
		KnowledgeBase_DeployedKnowledgeBase("AgentCommons.KnowledgeBase_DeployedKnowledgeBase");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public KnowledgeBase(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected KnowledgeBase(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject knowledgeBaseMendixObject)
	{
		if (knowledgeBaseMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!knowledgeBaseMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.knowledgeBaseMendixObject = knowledgeBaseMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static agentcommons.proxies.KnowledgeBase initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new agentcommons.proxies.KnowledgeBase(context, mendixObject);
	}

	public static agentcommons.proxies.KnowledgeBase load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return agentcommons.proxies.KnowledgeBase.initialize(context, mendixObject);
	}

	public static java.util.List<agentcommons.proxies.KnowledgeBase> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> agentcommons.proxies.KnowledgeBase.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of Description
	 */
	public final java.lang.String getDescription()
	{
		return getDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of Description
	 */
	public final java.lang.String getDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Description.toString());
	}

	/**
	 * Set value of Description
	 * @param description
	 */
	public final void setDescription(java.lang.String description)
	{
		setDescription(getContext(), description);
	}

	/**
	 * Set value of Description
	 * @param context
	 * @param description
	 */
	public final void setDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String description)
	{
		getMendixObject().setValue(context, MemberNames.Description.toString(), description);
	}

	/**
	 * @return value of MaxNumberOfResults
	 */
	public final java.lang.Integer getMaxNumberOfResults()
	{
		return getMaxNumberOfResults(getContext());
	}

	/**
	 * @param context
	 * @return value of MaxNumberOfResults
	 */
	public final java.lang.Integer getMaxNumberOfResults(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.MaxNumberOfResults.toString());
	}

	/**
	 * Set value of MaxNumberOfResults
	 * @param maxnumberofresults
	 */
	public final void setMaxNumberOfResults(java.lang.Integer maxnumberofresults)
	{
		setMaxNumberOfResults(getContext(), maxnumberofresults);
	}

	/**
	 * Set value of MaxNumberOfResults
	 * @param context
	 * @param maxnumberofresults
	 */
	public final void setMaxNumberOfResults(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer maxnumberofresults)
	{
		getMendixObject().setValue(context, MemberNames.MaxNumberOfResults.toString(), maxnumberofresults);
	}

	/**
	 * @return value of MinimumSimilarity
	 */
	public final java.math.BigDecimal getMinimumSimilarity()
	{
		return getMinimumSimilarity(getContext());
	}

	/**
	 * @param context
	 * @return value of MinimumSimilarity
	 */
	public final java.math.BigDecimal getMinimumSimilarity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.MinimumSimilarity.toString());
	}

	/**
	 * Set value of MinimumSimilarity
	 * @param minimumsimilarity
	 */
	public final void setMinimumSimilarity(java.math.BigDecimal minimumsimilarity)
	{
		setMinimumSimilarity(getContext(), minimumsimilarity);
	}

	/**
	 * Set value of MinimumSimilarity
	 * @param context
	 * @param minimumsimilarity
	 */
	public final void setMinimumSimilarity(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal minimumsimilarity)
	{
		getMendixObject().setValue(context, MemberNames.MinimumSimilarity.toString(), minimumsimilarity);
	}

	/**
	 * @return value of IsEnabled
	 */
	public final java.lang.Boolean getIsEnabled()
	{
		return getIsEnabled(getContext());
	}

	/**
	 * @param context
	 * @return value of IsEnabled
	 */
	public final java.lang.Boolean getIsEnabled(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsEnabled.toString());
	}

	/**
	 * Set value of IsEnabled
	 * @param isenabled
	 */
	public final void setIsEnabled(java.lang.Boolean isenabled)
	{
		setIsEnabled(getContext(), isenabled);
	}

	/**
	 * Set value of IsEnabled
	 * @param context
	 * @param isenabled
	 */
	public final void setIsEnabled(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isenabled)
	{
		getMendixObject().setValue(context, MemberNames.IsEnabled.toString(), isenabled);
	}

	/**
	 * @return value of UUID
	 */
	public final java.lang.String getUUID()
	{
		return getUUID(getContext());
	}

	/**
	 * @param context
	 * @return value of UUID
	 */
	public final java.lang.String getUUID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.UUID.toString());
	}

	/**
	 * Set value of UUID
	 * @param uuid
	 */
	public final void setUUID(java.lang.String uuid)
	{
		setUUID(getContext(), uuid);
	}

	/**
	 * Set value of UUID
	 * @param context
	 * @param uuid
	 */
	public final void setUUID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String uuid)
	{
		getMendixObject().setValue(context, MemberNames.UUID.toString(), uuid);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of KnowledgeBase_Version
	 */
	public final agentcommons.proxies.Version getKnowledgeBase_Version() throws com.mendix.core.CoreException
	{
		return getKnowledgeBase_Version(getContext());
	}

	/**
	 * @param context
	 * @return value of KnowledgeBase_Version
	 * @throws com.mendix.core.CoreException
	 */
	public final agentcommons.proxies.Version getKnowledgeBase_Version(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		agentcommons.proxies.Version result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.KnowledgeBase_Version.toString());
		if (identifier != null) {
			result = agentcommons.proxies.Version.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of KnowledgeBase_Version
	 * @param knowledgebase_version
	 */
	public final void setKnowledgeBase_Version(agentcommons.proxies.Version knowledgebase_version)
	{
		setKnowledgeBase_Version(getContext(), knowledgebase_version);
	}

	/**
	 * Set value of KnowledgeBase_Version
	 * @param context
	 * @param knowledgebase_version
	 */
	public final void setKnowledgeBase_Version(com.mendix.systemwideinterfaces.core.IContext context, agentcommons.proxies.Version knowledgebase_version)
	{
		if (knowledgebase_version == null) {
			getMendixObject().setValue(context, MemberNames.KnowledgeBase_Version.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.KnowledgeBase_Version.toString(), knowledgebase_version.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of KnowledgeBase_DeployedKnowledgeBase
	 */
	public final genaicommons.proxies.DeployedKnowledgeBase getKnowledgeBase_DeployedKnowledgeBase() throws com.mendix.core.CoreException
	{
		return getKnowledgeBase_DeployedKnowledgeBase(getContext());
	}

	/**
	 * @param context
	 * @return value of KnowledgeBase_DeployedKnowledgeBase
	 * @throws com.mendix.core.CoreException
	 */
	public final genaicommons.proxies.DeployedKnowledgeBase getKnowledgeBase_DeployedKnowledgeBase(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		genaicommons.proxies.DeployedKnowledgeBase result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.KnowledgeBase_DeployedKnowledgeBase.toString());
		if (identifier != null) {
			result = genaicommons.proxies.DeployedKnowledgeBase.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of KnowledgeBase_DeployedKnowledgeBase
	 * @param knowledgebase_deployedknowledgebase
	 */
	public final void setKnowledgeBase_DeployedKnowledgeBase(genaicommons.proxies.DeployedKnowledgeBase knowledgebase_deployedknowledgebase)
	{
		setKnowledgeBase_DeployedKnowledgeBase(getContext(), knowledgebase_deployedknowledgebase);
	}

	/**
	 * Set value of KnowledgeBase_DeployedKnowledgeBase
	 * @param context
	 * @param knowledgebase_deployedknowledgebase
	 */
	public final void setKnowledgeBase_DeployedKnowledgeBase(com.mendix.systemwideinterfaces.core.IContext context, genaicommons.proxies.DeployedKnowledgeBase knowledgebase_deployedknowledgebase)
	{
		if (knowledgebase_deployedknowledgebase == null) {
			getMendixObject().setValue(context, MemberNames.KnowledgeBase_DeployedKnowledgeBase.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.KnowledgeBase_DeployedKnowledgeBase.toString(), knowledgebase_deployedknowledgebase.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return knowledgeBaseMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final agentcommons.proxies.KnowledgeBase that = (agentcommons.proxies.KnowledgeBase) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
