// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package agentcommons.proxies;

/**
 * Helper entity to facilitate the selection of the tool microflow.
 */
public class MicroflowSelection implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject microflowSelectionMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AgentCommons.MicroflowSelection";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ToolMicroflowFound("ToolMicroflowFound"),
		MicroflowSelection_Tool("AgentCommons.MicroflowSelection_Tool"),
		MicroflowSelection_Microflow_Active("AgentCommons.MicroflowSelection_Microflow_Active"),
		MicroflowSelection_Microflow("AgentCommons.MicroflowSelection_Microflow"),
		MicroflowSelection_Module("AgentCommons.MicroflowSelection_Module"),
		MicroflowSelection_Module_Active("AgentCommons.MicroflowSelection_Module_Active");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public MicroflowSelection(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected MicroflowSelection(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject microflowSelectionMendixObject)
	{
		if (microflowSelectionMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!microflowSelectionMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.microflowSelectionMendixObject = microflowSelectionMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static agentcommons.proxies.MicroflowSelection initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new agentcommons.proxies.MicroflowSelection(context, mendixObject);
	}

	public static agentcommons.proxies.MicroflowSelection load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return agentcommons.proxies.MicroflowSelection.initialize(context, mendixObject);
	}

	/**
	 * @return value of ToolMicroflowFound
	 */
	public final java.lang.Boolean getToolMicroflowFound()
	{
		return getToolMicroflowFound(getContext());
	}

	/**
	 * @param context
	 * @return value of ToolMicroflowFound
	 */
	public final java.lang.Boolean getToolMicroflowFound(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ToolMicroflowFound.toString());
	}

	/**
	 * Set value of ToolMicroflowFound
	 * @param toolmicroflowfound
	 */
	public final void setToolMicroflowFound(java.lang.Boolean toolmicroflowfound)
	{
		setToolMicroflowFound(getContext(), toolmicroflowfound);
	}

	/**
	 * Set value of ToolMicroflowFound
	 * @param context
	 * @param toolmicroflowfound
	 */
	public final void setToolMicroflowFound(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean toolmicroflowfound)
	{
		getMendixObject().setValue(context, MemberNames.ToolMicroflowFound.toString(), toolmicroflowfound);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of MicroflowSelection_Tool
	 */
	public final agentcommons.proxies.Tool getMicroflowSelection_Tool() throws com.mendix.core.CoreException
	{
		return getMicroflowSelection_Tool(getContext());
	}

	/**
	 * @param context
	 * @return value of MicroflowSelection_Tool
	 * @throws com.mendix.core.CoreException
	 */
	public final agentcommons.proxies.Tool getMicroflowSelection_Tool(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		agentcommons.proxies.Tool result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.MicroflowSelection_Tool.toString());
		if (identifier != null) {
			result = agentcommons.proxies.Tool.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of MicroflowSelection_Tool
	 * @param microflowselection_tool
	 */
	public final void setMicroflowSelection_Tool(agentcommons.proxies.Tool microflowselection_tool)
	{
		setMicroflowSelection_Tool(getContext(), microflowselection_tool);
	}

	/**
	 * Set value of MicroflowSelection_Tool
	 * @param context
	 * @param microflowselection_tool
	 */
	public final void setMicroflowSelection_Tool(com.mendix.systemwideinterfaces.core.IContext context, agentcommons.proxies.Tool microflowselection_tool)
	{
		if (microflowselection_tool == null) {
			getMendixObject().setValue(context, MemberNames.MicroflowSelection_Tool.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.MicroflowSelection_Tool.toString(), microflowselection_tool.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of MicroflowSelection_Microflow_Active
	 */
	public final agentcommons.proxies.Microflow getMicroflowSelection_Microflow_Active() throws com.mendix.core.CoreException
	{
		return getMicroflowSelection_Microflow_Active(getContext());
	}

	/**
	 * @param context
	 * @return value of MicroflowSelection_Microflow_Active
	 * @throws com.mendix.core.CoreException
	 */
	public final agentcommons.proxies.Microflow getMicroflowSelection_Microflow_Active(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		agentcommons.proxies.Microflow result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.MicroflowSelection_Microflow_Active.toString());
		if (identifier != null) {
			result = agentcommons.proxies.Microflow.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of MicroflowSelection_Microflow_Active
	 * @param microflowselection_microflow_active
	 */
	public final void setMicroflowSelection_Microflow_Active(agentcommons.proxies.Microflow microflowselection_microflow_active)
	{
		setMicroflowSelection_Microflow_Active(getContext(), microflowselection_microflow_active);
	}

	/**
	 * Set value of MicroflowSelection_Microflow_Active
	 * @param context
	 * @param microflowselection_microflow_active
	 */
	public final void setMicroflowSelection_Microflow_Active(com.mendix.systemwideinterfaces.core.IContext context, agentcommons.proxies.Microflow microflowselection_microflow_active)
	{
		if (microflowselection_microflow_active == null) {
			getMendixObject().setValue(context, MemberNames.MicroflowSelection_Microflow_Active.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.MicroflowSelection_Microflow_Active.toString(), microflowselection_microflow_active.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of MicroflowSelection_Microflow
	 */
	public final java.util.List<agentcommons.proxies.Microflow> getMicroflowSelection_Microflow() throws com.mendix.core.CoreException
	{
		return getMicroflowSelection_Microflow(getContext());
	}

	/**
	 * @param context
	 * @return value of MicroflowSelection_Microflow
	 * @throws com.mendix.core.CoreException
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<agentcommons.proxies.Microflow> getMicroflowSelection_Microflow(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<agentcommons.proxies.Microflow> result = new java.util.ArrayList<>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.MicroflowSelection_Microflow.toString());
		if (valueObject == null) {
			return result;
		}
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject)) {
			result.add(agentcommons.proxies.Microflow.initialize(context, mendixObject));
		}
		return result;
	}

	/**
	 * Set value of MicroflowSelection_Microflow
	 * @param microflowselection_microflow
	 */
	public final void setMicroflowSelection_Microflow(java.util.List<agentcommons.proxies.Microflow> microflowselection_microflow)
	{
		setMicroflowSelection_Microflow(getContext(), microflowselection_microflow);
	}

	/**
	 * Set value of MicroflowSelection_Microflow
	 * @param context
	 * @param microflowselection_microflow
	 */
	public final void setMicroflowSelection_Microflow(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<agentcommons.proxies.Microflow> microflowselection_microflow)
	{
		var identifiers = microflowselection_microflow
			.stream()
			.map(proxyObject -> proxyObject.getMendixObject().getId())
			.collect(java.util.stream.Collectors.toList());
		
		getMendixObject().setValue(context, MemberNames.MicroflowSelection_Microflow.toString(), identifiers);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of MicroflowSelection_Module
	 */
	public final java.util.List<agentcommons.proxies.Module> getMicroflowSelection_Module() throws com.mendix.core.CoreException
	{
		return getMicroflowSelection_Module(getContext());
	}

	/**
	 * @param context
	 * @return value of MicroflowSelection_Module
	 * @throws com.mendix.core.CoreException
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<agentcommons.proxies.Module> getMicroflowSelection_Module(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<agentcommons.proxies.Module> result = new java.util.ArrayList<>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.MicroflowSelection_Module.toString());
		if (valueObject == null) {
			return result;
		}
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject)) {
			result.add(agentcommons.proxies.Module.initialize(context, mendixObject));
		}
		return result;
	}

	/**
	 * Set value of MicroflowSelection_Module
	 * @param microflowselection_module
	 */
	public final void setMicroflowSelection_Module(java.util.List<agentcommons.proxies.Module> microflowselection_module)
	{
		setMicroflowSelection_Module(getContext(), microflowselection_module);
	}

	/**
	 * Set value of MicroflowSelection_Module
	 * @param context
	 * @param microflowselection_module
	 */
	public final void setMicroflowSelection_Module(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<agentcommons.proxies.Module> microflowselection_module)
	{
		var identifiers = microflowselection_module
			.stream()
			.map(proxyObject -> proxyObject.getMendixObject().getId())
			.collect(java.util.stream.Collectors.toList());
		
		getMendixObject().setValue(context, MemberNames.MicroflowSelection_Module.toString(), identifiers);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of MicroflowSelection_Module_Active
	 */
	public final agentcommons.proxies.Module getMicroflowSelection_Module_Active() throws com.mendix.core.CoreException
	{
		return getMicroflowSelection_Module_Active(getContext());
	}

	/**
	 * @param context
	 * @return value of MicroflowSelection_Module_Active
	 * @throws com.mendix.core.CoreException
	 */
	public final agentcommons.proxies.Module getMicroflowSelection_Module_Active(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		agentcommons.proxies.Module result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.MicroflowSelection_Module_Active.toString());
		if (identifier != null) {
			result = agentcommons.proxies.Module.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of MicroflowSelection_Module_Active
	 * @param microflowselection_module_active
	 */
	public final void setMicroflowSelection_Module_Active(agentcommons.proxies.Module microflowselection_module_active)
	{
		setMicroflowSelection_Module_Active(getContext(), microflowselection_module_active);
	}

	/**
	 * Set value of MicroflowSelection_Module_Active
	 * @param context
	 * @param microflowselection_module_active
	 */
	public final void setMicroflowSelection_Module_Active(com.mendix.systemwideinterfaces.core.IContext context, agentcommons.proxies.Module microflowselection_module_active)
	{
		if (microflowselection_module_active == null) {
			getMendixObject().setValue(context, MemberNames.MicroflowSelection_Module_Active.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.MicroflowSelection_Module_Active.toString(), microflowselection_module_active.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return microflowSelectionMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final agentcommons.proxies.MicroflowSelection that = (agentcommons.proxies.MicroflowSelection) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
