// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package agentcommons.proxies;

/**
 * The PromptToUse is created via the "Get Prompt For Context Object" action. It contains the System and User prompt texts, with the placeholders replaced by the attribute values of the Context Object. It can be used to pass system and/or user prompt in chat completions operations or other toolbox actions.
 */
public class PromptToUse implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject promptToUseMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AgentCommons.PromptToUse";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		SystemPrompt("SystemPrompt"),
		UserPrompt("UserPrompt"),
		PromptToUse_Version("AgentCommons.PromptToUse_Version");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public PromptToUse(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected PromptToUse(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject promptToUseMendixObject)
	{
		if (promptToUseMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!promptToUseMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.promptToUseMendixObject = promptToUseMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static agentcommons.proxies.PromptToUse initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new agentcommons.proxies.PromptToUse(context, mendixObject);
	}

	public static agentcommons.proxies.PromptToUse load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return agentcommons.proxies.PromptToUse.initialize(context, mendixObject);
	}

	/**
	 * @return value of SystemPrompt
	 */
	public final java.lang.String getSystemPrompt()
	{
		return getSystemPrompt(getContext());
	}

	/**
	 * @param context
	 * @return value of SystemPrompt
	 */
	public final java.lang.String getSystemPrompt(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SystemPrompt.toString());
	}

	/**
	 * Set value of SystemPrompt
	 * @param systemprompt
	 */
	public final void setSystemPrompt(java.lang.String systemprompt)
	{
		setSystemPrompt(getContext(), systemprompt);
	}

	/**
	 * Set value of SystemPrompt
	 * @param context
	 * @param systemprompt
	 */
	public final void setSystemPrompt(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String systemprompt)
	{
		getMendixObject().setValue(context, MemberNames.SystemPrompt.toString(), systemprompt);
	}

	/**
	 * @return value of UserPrompt
	 */
	public final java.lang.String getUserPrompt()
	{
		return getUserPrompt(getContext());
	}

	/**
	 * @param context
	 * @return value of UserPrompt
	 */
	public final java.lang.String getUserPrompt(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.UserPrompt.toString());
	}

	/**
	 * Set value of UserPrompt
	 * @param userprompt
	 */
	public final void setUserPrompt(java.lang.String userprompt)
	{
		setUserPrompt(getContext(), userprompt);
	}

	/**
	 * Set value of UserPrompt
	 * @param context
	 * @param userprompt
	 */
	public final void setUserPrompt(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String userprompt)
	{
		getMendixObject().setValue(context, MemberNames.UserPrompt.toString(), userprompt);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of PromptToUse_Version
	 */
	public final agentcommons.proxies.Version getPromptToUse_Version() throws com.mendix.core.CoreException
	{
		return getPromptToUse_Version(getContext());
	}

	/**
	 * @param context
	 * @return value of PromptToUse_Version
	 * @throws com.mendix.core.CoreException
	 */
	public final agentcommons.proxies.Version getPromptToUse_Version(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		agentcommons.proxies.Version result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.PromptToUse_Version.toString());
		if (identifier != null) {
			result = agentcommons.proxies.Version.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of PromptToUse_Version
	 * @param prompttouse_version
	 */
	public final void setPromptToUse_Version(agentcommons.proxies.Version prompttouse_version)
	{
		setPromptToUse_Version(getContext(), prompttouse_version);
	}

	/**
	 * Set value of PromptToUse_Version
	 * @param context
	 * @param prompttouse_version
	 */
	public final void setPromptToUse_Version(com.mendix.systemwideinterfaces.core.IContext context, agentcommons.proxies.Version prompttouse_version)
	{
		if (prompttouse_version == null) {
			getMendixObject().setValue(context, MemberNames.PromptToUse_Version.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.PromptToUse_Version.toString(), prompttouse_version.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return promptToUseMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final agentcommons.proxies.PromptToUse that = (agentcommons.proxies.PromptToUse) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
