// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package agentcommons.proxies;

/**
 * A tool specialization of type SingleMCPTool which points to a specific tool of an MCP server configuration.
 */
public class SingleMCPTool extends agentcommons.proxies.Tool
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AgentCommons.SingleMCPTool";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		_MCPServerName("_MCPServerName"),
		Name("Name"),
		Description("Description"),
		Microflow("Microflow"),
		IsEnabled("IsEnabled"),
		UUID("UUID"),
		SingleMCPTool_MCPTool("AgentCommons.SingleMCPTool_MCPTool"),
		Tool_Version("AgentCommons.Tool_Version");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public SingleMCPTool(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected SingleMCPTool(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject singleMCPToolMendixObject)
	{
		super(context, singleMCPToolMendixObject);
		if (!singleMCPToolMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static agentcommons.proxies.SingleMCPTool initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new agentcommons.proxies.SingleMCPTool(context, mendixObject);
	}

	public static agentcommons.proxies.SingleMCPTool load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return agentcommons.proxies.SingleMCPTool.initialize(context, mendixObject);
	}

	public static java.util.List<agentcommons.proxies.SingleMCPTool> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> agentcommons.proxies.SingleMCPTool.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of _MCPServerName
	 */
	public final java.lang.String get_MCPServerName()
	{
		return get_MCPServerName(getContext());
	}

	/**
	 * @param context
	 * @return value of _MCPServerName
	 */
	public final java.lang.String get_MCPServerName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames._MCPServerName.toString());
	}

	/**
	 * Set value of _MCPServerName
	 * @param _mcpservername
	 */
	public final void set_MCPServerName(java.lang.String _mcpservername)
	{
		set_MCPServerName(getContext(), _mcpservername);
	}

	/**
	 * Set value of _MCPServerName
	 * @param context
	 * @param _mcpservername
	 */
	public final void set_MCPServerName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String _mcpservername)
	{
		getMendixObject().setValue(context, MemberNames._MCPServerName.toString(), _mcpservername);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of SingleMCPTool_MCPTool
	 */
	public final mcpclient.proxies.MCPTool getSingleMCPTool_MCPTool() throws com.mendix.core.CoreException
	{
		return getSingleMCPTool_MCPTool(getContext());
	}

	/**
	 * @param context
	 * @return value of SingleMCPTool_MCPTool
	 * @throws com.mendix.core.CoreException
	 */
	public final mcpclient.proxies.MCPTool getSingleMCPTool_MCPTool(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		mcpclient.proxies.MCPTool result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.SingleMCPTool_MCPTool.toString());
		if (identifier != null) {
			result = mcpclient.proxies.MCPTool.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of SingleMCPTool_MCPTool
	 * @param singlemcptool_mcptool
	 */
	public final void setSingleMCPTool_MCPTool(mcpclient.proxies.MCPTool singlemcptool_mcptool)
	{
		setSingleMCPTool_MCPTool(getContext(), singlemcptool_mcptool);
	}

	/**
	 * Set value of SingleMCPTool_MCPTool
	 * @param context
	 * @param singlemcptool_mcptool
	 */
	public final void setSingleMCPTool_MCPTool(com.mendix.systemwideinterfaces.core.IContext context, mcpclient.proxies.MCPTool singlemcptool_mcptool)
	{
		if (singlemcptool_mcptool == null) {
			getMendixObject().setValue(context, MemberNames.SingleMCPTool_MCPTool.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.SingleMCPTool_MCPTool.toString(), singlemcptool_mcptool.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final agentcommons.proxies.SingleMCPTool that = (agentcommons.proxies.SingleMCPTool) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
