// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package agentcommons.proxies;

/**
 * A helper entity that is used to add the tool specialization SingleMCPTool.
 */
public class SingleMCPToolView implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject singleMCPToolViewMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AgentCommons.SingleMCPToolView";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		Description("Description"),
		IsEnabled("IsEnabled"),
		SingleMCPToolView_MCPView("AgentCommons.SingleMCPToolView_MCPView"),
		SingleMCPToolView_MCPTool("AgentCommons.SingleMCPToolView_MCPTool");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public SingleMCPToolView(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected SingleMCPToolView(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject singleMCPToolViewMendixObject)
	{
		if (singleMCPToolViewMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!singleMCPToolViewMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.singleMCPToolViewMendixObject = singleMCPToolViewMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static agentcommons.proxies.SingleMCPToolView initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new agentcommons.proxies.SingleMCPToolView(context, mendixObject);
	}

	public static agentcommons.proxies.SingleMCPToolView load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return agentcommons.proxies.SingleMCPToolView.initialize(context, mendixObject);
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of Description
	 */
	public final java.lang.String getDescription()
	{
		return getDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of Description
	 */
	public final java.lang.String getDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Description.toString());
	}

	/**
	 * Set value of Description
	 * @param description
	 */
	public final void setDescription(java.lang.String description)
	{
		setDescription(getContext(), description);
	}

	/**
	 * Set value of Description
	 * @param context
	 * @param description
	 */
	public final void setDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String description)
	{
		getMendixObject().setValue(context, MemberNames.Description.toString(), description);
	}

	/**
	 * @return value of IsEnabled
	 */
	public final java.lang.Boolean getIsEnabled()
	{
		return getIsEnabled(getContext());
	}

	/**
	 * @param context
	 * @return value of IsEnabled
	 */
	public final java.lang.Boolean getIsEnabled(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsEnabled.toString());
	}

	/**
	 * Set value of IsEnabled
	 * @param isenabled
	 */
	public final void setIsEnabled(java.lang.Boolean isenabled)
	{
		setIsEnabled(getContext(), isenabled);
	}

	/**
	 * Set value of IsEnabled
	 * @param context
	 * @param isenabled
	 */
	public final void setIsEnabled(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isenabled)
	{
		getMendixObject().setValue(context, MemberNames.IsEnabled.toString(), isenabled);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of SingleMCPToolView_MCPView
	 */
	public final agentcommons.proxies.MCPView getSingleMCPToolView_MCPView() throws com.mendix.core.CoreException
	{
		return getSingleMCPToolView_MCPView(getContext());
	}

	/**
	 * @param context
	 * @return value of SingleMCPToolView_MCPView
	 * @throws com.mendix.core.CoreException
	 */
	public final agentcommons.proxies.MCPView getSingleMCPToolView_MCPView(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		agentcommons.proxies.MCPView result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.SingleMCPToolView_MCPView.toString());
		if (identifier != null) {
			result = agentcommons.proxies.MCPView.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of SingleMCPToolView_MCPView
	 * @param singlemcptoolview_mcpview
	 */
	public final void setSingleMCPToolView_MCPView(agentcommons.proxies.MCPView singlemcptoolview_mcpview)
	{
		setSingleMCPToolView_MCPView(getContext(), singlemcptoolview_mcpview);
	}

	/**
	 * Set value of SingleMCPToolView_MCPView
	 * @param context
	 * @param singlemcptoolview_mcpview
	 */
	public final void setSingleMCPToolView_MCPView(com.mendix.systemwideinterfaces.core.IContext context, agentcommons.proxies.MCPView singlemcptoolview_mcpview)
	{
		if (singlemcptoolview_mcpview == null) {
			getMendixObject().setValue(context, MemberNames.SingleMCPToolView_MCPView.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.SingleMCPToolView_MCPView.toString(), singlemcptoolview_mcpview.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of SingleMCPToolView_MCPTool
	 */
	public final mcpclient.proxies.MCPTool getSingleMCPToolView_MCPTool() throws com.mendix.core.CoreException
	{
		return getSingleMCPToolView_MCPTool(getContext());
	}

	/**
	 * @param context
	 * @return value of SingleMCPToolView_MCPTool
	 * @throws com.mendix.core.CoreException
	 */
	public final mcpclient.proxies.MCPTool getSingleMCPToolView_MCPTool(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		mcpclient.proxies.MCPTool result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.SingleMCPToolView_MCPTool.toString());
		if (identifier != null) {
			result = mcpclient.proxies.MCPTool.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of SingleMCPToolView_MCPTool
	 * @param singlemcptoolview_mcptool
	 */
	public final void setSingleMCPToolView_MCPTool(mcpclient.proxies.MCPTool singlemcptoolview_mcptool)
	{
		setSingleMCPToolView_MCPTool(getContext(), singlemcptoolview_mcptool);
	}

	/**
	 * Set value of SingleMCPToolView_MCPTool
	 * @param context
	 * @param singlemcptoolview_mcptool
	 */
	public final void setSingleMCPToolView_MCPTool(com.mendix.systemwideinterfaces.core.IContext context, mcpclient.proxies.MCPTool singlemcptoolview_mcptool)
	{
		if (singlemcptoolview_mcptool == null) {
			getMendixObject().setValue(context, MemberNames.SingleMCPToolView_MCPTool.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.SingleMCPToolView_MCPTool.toString(), singlemcptoolview_mcptool.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return singleMCPToolViewMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final agentcommons.proxies.SingleMCPToolView that = (agentcommons.proxies.SingleMCPToolView) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
