// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package agentcommons.proxies;

/**
 * Keeps track of individual test runs while defining the agent.
 */
public class TestRun implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject testRunMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AgentCommons.TestRun";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		OutputText("OutputText"),
		DurationSeconds("DurationSeconds"),
		InputTokens("InputTokens"),
		OutputTokens("OutputTokens"),
		TestRun_TestCase("AgentCommons.TestRun_TestCase"),
		TestRun_PageHelper("AgentCommons.TestRun_PageHelper");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public TestRun(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected TestRun(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject testRunMendixObject)
	{
		if (testRunMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!testRunMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.testRunMendixObject = testRunMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static agentcommons.proxies.TestRun initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new agentcommons.proxies.TestRun(context, mendixObject);
	}

	public static agentcommons.proxies.TestRun load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return agentcommons.proxies.TestRun.initialize(context, mendixObject);
	}

	/**
	 * @return value of OutputText
	 */
	public final java.lang.String getOutputText()
	{
		return getOutputText(getContext());
	}

	/**
	 * @param context
	 * @return value of OutputText
	 */
	public final java.lang.String getOutputText(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.OutputText.toString());
	}

	/**
	 * Set value of OutputText
	 * @param outputtext
	 */
	public final void setOutputText(java.lang.String outputtext)
	{
		setOutputText(getContext(), outputtext);
	}

	/**
	 * Set value of OutputText
	 * @param context
	 * @param outputtext
	 */
	public final void setOutputText(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String outputtext)
	{
		getMendixObject().setValue(context, MemberNames.OutputText.toString(), outputtext);
	}

	/**
	 * @return value of DurationSeconds
	 */
	public final java.math.BigDecimal getDurationSeconds()
	{
		return getDurationSeconds(getContext());
	}

	/**
	 * @param context
	 * @return value of DurationSeconds
	 */
	public final java.math.BigDecimal getDurationSeconds(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.DurationSeconds.toString());
	}

	/**
	 * Set value of DurationSeconds
	 * @param durationseconds
	 */
	public final void setDurationSeconds(java.math.BigDecimal durationseconds)
	{
		setDurationSeconds(getContext(), durationseconds);
	}

	/**
	 * Set value of DurationSeconds
	 * @param context
	 * @param durationseconds
	 */
	public final void setDurationSeconds(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal durationseconds)
	{
		getMendixObject().setValue(context, MemberNames.DurationSeconds.toString(), durationseconds);
	}

	/**
	 * @return value of InputTokens
	 */
	public final java.lang.Integer getInputTokens()
	{
		return getInputTokens(getContext());
	}

	/**
	 * @param context
	 * @return value of InputTokens
	 */
	public final java.lang.Integer getInputTokens(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.InputTokens.toString());
	}

	/**
	 * Set value of InputTokens
	 * @param inputtokens
	 */
	public final void setInputTokens(java.lang.Integer inputtokens)
	{
		setInputTokens(getContext(), inputtokens);
	}

	/**
	 * Set value of InputTokens
	 * @param context
	 * @param inputtokens
	 */
	public final void setInputTokens(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer inputtokens)
	{
		getMendixObject().setValue(context, MemberNames.InputTokens.toString(), inputtokens);
	}

	/**
	 * @return value of OutputTokens
	 */
	public final java.lang.Integer getOutputTokens()
	{
		return getOutputTokens(getContext());
	}

	/**
	 * @param context
	 * @return value of OutputTokens
	 */
	public final java.lang.Integer getOutputTokens(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.OutputTokens.toString());
	}

	/**
	 * Set value of OutputTokens
	 * @param outputtokens
	 */
	public final void setOutputTokens(java.lang.Integer outputtokens)
	{
		setOutputTokens(getContext(), outputtokens);
	}

	/**
	 * Set value of OutputTokens
	 * @param context
	 * @param outputtokens
	 */
	public final void setOutputTokens(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer outputtokens)
	{
		getMendixObject().setValue(context, MemberNames.OutputTokens.toString(), outputtokens);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of TestRun_TestCase
	 */
	public final agentcommons.proxies.TestCase getTestRun_TestCase() throws com.mendix.core.CoreException
	{
		return getTestRun_TestCase(getContext());
	}

	/**
	 * @param context
	 * @return value of TestRun_TestCase
	 * @throws com.mendix.core.CoreException
	 */
	public final agentcommons.proxies.TestCase getTestRun_TestCase(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		agentcommons.proxies.TestCase result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.TestRun_TestCase.toString());
		if (identifier != null) {
			result = agentcommons.proxies.TestCase.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of TestRun_TestCase
	 * @param testrun_testcase
	 */
	public final void setTestRun_TestCase(agentcommons.proxies.TestCase testrun_testcase)
	{
		setTestRun_TestCase(getContext(), testrun_testcase);
	}

	/**
	 * Set value of TestRun_TestCase
	 * @param context
	 * @param testrun_testcase
	 */
	public final void setTestRun_TestCase(com.mendix.systemwideinterfaces.core.IContext context, agentcommons.proxies.TestCase testrun_testcase)
	{
		if (testrun_testcase == null) {
			getMendixObject().setValue(context, MemberNames.TestRun_TestCase.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.TestRun_TestCase.toString(), testrun_testcase.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of TestRun_PageHelper
	 */
	public final agentcommons.proxies.PageHelper getTestRun_PageHelper() throws com.mendix.core.CoreException
	{
		return getTestRun_PageHelper(getContext());
	}

	/**
	 * @param context
	 * @return value of TestRun_PageHelper
	 * @throws com.mendix.core.CoreException
	 */
	public final agentcommons.proxies.PageHelper getTestRun_PageHelper(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		agentcommons.proxies.PageHelper result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.TestRun_PageHelper.toString());
		if (identifier != null) {
			result = agentcommons.proxies.PageHelper.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of TestRun_PageHelper
	 * @param testrun_pagehelper
	 */
	public final void setTestRun_PageHelper(agentcommons.proxies.PageHelper testrun_pagehelper)
	{
		setTestRun_PageHelper(getContext(), testrun_pagehelper);
	}

	/**
	 * Set value of TestRun_PageHelper
	 * @param context
	 * @param testrun_pagehelper
	 */
	public final void setTestRun_PageHelper(com.mendix.systemwideinterfaces.core.IContext context, agentcommons.proxies.PageHelper testrun_pagehelper)
	{
		if (testrun_pagehelper == null) {
			getMendixObject().setValue(context, MemberNames.TestRun_PageHelper.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.TestRun_PageHelper.toString(), testrun_pagehelper.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return testRunMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final agentcommons.proxies.TestRun that = (agentcommons.proxies.TestRun) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
