// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package agentcommons.proxies;

/**
 * Test Cases can be created to test different scenarios with the same agent. Its associated values represent the values the variable placeholders should be replaced with.
 */
public class TestCase implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject testCaseMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AgentCommons.TestCase";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		UUID("UUID"),
		IsDraftTestCase("IsDraftTestCase"),
		TestCase_Agent("AgentCommons.TestCase_Agent");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public TestCase(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected TestCase(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject testCaseMendixObject)
	{
		if (testCaseMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!testCaseMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.testCaseMendixObject = testCaseMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static agentcommons.proxies.TestCase initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new agentcommons.proxies.TestCase(context, mendixObject);
	}

	public static agentcommons.proxies.TestCase load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return agentcommons.proxies.TestCase.initialize(context, mendixObject);
	}

	public static java.util.List<agentcommons.proxies.TestCase> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> agentcommons.proxies.TestCase.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of UUID
	 */
	public final java.lang.String getUUID()
	{
		return getUUID(getContext());
	}

	/**
	 * @param context
	 * @return value of UUID
	 */
	public final java.lang.String getUUID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.UUID.toString());
	}

	/**
	 * Set value of UUID
	 * @param uuid
	 */
	public final void setUUID(java.lang.String uuid)
	{
		setUUID(getContext(), uuid);
	}

	/**
	 * Set value of UUID
	 * @param context
	 * @param uuid
	 */
	public final void setUUID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String uuid)
	{
		getMendixObject().setValue(context, MemberNames.UUID.toString(), uuid);
	}

	/**
	 * @return value of IsDraftTestCase
	 */
	public final java.lang.Boolean getIsDraftTestCase()
	{
		return getIsDraftTestCase(getContext());
	}

	/**
	 * @param context
	 * @return value of IsDraftTestCase
	 */
	public final java.lang.Boolean getIsDraftTestCase(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsDraftTestCase.toString());
	}

	/**
	 * Set value of IsDraftTestCase
	 * @param isdrafttestcase
	 */
	public final void setIsDraftTestCase(java.lang.Boolean isdrafttestcase)
	{
		setIsDraftTestCase(getContext(), isdrafttestcase);
	}

	/**
	 * Set value of IsDraftTestCase
	 * @param context
	 * @param isdrafttestcase
	 */
	public final void setIsDraftTestCase(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isdrafttestcase)
	{
		getMendixObject().setValue(context, MemberNames.IsDraftTestCase.toString(), isdrafttestcase);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of TestCase_Agent
	 */
	public final agentcommons.proxies.Agent getTestCase_Agent() throws com.mendix.core.CoreException
	{
		return getTestCase_Agent(getContext());
	}

	/**
	 * @param context
	 * @return value of TestCase_Agent
	 * @throws com.mendix.core.CoreException
	 */
	public final agentcommons.proxies.Agent getTestCase_Agent(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		agentcommons.proxies.Agent result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.TestCase_Agent.toString());
		if (identifier != null) {
			result = agentcommons.proxies.Agent.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of TestCase_Agent
	 * @param testcase_agent
	 */
	public final void setTestCase_Agent(agentcommons.proxies.Agent testcase_agent)
	{
		setTestCase_Agent(getContext(), testcase_agent);
	}

	/**
	 * Set value of TestCase_Agent
	 * @param context
	 * @param testcase_agent
	 */
	public final void setTestCase_Agent(com.mendix.systemwideinterfaces.core.IContext context, agentcommons.proxies.Agent testcase_agent)
	{
		if (testcase_agent == null) {
			getMendixObject().setValue(context, MemberNames.TestCase_Agent.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.TestCase_Agent.toString(), testcase_agent.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return testCaseMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final agentcommons.proxies.TestCase that = (agentcommons.proxies.TestCase) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
