// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package agentcommons.proxies;

/**
 * A Value can be set per Variable and TestCase. This is used to replace the variable {{placeholder}} found in the prompts when running the a test for the agent.
 */
public class Value implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject valueMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AgentCommons.Value";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Value("Value"),
		Value_Variable("AgentCommons.Value_Variable"),
		Value_TestCase("AgentCommons.Value_TestCase");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Value(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Value(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject valueMendixObject)
	{
		if (valueMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!valueMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.valueMendixObject = valueMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static agentcommons.proxies.Value initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new agentcommons.proxies.Value(context, mendixObject);
	}

	public static agentcommons.proxies.Value load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return agentcommons.proxies.Value.initialize(context, mendixObject);
	}

	public static java.util.List<agentcommons.proxies.Value> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> agentcommons.proxies.Value.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of Value
	 */
	public final java.lang.String getValue()
	{
		return getValue(getContext());
	}

	/**
	 * @param context
	 * @return value of Value
	 */
	public final java.lang.String getValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Value.toString());
	}

	/**
	 * Set value of Value
	 * @param value
	 */
	public final void setValue(java.lang.String value)
	{
		setValue(getContext(), value);
	}

	/**
	 * Set value of Value
	 * @param context
	 * @param value
	 */
	public final void setValue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String value)
	{
		getMendixObject().setValue(context, MemberNames.Value.toString(), value);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Value_Variable
	 */
	public final agentcommons.proxies.Variable getValue_Variable() throws com.mendix.core.CoreException
	{
		return getValue_Variable(getContext());
	}

	/**
	 * @param context
	 * @return value of Value_Variable
	 * @throws com.mendix.core.CoreException
	 */
	public final agentcommons.proxies.Variable getValue_Variable(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		agentcommons.proxies.Variable result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Value_Variable.toString());
		if (identifier != null) {
			result = agentcommons.proxies.Variable.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Value_Variable
	 * @param value_variable
	 */
	public final void setValue_Variable(agentcommons.proxies.Variable value_variable)
	{
		setValue_Variable(getContext(), value_variable);
	}

	/**
	 * Set value of Value_Variable
	 * @param context
	 * @param value_variable
	 */
	public final void setValue_Variable(com.mendix.systemwideinterfaces.core.IContext context, agentcommons.proxies.Variable value_variable)
	{
		if (value_variable == null) {
			getMendixObject().setValue(context, MemberNames.Value_Variable.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Value_Variable.toString(), value_variable.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Value_TestCase
	 */
	public final agentcommons.proxies.TestCase getValue_TestCase() throws com.mendix.core.CoreException
	{
		return getValue_TestCase(getContext());
	}

	/**
	 * @param context
	 * @return value of Value_TestCase
	 * @throws com.mendix.core.CoreException
	 */
	public final agentcommons.proxies.TestCase getValue_TestCase(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		agentcommons.proxies.TestCase result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Value_TestCase.toString());
		if (identifier != null) {
			result = agentcommons.proxies.TestCase.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Value_TestCase
	 * @param value_testcase
	 */
	public final void setValue_TestCase(agentcommons.proxies.TestCase value_testcase)
	{
		setValue_TestCase(getContext(), value_testcase);
	}

	/**
	 * Set value of Value_TestCase
	 * @param context
	 * @param value_testcase
	 */
	public final void setValue_TestCase(com.mendix.systemwideinterfaces.core.IContext context, agentcommons.proxies.TestCase value_testcase)
	{
		if (value_testcase == null) {
			getMendixObject().setValue(context, MemberNames.Value_TestCase.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Value_TestCase.toString(), value_testcase.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return valueMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final agentcommons.proxies.Value that = (agentcommons.proxies.Value) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
