// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package agentcommons.proxies;

public class ValueImport implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject valueImportMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AgentCommons.ValueImport";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Value("Value"),
		ValueImport_VariableImport("AgentCommons.ValueImport_VariableImport"),
		ValueImport_TestCaseImport("AgentCommons.ValueImport_TestCaseImport");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ValueImport(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ValueImport(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject valueImportMendixObject)
	{
		if (valueImportMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!valueImportMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.valueImportMendixObject = valueImportMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static agentcommons.proxies.ValueImport initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new agentcommons.proxies.ValueImport(context, mendixObject);
	}

	public static agentcommons.proxies.ValueImport load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return agentcommons.proxies.ValueImport.initialize(context, mendixObject);
	}

	/**
	 * @return value of Value
	 */
	public final java.lang.String getValue()
	{
		return getValue(getContext());
	}

	/**
	 * @param context
	 * @return value of Value
	 */
	public final java.lang.String getValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Value.toString());
	}

	/**
	 * Set value of Value
	 * @param value
	 */
	public final void setValue(java.lang.String value)
	{
		setValue(getContext(), value);
	}

	/**
	 * Set value of Value
	 * @param context
	 * @param value
	 */
	public final void setValue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String value)
	{
		getMendixObject().setValue(context, MemberNames.Value.toString(), value);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ValueImport_VariableImport
	 */
	public final agentcommons.proxies.VariableImport getValueImport_VariableImport() throws com.mendix.core.CoreException
	{
		return getValueImport_VariableImport(getContext());
	}

	/**
	 * @param context
	 * @return value of ValueImport_VariableImport
	 * @throws com.mendix.core.CoreException
	 */
	public final agentcommons.proxies.VariableImport getValueImport_VariableImport(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		agentcommons.proxies.VariableImport result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ValueImport_VariableImport.toString());
		if (identifier != null) {
			result = agentcommons.proxies.VariableImport.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ValueImport_VariableImport
	 * @param valueimport_variableimport
	 */
	public final void setValueImport_VariableImport(agentcommons.proxies.VariableImport valueimport_variableimport)
	{
		setValueImport_VariableImport(getContext(), valueimport_variableimport);
	}

	/**
	 * Set value of ValueImport_VariableImport
	 * @param context
	 * @param valueimport_variableimport
	 */
	public final void setValueImport_VariableImport(com.mendix.systemwideinterfaces.core.IContext context, agentcommons.proxies.VariableImport valueimport_variableimport)
	{
		if (valueimport_variableimport == null) {
			getMendixObject().setValue(context, MemberNames.ValueImport_VariableImport.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ValueImport_VariableImport.toString(), valueimport_variableimport.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ValueImport_TestCaseImport
	 */
	public final agentcommons.proxies.TestCaseImport getValueImport_TestCaseImport() throws com.mendix.core.CoreException
	{
		return getValueImport_TestCaseImport(getContext());
	}

	/**
	 * @param context
	 * @return value of ValueImport_TestCaseImport
	 * @throws com.mendix.core.CoreException
	 */
	public final agentcommons.proxies.TestCaseImport getValueImport_TestCaseImport(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		agentcommons.proxies.TestCaseImport result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ValueImport_TestCaseImport.toString());
		if (identifier != null) {
			result = agentcommons.proxies.TestCaseImport.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ValueImport_TestCaseImport
	 * @param valueimport_testcaseimport
	 */
	public final void setValueImport_TestCaseImport(agentcommons.proxies.TestCaseImport valueimport_testcaseimport)
	{
		setValueImport_TestCaseImport(getContext(), valueimport_testcaseimport);
	}

	/**
	 * Set value of ValueImport_TestCaseImport
	 * @param context
	 * @param valueimport_testcaseimport
	 */
	public final void setValueImport_TestCaseImport(com.mendix.systemwideinterfaces.core.IContext context, agentcommons.proxies.TestCaseImport valueimport_testcaseimport)
	{
		if (valueimport_testcaseimport == null) {
			getMendixObject().setValue(context, MemberNames.ValueImport_TestCaseImport.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ValueImport_TestCaseImport.toString(), valueimport_testcaseimport.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return valueImportMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final agentcommons.proxies.ValueImport that = (agentcommons.proxies.ValueImport) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
