// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package agentcommons.proxies;

/**
 * A Variable is created when a {{placeholder}} is found in the system or user prompt (a key string within curly brackets). If the variable is no longer in use as a placeholder in any of the prompt texts, it gets deleted automatically.
 */
public class Variable implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject variableMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AgentCommons.Variable";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Key("Key"),
		IsAttributeInEntity("IsAttributeInEntity"),
		Variable_Agent("AgentCommons.Variable_Agent");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Variable(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Variable(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject variableMendixObject)
	{
		if (variableMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!variableMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.variableMendixObject = variableMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static agentcommons.proxies.Variable initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new agentcommons.proxies.Variable(context, mendixObject);
	}

	public static agentcommons.proxies.Variable load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return agentcommons.proxies.Variable.initialize(context, mendixObject);
	}

	public static java.util.List<agentcommons.proxies.Variable> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> agentcommons.proxies.Variable.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of Key
	 */
	public final java.lang.String getKey()
	{
		return getKey(getContext());
	}

	/**
	 * @param context
	 * @return value of Key
	 */
	public final java.lang.String getKey(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Key.toString());
	}

	/**
	 * Set value of Key
	 * @param key
	 */
	public final void setKey(java.lang.String key)
	{
		setKey(getContext(), key);
	}

	/**
	 * Set value of Key
	 * @param context
	 * @param key
	 */
	public final void setKey(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String key)
	{
		getMendixObject().setValue(context, MemberNames.Key.toString(), key);
	}

	/**
	 * @return value of IsAttributeInEntity
	 */
	public final java.lang.Boolean getIsAttributeInEntity()
	{
		return getIsAttributeInEntity(getContext());
	}

	/**
	 * @param context
	 * @return value of IsAttributeInEntity
	 */
	public final java.lang.Boolean getIsAttributeInEntity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsAttributeInEntity.toString());
	}

	/**
	 * Set value of IsAttributeInEntity
	 * @param isattributeinentity
	 */
	public final void setIsAttributeInEntity(java.lang.Boolean isattributeinentity)
	{
		setIsAttributeInEntity(getContext(), isattributeinentity);
	}

	/**
	 * Set value of IsAttributeInEntity
	 * @param context
	 * @param isattributeinentity
	 */
	public final void setIsAttributeInEntity(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isattributeinentity)
	{
		getMendixObject().setValue(context, MemberNames.IsAttributeInEntity.toString(), isattributeinentity);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Variable_Agent
	 */
	public final agentcommons.proxies.Agent getVariable_Agent() throws com.mendix.core.CoreException
	{
		return getVariable_Agent(getContext());
	}

	/**
	 * @param context
	 * @return value of Variable_Agent
	 * @throws com.mendix.core.CoreException
	 */
	public final agentcommons.proxies.Agent getVariable_Agent(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		agentcommons.proxies.Agent result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Variable_Agent.toString());
		if (identifier != null) {
			result = agentcommons.proxies.Agent.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Variable_Agent
	 * @param variable_agent
	 */
	public final void setVariable_Agent(agentcommons.proxies.Agent variable_agent)
	{
		setVariable_Agent(getContext(), variable_agent);
	}

	/**
	 * Set value of Variable_Agent
	 * @param context
	 * @param variable_agent
	 */
	public final void setVariable_Agent(com.mendix.systemwideinterfaces.core.IContext context, agentcommons.proxies.Agent variable_agent)
	{
		if (variable_agent == null) {
			getMendixObject().setValue(context, MemberNames.Variable_Agent.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Variable_Agent.toString(), variable_agent.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return variableMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final agentcommons.proxies.Variable that = (agentcommons.proxies.Variable) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
