// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package agentcommons.proxies;

public class VersionImport implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject versionImportMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AgentCommons.VersionImport";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Title("Title"),
		Description("Description"),
		VersionNumber("VersionNumber"),
		UUID("UUID"),
		SystemPrompt("SystemPrompt"),
		UserPrompt("UserPrompt"),
		VersionOwner("VersionOwner"),
		VersionChangedDate("VersionChangedDate"),
		ToolChoice("ToolChoice"),
		MaxTokens("MaxTokens"),
		Temperature("Temperature"),
		TopP("TopP"),
		DeployedModel_Model("DeployedModel_Model"),
		DeployedModel_Architecture("DeployedModel_Architecture"),
		VersionImport_AgentImport("AgentCommons.VersionImport_AgentImport"),
		VersionImport_ToolImport_Choice("AgentCommons.VersionImport_ToolImport_Choice");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public VersionImport(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected VersionImport(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject versionImportMendixObject)
	{
		if (versionImportMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!versionImportMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.versionImportMendixObject = versionImportMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static agentcommons.proxies.VersionImport initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new agentcommons.proxies.VersionImport(context, mendixObject);
	}

	public static agentcommons.proxies.VersionImport load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return agentcommons.proxies.VersionImport.initialize(context, mendixObject);
	}

	/**
	 * @return value of Title
	 */
	public final java.lang.String getTitle()
	{
		return getTitle(getContext());
	}

	/**
	 * @param context
	 * @return value of Title
	 */
	public final java.lang.String getTitle(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Title.toString());
	}

	/**
	 * Set value of Title
	 * @param title
	 */
	public final void setTitle(java.lang.String title)
	{
		setTitle(getContext(), title);
	}

	/**
	 * Set value of Title
	 * @param context
	 * @param title
	 */
	public final void setTitle(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String title)
	{
		getMendixObject().setValue(context, MemberNames.Title.toString(), title);
	}

	/**
	 * @return value of Description
	 */
	public final java.lang.String getDescription()
	{
		return getDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of Description
	 */
	public final java.lang.String getDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Description.toString());
	}

	/**
	 * Set value of Description
	 * @param description
	 */
	public final void setDescription(java.lang.String description)
	{
		setDescription(getContext(), description);
	}

	/**
	 * Set value of Description
	 * @param context
	 * @param description
	 */
	public final void setDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String description)
	{
		getMendixObject().setValue(context, MemberNames.Description.toString(), description);
	}

	/**
	 * @return value of VersionNumber
	 */
	public final java.lang.Integer getVersionNumber()
	{
		return getVersionNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of VersionNumber
	 */
	public final java.lang.Integer getVersionNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.VersionNumber.toString());
	}

	/**
	 * Set value of VersionNumber
	 * @param versionnumber
	 */
	public final void setVersionNumber(java.lang.Integer versionnumber)
	{
		setVersionNumber(getContext(), versionnumber);
	}

	/**
	 * Set value of VersionNumber
	 * @param context
	 * @param versionnumber
	 */
	public final void setVersionNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer versionnumber)
	{
		getMendixObject().setValue(context, MemberNames.VersionNumber.toString(), versionnumber);
	}

	/**
	 * @return value of UUID
	 */
	public final java.lang.String getUUID()
	{
		return getUUID(getContext());
	}

	/**
	 * @param context
	 * @return value of UUID
	 */
	public final java.lang.String getUUID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.UUID.toString());
	}

	/**
	 * Set value of UUID
	 * @param uuid
	 */
	public final void setUUID(java.lang.String uuid)
	{
		setUUID(getContext(), uuid);
	}

	/**
	 * Set value of UUID
	 * @param context
	 * @param uuid
	 */
	public final void setUUID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String uuid)
	{
		getMendixObject().setValue(context, MemberNames.UUID.toString(), uuid);
	}

	/**
	 * @return value of SystemPrompt
	 */
	public final java.lang.String getSystemPrompt()
	{
		return getSystemPrompt(getContext());
	}

	/**
	 * @param context
	 * @return value of SystemPrompt
	 */
	public final java.lang.String getSystemPrompt(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SystemPrompt.toString());
	}

	/**
	 * Set value of SystemPrompt
	 * @param systemprompt
	 */
	public final void setSystemPrompt(java.lang.String systemprompt)
	{
		setSystemPrompt(getContext(), systemprompt);
	}

	/**
	 * Set value of SystemPrompt
	 * @param context
	 * @param systemprompt
	 */
	public final void setSystemPrompt(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String systemprompt)
	{
		getMendixObject().setValue(context, MemberNames.SystemPrompt.toString(), systemprompt);
	}

	/**
	 * @return value of UserPrompt
	 */
	public final java.lang.String getUserPrompt()
	{
		return getUserPrompt(getContext());
	}

	/**
	 * @param context
	 * @return value of UserPrompt
	 */
	public final java.lang.String getUserPrompt(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.UserPrompt.toString());
	}

	/**
	 * Set value of UserPrompt
	 * @param userprompt
	 */
	public final void setUserPrompt(java.lang.String userprompt)
	{
		setUserPrompt(getContext(), userprompt);
	}

	/**
	 * Set value of UserPrompt
	 * @param context
	 * @param userprompt
	 */
	public final void setUserPrompt(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String userprompt)
	{
		getMendixObject().setValue(context, MemberNames.UserPrompt.toString(), userprompt);
	}

	/**
	 * @return value of VersionOwner
	 */
	public final java.lang.String getVersionOwner()
	{
		return getVersionOwner(getContext());
	}

	/**
	 * @param context
	 * @return value of VersionOwner
	 */
	public final java.lang.String getVersionOwner(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.VersionOwner.toString());
	}

	/**
	 * Set value of VersionOwner
	 * @param versionowner
	 */
	public final void setVersionOwner(java.lang.String versionowner)
	{
		setVersionOwner(getContext(), versionowner);
	}

	/**
	 * Set value of VersionOwner
	 * @param context
	 * @param versionowner
	 */
	public final void setVersionOwner(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String versionowner)
	{
		getMendixObject().setValue(context, MemberNames.VersionOwner.toString(), versionowner);
	}

	/**
	 * @return value of VersionChangedDate
	 */
	public final java.util.Date getVersionChangedDate()
	{
		return getVersionChangedDate(getContext());
	}

	/**
	 * @param context
	 * @return value of VersionChangedDate
	 */
	public final java.util.Date getVersionChangedDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.VersionChangedDate.toString());
	}

	/**
	 * Set value of VersionChangedDate
	 * @param versionchangeddate
	 */
	public final void setVersionChangedDate(java.util.Date versionchangeddate)
	{
		setVersionChangedDate(getContext(), versionchangeddate);
	}

	/**
	 * Set value of VersionChangedDate
	 * @param context
	 * @param versionchangeddate
	 */
	public final void setVersionChangedDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date versionchangeddate)
	{
		getMendixObject().setValue(context, MemberNames.VersionChangedDate.toString(), versionchangeddate);
	}

	/**
	 * Get value of ToolChoice
	 * @param toolchoice
	 */
	public final genaicommons.proxies.ENUM_ToolChoice getToolChoice()
	{
		return getToolChoice(getContext());
	}

	/**
	 * @param context
	 * @return value of ToolChoice
	 */
	public final genaicommons.proxies.ENUM_ToolChoice getToolChoice(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.ToolChoice.toString());
		if (obj == null) {
			return null;
		}
		return genaicommons.proxies.ENUM_ToolChoice.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of ToolChoice
	 * @param toolchoice
	 */
	public final void setToolChoice(genaicommons.proxies.ENUM_ToolChoice toolchoice)
	{
		setToolChoice(getContext(), toolchoice);
	}

	/**
	 * Set value of ToolChoice
	 * @param context
	 * @param toolchoice
	 */
	public final void setToolChoice(com.mendix.systemwideinterfaces.core.IContext context, genaicommons.proxies.ENUM_ToolChoice toolchoice)
	{
		if (toolchoice != null) {
			getMendixObject().setValue(context, MemberNames.ToolChoice.toString(), toolchoice.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.ToolChoice.toString(), null);
		}
	}

	/**
	 * @return value of MaxTokens
	 */
	public final java.lang.Integer getMaxTokens()
	{
		return getMaxTokens(getContext());
	}

	/**
	 * @param context
	 * @return value of MaxTokens
	 */
	public final java.lang.Integer getMaxTokens(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.MaxTokens.toString());
	}

	/**
	 * Set value of MaxTokens
	 * @param maxtokens
	 */
	public final void setMaxTokens(java.lang.Integer maxtokens)
	{
		setMaxTokens(getContext(), maxtokens);
	}

	/**
	 * Set value of MaxTokens
	 * @param context
	 * @param maxtokens
	 */
	public final void setMaxTokens(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer maxtokens)
	{
		getMendixObject().setValue(context, MemberNames.MaxTokens.toString(), maxtokens);
	}

	/**
	 * @return value of Temperature
	 */
	public final java.math.BigDecimal getTemperature()
	{
		return getTemperature(getContext());
	}

	/**
	 * @param context
	 * @return value of Temperature
	 */
	public final java.math.BigDecimal getTemperature(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Temperature.toString());
	}

	/**
	 * Set value of Temperature
	 * @param temperature
	 */
	public final void setTemperature(java.math.BigDecimal temperature)
	{
		setTemperature(getContext(), temperature);
	}

	/**
	 * Set value of Temperature
	 * @param context
	 * @param temperature
	 */
	public final void setTemperature(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal temperature)
	{
		getMendixObject().setValue(context, MemberNames.Temperature.toString(), temperature);
	}

	/**
	 * @return value of TopP
	 */
	public final java.math.BigDecimal getTopP()
	{
		return getTopP(getContext());
	}

	/**
	 * @param context
	 * @return value of TopP
	 */
	public final java.math.BigDecimal getTopP(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.TopP.toString());
	}

	/**
	 * Set value of TopP
	 * @param topp
	 */
	public final void setTopP(java.math.BigDecimal topp)
	{
		setTopP(getContext(), topp);
	}

	/**
	 * Set value of TopP
	 * @param context
	 * @param topp
	 */
	public final void setTopP(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal topp)
	{
		getMendixObject().setValue(context, MemberNames.TopP.toString(), topp);
	}

	/**
	 * @return value of DeployedModel_Model
	 */
	public final java.lang.String getDeployedModel_Model()
	{
		return getDeployedModel_Model(getContext());
	}

	/**
	 * @param context
	 * @return value of DeployedModel_Model
	 */
	public final java.lang.String getDeployedModel_Model(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DeployedModel_Model.toString());
	}

	/**
	 * Set value of DeployedModel_Model
	 * @param deployedmodel_model
	 */
	public final void setDeployedModel_Model(java.lang.String deployedmodel_model)
	{
		setDeployedModel_Model(getContext(), deployedmodel_model);
	}

	/**
	 * Set value of DeployedModel_Model
	 * @param context
	 * @param deployedmodel_model
	 */
	public final void setDeployedModel_Model(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String deployedmodel_model)
	{
		getMendixObject().setValue(context, MemberNames.DeployedModel_Model.toString(), deployedmodel_model);
	}

	/**
	 * @return value of DeployedModel_Architecture
	 */
	public final java.lang.String getDeployedModel_Architecture()
	{
		return getDeployedModel_Architecture(getContext());
	}

	/**
	 * @param context
	 * @return value of DeployedModel_Architecture
	 */
	public final java.lang.String getDeployedModel_Architecture(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DeployedModel_Architecture.toString());
	}

	/**
	 * Set value of DeployedModel_Architecture
	 * @param deployedmodel_architecture
	 */
	public final void setDeployedModel_Architecture(java.lang.String deployedmodel_architecture)
	{
		setDeployedModel_Architecture(getContext(), deployedmodel_architecture);
	}

	/**
	 * Set value of DeployedModel_Architecture
	 * @param context
	 * @param deployedmodel_architecture
	 */
	public final void setDeployedModel_Architecture(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String deployedmodel_architecture)
	{
		getMendixObject().setValue(context, MemberNames.DeployedModel_Architecture.toString(), deployedmodel_architecture);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of VersionImport_AgentImport
	 */
	public final agentcommons.proxies.AgentImport getVersionImport_AgentImport() throws com.mendix.core.CoreException
	{
		return getVersionImport_AgentImport(getContext());
	}

	/**
	 * @param context
	 * @return value of VersionImport_AgentImport
	 * @throws com.mendix.core.CoreException
	 */
	public final agentcommons.proxies.AgentImport getVersionImport_AgentImport(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		agentcommons.proxies.AgentImport result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.VersionImport_AgentImport.toString());
		if (identifier != null) {
			result = agentcommons.proxies.AgentImport.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of VersionImport_AgentImport
	 * @param versionimport_agentimport
	 */
	public final void setVersionImport_AgentImport(agentcommons.proxies.AgentImport versionimport_agentimport)
	{
		setVersionImport_AgentImport(getContext(), versionimport_agentimport);
	}

	/**
	 * Set value of VersionImport_AgentImport
	 * @param context
	 * @param versionimport_agentimport
	 */
	public final void setVersionImport_AgentImport(com.mendix.systemwideinterfaces.core.IContext context, agentcommons.proxies.AgentImport versionimport_agentimport)
	{
		if (versionimport_agentimport == null) {
			getMendixObject().setValue(context, MemberNames.VersionImport_AgentImport.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.VersionImport_AgentImport.toString(), versionimport_agentimport.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of VersionImport_ToolImport_Choice
	 */
	public final agentcommons.proxies.ToolImport getVersionImport_ToolImport_Choice() throws com.mendix.core.CoreException
	{
		return getVersionImport_ToolImport_Choice(getContext());
	}

	/**
	 * @param context
	 * @return value of VersionImport_ToolImport_Choice
	 * @throws com.mendix.core.CoreException
	 */
	public final agentcommons.proxies.ToolImport getVersionImport_ToolImport_Choice(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		agentcommons.proxies.ToolImport result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.VersionImport_ToolImport_Choice.toString());
		if (identifier != null) {
			result = agentcommons.proxies.ToolImport.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of VersionImport_ToolImport_Choice
	 * @param versionimport_toolimport_choice
	 */
	public final void setVersionImport_ToolImport_Choice(agentcommons.proxies.ToolImport versionimport_toolimport_choice)
	{
		setVersionImport_ToolImport_Choice(getContext(), versionimport_toolimport_choice);
	}

	/**
	 * Set value of VersionImport_ToolImport_Choice
	 * @param context
	 * @param versionimport_toolimport_choice
	 */
	public final void setVersionImport_ToolImport_Choice(com.mendix.systemwideinterfaces.core.IContext context, agentcommons.proxies.ToolImport versionimport_toolimport_choice)
	{
		if (versionimport_toolimport_choice == null) {
			getMendixObject().setValue(context, MemberNames.VersionImport_ToolImport_Choice.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.VersionImport_ToolImport_Choice.toString(), versionimport_toolimport_choice.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return versionImportMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final agentcommons.proxies.VersionImport that = (agentcommons.proxies.VersionImport) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
