// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package agentcommons.proxies;

/**
 * An Agent can have multiple Versions that the AgentAdmin can create to improve and further refine the prompts, parameters, tool calls and knowledge base interactions. Only one version is marked as the current "In use" version for the agent, which is the one that is used at runtime in the running app instance, for example if using the Call Agent activity from the toolbox.
 */
public class Version implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject versionMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AgentCommons.Version";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Title("Title"),
		Description("Description"),
		VersionNumber("VersionNumber"),
		UUID("UUID"),
		SystemPrompt("SystemPrompt"),
		UserPrompt("UserPrompt"),
		VersionOwner("VersionOwner"),
		VersionChangedDate("VersionChangedDate"),
		LastChangedBy("LastChangedBy"),
		IsDraftVersion("IsDraftVersion"),
		ToolChoice("ToolChoice"),
		Temperature("Temperature"),
		MaxTokens("MaxTokens"),
		TopP("TopP"),
		Version_Agent("AgentCommons.Version_Agent"),
		Version_ToolChoice("AgentCommons.Version_ToolChoice"),
		Version_DeployedModel("AgentCommons.Version_DeployedModel");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Version(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Version(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject versionMendixObject)
	{
		if (versionMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!versionMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.versionMendixObject = versionMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static agentcommons.proxies.Version initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new agentcommons.proxies.Version(context, mendixObject);
	}

	public static agentcommons.proxies.Version load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return agentcommons.proxies.Version.initialize(context, mendixObject);
	}

	public static java.util.List<agentcommons.proxies.Version> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> agentcommons.proxies.Version.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of Title
	 */
	public final java.lang.String getTitle()
	{
		return getTitle(getContext());
	}

	/**
	 * @param context
	 * @return value of Title
	 */
	public final java.lang.String getTitle(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Title.toString());
	}

	/**
	 * Set value of Title
	 * @param title
	 */
	public final void setTitle(java.lang.String title)
	{
		setTitle(getContext(), title);
	}

	/**
	 * Set value of Title
	 * @param context
	 * @param title
	 */
	public final void setTitle(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String title)
	{
		getMendixObject().setValue(context, MemberNames.Title.toString(), title);
	}

	/**
	 * @return value of Description
	 */
	public final java.lang.String getDescription()
	{
		return getDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of Description
	 */
	public final java.lang.String getDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Description.toString());
	}

	/**
	 * Set value of Description
	 * @param description
	 */
	public final void setDescription(java.lang.String description)
	{
		setDescription(getContext(), description);
	}

	/**
	 * Set value of Description
	 * @param context
	 * @param description
	 */
	public final void setDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String description)
	{
		getMendixObject().setValue(context, MemberNames.Description.toString(), description);
	}

	/**
	 * @return value of VersionNumber
	 */
	public final java.lang.Integer getVersionNumber()
	{
		return getVersionNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of VersionNumber
	 */
	public final java.lang.Integer getVersionNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.VersionNumber.toString());
	}

	/**
	 * Set value of VersionNumber
	 * @param versionnumber
	 */
	public final void setVersionNumber(java.lang.Integer versionnumber)
	{
		setVersionNumber(getContext(), versionnumber);
	}

	/**
	 * Set value of VersionNumber
	 * @param context
	 * @param versionnumber
	 */
	public final void setVersionNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer versionnumber)
	{
		getMendixObject().setValue(context, MemberNames.VersionNumber.toString(), versionnumber);
	}

	/**
	 * @return value of UUID
	 */
	public final java.lang.String getUUID()
	{
		return getUUID(getContext());
	}

	/**
	 * @param context
	 * @return value of UUID
	 */
	public final java.lang.String getUUID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.UUID.toString());
	}

	/**
	 * Set value of UUID
	 * @param uuid
	 */
	public final void setUUID(java.lang.String uuid)
	{
		setUUID(getContext(), uuid);
	}

	/**
	 * Set value of UUID
	 * @param context
	 * @param uuid
	 */
	public final void setUUID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String uuid)
	{
		getMendixObject().setValue(context, MemberNames.UUID.toString(), uuid);
	}

	/**
	 * @return value of SystemPrompt
	 */
	public final java.lang.String getSystemPrompt()
	{
		return getSystemPrompt(getContext());
	}

	/**
	 * @param context
	 * @return value of SystemPrompt
	 */
	public final java.lang.String getSystemPrompt(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SystemPrompt.toString());
	}

	/**
	 * Set value of SystemPrompt
	 * @param systemprompt
	 */
	public final void setSystemPrompt(java.lang.String systemprompt)
	{
		setSystemPrompt(getContext(), systemprompt);
	}

	/**
	 * Set value of SystemPrompt
	 * @param context
	 * @param systemprompt
	 */
	public final void setSystemPrompt(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String systemprompt)
	{
		getMendixObject().setValue(context, MemberNames.SystemPrompt.toString(), systemprompt);
	}

	/**
	 * @return value of UserPrompt
	 */
	public final java.lang.String getUserPrompt()
	{
		return getUserPrompt(getContext());
	}

	/**
	 * @param context
	 * @return value of UserPrompt
	 */
	public final java.lang.String getUserPrompt(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.UserPrompt.toString());
	}

	/**
	 * Set value of UserPrompt
	 * @param userprompt
	 */
	public final void setUserPrompt(java.lang.String userprompt)
	{
		setUserPrompt(getContext(), userprompt);
	}

	/**
	 * Set value of UserPrompt
	 * @param context
	 * @param userprompt
	 */
	public final void setUserPrompt(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String userprompt)
	{
		getMendixObject().setValue(context, MemberNames.UserPrompt.toString(), userprompt);
	}

	/**
	 * @return value of VersionOwner
	 */
	public final java.lang.String getVersionOwner()
	{
		return getVersionOwner(getContext());
	}

	/**
	 * @param context
	 * @return value of VersionOwner
	 */
	public final java.lang.String getVersionOwner(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.VersionOwner.toString());
	}

	/**
	 * Set value of VersionOwner
	 * @param versionowner
	 */
	public final void setVersionOwner(java.lang.String versionowner)
	{
		setVersionOwner(getContext(), versionowner);
	}

	/**
	 * Set value of VersionOwner
	 * @param context
	 * @param versionowner
	 */
	public final void setVersionOwner(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String versionowner)
	{
		getMendixObject().setValue(context, MemberNames.VersionOwner.toString(), versionowner);
	}

	/**
	 * @return value of VersionChangedDate
	 */
	public final java.util.Date getVersionChangedDate()
	{
		return getVersionChangedDate(getContext());
	}

	/**
	 * @param context
	 * @return value of VersionChangedDate
	 */
	public final java.util.Date getVersionChangedDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.VersionChangedDate.toString());
	}

	/**
	 * Set value of VersionChangedDate
	 * @param versionchangeddate
	 */
	public final void setVersionChangedDate(java.util.Date versionchangeddate)
	{
		setVersionChangedDate(getContext(), versionchangeddate);
	}

	/**
	 * Set value of VersionChangedDate
	 * @param context
	 * @param versionchangeddate
	 */
	public final void setVersionChangedDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date versionchangeddate)
	{
		getMendixObject().setValue(context, MemberNames.VersionChangedDate.toString(), versionchangeddate);
	}

	/**
	 * @return value of LastChangedBy
	 */
	public final java.lang.String getLastChangedBy()
	{
		return getLastChangedBy(getContext());
	}

	/**
	 * @param context
	 * @return value of LastChangedBy
	 */
	public final java.lang.String getLastChangedBy(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.LastChangedBy.toString());
	}

	/**
	 * Set value of LastChangedBy
	 * @param lastchangedby
	 */
	public final void setLastChangedBy(java.lang.String lastchangedby)
	{
		setLastChangedBy(getContext(), lastchangedby);
	}

	/**
	 * Set value of LastChangedBy
	 * @param context
	 * @param lastchangedby
	 */
	public final void setLastChangedBy(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String lastchangedby)
	{
		getMendixObject().setValue(context, MemberNames.LastChangedBy.toString(), lastchangedby);
	}

	/**
	 * @return value of IsDraftVersion
	 */
	public final java.lang.Boolean getIsDraftVersion()
	{
		return getIsDraftVersion(getContext());
	}

	/**
	 * @param context
	 * @return value of IsDraftVersion
	 */
	public final java.lang.Boolean getIsDraftVersion(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsDraftVersion.toString());
	}

	/**
	 * Set value of IsDraftVersion
	 * @param isdraftversion
	 */
	public final void setIsDraftVersion(java.lang.Boolean isdraftversion)
	{
		setIsDraftVersion(getContext(), isdraftversion);
	}

	/**
	 * Set value of IsDraftVersion
	 * @param context
	 * @param isdraftversion
	 */
	public final void setIsDraftVersion(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isdraftversion)
	{
		getMendixObject().setValue(context, MemberNames.IsDraftVersion.toString(), isdraftversion);
	}

	/**
	 * Get value of ToolChoice
	 * @param toolchoice
	 */
	public final genaicommons.proxies.ENUM_ToolChoice getToolChoice()
	{
		return getToolChoice(getContext());
	}

	/**
	 * @param context
	 * @return value of ToolChoice
	 */
	public final genaicommons.proxies.ENUM_ToolChoice getToolChoice(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.ToolChoice.toString());
		if (obj == null) {
			return null;
		}
		return genaicommons.proxies.ENUM_ToolChoice.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of ToolChoice
	 * @param toolchoice
	 */
	public final void setToolChoice(genaicommons.proxies.ENUM_ToolChoice toolchoice)
	{
		setToolChoice(getContext(), toolchoice);
	}

	/**
	 * Set value of ToolChoice
	 * @param context
	 * @param toolchoice
	 */
	public final void setToolChoice(com.mendix.systemwideinterfaces.core.IContext context, genaicommons.proxies.ENUM_ToolChoice toolchoice)
	{
		if (toolchoice != null) {
			getMendixObject().setValue(context, MemberNames.ToolChoice.toString(), toolchoice.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.ToolChoice.toString(), null);
		}
	}

	/**
	 * @return value of Temperature
	 */
	public final java.math.BigDecimal getTemperature()
	{
		return getTemperature(getContext());
	}

	/**
	 * @param context
	 * @return value of Temperature
	 */
	public final java.math.BigDecimal getTemperature(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Temperature.toString());
	}

	/**
	 * Set value of Temperature
	 * @param temperature
	 */
	public final void setTemperature(java.math.BigDecimal temperature)
	{
		setTemperature(getContext(), temperature);
	}

	/**
	 * Set value of Temperature
	 * @param context
	 * @param temperature
	 */
	public final void setTemperature(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal temperature)
	{
		getMendixObject().setValue(context, MemberNames.Temperature.toString(), temperature);
	}

	/**
	 * @return value of MaxTokens
	 */
	public final java.lang.Integer getMaxTokens()
	{
		return getMaxTokens(getContext());
	}

	/**
	 * @param context
	 * @return value of MaxTokens
	 */
	public final java.lang.Integer getMaxTokens(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.MaxTokens.toString());
	}

	/**
	 * Set value of MaxTokens
	 * @param maxtokens
	 */
	public final void setMaxTokens(java.lang.Integer maxtokens)
	{
		setMaxTokens(getContext(), maxtokens);
	}

	/**
	 * Set value of MaxTokens
	 * @param context
	 * @param maxtokens
	 */
	public final void setMaxTokens(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer maxtokens)
	{
		getMendixObject().setValue(context, MemberNames.MaxTokens.toString(), maxtokens);
	}

	/**
	 * @return value of TopP
	 */
	public final java.math.BigDecimal getTopP()
	{
		return getTopP(getContext());
	}

	/**
	 * @param context
	 * @return value of TopP
	 */
	public final java.math.BigDecimal getTopP(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.TopP.toString());
	}

	/**
	 * Set value of TopP
	 * @param topp
	 */
	public final void setTopP(java.math.BigDecimal topp)
	{
		setTopP(getContext(), topp);
	}

	/**
	 * Set value of TopP
	 * @param context
	 * @param topp
	 */
	public final void setTopP(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal topp)
	{
		getMendixObject().setValue(context, MemberNames.TopP.toString(), topp);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Version_Agent
	 */
	public final agentcommons.proxies.Agent getVersion_Agent() throws com.mendix.core.CoreException
	{
		return getVersion_Agent(getContext());
	}

	/**
	 * @param context
	 * @return value of Version_Agent
	 * @throws com.mendix.core.CoreException
	 */
	public final agentcommons.proxies.Agent getVersion_Agent(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		agentcommons.proxies.Agent result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Version_Agent.toString());
		if (identifier != null) {
			result = agentcommons.proxies.Agent.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Version_Agent
	 * @param version_agent
	 */
	public final void setVersion_Agent(agentcommons.proxies.Agent version_agent)
	{
		setVersion_Agent(getContext(), version_agent);
	}

	/**
	 * Set value of Version_Agent
	 * @param context
	 * @param version_agent
	 */
	public final void setVersion_Agent(com.mendix.systemwideinterfaces.core.IContext context, agentcommons.proxies.Agent version_agent)
	{
		if (version_agent == null) {
			getMendixObject().setValue(context, MemberNames.Version_Agent.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Version_Agent.toString(), version_agent.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Version_ToolChoice
	 */
	public final agentcommons.proxies.Tool getVersion_ToolChoice() throws com.mendix.core.CoreException
	{
		return getVersion_ToolChoice(getContext());
	}

	/**
	 * @param context
	 * @return value of Version_ToolChoice
	 * @throws com.mendix.core.CoreException
	 */
	public final agentcommons.proxies.Tool getVersion_ToolChoice(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		agentcommons.proxies.Tool result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Version_ToolChoice.toString());
		if (identifier != null) {
			result = agentcommons.proxies.Tool.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Version_ToolChoice
	 * @param version_toolchoice
	 */
	public final void setVersion_ToolChoice(agentcommons.proxies.Tool version_toolchoice)
	{
		setVersion_ToolChoice(getContext(), version_toolchoice);
	}

	/**
	 * Set value of Version_ToolChoice
	 * @param context
	 * @param version_toolchoice
	 */
	public final void setVersion_ToolChoice(com.mendix.systemwideinterfaces.core.IContext context, agentcommons.proxies.Tool version_toolchoice)
	{
		if (version_toolchoice == null) {
			getMendixObject().setValue(context, MemberNames.Version_ToolChoice.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Version_ToolChoice.toString(), version_toolchoice.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Version_DeployedModel
	 */
	public final genaicommons.proxies.DeployedModel getVersion_DeployedModel() throws com.mendix.core.CoreException
	{
		return getVersion_DeployedModel(getContext());
	}

	/**
	 * @param context
	 * @return value of Version_DeployedModel
	 * @throws com.mendix.core.CoreException
	 */
	public final genaicommons.proxies.DeployedModel getVersion_DeployedModel(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		genaicommons.proxies.DeployedModel result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Version_DeployedModel.toString());
		if (identifier != null) {
			result = genaicommons.proxies.DeployedModel.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Version_DeployedModel
	 * @param version_deployedmodel
	 */
	public final void setVersion_DeployedModel(genaicommons.proxies.DeployedModel version_deployedmodel)
	{
		setVersion_DeployedModel(getContext(), version_deployedmodel);
	}

	/**
	 * Set value of Version_DeployedModel
	 * @param context
	 * @param version_deployedmodel
	 */
	public final void setVersion_DeployedModel(com.mendix.systemwideinterfaces.core.IContext context, genaicommons.proxies.DeployedModel version_deployedmodel)
	{
		if (version_deployedmodel == null) {
			getMendixObject().setValue(context, MemberNames.Version_DeployedModel.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Version_DeployedModel.toString(), version_deployedmodel.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return versionMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final agentcommons.proxies.Version that = (agentcommons.proxies.Version) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
