// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package awsauthentication.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the AWSAuthentication module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Credentials_ValidateBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("AWSAuthentication.ACT_Credentials_Validate");
		return builder;
	}

	public static void aCT_Credentials_Validate(IContext context)
	{
		aCT_Credentials_ValidateBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Settings_DeleteBuilder(
		awsauthentication.proxies.Settings _settings
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("AWSAuthentication.ACT_Settings_Delete");
		builder = builder.withParam("Settings", _settings);
		return builder;
	}

	public static void aCT_Settings_Delete(
		IContext context,
		awsauthentication.proxies.Settings _settings
	)
	{
		aCT_Settings_DeleteBuilder(
				_settings
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Settings_NewEditBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("AWSAuthentication.ACT_Settings_NewEdit");
		return builder;
	}

	public static void aCT_Settings_NewEdit(IContext context)
	{
		aCT_Settings_NewEditBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Settings_SaveBuilder(
		awsauthentication.proxies.Settings _settings
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("AWSAuthentication.ACT_Settings_Save");
		builder = builder.withParam("Settings", _settings);
		return builder;
	}

	public static boolean aCT_Settings_Save(
		IContext context,
		awsauthentication.proxies.Settings _settings
	)
	{
		Object result = aCT_Settings_SaveBuilder(
				_settings
			)
			.execute(context);
		return (boolean) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder assumeRoleBuilder(
		awsauthentication.proxies.AssumeRoleRequest _assumeRoleRequest
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("AWSAuthentication.AssumeRole");
		builder = builder.withParam("AssumeRoleRequest", _assumeRoleRequest);
		return builder;
	}

	public static awsauthentication.proxies.AssumeRoleResponse assumeRole(
		IContext context,
		awsauthentication.proxies.AssumeRoleRequest _assumeRoleRequest
	)
	{
		Object result = assumeRoleBuilder(
				_assumeRoleRequest
			)
			.execute(context);
		return result == null ? null : awsauthentication.proxies.AssumeRoleResponse.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder assumeRoleResponse_GetTemporaryCredentialsBuilder(
		awsauthentication.proxies.AssumeRoleResponse _assumeRoleResponse
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("AWSAuthentication.AssumeRoleResponse_GetTemporaryCredentials");
		builder = builder.withParam("AssumeRoleResponse", _assumeRoleResponse);
		return builder;
	}

	public static awsauthentication.proxies.TemporaryCredentials assumeRoleResponse_GetTemporaryCredentials(
		IContext context,
		awsauthentication.proxies.AssumeRoleResponse _assumeRoleResponse
	)
	{
		Object result = assumeRoleResponse_GetTemporaryCredentialsBuilder(
				_assumeRoleResponse
			)
			.execute(context);
		return result == null ? null : awsauthentication.proxies.TemporaryCredentials.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder credentials_CreateBuilder(
		java.lang.String _accessKey,
		java.lang.String _secretAccessKey
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("AWSAuthentication.Credentials_Create");
		builder = builder.withParam("AccessKey", _accessKey);
		builder = builder.withParam("SecretAccessKey", _secretAccessKey);
		return builder;
	}

	public static awsauthentication.proxies.Credentials credentials_Create(
		IContext context,
		java.lang.String _accessKey,
		java.lang.String _secretAccessKey
	)
	{
		Object result = credentials_CreateBuilder(
				_accessKey,
				_secretAccessKey
			)
			.execute(context);
		return result == null ? null : awsauthentication.proxies.Credentials.initialize(context, (IMendixObject) result);
	}
	/**
	 * This microflow takes values for Region (ENUM_Region) and UseStaticCredentials (boolean) as input and returns a credentials object of the specified type.
	 */
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder getCredentialsBuilder(
		boolean _useStaticCredentials,
		awsauthentication.proxies.ENUM_Region _eNUM_Region
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("AWSAuthentication.GetCredentials");
		builder = builder.withParam("UseStaticCredentials", _useStaticCredentials);
		builder = builder.withParam("ENUM_Region", _eNUM_Region == null ? null : _eNUM_Region.name());
		return builder;
	}

	/**
	 * This microflow takes values for Region (ENUM_Region) and UseStaticCredentials (boolean) as input and returns a credentials object of the specified type.
	 */
	public static awsauthentication.proxies.Credentials getCredentials(
		IContext context,
		boolean _useStaticCredentials,
		awsauthentication.proxies.ENUM_Region _eNUM_Region
	)
	{
		Object result = getCredentialsBuilder(
				_useStaticCredentials,
				_eNUM_Region
			)
			.execute(context);
		return result == null ? null : awsauthentication.proxies.Credentials.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder getRegionBuilder(
		awsauthentication.proxies.ENUM_Region _region
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("AWSAuthentication.GetRegion");
		builder = builder.withParam("Region", _region == null ? null : _region.name());
		return builder;
	}

	public static java.lang.String getRegion(
		IContext context,
		awsauthentication.proxies.ENUM_Region _region
	)
	{
		Object result = getRegionBuilder(
				_region
			)
			.execute(context);
		return (java.lang.String) result;
	}
	/**
	 * The AWS Authentication GetSigV4Headers action allows you to sign your REST calls using AWS' SignatureV4. To do so, add the values for the attributes as headers into your invocation.
	 * 
	 * The following parameters are required:
	 * - SigV4Builder (Object)
	 * - Credentials (Object)
	 * 
	 * This action returns an object of type SigV4Headers.
	 */
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder getSigV4HeadersBuilder(
		awsauthentication.proxies.Credentials _credentials,
		awsauthentication.proxies.SigV4Builder _sigV4Builder,
		java.util.List<awsauthentication.proxies.SigV4Parameter> _sigV4HeaderParameterList,
		java.util.List<awsauthentication.proxies.SigV4Parameter> _sigV4QueryParameterList
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("AWSAuthentication.GetSigV4Headers");
		builder = builder.withParam("Credentials", _credentials);
		builder = builder.withParam("SigV4Builder", _sigV4Builder);
		builder = builder.withParam("SigV4HeaderParameterList", _sigV4HeaderParameterList);
		builder = builder.withParam("SigV4QueryParameterList", _sigV4QueryParameterList);
		return builder;
	}

	/**
	 * The AWS Authentication GetSigV4Headers action allows you to sign your REST calls using AWS' SignatureV4. To do so, add the values for the attributes as headers into your invocation.
	 * 
	 * The following parameters are required:
	 * - SigV4Builder (Object)
	 * - Credentials (Object)
	 * 
	 * This action returns an object of type SigV4Headers.
	 */
	public static awsauthentication.proxies.SigV4Headers getSigV4Headers(
		IContext context,
		awsauthentication.proxies.Credentials _credentials,
		awsauthentication.proxies.SigV4Builder _sigV4Builder,
		java.util.List<awsauthentication.proxies.SigV4Parameter> _sigV4HeaderParameterList,
		java.util.List<awsauthentication.proxies.SigV4Parameter> _sigV4QueryParameterList
	)
	{
		Object result = getSigV4HeadersBuilder(
				_credentials,
				_sigV4Builder,
				_sigV4HeaderParameterList,
				_sigV4QueryParameterList
			)
			.execute(context);
		return result == null ? null : awsauthentication.proxies.SigV4Headers.initialize(context, (IMendixObject) result);
	}
	/**
	 * The AWS Authentication GetStaticCredentials action allows you to generate an object of type Credentials allowing for authentication using static credentials.
	 * 
	 * For testing and development purposes the static authentication should suffice, but for production environments we strongly urge you to use temporary credentials..
	 * 
	 * This action returns an object of type Credentials.
	 */
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder getStaticCredentialsBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("AWSAuthentication.GetStaticCredentials");
		return builder;
	}

	/**
	 * The AWS Authentication GetStaticCredentials action allows you to generate an object of type Credentials allowing for authentication using static credentials.
	 * 
	 * For testing and development purposes the static authentication should suffice, but for production environments we strongly urge you to use temporary credentials..
	 * 
	 * This action returns an object of type Credentials.
	 */
	public static awsauthentication.proxies.Credentials getStaticCredentials(IContext context)
	{
		Object result = getStaticCredentialsBuilder().execute(context);
		return result == null ? null : awsauthentication.proxies.Credentials.initialize(context, (IMendixObject) result);
	}
	/**
	 * The AWS Authentication GetTemporaryCredentials action allows you to generate an object of type TemporaryCredentials allowing for authentication using temporary credentials.
	 * 
	 * For testing and development purposes the static authentication should suffice, but for production environments we strongly urge you to use temporary credentials..
	 * 
	 * The following parameters are required:
	 * - Region (Enumeration)
	 * 
	 * This action returns an object of type TemporaryCredentials.
	 */
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder getTemporaryCredentialsBuilder(
		awsauthentication.proxies.ENUM_Region _region
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("AWSAuthentication.GetTemporaryCredentials");
		builder = builder.withParam("Region", _region == null ? null : _region.name());
		return builder;
	}

	/**
	 * The AWS Authentication GetTemporaryCredentials action allows you to generate an object of type TemporaryCredentials allowing for authentication using temporary credentials.
	 * 
	 * For testing and development purposes the static authentication should suffice, but for production environments we strongly urge you to use temporary credentials..
	 * 
	 * The following parameters are required:
	 * - Region (Enumeration)
	 * 
	 * This action returns an object of type TemporaryCredentials.
	 */
	public static awsauthentication.proxies.Credentials getTemporaryCredentials(
		IContext context,
		awsauthentication.proxies.ENUM_Region _region
	)
	{
		Object result = getTemporaryCredentialsBuilder(
				_region
			)
			.execute(context);
		return result == null ? null : awsauthentication.proxies.Credentials.initialize(context, (IMendixObject) result);
	}
	/**
	 * The Validate Credentials operation performs a GetCallerIdentity call to the AWS Security Token Service (AWS STS). 
	 * 
	 * It returns true, if a caller identity was found and thus the used credentials are valid. This doesn't indicate which services can be accessed with the credentials.
	 * 
	 * See also: https://docs.aws.amazon.com/STS/latest/APIReference/API_GetCallerIdentity.html
	 */
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder pOST_v1_GetCallerIdentity_ValidateCredentialsBuilder(
		awsauthentication.proxies.Credentials _credentials,
		awsauthentication.proxies.ENUM_Region _eNUM_Region
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("AWSAuthentication.POST_v1_GetCallerIdentity_ValidateCredentials");
		builder = builder.withParam("Credentials", _credentials);
		builder = builder.withParam("ENUM_Region", _eNUM_Region == null ? null : _eNUM_Region.name());
		return builder;
	}

	/**
	 * The Validate Credentials operation performs a GetCallerIdentity call to the AWS Security Token Service (AWS STS). 
	 * 
	 * It returns true, if a caller identity was found and thus the used credentials are valid. This doesn't indicate which services can be accessed with the credentials.
	 * 
	 * See also: https://docs.aws.amazon.com/STS/latest/APIReference/API_GetCallerIdentity.html
	 */
	public static boolean pOST_v1_GetCallerIdentity_ValidateCredentials(
		IContext context,
		awsauthentication.proxies.Credentials _credentials,
		awsauthentication.proxies.ENUM_Region _eNUM_Region
	)
	{
		Object result = pOST_v1_GetCallerIdentity_ValidateCredentialsBuilder(
				_credentials,
				_eNUM_Region
			)
			.execute(context);
		return (boolean) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder settings_CommitBuilder(
		awsauthentication.proxies.Settings _settings
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("AWSAuthentication.Settings_Commit");
		builder = builder.withParam("Settings", _settings);
		return builder;
	}

	public static void settings_Commit(
		IContext context,
		awsauthentication.proxies.Settings _settings
	)
	{
		settings_CommitBuilder(
				_settings
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder settings_DeleteBuilder(
		awsauthentication.proxies.Settings _settings
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("AWSAuthentication.Settings_Delete");
		builder = builder.withParam("Settings", _settings);
		return builder;
	}

	public static void settings_Delete(
		IContext context,
		awsauthentication.proxies.Settings _settings
	)
	{
		settings_DeleteBuilder(
				_settings
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder settings_GetCreateBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("AWSAuthentication.Settings_GetCreate");
		return builder;
	}

	public static awsauthentication.proxies.Settings settings_GetCreate(IContext context)
	{
		Object result = settings_GetCreateBuilder().execute(context);
		return result == null ? null : awsauthentication.proxies.Settings.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder settings_ValidateBuilder(
		awsauthentication.proxies.Settings _settings
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("AWSAuthentication.Settings_Validate");
		builder = builder.withParam("Settings", _settings);
		return builder;
	}

	public static boolean settings_Validate(
		IContext context,
		awsauthentication.proxies.Settings _settings
	)
	{
		Object result = settings_ValidateBuilder(
				_settings
			)
			.execute(context);
		return (boolean) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sigV4Headers_GetForGetCallerIdentityBuilder(
		awsauthentication.proxies.ENUM_Region _eNUM_Region,
		awsauthentication.proxies.Credentials _credentials
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("AWSAuthentication.SigV4Headers_GetForGetCallerIdentity");
		builder = builder.withParam("ENUM_Region", _eNUM_Region == null ? null : _eNUM_Region.name());
		builder = builder.withParam("Credentials", _credentials);
		return builder;
	}

	public static awsauthentication.proxies.SigV4Headers sigV4Headers_GetForGetCallerIdentity(
		IContext context,
		awsauthentication.proxies.ENUM_Region _eNUM_Region,
		awsauthentication.proxies.Credentials _credentials
	)
	{
		Object result = sigV4Headers_GetForGetCallerIdentityBuilder(
				_eNUM_Region,
				_credentials
			)
			.execute(context);
		return result == null ? null : awsauthentication.proxies.SigV4Headers.initialize(context, (IMendixObject) result);
	}
	/**
	 * This microflow will create the request that will be used to call the consumeRolesAnywhere REST call. It then gets the temporary credentials from the response and returns this as a credentials object.
	 */
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder temporaryCredentials_CreateBuilder(
		awsauthentication.proxies.ENUM_Region _region,
		java.lang.String _trustAnchorARN,
		java.lang.String _roleARN,
		java.lang.String _clientCertificateID,
		java.lang.String _profileARN,
		java.lang.String _sessionName,
		java.lang.Long _duration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("AWSAuthentication.TemporaryCredentials_Create");
		builder = builder.withParam("Region", _region == null ? null : _region.name());
		builder = builder.withParam("TrustAnchorARN", _trustAnchorARN);
		builder = builder.withParam("RoleARN", _roleARN);
		builder = builder.withParam("ClientCertificateID", _clientCertificateID);
		builder = builder.withParam("ProfileARN", _profileARN);
		builder = builder.withParam("SessionName", _sessionName);
		builder = builder.withParam("Duration", _duration);
		return builder;
	}

	/**
	 * This microflow will create the request that will be used to call the consumeRolesAnywhere REST call. It then gets the temporary credentials from the response and returns this as a credentials object.
	 */
	public static awsauthentication.proxies.TemporaryCredentials temporaryCredentials_Create(
		IContext context,
		awsauthentication.proxies.ENUM_Region _region,
		java.lang.String _trustAnchorARN,
		java.lang.String _roleARN,
		java.lang.String _clientCertificateID,
		java.lang.String _profileARN,
		java.lang.String _sessionName,
		java.lang.Long _duration
	)
	{
		Object result = temporaryCredentials_CreateBuilder(
				_region,
				_trustAnchorARN,
				_roleARN,
				_clientCertificateID,
				_profileARN,
				_sessionName,
				_duration
			)
			.execute(context);
		return result == null ? null : awsauthentication.proxies.TemporaryCredentials.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder validateEnvironmentVariablesBuilder(
		boolean _useStaticCredentials
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("AWSAuthentication.ValidateEnvironmentVariables");
		builder = builder.withParam("UseStaticCredentials", _useStaticCredentials);
		return builder;
	}

	public static java.lang.String validateEnvironmentVariables(
		IContext context,
		boolean _useStaticCredentials
	)
	{
		Object result = validateEnvironmentVariablesBuilder(
				_useStaticCredentials
			)
			.execute(context);
		return (java.lang.String) result;
	}
}
