// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mcpclient.proxies;

/**
 * One ore multiple (optional) audience objects may be associated to the message indicating the intended audience(s) for this resource. Valid values are "user" and "assistant".
 */
public class Audience implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject audienceMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MCPClient.Audience";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Role("Role"),
		Audience_PromptMessage("MCPClient.Audience_PromptMessage");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Audience(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Audience(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject audienceMendixObject)
	{
		if (audienceMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!audienceMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.audienceMendixObject = audienceMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static mcpclient.proxies.Audience initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new mcpclient.proxies.Audience(context, mendixObject);
	}

	public static mcpclient.proxies.Audience load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return mcpclient.proxies.Audience.initialize(context, mendixObject);
	}

	/**
	 * @return value of Role
	 */
	public final java.lang.String getRole()
	{
		return getRole(getContext());
	}

	/**
	 * @param context
	 * @return value of Role
	 */
	public final java.lang.String getRole(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Role.toString());
	}

	/**
	 * Set value of Role
	 * @param role
	 */
	public final void setRole(java.lang.String role)
	{
		setRole(getContext(), role);
	}

	/**
	 * Set value of Role
	 * @param context
	 * @param role
	 */
	public final void setRole(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String role)
	{
		getMendixObject().setValue(context, MemberNames.Role.toString(), role);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Audience_PromptMessage
	 */
	public final mcpclient.proxies.PromptMessage getAudience_PromptMessage() throws com.mendix.core.CoreException
	{
		return getAudience_PromptMessage(getContext());
	}

	/**
	 * @param context
	 * @return value of Audience_PromptMessage
	 * @throws com.mendix.core.CoreException
	 */
	public final mcpclient.proxies.PromptMessage getAudience_PromptMessage(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		mcpclient.proxies.PromptMessage result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Audience_PromptMessage.toString());
		if (identifier != null) {
			result = mcpclient.proxies.PromptMessage.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Audience_PromptMessage
	 * @param audience_promptmessage
	 */
	public final void setAudience_PromptMessage(mcpclient.proxies.PromptMessage audience_promptmessage)
	{
		setAudience_PromptMessage(getContext(), audience_promptmessage);
	}

	/**
	 * Set value of Audience_PromptMessage
	 * @param context
	 * @param audience_promptmessage
	 */
	public final void setAudience_PromptMessage(com.mendix.systemwideinterfaces.core.IContext context, mcpclient.proxies.PromptMessage audience_promptmessage)
	{
		if (audience_promptmessage == null) {
			getMendixObject().setValue(context, MemberNames.Audience_PromptMessage.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Audience_PromptMessage.toString(), audience_promptmessage.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return audienceMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final mcpclient.proxies.Audience that = (mcpclient.proxies.Audience) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
