// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mcpclient.proxies;

/**
 * An EnumValue is created for each value of the argument, if the ToolArgument is a list of (enum) values. Only string values are supported.
 */
public class EnumValue implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject enumValueMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MCPClient.EnumValue";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Key("Key"),
		EnumValue_ToolArgument("MCPClient.EnumValue_ToolArgument");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public EnumValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected EnumValue(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject enumValueMendixObject)
	{
		if (enumValueMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!enumValueMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.enumValueMendixObject = enumValueMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static mcpclient.proxies.EnumValue initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new mcpclient.proxies.EnumValue(context, mendixObject);
	}

	public static mcpclient.proxies.EnumValue load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return mcpclient.proxies.EnumValue.initialize(context, mendixObject);
	}

	/**
	 * @return value of Key
	 */
	public final java.lang.String getKey()
	{
		return getKey(getContext());
	}

	/**
	 * @param context
	 * @return value of Key
	 */
	public final java.lang.String getKey(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Key.toString());
	}

	/**
	 * Set value of Key
	 * @param key
	 */
	public final void setKey(java.lang.String key)
	{
		setKey(getContext(), key);
	}

	/**
	 * Set value of Key
	 * @param context
	 * @param key
	 */
	public final void setKey(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String key)
	{
		getMendixObject().setValue(context, MemberNames.Key.toString(), key);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of EnumValue_ToolArgument
	 */
	public final mcpclient.proxies.ToolArgument getEnumValue_ToolArgument() throws com.mendix.core.CoreException
	{
		return getEnumValue_ToolArgument(getContext());
	}

	/**
	 * @param context
	 * @return value of EnumValue_ToolArgument
	 * @throws com.mendix.core.CoreException
	 */
	public final mcpclient.proxies.ToolArgument getEnumValue_ToolArgument(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		mcpclient.proxies.ToolArgument result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.EnumValue_ToolArgument.toString());
		if (identifier != null) {
			result = mcpclient.proxies.ToolArgument.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of EnumValue_ToolArgument
	 * @param enumvalue_toolargument
	 */
	public final void setEnumValue_ToolArgument(mcpclient.proxies.ToolArgument enumvalue_toolargument)
	{
		setEnumValue_ToolArgument(getContext(), enumvalue_toolargument);
	}

	/**
	 * Set value of EnumValue_ToolArgument
	 * @param context
	 * @param enumvalue_toolargument
	 */
	public final void setEnumValue_ToolArgument(com.mendix.systemwideinterfaces.core.IContext context, mcpclient.proxies.ToolArgument enumvalue_toolargument)
	{
		if (enumvalue_toolargument == null) {
			getMendixObject().setValue(context, MemberNames.EnumValue_ToolArgument.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.EnumValue_ToolArgument.toString(), enumvalue_toolargument.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return enumValueMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final mcpclient.proxies.EnumValue that = (mcpclient.proxies.EnumValue) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
