// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mcpclient.proxies;

public enum ENUM_SyncState
{
	Synced("abe9ecca-6625-4e48-85fd-6fbf39bd423d"),
	Syncing("ca38827d-d7bd-4d44-9418-67caeb66d812"),
	Not_synced("a52b672e-8784-42b0-994b-52d84e34a790");

	private final java.lang.String i18nCaptionKey;
	
	private ENUM_SyncState(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
