// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mcpclient.proxies;

/**
 * ListPromptsResult gets created via the "List Prompts Result" action and may contain one or multiple Prompts associated.
 */
public class ListPromptsResult implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject listPromptsResultMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MCPClient.ListPromptsResult";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		NextCursor("NextCursor");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ListPromptsResult(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ListPromptsResult(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject listPromptsResultMendixObject)
	{
		if (listPromptsResultMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!listPromptsResultMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.listPromptsResultMendixObject = listPromptsResultMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static mcpclient.proxies.ListPromptsResult initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new mcpclient.proxies.ListPromptsResult(context, mendixObject);
	}

	public static mcpclient.proxies.ListPromptsResult load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return mcpclient.proxies.ListPromptsResult.initialize(context, mendixObject);
	}

	/**
	 * @return value of NextCursor
	 */
	public final java.lang.String getNextCursor()
	{
		return getNextCursor(getContext());
	}

	/**
	 * @param context
	 * @return value of NextCursor
	 */
	public final java.lang.String getNextCursor(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.NextCursor.toString());
	}

	/**
	 * Set value of NextCursor
	 * @param nextcursor
	 */
	public final void setNextCursor(java.lang.String nextcursor)
	{
		setNextCursor(getContext(), nextcursor);
	}

	/**
	 * Set value of NextCursor
	 * @param context
	 * @param nextcursor
	 */
	public final void setNextCursor(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String nextcursor)
	{
		getMendixObject().setValue(context, MemberNames.NextCursor.toString(), nextcursor);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return listPromptsResultMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final mcpclient.proxies.ListPromptsResult that = (mcpclient.proxies.ListPromptsResult) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
