// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mcpclient.proxies;

/**
 * The MCPClient is created via the "Create MCP Client" action. The object needs to be passed to every other action that interacts with the MCP server. You can close the connection and clean up the registry via the "Close MCP Client" action.
 */
public class MCPClient implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject mCPClientMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MCPClient.MCPClient";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		MCPEndpoint("MCPEndpoint"),
		Connected("Connected");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public MCPClient(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected MCPClient(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mCPClientMendixObject)
	{
		if (mCPClientMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!mCPClientMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.mCPClientMendixObject = mCPClientMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static mcpclient.proxies.MCPClient initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new mcpclient.proxies.MCPClient(context, mendixObject);
	}

	public static mcpclient.proxies.MCPClient load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return mcpclient.proxies.MCPClient.initialize(context, mendixObject);
	}

	/**
	 * @return value of MCPEndpoint
	 */
	public final java.lang.String getMCPEndpoint()
	{
		return getMCPEndpoint(getContext());
	}

	/**
	 * @param context
	 * @return value of MCPEndpoint
	 */
	public final java.lang.String getMCPEndpoint(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MCPEndpoint.toString());
	}

	/**
	 * Set value of MCPEndpoint
	 * @param mcpendpoint
	 */
	public final void setMCPEndpoint(java.lang.String mcpendpoint)
	{
		setMCPEndpoint(getContext(), mcpendpoint);
	}

	/**
	 * Set value of MCPEndpoint
	 * @param context
	 * @param mcpendpoint
	 */
	public final void setMCPEndpoint(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String mcpendpoint)
	{
		getMendixObject().setValue(context, MemberNames.MCPEndpoint.toString(), mcpendpoint);
	}

	/**
	 * @return value of Connected
	 */
	public final java.lang.Boolean getConnected()
	{
		return getConnected(getContext());
	}

	/**
	 * @param context
	 * @return value of Connected
	 */
	public final java.lang.Boolean getConnected(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Connected.toString());
	}

	/**
	 * Set value of Connected
	 * @param connected
	 */
	public final void setConnected(java.lang.Boolean connected)
	{
		setConnected(getContext(), connected);
	}

	/**
	 * Set value of Connected
	 * @param context
	 * @param connected
	 */
	public final void setConnected(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean connected)
	{
		getMendixObject().setValue(context, MemberNames.Connected.toString(), connected);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return mCPClientMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final mcpclient.proxies.MCPClient that = (mcpclient.proxies.MCPClient) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
