// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mcpclient.proxies;

/**
 * The MCPClientConfig object is used as an input to create the MCP Client object which connects to an MCP Server.
 * You can add HttpHeaders via the "Config: Add Http Header" action to pass those as part of the request to the server (e.g., for authentication purposes).
 */
public class MCPClientConfig implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject mCPClientConfigMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MCPClient.MCPClientConfig";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		MCPEndpoint("MCPEndpoint"),
		Name("Name"),
		Version("Version"),
		ProtocolVersion("ProtocolVersion"),
		MCPClientConfig_HttpHeader("MCPClient.MCPClientConfig_HttpHeader");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public MCPClientConfig(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected MCPClientConfig(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mCPClientConfigMendixObject)
	{
		if (mCPClientConfigMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!mCPClientConfigMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.mCPClientConfigMendixObject = mCPClientConfigMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static mcpclient.proxies.MCPClientConfig initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new mcpclient.proxies.MCPClientConfig(context, mendixObject);
	}

	public static mcpclient.proxies.MCPClientConfig load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return mcpclient.proxies.MCPClientConfig.initialize(context, mendixObject);
	}

	/**
	 * @return value of MCPEndpoint
	 */
	public final java.lang.String getMCPEndpoint()
	{
		return getMCPEndpoint(getContext());
	}

	/**
	 * @param context
	 * @return value of MCPEndpoint
	 */
	public final java.lang.String getMCPEndpoint(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MCPEndpoint.toString());
	}

	/**
	 * Set value of MCPEndpoint
	 * @param mcpendpoint
	 */
	public final void setMCPEndpoint(java.lang.String mcpendpoint)
	{
		setMCPEndpoint(getContext(), mcpendpoint);
	}

	/**
	 * Set value of MCPEndpoint
	 * @param context
	 * @param mcpendpoint
	 */
	public final void setMCPEndpoint(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String mcpendpoint)
	{
		getMendixObject().setValue(context, MemberNames.MCPEndpoint.toString(), mcpendpoint);
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of Version
	 */
	public final java.lang.String getVersion()
	{
		return getVersion(getContext());
	}

	/**
	 * @param context
	 * @return value of Version
	 */
	public final java.lang.String getVersion(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Version.toString());
	}

	/**
	 * Set value of Version
	 * @param version
	 */
	public final void setVersion(java.lang.String version)
	{
		setVersion(getContext(), version);
	}

	/**
	 * Set value of Version
	 * @param context
	 * @param version
	 */
	public final void setVersion(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String version)
	{
		getMendixObject().setValue(context, MemberNames.Version.toString(), version);
	}

	/**
	 * Get value of ProtocolVersion
	 * @param protocolversion
	 */
	public final mcpclient.proxies.ENUM_ProtocolVersion getProtocolVersion()
	{
		return getProtocolVersion(getContext());
	}

	/**
	 * @param context
	 * @return value of ProtocolVersion
	 */
	public final mcpclient.proxies.ENUM_ProtocolVersion getProtocolVersion(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.ProtocolVersion.toString());
		if (obj == null) {
			return null;
		}
		return mcpclient.proxies.ENUM_ProtocolVersion.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of ProtocolVersion
	 * @param protocolversion
	 */
	public final void setProtocolVersion(mcpclient.proxies.ENUM_ProtocolVersion protocolversion)
	{
		setProtocolVersion(getContext(), protocolversion);
	}

	/**
	 * Set value of ProtocolVersion
	 * @param context
	 * @param protocolversion
	 */
	public final void setProtocolVersion(com.mendix.systemwideinterfaces.core.IContext context, mcpclient.proxies.ENUM_ProtocolVersion protocolversion)
	{
		if (protocolversion != null) {
			getMendixObject().setValue(context, MemberNames.ProtocolVersion.toString(), protocolversion.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.ProtocolVersion.toString(), null);
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of MCPClientConfig_HttpHeader
	 */
	public final java.util.List<system.proxies.HttpHeader> getMCPClientConfig_HttpHeader() throws com.mendix.core.CoreException
	{
		return getMCPClientConfig_HttpHeader(getContext());
	}

	/**
	 * @param context
	 * @return value of MCPClientConfig_HttpHeader
	 * @throws com.mendix.core.CoreException
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<system.proxies.HttpHeader> getMCPClientConfig_HttpHeader(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<system.proxies.HttpHeader> result = new java.util.ArrayList<>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.MCPClientConfig_HttpHeader.toString());
		if (valueObject == null) {
			return result;
		}
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject)) {
			result.add(system.proxies.HttpHeader.initialize(context, mendixObject));
		}
		return result;
	}

	/**
	 * Set value of MCPClientConfig_HttpHeader
	 * @param mcpclientconfig_httpheader
	 */
	public final void setMCPClientConfig_HttpHeader(java.util.List<system.proxies.HttpHeader> mcpclientconfig_httpheader)
	{
		setMCPClientConfig_HttpHeader(getContext(), mcpclientconfig_httpheader);
	}

	/**
	 * Set value of MCPClientConfig_HttpHeader
	 * @param context
	 * @param mcpclientconfig_httpheader
	 */
	public final void setMCPClientConfig_HttpHeader(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<system.proxies.HttpHeader> mcpclientconfig_httpheader)
	{
		var identifiers = mcpclientconfig_httpheader
			.stream()
			.map(proxyObject -> proxyObject.getMendixObject().getId())
			.collect(java.util.stream.Collectors.toList());
		
		getMendixObject().setValue(context, MemberNames.MCPClientConfig_HttpHeader.toString(), identifiers);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return mCPClientConfigMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final mcpclient.proxies.MCPClientConfig that = (mcpclient.proxies.MCPClientConfig) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
