// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mcpclient.proxies;

/**
 * The configuration object contains all the information required to create an MCP client that connects to the MCP server.
 */
public class MCPServerConfiguration implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject mCPServerConfigurationMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MCPClient.MCPServerConfiguration";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		MCPEndpoint("MCPEndpoint"),
		Name("Name"),
		Version("Version"),
		ProtocolVersion("ProtocolVersion"),
		GetCredentialsMicroflow("GetCredentialsMicroflow"),
		SyncState("SyncState");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public MCPServerConfiguration(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected MCPServerConfiguration(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mCPServerConfigurationMendixObject)
	{
		if (mCPServerConfigurationMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!mCPServerConfigurationMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.mCPServerConfigurationMendixObject = mCPServerConfigurationMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static mcpclient.proxies.MCPServerConfiguration initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new mcpclient.proxies.MCPServerConfiguration(context, mendixObject);
	}

	public static mcpclient.proxies.MCPServerConfiguration load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return mcpclient.proxies.MCPServerConfiguration.initialize(context, mendixObject);
	}

	public static java.util.List<mcpclient.proxies.MCPServerConfiguration> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> mcpclient.proxies.MCPServerConfiguration.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of MCPEndpoint
	 */
	public final java.lang.String getMCPEndpoint()
	{
		return getMCPEndpoint(getContext());
	}

	/**
	 * @param context
	 * @return value of MCPEndpoint
	 */
	public final java.lang.String getMCPEndpoint(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MCPEndpoint.toString());
	}

	/**
	 * Set value of MCPEndpoint
	 * @param mcpendpoint
	 */
	public final void setMCPEndpoint(java.lang.String mcpendpoint)
	{
		setMCPEndpoint(getContext(), mcpendpoint);
	}

	/**
	 * Set value of MCPEndpoint
	 * @param context
	 * @param mcpendpoint
	 */
	public final void setMCPEndpoint(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String mcpendpoint)
	{
		getMendixObject().setValue(context, MemberNames.MCPEndpoint.toString(), mcpendpoint);
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of Version
	 */
	public final java.lang.String getVersion()
	{
		return getVersion(getContext());
	}

	/**
	 * @param context
	 * @return value of Version
	 */
	public final java.lang.String getVersion(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Version.toString());
	}

	/**
	 * Set value of Version
	 * @param version
	 */
	public final void setVersion(java.lang.String version)
	{
		setVersion(getContext(), version);
	}

	/**
	 * Set value of Version
	 * @param context
	 * @param version
	 */
	public final void setVersion(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String version)
	{
		getMendixObject().setValue(context, MemberNames.Version.toString(), version);
	}

	/**
	 * Get value of ProtocolVersion
	 * @param protocolversion
	 */
	public final mcpclient.proxies.ENUM_ProtocolVersion getProtocolVersion()
	{
		return getProtocolVersion(getContext());
	}

	/**
	 * @param context
	 * @return value of ProtocolVersion
	 */
	public final mcpclient.proxies.ENUM_ProtocolVersion getProtocolVersion(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.ProtocolVersion.toString());
		if (obj == null) {
			return null;
		}
		return mcpclient.proxies.ENUM_ProtocolVersion.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of ProtocolVersion
	 * @param protocolversion
	 */
	public final void setProtocolVersion(mcpclient.proxies.ENUM_ProtocolVersion protocolversion)
	{
		setProtocolVersion(getContext(), protocolversion);
	}

	/**
	 * Set value of ProtocolVersion
	 * @param context
	 * @param protocolversion
	 */
	public final void setProtocolVersion(com.mendix.systemwideinterfaces.core.IContext context, mcpclient.proxies.ENUM_ProtocolVersion protocolversion)
	{
		if (protocolversion != null) {
			getMendixObject().setValue(context, MemberNames.ProtocolVersion.toString(), protocolversion.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.ProtocolVersion.toString(), null);
		}
	}

	/**
	 * @return value of GetCredentialsMicroflow
	 */
	public final java.lang.String getGetCredentialsMicroflow()
	{
		return getGetCredentialsMicroflow(getContext());
	}

	/**
	 * @param context
	 * @return value of GetCredentialsMicroflow
	 */
	public final java.lang.String getGetCredentialsMicroflow(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.GetCredentialsMicroflow.toString());
	}

	/**
	 * Set value of GetCredentialsMicroflow
	 * @param getcredentialsmicroflow
	 */
	public final void setGetCredentialsMicroflow(java.lang.String getcredentialsmicroflow)
	{
		setGetCredentialsMicroflow(getContext(), getcredentialsmicroflow);
	}

	/**
	 * Set value of GetCredentialsMicroflow
	 * @param context
	 * @param getcredentialsmicroflow
	 */
	public final void setGetCredentialsMicroflow(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String getcredentialsmicroflow)
	{
		getMendixObject().setValue(context, MemberNames.GetCredentialsMicroflow.toString(), getcredentialsmicroflow);
	}

	/**
	 * Get value of SyncState
	 * @param syncstate
	 */
	public final mcpclient.proxies.ENUM_SyncState getSyncState()
	{
		return getSyncState(getContext());
	}

	/**
	 * @param context
	 * @return value of SyncState
	 */
	public final mcpclient.proxies.ENUM_SyncState getSyncState(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.SyncState.toString());
		if (obj == null) {
			return null;
		}
		return mcpclient.proxies.ENUM_SyncState.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of SyncState
	 * @param syncstate
	 */
	public final void setSyncState(mcpclient.proxies.ENUM_SyncState syncstate)
	{
		setSyncState(getContext(), syncstate);
	}

	/**
	 * Set value of SyncState
	 * @param context
	 * @param syncstate
	 */
	public final void setSyncState(com.mendix.systemwideinterfaces.core.IContext context, mcpclient.proxies.ENUM_SyncState syncstate)
	{
		if (syncstate != null) {
			getMendixObject().setValue(context, MemberNames.SyncState.toString(), syncstate.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.SyncState.toString(), null);
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return mCPServerConfigurationMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final mcpclient.proxies.MCPServerConfiguration that = (mcpclient.proxies.MCPServerConfiguration) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
