// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mcpclient.proxies;

/**
 * Tools exposed by the MCP server
 */
public class MCPTool implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject mCPToolMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MCPClient.MCPTool";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		Description("Description"),
		SyncState("SyncState"),
		MCPTool_MCPServerConfiguration("MCPClient.MCPTool_MCPServerConfiguration");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public MCPTool(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected MCPTool(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mCPToolMendixObject)
	{
		if (mCPToolMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!mCPToolMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.mCPToolMendixObject = mCPToolMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static mcpclient.proxies.MCPTool initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new mcpclient.proxies.MCPTool(context, mendixObject);
	}

	public static mcpclient.proxies.MCPTool load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return mcpclient.proxies.MCPTool.initialize(context, mendixObject);
	}

	public static java.util.List<mcpclient.proxies.MCPTool> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> mcpclient.proxies.MCPTool.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of Description
	 */
	public final java.lang.String getDescription()
	{
		return getDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of Description
	 */
	public final java.lang.String getDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Description.toString());
	}

	/**
	 * Set value of Description
	 * @param description
	 */
	public final void setDescription(java.lang.String description)
	{
		setDescription(getContext(), description);
	}

	/**
	 * Set value of Description
	 * @param context
	 * @param description
	 */
	public final void setDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String description)
	{
		getMendixObject().setValue(context, MemberNames.Description.toString(), description);
	}

	/**
	 * Get value of SyncState
	 * @param syncstate
	 */
	public final mcpclient.proxies.ENUM_SyncState getSyncState()
	{
		return getSyncState(getContext());
	}

	/**
	 * @param context
	 * @return value of SyncState
	 */
	public final mcpclient.proxies.ENUM_SyncState getSyncState(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.SyncState.toString());
		if (obj == null) {
			return null;
		}
		return mcpclient.proxies.ENUM_SyncState.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of SyncState
	 * @param syncstate
	 */
	public final void setSyncState(mcpclient.proxies.ENUM_SyncState syncstate)
	{
		setSyncState(getContext(), syncstate);
	}

	/**
	 * Set value of SyncState
	 * @param context
	 * @param syncstate
	 */
	public final void setSyncState(com.mendix.systemwideinterfaces.core.IContext context, mcpclient.proxies.ENUM_SyncState syncstate)
	{
		if (syncstate != null) {
			getMendixObject().setValue(context, MemberNames.SyncState.toString(), syncstate.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.SyncState.toString(), null);
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of MCPTool_MCPServerConfiguration
	 */
	public final mcpclient.proxies.MCPServerConfiguration getMCPTool_MCPServerConfiguration() throws com.mendix.core.CoreException
	{
		return getMCPTool_MCPServerConfiguration(getContext());
	}

	/**
	 * @param context
	 * @return value of MCPTool_MCPServerConfiguration
	 * @throws com.mendix.core.CoreException
	 */
	public final mcpclient.proxies.MCPServerConfiguration getMCPTool_MCPServerConfiguration(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		mcpclient.proxies.MCPServerConfiguration result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.MCPTool_MCPServerConfiguration.toString());
		if (identifier != null) {
			result = mcpclient.proxies.MCPServerConfiguration.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of MCPTool_MCPServerConfiguration
	 * @param mcptool_mcpserverconfiguration
	 */
	public final void setMCPTool_MCPServerConfiguration(mcpclient.proxies.MCPServerConfiguration mcptool_mcpserverconfiguration)
	{
		setMCPTool_MCPServerConfiguration(getContext(), mcptool_mcpserverconfiguration);
	}

	/**
	 * Set value of MCPTool_MCPServerConfiguration
	 * @param context
	 * @param mcptool_mcpserverconfiguration
	 */
	public final void setMCPTool_MCPServerConfiguration(com.mendix.systemwideinterfaces.core.IContext context, mcpclient.proxies.MCPServerConfiguration mcptool_mcpserverconfiguration)
	{
		if (mcptool_mcpserverconfiguration == null) {
			getMendixObject().setValue(context, MemberNames.MCPTool_MCPServerConfiguration.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.MCPTool_MCPServerConfiguration.toString(), mcptool_mcpserverconfiguration.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return mCPToolMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final mcpclient.proxies.MCPTool that = (mcpclient.proxies.MCPTool) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
