// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mcpclient.proxies;

/**
 * Helper entity for the GetCredentialsMicroflow selection
 */
public class MicroflowSelection implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject microflowSelectionMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MCPClient.MicroflowSelection";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		MicroflowSelection_Microflow_Active("MCPClient.MicroflowSelection_Microflow_Active"),
		MicroflowSelection_Microflow("MCPClient.MicroflowSelection_Microflow"),
		MicroflowSelection_MCPServerConfiguration("MCPClient.MicroflowSelection_MCPServerConfiguration");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public MicroflowSelection(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected MicroflowSelection(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject microflowSelectionMendixObject)
	{
		if (microflowSelectionMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!microflowSelectionMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.microflowSelectionMendixObject = microflowSelectionMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static mcpclient.proxies.MicroflowSelection initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new mcpclient.proxies.MicroflowSelection(context, mendixObject);
	}

	public static mcpclient.proxies.MicroflowSelection load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return mcpclient.proxies.MicroflowSelection.initialize(context, mendixObject);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of MicroflowSelection_Microflow_Active
	 */
	public final mcpclient.proxies.Microflow getMicroflowSelection_Microflow_Active() throws com.mendix.core.CoreException
	{
		return getMicroflowSelection_Microflow_Active(getContext());
	}

	/**
	 * @param context
	 * @return value of MicroflowSelection_Microflow_Active
	 * @throws com.mendix.core.CoreException
	 */
	public final mcpclient.proxies.Microflow getMicroflowSelection_Microflow_Active(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		mcpclient.proxies.Microflow result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.MicroflowSelection_Microflow_Active.toString());
		if (identifier != null) {
			result = mcpclient.proxies.Microflow.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of MicroflowSelection_Microflow_Active
	 * @param microflowselection_microflow_active
	 */
	public final void setMicroflowSelection_Microflow_Active(mcpclient.proxies.Microflow microflowselection_microflow_active)
	{
		setMicroflowSelection_Microflow_Active(getContext(), microflowselection_microflow_active);
	}

	/**
	 * Set value of MicroflowSelection_Microflow_Active
	 * @param context
	 * @param microflowselection_microflow_active
	 */
	public final void setMicroflowSelection_Microflow_Active(com.mendix.systemwideinterfaces.core.IContext context, mcpclient.proxies.Microflow microflowselection_microflow_active)
	{
		if (microflowselection_microflow_active == null) {
			getMendixObject().setValue(context, MemberNames.MicroflowSelection_Microflow_Active.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.MicroflowSelection_Microflow_Active.toString(), microflowselection_microflow_active.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of MicroflowSelection_Microflow
	 */
	public final java.util.List<mcpclient.proxies.Microflow> getMicroflowSelection_Microflow() throws com.mendix.core.CoreException
	{
		return getMicroflowSelection_Microflow(getContext());
	}

	/**
	 * @param context
	 * @return value of MicroflowSelection_Microflow
	 * @throws com.mendix.core.CoreException
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<mcpclient.proxies.Microflow> getMicroflowSelection_Microflow(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<mcpclient.proxies.Microflow> result = new java.util.ArrayList<>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.MicroflowSelection_Microflow.toString());
		if (valueObject == null) {
			return result;
		}
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject)) {
			result.add(mcpclient.proxies.Microflow.initialize(context, mendixObject));
		}
		return result;
	}

	/**
	 * Set value of MicroflowSelection_Microflow
	 * @param microflowselection_microflow
	 */
	public final void setMicroflowSelection_Microflow(java.util.List<mcpclient.proxies.Microflow> microflowselection_microflow)
	{
		setMicroflowSelection_Microflow(getContext(), microflowselection_microflow);
	}

	/**
	 * Set value of MicroflowSelection_Microflow
	 * @param context
	 * @param microflowselection_microflow
	 */
	public final void setMicroflowSelection_Microflow(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<mcpclient.proxies.Microflow> microflowselection_microflow)
	{
		var identifiers = microflowselection_microflow
			.stream()
			.map(proxyObject -> proxyObject.getMendixObject().getId())
			.collect(java.util.stream.Collectors.toList());
		
		getMendixObject().setValue(context, MemberNames.MicroflowSelection_Microflow.toString(), identifiers);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of MicroflowSelection_MCPServerConfiguration
	 */
	public final mcpclient.proxies.MCPServerConfiguration getMicroflowSelection_MCPServerConfiguration() throws com.mendix.core.CoreException
	{
		return getMicroflowSelection_MCPServerConfiguration(getContext());
	}

	/**
	 * @param context
	 * @return value of MicroflowSelection_MCPServerConfiguration
	 * @throws com.mendix.core.CoreException
	 */
	public final mcpclient.proxies.MCPServerConfiguration getMicroflowSelection_MCPServerConfiguration(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		mcpclient.proxies.MCPServerConfiguration result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.MicroflowSelection_MCPServerConfiguration.toString());
		if (identifier != null) {
			result = mcpclient.proxies.MCPServerConfiguration.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of MicroflowSelection_MCPServerConfiguration
	 * @param microflowselection_mcpserverconfiguration
	 */
	public final void setMicroflowSelection_MCPServerConfiguration(mcpclient.proxies.MCPServerConfiguration microflowselection_mcpserverconfiguration)
	{
		setMicroflowSelection_MCPServerConfiguration(getContext(), microflowselection_mcpserverconfiguration);
	}

	/**
	 * Set value of MicroflowSelection_MCPServerConfiguration
	 * @param context
	 * @param microflowselection_mcpserverconfiguration
	 */
	public final void setMicroflowSelection_MCPServerConfiguration(com.mendix.systemwideinterfaces.core.IContext context, mcpclient.proxies.MCPServerConfiguration microflowselection_mcpserverconfiguration)
	{
		if (microflowselection_mcpserverconfiguration == null) {
			getMendixObject().setValue(context, MemberNames.MicroflowSelection_MCPServerConfiguration.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.MicroflowSelection_MCPServerConfiguration.toString(), microflowselection_mcpserverconfiguration.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return microflowSelectionMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final mcpclient.proxies.MicroflowSelection that = (mcpclient.proxies.MicroflowSelection) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
