// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mcpclient.proxies;

/**
 * One or multiple PromptMessages can be returned as part of the "Get Prompt" action. This can be used to send to the model directly or preferably expose to the user first to decide if that is the prompt that is desired.
 * 
 * Currently only text content is allowed.
 * 
 * If multiple messages are returned, ensure that is is compatible with the expected request of the model, for example many LLM apis require that the first message needs to be a user message and then alternating between assistant and user while the final message needs to be a user message.
 */
public class PromptMessage implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject promptMessageMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MCPClient.PromptMessage";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Role("Role"),
		Content("Content"),
		Priority("Priority"),
		PromptMessage_PromptResult("MCPClient.PromptMessage_PromptResult");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public PromptMessage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected PromptMessage(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject promptMessageMendixObject)
	{
		if (promptMessageMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!promptMessageMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.promptMessageMendixObject = promptMessageMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static mcpclient.proxies.PromptMessage initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new mcpclient.proxies.PromptMessage(context, mendixObject);
	}

	public static mcpclient.proxies.PromptMessage load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return mcpclient.proxies.PromptMessage.initialize(context, mendixObject);
	}

	/**
	 * @return value of Role
	 */
	public final java.lang.String getRole()
	{
		return getRole(getContext());
	}

	/**
	 * @param context
	 * @return value of Role
	 */
	public final java.lang.String getRole(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Role.toString());
	}

	/**
	 * Set value of Role
	 * @param role
	 */
	public final void setRole(java.lang.String role)
	{
		setRole(getContext(), role);
	}

	/**
	 * Set value of Role
	 * @param context
	 * @param role
	 */
	public final void setRole(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String role)
	{
		getMendixObject().setValue(context, MemberNames.Role.toString(), role);
	}

	/**
	 * @return value of Content
	 */
	public final java.lang.String getContent()
	{
		return getContent(getContext());
	}

	/**
	 * @param context
	 * @return value of Content
	 */
	public final java.lang.String getContent(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Content.toString());
	}

	/**
	 * Set value of Content
	 * @param content
	 */
	public final void setContent(java.lang.String content)
	{
		setContent(getContext(), content);
	}

	/**
	 * Set value of Content
	 * @param context
	 * @param content
	 */
	public final void setContent(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String content)
	{
		getMendixObject().setValue(context, MemberNames.Content.toString(), content);
	}

	/**
	 * @return value of Priority
	 */
	public final java.math.BigDecimal getPriority()
	{
		return getPriority(getContext());
	}

	/**
	 * @param context
	 * @return value of Priority
	 */
	public final java.math.BigDecimal getPriority(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Priority.toString());
	}

	/**
	 * Set value of Priority
	 * @param priority
	 */
	public final void setPriority(java.math.BigDecimal priority)
	{
		setPriority(getContext(), priority);
	}

	/**
	 * Set value of Priority
	 * @param context
	 * @param priority
	 */
	public final void setPriority(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal priority)
	{
		getMendixObject().setValue(context, MemberNames.Priority.toString(), priority);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of PromptMessage_PromptResult
	 */
	public final mcpclient.proxies.PromptResult getPromptMessage_PromptResult() throws com.mendix.core.CoreException
	{
		return getPromptMessage_PromptResult(getContext());
	}

	/**
	 * @param context
	 * @return value of PromptMessage_PromptResult
	 * @throws com.mendix.core.CoreException
	 */
	public final mcpclient.proxies.PromptResult getPromptMessage_PromptResult(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		mcpclient.proxies.PromptResult result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.PromptMessage_PromptResult.toString());
		if (identifier != null) {
			result = mcpclient.proxies.PromptResult.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of PromptMessage_PromptResult
	 * @param promptmessage_promptresult
	 */
	public final void setPromptMessage_PromptResult(mcpclient.proxies.PromptResult promptmessage_promptresult)
	{
		setPromptMessage_PromptResult(getContext(), promptmessage_promptresult);
	}

	/**
	 * Set value of PromptMessage_PromptResult
	 * @param context
	 * @param promptmessage_promptresult
	 */
	public final void setPromptMessage_PromptResult(com.mendix.systemwideinterfaces.core.IContext context, mcpclient.proxies.PromptResult promptmessage_promptresult)
	{
		if (promptmessage_promptresult == null) {
			getMendixObject().setValue(context, MemberNames.PromptMessage_PromptResult.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.PromptMessage_PromptResult.toString(), promptmessage_promptresult.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return promptMessageMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final mcpclient.proxies.PromptMessage that = (mcpclient.proxies.PromptMessage) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
