// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package communitycommons.proxies;

public enum LogLevel
{
	Trace("28b88d41-8188-4e65-bb52-9bb99a7e998e"),
	Debug("6b821c96-7dde-4cd5-b8ae-4a70018580e9"),
	Info("e0d9d312-437e-45cb-b4c8-a3b7aa49c989"),
	Warning("ad3c9f39-2c23-46bf-b803-4482117f9db1"),
	Error("07b315dd-a78e-4eab-bc6a-f85d517fd222"),
	Critical("140d8062-7986-4eb6-8232-5c1f6f7cec22");

	private final java.lang.String i18nCaptionKey;
	
	private LogLevel(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
