// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package communitycommons.proxies;

public enum SanitizerPolicy
{
	BLOCKS("6035bd8f-4b80-4fa9-bb69-994fe377d2c2"),
	FORMATTING("535a5de9-4c15-4f38-b2bf-64daac97e91c"),
	IMAGES("8136c709-de07-4446-8ca0-c00fffeab3f1"),
	LINKS("72e3b32e-94f7-4c4b-a3fa-a74871623f82"),
	STYLES("25288a15-91bc-4684-ae68-f825fbaf8af1"),
	TABLES("4a291627-ec14-4406-8f3b-08519d47002d");

	private final java.lang.String i18nCaptionKey;
	
	private SanitizerPolicy(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
