// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package communitycommons.proxies;

public enum StandardEncodings
{
	US_ASCII("1d30a622-57c1-42bc-9dfe-bacc7db40dbe"),
	ISO_8859_1("1f2cbcf3-e0eb-42e2-9066-19e377cd44bc"),
	UTF_8("77942f84-7967-4fe5-9803-7227351d74bc"),
	UTF_16BE("6cba7e98-2eb0-4041-8e79-ba60c4c8ec2c"),
	UTF_16LE("cfe778ef-98e1-4367-be6c-8c9e18476d51"),
	UTF_16("8c5413b6-cb6e-4e94-9367-8919d4dff4e9");

	private final java.lang.String i18nCaptionKey;
	
	private StandardEncodings(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
