// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package conversationalui.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the ConversationalUI module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_ChatContext_ClearChat_FullScreenChatBuilder(
		conversationalui.proxies.ChatContext _chatContext
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ConversationalUI.ACT_ChatContext_ClearChat_FullScreenChat");
		builder = builder.withParam("ChatContext", _chatContext);
		return builder;
	}

	public static void aCT_ChatContext_ClearChat_FullScreenChat(
		IContext context,
		conversationalui.proxies.ChatContext _chatContext
	)
	{
		aCT_ChatContext_ClearChat_FullScreenChatBuilder(
				_chatContext
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_ChatContext_DeleteBuilder(
		conversationalui.proxies.ChatContext _chatContext
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ConversationalUI.ACT_ChatContext_Delete");
		builder = builder.withParam("ChatContext", _chatContext);
		return builder;
	}

	public static void aCT_ChatContext_Delete(
		IContext context,
		conversationalui.proxies.ChatContext _chatContext
	)
	{
		aCT_ChatContext_DeleteBuilder(
				_chatContext
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_ConversationStarter_FindCupcakeRecipeBuilder(
		conversationalui.proxies.ChatContext _chatContext
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ConversationalUI.ACT_ConversationStarter_FindCupcakeRecipe");
		builder = builder.withParam("ChatContext", _chatContext);
		return builder;
	}

	public static void aCT_ConversationStarter_FindCupcakeRecipe(
		IContext context,
		conversationalui.proxies.ChatContext _chatContext
	)
	{
		aCT_ConversationStarter_FindCupcakeRecipeBuilder(
				_chatContext
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_ConversationStarter_SummarizeMeetingNotesBuilder(
		conversationalui.proxies.ChatContext _chatContext
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ConversationalUI.ACT_ConversationStarter_SummarizeMeetingNotes");
		builder = builder.withParam("ChatContext", _chatContext);
		return builder;
	}

	public static void aCT_ConversationStarter_SummarizeMeetingNotes(
		IContext context,
		conversationalui.proxies.ChatContext _chatContext
	)
	{
		aCT_ConversationStarter_SummarizeMeetingNotesBuilder(
				_chatContext
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_ConversationStarter_WriteLinkedInPostBuilder(
		conversationalui.proxies.ChatContext _chatContext
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ConversationalUI.ACT_ConversationStarter_WriteLinkedInPost");
		builder = builder.withParam("ChatContext", _chatContext);
		return builder;
	}

	public static void aCT_ConversationStarter_WriteLinkedInPost(
		IContext context,
		conversationalui.proxies.ChatContext _chatContext
	)
	{
		aCT_ConversationStarter_WriteLinkedInPostBuilder(
				_chatContext
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_DoNothingBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ConversationalUI.ACT_DoNothing");
		return builder;
	}

	public static void aCT_DoNothing(IContext context)
	{
		aCT_DoNothingBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Filter_RemoveBuilder(
		conversationalui.proxies.Filter _filter
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ConversationalUI.ACT_Filter_Remove");
		builder = builder.withParam("Filter", _filter);
		return builder;
	}

	public static void aCT_Filter_Remove(
		IContext context,
		conversationalui.proxies.Filter _filter
	)
	{
		aCT_Filter_RemoveBuilder(
				_filter
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_SpanTreeView_ShowDetailsBuilder(
		conversationalui.proxies.SpanTreeView _spanTreeView,
		conversationalui.proxies.TraceView _traceView
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ConversationalUI.ACT_SpanTreeView_ShowDetails");
		builder = builder.withParam("SpanTreeView", _spanTreeView);
		builder = builder.withParam("TraceView", _traceView);
		return builder;
	}

	public static void aCT_SpanTreeView_ShowDetails(
		IContext context,
		conversationalui.proxies.SpanTreeView _spanTreeView,
		conversationalui.proxies.TraceView _traceView
	)
	{
		aCT_SpanTreeView_ShowDetailsBuilder(
				_spanTreeView,
				_traceView
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_TokenMonitor_Export_ShowBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ConversationalUI.ACT_TokenMonitor_Export_Show");
		return builder;
	}

	public static void aCT_TokenMonitor_Export_Show(IContext context)
	{
		aCT_TokenMonitor_Export_ShowBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_TokenMonitorSettings_3MBuilder(
		conversationalui.proxies.TokenMonitorSettings _tokenMonitorSettings
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ConversationalUI.ACT_TokenMonitorSettings_3M");
		builder = builder.withParam("TokenMonitorSettings", _tokenMonitorSettings);
		return builder;
	}

	public static void aCT_TokenMonitorSettings_3M(
		IContext context,
		conversationalui.proxies.TokenMonitorSettings _tokenMonitorSettings
	)
	{
		aCT_TokenMonitorSettings_3MBuilder(
				_tokenMonitorSettings
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_TokenMonitorSettings_6MBuilder(
		conversationalui.proxies.TokenMonitorSettings _tokenMonitorSettings
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ConversationalUI.ACT_TokenMonitorSettings_6M");
		builder = builder.withParam("TokenMonitorSettings", _tokenMonitorSettings);
		return builder;
	}

	public static void aCT_TokenMonitorSettings_6M(
		IContext context,
		conversationalui.proxies.TokenMonitorSettings _tokenMonitorSettings
	)
	{
		aCT_TokenMonitorSettings_6MBuilder(
				_tokenMonitorSettings
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_TokenMonitorSettings_AllBuilder(
		conversationalui.proxies.TokenMonitorSettings _tokenMonitorSettings
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ConversationalUI.ACT_TokenMonitorSettings_All");
		builder = builder.withParam("TokenMonitorSettings", _tokenMonitorSettings);
		return builder;
	}

	public static void aCT_TokenMonitorSettings_All(
		IContext context,
		conversationalui.proxies.TokenMonitorSettings _tokenMonitorSettings
	)
	{
		aCT_TokenMonitorSettings_AllBuilder(
				_tokenMonitorSettings
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_TokenMonitorSettings_CustomBuilder(
		conversationalui.proxies.TokenMonitorSettings _tokenMonitorSettings
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ConversationalUI.ACT_TokenMonitorSettings_Custom");
		builder = builder.withParam("TokenMonitorSettings", _tokenMonitorSettings);
		return builder;
	}

	public static void aCT_TokenMonitorSettings_Custom(
		IContext context,
		conversationalui.proxies.TokenMonitorSettings _tokenMonitorSettings
	)
	{
		aCT_TokenMonitorSettings_CustomBuilder(
				_tokenMonitorSettings
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_TokenMonitorSettings_DBuilder(
		conversationalui.proxies.TokenMonitorSettings _tokenMonitorSettings
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ConversationalUI.ACT_TokenMonitorSettings_D");
		builder = builder.withParam("TokenMonitorSettings", _tokenMonitorSettings);
		return builder;
	}

	public static void aCT_TokenMonitorSettings_D(
		IContext context,
		conversationalui.proxies.TokenMonitorSettings _tokenMonitorSettings
	)
	{
		aCT_TokenMonitorSettings_DBuilder(
				_tokenMonitorSettings
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_TokenMonitorSettings_MBuilder(
		conversationalui.proxies.TokenMonitorSettings _tokenMonitorSettings
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ConversationalUI.ACT_TokenMonitorSettings_M");
		builder = builder.withParam("TokenMonitorSettings", _tokenMonitorSettings);
		return builder;
	}

	public static void aCT_TokenMonitorSettings_M(
		IContext context,
		conversationalui.proxies.TokenMonitorSettings _tokenMonitorSettings
	)
	{
		aCT_TokenMonitorSettings_MBuilder(
				_tokenMonitorSettings
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_TokenMonitorSettings_MTDBuilder(
		conversationalui.proxies.TokenMonitorSettings _tokenMonitorSettings
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ConversationalUI.ACT_TokenMonitorSettings_MTD");
		builder = builder.withParam("TokenMonitorSettings", _tokenMonitorSettings);
		return builder;
	}

	public static void aCT_TokenMonitorSettings_MTD(
		IContext context,
		conversationalui.proxies.TokenMonitorSettings _tokenMonitorSettings
	)
	{
		aCT_TokenMonitorSettings_MTDBuilder(
				_tokenMonitorSettings
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_TokenMonitorSettings_WBuilder(
		conversationalui.proxies.TokenMonitorSettings _tokenMonitorSettings
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ConversationalUI.ACT_TokenMonitorSettings_W");
		builder = builder.withParam("TokenMonitorSettings", _tokenMonitorSettings);
		return builder;
	}

	public static void aCT_TokenMonitorSettings_W(
		IContext context,
		conversationalui.proxies.TokenMonitorSettings _tokenMonitorSettings
	)
	{
		aCT_TokenMonitorSettings_WBuilder(
				_tokenMonitorSettings
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Trace_FilterConversationIDBuilder(
		genaicommons.proxies.Trace _trace
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ConversationalUI.ACT_Trace_FilterConversationID");
		builder = builder.withParam("Trace", _trace);
		return builder;
	}

	public static void aCT_Trace_FilterConversationID(
		IContext context,
		genaicommons.proxies.Trace _trace
	)
	{
		aCT_Trace_FilterConversationIDBuilder(
				_trace
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Trace_FilterVersionBuilder(
		genaicommons.proxies.Trace _trace
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ConversationalUI.ACT_Trace_FilterVersion");
		builder = builder.withParam("Trace", _trace);
		return builder;
	}

	public static void aCT_Trace_FilterVersion(
		IContext context,
		genaicommons.proxies.Trace _trace
	)
	{
		aCT_Trace_FilterVersionBuilder(
				_trace
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Trace_OpenVersionBuilder(
		genaicommons.proxies.Trace _trace
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ConversationalUI.ACT_Trace_OpenVersion");
		builder = builder.withParam("Trace", _trace);
		return builder;
	}

	public static void aCT_Trace_OpenVersion(
		IContext context,
		genaicommons.proxies.Trace _trace
	)
	{
		aCT_Trace_OpenVersionBuilder(
				_trace
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_TraceFiltering_6MBuilder(
		conversationalui.proxies.TraceFiltering _traceFiltering
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ConversationalUI.ACT_TraceFiltering_6M");
		builder = builder.withParam("TraceFiltering", _traceFiltering);
		return builder;
	}

	public static void aCT_TraceFiltering_6M(
		IContext context,
		conversationalui.proxies.TraceFiltering _traceFiltering
	)
	{
		aCT_TraceFiltering_6MBuilder(
				_traceFiltering
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_TraceFiltering_ApplyBuilder(
		conversationalui.proxies.TraceFiltering _traceFiltering
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ConversationalUI.ACT_TraceFiltering_Apply");
		builder = builder.withParam("TraceFiltering", _traceFiltering);
		return builder;
	}

	public static void aCT_TraceFiltering_Apply(
		IContext context,
		conversationalui.proxies.TraceFiltering _traceFiltering
	)
	{
		aCT_TraceFiltering_ApplyBuilder(
				_traceFiltering
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_TraceFiltering_CustomBuilder(
		conversationalui.proxies.TraceFiltering _traceFiltering
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ConversationalUI.ACT_TraceFiltering_Custom");
		builder = builder.withParam("TraceFiltering", _traceFiltering);
		return builder;
	}

	public static void aCT_TraceFiltering_Custom(
		IContext context,
		conversationalui.proxies.TraceFiltering _traceFiltering
	)
	{
		aCT_TraceFiltering_CustomBuilder(
				_traceFiltering
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_TraceFiltering_MBuilder(
		conversationalui.proxies.TraceFiltering _traceFiltering
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ConversationalUI.ACT_TraceFiltering_M");
		builder = builder.withParam("TraceFiltering", _traceFiltering);
		return builder;
	}

	public static void aCT_TraceFiltering_M(
		IContext context,
		conversationalui.proxies.TraceFiltering _traceFiltering
	)
	{
		aCT_TraceFiltering_MBuilder(
				_traceFiltering
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_TraceFiltering_ResetBuilder(
		conversationalui.proxies.TraceFiltering _traceFiltering
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ConversationalUI.ACT_TraceFiltering_Reset");
		builder = builder.withParam("TraceFiltering", _traceFiltering);
		return builder;
	}

	public static void aCT_TraceFiltering_Reset(
		IContext context,
		conversationalui.proxies.TraceFiltering _traceFiltering
	)
	{
		aCT_TraceFiltering_ResetBuilder(
				_traceFiltering
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_TraceFiltering_ResetAndCloseBuilder(
		conversationalui.proxies.TraceFiltering _traceFiltering
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ConversationalUI.ACT_TraceFiltering_ResetAndClose");
		builder = builder.withParam("TraceFiltering", _traceFiltering);
		return builder;
	}

	public static void aCT_TraceFiltering_ResetAndClose(
		IContext context,
		conversationalui.proxies.TraceFiltering _traceFiltering
	)
	{
		aCT_TraceFiltering_ResetAndCloseBuilder(
				_traceFiltering
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_TraceFiltering_WBuilder(
		conversationalui.proxies.TraceFiltering _traceFiltering
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ConversationalUI.ACT_TraceFiltering_W");
		builder = builder.withParam("TraceFiltering", _traceFiltering);
		return builder;
	}

	public static void aCT_TraceFiltering_W(
		IContext context,
		conversationalui.proxies.TraceFiltering _traceFiltering
	)
	{
		aCT_TraceFiltering_WBuilder(
				_traceFiltering
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder advancedSettings_GetBuilder(
		conversationalui.proxies.ChatContext _chatContext
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ConversationalUI.AdvancedSettings_Get");
		builder = builder.withParam("ChatContext", _chatContext);
		return builder;
	}

	public static conversationalui.proxies.AdvancedSettings advancedSettings_Get(
		IContext context,
		conversationalui.proxies.ChatContext _chatContext
	)
	{
		Object result = advancedSettings_GetBuilder(
				_chatContext
			)
			.execute(context);
		return result == null ? null : conversationalui.proxies.AdvancedSettings.initialize(context, (IMendixObject) result);
	}
	/**
	 * Can be used after the chat context was created to set the boundaries and default value for advanced settings in the UI.
	 */
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder advancedSettings_GetAndUpdateBuilder(
		conversationalui.proxies.ChatContext _chatContext,
		java.math.BigDecimal _temperatureMin,
		java.math.BigDecimal _temperatureMax
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ConversationalUI.AdvancedSettings_GetAndUpdate");
		builder = builder.withParam("ChatContext", _chatContext);
		builder = builder.withParam("TemperatureMin", _temperatureMin);
		builder = builder.withParam("TemperatureMax", _temperatureMax);
		return builder;
	}

	/**
	 * Can be used after the chat context was created to set the boundaries and default value for advanced settings in the UI.
	 */
	public static conversationalui.proxies.AdvancedSettings advancedSettings_GetAndUpdate(
		IContext context,
		conversationalui.proxies.ChatContext _chatContext,
		java.math.BigDecimal _temperatureMin,
		java.math.BigDecimal _temperatureMax
	)
	{
		Object result = advancedSettings_GetAndUpdateBuilder(
				_chatContext,
				_temperatureMin,
				_temperatureMax
			)
			.execute(context);
		return result == null ? null : conversationalui.proxies.AdvancedSettings.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder advancedSettings_GetCreateBuilder(
		conversationalui.proxies.ChatContext _chatContext
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ConversationalUI.AdvancedSettings_GetCreate");
		builder = builder.withParam("ChatContext", _chatContext);
		return builder;
	}

	public static conversationalui.proxies.AdvancedSettings advancedSettings_GetCreate(
		IContext context,
		conversationalui.proxies.ChatContext _chatContext
	)
	{
		Object result = advancedSettings_GetCreateBuilder(
				_chatContext
			)
			.execute(context);
		return result == null ? null : conversationalui.proxies.AdvancedSettings.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder chatContext_AddMessagesBuilder(
		conversationalui.proxies.ChatContext _chatContext
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ConversationalUI.ChatContext_AddMessages");
		builder = builder.withParam("ChatContext", _chatContext);
		return builder;
	}

	public static void chatContext_AddMessages(
		IContext context,
		conversationalui.proxies.ChatContext _chatContext
	)
	{
		chatContext_AddMessagesBuilder(
				_chatContext
			)
			.execute(context);
	}
	/**
	 * Adds a a single `ProviderConfig` to the chat context and sets it to active.
	 */
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder chatContext_AddProviderConfig_SetActiveBuilder(
		conversationalui.proxies.ChatContext _chatContext,
		conversationalui.proxies.ProviderConfig _providerConfig
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ConversationalUI.ChatContext_AddProviderConfig_SetActive");
		builder = builder.withParam("ChatContext", _chatContext);
		builder = builder.withParam("ProviderConfig", _providerConfig);
		return builder;
	}

	/**
	 * Adds a a single `ProviderConfig` to the chat context and sets it to active.
	 */
	public static void chatContext_AddProviderConfig_SetActive(
		IContext context,
		conversationalui.proxies.ChatContext _chatContext,
		conversationalui.proxies.ProviderConfig _providerConfig
	)
	{
		chatContext_AddProviderConfig_SetActiveBuilder(
				_chatContext,
				_providerConfig
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder chatContext_ChatWithHistory_ActionMicroflowBuilder(
		conversationalui.proxies.ChatContext _chatContext
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ConversationalUI.ChatContext_ChatWithHistory_ActionMicroflow");
		builder = builder.withParam("ChatContext", _chatContext);
		return builder;
	}

	public static boolean chatContext_ChatWithHistory_ActionMicroflow(
		IContext context,
		conversationalui.proxies.ChatContext _chatContext
	)
	{
		Object result = chatContext_ChatWithHistory_ActionMicroflowBuilder(
				_chatContext
			)
			.execute(context);
		return (boolean) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder chatContext_ClearSuggestedUserPromptsBuilder(
		conversationalui.proxies.ChatContext _chatContext
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ConversationalUI.ChatContext_ClearSuggestedUserPrompts");
		builder = builder.withParam("ChatContext", _chatContext);
		return builder;
	}

	public static void chatContext_ClearSuggestedUserPrompts(
		IContext context,
		conversationalui.proxies.ChatContext _chatContext
	)
	{
		chatContext_ClearSuggestedUserPromptsBuilder(
				_chatContext
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder chatContext_CommitBuilder(
		conversationalui.proxies.ChatContext _chatContext
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ConversationalUI.ChatContext_Commit");
		builder = builder.withParam("ChatContext", _chatContext);
		return builder;
	}

	public static void chatContext_Commit(
		IContext context,
		conversationalui.proxies.ChatContext _chatContext
	)
	{
		chatContext_CommitBuilder(
				_chatContext
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder chatContext_CommitProviderConfigListBuilder(
		conversationalui.proxies.ChatContext _chatContext
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ConversationalUI.ChatContext_CommitProviderConfigList");
		builder = builder.withParam("ChatContext", _chatContext);
		return builder;
	}

	public static void chatContext_CommitProviderConfigList(
		IContext context,
		conversationalui.proxies.ChatContext _chatContext
	)
	{
		chatContext_CommitProviderConfigListBuilder(
				_chatContext
			)
			.execute(context);
	}
	/**
	 * Creates and returns a new chat context in status 'Ready'.
	 */
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder chatContext_CreateBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ConversationalUI.ChatContext_Create");
		return builder;
	}

	/**
	 * Creates and returns a new chat context in status 'Ready'.
	 */
	public static conversationalui.proxies.ChatContext chatContext_Create(IContext context)
	{
		Object result = chatContext_CreateBuilder().execute(context);
		return result == null ? null : conversationalui.proxies.ChatContext.initialize(context, (IMendixObject) result);
	}
	/**
	 * Creates a new chat context and sets a given `ProviderConfig` to active.
	 */
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder chatContext_Create_SetProviderConfigBuilder(
		conversationalui.proxies.ProviderConfig _providerConfig
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ConversationalUI.ChatContext_Create_SetProviderConfig");
		builder = builder.withParam("ProviderConfig", _providerConfig);
		return builder;
	}

	/**
	 * Creates a new chat context and sets a given `ProviderConfig` to active.
	 */
	public static conversationalui.proxies.ChatContext chatContext_Create_SetProviderConfig(
		IContext context,
		conversationalui.proxies.ProviderConfig _providerConfig
	)
	{
		Object result = chatContext_Create_SetProviderConfigBuilder(
				_providerConfig
			)
			.execute(context);
		return result == null ? null : conversationalui.proxies.ChatContext.initialize(context, (IMendixObject) result);
	}
	/**
	 * Create a new ChatContext and adds a ProviderConfig to the chat context and sets it to active/selected. In addition, a list of ProviderConfigs can be added to the chat context so that these can be selectable in the UI for the chat user.
	 */
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder chatContext_Create_SetProviderConfigListBuilder(
		java.util.List<conversationalui.proxies.ProviderConfig> _providerConfigList,
		conversationalui.proxies.ProviderConfig _providerConfig_Active
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ConversationalUI.ChatContext_Create_SetProviderConfigList");
		builder = builder.withParam("ProviderConfigList", _providerConfigList);
		builder = builder.withParam("ProviderConfig_Active", _providerConfig_Active);
		return builder;
	}

	/**
	 * Create a new ChatContext and adds a ProviderConfig to the chat context and sets it to active/selected. In addition, a list of ProviderConfigs can be added to the chat context so that these can be selectable in the UI for the chat user.
	 */
	public static conversationalui.proxies.ChatContext chatContext_Create_SetProviderConfigList(
		IContext context,
		java.util.List<conversationalui.proxies.ProviderConfig> _providerConfigList,
		conversationalui.proxies.ProviderConfig _providerConfig_Active
	)
	{
		Object result = chatContext_Create_SetProviderConfigListBuilder(
				_providerConfigList,
				_providerConfig_Active
			)
			.execute(context);
		return result == null ? null : conversationalui.proxies.ChatContext.initialize(context, (IMendixObject) result);
	}
	/**
	 * Deletes a ChatContext.
	 */
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder chatContext_DeleteBuilder(
		conversationalui.proxies.ChatContext _chatContext
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ConversationalUI.ChatContext_Delete");
		builder = builder.withParam("ChatContext", _chatContext);
		return builder;
	}

	/**
	 * Deletes a ChatContext.
	 */
	public static void chatContext_Delete(
		IContext context,
		conversationalui.proxies.ChatContext _chatContext
	)
	{
		chatContext_DeleteBuilder(
				_chatContext
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder chatContext_ExecuteActionBuilder(
		conversationalui.proxies.ChatContext _chatContext
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ConversationalUI.ChatContext_ExecuteAction");
		builder = builder.withParam("ChatContext", _chatContext);
		return builder;
	}

	public static void chatContext_ExecuteAction(
		IContext context,
		conversationalui.proxies.ChatContext _chatContext
	)
	{
		chatContext_ExecuteActionBuilder(
				_chatContext
			)
			.execute(context);
	}
	/**
	 * Gets the current user prompt. Can be used in the ActionMicroflow , because the `CurrentUserPrompt` from the chat context is no longer available and has been moved to a User Message under the ChatContext.
	 */
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder chatContext_GetCurrentUserPromptBuilder(
		conversationalui.proxies.ChatContext _chatContext
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ConversationalUI.ChatContext_GetCurrentUserPrompt");
		builder = builder.withParam("ChatContext", _chatContext);
		return builder;
	}

	/**
	 * Gets the current user prompt. Can be used in the ActionMicroflow , because the `CurrentUserPrompt` from the chat context is no longer available and has been moved to a User Message under the ChatContext.
	 */
	public static java.lang.String chatContext_GetCurrentUserPrompt(
		IContext context,
		conversationalui.proxies.ChatContext _chatContext
	)
	{
		Object result = chatContext_GetCurrentUserPromptBuilder(
				_chatContext
			)
			.execute(context);
		return (java.lang.String) result;
	}
	/**
	 * Default preprocessing microflow that is called before the chat completions action is performed. This is an example and can be used as a starting point to add more logic depending on your usecase.
	 */
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder chatContext_PreprocessingBuilder(
		conversationalui.proxies.ChatContext _chatContext
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ConversationalUI.ChatContext_Preprocessing");
		builder = builder.withParam("ChatContext", _chatContext);
		return builder;
	}

	/**
	 * Default preprocessing microflow that is called before the chat completions action is performed. This is an example and can be used as a starting point to add more logic depending on your usecase.
	 */
	public static genaicommons.proxies.Request chatContext_Preprocessing(
		IContext context,
		conversationalui.proxies.ChatContext _chatContext
	)
	{
		Object result = chatContext_PreprocessingBuilder(
				_chatContext
			)
			.execute(context);
		return result == null ? null : genaicommons.proxies.Request.initialize(context, (IMendixObject) result);
	}
	/**
	 * Sets the ConversationID of the ChatContext.
	 */
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder chatContext_SetConversationIDBuilder(
		java.lang.String _conversationID,
		conversationalui.proxies.ChatContext _chatContext
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ConversationalUI.ChatContext_SetConversationID");
		builder = builder.withParam("ConversationID", _conversationID);
		builder = builder.withParam("ChatContext", _chatContext);
		return builder;
	}

	/**
	 * Sets the ConversationID of the ChatContext.
	 */
	public static void chatContext_SetConversationID(
		IContext context,
		java.lang.String _conversationID,
		conversationalui.proxies.ChatContext _chatContext
	)
	{
		chatContext_SetConversationIDBuilder(
				_conversationID,
				_chatContext
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder chatContext_SetStatusBuilder(
		conversationalui.proxies.ChatContext _chatContext
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ConversationalUI.ChatContext_SetStatus");
		builder = builder.withParam("ChatContext", _chatContext);
		return builder;
	}

	public static void chatContext_SetStatus(
		IContext context,
		conversationalui.proxies.ChatContext _chatContext
	)
	{
		chatContext_SetStatusBuilder(
				_chatContext
			)
			.execute(context);
	}
	/**
	 * Sets the `Topic`of the chat context. Will be used in the history-sidebar to make historical chats recognizable for users.
	 */
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder chatContext_SetTopicBuilder(
		java.lang.String _topic,
		conversationalui.proxies.ChatContext _chatContext,
		boolean _forceOverwrite
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ConversationalUI.ChatContext_SetTopic");
		builder = builder.withParam("Topic", _topic);
		builder = builder.withParam("ChatContext", _chatContext);
		builder = builder.withParam("ForceOverwrite", _forceOverwrite);
		return builder;
	}

	/**
	 * Sets the `Topic`of the chat context. Will be used in the history-sidebar to make historical chats recognizable for users.
	 */
	public static void chatContext_SetTopic(
		IContext context,
		java.lang.String _topic,
		conversationalui.proxies.ChatContext _chatContext,
		boolean _forceOverwrite
	)
	{
		chatContext_SetTopicBuilder(
				_topic,
				_chatContext,
				_forceOverwrite
			)
			.execute(context);
	}
	/**
	 * Will process the response of the model and add the new message and (if present) sources to the ChatContext so that it can be stored in the App and displayed in the UI.
	 */
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder chatContext_UpdateAssistantResponseBuilder(
		conversationalui.proxies.ChatContext _chatContext,
		conversationalui.proxies.ENUM_MessageStatus _messageStatus,
		genaicommons.proxies.Response _response
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ConversationalUI.ChatContext_UpdateAssistantResponse");
		builder = builder.withParam("ChatContext", _chatContext);
		builder = builder.withParam("MessageStatus", _messageStatus == null ? null : _messageStatus.name());
		builder = builder.withParam("Response", _response);
		return builder;
	}

	/**
	 * Will process the response of the model and add the new message and (if present) sources to the ChatContext so that it can be stored in the App and displayed in the UI.
	 */
	public static conversationalui.proxies.Message chatContext_UpdateAssistantResponse(
		IContext context,
		conversationalui.proxies.ChatContext _chatContext,
		conversationalui.proxies.ENUM_MessageStatus _messageStatus,
		genaicommons.proxies.Response _response
	)
	{
		Object result = chatContext_UpdateAssistantResponseBuilder(
				_chatContext,
				_messageStatus,
				_response
			)
			.execute(context);
		return result == null ? null : conversationalui.proxies.Message.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder chatContext_UpdateConversationIdBuilder(
		conversationalui.proxies.ChatContext _chatContext,
		genaicommons.proxies.Response _response
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ConversationalUI.ChatContext_UpdateConversationId");
		builder = builder.withParam("ChatContext", _chatContext);
		builder = builder.withParam("Response", _response);
		return builder;
	}

	public static void chatContext_UpdateConversationId(
		IContext context,
		conversationalui.proxies.ChatContext _chatContext,
		genaicommons.proxies.Response _response
	)
	{
		chatContext_UpdateConversationIdBuilder(
				_chatContext,
				_response
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder chatContext_ValidateBuilder(
		conversationalui.proxies.ChatContext _chatContext
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ConversationalUI.ChatContext_Validate");
		builder = builder.withParam("ChatContext", _chatContext);
		return builder;
	}

	public static boolean chatContext_Validate(
		IContext context,
		conversationalui.proxies.ChatContext _chatContext
	)
	{
		Object result = chatContext_ValidateBuilder(
				_chatContext
			)
			.execute(context);
		return (boolean) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder chatContext_ValidateActiveProviderConfigBuilder(
		conversationalui.proxies.ChatContext _chatContext
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ConversationalUI.ChatContext_ValidateActiveProviderConfig");
		builder = builder.withParam("ChatContext", _chatContext);
		return builder;
	}

	public static boolean chatContext_ValidateActiveProviderConfig(
		IContext context,
		conversationalui.proxies.ChatContext _chatContext
	)
	{
		Object result = chatContext_ValidateActiveProviderConfigBuilder(
				_chatContext
			)
			.execute(context);
		return (boolean) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder chatContext_ValidateAndUpdateBuilder(
		conversationalui.proxies.ChatContext _chatContext
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ConversationalUI.ChatContext_ValidateAndUpdate");
		builder = builder.withParam("ChatContext", _chatContext);
		return builder;
	}

	public static boolean chatContext_ValidateAndUpdate(
		IContext context,
		conversationalui.proxies.ChatContext _chatContext
	)
	{
		Object result = chatContext_ValidateAndUpdateBuilder(
				_chatContext
			)
			.execute(context);
		return (boolean) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder cONV_IntToDisplayString_SIPrefixBuilder(
		java.lang.Long _input
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ConversationalUI.CONV_IntToDisplayString_SIPrefix");
		builder = builder.withParam("Input", _input);
		return builder;
	}

	public static java.lang.String cONV_IntToDisplayString_SIPrefix(
		IContext context,
		java.lang.Long _input
	)
	{
		Object result = cONV_IntToDisplayString_SIPrefixBuilder(
				_input
			)
			.execute(context);
		return (java.lang.String) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_AdvancedSettings_GetCreateBuilder(
		conversationalui.proxies.ChatContext _chatContext
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ConversationalUI.DS_AdvancedSettings_GetCreate");
		builder = builder.withParam("ChatContext", _chatContext);
		return builder;
	}

	public static conversationalui.proxies.AdvancedSettings dS_AdvancedSettings_GetCreate(
		IContext context,
		conversationalui.proxies.ChatContext _chatContext
	)
	{
		Object result = dS_AdvancedSettings_GetCreateBuilder(
				_chatContext
			)
			.execute(context);
		return result == null ? null : conversationalui.proxies.AdvancedSettings.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_ChatContext_GetProviderConfigListBuilder(
		conversationalui.proxies.ChatContext _chatContext
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ConversationalUI.DS_ChatContext_GetProviderConfigList");
		builder = builder.withParam("ChatContext", _chatContext);
		return builder;
	}

	public static java.util.List<conversationalui.proxies.ProviderConfig> dS_ChatContext_GetProviderConfigList(
		IContext context,
		conversationalui.proxies.ChatContext _chatContext
	)
	{
		Object result = dS_ChatContext_GetProviderConfigListBuilder(
				_chatContext
			)
			.execute(context);
		return result == null ? null : com.mendix.utils.ListUtils.map((java.util.List<IMendixObject>) result, obj -> conversationalui.proxies.ProviderConfig.initialize(context, obj));
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_SpanTreeView_GetSubBuilder(
		conversationalui.proxies.SpanTreeView _spanTreeView_Parent,
		genaicommons.proxies.Trace _trace
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ConversationalUI.DS_SpanTreeView_GetSub");
		builder = builder.withParam("SpanTreeView_Parent", _spanTreeView_Parent);
		builder = builder.withParam("Trace", _trace);
		return builder;
	}

	public static java.util.List<conversationalui.proxies.SpanTreeView> dS_SpanTreeView_GetSub(
		IContext context,
		conversationalui.proxies.SpanTreeView _spanTreeView_Parent,
		genaicommons.proxies.Trace _trace
	)
	{
		Object result = dS_SpanTreeView_GetSubBuilder(
				_spanTreeView_Parent,
				_trace
			)
			.execute(context);
		return result == null ? null : com.mendix.utils.ListUtils.map((java.util.List<IMendixObject>) result, obj -> conversationalui.proxies.SpanTreeView.initialize(context, obj));
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_TokenMonitor_UsageListBuilder(
		conversationalui.proxies.TokenMonitorSettings _tokenMonitorSettings
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ConversationalUI.DS_TokenMonitor_UsageList");
		builder = builder.withParam("TokenMonitorSettings", _tokenMonitorSettings);
		return builder;
	}

	public static java.util.List<conversationalui.proxies.UsageBin> dS_TokenMonitor_UsageList(
		IContext context,
		conversationalui.proxies.TokenMonitorSettings _tokenMonitorSettings
	)
	{
		Object result = dS_TokenMonitor_UsageListBuilder(
				_tokenMonitorSettings
			)
			.execute(context);
		return result == null ? null : com.mendix.utils.ListUtils.map((java.util.List<IMendixObject>) result, obj -> conversationalui.proxies.UsageBin.initialize(context, obj));
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_Trace_GetFromFilterBuilder(
		conversationalui.proxies.TraceFiltering _traceFiltering
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ConversationalUI.DS_Trace_GetFromFilter");
		builder = builder.withParam("TraceFiltering", _traceFiltering);
		return builder;
	}

	public static java.util.List<genaicommons.proxies.Trace> dS_Trace_GetFromFilter(
		IContext context,
		conversationalui.proxies.TraceFiltering _traceFiltering
	)
	{
		Object result = dS_Trace_GetFromFilterBuilder(
				_traceFiltering
			)
			.execute(context);
		return result == null ? null : com.mendix.utils.ListUtils.map((java.util.List<IMendixObject>) result, obj -> genaicommons.proxies.Trace.initialize(context, obj));
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_Trace_GetSpanTreeBuilder(
		genaicommons.proxies.Trace _trace
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ConversationalUI.DS_Trace_GetSpanTree");
		builder = builder.withParam("Trace", _trace);
		return builder;
	}

	public static java.util.List<conversationalui.proxies.SpanTreeView> dS_Trace_GetSpanTree(
		IContext context,
		genaicommons.proxies.Trace _trace
	)
	{
		Object result = dS_Trace_GetSpanTreeBuilder(
				_trace
			)
			.execute(context);
		return result == null ? null : com.mendix.utils.ListUtils.map((java.util.List<IMendixObject>) result, obj -> conversationalui.proxies.SpanTreeView.initialize(context, obj));
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_Trace_GetToolCallsBuilder(
		genaicommons.proxies.Trace _trace
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ConversationalUI.DS_Trace_GetToolCalls");
		builder = builder.withParam("Trace", _trace);
		return builder;
	}

	public static conversationalui.proxies.TraceView dS_Trace_GetToolCalls(
		IContext context,
		genaicommons.proxies.Trace _trace
	)
	{
		Object result = dS_Trace_GetToolCallsBuilder(
				_trace
			)
			.execute(context);
		return result == null ? null : conversationalui.proxies.TraceView.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_Trace_GetVersionBuilder(
		genaicommons.proxies.Trace _trace
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ConversationalUI.DS_Trace_GetVersion");
		builder = builder.withParam("Trace", _trace);
		return builder;
	}

	public static agentcommons.proxies.Version dS_Trace_GetVersion(
		IContext context,
		genaicommons.proxies.Trace _trace
	)
	{
		Object result = dS_Trace_GetVersionBuilder(
				_trace
			)
			.execute(context);
		return result == null ? null : agentcommons.proxies.Version.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_Trace_TraceViewBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ConversationalUI.DS_Trace_TraceView");
		return builder;
	}

	public static conversationalui.proxies.TraceView dS_Trace_TraceView(IContext context)
	{
		Object result = dS_Trace_TraceViewBuilder().execute(context);
		return result == null ? null : conversationalui.proxies.TraceView.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_TraceFiltering_GetBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ConversationalUI.DS_TraceFiltering_Get");
		return builder;
	}

	public static conversationalui.proxies.TraceFiltering dS_TraceFiltering_Get(IContext context)
	{
		Object result = dS_TraceFiltering_GetBuilder().execute(context);
		return result == null ? null : conversationalui.proxies.TraceFiltering.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_Version_SelectableObjectsBuilder(
		conversationalui.proxies.TraceFiltering _traceFiltering
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ConversationalUI.DS_Version_SelectableObjects");
		builder = builder.withParam("TraceFiltering", _traceFiltering);
		return builder;
	}

	public static java.util.List<agentcommons.proxies.Version> dS_Version_SelectableObjects(
		IContext context,
		conversationalui.proxies.TraceFiltering _traceFiltering
	)
	{
		Object result = dS_Version_SelectableObjectsBuilder(
				_traceFiltering
			)
			.execute(context);
		return result == null ? null : com.mendix.utils.ListUtils.map((java.util.List<IMendixObject>) result, obj -> agentcommons.proxies.Version.initialize(context, obj));
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder filter_CommitListBuilder(
		java.util.List<conversationalui.proxies.Filter> _filterList
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ConversationalUI.Filter_CommitList");
		builder = builder.withParam("FilterList", _filterList);
		return builder;
	}

	public static void filter_CommitList(
		IContext context,
		java.util.List<conversationalui.proxies.Filter> _filterList
	)
	{
		filter_CommitListBuilder(
				_filterList
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder filter_DeleteBuilder(
		conversationalui.proxies.Filter _filter
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ConversationalUI.Filter_Delete");
		builder = builder.withParam("Filter", _filter);
		return builder;
	}

	public static void filter_Delete(
		IContext context,
		conversationalui.proxies.Filter _filter
	)
	{
		filter_DeleteBuilder(
				_filter
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder filter_DeleteListBuilder(
		java.util.List<conversationalui.proxies.Filter> _filterList
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ConversationalUI.Filter_DeleteList");
		builder = builder.withParam("FilterList", _filterList);
		return builder;
	}

	public static void filter_DeleteList(
		IContext context,
		java.util.List<conversationalui.proxies.Filter> _filterList
	)
	{
		filter_DeleteListBuilder(
				_filterList
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder filter_RemoveBuilder(
		conversationalui.proxies.Filter _filter
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ConversationalUI.Filter_Remove");
		builder = builder.withParam("Filter", _filter);
		return builder;
	}

	public static void filter_Remove(
		IContext context,
		conversationalui.proxies.Filter _filter
	)
	{
		filter_RemoveBuilder(
				_filter
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder filter_RemoveVersionBuilder(
		conversationalui.proxies.TraceFiltering _traceFiltering,
		java.lang.String _filterContent
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ConversationalUI.Filter_RemoveVersion");
		builder = builder.withParam("TraceFiltering", _traceFiltering);
		builder = builder.withParam("FilterContent", _filterContent);
		return builder;
	}

	public static void filter_RemoveVersion(
		IContext context,
		conversationalui.proxies.TraceFiltering _traceFiltering,
		java.lang.String _filterContent
	)
	{
		filter_RemoveVersionBuilder(
				_traceFiltering,
				_filterContent
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder message_AddSourcesBuilder(
		conversationalui.proxies.Message _message,
		java.util.List<genaicommons.proxies.Reference> _referenceList
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ConversationalUI.Message_AddSources");
		builder = builder.withParam("Message", _message);
		builder = builder.withParam("ReferenceList", _referenceList);
		return builder;
	}

	public static void message_AddSources(
		IContext context,
		conversationalui.proxies.Message _message,
		java.util.List<genaicommons.proxies.Reference> _referenceList
	)
	{
		message_AddSourcesBuilder(
				_message,
				_referenceList
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder message_CommitBuilder(
		conversationalui.proxies.Message _message
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ConversationalUI.Message_Commit");
		builder = builder.withParam("Message", _message);
		return builder;
	}

	public static void message_Commit(
		IContext context,
		conversationalui.proxies.Message _message
	)
	{
		message_CommitBuilder(
				_message
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder message_CommitListBuilder(
		java.util.List<conversationalui.proxies.Message> _messageList
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ConversationalUI.Message_CommitList");
		builder = builder.withParam("MessageList", _messageList);
		return builder;
	}

	public static void message_CommitList(
		IContext context,
		java.util.List<conversationalui.proxies.Message> _messageList
	)
	{
		message_CommitListBuilder(
				_messageList
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder message_CreateBuilder(
		conversationalui.proxies.ChatContext _chatContext,
		java.lang.String _content,
		genaicommons.proxies.ENUM_MessageRole _role,
		conversationalui.proxies.ENUM_MessageStatus _messageStatus
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ConversationalUI.Message_Create");
		builder = builder.withParam("ChatContext", _chatContext);
		builder = builder.withParam("Content", _content);
		builder = builder.withParam("Role", _role == null ? null : _role.name());
		builder = builder.withParam("MessageStatus", _messageStatus == null ? null : _messageStatus.name());
		return builder;
	}

	public static conversationalui.proxies.Message message_Create(
		IContext context,
		conversationalui.proxies.ChatContext _chatContext,
		java.lang.String _content,
		genaicommons.proxies.ENUM_MessageRole _role,
		conversationalui.proxies.ENUM_MessageStatus _messageStatus
	)
	{
		Object result = message_CreateBuilder(
				_chatContext,
				_content,
				_role,
				_messageStatus
			)
			.execute(context);
		return result == null ? null : conversationalui.proxies.Message.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder nAV_TokenConsumptionMonitorBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ConversationalUI.NAV_TokenConsumptionMonitor");
		return builder;
	}

	public static void nAV_TokenConsumptionMonitor(IContext context)
	{
		nAV_TokenConsumptionMonitorBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder oCh_TokenMonitorSettings_RefreshBuilder(
		conversationalui.proxies.TokenMonitorSettings _tokenMonitorSettings
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ConversationalUI.OCh_TokenMonitorSettings_Refresh");
		builder = builder.withParam("TokenMonitorSettings", _tokenMonitorSettings);
		return builder;
	}

	public static void oCh_TokenMonitorSettings_Refresh(
		IContext context,
		conversationalui.proxies.TokenMonitorSettings _tokenMonitorSettings
	)
	{
		oCh_TokenMonitorSettings_RefreshBuilder(
				_tokenMonitorSettings
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder oCH_TraceFiltering_CommitBuilder(
		conversationalui.proxies.TraceFiltering _traceFiltering
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ConversationalUI.OCH_TraceFiltering_Commit");
		builder = builder.withParam("TraceFiltering", _traceFiltering);
		return builder;
	}

	public static void oCH_TraceFiltering_Commit(
		IContext context,
		conversationalui.proxies.TraceFiltering _traceFiltering
	)
	{
		oCH_TraceFiltering_CommitBuilder(
				_traceFiltering
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder providerConfig_CommitListBuilder(
		java.util.List<conversationalui.proxies.ProviderConfig> _providerConfigList
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ConversationalUI.ProviderConfig_CommitList");
		builder = builder.withParam("ProviderConfigList", _providerConfigList);
		return builder;
	}

	public static void providerConfig_CommitList(
		IContext context,
		java.util.List<conversationalui.proxies.ProviderConfig> _providerConfigList
	)
	{
		providerConfig_CommitListBuilder(
				_providerConfigList
			)
			.execute(context);
	}
	/**
	 * Will take a ChatContext as input and create GenAICommons.Request object that can be used as input parameter in a "Chat with History" operation.  It will contain all the successful messages of the ChatContext so far.
	 */
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder request_CreateFromChatContextBuilder(
		conversationalui.proxies.ChatContext _chatContext,
		java.lang.String _systemPrompt,
		java.lang.Long _maxTokens,
		java.math.BigDecimal _topP
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ConversationalUI.Request_CreateFromChatContext");
		builder = builder.withParam("ChatContext", _chatContext);
		builder = builder.withParam("SystemPrompt", _systemPrompt);
		builder = builder.withParam("MaxTokens", _maxTokens);
		builder = builder.withParam("TopP", _topP);
		return builder;
	}

	/**
	 * Will take a ChatContext as input and create GenAICommons.Request object that can be used as input parameter in a "Chat with History" operation.  It will contain all the successful messages of the ChatContext so far.
	 */
	public static genaicommons.proxies.Request request_CreateFromChatContext(
		IContext context,
		conversationalui.proxies.ChatContext _chatContext,
		java.lang.String _systemPrompt,
		java.lang.Long _maxTokens,
		java.math.BigDecimal _topP
	)
	{
		Object result = request_CreateFromChatContextBuilder(
				_chatContext,
				_systemPrompt,
				_maxTokens,
				_topP
			)
			.execute(context);
		return result == null ? null : genaicommons.proxies.Request.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder source_CommitListBuilder(
		java.util.List<conversationalui.proxies.Source> _sourceList
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ConversationalUI.Source_CommitList");
		builder = builder.withParam("SourceList", _sourceList);
		return builder;
	}

	public static void source_CommitList(
		IContext context,
		java.util.List<conversationalui.proxies.Source> _sourceList
	)
	{
		source_CommitListBuilder(
				_sourceList
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder source_CreateBuilder(
		conversationalui.proxies.Message _message,
		java.lang.String _title,
		java.lang.String _content,
		java.lang.String _source
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ConversationalUI.Source_Create");
		builder = builder.withParam("Message", _message);
		builder = builder.withParam("Title", _title);
		builder = builder.withParam("Content", _content);
		builder = builder.withParam("Source", _source);
		return builder;
	}

	public static conversationalui.proxies.Source source_Create(
		IContext context,
		conversationalui.proxies.Message _message,
		java.lang.String _title,
		java.lang.String _content,
		java.lang.String _source
	)
	{
		Object result = source_CreateBuilder(
				_message,
				_title,
				_content,
				_source
			)
			.execute(context);
		return result == null ? null : conversationalui.proxies.Source.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder spanTreeView_CreateBuilder(
		conversationalui.proxies.SpanTreeView _spanTreeView_Parent,
		genaicommons.proxies.Span _span
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ConversationalUI.SpanTreeView_Create");
		builder = builder.withParam("SpanTreeView_Parent", _spanTreeView_Parent);
		builder = builder.withParam("Span", _span);
		return builder;
	}

	public static conversationalui.proxies.SpanTreeView spanTreeView_Create(
		IContext context,
		conversationalui.proxies.SpanTreeView _spanTreeView_Parent,
		genaicommons.proxies.Span _span
	)
	{
		Object result = spanTreeView_CreateBuilder(
				_spanTreeView_Parent,
				_span
			)
			.execute(context);
		return result == null ? null : conversationalui.proxies.SpanTreeView.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder spanTreeView_GetAllBuilder(
		conversationalui.proxies.SpanTreeView _spanTreeView
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ConversationalUI.SpanTreeView_GetAll");
		builder = builder.withParam("SpanTreeView", _spanTreeView);
		return builder;
	}

	public static java.util.List<conversationalui.proxies.SpanTreeView> spanTreeView_GetAll(
		IContext context,
		conversationalui.proxies.SpanTreeView _spanTreeView
	)
	{
		Object result = spanTreeView_GetAllBuilder(
				_spanTreeView
			)
			.execute(context);
		return result == null ? null : com.mendix.utils.ListUtils.map((java.util.List<IMendixObject>) result, obj -> conversationalui.proxies.SpanTreeView.initialize(context, obj));
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder spanTreeView_SetAllCopyFalseBuilder(
		conversationalui.proxies.SpanTreeView _spanTreeView
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ConversationalUI.SpanTreeView_SetAllCopyFalse");
		builder = builder.withParam("SpanTreeView", _spanTreeView);
		return builder;
	}

	public static void spanTreeView_SetAllCopyFalse(
		IContext context,
		conversationalui.proxies.SpanTreeView _spanTreeView
	)
	{
		spanTreeView_SetAllCopyFalseBuilder(
				_spanTreeView
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder spanTreeView_SetCopyFalseBuilder(
		conversationalui.proxies.SpanTreeView _spanTreeView
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ConversationalUI.SpanTreeView_SetCopyFalse");
		builder = builder.withParam("SpanTreeView", _spanTreeView);
		return builder;
	}

	public static void spanTreeView_SetCopyFalse(
		IContext context,
		conversationalui.proxies.SpanTreeView _spanTreeView
	)
	{
		spanTreeView_SetCopyFalseBuilder(
				_spanTreeView
			)
			.execute(context);
	}
	/**
	 * Creates a SuggestedUserPrompt  that can start a predefined chat in the interface when clicked.
	 */
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder suggestedUserPrompt_CreateBuilder(
		conversationalui.proxies.ChatContext _chatContext,
		java.lang.String _content
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ConversationalUI.SuggestedUserPrompt_Create");
		builder = builder.withParam("ChatContext", _chatContext);
		builder = builder.withParam("Content", _content);
		return builder;
	}

	/**
	 * Creates a SuggestedUserPrompt  that can start a predefined chat in the interface when clicked.
	 */
	public static void suggestedUserPrompt_Create(
		IContext context,
		conversationalui.proxies.ChatContext _chatContext,
		java.lang.String _content
	)
	{
		suggestedUserPrompt_CreateBuilder(
				_chatContext,
				_content
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder suggestedUserPrompt_DeleteListBuilder(
		java.util.List<conversationalui.proxies.SuggestedUserPrompt> _suggestedUserPromptList
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ConversationalUI.SuggestedUserPrompt_DeleteList");
		builder = builder.withParam("SuggestedUserPromptList", _suggestedUserPromptList);
		return builder;
	}

	public static void suggestedUserPrompt_DeleteList(
		IContext context,
		java.util.List<conversationalui.proxies.SuggestedUserPrompt> _suggestedUserPromptList
	)
	{
		suggestedUserPrompt_DeleteListBuilder(
				_suggestedUserPromptList
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder tokenMonitorSettings_CalculateMonthlyStatsBuilder(
		conversationalui.proxies.TokenMonitorSettings _tokenMonitorSettings
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ConversationalUI.TokenMonitorSettings_CalculateMonthlyStats");
		builder = builder.withParam("TokenMonitorSettings", _tokenMonitorSettings);
		return builder;
	}

	public static void tokenMonitorSettings_CalculateMonthlyStats(
		IContext context,
		conversationalui.proxies.TokenMonitorSettings _tokenMonitorSettings
	)
	{
		tokenMonitorSettings_CalculateMonthlyStatsBuilder(
				_tokenMonitorSettings
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder tokenMonitorSettings_GetGranularityBuilder(
		conversationalui.proxies.TokenMonitorSettings _tokenMonitorSettings
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ConversationalUI.TokenMonitorSettings_GetGranularity");
		builder = builder.withParam("TokenMonitorSettings", _tokenMonitorSettings);
		return builder;
	}

	public static conversationalui.proxies.ENUM_Granularity tokenMonitorSettings_GetGranularity(
		IContext context,
		conversationalui.proxies.TokenMonitorSettings _tokenMonitorSettings
	)
	{
		Object result = tokenMonitorSettings_GetGranularityBuilder(
				_tokenMonitorSettings
			)
			.execute(context);
		return result == null ? null : conversationalui.proxies.ENUM_Granularity.valueOf((java.lang.String) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder tokenMonitorSettings_SetDateFromToBuilder(
		conversationalui.proxies.TokenMonitorSettings _tokenMonitorSettings
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ConversationalUI.TokenMonitorSettings_SetDateFromTo");
		builder = builder.withParam("TokenMonitorSettings", _tokenMonitorSettings);
		return builder;
	}

	public static void tokenMonitorSettings_SetDateFromTo(
		IContext context,
		conversationalui.proxies.TokenMonitorSettings _tokenMonitorSettings
	)
	{
		tokenMonitorSettings_SetDateFromToBuilder(
				_tokenMonitorSettings
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder tokenMonitorSettings_SetDatesAndGranularityBuilder(
		conversationalui.proxies.TokenMonitorSettings _tokenMonitorSettings
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ConversationalUI.TokenMonitorSettings_SetDatesAndGranularity");
		builder = builder.withParam("TokenMonitorSettings", _tokenMonitorSettings);
		return builder;
	}

	public static void tokenMonitorSettings_SetDatesAndGranularity(
		IContext context,
		conversationalui.proxies.TokenMonitorSettings _tokenMonitorSettings
	)
	{
		tokenMonitorSettings_SetDatesAndGranularityBuilder(
				_tokenMonitorSettings
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder trace_GetFromFilterBuilder(
		conversationalui.proxies.TraceFiltering _traceFiltering
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ConversationalUI.Trace_GetFromFilter");
		builder = builder.withParam("TraceFiltering", _traceFiltering);
		return builder;
	}

	public static java.util.List<genaicommons.proxies.Trace> trace_GetFromFilter(
		IContext context,
		conversationalui.proxies.TraceFiltering _traceFiltering
	)
	{
		Object result = trace_GetFromFilterBuilder(
				_traceFiltering
			)
			.execute(context);
		return result == null ? null : com.mendix.utils.ListUtils.map((java.util.List<IMendixObject>) result, obj -> genaicommons.proxies.Trace.initialize(context, obj));
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder trace_GetPageURLBuilder(
		genaicommons.proxies.Trace _trace
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ConversationalUI.Trace_GetPageURL");
		builder = builder.withParam("Trace", _trace);
		return builder;
	}

	public static java.lang.String trace_GetPageURL(
		IContext context,
		genaicommons.proxies.Trace _trace
	)
	{
		Object result = trace_GetPageURLBuilder(
				_trace
			)
			.execute(context);
		return (java.lang.String) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder traceChartView_CreateNewValueBuilder(
		java.util.List<conversationalui.proxies.TraceChartView> _traceChartView_Display,
		conversationalui.proxies.TraceFiltering _traceFiltering,
		java.util.Date _endOfCurrentBin,
		java.util.Date _startOfCurrentBin
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ConversationalUI.TraceChartView_CreateNewValue");
		builder = builder.withParam("TraceChartView_Display", _traceChartView_Display);
		builder = builder.withParam("TraceFiltering", _traceFiltering);
		builder = builder.withParam("EndOfCurrentBin", _endOfCurrentBin);
		builder = builder.withParam("StartOfCurrentBin", _startOfCurrentBin);
		return builder;
	}

	public static void traceChartView_CreateNewValue(
		IContext context,
		java.util.List<conversationalui.proxies.TraceChartView> _traceChartView_Display,
		conversationalui.proxies.TraceFiltering _traceFiltering,
		java.util.Date _endOfCurrentBin,
		java.util.Date _startOfCurrentBin
	)
	{
		traceChartView_CreateNewValueBuilder(
				_traceChartView_Display,
				_traceFiltering,
				_endOfCurrentBin,
				_startOfCurrentBin
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder traceChartView_GetValuesBuilder(
		conversationalui.proxies.TraceFiltering _traceFiltering
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ConversationalUI.TraceChartView_GetValues");
		builder = builder.withParam("TraceFiltering", _traceFiltering);
		return builder;
	}

	public static void traceChartView_GetValues(
		IContext context,
		conversationalui.proxies.TraceFiltering _traceFiltering
	)
	{
		traceChartView_GetValuesBuilder(
				_traceFiltering
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder traceFiltering_AgentFilterBuilder(
		conversationalui.proxies.TraceFiltering _traceFiltering
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ConversationalUI.TraceFiltering_AgentFilter");
		builder = builder.withParam("TraceFiltering", _traceFiltering);
		return builder;
	}

	public static java.util.List<genaicommons.proxies.Trace> traceFiltering_AgentFilter(
		IContext context,
		conversationalui.proxies.TraceFiltering _traceFiltering
	)
	{
		Object result = traceFiltering_AgentFilterBuilder(
				_traceFiltering
			)
			.execute(context);
		return result == null ? null : com.mendix.utils.ListUtils.map((java.util.List<IMendixObject>) result, obj -> genaicommons.proxies.Trace.initialize(context, obj));
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder traceFiltering_CalculateStatsBuilder(
		conversationalui.proxies.TraceFiltering _traceFiltering,
		java.util.List<conversationalui.proxies.TraceChartView> _traceChartViewList
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ConversationalUI.TraceFiltering_CalculateStats");
		builder = builder.withParam("TraceFiltering", _traceFiltering);
		builder = builder.withParam("TraceChartViewList", _traceChartViewList);
		return builder;
	}

	public static void traceFiltering_CalculateStats(
		IContext context,
		conversationalui.proxies.TraceFiltering _traceFiltering,
		java.util.List<conversationalui.proxies.TraceChartView> _traceChartViewList
	)
	{
		traceFiltering_CalculateStatsBuilder(
				_traceFiltering,
				_traceChartViewList
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder traceFiltering_CommitBuilder(
		conversationalui.proxies.TraceFiltering _traceFiltering
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ConversationalUI.TraceFiltering_Commit");
		builder = builder.withParam("TraceFiltering", _traceFiltering);
		return builder;
	}

	public static void traceFiltering_Commit(
		IContext context,
		conversationalui.proxies.TraceFiltering _traceFiltering
	)
	{
		traceFiltering_CommitBuilder(
				_traceFiltering
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder traceFiltering_CreateFilterLabelsBuilder(
		conversationalui.proxies.TraceFiltering _traceFiltering
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ConversationalUI.TraceFiltering_CreateFilterLabels");
		builder = builder.withParam("TraceFiltering", _traceFiltering);
		return builder;
	}

	public static void traceFiltering_CreateFilterLabels(
		IContext context,
		conversationalui.proxies.TraceFiltering _traceFiltering
	)
	{
		traceFiltering_CreateFilterLabelsBuilder(
				_traceFiltering
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder traceFiltering_GetGranularityBuilder(
		conversationalui.proxies.TraceFiltering _traceFiltering
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ConversationalUI.TraceFiltering_GetGranularity");
		builder = builder.withParam("TraceFiltering", _traceFiltering);
		return builder;
	}

	public static conversationalui.proxies.ENUM_Granularity traceFiltering_GetGranularity(
		IContext context,
		conversationalui.proxies.TraceFiltering _traceFiltering
	)
	{
		Object result = traceFiltering_GetGranularityBuilder(
				_traceFiltering
			)
			.execute(context);
		return result == null ? null : conversationalui.proxies.ENUM_Granularity.valueOf((java.lang.String) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder traceFiltering_GetOrCreateBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ConversationalUI.TraceFiltering_GetOrCreate");
		return builder;
	}

	public static conversationalui.proxies.TraceFiltering traceFiltering_GetOrCreate(IContext context)
	{
		Object result = traceFiltering_GetOrCreateBuilder().execute(context);
		return result == null ? null : conversationalui.proxies.TraceFiltering.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder traceFiltering_GetOrCreate_UpdateBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ConversationalUI.TraceFiltering_GetOrCreate_Update");
		return builder;
	}

	public static conversationalui.proxies.TraceFiltering traceFiltering_GetOrCreate_Update(IContext context)
	{
		Object result = traceFiltering_GetOrCreate_UpdateBuilder().execute(context);
		return result == null ? null : conversationalui.proxies.TraceFiltering.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder traceFiltering_ResetBuilder(
		conversationalui.proxies.TraceFiltering _traceFiltering,
		boolean _isFullReset
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ConversationalUI.TraceFiltering_Reset");
		builder = builder.withParam("TraceFiltering", _traceFiltering);
		builder = builder.withParam("IsFullReset", _isFullReset);
		return builder;
	}

	public static void traceFiltering_Reset(
		IContext context,
		conversationalui.proxies.TraceFiltering _traceFiltering,
		boolean _isFullReset
	)
	{
		traceFiltering_ResetBuilder(
				_traceFiltering,
				_isFullReset
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder traceFiltering_SetDateAndGranularityBuilder(
		conversationalui.proxies.TraceFiltering _traceFiltering
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ConversationalUI.TraceFiltering_SetDateAndGranularity");
		builder = builder.withParam("TraceFiltering", _traceFiltering);
		return builder;
	}

	public static void traceFiltering_SetDateAndGranularity(
		IContext context,
		conversationalui.proxies.TraceFiltering _traceFiltering
	)
	{
		traceFiltering_SetDateAndGranularityBuilder(
				_traceFiltering
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder traceFiltering_SetDateFromToBuilder(
		conversationalui.proxies.TraceFiltering _traceFiltering
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ConversationalUI.TraceFiltering_SetDateFromTo");
		builder = builder.withParam("TraceFiltering", _traceFiltering);
		return builder;
	}

	public static void traceFiltering_SetDateFromTo(
		IContext context,
		conversationalui.proxies.TraceFiltering _traceFiltering
	)
	{
		traceFiltering_SetDateFromToBuilder(
				_traceFiltering
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder traceFiltering_UpdateChartValuesBuilder(
		conversationalui.proxies.TraceFiltering _traceFiltering
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ConversationalUI.TraceFiltering_UpdateChartValues");
		builder = builder.withParam("TraceFiltering", _traceFiltering);
		return builder;
	}

	public static void traceFiltering_UpdateChartValues(
		IContext context,
		conversationalui.proxies.TraceFiltering _traceFiltering
	)
	{
		traceFiltering_UpdateChartValuesBuilder(
				_traceFiltering
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder traceFiltering_UpdateFiltersAndCommitBuilder(
		conversationalui.proxies.TraceFiltering _traceFiltering
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ConversationalUI.TraceFiltering_UpdateFiltersAndCommit");
		builder = builder.withParam("TraceFiltering", _traceFiltering);
		return builder;
	}

	public static void traceFiltering_UpdateFiltersAndCommit(
		IContext context,
		conversationalui.proxies.TraceFiltering _traceFiltering
	)
	{
		traceFiltering_UpdateFiltersAndCommitBuilder(
				_traceFiltering
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder traceFiltering_VersionFilterBuilder(
		java.util.List<genaicommons.proxies.Trace> _traceList,
		agentcommons.proxies.Version _iteratorVersion,
		conversationalui.proxies.TraceFiltering _traceFiltering
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ConversationalUI.TraceFiltering_VersionFilter");
		builder = builder.withParam("TraceList", _traceList);
		builder = builder.withParam("IteratorVersion", _iteratorVersion);
		builder = builder.withParam("TraceFiltering", _traceFiltering);
		return builder;
	}

	public static void traceFiltering_VersionFilter(
		IContext context,
		java.util.List<genaicommons.proxies.Trace> _traceList,
		agentcommons.proxies.Version _iteratorVersion,
		conversationalui.proxies.TraceFiltering _traceFiltering
	)
	{
		traceFiltering_VersionFilterBuilder(
				_traceList,
				_iteratorVersion,
				_traceFiltering
			)
			.execute(context);
	}
}
